---
approved: 'no'
fedora_abbrev: ''
fedora_name: License Agreement for Application Response Measurement (ARM) SDK
id: '309'
license_text: ''
name: License Agreement for Application Response Measurement (ARM) SDK
spdx_abbrev: ''
spdx_name: ''
url: https://fedoraproject.org/wiki/Licensing/ApplicationResponseMeasurementSDKLicense
