[license]

expression = [ "" ]
status = "not approved"

text = '''
http://unauthorised.org/dhog/9wm/README
'''

[fedora]

name = [
    "9wm License (Original)"
]

abbreviation = [
    ""
]

notes = '''
The argument that there's a strongly-implied right to modify is unlikely to fly
in many countries outside the US. NOTE: 9wm has since been relicensed to MIT.
'''
