[license]

expression = ""
status = "not approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Agere_LT_Modem_Driver_License
'''

[fedora]

name = [
    "Agere LT Modem Driver License"
]

abbreviation = [
    ""
]

notes = '''
This license is non-free. A copy of this license was obtained from
http://www.mepis.org/node/10356 and is preserved here for reference.
'''
