[license]

expression = [ "" ]
status = "not approved"

text = '''
https://fedoraproject.org/wiki/Licensing/CMigemo
'''

[fedora]

name = [
    "C/Migemo License"
]

abbreviation = [
    ""
]

notes = '''
see notes on page
'''
