[license]

expression = [
    "CC-BY-NC-1.0",
    "CC-BY-NC-2.0",
    "CC-BY-NC-2.5",
    "CC-BY-NC-3.0",
    "CC-BY-NC-3.0-DE",
    "CC-BY-NC-4.0"
]
status = "not approved"

text = '''
http://creativecommons.org/licenses/by-nc/4.0/
'''

[fedora]

name = [
    "Creative Commons Attribution-NonCommercial"
]

abbreviation = [
    ""
]
