[license]

expression = "CC-BY-NC-SA-1.0                 CC-BY-NC-SA-2.0                 CC-BY-NC-SA-2.0-FR                 CC-BY-NC-SA-2.0-UK                 CC-BY-NC-SA-2.5                 CC-BY-NC-SA-3.0                 CC-BY-NC-SA-3.0-DE                 CC-BY-NC-SA-3.0-IGO                 CC-BY-NC-SA-4.0"
status = "not approved"

text = '''
http://creativecommons.org/licenses/by-nc-sa/4.0/
'''

[fedora]

name = [
    "Creative Commons Attribution-NonCommercial-ShareAlike"
]

abbreviation = [
    ""
]
