[license]

expression = [ "" ]
status = "not approved"

text = '''
https://fedoraproject.org/wiki/Licensing/DIP_SIPA_Font_License
'''

[fedora]

name = [
    "DIP SIPA Font License"
]

abbreviation = [
    ""
]

notes = '''
Restrictions on modification
'''
