[license]

expression = ""
status = "not approved"

text = '''
http://pauillac.inria.fr/cdrom_a_graver/www/emc2/copyright.htm
'''

[fedora]

name = [
    "EMC2 License"
]

abbreviation = [
    ""
]

notes = '''
Commercial use restrictions
'''
