[license]

expression = [ "" ]
status = "not approved"

text = '''
http://www.spinwardstars.com/frontier/fal.html
'''

[fedora]

name = [
    "Frontier Artistic License"
]

abbreviation = [
    ""
]

notes = '''
Non-free for the same reasons as regular Artistic 1.0 License
'''
