[license]

expression = ""
status = "not approved"

text = '''
http://www.celepar.pr.gov.br/modules/conteudo/conteudo.php?conteudo=69
'''

[fedora]

name = [
    "GPL for Computer Programs of the Public Administration"
]

abbreviation = [
    ""
]
