[license]

expression = [ "" ]
status = "not approved"

text = '''
http://www.hacktivismo.com/about/hessla.php
'''

[fedora]

name = [
    "Hacktivismo Enhanced-Source Software License Agreement"
]

abbreviation = [
    ""
]
