[license]

expression = ""
status = "not approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Intel_IPW3945_Daemon_License
'''

[fedora]

name = [
    "Intel IPW3945 Daemon License"
]

abbreviation = [
    ""
]

notes = '''
No source permissions, binary EULA  see notes on page
'''
