[license]

expression = ""
status = "not approved"

text = '''
http://www.maiamailguard.org/license.php
'''

[fedora]

name = [
    "Maia Mailguard License"
]

abbreviation = [
    ""
]

notes = '''
broken link
'''
