[license]

expression = ""
status = "not approved"

text = '''
https://nmap.org/npsl/npsl-annotated.html
'''

[fedora]

name = [
    "Nmap Public Source License Version 0.92 (NPSL)"
]

abbreviation = [
    ""
]

notes = '''
The "Proprietary software companies" text in the preamble is a field of use
restriction.
'''
