[license]

expression = ""
status = "not approved"

text = '''
http://opencontent.org/opl.shtml
'''

[fedora]

name = [
    "Open Content License"
]

abbreviation = [
    ""
]

notes = '''
link broken
'''
