[license]

expression = ""
status = "not approved"

text = '''
http://openmap.bbn.com/license.html
'''

[fedora]

name = [
    "Open Map License"
]

abbreviation = [
    ""
]

notes = '''
Derived from Artistic 1.0, has same flaws  review w/Artistic
'''
