[license]

expression = ""
status = "not approved"

text = '''
http://www.azillionmonkeys.com/qed/license-exposition.html
'''

[fedora]

name = [
    "Paul Hsieh Exposition License"
]

abbreviation = [
    ""
]
