[license]

expression = [ "" ]
status = "not approved"

text = '''
http://www.systemc.org/about/org_docs/license/
'''

[fedora]

name = [
    "SystemC Open Source License"
]

abbreviation = [
    ""
]
