# Each file provides information about a single allowed or not-allowed
# Fedora license.  The file format is TOML and the sections are
# described below.  For information on the TOML standard, see
# https://toml.io/en/

# All files must provide a 'license' block.
[license]

# The SPDX expression for this license type in Fedora.
#
#     spdx_expression = "GPL-3.0-or-later WITH Autoconf-exception-3.0"
#
# This expression is constructed using valid SPDX license and
# exception identifiers found at https://spdx.org/
#
# This is a required field.
expression = ""

# The status identifiers for this license expression.  It is an array
# of strings where each string may be any of:
#
#     allowed
#     allowed-content
#     allowed-documentation
#     allowed-fonts
#     allowed-firmware
#     not-allowed
#
# This is a required field.  At least one status is required, but a license
# may have multiple listed for specific "allowed" scenarios 
# (e.g., "allowed-content" and "allowed-documentation").  Note that 
# "not-allowed" should not be combined with any allowed statuses and "allowed"
# need not be combined with any other allowed statuses.
status = [ "" ]

# Optional URL(s) to the license text.  This field is a multiline
# literal string.  For example:
#
#     url = '''
#     https://www.gnu.org/licenses/gpl-3.0-standalone.html
#     https://www.gnu.org/licenses/autoconf-exception-3.0.html
#     '''
#
# This field is optional.
#url = '''
#'''

# Optional full text of the license.  This field is a multiline
# literal string.  For example:
#
#     text = '''
#     Lorem ipsum dolor sit amet, consectetur adipiscing
#     elit. Vestibulum aliquam eros enim, eu tristique nisi tempus
#     et. Nunc erat lacus, consequat eget lacinia eleifend, rutrum a
#     lectus. Aliquam et risus vitae lacus pellentesque
#     pellentesque. Pellentesque facilisis tempor fermentum. Ut id
#     aliquet nisl. Sed tincidunt lorem ut lorem maximus
#     bibendum. Duis hendrerit sem sed nunc faucibus
#     consectetur. Morbi augue tortor, placerat id quam quis, suscipit
#     sodales lacus. Interdum et malesuada fames ac ante ipsum primis
#     in faucibus. Maecenas eu sem volutpat, congue metus ac, finibus
#     sapien. In at quam porta, rutrum augue nec, semper lectus.
#     '''
#
# This field is optional.
#text = '''
#'''

# The 'fedora' block contains additional information specific to the 
# Fedora Project regarding the license.  This section is optional 
# and any o the fields in it are optional.
#[fedora]

# The names Fedora uses to refer to this license.  This field is a
# list of strings.
#name = [
#    "License Full Name",
#    "Another Name For This License"
#]

# The short abbreviations Fedora has used to represent this license in RPM
# packages.  This field is a list of strings.
#abbreviation = [
#    "ShortName",
#    "ShorterName",
#    "AnotherName"
#]

# Any additional notes, history, or other information about this
# license and its use in Fedora.  This field is a multiline literal
# string.
#notes = '''
#'''
