// SPDX-FileCopyrightText: Copyright 2026 Siemens AG
// SPDX-License-Identifier: BSD-3-Clause
// Code generated by go/internal/codegen. DO NOT EDIT.

package licenselynx

var generatedOrgMaps = map[Organization]map[string]LicenseObject{
	OrgSiemens: generatedSiemensMap,
}
