// SPDX-FileCopyrightText: Copyright 2026 Siemens AG
// SPDX-License-Identifier: BSD-3-Clause

package main

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunRequiresInput(t *testing.T) {
	t.Parallel()

	err := run([]string{"-output", t.TempDir()})
	if err == nil || !strings.Contains(err.Error(), "missing required -input") {
		t.Fatalf("expected missing input error, got %v", err)
	}
}

func TestRunRequiresOutput(t *testing.T) {
	t.Parallel()

	err := run([]string{"-input", fixturePath(t)})
	if err == nil || !strings.Contains(err.Error(), "missing required -output") {
		t.Fatalf("expected missing output error, got %v", err)
	}
}

func TestGeneratorProducesCompilableFiles(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	if err := run([]string{"-input", fixturePath(t), "-output", outputDir}); err != nil {
		t.Fatalf("run generator: %v", err)
	}

	expectedFiles := []string{
		"stable_map_generated.go",
		"risky_map_generated.go",
		"organizations_generated.go",
		"org_index_generated.go",
		"org_acme_corp_map_generated.go",
		"org_siemens_map_generated.go",
	}

	for _, filename := range expectedFiles {
		filePath := filepath.Join(outputDir, filename)
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Fatalf("read %s: %v", filename, err)
		}

		assertContains(t, string(content), "SPDX-License-Identifier: BSD-3-Clause")
		assertContains(t, string(content), "Code generated by go/internal/codegen. DO NOT EDIT.")
	}

	organizationsSource, err := os.ReadFile(filepath.Join(outputDir, "organizations_generated.go"))
	if err != nil {
		t.Fatalf("read organizations file: %v", err)
	}
	assertContains(t, string(organizationsSource), "OrgAcmeCorp Organization = \"acme-corp\"")
	assertContains(t, string(organizationsSource), "OrgSiemens  Organization = \"siemens\"")

	stableMapSource, err := os.ReadFile(filepath.Join(outputDir, "stable_map_generated.go"))
	if err != nil {
		t.Fatalf("read stable map file: %v", err)
	}
	assertContains(t, string(stableMapSource), "\"Apache 2.0\": {ID: \"Apache-2.0\", Src: \"spdx\"},")
	assertContains(t, string(stableMapSource), "\"MIT\":")
	assertContains(t, string(stableMapSource), "ID: \"MIT\", Src: \"spdx\"}")

	writeSupportFiles(t, outputDir)
	runGoBuild(t, outputDir)
	ensureFormatted(t, outputDir)
}

func TestReadMergedDataMissingFile(t *testing.T) {
	t.Parallel()

	_, err := readMergedData(filepath.Join(t.TempDir(), "missing.json"))
	if err == nil || !strings.Contains(err.Error(), "read input") {
		t.Fatalf("expected read input error, got %v", err)
	}
}

func TestReadMergedDataInvalidJSON(t *testing.T) {
	t.Parallel()

	invalidJSONPath := filepath.Join(t.TempDir(), "invalid.json")
	if err := os.WriteFile(invalidJSONPath, []byte("{"), 0o644); err != nil {
		t.Fatalf("write invalid json: %v", err)
	}

	_, err := readMergedData(invalidJSONPath)
	if err == nil || !strings.Contains(err.Error(), "parse input json") {
		t.Fatalf("expected parse input json error, got %v", err)
	}
}

func TestGenerateWithoutOrganizations(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	g := generator{
		packageName: defaultPackageName,
		outputDir:   outputDir,
		data: mergedData{
			"stableMap": {
				"MIT": {ID: "MIT", Src: "spdx"},
			},
			"riskyMap": {},
		},
	}

	if err := g.generate(); err != nil {
		t.Fatalf("generate without organizations: %v", err)
	}

	organizationsSource, err := os.ReadFile(filepath.Join(outputDir, "organizations_generated.go"))
	if err != nil {
		t.Fatalf("read organizations output: %v", err)
	}
	assertContains(t, string(organizationsSource), "const ()")
}

func TestGenerateFailsWhenOutputPathIsFile(t *testing.T) {
	t.Parallel()

	outputPath := filepath.Join(t.TempDir(), "not-a-directory")
	if err := os.WriteFile(outputPath, []byte("x"), 0o644); err != nil {
		t.Fatalf("write output path fixture: %v", err)
	}

	g := generator{
		packageName: defaultPackageName,
		outputDir:   outputPath,
		data:        mergedData{},
	}

	err := g.generate()
	if err == nil || !strings.Contains(err.Error(), "create output directory") {
		t.Fatalf("expected create output directory error, got %v", err)
	}
}

func TestWriteFormattedFileReportsFormatError(t *testing.T) {
	t.Parallel()

	err := writeFormattedFile(filepath.Join(t.TempDir(), "broken.go"), "package bad\nfunc {\n")
	if err == nil || !strings.Contains(err.Error(), "format broken.go") {
		t.Fatalf("expected format error, got %v", err)
	}
}

func TestWriteFormattedFileReportsWriteError(t *testing.T) {
	t.Parallel()

	outputDir := t.TempDir()
	err := writeFormattedFile(outputDir, "package licenselynx\n")
	if err == nil || !strings.Contains(err.Error(), "write ") {
		t.Fatalf("expected write error, got %v", err)
	}
}

func TestIdentifierSuffix(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		input string
		want  string
	}{
		{name: "simple org", input: "siemens", want: "Siemens"},
		{name: "mixed separators", input: "acme-corp_group", want: "AcmeCorpGroup"},
		{name: "starts with digit", input: "123-org", want: "X123Org"},
		{name: "punctuation only", input: "---", want: "Org"},
		{name: "empty", input: "", want: "Org"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			if got := identifierSuffix(test.input); got != test.want {
				t.Fatalf("identifierSuffix(%q) = %q, want %q", test.input, got, test.want)
			}
		})
	}
}

func TestSanitizeFilename(t *testing.T) {
	t.Parallel()

	got := sanitizeFilename("Acme-Corp 2026/Legal")
	if got != "acme_corp_2026_legal" {
		t.Fatalf("sanitizeFilename mismatch: got %q", got)
	}
}

func TestMainWritesErrorAndExits(t *testing.T) {
	t.Parallel()

	if os.Getenv("LICENSELYNX_CODEGEN_MAIN_TEST") == "1" {
		os.Args = []string{"codegen"}
		main()
		return
	}

	cmd := exec.Command(os.Args[0], "-test.run=TestMainWritesErrorAndExits")
	cmd.Env = append(os.Environ(), "LICENSELYNX_CODEGEN_MAIN_TEST=1")
	output, err := cmd.CombinedOutput()

	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("expected subprocess to exit with error, got %v", err)
	}
	if exitErr.ExitCode() != 1 {
		t.Fatalf("unexpected exit code: got %d", exitErr.ExitCode())
	}
	assertContains(t, string(output), "code generation failed: missing required -input")
}

func fixturePath(t *testing.T) string {
	t.Helper()
	return filepath.Join("..", "..", "testdata", "merged_data.json")
}

func writeSupportFiles(t *testing.T, outputDir string) {
	t.Helper()

	files := map[string]string{
		"go.mod": "module generatedtest\n\ngo 1.25\n",
		"support.go": `package licenselynx

type LicenseObject struct {
	ID  string
	Src string
}

type Organization string
`,
	}

	for name, content := range files {
		if err := os.WriteFile(filepath.Join(outputDir, name), []byte(content), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
}

func runGoBuild(t *testing.T, outputDir string) {
	t.Helper()

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = outputDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go build failed: %v\n%s", err, output)
	}
}

func ensureFormatted(t *testing.T, outputDir string) {
	t.Helper()

	cmd := exec.Command("gofmt", "-d", ".")
	cmd.Dir = outputDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("gofmt -d failed: %v\n%s", err, output)
	}
	if len(output) != 0 {
		t.Fatalf("generated files are not gofmt clean:\n%s", output)
	}
}

func assertContains(t *testing.T, content, want string) {
	t.Helper()
	if !strings.Contains(content, want) {
		t.Fatalf("expected content to contain %q\nactual:\n%s", want, content)
	}
}
