# Generated by Django 3.1.2 on 2020-10-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='usage',
            name='licenses_chosen',
            field=models.ManyToManyField(blank=True, to='cube.License'),
        ),
    ]
