# Generated by Django 3.1.2 on 2020-10-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_auto_20201008_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='corrected_license',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
