# Generated by Django 3.1.2 on 2020-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0003_version_corrected_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='cpe_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='version',
            name='cpe_name_v',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
