# Generated by Django 4.0.3 on 2022-04-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0003_alter_generic_options_alter_release_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="cube.component",
            ),
        ),
    ]
