# Generated by Django 3.1.2 on 2020-11-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0004_auto_20201105_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('orga_url', models.CharField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.component')),
            ],
        ),
    ]
