# Generated by Django 4.0.3 on 2022-04-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0004_exploitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="cube.product",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="cube.component",
            ),
        ),
    ]
