# Generated by Django 3.1.2 on 2020-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0005_sustain'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='package_repo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
