# Generated by Django 4.0.4 on 2022-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0006_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("Checked", "Checked"),
                    ("Pending", "Pending"),
                    ("To_Discuss", "To discuss"),
                    ("To_Check", "To check"),
                ],
                default="To check",
                help_text="The review status of the license",
                max_length=20,
            ),
        ),
    ]
