# Generated by Django 3.1.3 on 2020-11-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0006_component_package_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='export_control_status',
            field=models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('ToCheck', 'To check'), ('Confirmed', 'Confirmed')], max_length=20),
        ),
    ]
