# Generated by Django 3.1.3 on 2020-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0007_component_export_control_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
