# Generated by Django 3.1.3 on 2020-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0008_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='release',
            name='ship_status',
            field=models.CharField(blank=True, choices=[('Archived', 'Archived'), ('Active', 'In developpement'), ('Published', 'Published')], max_length=20),
        ),
    ]
