# Generated by Django 4.0.6 on 2022-07-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0008_release_commit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('spdx_id',)},
        ),
    ]
