# Generated by Django 3.1.3 on 2021-01-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0009_auto_20201205_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='scope',
            field=models.CharField(blank=True, choices=[('Scan', 'Added by scan'), ('Manual', 'Added manualy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='linking',
            field=models.CharField(blank=True, choices=[('Aggregat', 'Mere aggregation'), ('Dynamic', 'Dynamic Linking'), ('Static', 'Static Linking'), ('Package', 'Package Manager'), ('Mingled', 'Source code directly derived')], max_length=20),
        ),
        migrations.CreateModel(
            name='Derogation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linking', models.CharField(blank=True, choices=[('Aggregat', 'Mere aggregation'), ('Dynamic', 'Dynamic Linking'), ('Static', 'Static Linking'), ('Package', 'Package Manager'), ('Mingled', 'Source code directly derived')], max_length=20)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.license')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.release')),
            ],
        ),
    ]
