# Generated by Django 3.1.3 on 2021-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0010_auto_20210118_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='scope',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
