# Generated by Django 4.0.6 on 2022-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0011_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='project',
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
    ]
