# Generated by Django 3.1.3 on 2021-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0011_auto_20210118_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='derogation',
            name='explanation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='derogation',
            name='scope',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='derogation',
            name='linking',
            field=models.CharField(blank=True, choices=[('Aggregat', 'Mere aggregation'), ('Dynamic', 'Dynamic Linking'), ('Static', 'Static Linking'), ('Package', 'Package Manager'), ('Mingled', 'Source code directly derived')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='scope',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
