# Generated by Django 3.1.3 on 2021-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0012_auto_20210201_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='valid_step',
            field=models.IntegerField(null=True, verbose_name='Validation Step'),
        ),
    ]
