# Generated by Django 4.0.6 on 2022-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0013_alter_exploitation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("name", "package_repo")},
        ),
    ]
