# Generated by Django 4.0.6 on 2022-07-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0012_licensecorrection_proxy'),
        ('cube', '0013_alter_exploitation_unique_together_and_more'),
    ]

    operations = [
    ]
