# Generated by Django 4.1 on 2022-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0014_alter_component_name_alter_component_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="trigger_expl",
            field=models.CharField(
                choices=[
                    (
                        "DistributionSourceDistributionNonSource",
                        "If source code or binaries are distributed",
                    ),
                    ("DistributionSource", "If source code is distributed"),
                    ("DistributionNonSource", "If binaries are distributed"),
                    ("NetworkAccess", "If component is accessible by network access"),
                    ("InternalUse", "If the component is used internally"),
                ],
                default="DistributionSourceDistributionNonSource",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="trigger_mdf",
            field=models.CharField(
                choices=[
                    ("Altered", "Only if component modified"),
                    ("Unmodified", "Only if component is not modified"),
                    ("AlteredUnmodified", "If component is modified or not"),
                ],
                default="AlteredUnmodified",
                max_length=40,
            ),
        ),
    ]
