# Generated by Django 3.1.3 on 2021-02-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0014_auto_20210204_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic',
            name='lead',
        ),
    ]
