# Generated by Django 4.1.1 on 2022-09-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0015_alter_obligation_trigger_expl_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("product", "release_number")},
        ),
    ]
