# Generated by Django 3.1.3 on 2021-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0015_remove_generic_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='scanned_licenses',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
