# Generated by Django 3.1.3 on 2021-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0016_version_scanned_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='valid_step',
            field=models.IntegerField(blank=True, null=True, verbose_name='Validation Step'),
        ),
    ]
