# Generated by Django 4.1.1 on 2022-09-21 13:59

from django.db import migrations, models
import django.db.models.deletion


def update_allowed_field(app, schema_editor):
    License = app.get_model("cube", "License")
    License.objects.filter(allowed="Green").update(allowed="always")
    License.objects.filter(allowed="Red").update(allowed="never")
    License.objects.filter(allowed="Orange").update(allowed="context")
    License.objects.filter(allowed="Grey").update(allowed="")


def reverse_allowed_field(app, schema_editor):
    License = app.get_model("cube", "License")
    License.objects.filter(allowed="always").update(allowed="Green")
    License.objects.filter(allowed="never").update(allowed="Red")
    License.objects.filter(allowed="context").update(allowed="Orange")
    License.objects.filter(allowed="").update(allowed="Grey")


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0016_alter_release_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="license",
            old_name="color_explanation",
            new_name="allowed_explanation",
        ),
        migrations.RenameField(
            model_name="license", old_name="color", new_name="allowed"
        ),
        migrations.RunPython(update_allowed_field, reverse_code=reverse_allowed_field),
        migrations.AlterField(
            model_name="license",
            name="allowed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("always", "Always allowed"),
                    ("never", "Never allowed"),
                    ("context", "Allowed depending on context"),
                    ("", "Not reviewed yet"),
                ],
                max_length=20,
            ),
        ),
    ]
