# Generated by Django 3.1.3 on 2021-02-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0017_auto_20210208_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='cpe_name_v',
            new_name='vuln_code_id',
        ),
        migrations.AddField(
            model_name='version',
            name='vuln_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of vulnerabilities'),
        ),
    ]
