# Generated by Django 3.1.3 on 2021-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0018_auto_20210209_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='spdx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
