# Generated by Django 3.2.6 on 2021-09-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0019_obligation_spdx'),
    ]

    operations = [
        migrations.AddField(
            model_name='derogation',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.usage'),
        ),
    ]
