# Generated by Django 3.2.6 on 2021-09-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0020_derogation_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='color_explanation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
