# Generated by Django 4.1.1 on 2022-10-10 14:04

import django.db.models.deletion
from django.db import migrations, models


def migrate_derogations(app, schema_editor):
    Derogation = app.get_model("cube", "Derogation")
    for derogation in Derogation.objects.exclude(usage=None):
        derogation.version = derogation.usage.version
        derogation.scope = derogation.usage.scope
        derogation.save()


def unmigrate_derogations(app, schema_editor):
    Derogation = app.get_model("cube", "Derogation")
    Usage = app.get_model("cube", "Usage")
    for derogation in Derogation.objects.exclude(version=None).exclude(release=None):
        try:
            usage = Usage.objects.get(
                release=derogation.release, version=derogation.version
            )
        except (Usage.DoesNotExist, Usage.MultipleObjectsReturned):
            continue
        else:
            derogation.usage = usage
            derogation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0020_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="derogation",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.component",
            ),
        ),
        migrations.AddField(
            model_name="derogation",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.product",
            ),
        ),
        migrations.AddField(
            model_name="derogation",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.version",
            ),
        ),
        migrations.RunPython(
            code=migrate_derogations, reverse_code=unmigrate_derogations
        ),
        migrations.RemoveField(
            model_name="derogation",
            name="usage",
        ),
        migrations.AlterField(
            model_name="derogation",
            name="justification",
            field=models.TextField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="derogation",
            name="linking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aggregation", "Mere aggregation"),
                    ("Dynamic", "Dynamic Linking"),
                    ("Static", "Static Linking"),
                    ("Package", "Package Manager"),
                    ("Mingled", "Source code directly derived"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="derogation",
            name="release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.release",
            ),
        ),
        migrations.AlterField(
            model_name="derogation",
            name="scope",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
