# Generated by Django 3.2.6 on 2021-09-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0021_license_color_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='derogation',
            old_name='explanation',
            new_name='justification',
        ),
    ]
