# Generated by Django 3.2.6 on 2021-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0022_rename_explanation_derogation_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='cpe_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='lectra',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='spdx',
        ),
        migrations.AlterField(
            model_name='component',
            name='export_control_status',
            field=models.CharField(blank=True, choices=[('CL', 'Cleared'), ('TBC', 'To check'), ('CONF', 'Confirmed')], max_length=20),
        ),
    ]
