# Generated by Django 4.1.1 on 2022-10-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0022_remove_license_legal_uncertainty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagedecision",
            name="expression_in",
            field=models.CharField(
                blank=True,
                help_text="The exact expression which must be changed",
                max_length=500,
            ),
        ),
    ]
