# Generated by Django 3.2.6 on 2021-09-20 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cube', '0023_auto_20210917_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='language',
            new_name='programming_language',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='release_text',
            new_name='release_number',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='modified',
            new_name='component_modified',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='declared_license',
            new_name='declared_license_expr',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='validated_spdx_license',
            new_name='spdx_valid_license_expr',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='addition',
        ),
        migrations.AddField(
            model_name='usage',
            name='addition_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='usage',
            name='addition_method',
            field=models.CharField(blank=True, choices=[('Scan', 'Added by scan'), ('Manual', 'Added manually')], max_length=20),
        ),
        migrations.AlterField(
            model_name='derogation',
            name='linking',
            field=models.CharField(blank=True, choices=[('Aggregation', 'Mere aggregation'), ('Dynamic', 'Dynamic Linking'), ('Static', 'Static Linking'), ('Package', 'Package Manager'), ('Mingled', 'Source code directly derived')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usage',
            name='linking',
            field=models.CharField(blank=True, choices=[('Aggregation', 'Mere aggregation'), ('Dynamic', 'Dynamic Linking'), ('Static', 'Static Linking'), ('Package', 'Package Manager'), ('Mingled', 'Source code directly derived')], max_length=20),
        ),
    ]
