# Generated by Django 4.1.1 on 2022-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0023_alter_usagedecision_expression_in"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="obligation",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("generic__metacategory"),
                        descending=True,
                        nulls_last=True,
                    )
                ]
            },
        ),
    ]
