# Generated by Django 3.2.6 on 2021-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0024_auto_20210920_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='trigger_mdf',
            field=models.CharField(choices=[('Altered', 'Only if modified'), ('Unmodified', 'Only if not modified'), ('AlteredUnmodified', 'Modified or not')], default='Both', max_length=40),
        ),
        migrations.AlterField(
            model_name='usage',
            name='component_modified',
            field=models.CharField(blank=True, choices=[('Altered', 'Modified'), ('Unmodified', 'Not modified')], max_length=20, null=True),
        ),
    ]
