# Generated by Django 4.1.1 on 2022-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0024_alter_obligation_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="technical_nature_constraint",
        ),
        migrations.AddField(
            model_name="license",
            name="liability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full", "Full clause"),
                    ("Partial", "Partial clause"),
                    ("Absent", "No clause"),
                ],
                max_length=30,
                verbose_name="Non Liability clause",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="warranty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full", "Full clause"),
                    ("Partial", "Partial clause"),
                    ("Absent", "No clause"),
                ],
                max_length=30,
                verbose_name="Warranty limitation clause",
            ),
        ),
    ]
