# Generated by Django 3.2.6 on 2021-09-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0025_auto_20210927_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generic',
            old_name='in_base',
            new_name='in_core',
        ),
    ]
