# Generated by Django 4.1.1 on 2022-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0026_alter_license_liability_alter_license_warranty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="scope",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
    ]
