# Generated by Django 3.2.7 on 2021-10-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0026_rename_in_base_generic_in_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='trigger_mdf',
            field=models.CharField(choices=[('Altered', 'Only if modified'), ('Unmodified', 'Only if not modified'), ('AlteredUnmodified', 'Modified or not')], default='AlteredUnmodified', max_length=40),
        ),
        migrations.AlterField(
            model_name='usage',
            name='component_modified',
            field=models.CharField(blank=True, choices=[('Altered', 'Modified'), ('Unmodified', 'Not modified')], default='Unmodified', max_length=20),
        ),
    ]
