# Generated by Django 3.2.7 on 2021-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0027_auto_20211005_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generic',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
