# Generated by Django 3.2.8 on 2021-10-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0028_alter_generic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generic',
            old_name='obligation_type',
            new_name='passivity',
        ),
        migrations.RenameField(
            model_name='obligation',
            old_name='obligation_type',
            new_name='passivity',
        ),
    ]
