# Generated by Django 3.2.8 on 2021-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0029_auto_20211011_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligation',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='distribution',
        ),
        migrations.AddField(
            model_name='obligation',
            name='trigger_expl',
            field=models.CharField(choices=[('Distribution', 'Distribution source and object'), ('DistributionSource', 'Distribution - Source'), ('DistributionNonSource', 'Distribution Non source'), ('NetworkAccess', 'Network access'), ('InternalUse', 'Internal use')], default='Distribution', max_length=40),
        ),
        migrations.AddField(
            model_name='usage',
            name='exploitation',
            field=models.CharField(choices=[('Distribution', 'Distribution source and object'), ('DistributionSource', 'Distribution - Source'), ('DistributionNonSource', 'Distribution Non source'), ('NetworkAccess', 'Network access'), ('InternalUse', 'Internal use')], default='Distribution', max_length=50),
        ),
        migrations.AlterField(
            model_name='license',
            name='color',
            field=models.CharField(choices=[('Green', 'Always allowed'), ('Red', 'Never allowed'), ('Orange', 'Allowed depending on context'), ('Grey', 'No reviewed yet')], default='Grey', max_length=20),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Pending', 'Pending'), ('To_Discuss', 'To discuss'), ('To_Check', 'To check')], default='To check', max_length=20),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
