# Generated by Django 3.2.8 on 2021-11-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0030_auto_20211019_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cube.generic'),
        ),
    ]
