# Generated by Django 3.2.8 on 2021-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0031_alter_obligation_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='inspiration_spdx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
