# Generated by Django 3.2.8 on 2021-11-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0032_license_inspiration_spdx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='jurisdictional_clause',
            new_name='law_choice',
        ),
    ]
