# Generated by Django 3.2.8 on 2021-11-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0033_rename_jurisdictional_clause_license_law_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='venue_choice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
