# Generated by Django 3.2.8 on 2021-11-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0034_license_venue_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('component', 'version_number')},
        ),
    ]
