# Generated by Django 4.1.1 on 2023-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0034_alter_derogation_scope_alter_exploitation_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derogation",
            name="linking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aggregation", "Mere aggregation"),
                    ("Dynamic", "Dynamic Linking"),
                    ("Static", "Static Linking"),
                    ("Mingled", "Source code directly derived"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="linking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Aggregation", "Mere aggregation"),
                    ("Dynamic", "Dynamic Linking"),
                    ("Static", "Static Linking"),
                    ("Mingled", "Source code directly derived"),
                ],
                max_length=20,
            ),
        ),
    ]
