# Generated by Django 4.1.1 on 2023-01-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0035_alter_derogation_linking_alter_usage_linking"),
        ("cube", "0035_funding"),
    ]

    operations = []
