# Generated by Django 3.2.8 on 2021-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0035_alter_version_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('product', 'release_number')},
        ),
    ]
