# Generated by Django 3.2.8 on 2021-12-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0036_auto_20211125_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odd_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('full_path', models.CharField(blank=True, max_length=2000)),
                ('spdx_valid_license_expr', models.CharField(blank=True, max_length=200)),
                ('corrected_license', models.CharField(blank=True, max_length=200)),
                ('copyright_texts', models.TextField(blank=True, max_length=4000)),
                ('line_start', models.IntegerField(blank=True, null=True, verbose_name='Start of the snippet')),
                ('line_end', models.IntegerField(blank=True, null=True, verbose_name='End of snippet')),
                ('microscope', models.CharField(blank=True, max_length=50, null=True)),
                ('relation', models.CharField(blank=True, choices=[('Integrated', 'Integrated'), ('Aggregation', 'Mere aggregation')], max_length=40)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.version')),
            ],
        ),
    ]
