# Generated by Django 3.2.8 on 2021-12-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0037_odd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='copyright_texts',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
