# Generated by Django 3.2.8 on 2022-01-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0038_version_copyright_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageChoice',
            fields=[
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usagechoice', serialize=False, to='cube.usage')),
                ('expression_in', models.CharField(max_length=500)),
                ('expression_out', models.CharField(max_length=500)),
                ('scope_mask', models.CharField(blank=True, choices=[('usage', 'Only this usage'), ('release', 'The whole release'), ('component', 'Every usage of this component'), ('linking', 'Every usage with this same linking'), ('scope', 'Every usage with the same scope'), ('linkingscope', 'Every usage with the same scope AND the same linking')], max_length=40)),
                ('explanation', models.TextField(blank=True, max_length=500, null=True)),
                ('is_propagated', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usage',
            name='license_expression',
        ),
        migrations.AlterField(
            model_name='derogation',
            name='scope',
            field=models.CharField(blank=True, choices=[('usage', 'Only this usage'), ('release', 'The whole release'), ('component', 'Every usage of this component'), ('linking', 'Every usage with this same linking'), ('scope', 'Every usage with the same scope'), ('linkingscope', 'Every usage with the same scope AND the same linking')], max_length=50, null=True),
        ),
    ]
