# Generated by Django 4.1.7 on 2023-04-05 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0038_alter_product_options_alter_release_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generic",
            options={
                "permissions": (("export_generic", "Can export generic obligations"),),
                "verbose_name": "Generic obligation",
                "verbose_name_plural": "Generic obligations",
            },
        ),
        migrations.AlterModelOptions(
            name="license",
            options={
                "ordering": ("spdx_id",),
                "permissions": (("export_license", "Can export licenses"),),
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
            },
        ),
        migrations.AlterModelOptions(
            name="licensecuration",
            options={
                "permissions": (
                    ("export_licensecuration", "Can export license curations"),
                ),
                "verbose_name": "License curation",
                "verbose_name_plural": "License curations",
            },
        ),
    ]
