# Generated by Django 4.1.7 on 2023-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0038_alter_product_options_alter_release_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="release",
            options={
                "ordering": ["product", "release_number"],
                "permissions": [
                    ("change_release_bom", "Can upload a new BOM for a release")
                ],
                "verbose_name": "Product release",
                "verbose_name_plural": "Product releases",
            },
        ),
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["component", "version_number"],
                "verbose_name": "Component version",
                "verbose_name_plural": "Component versions",
            },
        ),
    ]
