# Generated by Django 3.2.8 on 2022-01-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0039_auto_20220107_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='license_expression',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='derogation',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.release'),
        ),
    ]
