# Generated by Django 3.2.8 on 2022-01-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0040_auto_20220113_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odd_file',
            name='version',
        ),
        migrations.RemoveField(
            model_name='sustain',
            name='component',
        ),
        migrations.RemoveField(
            model_name='version',
            name='vuln_code_id',
        ),
        migrations.RemoveField(
            model_name='version',
            name='vuln_number',
        ),
        migrations.DeleteModel(
            name='Compatibility',
        ),
        migrations.DeleteModel(
            name='Odd_file',
        ),
        migrations.DeleteModel(
            name='Sustain',
        ),
    ]
