# Generated by Django 4.1.7 on 2023-04-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0039_alter_component_options_alter_product_options_and_more"),
        ("cube", "0040_default_groups"),
    ]

    operations = []
