# Generated by Django 3.2.11 on 2022-01-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0041_auto_20220113_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_in', models.CharField(max_length=500)),
                ('expression_out', models.CharField(max_length=500)),
                ('scope', models.CharField(blank=True, max_length=128, null=True)),
                ('explanation', models.TextField(blank=True, max_length=500, null=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.component')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.product')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.release')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.version')),
            ],
        ),
        migrations.DeleteModel(
            name='UsageChoice',
        ),
    ]
