# Generated by Django 4.2.1 on 2023-05-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0042_alter_usage_addition_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="generic",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="generic",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
