# Generated by Django 4.2.2 on 2023-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0043_generic_created_generic_updated_license_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="package_repo",
            new_name="purl_type",
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("name", "purl_type")},
        ),
        migrations.AlterField(
            model_name="component",
            name="purl_type",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="purl package type"
            ),
        ),
    ]
