# Generated by Django 4.2.4 on 2023-12-18 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cube", "0048_alter_usage_exploitation_alter_usage_linking"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200)),
                ("file_format", models.CharField(blank=True, max_length=10)),
                ("file_component_link", models.CharField(blank=True, max_length=20)),
                ("importation_date", models.DateTimeField(blank=True, max_length=20)),
                (
                    "importation_author",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_release",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cube.release",
                    ),
                ),
            ],
        ),
    ]
