# Generated by Django 5.0.6 on 2024-06-25 11:05

import cube.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0048_alter_license_comment_alter_usage_exploitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="spdx_expression",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="version",
            name="corrected_license",
            field=models.CharField(
                blank=True,
                help_text="Final license expression used in legal evaluation (required when validated expression is ambiguous or empty)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="declared_license_expr",
            field=models.CharField(
                blank=True,
                help_text="Declared license expression (may not be SPDX valid)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="spdx_valid_license_expr",
            field=models.CharField(
                blank=True,
                help_text="License expression concluded by analyzing tool (e.g. ORT)",
                max_length=500,
                validators=[cube.utils.validators.validate_spdx_expression],
            ),
        ),
    ]
