# Generated by Django 5.1.1 on 2024-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0051_alter_generic_options_alter_generic_in_core_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="autoupgrade",
        ),
        migrations.RemoveField(
            model_name="license",
            name="inspiration",
        ),
        migrations.RemoveField(
            model_name="license",
            name="inspiration_spdx",
        ),
        migrations.RemoveField(
            model_name="license",
            name="license_version",
        ),
        migrations.RemoveField(
            model_name="license",
            name="radical",
        ),
    ]
