# Generated by Django 5.1.6 on 2025-03-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0053_licensepolicy_remove_license_allowed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SBOMImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORTBom", "ORT Evaluated model (JSON)"),
                            ("SPDXBom", "SPDX Bill of Materials"),
                            ("CYCLONEDXBom", "CycloneDX Bill of Materials (JSON)"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            (
                                "Replace",
                                "Delete all previously saved component usages and remplace with new import",
                            ),
                            (
                                "Merge",
                                "Add new component usages while keeping previous ones",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "linking",
                    models.CharField(
                        choices=[
                            ("Aggregation", "Mere aggregation"),
                            ("Dynamic", "Dynamic Linking"),
                            ("Static", "Static Linking"),
                            ("Mingled", "Source code directly derived"),
                        ],
                        help_text="Linking type for the imported components",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_history",
                        to="cube.release",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SBOM import",
                "verbose_name_plural": "SBOM imports",
            },
        ),
    ]
