# Generated by Django 5.1.6 on 2025-03-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cube.models.auth


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0053_licensepolicy_remove_license_allowed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "key",
                    models.TextField(
                        default=cube.models.auth.make_token_key,
                        help_text="This will only be shown once",
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ttl",
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text="Duration in seconds of the token validity, empty for no limit",
                        null=True,
                        verbose_name="Time to live",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "verbose_name_plural": "API Tokens",
            },
        ),
    ]
