# Generated by Django 5.1.6 on 2025-02-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0053_licensepolicy_remove_license_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="outbound_licenses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Exploitation licenses that will apply to all products of this category",
                related_name="outbound_categories",
                to="cube.license",
                verbose_name="Exploitation licenses",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="outbound_licenses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Exploitation licenses that will apply for all releases of this product",
                related_name="outbound_products",
                to="cube.license",
                verbose_name="Exploitation licenses",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="outbound_licenses",
            field=models.ManyToManyField(
                blank=True,
                related_name="releases",
                to="cube.license",
                verbose_name="Exploitation licenses",
            ),
        ),
        migrations.CreateModel(
            name="Compatibility",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("A", "Ascending"), ("D", "Descending")],
                        default="A",
                        help_text="Ascending means the license explicitly allows re-licensing under the other one. Descending means the license explicitly allows inclusion of works under the other one inside a combination or derivative work..",
                        max_length=1,
                    ),
                ),
                (
                    "verbatim",
                    models.TextField(
                        blank=True, verbose_name="Exact text of the compatibility"
                    ),
                ),
                (
                    "from_license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_from",
                        to="cube.license",
                        verbose_name="From license",
                    ),
                ),
                (
                    "to_license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_to",
                        to="cube.license",
                        verbose_name="To license",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibility",
                "verbose_name_plural": "Compatibilities",
                "unique_together": {("from_license", "to_license")},
            },
        ),
    ]
