# Generated by Django 5.1.6 on 2025-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0055_merge_0054_sbomimport_0054_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbomimport",
            name="component_update_mode",
            field=models.CharField(
                choices=[
                    ("Default", "Default: update missing informations only"),
                    (
                        "Override",
                        "Override all informations",
                    ),
                ],
                default="Default",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
