# Generated by Django 5.1.5 on 2025-03-25 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0056_merge_20250325_1159"),
        ("cube", "0056_sbomimport_component_update_mode"),
    ]

    operations = []
