# Generated by Django 5.2.6 on 2025-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0057_merge_20250325_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obligation",
            name="trigger_mdf",
            field=models.CharField(
                choices=[
                    ("Altered", "Only if the component is modified"),
                    ("Unmodified", "Only if the component is not modified"),
                    ("AlteredUnmodified", "Whether the component is modified or not"),
                ],
                default="AlteredUnmodified",
                help_text="Status of modification necessary to trigger this obligation",
                max_length=40,
                verbose_name="Triggering modifications",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="ship_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Archived", "Archived"),
                    ("Active", "In development"),
                    ("Published", "Published"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sbomimport",
            name="component_update_mode",
            field=models.CharField(
                choices=[
                    ("Default", "Default: update missing information only"),
                    ("Override", "Override all information"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sbomimport",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORTBom", "ORT Evaluated model (JSON)"),
                    ("SPDXBom", "SPDX Bill of Materials"),
                    ("CYCLONEDXBom", "CycloneDX Bill of Materials (JSON)"),
                    ("HKISSBom", "Hermine KISSBOM variant (JSON)"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="sbomimport",
            name="mode",
            field=models.CharField(
                choices=[
                    (
                        "Replace",
                        "Delete all previously saved component usages and replace with new import",
                    ),
                    ("Merge", "Add new component usages while keeping previous ones"),
                ],
                max_length=20,
            ),
        ),
    ]
