# Generated by Django 5.2 on 2025-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0058_alter_obligation_trigger_mdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="copyright_info",
            field=models.TextField(
                blank=True, help_text="Information about the copyright holder"
            ),
        ),
    ]
