# Generated by Django 5.2.11 on 2026-03-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0061_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensepolicy",
            name="allowed_explanation",
            field=models.TextField(
                blank=True, max_length=1500, verbose_name="Internal comment"
            ),
        ),
    ]
