# Generated by Django 5.2.11 on 2026-03-04 14:44

from django.db import migrations, models

import cube.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0061_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="foss",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Yes", "We consider it is FOSS"),
                    ("Yes-Auto", "FOSS - deduced"),
                    ("No", "We consider it is NOT FOSS"),
                    ("No-Auto", "NOT FOSS - deduced"),
                ],
                help_text="Whether this license is considered Free/Open Source",
                max_length=20,
                verbose_name="FOSS Status",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="fsf_approved",
            field=models.BooleanField(null=True, verbose_name="Approved by FSF"),
        ),
        migrations.AlterField(
            model_name="license",
            name="non_commercial",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "Unknown"), (True, "Disallowed"), (False, "Allowed")],
                null=True,
                verbose_name="Commercial use",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="non_tivoisation",
            field=models.BooleanField(
                help_text="Whether the license forbid inclusion of the software in hardware that prevents users from running modified versions",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="osi_approved",
            field=models.BooleanField(null=True, verbose_name="Approved by OSI"),
        ),
        migrations.AlterField(
            model_name="license",
            name="patent_grant",
            field=models.BooleanField(
                help_text="Whether the license includes a patent grant clause",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="spdx_id",
            field=models.CharField(
                help_text="The SPDX identifier can be found on the spdx.org website",
                max_length=200,
                unique=True,
                validators=[cube.utils.validators.validate_spdx_id],
                verbose_name="SPDX Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="steward",
            field=models.CharField(
                blank=True,
                help_text="The organization supporting the development of this license",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="url",
            field=models.URLField(
                blank=True, help_text="The link to the official license"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="verbatim",
            field=models.TextField(
                blank=True, verbose_name="Exact text of the license"
            ),
        ),
    ]
