# Generated by Django 5.2.11 on 2026-04-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0063_merge_20260427_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="generic",
            name="internal_process",
            field=models.TextField(
                blank=True,
                help_text="Define the specific actions to take in your organization related to the compliance action.",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="What needs to be done, or not done, to be compliant.",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="in_core",
            field=models.BooleanField(
                choices=[
                    (True, "Yes (no action required)"),
                    (False, "No (action required)"),
                ],
                default=False,
                help_text="If selected, this compliance action is part of the core policy of your organization, and no further action is required.",
                verbose_name="Included by default",
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="metacategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Communication", "Communication constraints"),
                    ("IPManagement", "IP management"),
                    ("LicenseAgreement", "License agreement"),
                    ("Mentions", "Mentions"),
                    ("ProvidingSourceCode", "Providing source code"),
                    ("TechnicalConstraints", "Technical constraints"),
                ],
                help_text="Select the category of compliance.",
                max_length=40,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="name",
            field=models.CharField(
                help_text="The name of the action to perform.",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="passivity",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active (DO)"), ("Passive", "Passive (DON'T)")],
                help_text='The action can be "Active" (you SHOULD perform some action) or "Passive" (you SHOULD NOT do something)',
                max_length=20,
                verbose_name="Action type",
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team in charge for this compliance action.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cube.team",
                verbose_name="Team",
            ),
        ),
    ]
