-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only



CREATE TABLE IF NOT EXISTS change_logs (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    field TEXT,
    updated_value TEXT,
    old_value TEXT,
    audit_id BIGINT,

    CONSTRAINT fk_audits_change_logs FOREIGN KEY (audit_id) REFERENCES audits(id)
);
