-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only

-- up.sql

CREATE TABLE IF NOT EXISTS license_dbs (
    rf_id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rf_shortname TEXT NOT NULL UNIQUE,
    rf_fullname TEXT NOT NULL,
    rf_text TEXT NOT NULL,
    rf_url TEXT NOT NULL DEFAULT '',
    rf_add_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    rf_copyleft BOOLEAN NOT NULL DEFAULT FALSE,
    rf_fsffree BOOLEAN NOT NULL DEFAULT FALSE,
    rf_osiapproved BOOLEAN NOT NULL DEFAULT FALSE,
    rf_gplv2compatible BOOLEAN NOT NULL DEFAULT FALSE,
    rf_gplv3compatible BOOLEAN NOT NULL DEFAULT FALSE,
    rf_fedora TEXT NOT NULL DEFAULT '',
    rf_notes TEXT NOT NULL DEFAULT '',
    rf_text_updatable BOOLEAN NOT NULL DEFAULT FALSE,
    rf_detector_type BIGINT NOT NULL DEFAULT 1,
    rf_active BOOLEAN NOT NULL DEFAULT TRUE,
    rf_source TEXT NOT NULL DEFAULT '',
    rf_spdx_id TEXT NOT NULL,
    rf_risk BIGINT NOT NULL DEFAULT 0,
    rf_flag BIGINT NOT NULL DEFAULT 0,
    marydone BOOLEAN NOT NULL DEFAULT FALSE,
    external_ref JSONB,
    user_id BIGINT,
   
    CONSTRAINT fk_license_dbs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_license_dbs_shortname UNIQUE (rf_shortname)
);
