-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only

-- obligation table up ---
CREATE TABLE IF NOT EXISTS obligations (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    topic TEXT NOT NULL,
    text TEXT NOT NULL,
    modifications BOOLEAN NOT NULL DEFAULT FALSE,
    comment TEXT NOT NULL DEFAULT ''::text,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    text_updatable BOOLEAN NOT NULL DEFAULT FALSE,
    md5 TEXT NOT NULL,
    obligation_classification_id BIGINT NOT NULL,
    obligation_type_id BIGINT NOT NULL,
    category TEXT DEFAULT 'GENERAL'::text,
    CONSTRAINT uni_obligations_md5 UNIQUE (md5),
    CONSTRAINT uni_obligations_topic UNIQUE (topic),
    CONSTRAINT fk_obligations_classification FOREIGN KEY (obligation_classification_id) REFERENCES obligation_classifications(id),
    CONSTRAINT fk_obligations_type FOREIGN KEY (obligation_type_id) REFERENCES obligation_types(id)
);
