# Generated by Django 4.0.4 on 2022-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0007_alter_license_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="commit",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Commit hash or ref"
            ),
        ),
    ]
