# Generated by Django 4.1.1 on 2022-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0018_verbose_names_and_help_texts"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseCuration",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cube.usagedecision",),
        ),
        migrations.AlterField(
            model_name="usagedecision",
            name="decision_type",
            field=models.CharField(
                choices=[
                    ("choice", "License choice"),
                    ("validation", "Expression validation"),
                    ("curation", "License curation"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="corrected_license",
            field=models.CharField(
                blank=True,
                help_text="Final license expression used in legal evaluation (required when validated expression is ambiguous)",
                max_length=200,
            ),
        ),
    ]
