# Generated by Django 4.1.1 on 2022-10-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0021_remove_derogation_usage_derogation_component_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="legal_uncertainty",
        ),
        migrations.AlterField(
            model_name="license",
            name="allowed",
            field=models.CharField(
                blank=True,
                choices=[
                    ("always", "Always allowed"),
                    ("never", "Never allowed"),
                    ("context", "Allowed depending on context"),
                    ("notfoss", "Out of FOSS Policy"),
                    ("", "Not reviewed yet"),
                ],
                max_length=20,
                verbose_name="OSS Policy",
            ),
        ),
    ]
