# Generated by Django 4.1.1 on 2022-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0025_remove_license_technical_nature_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="liability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full", "Full clause"),
                    ("Partial", "Partial clause"),
                    ("Absent", "No clause"),
                ],
                max_length=30,
                verbose_name="Limitation of Liability",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="warranty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full", "Full clause"),
                    ("Partial", "Partial clause"),
                    ("Absent", "No clause"),
                ],
                max_length=30,
                verbose_name="Disclaimer of Warranty",
            ),
        ),
    ]
