# Generated by Django 4.1.1 on 2023-01-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0031_merge_curations"),
    ]

    operations = [
        migrations.AddField(
            model_name="derogation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.category",
            ),
        ),
        migrations.AddField(
            model_name="licensechoice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cube.category",
            ),
        ),
        migrations.AddField(
            model_name="licensechoice",
            name="exploitation",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "DistributionSourceDistributionNonSource",
                        "Distribution source and object",
                    ),
                    ("DistributionSource", "Distribution - Source"),
                    ("DistributionNonSource", "Distribution Non source"),
                    ("NetworkAccess", "Network access"),
                    ("InternalUse", "Internal use"),
                ],
                max_length=50,
            ),
        ),
    ]
