# Generated by Django 4.1.1 on 2023-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0032_derogation_category_licensechoice_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="allowed_explanation",
            field=models.TextField(
                blank=True, max_length=1500, verbose_name="OSS Policy explanation"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="verbatim",
            field=models.TextField(
                blank=True,
                help_text="Only necessary if the license has no official SPDX ID",
                verbose_name="Exact text of the license",
            ),
        ),
    ]
