# Generated by Django 4.1.1 on 2023-01-20 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0034_alter_derogation_scope_alter_exploitation_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("type", models.CharField(max_length=200)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundings",
                        to="cube.component",
                    ),
                ),
            ],
        ),
    ]
