# Generated by Django 4.1.7 on 2023-02-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0036_merge_20230124_1611"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="valid_step",
            field=models.IntegerField(default=0, verbose_name="Validation Step"),
        ),
    ]
