# Generated by Django 4.1.7 on 2023-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0037_alter_release_valid_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="release",
            options={
                "permissions": [
                    ("change_release_bom", "Can upload a new BOM for a release")
                ],
                "verbose_name": "Product release",
                "verbose_name_plural": "Product releases",
            },
        ),
        migrations.AlterField(
            model_name="release",
            name="release_number",
            field=models.CharField(
                help_text="Must be unique for a product", max_length=200
            ),
        ),
    ]
