# Generated by Django 4.1.7 on 2023-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cube", "0041_merge_20230405_2141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="addition_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last updated"
            ),
        ),
    ]
