# Generated by Django 4.2.4 on 2023-10-04 10:32

from django.db import migrations, models
import semantic_version.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0045_releaseconsultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="derogation",
            name="version_constraint",
            field=semantic_version.django_fields.SpecField(
                blank=True, max_length=200, verbose_name="Version constraint"
            ),
        ),
        migrations.AddField(
            model_name="licensechoice",
            name="version_constraint",
            field=semantic_version.django_fields.SpecField(
                blank=True, max_length=200, verbose_name="Version constraint"
            ),
        ),
        migrations.AddField(
            model_name="licensecuration",
            name="version_constraint",
            field=semantic_version.django_fields.SpecField(
                blank=True, max_length=200, verbose_name="Version constraint"
            ),
        ),
        migrations.AlterField(
            model_name="releaseconsultation",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
