# Generated by Django 5.0.7 on 2024-08-13 14:18

from django.db import migrations, models

import cube.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0049_alter_component_spdx_expression_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usage",
            options={
                "ordering": ["id"],
                "verbose_name": "Component usage",
                "verbose_name_plural": "Component usages",
            },
        ),
        migrations.AlterField(
            model_name="license",
            name="spdx_id",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[cube.utils.validators.validate_spdx_id],
                verbose_name="SPDX Identifier",
            ),
        ),
    ]
