# Generated by Django 5.0.7 on 2024-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0050_alter_usage_options_alter_license_spdx_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generic",
            options={
                "permissions": (
                    ("export_generic", "Can export compliance actions"),
                    ("import_generic", "Can import compliance actions"),
                ),
                "verbose_name": "Compliance action",
                "verbose_name_plural": "Compliance actions",
            },
        ),
        migrations.AlterField(
            model_name="generic",
            name="in_core",
            field=models.BooleanField(
                default=False,
                help_text="If True, means this compliance action is assumed to systematically fit to the enterprise policy. Otherwise, means it has to be manually checked.",
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="metacategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Communication", "Communication constraints"),
                    ("IPManagement", "IP management"),
                    ("LicenseAgreement", "License agreement"),
                    ("Mentions", "Mentions"),
                    ("ProvidingSourceCode", "Providing source code"),
                    ("TechnicalConstraints", "Technical constraints"),
                ],
                help_text="A category of compliance action.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="name",
            field=models.CharField(
                help_text="Short description of the compliance action. Unique.",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="generic",
            name="passivity",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Passive", "Passive")],
                help_text="A compliance action needs to conduct some kind of action(Active) or NOT to do specific things (Passive)",
                max_length=20,
            ),
        ),
    ]
