# Generated by Django 5.1.6 on 2025-03-25 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0054_sbomimport"),
        ("cube", "0054_token"),
    ]

    operations = []
