# Generated by Django 5.1.6 on 2025-03-25 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0054_category_default_outbound_licenses_and_more"),
        ("cube", "0055_merge_0054_sbomimport_0054_token"),
    ]

    operations = []
