# Generated by Django 5.2.8 on 2025-11-27 18:24

import cube.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0060_alter_exploitation_scope_alter_usage_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="component",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="component",
            name="spdx_expression",
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="derogation",
            name="justification",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="generic",
            name="description",
            field=models.TextField(
                blank=True, help_text="Longer description, optional.", max_length=2500
            ),
        ),
        migrations.AlterField(
            model_name="licensechoice",
            name="explanation",
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name="licensechoice",
            name="expression_in",
            field=models.CharField(
                help_text="The exact expression which must be changed", max_length=2500
            ),
        ),
        migrations.AlterField(
            model_name="licensechoice",
            name="expression_out",
            field=models.CharField(
                help_text="The final license expression chosen. Can still contains ANDs, and even ORs if you want to comply with all licenses and let the end user choose.",
                max_length=2500,
                validators=[cube.utils.validators.validate_spdx_expression],
                verbose_name="Final SPDX expression",
            ),
        ),
        migrations.AlterField(
            model_name="licensecuration",
            name="declared_expression",
            field=models.CharField(
                blank=True,
                help_text="The declared expression before any curation (used only for curation exports)",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="licensecuration",
            name="explanation",
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name="licensecuration",
            name="expression_in",
            field=models.CharField(
                blank=True,
                help_text="The exact expression which must be changed",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="licensecuration",
            name="expression_out",
            field=models.CharField(
                help_text="The expression which will replace `expression_in`",
                max_length=2500,
                validators=[cube.utils.validators.validate_spdx_expression],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="usage",
            name="description",
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="usage",
            name="license_expression",
            field=models.CharField(
                blank=True,
                max_length=2500,
                validators=[cube.utils.validators.validate_spdx_expression],
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="corrected_license",
            field=models.CharField(
                blank=True,
                help_text="Final license expression used in legal evaluation (required when validated expression is ambiguous or empty)",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="declared_license_expr",
            field=models.CharField(
                blank=True,
                help_text="Declared license expression (may not be SPDX valid)",
                max_length=2500,
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="spdx_valid_license_expr",
            field=models.CharField(
                blank=True,
                help_text="License expression concluded by analyzing tool (e.g. ORT)",
                max_length=2500,
                validators=[cube.utils.validators.validate_spdx_expression],
            ),
        ),
    ]
