# SPDX-FileCopyrightText: 2026 Hermine-team <hermine@inno3.fr>
# SPDX-License-Identifier: AGPL-3.0-only

# Generated by Django 5.2.11 on 2026-04-27 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cube", "0062_alter_license_foss_alter_license_fsf_approved_and_more"),
        ("cube", "0062_alter_licensepolicy_allowed_explanation"),
    ]

    operations = []
