# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright © metaeffekt GmbH 2021. All rights reserved.
canonicalName: "Qt Application Development License 1.1"
category: "Qt Application Development"
shortName: "Qt-Application-Development-1.1"

alternativeNames:
  - "Qt FOR APPLICATION DEVELOPMENT LICENSE AGREEMENT Agreement version 1.1"

