== BSD Zero Clause License (0BSD)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD Zero Clause License
|Shortname |0BSD
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://bsd-zero`

=== Description

____
The BSD Zero Clause license goes further than the BSD 2-Clause license
to allow you unlimited freedom with the software without requirements to
include the copyright notice, license text, or disclaimer in either
source or binary forms.
____

(source: choosealicense.com
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/0BSD.html[SPDX] (all data [in this repository]
is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== Obligations

[cols=",,",options="header",]
|===
|Rights: |Conditions: |Limitations:
a|
* commercial-use
* distribution
* modifications
* private-use

a|

a|
* liability
* warranty

|===

(source:
https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/0bsd.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== URLs

* *Homepage:* http://landley.net/toybox/license.html
* *SPDX:* https://spdx.org/licenses/0BSD.html
* *SPDX:* http://spdx.org/licenses/0BSD.json

=== Text

....
Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/0bsd.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT])
* https://github.com/finos/OSLC-handbook/blob/master/src/0BSD.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/0BSD.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-zero.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "0BSD",
        "BSD Zero Clause License",
        "0bsd",
        "scancode://bsd-zero"
    ],
    "__impliedId": "0BSD",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "0BSD"
                ],
                "__impliedId": "0BSD"
            },
            "shortname": "0BSD",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD Zero Clause License",
            "spdxDetailsURL": "http://spdx.org/licenses/0BSD.json",
            "_sourceURL": "https://spdx.org/licenses/0BSD.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://landley.net/toybox/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "0BSD",
                    "BSD Zero Clause License"
                ],
                "__impliedId": "0BSD",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/0BSD.json"
                    ],
                    [
                        null,
                        "http://landley.net/toybox/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "0BSD"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://landley.net/toybox/license.html",
            "shortName": "BSD Zero Clause License",
            "textUrls": null,
            "text": "Permission to use, copy, modify, and/or distribute this software for any\npurpose with or without fee is hereby granted.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES\nWITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR\nANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES\nWHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN\nACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF\nOR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Rob Landley",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-zero.yml",
            "key": "bsd-zero",
            "name": "BSD Zero Clause License",
            "spdxId": "0BSD",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://bsd-zero",
                    "BSD Zero Clause License",
                    "0BSD"
                ],
                "__impliedId": "0BSD",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission to use, copy, modify, and/or distribute this software for any\npurpose with or without fee is hereby granted.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES\nWITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR\nANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES\nWHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN\nACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF\nOR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://landley.net/toybox/license.html"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Free Public License 1.0.0",
            "commercialUse": true,
            "spdxId": "0BSD",
            "_implications": {
                "__impliedNames": [
                    "0BSD"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/0BSD.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD Zero Clause License",
            "id": "0BSD",
            "_implications": {
                "__impliedNames": [
                    "0BSD",
                    "BSD Zero Clause License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/0BSD.html"
                    ]
                ]
            }
        },
        "choosealicense.com": {
            "limitations": [
                "liability",
                "warranty"
            ],
            "_sourceURL": "https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/0bsd.txt",
            "content": "---\ntitle: BSD Zero Clause License\nspdx-id: 0BSD\n\ndescription: The BSD Zero Clause license goes further than the BSD 2-Clause license to allow you unlimited freedom with the software without requirements to include the copyright notice, license text, or disclaimer in either source or binary forms.\n\nhow: Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.  Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders. You may take the additional step of removing the copyright notice.\n\nusing:\n  PickMeUp: https://github.com/nazar-pc/PickMeUp/blob/master/copying.md\n  smoltcp: https://github.com/m-labs/smoltcp/blob/master/LICENSE-0BSD.txt\n  Toybox: https://github.com/landley/toybox/blob/master/LICENSE\n\npermissions:\n  - commercial-use\n  - distribution\n  - modifications\n  - private-use\n\nconditions: []\n\nlimitations:\n  - liability\n  - warranty\n\n---\n\nCopyright (c) [year] [fullname]\n\nPermission to use, copy, modify, and/or distribute this software for any\npurpose with or without fee is hereby granted.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH\nREGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY\nAND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,\nINDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM\nLOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR\nOTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR\nPERFORMANCE OF THIS SOFTWARE.\n",
            "name": "0bsd",
            "hidden": null,
            "spdxId": "0BSD",
            "conditions": [],
            "permissions": [
                "commercial-use",
                "distribution",
                "modifications",
                "private-use"
            ],
            "featured": null,
            "nickname": null,
            "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.  Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders. You may take the additional step of removing the copyright notice.",
            "title": "BSD Zero Clause License",
            "_implications": {
                "__impliedNames": [
                    "0bsd",
                    "0BSD"
                ],
                "__obligations": {
                    "limitations": [
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "liability"
                        },
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "warranty"
                        }
                    ],
                    "rights": [
                        {
                            "tag": "ImpliedRight",
                            "contents": "commercial-use"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "distribution"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "modifications"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "private-use"
                        }
                    ],
                    "conditions": []
                }
            },
            "description": "The BSD Zero Clause license goes further than the BSD 2-Clause license to allow you unlimited freedom with the software without requirements to include the copyright notice, license text, or disclaimer in either source or binary forms."
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "This license places no conditions whatsoever on using, copying, modifying or distributing the software for any purpose.",
                    "termComplianceNotes": null,
                    "termType": "other"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/0BSD.yaml",
            "name": "BSD Zero Clause License",
            "nameFromFilename": "0BSD",
            "notes": "This is a blanket license with no conditions.",
            "_implications": {
                "__impliedNames": [
                    "0BSD",
                    "BSD Zero Clause License"
                ]
            },
            "licenseId": [
                "0BSD",
                "BSD Zero Clause License"
            ]
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__obligations": {
        "limitations": [
            {
                "tag": "ImpliedLimitation",
                "contents": "liability"
            },
            {
                "tag": "ImpliedLimitation",
                "contents": "warranty"
            }
        ],
        "rights": [
            {
                "tag": "ImpliedRight",
                "contents": "commercial-use"
            },
            {
                "tag": "ImpliedRight",
                "contents": "distribution"
            },
            {
                "tag": "ImpliedRight",
                "contents": "modifications"
            },
            {
                "tag": "ImpliedRight",
                "contents": "private-use"
            }
        ],
        "conditions": []
    },
    "__isOsiApproved": true,
    "__impliedText": "Permission to use, copy, modify, and/or distribute this software for any\npurpose with or without fee is hereby granted.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\" AND THE AUTHOR DISCLAIMS ALL WARRANTIES\nWITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR\nANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES\nWHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN\nACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF\nOR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/0BSD.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/0BSD.json"
        ],
        [
            null,
            "http://landley.net/toybox/license.html"
        ],
        [
            "Homepage",
            "http://landley.net/toybox/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/0BSD.svg
