== Abstyles License (Abstyles)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Abstyles License
|Shortname |Abstyles
|Rating |Unknown
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://abstyles+`

=== Comments on (easy) usability

* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Abstyles
* *SPDX:* http://spdx.org/licenses/Abstyles.json

=== Text

....
This program is distributed WITHOUT ANY WARRANTY, express or implied.  

Permission is granted to make and distribute verbatim copies of this
document provided that the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
document under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Abstyles",
        "Abstyles License",
        "scancode://abstyles"
    ],
    "__impliedId": "Abstyles",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Abstyles",
                    "Abstyles",
                    "Abstyles License",
                    "scancode://abstyles"
                ],
                "__impliedId": "Abstyles"
            },
            "shortname": "Abstyles",
            "otherNames": [
                "Abstyles",
                "Abstyles License",
                "scancode://abstyles"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Abstyles License",
            "spdxDetailsURL": "http://spdx.org/licenses/Abstyles.json",
            "_sourceURL": "https://spdx.org/licenses/Abstyles.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Abstyles"
            ],
            "_implications": {
                "__impliedNames": [
                    "Abstyles",
                    "Abstyles License"
                ],
                "__impliedId": "Abstyles",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Abstyles.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Abstyles"
                    ]
                ]
            },
            "spdxLicenseId": "Abstyles"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Abstyles",
            "GPLv3 Compat?": "NO",
            "Short Name": "Abstyles",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Abstyles License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Abstyles License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Abstyles",
            "shortName": "Abstyles License",
            "textUrls": null,
            "text": "This program is distributed WITHOUT ANY WARRANTY, express or implied.  \n\nPermission is granted to make and distribute verbatim copies of this\ndocument provided that the copyright notice and this permission notice are\npreserved on all copies.\n\nPermission is granted to copy and distribute modified versions of this\ndocument under the conditions for verbatim copying, provided that the\nentire resulting derived work is distributed under the terms of a\npermission notice identical to this one.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "CTAN",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/abstyles.yml",
            "key": "abstyles",
            "name": "Abstyles License",
            "spdxId": "Abstyles",
            "_implications": {
                "__impliedNames": [
                    "scancode://abstyles",
                    "Abstyles License",
                    "Abstyles"
                ],
                "__impliedId": "Abstyles",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This program is distributed WITHOUT ANY WARRANTY, express or implied.  \n\nPermission is granted to make and distribute verbatim copies of this\ndocument provided that the copyright notice and this permission notice are\npreserved on all copies.\n\nPermission is granted to copy and distribute modified versions of this\ndocument under the conditions for verbatim copying, provided that the\nentire resulting derived work is distributed under the terms of a\npermission notice identical to this one.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Abstyles"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This program is distributed WITHOUT ANY WARRANTY, express or implied.  \n\nPermission is granted to make and distribute verbatim copies of this\ndocument provided that the copyright notice and this permission notice are\npreserved on all copies.\n\nPermission is granted to copy and distribute modified versions of this\ndocument under the conditions for verbatim copying, provided that the\nentire resulting derived work is distributed under the terms of a\npermission notice identical to this one.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Abstyles.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Abstyles"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Abstyles"
        ]
    ]
}
....