== Abstyles License (Abstyles)

[cols=",",options="header",]
|====================================================
|Key |Value
|Fullname |Abstyles License
|Shortname |Abstyles
|Rating |Unknown, probably Attention or Stop or No-Go
|====================================================

=== Comments on (easy) usability

* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *SPDX:* http://spdx.org/licenses/Abstyles.json
* https://fedoraproject.org/wiki/Licensing/Abstyles

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Abstyles",
        "Abstyles License"
    ],
    "__impliedId": "Abstyles",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Abstyles",
                    "Abstyles",
                    "Abstyles License"
                ],
                "__impliedId": "Abstyles"
            },
            "shortname": "Abstyles",
            "otherNames": [
                "Abstyles",
                "Abstyles License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Abstyles License",
            "spdxDetailsURL": "http://spdx.org/licenses/Abstyles.json",
            "_sourceURL": "https://spdx.org/licenses/Abstyles.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Abstyles"
            ],
            "_implications": {
                "__impliedNames": [
                    "Abstyles",
                    "Abstyles License"
                ],
                "__impliedId": "Abstyles",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Abstyles.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Abstyles"
                    ]
                ]
            },
            "spdxLicenseId": "Abstyles"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Abstyles",
            "GPLv3 Compat?": "NO",
            "Short Name": "Abstyles",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Abstyles License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Abstyles License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Abstyles.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Abstyles"
        ]
    ]
}
....