== Amazon Digital Services License (ADSL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Amazon Digital Services License
|Shortname |ADSL
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://adsl`

=== Comments on (easy) usability

* **↑**``Rating is: Silver'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *Homepage:*
https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense
* *SPDX:* https://spdx.org/licenses/ADSL.html
* *SPDX:* http://spdx.org/licenses/ADSL.json

=== Text

....
This software code is made available "AS IS" without warranties of any kind.

You may copy, display, modify and redistribute the software code either by
itself or as incorporated into your code; provided that you do not remove any
proprietary notices.

Your use of this software code is at your own risk and you waive any claim
against Amazon Digital Services, Inc. or its affiliates with respect to your use
of this software code.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/ADSL.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/adsl.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "ADSL",
        "Amazon Digital Services License",
        "scancode://adsl"
    ],
    "__impliedId": "ADSL",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "ADSL"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ADSL"
                ],
                "__impliedId": "ADSL"
            },
            "shortname": "ADSL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Amazon Digital Services License",
            "spdxDetailsURL": "http://spdx.org/licenses/ADSL.json",
            "_sourceURL": "https://spdx.org/licenses/ADSL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"
            ],
            "_implications": {
                "__impliedNames": [
                    "ADSL",
                    "Amazon Digital Services License"
                ],
                "__impliedId": "ADSL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ADSL.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"
                    ]
                ]
            },
            "spdxLicenseId": "ADSL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense",
            "GPLv3 Compat?": "Yes",
            "Short Name": "ADSL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Amazon Digital Services License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Amazon Digital Services License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "ADSL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense",
            "shortName": "Amazon Digital Services License",
            "textUrls": null,
            "text": "This software code is made available \"AS IS\" without warranties of any kind.\n\nYou may copy, display, modify and redistribute the software code either by\nitself or as incorporated into your code; provided that you do not remove any\nproprietary notices.\n\nYour use of this software code is at your own risk and you waive any claim\nagainst Amazon Digital Services, Inc. or its affiliates with respect to your use\nof this software code.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Amazon Web Services",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/adsl.yml",
            "key": "adsl",
            "name": "Amazon Digital Services License",
            "spdxId": "ADSL",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://adsl",
                    "Amazon Digital Services License",
                    "ADSL"
                ],
                "__impliedId": "ADSL",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This software code is made available \"AS IS\" without warranties of any kind.\n\nYou may copy, display, modify and redistribute the software code either by\nitself or as incorporated into your code; provided that you do not remove any\nproprietary notices.\n\nYour use of this software code is at your own risk and you waive any claim\nagainst Amazon Digital Services, Inc. or its affiliates with respect to your use\nof this software code.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/ADSL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Amazon Digital Services License",
            "id": "ADSL",
            "_implications": {
                "__impliedNames": [
                    "ADSL",
                    "Amazon Digital Services License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ADSL.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This software code is made available \"AS IS\" without warranties of any kind.\n\nYou may copy, display, modify and redistribute the software code either by\nitself or as incorporated into your code; provided that you do not remove any\nproprietary notices.\n\nYour use of this software code is at your own risk and you waive any claim\nagainst Amazon Digital Services, Inc. or its affiliates with respect to your use\nof this software code.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/ADSL.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/ADSL.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/ADSL.svg
