== Academic Free License v2.0 (AFL-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Academic Free License v2.0
|Shortname |AFL-2.0
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/AFL-2.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/AFL-2.0.html
* *SPDX:* http://spdx.org/licenses/AFL-2.0.json
* http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/librariesio/license-compatibility/blob/master/lib/license/licenses.json[librariesio
license-compatibility]
(https://github.com/librariesio/license-compatibility/blob/master/LICENSE.txt[MIT])
* https://spdx.org/licenses/AFL-2.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "AFL-2.0",
        "Academic Free License v2.0"
    ],
    "__impliedId": "AFL-2.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "AFL-2.0"
                ],
                "__impliedId": "AFL-2.0"
            },
            "shortname": "AFL-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Academic Free License v2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/AFL-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/AFL-2.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "AFL-2.0",
                    "Academic Free License v2.0"
                ],
                "__impliedId": "AFL-2.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/AFL-2.0.json"
                    ],
                    [
                        null,
                        "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
                    ]
                ]
            },
            "spdxLicenseId": "AFL-2.0"
        },
        "librariesio license-compatibility": {
            "implications": {
                "__impliedNames": [
                    "AFL-2.0"
                ],
                "__impliedCopyleft": [
                    [
                        "librariesio license-compatibility",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "AFL-2.0",
            "copyleftkind": "NoCopyleft"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "AFL-2.0"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "AFL-2.0",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/AFL-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Academic Free License v2.0",
            "id": "AFL-2.0",
            "_implications": {
                "__impliedNames": [
                    "AFL-2.0",
                    "Academic Free License v2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/AFL-2.0.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ],
        [
            "librariesio license-compatibility",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/AFL-2.0.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/AFL-2.0.json"
        ],
        [
            null,
            "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/AFL-2.0.svg
