== Academic Free License v2.0 (AFL-2.0)

[cols=",",options="header",]
|====================================
|Key |Value
|Fullname |Academic Free License v2.0
|Shortname |AFL-2.0
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |True
|====================================

=== Comments on (easy) usability

* **↑**Is OSI Approved (source:
https://spdx.org/licenses/AFL-2.0.html[SPDX])
* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== URLs

* *SPDX:* http://spdx.org/licenses/AFL-2.0.json
* *SPDX:* https://spdx.org/licenses/AFL-2.0.html
* http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt

=== OSADL Rule

....
USE CASE Source code delivery
	IF Software modification
		YOU MUST Forward Copyright notices
		YOU MUST Forward Patent notice
		YOU MUST Forward Trademark notice
		YOU MUST Forward License notice
		YOU MUST Provide Copyright notices
		YOU MUST Provide Modification notice
		YOU MUST Forward Warranty disclaimer
		YOU MUST NOT Promote
USE CASE Binary delivery
	EITHER
		YOU MUST Include Original source code
			ATTRIBUTE Machine-readable
		IF Software modification
			YOU MUST Forward Copyright notices
			YOU MUST Forward Patent notice
			YOU MUST Forward Trademark notice
			YOU MUST Forward License notice
			YOU MUST Provide Copyright notices
			YOU MUST Provide Modification notice
			YOU MUST Forward Warranty disclaimer
			YOU MUST NOT Promote
	OR
		YOU MUST Provide Delayed source code delivery
		YOU MUST Reference Source code
			ATTRIBUTE Machine-readable
			ATTRIBUTE Via Internet
			ATTRIBUTE No profit
			ATTRIBUTE Duration As long as distributed
PATENT HINTS Yes
....

(source: OSADL License Checklist)

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "AFL-2.0",
        "Academic Free License v2.0"
    ],
    "__impliedId": "AFL-2.0",
    "__hasPatentHint": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "AFL-2.0",
                    "AFL-2.0",
                    "Academic Free License v2.0"
                ],
                "__impliedId": "AFL-2.0"
            },
            "shortname": "AFL-2.0",
            "otherNames": [
                "AFL-2.0",
                "Academic Free License v2.0"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Academic Free License v2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/AFL-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/AFL-2.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "AFL-2.0",
                    "Academic Free License v2.0"
                ],
                "__impliedId": "AFL-2.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/AFL-2.0.json"
                    ],
                    [
                        null,
                        "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
                    ]
                ]
            },
            "spdxLicenseId": "AFL-2.0"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-2.0.txt",
            "spdxId": "AFL-2.0",
            "osadlRule": "USE CASE Source code delivery\r\n\tIF Software modification\n\t\tYOU MUST Forward Copyright notices\n\t\tYOU MUST Forward Patent notice\n\t\tYOU MUST Forward Trademark notice\n\t\tYOU MUST Forward License notice\n\t\tYOU MUST Provide Copyright notices\n\t\tYOU MUST Provide Modification notice\n\t\tYOU MUST Forward Warranty disclaimer\n\t\tYOU MUST NOT Promote\nUSE CASE Binary delivery\r\n\tEITHER\r\n\t\tYOU MUST Include Original source code\n\t\t\tATTRIBUTE Machine-readable\n\t\tIF Software modification\n\t\t\tYOU MUST Forward Copyright notices\n\t\t\tYOU MUST Forward Patent notice\n\t\t\tYOU MUST Forward Trademark notice\n\t\t\tYOU MUST Forward License notice\n\t\t\tYOU MUST Provide Copyright notices\n\t\t\tYOU MUST Provide Modification notice\n\t\t\tYOU MUST Forward Warranty disclaimer\n\t\t\tYOU MUST NOT Promote\n\tOR\r\n\t\tYOU MUST Provide Delayed source code delivery\n\t\tYOU MUST Reference Source code\n\t\t\tATTRIBUTE Machine-readable\n\t\t\tATTRIBUTE Via Internet\n\t\t\tATTRIBUTE No profit\n\t\t\tATTRIBUTE Duration As long as distributed\nPATENT HINTS Yes\n",
            "_implications": {
                "__impliedNames": [
                    "AFL-2.0"
                ],
                "__hasPatentHint": true
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/AFL-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Academic Free License v2.0",
            "id": "AFL-2.0",
            "_implications": {
                "__impliedNames": [
                    "AFL-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/AFL-2.0.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/AFL-2.0.json"
        ],
        [
            null,
            "http://wayback.archive.org/web/20060924134533/http://www.opensource.org/licenses/afl-2.0.txt"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/AFL-2.0.html"
        ]
    ]
}
....