== Afmparse License (Afmparse)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Afmparse License
|Shortname |Afmparse
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://afmparse+`

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Afmparse
* *SPDX:* https://spdx.org/licenses/Afmparse.html
* *SPDX:* http://spdx.org/licenses/Afmparse.json

=== Text

....
This file may be freely copied and redistributed as long as:  

     1) This entire notice continues to be included in the file,  

     2) If the file has been modified in any way, a notice of such modification
     is conspicuously indicated.

PostScript, Display PostScript,and Adobe are registered trademarks of Adobe
Systems Incorporated.

THE INFORMATION BELOW IS FURNISHED AS IS, IS SUBJECT TO CHANGE WITHOUT NOTICE,
AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY ADOBE SYSTEMS INCORPORATED. ADOBE
SYSTEMS INCORPORATED ASSUMES NO RESPONSIBILITY OR LIABILITY FOR ANY ERRORS OR
INACCURACIES, MAKES NO WARRANTY OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WITH
RESPECT TO THIS INFORMATION, AND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES OF
MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSES AND NONINFRINGEMENT OF THIRD
PARTY RIGHTS.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/Afmparse.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/afmparse.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Afmparse",
        "Afmparse License",
        "scancode://afmparse",
        "afmparse License"
    ],
    "__impliedId": "Afmparse",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Afmparse"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Afmparse"
                ],
                "__impliedId": "Afmparse"
            },
            "shortname": "Afmparse",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Afmparse License",
            "spdxDetailsURL": "http://spdx.org/licenses/Afmparse.json",
            "_sourceURL": "https://spdx.org/licenses/Afmparse.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Afmparse"
            ],
            "_implications": {
                "__impliedNames": [
                    "Afmparse",
                    "Afmparse License"
                ],
                "__impliedId": "Afmparse",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Afmparse.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Afmparse"
                    ]
                ]
            },
            "spdxLicenseId": "Afmparse"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Afmparse",
            "GPLv3 Compat?": "Yes",
            "Short Name": "Afmparse",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Afmparse License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Afmparse License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Afmparse"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Afmparse",
            "shortName": "afmparse License",
            "textUrls": null,
            "text": "This file may be freely copied and redistributed as long as:  \n\n     1) This entire notice continues to be included in the file,  \n\n     2) If the file has been modified in any way, a notice of such modification\n     is conspicuously indicated.\n\nPostScript, Display PostScript,and Adobe are registered trademarks of Adobe\nSystems Incorporated.\n\nTHE INFORMATION BELOW IS FURNISHED AS IS, IS SUBJECT TO CHANGE WITHOUT NOTICE,\nAND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY ADOBE SYSTEMS INCORPORATED. ADOBE\nSYSTEMS INCORPORATED ASSUMES NO RESPONSIBILITY OR LIABILITY FOR ANY ERRORS OR\nINACCURACIES, MAKES NO WARRANTY OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WITH\nRESPECT TO THIS INFORMATION, AND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSES AND NONINFRINGEMENT OF THIRD\nPARTY RIGHTS.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Adobe Systems",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/afmparse.yml",
            "key": "afmparse",
            "name": "afmparse License",
            "spdxId": "Afmparse",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://afmparse",
                    "afmparse License",
                    "Afmparse"
                ],
                "__impliedId": "Afmparse",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This file may be freely copied and redistributed as long as:  \n\n     1) This entire notice continues to be included in the file,  \n\n     2) If the file has been modified in any way, a notice of such modification\n     is conspicuously indicated.\n\nPostScript, Display PostScript,and Adobe are registered trademarks of Adobe\nSystems Incorporated.\n\nTHE INFORMATION BELOW IS FURNISHED AS IS, IS SUBJECT TO CHANGE WITHOUT NOTICE,\nAND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY ADOBE SYSTEMS INCORPORATED. ADOBE\nSYSTEMS INCORPORATED ASSUMES NO RESPONSIBILITY OR LIABILITY FOR ANY ERRORS OR\nINACCURACIES, MAKES NO WARRANTY OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WITH\nRESPECT TO THIS INFORMATION, AND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSES AND NONINFRINGEMENT OF THIRD\nPARTY RIGHTS.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Afmparse"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Afmparse.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Afmparse License",
            "id": "Afmparse",
            "_implications": {
                "__impliedNames": [
                    "Afmparse",
                    "Afmparse License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Afmparse.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This file may be freely copied and redistributed as long as:  \n\n     1) This entire notice continues to be included in the file,  \n\n     2) If the file has been modified in any way, a notice of such modification\n     is conspicuously indicated.\n\nPostScript, Display PostScript,and Adobe are registered trademarks of Adobe\nSystems Incorporated.\n\nTHE INFORMATION BELOW IS FURNISHED AS IS, IS SUBJECT TO CHANGE WITHOUT NOTICE,\nAND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY ADOBE SYSTEMS INCORPORATED. ADOBE\nSYSTEMS INCORPORATED ASSUMES NO RESPONSIBILITY OR LIABILITY FOR ANY ERRORS OR\nINACCURACIES, MAKES NO WARRANTY OF ANY KIND (EXPRESS, IMPLIED OR STATUTORY) WITH\nRESPECT TO THIS INFORMATION, AND EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSES AND NONINFRINGEMENT OF THIRD\nPARTY RIGHTS.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Afmparse.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Afmparse.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Afmparse"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Afmparse"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Afmparse.svg