== Affero General Public License v1.0 only (AGPL-1.0-only)

[cols=",",options="header",]
|====================================================
|Key |Value
|Fullname |Affero General Public License v1.0 only
|Shortname |AGPL-1.0-only
|Rating |Unknown, probably Attention or Stop or No-Go
|====================================================

=== Comments on (easy) usability

=== URLs

* *SPDX:* http://spdx.org/licenses/AGPL-1.0-only.json
* http://www.affero.org/oagpl.html

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "AGPL-1.0-only",
        "Affero General Public License v1.0 only"
    ],
    "__impliedId": "AGPL-1.0-only",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "AGPL-1.0-only",
                    "AGPL-1.0-only",
                    "Affero General Public License v1.0 only"
                ],
                "__impliedId": "AGPL-1.0-only"
            },
            "shortname": "AGPL-1.0-only",
            "otherNames": [
                "AGPL-1.0-only",
                "Affero General Public License v1.0 only"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Affero General Public License v1.0 only",
            "spdxDetailsURL": "http://spdx.org/licenses/AGPL-1.0-only.json",
            "_sourceURL": "https://spdx.org/licenses/AGPL-1.0-only.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.affero.org/oagpl.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "AGPL-1.0-only",
                    "Affero General Public License v1.0 only"
                ],
                "__impliedId": "AGPL-1.0-only",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/AGPL-1.0-only.json"
                    ],
                    [
                        null,
                        "http://www.affero.org/oagpl.html"
                    ]
                ]
            },
            "spdxLicenseId": "AGPL-1.0-only"
        },
        "Override": {
            "oNonCommecrial": null,
            "implications": {
                "__impliedNames": [
                    "AGPL-1.0-only"
                ],
                "__impliedId": "AGPL-1.0-only"
            },
            "oName": "AGPL-1.0-only",
            "oOtherLicenseIds": [
                "AGPL-1.0",
                "Affero General Public License (v. 1)"
            ],
            "oDescription": null,
            "oJudgement": null,
            "oRatingState": null
        }
    },
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/AGPL-1.0-only.json"
        ],
        [
            null,
            "http://www.affero.org/oagpl.html"
        ]
    ]
}
....