== AMD's plpa_map.c License (AMDPLPA)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |AMD's plpa_map.c License
|Shortname |AMDPLPA
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode:amdplpa+`
* `+AMD PLPA License+`

=== Comments on (easy) usability

* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:*
https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License
* *SPDX:* http://spdx.org/licenses/AMDPLPA.json
* *SPDX:* https://spdx.org/licenses/AMDPLPA.html

=== Text

....
Redistribution and use in any form of this material and any product thereof including
software in source or binary forms, along with any related documentation, with or
without modification ("this material"), is permitted provided that the following
conditions are met:

     Redistributions of source code of any software must retain the above copyright
     notice and all terms of this license as part of the code.

     Redistributions in binary form of any software must reproduce the above
     copyright notice and all terms of this license in any related documentation
     and/or other materials.

     Neither the names nor trademarks of Advanced Micro Devices, Inc. or any
     copyright holders or contributors may be used to endorse or promote products
     derived from this material without specific prior written permission.

     Notice about U.S. Government restricted rights: This material is provided with
     "RESTRICTED RIGHTS." Use, duplication or disclosure by the U.S. Government is
     subject to the full extent of restrictions set forth in FAR52.227 and
     DFARS252.227 et seq., or any successor or applicable regulations. Use of this
     material by the U.S. Government constitutes acknowledgment of the proprietary
     rights of Advanced Micro Devices, Inc. and any copyright holders and
     contributors.

     ANY BREACH OF ANY TERM OF THIS LICENSE SHALL RESULT IN THE IMMEDIATE REVOCATION
     OF ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS MATERIAL.

THIS MATERIAL IS PROVIDED BY ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS
AND CONTRIBUTORS "AS IS" IN ITS CURRENT CONDITION AND WITHOUT ANY REPRESENTATIONS,
GUARANTEE, OR WARRANTY OF ANY KIND OR IN ANY WAY RELATED TO SUPPORT, INDEMNITY, ERROR
FREE OR UNINTERRUPTED OPERATION, OR THAT IT IS FREE FROM DEFECTS OR VIRUSES. ALL
OBLIGATIONS ARE HEREBY DISCLAIMED - WHETHER EXPRESS, IMPLIED, OR STATUTORY -
INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OPERABILITY, QUALITY OF
SERVICE, OR NON-INFRINGEMENT. IN NO EVENT SHALL ADVANCED MICRO DEVICES, INC. OR ANY
COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, REVENUE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED OR BASED ON ANY THEORY OF LIABILITY
ARISING IN ANY WAY RELATED TO THIS MATERIAL, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE. THE ENTIRE AND AGGREGATE LIABILITY OF ADVANCED MICRO DEVICES, INC. AND
ANY COPYRIGHT HOLDERS AND CONTRIBUTORS SHALL NOT EXCEED TEN DOLLARS (US $10.00).
ANYONE REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL ACCEPTS THIS ALLOCATION OF
RISK AND AGREES TO RELEASE ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS AND
CONTRIBUTORS FROM ANY AND ALL LIABILITIES, OBLIGATIONS, CLAIMS, OR DEMANDS IN EXCESS
OF TEN DOLLARS (US $10.00). THE FOREGOING ARE ESSENTIAL TERMS OF THIS LICENSE AND, IF
ANY OF THESE TERMS ARE CONSTRUED AS UNENFORCEABLE, FAIL IN ESSENTIAL PURPOSE, OR
BECOME VOID OR DETRIMENTAL TO ADVANCED MICRO DEVICES, INC. OR ANY COPYRIGHT HOLDERS
OR CONTRIBUTORS FOR ANY REASON, THEN ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS
MATERIAL SHALL TERMINATE IMMEDIATELY. MOREOVER, THE FOREGOING SHALL SURVIVE ANY
EXPIRATION OR TERMINATION OF THIS LICENSE OR ANY AGREEMENT OR ACCESS OR USE RELATED
TO THIS MATERIAL.

NOTICE IS HEREBY PROVIDED, AND BY REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL
SUCH NOTICE IS ACKNOWLEDGED, THAT THIS MATERIAL MAY BE SUBJECT TO RESTRICTIONS UNDER
THE LAWS AND REGULATIONS OF THE UNITED STATES OR OTHER COUNTRIES, WHICH INCLUDE BUT
ARE NOT LIMITED TO, U.S. EXPORT CONTROL LAWS SUCH AS THE EXPORT ADMINISTRATION
REGULATIONS AND NATIONAL SECURITY CONTROLS AS DEFINED THEREUNDER, AS WELL AS STATE
DEPARTMENT CONTROLS UNDER THE U.S. MUNITIONS LIST. THIS MATERIAL MAY NOT BE USED,
RELEASED, TRANSFERRED, IMPORTED, EXPORTED AND/OR RE- EXPORTED IN ANY MANNER
PROHIBITED UNDER ANY APPLICABLE LAWS, INCLUDING U.S. EXPORT CONTROL LAWS REGARDING
SPECIFICALLY DESIGNATED PERSONS, COUNTRIES AND NATIONALS OF COUNTRIES SUBJECT TO
NATIONAL SECURITY CONTROLS. MOREOVER, THE FOREGOING SHALL SURVIVE ANY EXPIRATION OR
TERMINATION OF ANY LICENSE OR AGREEMENT OR ACCESS OR USE RELATED TO THIS MATERIAL.

This license forms the entire agreement regarding the subject matter hereof and
supersedes all proposals and prior discussions and writings between the parties with
respect thereto. This license does not affect any ownership, rights, title, or
interest in, or relating to, this material. No terms of this license can be modified
or waived, and no breach of this license can be excused, unless done so in a writing
signed by all affected parties. Each term of this license is separately enforceable.
If any term of this license is determined to be or becomes unenforceable or illegal,
such term shall be reformed to the minimum extent necessary in order for this license
to remain in effect in accordance with its terms as modified by such reformation.
This license shall be governed by and construed in accordance with the laws of the
State of Texas without regard to rules on conflicts of law of any state or
jurisdiction or the United Nations Convention on the International Sale of Goods. All
disputes arising out of this license shall be subject to the jurisdiction of the
federal and state courts in Austin, Texas, and all defenses are hereby waived
concerning personal jurisdiction and venue of these courts.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "AMDPLPA",
        "AMD's plpa_map.c License",
        "scancode:amdplpa",
        "AMD PLPA License"
    ],
    "__impliedId": "AMDPLPA",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "AMDPLPA",
                    "AMDPLPA",
                    "AMD's plpa_map.c License",
                    "scancode:amdplpa",
                    "AMD PLPA License"
                ],
                "__impliedId": "AMDPLPA"
            },
            "shortname": "AMDPLPA",
            "otherNames": [
                "AMDPLPA",
                "AMD's plpa_map.c License",
                "scancode:amdplpa",
                "AMD PLPA License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "AMD's plpa_map.c License",
            "spdxDetailsURL": "http://spdx.org/licenses/AMDPLPA.json",
            "_sourceURL": "https://spdx.org/licenses/AMDPLPA.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "AMDPLPA",
                    "AMD's plpa_map.c License"
                ],
                "__impliedId": "AMDPLPA",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/AMDPLPA.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"
                    ]
                ]
            },
            "spdxLicenseId": "AMDPLPA"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License",
            "GPLv3 Compat?": "NO",
            "Short Name": "AMDPLPA",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "AMD's plpa_map.c License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "AMD's plpa_map.c License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License",
            "shortName": "AMD PLPA License",
            "textUrls": null,
            "text": "Redistribution and use in any form of this material and any product thereof including\nsoftware in source or binary forms, along with any related documentation, with or\nwithout modification (\"this material\"), is permitted provided that the following\nconditions are met:\n\n     Redistributions of source code of any software must retain the above copyright\n     notice and all terms of this license as part of the code.\n\n     Redistributions in binary form of any software must reproduce the above\n     copyright notice and all terms of this license in any related documentation\n     and/or other materials.\n\n     Neither the names nor trademarks of Advanced Micro Devices, Inc. or any\n     copyright holders or contributors may be used to endorse or promote products\n     derived from this material without specific prior written permission.\n\n     Notice about U.S. Government restricted rights: This material is provided with\n     \"RESTRICTED RIGHTS.\" Use, duplication or disclosure by the U.S. Government is\n     subject to the full extent of restrictions set forth in FAR52.227 and\n     DFARS252.227 et seq., or any successor or applicable regulations. Use of this\n     material by the U.S. Government constitutes acknowledgment of the proprietary\n     rights of Advanced Micro Devices, Inc. and any copyright holders and\n     contributors.\n\n     ANY BREACH OF ANY TERM OF THIS LICENSE SHALL RESULT IN THE IMMEDIATE REVOCATION\n     OF ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS MATERIAL.\n\nTHIS MATERIAL IS PROVIDED BY ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS\nAND CONTRIBUTORS \"AS IS\" IN ITS CURRENT CONDITION AND WITHOUT ANY REPRESENTATIONS,\nGUARANTEE, OR WARRANTY OF ANY KIND OR IN ANY WAY RELATED TO SUPPORT, INDEMNITY, ERROR\nFREE OR UNINTERRUPTED OPERATION, OR THAT IT IS FREE FROM DEFECTS OR VIRUSES. ALL\nOBLIGATIONS ARE HEREBY DISCLAIMED - WHETHER EXPRESS, IMPLIED, OR STATUTORY -\nINCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OPERABILITY, QUALITY OF\nSERVICE, OR NON-INFRINGEMENT. IN NO EVENT SHALL ADVANCED MICRO DEVICES, INC. OR ANY\nCOPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\nTO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, REVENUE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED OR BASED ON ANY THEORY OF LIABILITY\nARISING IN ANY WAY RELATED TO THIS MATERIAL, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE. THE ENTIRE AND AGGREGATE LIABILITY OF ADVANCED MICRO DEVICES, INC. AND\nANY COPYRIGHT HOLDERS AND CONTRIBUTORS SHALL NOT EXCEED TEN DOLLARS (US $10.00).\nANYONE REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL ACCEPTS THIS ALLOCATION OF\nRISK AND AGREES TO RELEASE ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS AND\nCONTRIBUTORS FROM ANY AND ALL LIABILITIES, OBLIGATIONS, CLAIMS, OR DEMANDS IN EXCESS\nOF TEN DOLLARS (US $10.00). THE FOREGOING ARE ESSENTIAL TERMS OF THIS LICENSE AND, IF\nANY OF THESE TERMS ARE CONSTRUED AS UNENFORCEABLE, FAIL IN ESSENTIAL PURPOSE, OR\nBECOME VOID OR DETRIMENTAL TO ADVANCED MICRO DEVICES, INC. OR ANY COPYRIGHT HOLDERS\nOR CONTRIBUTORS FOR ANY REASON, THEN ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS\nMATERIAL SHALL TERMINATE IMMEDIATELY. MOREOVER, THE FOREGOING SHALL SURVIVE ANY\nEXPIRATION OR TERMINATION OF THIS LICENSE OR ANY AGREEMENT OR ACCESS OR USE RELATED\nTO THIS MATERIAL.\n\nNOTICE IS HEREBY PROVIDED, AND BY REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL\nSUCH NOTICE IS ACKNOWLEDGED, THAT THIS MATERIAL MAY BE SUBJECT TO RESTRICTIONS UNDER\nTHE LAWS AND REGULATIONS OF THE UNITED STATES OR OTHER COUNTRIES, WHICH INCLUDE BUT\nARE NOT LIMITED TO, U.S. EXPORT CONTROL LAWS SUCH AS THE EXPORT ADMINISTRATION\nREGULATIONS AND NATIONAL SECURITY CONTROLS AS DEFINED THEREUNDER, AS WELL AS STATE\nDEPARTMENT CONTROLS UNDER THE U.S. MUNITIONS LIST. THIS MATERIAL MAY NOT BE USED,\nRELEASED, TRANSFERRED, IMPORTED, EXPORTED AND/OR RE- EXPORTED IN ANY MANNER\nPROHIBITED UNDER ANY APPLICABLE LAWS, INCLUDING U.S. EXPORT CONTROL LAWS REGARDING\nSPECIFICALLY DESIGNATED PERSONS, COUNTRIES AND NATIONALS OF COUNTRIES SUBJECT TO\nNATIONAL SECURITY CONTROLS. MOREOVER, THE FOREGOING SHALL SURVIVE ANY EXPIRATION OR\nTERMINATION OF ANY LICENSE OR AGREEMENT OR ACCESS OR USE RELATED TO THIS MATERIAL.\n\nThis license forms the entire agreement regarding the subject matter hereof and\nsupersedes all proposals and prior discussions and writings between the parties with\nrespect thereto. This license does not affect any ownership, rights, title, or\ninterest in, or relating to, this material. No terms of this license can be modified\nor waived, and no breach of this license can be excused, unless done so in a writing\nsigned by all affected parties. Each term of this license is separately enforceable.\nIf any term of this license is determined to be or becomes unenforceable or illegal,\nsuch term shall be reformed to the minimum extent necessary in order for this license\nto remain in effect in accordance with its terms as modified by such reformation.\nThis license shall be governed by and construed in accordance with the laws of the\nState of Texas without regard to rules on conflicts of law of any state or\njurisdiction or the United Nations Convention on the International Sale of Goods. All\ndisputes arising out of this license shall be subject to the jurisdiction of the\nfederal and state courts in Austin, Texas, and all defenses are hereby waived\nconcerning personal jurisdiction and venue of these courts.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Advanced Micro Devices",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/amdplpa.yml",
            "key": "amdplpa",
            "name": "AMD PLPA License",
            "spdxId": "AMDPLPA",
            "_implications": {
                "__impliedNames": [
                    "scancode:amdplpa",
                    "AMD PLPA License",
                    "AMDPLPA"
                ],
                "__impliedId": "AMDPLPA",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in any form of this material and any product thereof including\nsoftware in source or binary forms, along with any related documentation, with or\nwithout modification (\"this material\"), is permitted provided that the following\nconditions are met:\n\n     Redistributions of source code of any software must retain the above copyright\n     notice and all terms of this license as part of the code.\n\n     Redistributions in binary form of any software must reproduce the above\n     copyright notice and all terms of this license in any related documentation\n     and/or other materials.\n\n     Neither the names nor trademarks of Advanced Micro Devices, Inc. or any\n     copyright holders or contributors may be used to endorse or promote products\n     derived from this material without specific prior written permission.\n\n     Notice about U.S. Government restricted rights: This material is provided with\n     \"RESTRICTED RIGHTS.\" Use, duplication or disclosure by the U.S. Government is\n     subject to the full extent of restrictions set forth in FAR52.227 and\n     DFARS252.227 et seq., or any successor or applicable regulations. Use of this\n     material by the U.S. Government constitutes acknowledgment of the proprietary\n     rights of Advanced Micro Devices, Inc. and any copyright holders and\n     contributors.\n\n     ANY BREACH OF ANY TERM OF THIS LICENSE SHALL RESULT IN THE IMMEDIATE REVOCATION\n     OF ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS MATERIAL.\n\nTHIS MATERIAL IS PROVIDED BY ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS\nAND CONTRIBUTORS \"AS IS\" IN ITS CURRENT CONDITION AND WITHOUT ANY REPRESENTATIONS,\nGUARANTEE, OR WARRANTY OF ANY KIND OR IN ANY WAY RELATED TO SUPPORT, INDEMNITY, ERROR\nFREE OR UNINTERRUPTED OPERATION, OR THAT IT IS FREE FROM DEFECTS OR VIRUSES. ALL\nOBLIGATIONS ARE HEREBY DISCLAIMED - WHETHER EXPRESS, IMPLIED, OR STATUTORY -\nINCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OPERABILITY, QUALITY OF\nSERVICE, OR NON-INFRINGEMENT. IN NO EVENT SHALL ADVANCED MICRO DEVICES, INC. OR ANY\nCOPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\nTO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, REVENUE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED OR BASED ON ANY THEORY OF LIABILITY\nARISING IN ANY WAY RELATED TO THIS MATERIAL, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE. THE ENTIRE AND AGGREGATE LIABILITY OF ADVANCED MICRO DEVICES, INC. AND\nANY COPYRIGHT HOLDERS AND CONTRIBUTORS SHALL NOT EXCEED TEN DOLLARS (US $10.00).\nANYONE REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL ACCEPTS THIS ALLOCATION OF\nRISK AND AGREES TO RELEASE ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS AND\nCONTRIBUTORS FROM ANY AND ALL LIABILITIES, OBLIGATIONS, CLAIMS, OR DEMANDS IN EXCESS\nOF TEN DOLLARS (US $10.00). THE FOREGOING ARE ESSENTIAL TERMS OF THIS LICENSE AND, IF\nANY OF THESE TERMS ARE CONSTRUED AS UNENFORCEABLE, FAIL IN ESSENTIAL PURPOSE, OR\nBECOME VOID OR DETRIMENTAL TO ADVANCED MICRO DEVICES, INC. OR ANY COPYRIGHT HOLDERS\nOR CONTRIBUTORS FOR ANY REASON, THEN ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS\nMATERIAL SHALL TERMINATE IMMEDIATELY. MOREOVER, THE FOREGOING SHALL SURVIVE ANY\nEXPIRATION OR TERMINATION OF THIS LICENSE OR ANY AGREEMENT OR ACCESS OR USE RELATED\nTO THIS MATERIAL.\n\nNOTICE IS HEREBY PROVIDED, AND BY REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL\nSUCH NOTICE IS ACKNOWLEDGED, THAT THIS MATERIAL MAY BE SUBJECT TO RESTRICTIONS UNDER\nTHE LAWS AND REGULATIONS OF THE UNITED STATES OR OTHER COUNTRIES, WHICH INCLUDE BUT\nARE NOT LIMITED TO, U.S. EXPORT CONTROL LAWS SUCH AS THE EXPORT ADMINISTRATION\nREGULATIONS AND NATIONAL SECURITY CONTROLS AS DEFINED THEREUNDER, AS WELL AS STATE\nDEPARTMENT CONTROLS UNDER THE U.S. MUNITIONS LIST. THIS MATERIAL MAY NOT BE USED,\nRELEASED, TRANSFERRED, IMPORTED, EXPORTED AND/OR RE- EXPORTED IN ANY MANNER\nPROHIBITED UNDER ANY APPLICABLE LAWS, INCLUDING U.S. EXPORT CONTROL LAWS REGARDING\nSPECIFICALLY DESIGNATED PERSONS, COUNTRIES AND NATIONALS OF COUNTRIES SUBJECT TO\nNATIONAL SECURITY CONTROLS. MOREOVER, THE FOREGOING SHALL SURVIVE ANY EXPIRATION OR\nTERMINATION OF ANY LICENSE OR AGREEMENT OR ACCESS OR USE RELATED TO THIS MATERIAL.\n\nThis license forms the entire agreement regarding the subject matter hereof and\nsupersedes all proposals and prior discussions and writings between the parties with\nrespect thereto. This license does not affect any ownership, rights, title, or\ninterest in, or relating to, this material. No terms of this license can be modified\nor waived, and no breach of this license can be excused, unless done so in a writing\nsigned by all affected parties. Each term of this license is separately enforceable.\nIf any term of this license is determined to be or becomes unenforceable or illegal,\nsuch term shall be reformed to the minimum extent necessary in order for this license\nto remain in effect in accordance with its terms as modified by such reformation.\nThis license shall be governed by and construed in accordance with the laws of the\nState of Texas without regard to rules on conflicts of law of any state or\njurisdiction or the United Nations Convention on the International Sale of Goods. All\ndisputes arising out of this license shall be subject to the jurisdiction of the\nfederal and state courts in Austin, Texas, and all defenses are hereby waived\nconcerning personal jurisdiction and venue of these courts.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/AMDPLPA.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "AMD's plpa_map.c License",
            "id": "AMDPLPA",
            "_implications": {
                "__impliedNames": [
                    "AMDPLPA"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/AMDPLPA.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in any form of this material and any product thereof including\nsoftware in source or binary forms, along with any related documentation, with or\nwithout modification (\"this material\"), is permitted provided that the following\nconditions are met:\n\n     Redistributions of source code of any software must retain the above copyright\n     notice and all terms of this license as part of the code.\n\n     Redistributions in binary form of any software must reproduce the above\n     copyright notice and all terms of this license in any related documentation\n     and/or other materials.\n\n     Neither the names nor trademarks of Advanced Micro Devices, Inc. or any\n     copyright holders or contributors may be used to endorse or promote products\n     derived from this material without specific prior written permission.\n\n     Notice about U.S. Government restricted rights: This material is provided with\n     \"RESTRICTED RIGHTS.\" Use, duplication or disclosure by the U.S. Government is\n     subject to the full extent of restrictions set forth in FAR52.227 and\n     DFARS252.227 et seq., or any successor or applicable regulations. Use of this\n     material by the U.S. Government constitutes acknowledgment of the proprietary\n     rights of Advanced Micro Devices, Inc. and any copyright holders and\n     contributors.\n\n     ANY BREACH OF ANY TERM OF THIS LICENSE SHALL RESULT IN THE IMMEDIATE REVOCATION\n     OF ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS MATERIAL.\n\nTHIS MATERIAL IS PROVIDED BY ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS\nAND CONTRIBUTORS \"AS IS\" IN ITS CURRENT CONDITION AND WITHOUT ANY REPRESENTATIONS,\nGUARANTEE, OR WARRANTY OF ANY KIND OR IN ANY WAY RELATED TO SUPPORT, INDEMNITY, ERROR\nFREE OR UNINTERRUPTED OPERATION, OR THAT IT IS FREE FROM DEFECTS OR VIRUSES. ALL\nOBLIGATIONS ARE HEREBY DISCLAIMED - WHETHER EXPRESS, IMPLIED, OR STATUTORY -\nINCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OPERABILITY, QUALITY OF\nSERVICE, OR NON-INFRINGEMENT. IN NO EVENT SHALL ADVANCED MICRO DEVICES, INC. OR ANY\nCOPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\nTO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, REVENUE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED OR BASED ON ANY THEORY OF LIABILITY\nARISING IN ANY WAY RELATED TO THIS MATERIAL, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE. THE ENTIRE AND AGGREGATE LIABILITY OF ADVANCED MICRO DEVICES, INC. AND\nANY COPYRIGHT HOLDERS AND CONTRIBUTORS SHALL NOT EXCEED TEN DOLLARS (US $10.00).\nANYONE REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL ACCEPTS THIS ALLOCATION OF\nRISK AND AGREES TO RELEASE ADVANCED MICRO DEVICES, INC. AND ANY COPYRIGHT HOLDERS AND\nCONTRIBUTORS FROM ANY AND ALL LIABILITIES, OBLIGATIONS, CLAIMS, OR DEMANDS IN EXCESS\nOF TEN DOLLARS (US $10.00). THE FOREGOING ARE ESSENTIAL TERMS OF THIS LICENSE AND, IF\nANY OF THESE TERMS ARE CONSTRUED AS UNENFORCEABLE, FAIL IN ESSENTIAL PURPOSE, OR\nBECOME VOID OR DETRIMENTAL TO ADVANCED MICRO DEVICES, INC. OR ANY COPYRIGHT HOLDERS\nOR CONTRIBUTORS FOR ANY REASON, THEN ALL RIGHTS TO REDISTRIBUTE, ACCESS OR USE THIS\nMATERIAL SHALL TERMINATE IMMEDIATELY. MOREOVER, THE FOREGOING SHALL SURVIVE ANY\nEXPIRATION OR TERMINATION OF THIS LICENSE OR ANY AGREEMENT OR ACCESS OR USE RELATED\nTO THIS MATERIAL.\n\nNOTICE IS HEREBY PROVIDED, AND BY REDISTRIBUTING OR ACCESSING OR USING THIS MATERIAL\nSUCH NOTICE IS ACKNOWLEDGED, THAT THIS MATERIAL MAY BE SUBJECT TO RESTRICTIONS UNDER\nTHE LAWS AND REGULATIONS OF THE UNITED STATES OR OTHER COUNTRIES, WHICH INCLUDE BUT\nARE NOT LIMITED TO, U.S. EXPORT CONTROL LAWS SUCH AS THE EXPORT ADMINISTRATION\nREGULATIONS AND NATIONAL SECURITY CONTROLS AS DEFINED THEREUNDER, AS WELL AS STATE\nDEPARTMENT CONTROLS UNDER THE U.S. MUNITIONS LIST. THIS MATERIAL MAY NOT BE USED,\nRELEASED, TRANSFERRED, IMPORTED, EXPORTED AND/OR RE- EXPORTED IN ANY MANNER\nPROHIBITED UNDER ANY APPLICABLE LAWS, INCLUDING U.S. EXPORT CONTROL LAWS REGARDING\nSPECIFICALLY DESIGNATED PERSONS, COUNTRIES AND NATIONALS OF COUNTRIES SUBJECT TO\nNATIONAL SECURITY CONTROLS. MOREOVER, THE FOREGOING SHALL SURVIVE ANY EXPIRATION OR\nTERMINATION OF ANY LICENSE OR AGREEMENT OR ACCESS OR USE RELATED TO THIS MATERIAL.\n\nThis license forms the entire agreement regarding the subject matter hereof and\nsupersedes all proposals and prior discussions and writings between the parties with\nrespect thereto. This license does not affect any ownership, rights, title, or\ninterest in, or relating to, this material. No terms of this license can be modified\nor waived, and no breach of this license can be excused, unless done so in a writing\nsigned by all affected parties. Each term of this license is separately enforceable.\nIf any term of this license is determined to be or becomes unenforceable or illegal,\nsuch term shall be reformed to the minimum extent necessary in order for this license\nto remain in effect in accordance with its terms as modified by such reformation.\nThis license shall be governed by and construed in accordance with the laws of the\nState of Texas without regard to rules on conflicts of law of any state or\njurisdiction or the United Nations Convention on the International Sale of Goods. All\ndisputes arising out of this license shall be subject to the jurisdiction of the\nfederal and state courts in Austin, Texas, and all defenses are hereby waived\nconcerning personal jurisdiction and venue of these courts.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/AMDPLPA.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/AMDPLPA.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/AMD_plpa_map_License"
        ]
    ]
}
....