== Apple MIT License (AML)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Apple MIT License
|Shortname |AML
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/AML.html
* *SPDX:* http://spdx.org/licenses/AML.json
* https://fedoraproject.org/wiki/Licensing/Apple_MIT_License

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/AML.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "AML",
        "Apple MIT License"
    ],
    "__impliedId": "AML",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "AML"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "AML"
                ],
                "__impliedId": "AML"
            },
            "shortname": "AML",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Apple MIT License",
            "spdxDetailsURL": "http://spdx.org/licenses/AML.json",
            "_sourceURL": "https://spdx.org/licenses/AML.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Apple_MIT_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "AML",
                    "Apple MIT License"
                ],
                "__impliedId": "AML",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/AML.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Apple_MIT_License"
                    ]
                ]
            },
            "spdxLicenseId": "AML"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Apple_MIT_License",
            "GPLv3 Compat?": "Yes",
            "Short Name": "AML",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Apple MIT License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Apple MIT License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "AML"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/AML.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Apple MIT License",
            "id": "AML",
            "_implications": {
                "__impliedNames": [
                    "AML",
                    "Apple MIT License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/AML.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/AML.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/AML.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Apple_MIT_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/AML.svg
