== Apache License 1.1 (Apache-1.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Apache License 1.1
|Shortname |Apache-1.1
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+Apache (v1.1)+`
* `+Apache Software License 1.1+`
* `+ASL 1.1+`
* `+Apache Software License, Version 1.1+`
* `+scancode://apache-1.1+`
* `+Apache 1.1+`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/Apache-1.1.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Older versions of the Apache License (1.0 and 1.1) are also
DFSG free, but the Apache Software Foundation recommends using the
Apache 2.0 license instead.'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``Per SPDX.org, this license is OSI certified. This license has been
superseded by Apache 2.0 '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/apache-1.1.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* http://www.apache.org/licenses/
* *OSI Page:* https://opensource.org/licenses/Apache-1.1
* *SPDX:* http://spdx.org/licenses/Apache-1.1.json
* *SPDX:* https://spdx.org/licenses/Apache-1.1.html
* *open-license:* http://open-license.hitachi.com/licenses/12
* http://apache.org/licenses/LICENSE-1.1

=== Description from open-license

....
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use binaries generated from modified source code

....

....
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribution of Modified Source Code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license

....

....
Actions:
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribute the generated binaries from modified source code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license

....

....
Description: The acknowledgements are here: "This product includes software developed by the Apache Software Foundation (http://www.apache.org/)." This acknowledgement may be included in the software itself.
Actions:
- Include end-user documentation in the distribution

Conditions:
OBLIGATION: Acknowledgements

....

....
Description: To use the names "Apache" and "Apache Software Foundation". apache@apache.orgに連絡する.
Actions:
- Use the name to endorse and promote derived products

Conditions:
REQUISITE: Get special permission in writing.

....

....
Description: "If you use the name "Apache". apache@apache.orgに連絡する.
Actions:
- Use the name of the product or part of the name of the product from which it was derived

Conditions:
REQUISITE: Get special permission in writing.

....

(source: Hitachi open-license)

=== Text

....
The Apache Software License, Version 1.1

Copyright (c) 2000 The Apache Software Foundation.  All rights
reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in
   the documentation and/or other materials provided with the
   distribution.

3. The end-user documentation included with the redistribution,
   if any, must include the following acknowledgment:
      "This product includes software developed by the
       Apache Software Foundation (http://www.apache.org/)."
   Alternately, this acknowledgment may appear in the software itself,
   if and wherever such third-party acknowledgments normally appear.

4. The names "Apache" and "Apache Software Foundation" must
   not be used to endorse or promote products derived from this
   software without prior written permission. For written
   permission, please contact apache@apache.org.

5. Products derived from this software may not be called "Apache",
   nor may "Apache" appear in their name, without prior written
   permission of the Apache Software Foundation.

THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* Override
* https://spdx.org/licenses/Apache-1.1.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/apache-1.1.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/finos/OSLC-handbook/blob/master/src/Apache-1.1.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Apache-1.1",
        "Apache (v1.1)",
        "Apache Software License 1.1",
        "ASL 1.1",
        "Apache Software License, Version 1.1",
        "Apache License 1.1",
        "scancode://apache-1.1",
        "Apache 1.1"
    ],
    "__impliedId": "Apache-1.1",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "ASL 1.1",
        "The Apache Software License (ASL)"
    ],
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified. This license has been\nsuperseded by Apache 2.0\n"
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "retired",
            "domain_software": true,
            "url": "https://opensource.org/licenses/Apache-1.1",
            "maintainer": "Apache Foundation",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "Apache-1.1",
            "title": "Apache Software License 1.1",
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache Software License 1.1"
                ],
                "__impliedId": "Apache-1.1",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/Apache-1.1"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Apache-1.1"
                ],
                "__impliedId": "Apache-1.1"
            },
            "shortname": "Apache-1.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Apache License 1.1",
            "spdxDetailsURL": "http://spdx.org/licenses/Apache-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/Apache-1.1.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://apache.org/licenses/LICENSE-1.1",
                "https://opensource.org/licenses/Apache-1.1"
            ],
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache License 1.1"
                ],
                "__impliedId": "Apache-1.1",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Apache-1.1.json"
                    ],
                    [
                        null,
                        "http://apache.org/licenses/LICENSE-1.1"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/Apache-1.1"
                    ]
                ]
            },
            "spdxLicenseId": "Apache-1.1"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.apache.org/licenses/LICENSE-1.1",
            "GPLv3 Compat?": "NO",
            "Short Name": "ASL 1.1",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Apache Software License 1.1",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Apache Software License 1.1"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "ASL 1.1"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://opensource.org/licenses/Apache-1.1",
                "https://opensource.org/licenses/Apache-1.1"
            ],
            "homepageUrl": "http://www.apache.org/licenses/",
            "shortName": "Apache 1.1",
            "textUrls": null,
            "text": "The Apache Software License, Version 1.1\n\nCopyright (c) 2000 The Apache Software Foundation.  All rights\nreserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright\n   notice, this list of conditions and the following disclaimer in\n   the documentation and/or other materials provided with the\n   distribution.\n\n3. The end-user documentation included with the redistribution,\n   if any, must include the following acknowledgment:\n      \"This product includes software developed by the\n       Apache Software Foundation (http://www.apache.org/).\"\n   Alternately, this acknowledgment may appear in the software itself,\n   if and wherever such third-party acknowledgments normally appear.\n\n4. The names \"Apache\" and \"Apache Software Foundation\" must\n   not be used to endorse or promote products derived from this\n   software without prior written permission. For written\n   permission, please contact apache@apache.org.\n\n5. Products derived from this software may not be called \"Apache\",\n   nor may \"Apache\" appear in their name, without prior written\n   permission of the Apache Software Foundation.\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\nOF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR\nITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Apache Software Foundation",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/apache-1.1.yml",
            "key": "apache-1.1",
            "name": "Apache License 1.1",
            "spdxId": "Apache-1.1",
            "notes": "Per SPDX.org, this license is OSI certified. This license has been\nsuperseded by Apache 2.0\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://apache-1.1",
                    "Apache 1.1",
                    "Apache-1.1"
                ],
                "__impliedId": "Apache-1.1",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified. This license has been\nsuperseded by Apache 2.0\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The Apache Software License, Version 1.1\n\nCopyright (c) 2000 The Apache Software Foundation.  All rights\nreserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright\n   notice, this list of conditions and the following disclaimer in\n   the documentation and/or other materials provided with the\n   distribution.\n\n3. The end-user documentation included with the redistribution,\n   if any, must include the following acknowledgment:\n      \"This product includes software developed by the\n       Apache Software Foundation (http://www.apache.org/).\"\n   Alternately, this acknowledgment may appear in the software itself,\n   if and wherever such third-party acknowledgments normally appear.\n\n4. The names \"Apache\" and \"Apache Software Foundation\" must\n   not be used to endorse or promote products derived from this\n   software without prior written permission. For written\n   permission, please contact apache@apache.org.\n\n5. Products derived from this software may not be called \"Apache\",\n   nor may \"Apache\" appear in their name, without prior written\n   permission of the Apache Software Foundation.\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\nOF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR\nITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.apache.org/licenses/"
                    ],
                    [
                        null,
                        "http://opensource.org/licenses/Apache-1.1"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/Apache-1.1"
                    ]
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "The Apache Software License (ASL)",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1"
                ],
                "__impliedAmbiguousNames": [
                    "The Apache Software License (ASL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Older versions of the Apache License (1.0 and 1.1) are also DFSG free, but the Apache Software Foundation recommends using the Apache 2.0 license instead."
                        }
                    ]
                ]
            },
            "Comment": "Older versions of the Apache License (1.0 and 1.1) are also DFSG free, but the Apache Software Foundation recommends using the Apache 2.0 license instead.",
            "LicenseId": "Apache-1.1"
        },
        "Override": {
            "oNonCommecrial": null,
            "implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache (v1.1)",
                    "Apache Software License 1.1",
                    "ASL 1.1",
                    "Apache Software License, Version 1.1"
                ],
                "__impliedId": "Apache-1.1"
            },
            "oName": "Apache-1.1",
            "oOtherLicenseIds": [
                "Apache (v1.1)",
                "Apache Software License 1.1",
                "ASL 1.1",
                "Apache Software License, Version 1.1"
            ],
            "oDescription": null,
            "oJudgement": null,
            "oCompatibilities": null,
            "oRatingState": null
        },
        "Hitachi open-license": {
            "notices": [
                {
                    "content": "the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of commercial usability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "neither the Apache Software Foundation nor any contributor has been advised of the possibility of such damages, for any cause whatsoever, regardless of how caused, and regardless of whether liability is based on contract, strict liability or tort (including negligence), even if advised of the possibility of such damages. for any direct, indirect, special, incidental, punitive, or consequential damages (including, but not limited to, compensation for procurement of substitute goods or substitute services, loss of use, loss of data, loss of profits, or business interruption) arising out of the use of such software. No liability (including but not limited to indemnification) shall be assumed."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/12",
            "content": "/* ====================================================================\r\n * The Apache Software License, Version 1.1\r\n *\r\n * Copyright (c) 2000 The Apache Software Foundation.  All rights\r\n * reserved.\r\n *\r\n * Redistribution and use in source and binary forms, with or without\r\n * modification, are permitted provided that the following conditions\r\n * are met:\r\n *\r\n * 1. Redistributions of source code must retain the above copyright\r\n *    notice, this list of conditions and the following disclaimer.\r\n *\r\n * 2. Redistributions in binary form must reproduce the above copyright\r\n *    notice, this list of conditions and the following disclaimer in\r\n *    the documentation and/or other materials provided with the\r\n *    distribution.\r\n *\r\n * 3. The end-user documentation included with the redistribution,\r\n *    if any, must include the following acknowledgment:\r\n *       \"This product includes software developed by the\r\n *        Apache Software Foundation (http://www.apache.org/).\"\r\n *    Alternately, this acknowledgment may appear in the software itself,\r\n *    if and wherever such third-party acknowledgments normally appear.\r\n *\r\n * 4. The names \"Apache\" and \"Apache Software Foundation\" must\r\n *    not be used to endorse or promote products derived from this\r\n *    software without prior written permission. For written\r\n *    permission, please contact apache@apache.org.\r\n *\r\n * 5. Products derived from this software may not be called \"Apache\",\r\n *    nor may \"Apache\" appear in their name, without prior written\r\n *    permission of the Apache Software Foundation.\r\n *\r\n * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED\r\n * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\r\n * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\r\n * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR\r\n * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\r\n * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\n * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\r\n * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\r\n * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\r\n * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\r\n * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\r\n * SUCH DAMAGE.\r\n * ====================================================================\r\n *\r\n * This software consists of voluntary contributions made by many\r\n * individuals on behalf of the Apache Software Foundation.  For more\r\n * information on the Apache Software Foundation, please see\r\n * <http://www.apache.org/>.\r\n *\r\n * Portions of this software are based upon public domain software\r\n * originally written at the National Center for Supercomputing Applications,\r\n * University of Illinois, Urbana-Champaign.\r\n */",
            "name": "Apache Software License, Version 1.1",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use binaries generated from modified source code\n\n",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license\n\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribute the generated binaries from modified source code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license\n\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Include end-user documentation in the distribution"
                        }
                    ],
                    "_str": "Description: The acknowledgements are here: \"This product includes software developed by the Apache Software Foundation (http://www.apache.org/).\" This acknowledgement may be included in the software itself.\nActions:\n- Include end-user documentation in the distribution\n\nConditions:\nOBLIGATION: Acknowledgements\n\n",
                    "conditions": {
                        "name": "Acknowledgements",
                        "type": "OBLIGATION"
                    },
                    "description": "The acknowledgements are here: \"This product includes software developed by the Apache Software Foundation (http://www.apache.org/).\" This acknowledgement may be included in the software itself."
                },
                {
                    "actions": [
                        {
                            "name": "Use the name to endorse and promote derived products"
                        }
                    ],
                    "_str": "Description: To use the names \"Apache\" and \"Apache Software Foundation\". apache@apache.orgã«é£çµ¡ãã.\nActions:\n- Use the name to endorse and promote derived products\n\nConditions:\nREQUISITE: Get special permission in writing.\n\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "To use the names \"Apache\" and \"Apache Software Foundation\". apache@apache.orgã«é£çµ¡ãã."
                },
                {
                    "actions": [
                        {
                            "name": "Use the name of the product or part of the name of the product from which it was derived"
                        }
                    ],
                    "_str": "Description: \"If you use the name \"Apache\". apache@apache.orgã«é£çµ¡ãã.\nActions:\n- Use the name of the product or part of the name of the product from which it was derived\n\nConditions:\nREQUISITE: Get special permission in writing.\n\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "\"If you use the name \"Apache\". apache@apache.orgã«é£çµ¡ãã."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Apache Software License, Version 1.1"
                ],
                "__impliedText": "/* ====================================================================\r\n * The Apache Software License, Version 1.1\r\n *\r\n * Copyright (c) 2000 The Apache Software Foundation.  All rights\r\n * reserved.\r\n *\r\n * Redistribution and use in source and binary forms, with or without\r\n * modification, are permitted provided that the following conditions\r\n * are met:\r\n *\r\n * 1. Redistributions of source code must retain the above copyright\r\n *    notice, this list of conditions and the following disclaimer.\r\n *\r\n * 2. Redistributions in binary form must reproduce the above copyright\r\n *    notice, this list of conditions and the following disclaimer in\r\n *    the documentation and/or other materials provided with the\r\n *    distribution.\r\n *\r\n * 3. The end-user documentation included with the redistribution,\r\n *    if any, must include the following acknowledgment:\r\n *       \"This product includes software developed by the\r\n *        Apache Software Foundation (http://www.apache.org/).\"\r\n *    Alternately, this acknowledgment may appear in the software itself,\r\n *    if and wherever such third-party acknowledgments normally appear.\r\n *\r\n * 4. The names \"Apache\" and \"Apache Software Foundation\" must\r\n *    not be used to endorse or promote products derived from this\r\n *    software without prior written permission. For written\r\n *    permission, please contact apache@apache.org.\r\n *\r\n * 5. Products derived from this software may not be called \"Apache\",\r\n *    nor may \"Apache\" appear in their name, without prior written\r\n *    permission of the Apache Software Foundation.\r\n *\r\n * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED\r\n * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\r\n * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\r\n * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR\r\n * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\r\n * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\n * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\r\n * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\r\n * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\r\n * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\r\n * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\r\n * SUCH DAMAGE.\r\n * ====================================================================\r\n *\r\n * This software consists of voluntary contributions made by many\r\n * individuals on behalf of the Apache Software Foundation.  For more\r\n * information on the Apache Software Foundation, please see\r\n * <http://www.apache.org/>.\r\n *\r\n * Portions of this software are based upon public domain software\r\n * originally written at the National Center for Supercomputing Applications,\r\n * University of Illinois, Urbana-Champaign.\r\n */",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/12"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Apache-1.1.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Apache License 1.1",
            "id": "Apache-1.1",
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache License 1.1"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Apache-1.1.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/Apache-1.1",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "Apache-1.1",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": "Apache-2.0",
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "Apache Software License, Version 1.1",
            "other_names": [],
            "keywords": [
                "discouraged",
                "obsolete",
                "osi-approved"
            ],
            "id": "Apache-1.1",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/Apache-1.1"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache Software License, Version 1.1",
                    "Apache-1.1"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/Apache-1.1"
                    ]
                ]
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": "For binary distributions, this information must be provided in âthe documentation and/or other materials provided with the distributionâ",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copyright notice",
                    "termComplianceNotes": "For binary distributions, this information must be provided in âthe documentation and/or other materials provided with the distributionâ",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Acknowledgement must be included in end-user documentation, in software or wherever third-party acknowledgments appear",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Name of project cannot be used for derived products without permission",
                    "termComplianceNotes": null,
                    "termType": "condition"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/Apache-1.1.yaml",
            "name": "Apache Software License 1.1",
            "nameFromFilename": "Apache-1.1",
            "notes": "Apache-1.1 and Entessa are essentially the same license (as per SPDX License List Matching Guidelines).  Because the OSI approved them separately, they are listed separately (here and on the SPDX License List).",
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1",
                    "Apache Software License 1.1"
                ]
            },
            "licenseId": [
                "Apache-1.1",
                "Apache Software License 1.1"
            ]
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "Apache-1.1",
            "_implications": {
                "__impliedNames": [
                    "Apache-1.1"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "Older versions of the Apache License (1.0 and 1.1) are also DFSG free, but the Apache Software Foundation recommends using the Apache 2.0 license instead."
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "The Apache Software License, Version 1.1\n\nCopyright (c) 2000 The Apache Software Foundation.  All rights\nreserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright\n   notice, this list of conditions and the following disclaimer in\n   the documentation and/or other materials provided with the\n   distribution.\n\n3. The end-user documentation included with the redistribution,\n   if any, must include the following acknowledgment:\n      \"This product includes software developed by the\n       Apache Software Foundation (http://www.apache.org/).\"\n   Alternately, this acknowledgment may appear in the software itself,\n   if and wherever such third-party acknowledgments normally appear.\n\n4. The names \"Apache\" and \"Apache Software Foundation\" must\n   not be used to endorse or promote products derived from this\n   software without prior written permission. For written\n   permission, please contact apache@apache.org.\n\n5. Products derived from this software may not be called \"Apache\",\n   nor may \"Apache\" appear in their name, without prior written\n   permission of the Apache Software Foundation.\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\nOF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR\nITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Apache-1.1.json"
        ],
        [
            null,
            "http://apache.org/licenses/LICENSE-1.1"
        ],
        [
            null,
            "https://opensource.org/licenses/Apache-1.1"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Apache-1.1.html"
        ],
        [
            "Homepage",
            "http://www.apache.org/licenses/"
        ],
        [
            null,
            "http://opensource.org/licenses/Apache-1.1"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/Apache-1.1"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/12"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Apache-1.1.svg