== Apple Public Source License 1.0 (APSL-1.0)

[cols=",",options="header",]
|====================================================
|Key |Value
|Fullname |Apple Public Source License 1.0
|Shortname |APSL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|====================================================

=== Comments on (easy) usability

* *↑* Is OSI Approved (source:
https://spdx.org/licenses/APSL-1.0.html[SPDX])
* *↓* This license is not compatible with the
DebianFreeSoftwareGuidelines (DFSG-unfree) (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines])
* *↓* This software licenses which is NOT OKAY for Fedora. Nothing in
Fedora is permitted to use this license. It is either non-free or
deprecated. (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *SPDX:* http://spdx.org/licenses/APSL-1.0.json
* https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "APSL-1.0",
        "Apple Public Source License 1.0"
    ],
    "__impliedId": "APSL-1.0",
    "__impliedAmbiguousNames": [
        "Apple Public Source License (APSL)"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "APSL-1.0",
                    "APSL-1.0",
                    "Apple Public Source License 1.0"
                ],
                "__impliedId": "APSL-1.0"
            },
            "shortname": "APSL-1.0",
            "otherNames": [
                "APSL-1.0",
                "Apple Public Source License 1.0"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Apple Public Source License 1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/APSL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/APSL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "APSL-1.0",
                    "Apple Public Source License 1.0"
                ],
                "__impliedId": "APSL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/APSL-1.0.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0"
                    ]
                ]
            },
            "spdxLicenseId": "APSL-1.0"
        },
        "Fedora Project Wiki": {
            "rating": "Bad",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Apple Public Source License 1.0",
            "FSF Free?": "No",
            "_implications": {
                "__impliedNames": [
                    "Apple Public Source License 1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
                        }
                    ]
                ]
            },
            "Notes": null
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Apple Public Source License (APSL)",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "APSL-1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Apple Public Source License (APSL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "APSL-1.0"
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "NegativeJudgement",
                "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/APSL-1.0.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Apple_Public_Source_License_1.0"
        ]
    ]
}
....