== Apple Public Source License 2.0 (APSL-2.0)

[cols=",",options="header",]
|====================================================
|Key |Value
|Fullname |Apple Public Source License 2.0
|Shortname |APSL-2.0
|Rating |Unknown, probably Attention or Stop or No-Go
|====================================================

*Other Names:*

* `Apple Public Source License, Version 2.0`
* `License :: OSI Approved :: Apple Public Source License`

=== Comments on (easy) usability

* **↑**Is OSI Approved (source:
https://spdx.org/licenses/APSL-2.0.html[SPDX])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])
* Google Classification is RECIPROCAL (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])
* **↓**This license is not compatible with the
DebianFreeSoftwareGuidelines (DFSG-unfree) (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines])

=== URLs

* *OSI Page:* https://opensource.org/licenses/APSL-2.0
* *SPDX:* http://spdx.org/licenses/APSL-2.0.json
* http://www.opensource.apple.com/license/apsl/

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "APSL-2.0",
        "Apple Public Source License 2.0",
        "Apple Public Source License, Version 2.0",
        "License :: OSI Approved :: Apple Public Source License"
    ],
    "__impliedId": "APSL-2.0",
    "__impliedAmbiguousNames": [
        "Apple Public Source License (APSL)"
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/APSL-2.0",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "APSL-2.0",
            "title": "Apple Public Source License 2.0",
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0",
                    "Apple Public Source License 2.0"
                ],
                "__impliedId": "APSL-2.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/APSL-2.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "APSL-2.0",
                    "APSL-2.0",
                    "Apple Public Source License 2.0",
                    "Apple Public Source License, Version 2.0",
                    "License :: OSI Approved :: Apple Public Source License"
                ],
                "__impliedId": "APSL-2.0"
            },
            "shortname": "APSL-2.0",
            "otherNames": [
                "APSL-2.0",
                "Apple Public Source License 2.0",
                "Apple Public Source License, Version 2.0",
                "License :: OSI Approved :: Apple Public Source License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Apple Public Source License 2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/APSL-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/APSL-2.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.opensource.apple.com/license/apsl/"
            ],
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0",
                    "Apple Public Source License 2.0"
                ],
                "__impliedId": "APSL-2.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/APSL-2.0.json"
                    ],
                    [
                        null,
                        "http://www.opensource.apple.com/license/apsl/"
                    ]
                ]
            },
            "spdxLicenseId": "APSL-2.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.opensource.apple.com/apsl/2.0.txt",
            "GPLv3 Compat?": null,
            "Short Name": "APSL 2.0",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Apple Public Source License 2.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Apple Public Source License 2.0"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Apple Public Source License",
            "commercialUse": true,
            "spdxId": "APSL-2.0",
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Apple Public Source License (APSL)",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0"
                ],
                "__impliedAmbiguousNames": [
                    "Apple Public Source License (APSL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "APSL-2.0"
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/APSL-2.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "APSL-2.0",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Apple Public Source License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "Apple Public Source License, Version 2.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "APSL-2.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/APSL-2.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0",
                    "Apple Public Source License, Version 2.0",
                    "APSL-2.0",
                    "License :: OSI Approved :: Apple Public Source License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/APSL-2.0"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Permissive",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": "06.08.03",
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "Koordinaten": {
                "name": "Apple Public Source License",
                "version": "2.0",
                "spdxId": ""
            },
            "_implications": {
                "__impliedNames": [
                    "Apple Public Source License 2.0"
                ]
            },
            "Modification": {
                "value": "Limited",
                "description": "modification of the code by a licensee"
            }
        },
        "Google OSS Policy": {
            "rating": "RECIPROCAL",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "APSL-2.0",
            "_implications": {
                "__impliedNames": [
                    "APSL-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "Google Classification is RECIPROCAL"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NeutralJudgement",
                "contents": "Google Classification is RECIPROCAL"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/APSL-2.0.json"
        ],
        [
            null,
            "http://www.opensource.apple.com/license/apsl/"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/APSL-2.0"
        ],
        [
            null,
            "https://opensource.org/licenses/APSL-2.0"
        ]
    ]
}
....