== Artistic License 1.0 (Perl) (Artistic-1.0-Perl)

[cols=",",options="header",]
|=======================================
|Key |Value
|Fullname |Artistic License 1.0 (Perl)
|Shortname |Artistic-1.0-Perl
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|=======================================

=== Comments on (easy) usability

* *↑* Do note that the Artistic License is considered non-free by the
FSF. They suggest to use the Clarified Artistic License (also called
Artistic License 2.0) instead. However, the original Artistic License is
still considered DFSG-free. (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines])
* *↑* Is OSI Approved (source:
https://spdx.org/licenses/Artistic-1.0-Perl.html[SPDX])
* *↓* Rating is: Lead (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== URLs

* *SPDX:* http://spdx.org/licenses/Artistic-1.0-Perl.json
* *SPDX:* https://spdx.org/licenses/Artistic-1.0-Perl.html
* http://dev.perl.org/licenses/artistic.html

=== OSADL Rule

....
USE CASE Source code delivery
	YOU MUST Forward Copyright notices
	YOU MUST Forward Warranty disclaimer
	IF Software modification
		YOU MUST Provide Modification notice
		YOU MUST Provide Modification report In Source code
		YOU MUST Provide Modification date In Source code
		EITHER
			YOU MUST Publish Source code
				ATTRIBUTE No charge
		OR
			YOU MUST Rename Source code
			YOU MUST Provide Original source code
			YOU MUST Provide Documentation
				YOU MUST Provide Modification report
	YOU MUST NOT Promote
USE CASE Binary delivery
	EITHER
		YOU MUST Provide Original source code
		YOU MUST Reference Original source code
	OR
		IF Software modification
			YOU MUST Provide Source code
				ATTRIBUTE Machine-readable
			YOU MUST NOT Promote
	OR
		IF Software modification
			YOU MUST Rename Source code
			YOU MUST Provide Modification report In Distribution material
			YOU MUST Reference Original source code In Distribution material
	YOU MUST NOT Promote
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Artistic-1.0-Perl",
        "Artistic License 1.0 (Perl)"
    ],
    "__impliedId": "Artistic-1.0-Perl",
    "__impliedAmbiguousNames": [
        "Artistic License"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Artistic-1.0-Perl",
                    "Artistic-1.0-Perl",
                    "Artistic License 1.0 (Perl)"
                ],
                "__impliedId": "Artistic-1.0-Perl"
            },
            "shortname": "Artistic-1.0-Perl",
            "otherNames": [
                "Artistic-1.0-Perl",
                "Artistic License 1.0 (Perl)"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Artistic License 1.0 (Perl)",
            "spdxDetailsURL": "http://spdx.org/licenses/Artistic-1.0-Perl.json",
            "_sourceURL": "https://spdx.org/licenses/Artistic-1.0-Perl.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://dev.perl.org/licenses/artistic.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Artistic-1.0-Perl",
                    "Artistic License 1.0 (Perl)"
                ],
                "__impliedId": "Artistic-1.0-Perl",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Artistic-1.0-Perl.json"
                    ],
                    [
                        null,
                        "http://dev.perl.org/licenses/artistic.html"
                    ]
                ]
            },
            "spdxLicenseId": "Artistic-1.0-Perl"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/Artistic-1.0-Perl.txt",
            "spdxId": "Artistic-1.0-Perl",
            "osadlRule": "USE CASE Source code delivery\n\tYOU MUST Forward Copyright notices\n\tYOU MUST Forward Warranty disclaimer\n\tIF Software modification\n\t\tYOU MUST Provide Modification notice\n\t\tYOU MUST Provide Modification report In Source code\n\t\tYOU MUST Provide Modification date In Source code\n\t\tEITHER\n\t\t\tYOU MUST Publish Source code\n\t\t\t\tATTRIBUTE No charge\r\n\t\tOR\r\n\t\t\tYOU MUST Rename Source code\n\t\t\tYOU MUST Provide Original source code\n\t\t\tYOU MUST Provide Documentation\n\t\t\t\tYOU MUST Provide Modification report\n\tYOU MUST NOT Promote\nUSE CASE Binary delivery\n\tEITHER\n\t\tYOU MUST Provide Original source code\n\t\tYOU MUST Reference Original source code\n\tOR\r\n\t\tIF Software modification\n\t\t\tYOU MUST Provide Source code\n\t\t\t\tATTRIBUTE Machine-readable\n\t\t\tYOU MUST NOT Promote\n\tOR\r\n\t\tIF Software modification\n\t\t\tYOU MUST Rename Source code\n\t\t\tYOU MUST Provide Modification report In Distribution material\n\t\t\tYOU MUST Reference Original source code In Distribution material\n\tYOU MUST NOT Promote\n",
            "_implications": {
                "__impliedNames": [
                    "Artistic-1.0-Perl"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Artistic License",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "Artistic-1.0-Perl"
                ],
                "__impliedAmbiguousNames": [
                    "Artistic License"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Do note that the Artistic License is considered non-free by the FSF. They suggest to use the Clarified Artistic License (also called Artistic License 2.0) instead. However, the original Artistic License is still considered DFSG-free."
                        }
                    ]
                ]
            },
            "Comment": "Do note that the Artistic License is considered non-free by the FSF. They suggest to use the Clarified Artistic License (also called Artistic License 2.0) instead. However, the original Artistic License is still considered DFSG-free.",
            "LicenseId": "Artistic-1.0-Perl"
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Artistic-1.0-Perl.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Artistic License 1.0 (Perl)",
            "id": "Artistic-1.0-Perl",
            "_implications": {
                "__impliedNames": [
                    "Artistic-1.0-Perl"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Artistic-1.0-Perl.html"
                    ]
                ]
            }
        },
        "finos-osr/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "US"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Retain all notices",
                    "termComplianceNotes": "Copyright notices and other notices",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Notice of modifications",
                    "termComplianceNotes": "Modified files must have \"prominent notice\" in each file stating how the file was modified and when",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide access to modifications",
                    "termComplianceNotes": "Do at least one of the following: place modification in the public domain or otherwise make them freely available; OR rename non-standard executables; OR \"make other distribution arrangements\" with the copyright holder (see section 3 for more details).",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Access to source",
                    "termComplianceNotes": "Do at least one of the following: provide a Standard Version of the executables and library files; OR provide source for your modifications; OR give non-standard executables non-standard name and document the differences with instructions on where to get the Standard Version; OR \"make other distribution arrangements\" with the copyright holder (see section 4 for more details)",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "You may distribute this package as part of a larger (commercial) distribution, but cannot charge a fee for the standalone package. You may charge a reasonable fee for copying or support.",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "The following are not considered part of the package or do not fall under copyright of this package and subject to the license: scripts and library files supplied as input to or produced as output from the program; C subroutines (or comparably compiled subroutines in other languages) supplied by you and linked into this Package in order to emulate subroutines and variables of the language defined by this package; aggregation of this package with other software where the package is embedded and the interfaces are not visible to the end user (see sections 6, 7, and 8 for more details)",
                    "termComplianceNotes": null,
                    "termType": "other"
                }
            ],
            "_sourceURL": "https://github.com/finos-osr/OSLC-handbook/blob/master/src/Artistic-1.0-Perl.yaml",
            "name": "Artistic License 1.0 (Perl)",
            "nameFromFilename": "Artistic-1.0-Perl",
            "notes": "This is the Artistic License 1.0 found on the Perl site, which is different (particularly, clauses 5, 6, 7 and 8) than the Artistic License 1.0 w/clause 8 found on the OSI site. This license has specific use cases and conditions that are difficult to summarize; please see sections 5-8 and relevant definitions for more details.",
            "_implications": {
                "__impliedNames": [
                    "Artistic License 1.0 (Perl)",
                    "Artistic-1.0-Perl"
                ]
            },
            "licenseId": [
                "Artistic-1.0-Perl"
            ]
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "Do note that the Artistic License is considered non-free by the FSF. They suggest to use the Clarified Artistic License (also called Artistic License 2.0) instead. However, the original Artistic License is still considered DFSG-free."
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Artistic-1.0-Perl.json"
        ],
        [
            null,
            "http://dev.perl.org/licenses/artistic.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Artistic-1.0-Perl.html"
        ]
    ]
}
....