== Bahyph License (Bahyph)

[cols=",",options="header",]
|==========================
|Key |Value
|Fullname |Bahyph License
|Shortname |Bahyph
|Rating |Go
|Classification |NoCopyleft
|==========================

=== Comments on (easy) usability

* *↑* Rating is: Bronze (source: https://blueoakcouncil.org/list[BlueOak
License List])
* *↑* This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *SPDX:* http://spdx.org/licenses/Bahyph.json
* *SPDX:* https://spdx.org/licenses/Bahyph
* https://fedoraproject.org/wiki/Licensing/Bahyph

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Bahyph",
        "Bahyph License"
    ],
    "__impliedId": "Bahyph",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Bahyph",
                    "Bahyph",
                    "Bahyph License"
                ],
                "__impliedId": "Bahyph"
            },
            "shortname": "Bahyph",
            "otherNames": [
                "Bahyph",
                "Bahyph License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Bahyph License",
            "spdxDetailsURL": "http://spdx.org/licenses/Bahyph.json",
            "_sourceURL": "https://spdx.org/licenses/Bahyph.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Bahyph"
            ],
            "_implications": {
                "__impliedNames": [
                    "Bahyph",
                    "Bahyph License"
                ],
                "__impliedId": "Bahyph",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Bahyph.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Bahyph"
                    ]
                ]
            },
            "spdxLicenseId": "Bahyph"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Bahyph",
            "GPLv3 Compat?": "NO",
            "Short Name": "Bahyph",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Bahyph License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Bahyph License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Bahyph",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Bahyph License",
            "id": "Bahyph",
            "_implications": {
                "__impliedNames": [
                    "Bahyph"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Bahyph"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Bahyph.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Bahyph"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Bahyph"
        ]
    ]
}
....