== Barr License (Barr)

[cols=",",options="header",]
|==========================
|Key |Value
|Fullname |Barr License
|Shortname |Barr
|Rating |Go
|Classification |NoCopyleft
|==========================

=== Comments on (easy) usability

* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *SPDX:* http://spdx.org/licenses/Barr.json
* *SPDX:* https://spdx.org/licenses/Barr.html
* https://fedoraproject.org/wiki/Licensing/Barr

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Barr",
        "Barr License"
    ],
    "__impliedId": "Barr",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Barr",
                    "Barr",
                    "Barr License"
                ],
                "__impliedId": "Barr"
            },
            "shortname": "Barr",
            "otherNames": [
                "Barr",
                "Barr License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Barr License",
            "spdxDetailsURL": "http://spdx.org/licenses/Barr.json",
            "_sourceURL": "https://spdx.org/licenses/Barr.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Barr"
            ],
            "_implications": {
                "__impliedNames": [
                    "Barr",
                    "Barr License"
                ],
                "__impliedId": "Barr",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Barr.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Barr"
                    ]
                ]
            },
            "spdxLicenseId": "Barr"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Barr",
            "GPLv3 Compat?": "NO",
            "Short Name": "Barr",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Barr License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Barr License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Barr.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Barr License",
            "id": "Barr",
            "_implications": {
                "__impliedNames": [
                    "Barr"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Barr.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Barr.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Barr"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Barr.html"
        ]
    ]
}
....