== Barr License (Barr)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Barr License
|Shortname |Barr
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/Barr.html
* *SPDX:* http://spdx.org/licenses/Barr.json
* https://fedoraproject.org/wiki/Licensing/Barr

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/Barr.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Barr",
        "Barr License"
    ],
    "__impliedId": "Barr",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Barr"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Barr"
                ],
                "__impliedId": "Barr"
            },
            "shortname": "Barr",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Barr License",
            "spdxDetailsURL": "http://spdx.org/licenses/Barr.json",
            "_sourceURL": "https://spdx.org/licenses/Barr.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Barr"
            ],
            "_implications": {
                "__impliedNames": [
                    "Barr",
                    "Barr License"
                ],
                "__impliedId": "Barr",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Barr.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Barr"
                    ]
                ]
            },
            "spdxLicenseId": "Barr"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Barr",
            "GPLv3 Compat?": "NO",
            "Short Name": "Barr",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Barr License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Barr License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Barr"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Barr.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Barr License",
            "id": "Barr",
            "_implications": {
                "__impliedNames": [
                    "Barr",
                    "Barr License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Barr.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Barr.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Barr.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Barr"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Barr.svg
