== BitTorrent Open Source License v1.0 (BitTorrent-1.0)

[cols=",",options="header",]
|====================================================
|Key |Value
|Fullname |BitTorrent Open Source License v1.0
|Shortname |BitTorrent-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|====================================================

=== Comments on (easy) usability

=== URLs

* *SPDX:* http://spdx.org/licenses/BitTorrent-1.0.json
* http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "BitTorrent-1.0",
        "BitTorrent Open Source License v1.0"
    ],
    "__impliedId": "BitTorrent-1.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BitTorrent-1.0",
                    "BitTorrent-1.0",
                    "BitTorrent Open Source License v1.0"
                ],
                "__impliedId": "BitTorrent-1.0"
            },
            "shortname": "BitTorrent-1.0",
            "otherNames": [
                "BitTorrent-1.0",
                "BitTorrent Open Source License v1.0"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BitTorrent Open Source License v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/BitTorrent-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/BitTorrent-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s"
            ],
            "_implications": {
                "__impliedNames": [
                    "BitTorrent-1.0",
                    "BitTorrent Open Source License v1.0"
                ],
                "__impliedId": "BitTorrent-1.0",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BitTorrent-1.0.json"
                    ],
                    [
                        null,
                        "http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s"
                    ]
                ]
            },
            "spdxLicenseId": "BitTorrent-1.0"
        }
    },
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/BitTorrent-1.0.json"
        ],
        [
            null,
            "http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/licenses/BitTorrent?r1=1.1&r2=1.1.1.1&diff_format=s"
        ]
    ]
}
....