== BitTorrent Open Source License v1.1 (BitTorrent-1.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BitTorrent Open Source License v1.1
|Shortname |BitTorrent-1.1
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

*Other Names:*

* `BitTorrent Open Source License 1.1`

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/BitTorrent-1.1.json
* https://spdx.org/licenses/BitTorrent-1.1
* http://directory.fsf.org/wiki/License:BitTorrentOSL1.1

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://spdx.org/licenses/BitTorrent-1.1.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "BitTorrent-1.1",
        "BitTorrent Open Source License 1.1",
        "BitTorrent Open Source License v1.1"
    ],
    "__impliedId": "BitTorrent-1.1",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://spdx.org/licenses/BitTorrent-1.1",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "not reviewed",
            "id": "BitTorrent-1.1",
            "title": "BitTorrent Open Source License 1.1",
            "_implications": {
                "__impliedNames": [
                    "BitTorrent-1.1",
                    "BitTorrent Open Source License 1.1"
                ],
                "__impliedId": "BitTorrent-1.1",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/BitTorrent-1.1"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BitTorrent-1.1"
                ],
                "__impliedId": "BitTorrent-1.1"
            },
            "shortname": "BitTorrent-1.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BitTorrent Open Source License v1.1",
            "spdxDetailsURL": "http://spdx.org/licenses/BitTorrent-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/BitTorrent-1.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://directory.fsf.org/wiki/License:BitTorrentOSL1.1"
            ],
            "_implications": {
                "__impliedNames": [
                    "BitTorrent-1.1",
                    "BitTorrent Open Source License v1.1"
                ],
                "__impliedId": "BitTorrent-1.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BitTorrent-1.1.json"
                    ],
                    [
                        null,
                        "http://directory.fsf.org/wiki/License:BitTorrentOSL1.1"
                    ]
                ]
            },
            "spdxLicenseId": "BitTorrent-1.1"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "BitTorrent-1.1"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "BitTorrent-1.1",
            "copyleftkind": "WeakCopyleft"
        }
    },
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/BitTorrent-1.1"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BitTorrent-1.1.json"
        ],
        [
            null,
            "http://directory.fsf.org/wiki/License:BitTorrentOSL1.1"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BitTorrent-1.1.svg
