== SQLite Blessing (blessing)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |SQLite Blessing
|Shortname |blessing
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://blessing`

=== Comments on (easy) usability

* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``category: Public Domain'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/[sq]/SQLite-Blessing.yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *Homepage:* https://sqlite.org/src/artifact/df5091916dbb40e6
* *SPDX:* https://spdx.org/licenses/blessing.html
* *SPDX:* https://spdx.org/licenses/blessing.json
* https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9

=== Text

....
The author disclaims copyright to this source code.
In place of a legal notice, here is a blessing:
   May you do good and not evil.
   May you find forgiveness for yourself and forgive others.
   May you share freely, never taking more than you give.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/[sq]/SQLite-Blessing.yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/blessing.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/blessing.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "blessing",
        "SQLite Blessing",
        "scancode://blessing"
    ],
    "__impliedId": "blessing",
    "__impliedAmbiguousNames": [
        "SQLite Blessing",
        "scancode:blessing"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: Public Domain"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "blessing"
                ],
                "__impliedId": "blessing"
            },
            "shortname": "blessing",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "SQLite Blessing",
            "spdxDetailsURL": "https://spdx.org/licenses/blessing.json",
            "_sourceURL": "https://spdx.org/licenses/blessing.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9",
                "https://sqlite.org/src/artifact/df5091916dbb40e6"
            ],
            "_implications": {
                "__impliedNames": [
                    "blessing",
                    "SQLite Blessing"
                ],
                "__impliedId": "blessing",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/blessing.json"
                    ],
                    [
                        null,
                        "https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9"
                    ],
                    [
                        null,
                        "https://sqlite.org/src/artifact/df5091916dbb40e6"
                    ]
                ]
            },
            "spdxLicenseId": "blessing"
        },
        "Scancode": {
            "otherUrls": [
                "https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9",
                "https://sqlite.org/src/artifact/df5091916dbb40e6"
            ],
            "homepageUrl": "https://sqlite.org/src/artifact/df5091916dbb40e6",
            "shortName": "SQLite Blessing",
            "textUrls": null,
            "text": "The author disclaims copyright to this source code.\nIn place of a legal notice, here is a blessing:\n   May you do good and not evil.\n   May you find forgiveness for yourself and forgive others.\n   May you share freely, never taking more than you give.",
            "category": "Public Domain",
            "osiUrl": null,
            "owner": "SQLite",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/blessing.yml",
            "key": "blessing",
            "name": "SQLite Blessing",
            "spdxId": "blessing",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://blessing",
                    "SQLite Blessing",
                    "blessing"
                ],
                "__impliedId": "blessing",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The author disclaims copyright to this source code.\nIn place of a legal notice, here is a blessing:\n   May you do good and not evil.\n   May you find forgiveness for yourself and forgive others.\n   May you share freely, never taking more than you give.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://sqlite.org/src/artifact/df5091916dbb40e6"
                    ],
                    [
                        null,
                        "https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9"
                    ],
                    [
                        null,
                        "https://sqlite.org/src/artifact/df5091916dbb40e6"
                    ]
                ]
            }
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "blessing",
            "shortName": null,
            "category": "Public Domain",
            "alternativeNames": [
                "SQLite Blessing"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/[sq]/SQLite-Blessing.yaml",
            "otherIds": [
                "scancode:blessing"
            ],
            "canonicalName": "SQLite Blessing",
            "_implications": {
                "__impliedNames": [
                    "SQLite Blessing",
                    "blessing"
                ],
                "__impliedId": "blessing",
                "__impliedAmbiguousNames": [
                    "SQLite Blessing",
                    "scancode:blessing"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: Public Domain"
                        ]
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/blessing.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "SQLite Blessing",
            "id": "blessing",
            "_implications": {
                "__impliedNames": [
                    "blessing",
                    "SQLite Blessing"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/blessing.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "The author disclaims copyright to this source code.\nIn place of a legal notice, here is a blessing:\n   May you do good and not evil.\n   May you find forgiveness for yourself and forgive others.\n   May you share freely, never taking more than you give.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/blessing.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/blessing.json"
        ],
        [
            null,
            "https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9"
        ],
        [
            null,
            "https://sqlite.org/src/artifact/df5091916dbb40e6"
        ],
        [
            "Homepage",
            "https://sqlite.org/src/artifact/df5091916dbb40e6"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/blessing.svg
