== Blue Oak Model License 1.0.0 (BlueOak-1.0.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Blue Oak Model License 1.0.0
|Shortname |BlueOak-1.0.0
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://blueoak-1.0.0+`

=== Comments on (easy) usability

* **↑**``Rating is: Model'' (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== General Comments

=== URLs

* *Homepage:* https://blueoakcouncil.org/license/1.0.0
* *SPDX:* http://spdx.org/licenses/BlueOak-1.0.0.json

=== Text

....
# Blue Oak Model License

Version 1.0.0

## Purpose

This license gives everyone as much permission to work with
this software as possible, while protecting contributors
from liability.

## Acceptance

In order to receive this license, you must agree to its
rules.  The rules of this license are both obligations
under that agreement and conditions to your license.
You must not do anything with this software that triggers
a rule that you cannot or will not follow.

## Copyright

Each contributor licenses you to do everything with this
software that would otherwise infringe that contributor's
copyright in it.

## Notices

You must ensure that everyone who gets a copy of
any part of this software from you, with or without
changes, also gets the text of this license or a link to
<https://blueoakcouncil.org/license/1.0.0>.

## Excuse

If anyone notifies you in writing that you have not
complied with [Notices](#notices), you can keep your
license by taking all practical steps to comply within 30
days after the notice.  If you do not do so, your license
ends immediately.

## Patent

Each contributor licenses you to do everything with this
software that would otherwise infringe any patent claims
they can license or become able to license.

## Reliability

No contributor can revoke this license.

## No Liability

***As far as the law allows, this software comes as is,
without any warranty or condition, and no contributor
will be liable to anyone for any damages related to this
software or this license, under any kind of legal claim.***
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/BlueOak-1.0.0.html[SPDX]
* https://blueoakcouncil.org/list[BlueOak License List]
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/blueoak-1.0.0.yml[Scancode]

==== Dot Cluster Graph

../dot/BlueOak-1.0.0.svg

==== Raw JSON

....
{
    "__impliedNames": [
        "BlueOak-1.0.0",
        "Blue Oak Model License 1.0.0",
        "scancode://blueoak-1.0.0"
    ],
    "__impliedId": "BlueOak-1.0.0",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Blue Oak Model License 1.0.0",
            "spdxDetailsURL": "http://spdx.org/licenses/BlueOak-1.0.0.json",
            "_sourceURL": "https://spdx.org/licenses/BlueOak-1.0.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://blueoakcouncil.org/license/1.0.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "BlueOak-1.0.0",
                    "Blue Oak Model License 1.0.0"
                ],
                "__impliedId": "BlueOak-1.0.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BlueOak-1.0.0.json"
                    ],
                    [
                        null,
                        "https://blueoakcouncil.org/license/1.0.0"
                    ]
                ]
            },
            "spdxLicenseId": "BlueOak-1.0.0"
        },
        "Scancode": {
            "otherUrls": [
                "https://blueoakcouncil.org/license/1.0.0"
            ],
            "homepageUrl": "https://blueoakcouncil.org/license/1.0.0",
            "shortName": "Blue Oak Model License 1.0.0",
            "textUrls": null,
            "text": "# Blue Oak Model License\n\nVersion 1.0.0\n\n## Purpose\n\nThis license gives everyone as much permission to work with\nthis software as possible, while protecting contributors\nfrom liability.\n\n## Acceptance\n\nIn order to receive this license, you must agree to its\nrules.  The rules of this license are both obligations\nunder that agreement and conditions to your license.\nYou must not do anything with this software that triggers\na rule that you cannot or will not follow.\n\n## Copyright\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe that contributor's\ncopyright in it.\n\n## Notices\n\nYou must ensure that everyone who gets a copy of\nany part of this software from you, with or without\nchanges, also gets the text of this license or a link to\n<https://blueoakcouncil.org/license/1.0.0>.\n\n## Excuse\n\nIf anyone notifies you in writing that you have not\ncomplied with [Notices](#notices), you can keep your\nlicense by taking all practical steps to comply within 30\ndays after the notice.  If you do not do so, your license\nends immediately.\n\n## Patent\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe any patent claims\nthey can license or become able to license.\n\n## Reliability\n\nNo contributor can revoke this license.\n\n## No Liability\n\n***As far as the law allows, this software comes as is,\nwithout any warranty or condition, and no contributor\nwill be liable to anyone for any damages related to this\nsoftware or this license, under any kind of legal claim.***",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Blue Oak Council",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/blueoak-1.0.0.yml",
            "key": "blueoak-1.0.0",
            "name": "Blue Oak Model License 1.0.0",
            "spdxId": "BlueOak-1.0.0",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://blueoak-1.0.0",
                    "Blue Oak Model License 1.0.0",
                    "BlueOak-1.0.0"
                ],
                "__impliedId": "BlueOak-1.0.0",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "# Blue Oak Model License\n\nVersion 1.0.0\n\n## Purpose\n\nThis license gives everyone as much permission to work with\nthis software as possible, while protecting contributors\nfrom liability.\n\n## Acceptance\n\nIn order to receive this license, you must agree to its\nrules.  The rules of this license are both obligations\nunder that agreement and conditions to your license.\nYou must not do anything with this software that triggers\na rule that you cannot or will not follow.\n\n## Copyright\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe that contributor's\ncopyright in it.\n\n## Notices\n\nYou must ensure that everyone who gets a copy of\nany part of this software from you, with or without\nchanges, also gets the text of this license or a link to\n<https://blueoakcouncil.org/license/1.0.0>.\n\n## Excuse\n\nIf anyone notifies you in writing that you have not\ncomplied with [Notices](#notices), you can keep your\nlicense by taking all practical steps to comply within 30\ndays after the notice.  If you do not do so, your license\nends immediately.\n\n## Patent\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe any patent claims\nthey can license or become able to license.\n\n## Reliability\n\nNo contributor can revoke this license.\n\n## No Liability\n\n***As far as the law allows, this software comes as is,\nwithout any warranty or condition, and no contributor\nwill be liable to anyone for any damages related to this\nsoftware or this license, under any kind of legal claim.***",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://blueoakcouncil.org/license/1.0.0"
                    ],
                    [
                        null,
                        "https://blueoakcouncil.org/license/1.0.0"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Model",
            "url": "https://blueoakcouncil.org/license/1.0.0",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Blue Oak Model License 1.0.0",
            "id": "BlueOak-1.0.0",
            "_implications": {
                "__impliedNames": [
                    "BlueOak-1.0.0",
                    "Blue Oak Model License 1.0.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Model"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://blueoakcouncil.org/license/1.0.0"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Model"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "# Blue Oak Model License\n\nVersion 1.0.0\n\n## Purpose\n\nThis license gives everyone as much permission to work with\nthis software as possible, while protecting contributors\nfrom liability.\n\n## Acceptance\n\nIn order to receive this license, you must agree to its\nrules.  The rules of this license are both obligations\nunder that agreement and conditions to your license.\nYou must not do anything with this software that triggers\na rule that you cannot or will not follow.\n\n## Copyright\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe that contributor's\ncopyright in it.\n\n## Notices\n\nYou must ensure that everyone who gets a copy of\nany part of this software from you, with or without\nchanges, also gets the text of this license or a link to\n<https://blueoakcouncil.org/license/1.0.0>.\n\n## Excuse\n\nIf anyone notifies you in writing that you have not\ncomplied with [Notices](#notices), you can keep your\nlicense by taking all practical steps to comply within 30\ndays after the notice.  If you do not do so, your license\nends immediately.\n\n## Patent\n\nEach contributor licenses you to do everything with this\nsoftware that would otherwise infringe any patent claims\nthey can license or become able to license.\n\n## Reliability\n\nNo contributor can revoke this license.\n\n## No Liability\n\n***As far as the law allows, this software comes as is,\nwithout any warranty or condition, and no contributor\nwill be liable to anyone for any damages related to this\nsoftware or this license, under any kind of legal claim.***",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/BlueOak-1.0.0.json"
        ],
        [
            null,
            "https://blueoakcouncil.org/license/1.0.0"
        ],
        [
            "Homepage",
            "https://blueoakcouncil.org/license/1.0.0"
        ]
    ]
}
....