== BSD 2-Clause with views sentence (BSD-2-Clause-Views)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD 2-Clause with views sentence
|Shortname |BSD-2-Clause-Views
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://bsd-2-clause-views`

=== Comments on (easy) usability

* **↑**``Rating is: Silver'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *Homepage:* https://www.freebsd.org/copyright/freebsd-license.html
* *SPDX:* https://spdx.org/licenses/BSD-2-Clause-Views.html
* *SPDX:* https://spdx.org/licenses/BSD-2-Clause-Views.json
* https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh
* https://github.com/protegeproject/protege/blob/master/license.txt

=== Text

....
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list
of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the FreeBSD Project.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/BSD-2-Clause-Views.html[SPDX] (all data [in
this repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-2-clause-views.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-2-Clause-Views",
        "BSD 2-Clause with Views Sentence",
        "BSD 2-Clause with views sentence",
        "scancode://bsd-2-clause-views"
    ],
    "__impliedId": "BSD-2-Clause-Views",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Views"
                ],
                "__impliedId": "BSD-2-Clause-Views"
            },
            "shortname": "BSD-2-Clause-Views",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD 2-Clause with views sentence",
            "spdxDetailsURL": "https://spdx.org/licenses/BSD-2-Clause-Views.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-2-Clause-Views.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.freebsd.org/copyright/freebsd-license.html",
                "https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh",
                "https://github.com/protegeproject/protege/blob/master/license.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Views",
                    "BSD 2-Clause with views sentence"
                ],
                "__impliedId": "BSD-2-Clause-Views",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-2-Clause-Views.json"
                    ],
                    [
                        null,
                        "http://www.freebsd.org/copyright/freebsd-license.html"
                    ],
                    [
                        null,
                        "https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh"
                    ],
                    [
                        null,
                        "https://github.com/protegeproject/protege/blob/master/license.txt"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-2-Clause-Views"
        },
        "Scancode": {
            "otherUrls": [
                "http://www.freebsd.org/copyright/freebsd-license.html",
                "https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh"
            ],
            "homepageUrl": "https://www.freebsd.org/copyright/freebsd-license.html",
            "shortName": "BSD-2-Clause-Views",
            "textUrls": null,
            "text": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\nRedistributions of source code must retain the above copyright notice, this list\nof conditions and the following disclaimer.\n\nRedistributions in binary form must reproduce the above copyright notice, this\nlist of conditions and the following disclaimer in the documentation and/or\nother materials provided with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY\nEXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThe views and conclusions contained in the software and documentation are those\nof the authors and should not be interpreted as representing official policies,\neither expressed or implied, of the FreeBSD Project.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "FreeBSD",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-2-clause-views.yml",
            "key": "bsd-2-clause-views",
            "name": "BSD 2-Clause with views sentence",
            "spdxId": "BSD-2-Clause-Views",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://bsd-2-clause-views",
                    "BSD-2-Clause-Views",
                    "BSD-2-Clause-Views"
                ],
                "__impliedId": "BSD-2-Clause-Views",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\nRedistributions of source code must retain the above copyright notice, this list\nof conditions and the following disclaimer.\n\nRedistributions in binary form must reproduce the above copyright notice, this\nlist of conditions and the following disclaimer in the documentation and/or\nother materials provided with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY\nEXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThe views and conclusions contained in the software and documentation are those\nof the authors and should not be interpreted as representing official policies,\neither expressed or implied, of the FreeBSD Project.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://www.freebsd.org/copyright/freebsd-license.html"
                    ],
                    [
                        null,
                        "http://www.freebsd.org/copyright/freebsd-license.html"
                    ],
                    [
                        null,
                        "https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/BSD-2-Clause-Views.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD 2-Clause with Views Sentence",
            "id": "BSD-2-Clause-Views",
            "_implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Views",
                    "BSD 2-Clause with Views Sentence"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-2-Clause-Views.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\nRedistributions of source code must retain the above copyright notice, this list\nof conditions and the following disclaimer.\n\nRedistributions in binary form must reproduce the above copyright notice, this\nlist of conditions and the following disclaimer in the documentation and/or\nother materials provided with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY\nEXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\nDISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\nLOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\nANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThe views and conclusions contained in the software and documentation are those\nof the authors and should not be interpreted as representing official policies,\neither expressed or implied, of the FreeBSD Project.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-2-Clause-Views.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-2-Clause-Views.json"
        ],
        [
            null,
            "http://www.freebsd.org/copyright/freebsd-license.html"
        ],
        [
            null,
            "https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh"
        ],
        [
            null,
            "https://github.com/protegeproject/protege/blob/master/license.txt"
        ],
        [
            "Homepage",
            "https://www.freebsd.org/copyright/freebsd-license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-2-Clause-Views.svg
