== BSD-4-Clause (University of California-Specific) (BSD-4-Clause-UC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD-4-Clause (University of California-Specific)
|Shortname |BSD-4-Clause-UC
|Rating |Attention
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↓**``Advertisement clause (3.) is complicated and prone to
conflicts'' (source: Override)

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/BSD-4-Clause-UC.html
* *SPDX:* http://spdx.org/licenses/BSD-4-Clause-UC.json
* http://www.freebsd.org/copyright/license.html

'''''

=== Raw Data

==== Facts

* LicenseName
* Override
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/finos/OSLC-handbook/blob/master/src/BSD-4-Clause-UC.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/BSD-4-Clause-UC.html[SPDX] (all data [in
this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-4-Clause-UC",
        "BSD-4-Clause (University of California-Specific)"
    ],
    "__impliedId": "BSD-4-Clause-UC",
    "__impliedRatingState": [
        [
            "Override",
            {
                "tag": "RatingState",
                "contents": [
                    false,
                    true,
                    true,
                    true
                ]
            }
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC"
                ],
                "__impliedId": "BSD-4-Clause-UC"
            },
            "shortname": "BSD-4-Clause-UC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD-4-Clause (University of California-Specific)",
            "spdxDetailsURL": "http://spdx.org/licenses/BSD-4-Clause-UC.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-4-Clause-UC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.freebsd.org/copyright/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC",
                    "BSD-4-Clause (University of California-Specific)"
                ],
                "__impliedId": "BSD-4-Clause-UC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BSD-4-Clause-UC.json"
                    ],
                    [
                        null,
                        "http://www.freebsd.org/copyright/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-4-Clause-UC"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "BSD-4-Clause-UC",
            "copyleftkind": "NoCopyleft"
        },
        "Override": {
            "oNonCommecrial": null,
            "implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC"
                ],
                "__impliedId": "BSD-4-Clause-UC",
                "__impliedRatingState": [
                    [
                        "Override",
                        {
                            "tag": "RatingState",
                            "contents": [
                                false,
                                true,
                                true,
                                true
                            ]
                        }
                    ]
                ],
                "__impliedJudgement": [
                    [
                        "Override",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Advertisement clause (3.) is complicated and prone to conflicts"
                        }
                    ]
                ]
            },
            "oName": "BSD-4-Clause-UC",
            "oOtherLicenseIds": [],
            "oDescription": null,
            "oJudgement": {
                "tag": "NegativeJudgement",
                "contents": "Advertisement clause (3.) is complicated and prone to conflicts"
            },
            "oCompatibilities": null,
            "oRatingState": {
                "tag": "RatingState",
                "contents": [
                    false,
                    true,
                    true,
                    true
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/BSD-4-Clause-UC.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD-4-Clause (University of California-Specific)",
            "id": "BSD-4-Clause-UC",
            "_implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC",
                    "BSD-4-Clause (University of California-Specific)"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-4-Clause-UC.html"
                    ]
                ]
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copyright notice",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/BSD-4-Clause-UC.yaml",
            "name": "BSD-4-Clause (University of California-Specific)",
            "nameFromFilename": "BSD-4-Clause-UC",
            "notes": "The advertising clause was rescinded by the University of California in 1999 for all material under BSD-4-Clause with University of California copyright notice. Thus, you do not need to comply with the advertising/acknowledgment requirement, which makes the license essentially BSD-3-Clause.",
            "_implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC",
                    "BSD-4-Clause (University of California-Specific)"
                ]
            },
            "licenseId": [
                "BSD-4-Clause-UC",
                "BSD-4-Clause (University of California-Specific)"
            ]
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "BSD-4-Clause-UC",
            "_implications": {
                "__impliedNames": [
                    "BSD-4-Clause-UC"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "Override",
            {
                "tag": "NegativeJudgement",
                "contents": "Advertisement clause (3.) is complicated and prone to conflicts"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-4-Clause-UC.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BSD-4-Clause-UC.json"
        ],
        [
            null,
            "http://www.freebsd.org/copyright/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-4-Clause-UC.svg
