== BSD Protection License (BSD-Protection)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD Protection License
|Shortname |BSD-Protection
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |StrongCopyleft
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``Strong copyleft licenses require you to share both the licensed
software (like the weak copyleft licenses, and larger programs that you
build with the licensed software, when you give copies to others.''
(source: https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *SPDX:* http://spdx.org/licenses/BSD-Protection.json
* https://spdx.org/licenses/BSD-Protection.html
* https://fedoraproject.org/wiki/Licensing/BSD_Protection_License

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/BSD-Protection.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-Protection",
        "BSD Protection License"
    ],
    "__impliedId": "BSD-Protection",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "BSD Protection License",
        "BSD Protection"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-Protection"
                ],
                "__impliedId": "BSD-Protection"
            },
            "shortname": "BSD-Protection",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD Protection License",
            "spdxDetailsURL": "http://spdx.org/licenses/BSD-Protection.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-Protection.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/BSD_Protection_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-Protection",
                    "BSD Protection License"
                ],
                "__impliedId": "BSD-Protection",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BSD-Protection.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/BSD_Protection_License"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-Protection"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/BSD_Protection_License",
            "GPLv3 Compat?": "NO",
            "Short Name": "BSD Protection",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "BSD Protection License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "BSD Protection License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "BSD Protection"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/BSD-Protection.html",
            "familyName": "BSD Protection License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "BSD Protection License",
            "id": "BSD-Protection",
            "_implications": {
                "__impliedNames": [
                    "BSD-Protection",
                    "BSD Protection License"
                ],
                "__impliedAmbiguousNames": [
                    "BSD Protection License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "StrongCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "StrongCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/BSD-Protection.html"
                    ]
                ]
            },
            "CopyleftKind": "StrongCopyleft"
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "StrongCopyleft"
        ]
    ],
    "__calculatedCopyleft": "StrongCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/BSD-Protection.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BSD-Protection.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/BSD_Protection_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-Protection.svg
