== BSD 3-Clause No Nuclear License 2014 (BSD-3-Clause-No-Nuclear-License-2014)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD 3-Clause No Nuclear License 2014
|Shortname |BSD-3-Clause-No-Nuclear-License-2014
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:*
https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html
* *SPDX:*
http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json
* https://java.net/projects/javaeetutorial/pages/BerkeleyLicense

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html[SPDX]
(all data [in this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-3-Clause-No-Nuclear-License-2014",
        "BSD 3-Clause No Nuclear License 2014"
    ],
    "__impliedId": "BSD-3-Clause-No-Nuclear-License-2014",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-3-Clause-No-Nuclear-License-2014"
                ],
                "__impliedId": "BSD-3-Clause-No-Nuclear-License-2014"
            },
            "shortname": "BSD-3-Clause-No-Nuclear-License-2014",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD 3-Clause No Nuclear License 2014",
            "spdxDetailsURL": "http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://java.net/projects/javaeetutorial/pages/BerkeleyLicense"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-3-Clause-No-Nuclear-License-2014",
                    "BSD 3-Clause No Nuclear License 2014"
                ],
                "__impliedId": "BSD-3-Clause-No-Nuclear-License-2014",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json"
                    ],
                    [
                        null,
                        "https://java.net/projects/javaeetutorial/pages/BerkeleyLicense"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-3-Clause-No-Nuclear-License-2014"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "BSD-3-Clause-No-Nuclear-License-2014"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "BSD-3-Clause-No-Nuclear-License-2014",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD 3-Clause No Nuclear License 2014",
            "id": "BSD-3-Clause-No-Nuclear-License-2014",
            "_implications": {
                "__impliedNames": [
                    "BSD-3-Clause-No-Nuclear-License-2014",
                    "BSD 3-Clause No Nuclear License 2014"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.json"
        ],
        [
            null,
            "https://java.net/projects/javaeetutorial/pages/BerkeleyLicense"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-3-Clause-No-Nuclear-License-2014.svg
