== BSD 3-Clause Open MPI variant (BSD-3-Clause-Open-MPI)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD 3-Clause Open MPI variant
|Shortname |BSD-3-Clause-Open-MPI
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `Open MPI License`
* `scancode://bsd-3-clause-open-mpi`

=== Comments on (easy) usability

=== General Comments

* ``http://www.open-mpi.org/community/license.php'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:* https://www.open-mpi.org/community/license.php
* *SPDX:* http://spdx.org/licenses/BSD-3-Clause-Open-MPI.json
* *open-license:* http://open-license.hitachi.com/licenses/831
* http://www.netlib.org/lapack/LICENSE.txt

=== Description from open-license

* {blank}
+
....
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use binaries generated from modified source code

Conditions: None
....
* {blank}
+
....
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribution of Modified Source Code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license
....
* {blank}
+
....
Actions:
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribute the generated binaries from modified source code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license
....
* {blank}
+
....
Actions:
- Use the name of the owner or contributor to promote or sell the derived product

Conditions:
REQUISITE: Get special permission in writing.
....

(source: Hitachi open-license)

=== Text

....
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

- Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

- Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer listed
  in this license in the documentation and/or other materials
  provided with the distribution.

- Neither the name of the copyright holders nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

The copyright holders provide no reassurances that the source code
provided does not infringe any patent, copyright, or any other
intellectual property rights of third parties.  The copyright holders
disclaim any liability to any recipient for claims brought against
recipient by any third party for infringement of that parties
intellectual property rights.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html[SPDX] (all data
[in this repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-3-clause-open-mpi.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-3-Clause-Open-MPI",
        "Open MPI License",
        "BSD 3-Clause Open MPI variant",
        "scancode://bsd-3-clause-open-mpi"
    ],
    "__impliedId": "BSD-3-Clause-Open-MPI",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "http://www.open-mpi.org/community/license.php"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-3-Clause-Open-MPI"
                ],
                "__impliedId": "BSD-3-Clause-Open-MPI"
            },
            "shortname": "BSD-3-Clause-Open-MPI",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD 3-Clause Open MPI variant",
            "spdxDetailsURL": "http://spdx.org/licenses/BSD-3-Clause-Open-MPI.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.open-mpi.org/community/license.php",
                "http://www.netlib.org/lapack/LICENSE.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-3-Clause-Open-MPI",
                    "BSD 3-Clause Open MPI variant"
                ],
                "__impliedId": "BSD-3-Clause-Open-MPI",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BSD-3-Clause-Open-MPI.json"
                    ],
                    [
                        null,
                        "https://www.open-mpi.org/community/license.php"
                    ],
                    [
                        null,
                        "http://www.netlib.org/lapack/LICENSE.txt"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-3-Clause-Open-MPI"
        },
        "Scancode": {
            "otherUrls": [
                "https://www.open-mpi.org/community/license.php",
                "http://www.netlib.org/lapack/LICENSE.txt"
            ],
            "homepageUrl": "https://www.open-mpi.org/community/license.php",
            "shortName": "BSD 3-Clause Open MPI variant",
            "textUrls": null,
            "text": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n- Redistributions of source code must retain the above copyright\n  notice, this list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright\n  notice, this list of conditions and the following disclaimer listed\n  in this license in the documentation and/or other materials\n  provided with the distribution.\n\n- Neither the name of the copyright holders nor the names of its\n  contributors may be used to endorse or promote products derived from\n  this software without specific prior written permission.\n\nThe copyright holders provide no reassurances that the source code\nprovided does not infringe any patent, copyright, or any other\nintellectual property rights of third parties.  The copyright holders\ndisclaim any liability to any recipient for claims brought against\nrecipient by any third party for infringement of that parties\nintellectual property rights.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Open MPI",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-3-clause-open-mpi.yml",
            "key": "bsd-3-clause-open-mpi",
            "name": "BSD 3-Clause Open MPI variant",
            "spdxId": "BSD-3-Clause-Open-MPI",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://bsd-3-clause-open-mpi",
                    "BSD 3-Clause Open MPI variant",
                    "BSD-3-Clause-Open-MPI"
                ],
                "__impliedId": "BSD-3-Clause-Open-MPI",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n- Redistributions of source code must retain the above copyright\n  notice, this list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright\n  notice, this list of conditions and the following disclaimer listed\n  in this license in the documentation and/or other materials\n  provided with the distribution.\n\n- Neither the name of the copyright holders nor the names of its\n  contributors may be used to endorse or promote products derived from\n  this software without specific prior written permission.\n\nThe copyright holders provide no reassurances that the source code\nprovided does not infringe any patent, copyright, or any other\nintellectual property rights of third parties.  The copyright holders\ndisclaim any liability to any recipient for claims brought against\nrecipient by any third party for infringement of that parties\nintellectual property rights.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://www.open-mpi.org/community/license.php"
                    ],
                    [
                        null,
                        "https://www.open-mpi.org/community/license.php"
                    ],
                    [
                        null,
                        "http://www.netlib.org/lapack/LICENSE.txt"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "http://www.open-mpi.org/community/license.php",
            "notices": [
                {
                    "content": "the software is provided by the copyright holders and contributors \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "Neither the copyright owner nor any contributor, for any cause whatsoever, shall be liable for damages, regardless of how caused, and regardless of whether the liability is based on contract, strict liability, or tort (including negligence), even if they have been advised of the possibility of such damages arising from the use of the software, and even if they have been advised of the possibility of such damages. for any direct, indirect, incidental, special, punitive, or consequential damages (including, but not limited to, compensation for procurement of substitute goods or services, loss of use, loss of data, loss of profits, or business interruption). It shall not be defeated."
                },
                {
                    "content": "The copyright holder does not warrant again that the source code provided does not infringe any intellectual property rights, such as patents or copyrights, of third parties."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/831",
            "content": "Open MPI is distributed under the \"New BSD license\"[http://www.opensource.org/licenses/bsd-license.php], listed below. \n----------------------------------------\nMost files in this release are marked with the copyrights of the\norganizations who have edited them.  The copyrights below are in no\nparticular order and generally reflect members of the Open MPI core\nteam who have contributed code to this release.  The copyrights for\ncode used under license from other parties are included in the\ncorresponding files.\n\nCopyright (c) 2004-2010 The Trustees of Indiana University and Indiana\n                        University Research and Technology\n                        Corporation.  All rights reserved.\nCopyright (c) 2004-2010 The University of Tennessee and The University\n                        of Tennessee Research Foundation.  All rights\n                        reserved.\nCopyright (c) 2004-2010 High Performance Computing Center Stuttgart, \n                        University of Stuttgart.  All rights reserved.\nCopyright (c) 2004-2008 The Regents of the University of California.\n                        All rights reserved.\nCopyright (c) 2006-2010 Los Alamos National Security, LLC.  All rights\n                        reserved. \nCopyright (c) 2006-2010 Cisco Systems, Inc.  All rights reserved.\nCopyright (c) 2006-2010 Voltaire, Inc. All rights reserved.\nCopyright (c) 2006-2011 Sandia National Laboratories. All rights reserved.\nCopyright (c) 2006-2010 Sun Microsystems, Inc.  All rights reserved.\n                        Use is subject to license terms.\nCopyright (c) 2006-2010 The University of Houston. All rights reserved.\nCopyright (c) 2006-2009 Myricom, Inc.  All rights reserved.\nCopyright (c) 2007-2008 UT-Battelle, LLC. All rights reserved.\nCopyright (c) 2007-2010 IBM Corporation.  All rights reserved.\nCopyright (c) 1998-2005 Forschungszentrum Juelich, Juelich Supercomputing \n                        Centre, Federal Republic of Germany\nCopyright (c) 2005-2008 ZIH, TU Dresden, Federal Republic of Germany\nCopyright (c) 2007      Evergrid, Inc. All rights reserved.\nCopyright (c) 2008      Chelsio, Inc.  All rights reserved.\nCopyright (c) 2008-2009 Institut National de Recherche en\n                        Informatique.  All rights reserved.\nCopyright (c) 2007      Lawrence Livermore National Security, LLC.\n                        All rights reserved.\nCopyright (c) 2007-2009 Mellanox Technologies.  All rights reserved.\nCopyright (c) 2006-2010 QLogic Corporation.  All rights reserved.\nCopyright (c) 2008-2010 Oak Ridge National Labs.  All rights reserved.\nCopyright (c) 2006-2010 Oracle and/or its affiliates.  All rights reserved.\nCopyright (c) 2009      Bull SAS.  All rights reserved.\nCopyright (c) 2010      ARM ltd.  All rights reserved.\nCopyright (c) 2010-2011 Alex Brick <bricka@ccs.neu.edu>.  All rights reserved.\nCopyright (c) 2013-2014 Intel, Inc. All rights reserved.\nCopyright (c) 2011-2014 NVIDIA Corporation.  All rights reserved.\n\n$COPYRIGHT$\n\nAdditional copyrights may follow\n\n$HEADER$\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n- Redistributions of source code must retain the above copyright\n  notice, this list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright\n  notice, this list of conditions and the following disclaimer listed\n  in this license in the documentation and/or other materials\n  provided with the distribution.\n\n- Neither the name of the copyright holders nor the names of its\n  contributors may be used to endorse or promote products derived from\n  this software without specific prior written permission.\n\nThe copyright holders provide no reassurances that the source code\nprovided does not infringe any patent, copyright, or any other\nintellectual property rights of third parties.  The copyright holders\ndisclaim any liability to any recipient for claims brought against\nrecipient by any third party for infringement of that parties\nintellectual property rights.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
            "name": "Open MPI License",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use binaries generated from modified source code\n\nConditions: None\n",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribute the generated binaries from modified source code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Use the name of the owner or contributor to promote or sell the derived product"
                        }
                    ],
                    "_str": "Actions:\n- Use the name of the owner or contributor to promote or sell the derived product\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    }
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Open MPI License",
                    "BSD-3-Clause-Open-MPI"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "http://www.open-mpi.org/community/license.php"
                        ]
                    ]
                ],
                "__impliedText": "Open MPI is distributed under the \"New BSD license\"[http://www.opensource.org/licenses/bsd-license.php], listed below. \n----------------------------------------\nMost files in this release are marked with the copyrights of the\norganizations who have edited them.  The copyrights below are in no\nparticular order and generally reflect members of the Open MPI core\nteam who have contributed code to this release.  The copyrights for\ncode used under license from other parties are included in the\ncorresponding files.\n\nCopyright (c) 2004-2010 The Trustees of Indiana University and Indiana\n                        University Research and Technology\n                        Corporation.  All rights reserved.\nCopyright (c) 2004-2010 The University of Tennessee and The University\n                        of Tennessee Research Foundation.  All rights\n                        reserved.\nCopyright (c) 2004-2010 High Performance Computing Center Stuttgart, \n                        University of Stuttgart.  All rights reserved.\nCopyright (c) 2004-2008 The Regents of the University of California.\n                        All rights reserved.\nCopyright (c) 2006-2010 Los Alamos National Security, LLC.  All rights\n                        reserved. \nCopyright (c) 2006-2010 Cisco Systems, Inc.  All rights reserved.\nCopyright (c) 2006-2010 Voltaire, Inc. All rights reserved.\nCopyright (c) 2006-2011 Sandia National Laboratories. All rights reserved.\nCopyright (c) 2006-2010 Sun Microsystems, Inc.  All rights reserved.\n                        Use is subject to license terms.\nCopyright (c) 2006-2010 The University of Houston. All rights reserved.\nCopyright (c) 2006-2009 Myricom, Inc.  All rights reserved.\nCopyright (c) 2007-2008 UT-Battelle, LLC. All rights reserved.\nCopyright (c) 2007-2010 IBM Corporation.  All rights reserved.\nCopyright (c) 1998-2005 Forschungszentrum Juelich, Juelich Supercomputing \n                        Centre, Federal Republic of Germany\nCopyright (c) 2005-2008 ZIH, TU Dresden, Federal Republic of Germany\nCopyright (c) 2007      Evergrid, Inc. All rights reserved.\nCopyright (c) 2008      Chelsio, Inc.  All rights reserved.\nCopyright (c) 2008-2009 Institut National de Recherche en\n                        Informatique.  All rights reserved.\nCopyright (c) 2007      Lawrence Livermore National Security, LLC.\n                        All rights reserved.\nCopyright (c) 2007-2009 Mellanox Technologies.  All rights reserved.\nCopyright (c) 2006-2010 QLogic Corporation.  All rights reserved.\nCopyright (c) 2008-2010 Oak Ridge National Labs.  All rights reserved.\nCopyright (c) 2006-2010 Oracle and/or its affiliates.  All rights reserved.\nCopyright (c) 2009      Bull SAS.  All rights reserved.\nCopyright (c) 2010      ARM ltd.  All rights reserved.\nCopyright (c) 2010-2011 Alex Brick <bricka@ccs.neu.edu>.  All rights reserved.\nCopyright (c) 2013-2014 Intel, Inc. All rights reserved.\nCopyright (c) 2011-2014 NVIDIA Corporation.  All rights reserved.\n\n$COPYRIGHT$\n\nAdditional copyrights may follow\n\n$HEADER$\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n- Redistributions of source code must retain the above copyright\n  notice, this list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright\n  notice, this list of conditions and the following disclaimer listed\n  in this license in the documentation and/or other materials\n  provided with the distribution.\n\n- Neither the name of the copyright holders nor the names of its\n  contributors may be used to endorse or promote products derived from\n  this software without specific prior written permission.\n\nThe copyright holders provide no reassurances that the source code\nprovided does not infringe any patent, copyright, or any other\nintellectual property rights of third parties.  The copyright holders\ndisclaim any liability to any recipient for claims brought against\nrecipient by any third party for infringement of that parties\nintellectual property rights.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/831"
                    ]
                ]
            }
        }
    },
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\n- Redistributions of source code must retain the above copyright\n  notice, this list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright\n  notice, this list of conditions and the following disclaimer listed\n  in this license in the documentation and/or other materials\n  provided with the distribution.\n\n- Neither the name of the copyright holders nor the names of its\n  contributors may be used to endorse or promote products derived from\n  this software without specific prior written permission.\n\nThe copyright holders provide no reassurances that the source code\nprovided does not infringe any patent, copyright, or any other\nintellectual property rights of third parties.  The copyright holders\ndisclaim any liability to any recipient for claims brought against\nrecipient by any third party for infringement of that parties\nintellectual property rights.\n\nTHIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
    "__impliedURLs": [
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/831"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BSD-3-Clause-Open-MPI.json"
        ],
        [
            null,
            "https://www.open-mpi.org/community/license.php"
        ],
        [
            null,
            "http://www.netlib.org/lapack/LICENSE.txt"
        ],
        [
            "Homepage",
            "https://www.open-mpi.org/community/license.php"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-3-Clause-Open-MPI.svg
