== BSD-2-Clause Plus Patent License (BSD-2-Clause-Patent)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD-2-Clause Plus Patent License
|Shortname |BSD-2-Clause-Patent
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/BSD-2-Clause-Patent.html[SPDX] (all data [in
this repository] is generated))
* **↑**``Rating is: Gold'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/BSD-2-Clause-Patent.html
* *SPDX:* http://spdx.org/licenses/BSD-2-Clause-Patent.json
* https://opensource.org/licenses/BSDplusPatent

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/BSD-2-Clause-Patent.html[SPDX] (all data [in
this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-2-Clause-Patent",
        "BSD-2-Clause Plus Patent License"
    ],
    "__impliedId": "BSD-2-Clause-Patent",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Patent"
                ],
                "__impliedId": "BSD-2-Clause-Patent"
            },
            "shortname": "BSD-2-Clause-Patent",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD-2-Clause Plus Patent License",
            "spdxDetailsURL": "http://spdx.org/licenses/BSD-2-Clause-Patent.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-2-Clause-Patent.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/BSDplusPatent"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Patent",
                    "BSD-2-Clause Plus Patent License"
                ],
                "__impliedId": "BSD-2-Clause-Patent",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/BSD-2-Clause-Patent.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/BSDplusPatent"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-2-Clause-Patent"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "BSD+Patent",
            "commercialUse": true,
            "spdxId": "BSD-2-Clause-Patent",
            "_implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Patent"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Gold",
            "url": "https://spdx.org/licenses/BSD-2-Clause-Patent.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD-2-Clause Plus Patent License",
            "id": "BSD-2-Clause-Patent",
            "_implications": {
                "__impliedNames": [
                    "BSD-2-Clause-Patent",
                    "BSD-2-Clause Plus Patent License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Gold"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-2-Clause-Patent.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Gold"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-2-Clause-Patent.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/BSD-2-Clause-Patent.json"
        ],
        [
            null,
            "https://opensource.org/licenses/BSDplusPatent"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-2-Clause-Patent.svg
