== BSD 3-Clause Modification (BSD-3-Clause-Modification)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |BSD 3-Clause Modification
|Shortname |BSD-3-Clause-Modification
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://repoze`
* `Repoze License`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``found in Debian reportbug'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/repoze.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* http://repoze.org/license.html
* *SPDX:* https://spdx.org/licenses/BSD-3-Clause-Modification.html
* *SPDX:* https://spdx.org/licenses/BSD-3-Clause-Modification.json
* https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant

=== Text

....
A copyright notice accompanies this license document that identifies the copyright
holders.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

Redistributions in source code must retain the accompanying
copyright notice, this list of conditions, and the following
disclaimer.

Redistributions in binary form must reproduce the accompanying
copyright notice, this list of conditions, and the following
disclaimer in the documentation and/or other materials provided
with the distribution.

Names of the copyright holders must not be used to endorse or
promote products derived from this software without prior
written permission from the copyright holders.

If any files are modified, you must cause the modified files to
carry prominent notices stating that you changed the files and
the date of any change.

Disclaimer

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND
  ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
  SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/BSD-3-Clause-Modification.html[SPDX] (all
data [in this repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/repoze.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "BSD-3-Clause-Modification",
        "BSD 3-Clause Modification",
        "scancode://repoze",
        "Repoze License"
    ],
    "__impliedId": "BSD-3-Clause-Modification",
    "__impliedComments": [
        [
            "Scancode",
            [
                "found in Debian reportbug"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BSD-3-Clause-Modification"
                ],
                "__impliedId": "BSD-3-Clause-Modification"
            },
            "shortname": "BSD-3-Clause-Modification",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "BSD 3-Clause Modification",
            "spdxDetailsURL": "https://spdx.org/licenses/BSD-3-Clause-Modification.json",
            "_sourceURL": "https://spdx.org/licenses/BSD-3-Clause-Modification.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant"
            ],
            "_implications": {
                "__impliedNames": [
                    "BSD-3-Clause-Modification",
                    "BSD 3-Clause Modification"
                ],
                "__impliedId": "BSD-3-Clause-Modification",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-3-Clause-Modification.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant"
                    ]
                ]
            },
            "spdxLicenseId": "BSD-3-Clause-Modification"
        },
        "Scancode": {
            "otherUrls": [
                "https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant"
            ],
            "homepageUrl": "http://repoze.org/license.html",
            "shortName": "Repoze License",
            "textUrls": null,
            "text": "A copyright notice accompanies this license document that identifies the copyright\nholders.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\nRedistributions in source code must retain the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer.\n\nRedistributions in binary form must reproduce the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer in the documentation and/or other materials provided\nwith the distribution.\n\nNames of the copyright holders must not be used to endorse or\npromote products derived from this software without prior\nwritten permission from the copyright holders.\n\nIf any files are modified, you must cause the modified files to\ncarry prominent notices stating that you changed the files and\nthe date of any change.\n\nDisclaimer\n\n  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND\n  ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED\n  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n  HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\n  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR\n  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF\n  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n  SUCH DAMAGE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Repoze",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/repoze.yml",
            "key": "repoze",
            "name": "Repoze License",
            "spdxId": "BSD-3-Clause-Modification",
            "notes": "found in Debian reportbug",
            "_implications": {
                "__impliedNames": [
                    "scancode://repoze",
                    "Repoze License",
                    "BSD-3-Clause-Modification"
                ],
                "__impliedId": "BSD-3-Clause-Modification",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "found in Debian reportbug"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "A copyright notice accompanies this license document that identifies the copyright\nholders.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\nRedistributions in source code must retain the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer.\n\nRedistributions in binary form must reproduce the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer in the documentation and/or other materials provided\nwith the distribution.\n\nNames of the copyright holders must not be used to endorse or\npromote products derived from this software without prior\nwritten permission from the copyright holders.\n\nIf any files are modified, you must cause the modified files to\ncarry prominent notices stating that you changed the files and\nthe date of any change.\n\nDisclaimer\n\n  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND\n  ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED\n  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n  HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\n  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR\n  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF\n  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n  SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://repoze.org/license.html"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/BSD-3-Clause-Modification.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "BSD 3-Clause Modification",
            "id": "BSD-3-Clause-Modification",
            "_implications": {
                "__impliedNames": [
                    "BSD-3-Clause-Modification",
                    "BSD 3-Clause Modification"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BSD-3-Clause-Modification.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "A copyright notice accompanies this license document that identifies the copyright\nholders.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions are\nmet:\n\nRedistributions in source code must retain the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer.\n\nRedistributions in binary form must reproduce the accompanying\ncopyright notice, this list of conditions, and the following\ndisclaimer in the documentation and/or other materials provided\nwith the distribution.\n\nNames of the copyright holders must not be used to endorse or\npromote products derived from this software without prior\nwritten permission from the copyright holders.\n\nIf any files are modified, you must cause the modified files to\ncarry prominent notices stating that you changed the files and\nthe date of any change.\n\nDisclaimer\n\n  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND\n  ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED\n  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n  HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED\n  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON\n  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR\n  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF\n  THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n  SUCH DAMAGE.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-3-Clause-Modification.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/BSD-3-Clause-Modification.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant"
        ],
        [
            "Homepage",
            "http://repoze.org/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BSD-3-Clause-Modification.svg
