== Business Source License 1.1 (BUSL-1.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Business Source License 1.1
|Shortname |BUSL-1.1
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Businnes-Source-1.1`
* `scancode://bsl-1.1`

=== Comments on (easy) usability

=== General Comments

* ``category: Business Source License'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/[bu]/Business-Source-License-1.1.yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *Homepage:* https://mariadb.com/bsl11/
* *SPDX:* https://spdx.org/licenses/BUSL-1.1.json
* https://mariadb.com/bsl-faq-adopting/
* https://mariadb.com/products/mariadb-enterprise

=== Text

....
Business Source License 1.1

License text copyright © 2017 MariaDB Corporation Ab, All Rights Reserved.
"Business Source License" is a trademark of MariaDB Corporation Ab.

Terms

The Licensor hereby grants you the right to copy, modify, create derivative
works, redistribute, and make non-production use of the Licensed Work. The
Licensor may make an Additional Use Grant, above, permitting limited production
use.

Effective on the Change Date, or the fourth anniversary of the first publicly
available distribution of a specific version of the Licensed Work under this
License, whichever comes first, the Licensor hereby grants you rights under the
terms of the Change License, and the rights granted in the paragraph above
terminate.

If your use of the Licensed Work does not comply with the requirements currently
in effect as described in this License, you must purchase a commercial license
from the Licensor, its affiliated entities, or authorized resellers, or you must
refrain from using the Licensed Work.

All copies of the original and modified Licensed Work, and derivative works of
the Licensed Work, are subject to this License. This License applies separately
for each version of the Licensed Work and the Change Date may vary for each
version of the Licensed Work released by Licensor.

You must conspicuously display this License on each original or modified copy of
the Licensed Work. If you receive the Licensed Work in original or modified form
from a third party, the terms and conditions set forth in this License apply to
your use of that work.

Any use of the Licensed Work in violation of this License will automatically
terminate your rights under this License for the current and all other versions
of the Licensed Work.

This License does not grant you any right in any trademark or logo of Licensor
or its affiliates (provided that you may use a trademark or logo of Licensor as
expressly required by this License).

TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON AN
"AS IS" BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS
OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.MariaDB hereby
grants you permission to use this License’s text to license your works, and to
refer to it using the trademark "Business Source License", as long as you comply
with the Covenants of Licensor below.

Covenants of Licensor

In consideration of the right to use this License’s text and the "Business
Source License" name and trademark, Licensor covenants to MariaDB, and to all
other recipients of the licensed work to be provided by Licensor:

    1. To specify as the Change License the GPL Version 2.0 or any later
    version, or a license that is compatible with GPL Version 2.0 or a later
    version, where "compatible" means that software provided under the Change
    License can be included in a program with software provided under GPL
    Version 2.0 or a later version. Licensor may specify additional Change
    Licenses without limitation.

    2. To either: (a) specify an additional grant of rights to use that does not
    impose any additional restriction on the right granted in this License, as
    the Additional Use Grant; or (b) insert the text "None".

    3. To specify a Change Date.

    4. Not to modify this License in any other way.

Notice

The Business Source License (this document, or the "License") is not an Open
Source license. However, the Licensed Work will eventually be made available
under an Open Source License, as stated in this License.

For more information on the use of the Business Source License for MariaDB
products, please visit the MariaDB Business Source License FAQ.
For more information on the use of the Business Source License generally, please
visit the Adopting and Developing Business Source License FAQ.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/[bu]/Business-Source-License-1.1.yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/BUSL-1.1.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsl-1.1.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "BUSL-1.1",
        "Business Source License 1.1",
        "Businnes-Source-1.1",
        "scancode://bsl-1.1"
    ],
    "__impliedId": "BUSL-1.1",
    "__impliedAmbiguousNames": [
        "Business Source License 1.1",
        "https://github.com/getsentry/sentry/blob/master/LICENSE",
        "scancode:bsl-1.1"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: Business Source License"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "BUSL-1.1"
                ],
                "__impliedId": "BUSL-1.1"
            },
            "shortname": "BUSL-1.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Business Source License 1.1",
            "spdxDetailsURL": "https://spdx.org/licenses/BUSL-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/BUSL-1.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://mariadb.com/bsl11/"
            ],
            "_implications": {
                "__impliedNames": [
                    "BUSL-1.1",
                    "Business Source License 1.1"
                ],
                "__impliedId": "BUSL-1.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/BUSL-1.1.json"
                    ],
                    [
                        null,
                        "https://mariadb.com/bsl11/"
                    ]
                ]
            },
            "spdxLicenseId": "BUSL-1.1"
        },
        "Scancode": {
            "otherUrls": [
                "https://mariadb.com/bsl-faq-adopting/",
                "https://mariadb.com/products/mariadb-enterprise"
            ],
            "homepageUrl": "https://mariadb.com/bsl11/",
            "shortName": "Business Source License 1.1",
            "textUrls": null,
            "text": "Business Source License 1.1\n\nLicense text copyright Â© 2017 MariaDB Corporation Ab, All Rights Reserved.\n\"Business Source License\" is a trademark of MariaDB Corporation Ab.\n\nTerms\n\nThe Licensor hereby grants you the right to copy, modify, create derivative\nworks, redistribute, and make non-production use of the Licensed Work. The\nLicensor may make an Additional Use Grant, above, permitting limited production\nuse.\n\nEffective on the Change Date, or the fourth anniversary of the first publicly\navailable distribution of a specific version of the Licensed Work under this\nLicense, whichever comes first, the Licensor hereby grants you rights under the\nterms of the Change License, and the rights granted in the paragraph above\nterminate.\n\nIf your use of the Licensed Work does not comply with the requirements currently\nin effect as described in this License, you must purchase a commercial license\nfrom the Licensor, its affiliated entities, or authorized resellers, or you must\nrefrain from using the Licensed Work.\n\nAll copies of the original and modified Licensed Work, and derivative works of\nthe Licensed Work, are subject to this License. This License applies separately\nfor each version of the Licensed Work and the Change Date may vary for each\nversion of the Licensed Work released by Licensor.\n\nYou must conspicuously display this License on each original or modified copy of\nthe Licensed Work. If you receive the Licensed Work in original or modified form\nfrom a third party, the terms and conditions set forth in this License apply to\nyour use of that work.\n\nAny use of the Licensed Work in violation of this License will automatically\nterminate your rights under this License for the current and all other versions\nof the Licensed Work.\n\nThis License does not grant you any right in any trademark or logo of Licensor\nor its affiliates (provided that you may use a trademark or logo of Licensor as\nexpressly required by this License).\n\nTO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON AN\n\"AS IS\" BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS\nOR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.MariaDB hereby\ngrants you permission to use this Licenseâs text to license your works, and to\nrefer to it using the trademark \"Business Source License\", as long as you comply\nwith the Covenants of Licensor below.\n\nCovenants of Licensor\n\nIn consideration of the right to use this Licenseâs text and the \"Business\nSource License\" name and trademark, Licensor covenants to MariaDB, and to all\nother recipients of the licensed work to be provided by Licensor:\n\n    1. To specify as the Change License the GPL Version 2.0 or any later\n    version, or a license that is compatible with GPL Version 2.0 or a later\n    version, where \"compatible\" means that software provided under the Change\n    License can be included in a program with software provided under GPL\n    Version 2.0 or a later version. Licensor may specify additional Change\n    Licenses without limitation.\n\n    2. To either: (a) specify an additional grant of rights to use that does not\n    impose any additional restriction on the right granted in this License, as\n    the Additional Use Grant; or (b) insert the text \"None\".\n\n    3. To specify a Change Date.\n\n    4. Not to modify this License in any other way.\n\nNotice\n\nThe Business Source License (this document, or the \"License\") is not an Open\nSource license. However, the Licensed Work will eventually be made available\nunder an Open Source License, as stated in this License.\n\nFor more information on the use of the Business Source License for MariaDB\nproducts, please visit the MariaDB Business Source License FAQ.\nFor more information on the use of the Business Source License generally, please\nvisit the Adopting and Developing Business Source License FAQ.\n",
            "category": "Source-available",
            "osiUrl": null,
            "owner": "MariaDB",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsl-1.1.yml",
            "key": "bsl-1.1",
            "name": "Business Source License 1.1",
            "spdxId": "BUSL-1.1",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://bsl-1.1",
                    "Business Source License 1.1",
                    "BUSL-1.1"
                ],
                "__impliedId": "BUSL-1.1",
                "__impliedText": "Business Source License 1.1\n\nLicense text copyright © 2017 MariaDB Corporation Ab, All Rights Reserved.\n\"Business Source License\" is a trademark of MariaDB Corporation Ab.\n\nTerms\n\nThe Licensor hereby grants you the right to copy, modify, create derivative\nworks, redistribute, and make non-production use of the Licensed Work. The\nLicensor may make an Additional Use Grant, above, permitting limited production\nuse.\n\nEffective on the Change Date, or the fourth anniversary of the first publicly\navailable distribution of a specific version of the Licensed Work under this\nLicense, whichever comes first, the Licensor hereby grants you rights under the\nterms of the Change License, and the rights granted in the paragraph above\nterminate.\n\nIf your use of the Licensed Work does not comply with the requirements currently\nin effect as described in this License, you must purchase a commercial license\nfrom the Licensor, its affiliated entities, or authorized resellers, or you must\nrefrain from using the Licensed Work.\n\nAll copies of the original and modified Licensed Work, and derivative works of\nthe Licensed Work, are subject to this License. This License applies separately\nfor each version of the Licensed Work and the Change Date may vary for each\nversion of the Licensed Work released by Licensor.\n\nYou must conspicuously display this License on each original or modified copy of\nthe Licensed Work. If you receive the Licensed Work in original or modified form\nfrom a third party, the terms and conditions set forth in this License apply to\nyour use of that work.\n\nAny use of the Licensed Work in violation of this License will automatically\nterminate your rights under this License for the current and all other versions\nof the Licensed Work.\n\nThis License does not grant you any right in any trademark or logo of Licensor\nor its affiliates (provided that you may use a trademark or logo of Licensor as\nexpressly required by this License).\n\nTO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON AN\n\"AS IS\" BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS\nOR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.MariaDB hereby\ngrants you permission to use this License’s text to license your works, and to\nrefer to it using the trademark \"Business Source License\", as long as you comply\nwith the Covenants of Licensor below.\n\nCovenants of Licensor\n\nIn consideration of the right to use this License’s text and the \"Business\nSource License\" name and trademark, Licensor covenants to MariaDB, and to all\nother recipients of the licensed work to be provided by Licensor:\n\n    1. To specify as the Change License the GPL Version 2.0 or any later\n    version, or a license that is compatible with GPL Version 2.0 or a later\n    version, where \"compatible\" means that software provided under the Change\n    License can be included in a program with software provided under GPL\n    Version 2.0 or a later version. Licensor may specify additional Change\n    Licenses without limitation.\n\n    2. To either: (a) specify an additional grant of rights to use that does not\n    impose any additional restriction on the right granted in this License, as\n    the Additional Use Grant; or (b) insert the text \"None\".\n\n    3. To specify a Change Date.\n\n    4. Not to modify this License in any other way.\n\nNotice\n\nThe Business Source License (this document, or the \"License\") is not an Open\nSource license. However, the Licensed Work will eventually be made available\nunder an Open Source License, as stated in this License.\n\nFor more information on the use of the Business Source License for MariaDB\nproducts, please visit the MariaDB Business Source License FAQ.\nFor more information on the use of the Business Source License generally, please\nvisit the Adopting and Developing Business Source License FAQ.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://mariadb.com/bsl11/"
                    ],
                    [
                        null,
                        "https://mariadb.com/bsl-faq-adopting/"
                    ],
                    [
                        null,
                        "https://mariadb.com/products/mariadb-enterprise"
                    ]
                ]
            }
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "BUSL-1.1",
            "shortName": "Businnes-Source-1.1",
            "category": "Business Source License",
            "alternativeNames": [
                "Business Source License 1.1",
                "https://github.com/getsentry/sentry/blob/master/LICENSE"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/[bu]/Business-Source-License-1.1.yaml",
            "otherIds": [
                "scancode:bsl-1.1"
            ],
            "canonicalName": "Business Source License 1.1",
            "_implications": {
                "__impliedNames": [
                    "Business Source License 1.1",
                    "Businnes-Source-1.1",
                    "BUSL-1.1"
                ],
                "__impliedId": "BUSL-1.1",
                "__impliedAmbiguousNames": [
                    "Business Source License 1.1",
                    "https://github.com/getsentry/sentry/blob/master/LICENSE",
                    "scancode:bsl-1.1"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: Business Source License"
                        ]
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedText": "Business Source License 1.1\n\nLicense text copyright © 2017 MariaDB Corporation Ab, All Rights Reserved.\n\"Business Source License\" is a trademark of MariaDB Corporation Ab.\n\nTerms\n\nThe Licensor hereby grants you the right to copy, modify, create derivative\nworks, redistribute, and make non-production use of the Licensed Work. The\nLicensor may make an Additional Use Grant, above, permitting limited production\nuse.\n\nEffective on the Change Date, or the fourth anniversary of the first publicly\navailable distribution of a specific version of the Licensed Work under this\nLicense, whichever comes first, the Licensor hereby grants you rights under the\nterms of the Change License, and the rights granted in the paragraph above\nterminate.\n\nIf your use of the Licensed Work does not comply with the requirements currently\nin effect as described in this License, you must purchase a commercial license\nfrom the Licensor, its affiliated entities, or authorized resellers, or you must\nrefrain from using the Licensed Work.\n\nAll copies of the original and modified Licensed Work, and derivative works of\nthe Licensed Work, are subject to this License. This License applies separately\nfor each version of the Licensed Work and the Change Date may vary for each\nversion of the Licensed Work released by Licensor.\n\nYou must conspicuously display this License on each original or modified copy of\nthe Licensed Work. If you receive the Licensed Work in original or modified form\nfrom a third party, the terms and conditions set forth in this License apply to\nyour use of that work.\n\nAny use of the Licensed Work in violation of this License will automatically\nterminate your rights under this License for the current and all other versions\nof the Licensed Work.\n\nThis License does not grant you any right in any trademark or logo of Licensor\nor its affiliates (provided that you may use a trademark or logo of Licensor as\nexpressly required by this License).\n\nTO THE EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED WORK IS PROVIDED ON AN\n\"AS IS\" BASIS. LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS\nOR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.MariaDB hereby\ngrants you permission to use this License’s text to license your works, and to\nrefer to it using the trademark \"Business Source License\", as long as you comply\nwith the Covenants of Licensor below.\n\nCovenants of Licensor\n\nIn consideration of the right to use this License’s text and the \"Business\nSource License\" name and trademark, Licensor covenants to MariaDB, and to all\nother recipients of the licensed work to be provided by Licensor:\n\n    1. To specify as the Change License the GPL Version 2.0 or any later\n    version, or a license that is compatible with GPL Version 2.0 or a later\n    version, where \"compatible\" means that software provided under the Change\n    License can be included in a program with software provided under GPL\n    Version 2.0 or a later version. Licensor may specify additional Change\n    Licenses without limitation.\n\n    2. To either: (a) specify an additional grant of rights to use that does not\n    impose any additional restriction on the right granted in this License, as\n    the Additional Use Grant; or (b) insert the text \"None\".\n\n    3. To specify a Change Date.\n\n    4. Not to modify this License in any other way.\n\nNotice\n\nThe Business Source License (this document, or the \"License\") is not an Open\nSource license. However, the Licensed Work will eventually be made available\nunder an Open Source License, as stated in this License.\n\nFor more information on the use of the Business Source License for MariaDB\nproducts, please visit the MariaDB Business Source License FAQ.\nFor more information on the use of the Business Source License generally, please\nvisit the Adopting and Developing Business Source License FAQ.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/BUSL-1.1.json"
        ],
        [
            null,
            "https://mariadb.com/bsl11/"
        ],
        [
            "Homepage",
            "https://mariadb.com/bsl11/"
        ],
        [
            null,
            "https://mariadb.com/bsl-faq-adopting/"
        ],
        [
            null,
            "https://mariadb.com/products/mariadb-enterprise"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/BUSL-1.1.svg
