== bzip2 and libbzip2 License v1.0.6 (bzip2-1.0.6)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |bzip2 and libbzip2 License v1.0.6
|Shortname |bzip2-1.0.6
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+The bzip2 license+`
* `+scancode://bzip2-libbzip-2010+`
* `+bzip2 License 2010+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``until bzip2 1.0.6 there is only one license and not two as listed in
SPDX'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bzip2-libbzip-2010.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* https://github.com/asimonov-im/bzip2/blob/master/LICENSE
* *SPDX:* http://spdx.org/licenses/bzip2-1.0.6.json
* *SPDX:* https://spdx.org/licenses/bzip2-1.0.6.html
* *open-license:* http://open-license.hitachi.com/licenses/381
* https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6
* http://bzip.org/1.0.5/bzip2-manual-1.0.5.html
* http://www.bzip.org/

=== Text

....
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. The origin of this software must not be misrepresented; you must
   not claim that you wrote the original software.  If you use this
   software in a product, an acknowledgment in the product
   documentation would be appreciated but is not required.

3. Altered source versions must be plainly marked as such, and must
   not be misrepresented as being the original software.

4. The name of the author may not be used to endorse or promote
   products derived from this software without specific prior written
   permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* Override
* https://spdx.org/licenses/bzip2-1.0.6.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bzip2-libbzip-2010.yml[Scancode]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "bzip2-1.0.6",
        "The bzip2 license",
        "bzip2 and libbzip2 License v1.0.6",
        "scancode://bzip2-libbzip-2010",
        "bzip2 License 2010"
    ],
    "__impliedId": "bzip2-1.0.6",
    "__impliedComments": [
        [
            "Hitachi open-license",
            []
        ],
        [
            "Scancode",
            [
                "until bzip2 1.0.6 there is only one license and not two as listed in SPDX"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "bzip2-1.0.6"
                ],
                "__impliedId": "bzip2-1.0.6"
            },
            "shortname": "bzip2-1.0.6",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "bzip2 and libbzip2 License v1.0.6",
            "spdxDetailsURL": "http://spdx.org/licenses/bzip2-1.0.6.json",
            "_sourceURL": "https://spdx.org/licenses/bzip2-1.0.6.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6",
                "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "bzip2-1.0.6",
                    "bzip2 and libbzip2 License v1.0.6"
                ],
                "__impliedId": "bzip2-1.0.6",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/bzip2-1.0.6.json"
                    ],
                    [
                        null,
                        "https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6"
                    ],
                    [
                        null,
                        "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html"
                    ]
                ]
            },
            "spdxLicenseId": "bzip2-1.0.6"
        },
        "Scancode": {
            "otherUrls": [
                "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html",
                "http://www.bzip.org/",
                "https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6"
            ],
            "homepageUrl": "https://github.com/asimonov-im/bzip2/blob/master/LICENSE",
            "shortName": "bzip2 License 2010",
            "textUrls": null,
            "text": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. The origin of this software must not be misrepresented; you must\n   not claim that you wrote the original software.  If you use this\n   software in a product, an acknowledgment in the product\n   documentation would be appreciated but is not required.\n\n3. Altered source versions must be plainly marked as such, and must\n   not be misrepresented as being the original software.\n\n4. The name of the author may not be used to endorse or promote\n   products derived from this software without specific prior written\n   permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS\nOR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\nARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\nDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE\nGOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\nWHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\nNEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "bzip",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bzip2-libbzip-2010.yml",
            "key": "bzip2-libbzip-2010",
            "name": "bzip2 License 2010",
            "spdxId": "bzip2-1.0.6",
            "notes": "until bzip2 1.0.6 there is only one license and not two as listed in SPDX",
            "_implications": {
                "__impliedNames": [
                    "scancode://bzip2-libbzip-2010",
                    "bzip2 License 2010",
                    "bzip2-1.0.6"
                ],
                "__impliedId": "bzip2-1.0.6",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "until bzip2 1.0.6 there is only one license and not two as listed in SPDX"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. The origin of this software must not be misrepresented; you must\n   not claim that you wrote the original software.  If you use this\n   software in a product, an acknowledgment in the product\n   documentation would be appreciated but is not required.\n\n3. Altered source versions must be plainly marked as such, and must\n   not be misrepresented as being the original software.\n\n4. The name of the author may not be used to endorse or promote\n   products derived from this software without specific prior written\n   permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS\nOR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\nARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\nDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE\nGOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\nWHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\nNEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://github.com/asimonov-im/bzip2/blob/master/LICENSE"
                    ],
                    [
                        null,
                        "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html"
                    ],
                    [
                        null,
                        "http://www.bzip.org/"
                    ],
                    [
                        null,
                        "https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6"
                    ]
                ]
            }
        },
        "Override": {
            "oNonCommecrial": null,
            "implications": {
                "__impliedNames": [
                    "bzip2-1.0.6",
                    "The bzip2 license"
                ],
                "__impliedId": "bzip2-1.0.6"
            },
            "oName": "bzip2-1.0.6",
            "oOtherLicenseIds": [
                "The bzip2 license"
            ],
            "oDescription": null,
            "oJudgement": null,
            "oCompatibilities": null,
            "oRatingState": null
        },
        "Hitachi open-license": {
            "notices": [
                {
                    "content": "the software is provided by the author \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "the author may be liable for direct or indirect damages arising from the use of the software, for any cause whatsoever, regardless of how caused, and regardless of whether the basis of liability is contract, strict liability, or tort (including negligence), even if he or she has been advised of the possibility of such damages In no event shall the company be liable for any incidental, special, punitive, or consequential damages (including, but not limited to, damages for procurement of substitute goods or substitute services, loss of use, loss of data, loss of profits, or for business interruption)."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/381",
            "content": "This program, \"bzip2\" and associated library \"libbzip2\", are copyright (C) 1996-2000 Julian R Seward. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: \r\n\r\n    1. Redistributions of source code must retain the above copyright notice, this list of conditions \r\n    and the following disclaimer.\r\n\r\n    2. The origin of this software must not be misrepresented; you must not claim that you wrote \r\n    the original software. If you use this software in a product, an acknowledgment in the product \r\n    documentation would be appreciated but is not required.\r\n\r\n    3. Altered source versions must be plainly marked as such, and must not be misrepresented as \r\n    being the original software.\r\n\r\n    4. The name of the author may not be used to endorse or promote products derived from this software \r\n    without specific prior written permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\r\n\r\nJulian Seward, Cambridge, UK.\r\n\r\njseward@acm.org",
            "name": "The bzip2 license",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        }
                    ],
                    "conditions": {
                        "AND": [
                            {
                                "name": "Correctly indicate the origin of the software in question",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "If used in a product, it would be nice to include an acknowledgement in the product documentation, but it is not required."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "conditions": {
                        "name": "Correctly indicate the origin of the software in question",
                        "type": "OBLIGATION"
                    },
                    "description": "If used in a product, it would be nice to include an acknowledgement in the product documentation, but it is not required."
                },
                {
                    "actions": [
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Correctly indicate the origin of the software in question",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Indicate that you have made the change yourself.",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "If used in a product, it would be nice to include an acknowledgement in the product documentation, but it is not required."
                },
                {
                    "actions": [
                        {
                            "name": "Use the author's name to endorse or promote the derived product"
                        }
                    ],
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    }
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "The bzip2 license"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        []
                    ]
                ],
                "__impliedText": "This program, \"bzip2\" and associated library \"libbzip2\", are copyright (C) 1996-2000 Julian R Seward. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: \r\n\r\n    1. Redistributions of source code must retain the above copyright notice, this list of conditions \r\n    and the following disclaimer.\r\n\r\n    2. The origin of this software must not be misrepresented; you must not claim that you wrote \r\n    the original software. If you use this software in a product, an acknowledgment in the product \r\n    documentation would be appreciated but is not required.\r\n\r\n    3. Altered source versions must be plainly marked as such, and must not be misrepresented as \r\n    being the original software.\r\n\r\n    4. The name of the author may not be used to endorse or promote products derived from this software \r\n    without specific prior written permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\r\n\r\nJulian Seward, Cambridge, UK.\r\n\r\njseward@acm.org",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/381"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/bzip2-1.0.6.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "bzip2 and libbzip2 License v1.0.6",
            "id": "bzip2-1.0.6",
            "_implications": {
                "__impliedNames": [
                    "bzip2-1.0.6",
                    "bzip2 and libbzip2 License v1.0.6"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/bzip2-1.0.6.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n\n1. Redistributions of source code must retain the above copyright\n   notice, this list of conditions and the following disclaimer.\n\n2. The origin of this software must not be misrepresented; you must\n   not claim that you wrote the original software.  If you use this\n   software in a product, an acknowledgment in the product\n   documentation would be appreciated but is not required.\n\n3. Altered source versions must be plainly marked as such, and must\n   not be misrepresented as being the original software.\n\n4. The name of the author may not be used to endorse or promote\n   products derived from this software without specific prior written\n   permission.\n\nTHIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS\nOR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\nWARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\nARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY\nDIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\nDAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE\nGOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\nWHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\nNEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\nSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/bzip2-1.0.6.json"
        ],
        [
            null,
            "https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.6"
        ],
        [
            null,
            "http://bzip.org/1.0.5/bzip2-manual-1.0.5.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/bzip2-1.0.6.html"
        ],
        [
            "Homepage",
            "https://github.com/asimonov-im/bzip2/blob/master/LICENSE"
        ],
        [
            null,
            "http://www.bzip.org/"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/381"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/bzip2-1.0.6.svg