== Computational Use of Data Agreement v1.0 (C-UDA-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Computational Use of Data Agreement v1.0
|Shortname |C-UDA-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Computational Use of Data Agreement 1.0`
* `scancode://c-uda-1.0`

=== Comments on (easy) usability

=== General Comments

* ``category: Computational Use of Data Agreement'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[co]/Computational-Use-of-Data-Agreement-1.0.yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/C-UDA-1.0.json
* https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md
* https://cdla.dev/computational-use-of-data-agreement-v1-0/

=== Text

....
Computational Use of Data Agreement v1.0

This is the Computational Use of Data Agreement, Version 1.0 (the “C-UDA”). Capitalized terms are defined in Section 5. Data Provider and you agree as follows:

1. Provision of the Data

1.1. You may use, modify, and distribute the Data made available to you by the Data Provider under this C-UDA for Computational Use if you follow the C-UDA's terms.

1.2. Data Provider will not sue you or any Downstream Recipient for any claim arising out of the use, modification, or distribution of the Data provided you meet the terms of the C-UDA.

1.3 This C-UDA does not restrict your use, modification, or distribution of any portions of the Data that are in the public domain or that may be used, modified, or distributed under any other legal exception or limitation.

2. Restrictions

2.1 You agree that you will use the Data solely for Computational Use.

2.2 The C-UDA does not impose any restriction with respect to the use, modification, or distribution of Results.

3. Redistribution of Data

3.1. You may redistribute the Data, so long as:

3.1.1. You include with any Data you redistribute all credit or attribution information that you received with the Data, and your terms require any Downstream Recipient to do the same; and

3.1.2. You bind each recipient to whom you redistribute the Data to the terms of the C-UDA.

4. No Warranty, Limitation of Liability

4.1. Data Provider does not represent or warrant that it has any rights whatsoever in the Data.

4.2. THE DATA IS PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

4.3. NEITHER DATA PROVIDER NOR ANY UPSTREAM DATA PROVIDER SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE DATA OR RESULTS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

5. Definitions

5.1. “Computational Use” means activities necessary to enable the use of Data (alone or along with other material) for analysis by a computer.

5.2.“Data” means the material you receive under the C-UDA in modified or unmodified form, but not including Results.

5.3. “Data Provider” means the source from which you receive the Data and with whom you enter into the C-UDA.

5.4. “Downstream Recipient” means any person or persons who receives the Data directly or indirectly from you in accordance with the C-UDA.

5.5. “Result” means anything that you develop or improve from your use of Data that does not include more than a de minimis portion of the Data on which the use is based. Results may include de minimis portions of the Data necessary to report on or explain use that has been conducted with the Data, such as figures in scientific papers, but do not include more. Artificial intelligence models trained on Data (and which do not include more than a de minimis portion of Data) are Results.

5.6. “Upstream Data Providers” means the source or sources from which the Data Provider directly or indirectly received, under the terms of the C-UDA, material that is included in the Data.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[co]/Computational-Use-of-Data-Agreement-1.0.yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/C-UDA-1.0.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/c-uda-1.0.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "C-UDA-1.0",
        "Computational Use of Data Agreement 1.0",
        "Computational Use of Data Agreement v1.0",
        "scancode://c-uda-1.0"
    ],
    "__impliedId": "C-UDA-1.0",
    "__impliedAmbiguousNames": [
        "Computational Use of Data Agreement v1.0",
        "scancode:c-uda-1.0"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: Computational Use of Data Agreement"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "C-UDA-1.0"
                ],
                "__impliedId": "C-UDA-1.0"
            },
            "shortname": "C-UDA-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Computational Use of Data Agreement v1.0",
            "spdxDetailsURL": "https://spdx.org/licenses/C-UDA-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/C-UDA-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md",
                "https://cdla.dev/computational-use-of-data-agreement-v1-0/"
            ],
            "_implications": {
                "__impliedNames": [
                    "C-UDA-1.0",
                    "Computational Use of Data Agreement v1.0"
                ],
                "__impliedId": "C-UDA-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/C-UDA-1.0.json"
                    ],
                    [
                        null,
                        "https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md"
                    ],
                    [
                        null,
                        "https://cdla.dev/computational-use-of-data-agreement-v1-0/"
                    ]
                ]
            },
            "spdxLicenseId": "C-UDA-1.0"
        },
        "Scancode": {
            "otherUrls": [
                "https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md",
                "https://cdla.dev/computational-use-of-data-agreement-v1-0/"
            ],
            "homepageUrl": null,
            "shortName": "Computational Use of Data Agreement v1.0",
            "textUrls": null,
            "text": "Computational Use of Data Agreement v1.0\n\nThis is the Computational Use of Data Agreement, Version 1.0 (the âC-UDAâ). Capitalized terms are defined in Section 5. Data Provider and you agree as follows:\n\n1. Provision of the Data\n\n1.1. You may use, modify, and distribute the Data made available to you by the Data Provider under this C-UDA for Computational Use if you follow the C-UDA's terms.\n\n1.2. Data Provider will not sue you or any Downstream Recipient for any claim arising out of the use, modification, or distribution of the Data provided you meet the terms of the C-UDA.\n\n1.3 This C-UDA does not restrict your use, modification, or distribution of any portions of the Data that are in the public domain or that may be used, modified, or distributed under any other legal exception or limitation.\n\n2. Restrictions\n\n2.1 You agree that you will use the Data solely for Computational Use.\n\n2.2 The C-UDA does not impose any restriction with respect to the use, modification, or distribution of Results.\n\n3. Redistribution of Data\n\n3.1. You may redistribute the Data, so long as:\n\n3.1.1. You include with any Data you redistribute all credit or attribution information that you received with the Data, and your terms require any Downstream Recipient to do the same; and\n\n3.1.2. You bind each recipient to whom you redistribute the Data to the terms of the C-UDA.\n\n4. No Warranty, Limitation of Liability\n\n4.1. Data Provider does not represent or warrant that it has any rights whatsoever in the Data.\n\n4.2. THE DATA IS PROVIDED ON AN âAS ISâ BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.\n\n4.3. NEITHER DATA PROVIDER NOR ANY UPSTREAM DATA PROVIDER SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE DATA OR RESULTS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\n5. Definitions\n\n5.1. âComputational Useâ means activities necessary to enable the use of Data (alone or along with other material) for analysis by a computer.\n\n5.2.âDataâ means the material you receive under the C-UDA in modified or unmodified form, but not including Results.\n\n5.3. âData Providerâ means the source from which you receive the Data and with whom you enter into the C-UDA.\n\n5.4. âDownstream Recipientâ means any person or persons who receives the Data directly or indirectly from you in accordance with the C-UDA.\n\n5.5. âResultâ means anything that you develop or improve from your use of Data that does not include more than a de minimis portion of the Data on which the use is based. Results may include de minimis portions of the Data necessary to report on or explain use that has been conducted with the Data, such as figures in scientific papers, but do not include more. Artificial intelligence models trained on Data (and which do not include more than a de minimis portion of Data) are Results.\n\n5.6. âUpstream Data Providersâ means the source or sources from which the Data Provider directly or indirectly received, under the terms of the C-UDA, material that is included in the Data.",
            "category": "Free Restricted",
            "osiUrl": null,
            "owner": "Microsoft",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/c-uda-1.0.yml",
            "key": "c-uda-1.0",
            "name": "Computational Use of Data Agreement v1.0",
            "spdxId": "C-UDA-1.0",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://c-uda-1.0",
                    "Computational Use of Data Agreement v1.0",
                    "C-UDA-1.0"
                ],
                "__impliedId": "C-UDA-1.0",
                "__impliedText": "Computational Use of Data Agreement v1.0\n\nThis is the Computational Use of Data Agreement, Version 1.0 (the “C-UDA”). Capitalized terms are defined in Section 5. Data Provider and you agree as follows:\n\n1. Provision of the Data\n\n1.1. You may use, modify, and distribute the Data made available to you by the Data Provider under this C-UDA for Computational Use if you follow the C-UDA's terms.\n\n1.2. Data Provider will not sue you or any Downstream Recipient for any claim arising out of the use, modification, or distribution of the Data provided you meet the terms of the C-UDA.\n\n1.3 This C-UDA does not restrict your use, modification, or distribution of any portions of the Data that are in the public domain or that may be used, modified, or distributed under any other legal exception or limitation.\n\n2. Restrictions\n\n2.1 You agree that you will use the Data solely for Computational Use.\n\n2.2 The C-UDA does not impose any restriction with respect to the use, modification, or distribution of Results.\n\n3. Redistribution of Data\n\n3.1. You may redistribute the Data, so long as:\n\n3.1.1. You include with any Data you redistribute all credit or attribution information that you received with the Data, and your terms require any Downstream Recipient to do the same; and\n\n3.1.2. You bind each recipient to whom you redistribute the Data to the terms of the C-UDA.\n\n4. No Warranty, Limitation of Liability\n\n4.1. Data Provider does not represent or warrant that it has any rights whatsoever in the Data.\n\n4.2. THE DATA IS PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.\n\n4.3. NEITHER DATA PROVIDER NOR ANY UPSTREAM DATA PROVIDER SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE DATA OR RESULTS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\n5. Definitions\n\n5.1. “Computational Use” means activities necessary to enable the use of Data (alone or along with other material) for analysis by a computer.\n\n5.2.“Data” means the material you receive under the C-UDA in modified or unmodified form, but not including Results.\n\n5.3. “Data Provider” means the source from which you receive the Data and with whom you enter into the C-UDA.\n\n5.4. “Downstream Recipient” means any person or persons who receives the Data directly or indirectly from you in accordance with the C-UDA.\n\n5.5. “Result” means anything that you develop or improve from your use of Data that does not include more than a de minimis portion of the Data on which the use is based. Results may include de minimis portions of the Data necessary to report on or explain use that has been conducted with the Data, such as figures in scientific papers, but do not include more. Artificial intelligence models trained on Data (and which do not include more than a de minimis portion of Data) are Results.\n\n5.6. “Upstream Data Providers” means the source or sources from which the Data Provider directly or indirectly received, under the terms of the C-UDA, material that is included in the Data.",
                "__impliedURLs": [
                    [
                        null,
                        "https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md"
                    ],
                    [
                        null,
                        "https://cdla.dev/computational-use-of-data-agreement-v1-0/"
                    ]
                ]
            }
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "C-UDA-1.0",
            "shortName": null,
            "category": "Computational Use of Data Agreement",
            "alternativeNames": [
                "Computational Use of Data Agreement v1.0"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[co]/Computational-Use-of-Data-Agreement-1.0.yaml",
            "otherIds": [
                "scancode:c-uda-1.0"
            ],
            "canonicalName": "Computational Use of Data Agreement 1.0",
            "_implications": {
                "__impliedNames": [
                    "Computational Use of Data Agreement 1.0",
                    "C-UDA-1.0"
                ],
                "__impliedId": "C-UDA-1.0",
                "__impliedAmbiguousNames": [
                    "Computational Use of Data Agreement v1.0",
                    "scancode:c-uda-1.0"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: Computational Use of Data Agreement"
                        ]
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedText": "Computational Use of Data Agreement v1.0\n\nThis is the Computational Use of Data Agreement, Version 1.0 (the “C-UDA”). Capitalized terms are defined in Section 5. Data Provider and you agree as follows:\n\n1. Provision of the Data\n\n1.1. You may use, modify, and distribute the Data made available to you by the Data Provider under this C-UDA for Computational Use if you follow the C-UDA's terms.\n\n1.2. Data Provider will not sue you or any Downstream Recipient for any claim arising out of the use, modification, or distribution of the Data provided you meet the terms of the C-UDA.\n\n1.3 This C-UDA does not restrict your use, modification, or distribution of any portions of the Data that are in the public domain or that may be used, modified, or distributed under any other legal exception or limitation.\n\n2. Restrictions\n\n2.1 You agree that you will use the Data solely for Computational Use.\n\n2.2 The C-UDA does not impose any restriction with respect to the use, modification, or distribution of Results.\n\n3. Redistribution of Data\n\n3.1. You may redistribute the Data, so long as:\n\n3.1.1. You include with any Data you redistribute all credit or attribution information that you received with the Data, and your terms require any Downstream Recipient to do the same; and\n\n3.1.2. You bind each recipient to whom you redistribute the Data to the terms of the C-UDA.\n\n4. No Warranty, Limitation of Liability\n\n4.1. Data Provider does not represent or warrant that it has any rights whatsoever in the Data.\n\n4.2. THE DATA IS PROVIDED ON AN “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.\n\n4.3. NEITHER DATA PROVIDER NOR ANY UPSTREAM DATA PROVIDER SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE DATA OR RESULTS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\n5. Definitions\n\n5.1. “Computational Use” means activities necessary to enable the use of Data (alone or along with other material) for analysis by a computer.\n\n5.2.“Data” means the material you receive under the C-UDA in modified or unmodified form, but not including Results.\n\n5.3. “Data Provider” means the source from which you receive the Data and with whom you enter into the C-UDA.\n\n5.4. “Downstream Recipient” means any person or persons who receives the Data directly or indirectly from you in accordance with the C-UDA.\n\n5.5. “Result” means anything that you develop or improve from your use of Data that does not include more than a de minimis portion of the Data on which the use is based. Results may include de minimis portions of the Data necessary to report on or explain use that has been conducted with the Data, such as figures in scientific papers, but do not include more. Artificial intelligence models trained on Data (and which do not include more than a de minimis portion of Data) are Results.\n\n5.6. “Upstream Data Providers” means the source or sources from which the Data Provider directly or indirectly received, under the terms of the C-UDA, material that is included in the Data.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/C-UDA-1.0.json"
        ],
        [
            null,
            "https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md"
        ],
        [
            null,
            "https://cdla.dev/computational-use-of-data-agreement-v1-0/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/C-UDA-1.0.svg
