== Cryptographic Autonomy License 1.0 (CAL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Cryptographic Autonomy License 1.0
|Shortname |CAL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/CAL-1.0.html[SPDX])

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/CAL-1.0.json
* http://cryptographicautonomylicense.com/license-text.html
* https://opensource.org/licenses/CAL-1.0

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "CAL-1.0",
        "Cryptographic Autonomy License 1.0"
    ],
    "__impliedId": "CAL-1.0",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Cryptographic Autonomy License 1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/CAL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/CAL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://cryptographicautonomylicense.com/license-text.html",
                "https://opensource.org/licenses/CAL-1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "CAL-1.0",
                    "Cryptographic Autonomy License 1.0"
                ],
                "__impliedId": "CAL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CAL-1.0.json"
                    ],
                    [
                        null,
                        "http://cryptographicautonomylicense.com/license-text.html"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/CAL-1.0"
                    ]
                ]
            },
            "spdxLicenseId": "CAL-1.0"
        }
    },
    "__impliedJudgement": [
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/CAL-1.0.json"
        ],
        [
            null,
            "http://cryptographicautonomylicense.com/license-text.html"
        ],
        [
            null,
            "https://opensource.org/licenses/CAL-1.0"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/CAL-1.0.svg[image,title="dot"]