== Creative Commons Attribution Non Commercial 4.0 International (CC-BY-NC-4.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Attribution Non Commercial 4.0 International
|Shortname |CC-BY-NC-4.0
|Rating |No-Go
|Is Non-Commercial |True
|===

*Other Names:*

* `Creative Commons Attribution-NonCommercial 4.0`

=== Comments on (easy) usability

* **↓**``Google Classification is CANNOT_BE_USED "Everything that Google
undertakes, including research, is considered a commercial endeavor, so
no code released under a license that restricts it to non-commercial
uses may be used at Google. For example, works under any Creative
Commons licenses containing NC (CC BY-NC, CC BY-NC-SA, CC BY-NC-ND) may
not be used at Google."'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↓**``This license is not compatible with the
DebianFreeSoftwareGuidelines (DFSG-unfree)'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/CC-BY-NC-4.0.json
* https://creativecommons.org/licenses/by-nc/4.0/
* https://creativecommons.org/licenses/by-nc/4.0/legalcode

'''''

=== Raw Data

==== Facts

* LicenseName
* Override
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/CC-BY-NC-4.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-BY-NC-4.0",
        "Creative Commons Attribution-NonCommercial 4.0",
        "Creative Commons Attribution Non Commercial 4.0 International"
    ],
    "__impliedId": "CC-BY-NC-4.0",
    "__impliedAmbiguousNames": [
        "Creative Commons Attribution-Non Commercial-Share Alike (CC-by-nc-sa)"
    ],
    "__impliedRatingState": [
        [
            "Override",
            {
                "tag": "FinalRating",
                "contents": {
                    "tag": "RNoGo"
                }
            }
        ]
    ],
    "__impliedNonCommercial": true,
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": false,
            "url": "https://creativecommons.org/licenses/by-nc/4.0/",
            "maintainer": "Creative Commons",
            "od_conformance": "rejected",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": true,
            "osd_conformance": "not reviewed",
            "id": "CC-BY-NC-4.0",
            "title": "Creative Commons Attribution-NonCommercial 4.0",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0",
                    "Creative Commons Attribution-NonCommercial 4.0"
                ],
                "__impliedId": "CC-BY-NC-4.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://creativecommons.org/licenses/by-nc/4.0/"
                    ]
                ]
            },
            "domain_content": true
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0"
                ],
                "__impliedId": "CC-BY-NC-4.0"
            },
            "shortname": "CC-BY-NC-4.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Attribution Non Commercial 4.0 International",
            "spdxDetailsURL": "http://spdx.org/licenses/CC-BY-NC-4.0.json",
            "_sourceURL": "https://spdx.org/licenses/CC-BY-NC-4.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/by-nc/4.0/legalcode"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0",
                    "Creative Commons Attribution Non Commercial 4.0 International"
                ],
                "__impliedId": "CC-BY-NC-4.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CC-BY-NC-4.0.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/by-nc/4.0/legalcode"
                    ]
                ]
            },
            "spdxLicenseId": "CC-BY-NC-4.0"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Creative Commons Non-commercial 4.0 International",
            "commercialUse": false,
            "spdxId": "CC-BY-NC-4.0",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Creative Commons Attribution-Non Commercial-Share Alike (CC-by-nc-sa)",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0"
                ],
                "__impliedAmbiguousNames": [
                    "Creative Commons Attribution-Non Commercial-Share Alike (CC-by-nc-sa)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "CC-BY-NC-4.0"
        },
        "Override": {
            "oNonCommecrial": true,
            "implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0"
                ],
                "__impliedId": "CC-BY-NC-4.0",
                "__impliedRatingState": [
                    [
                        "Override",
                        {
                            "tag": "FinalRating",
                            "contents": {
                                "tag": "RNoGo"
                            }
                        }
                    ]
                ],
                "__impliedNonCommercial": true
            },
            "oName": "CC-BY-NC-4.0",
            "oOtherLicenseIds": [],
            "oDescription": null,
            "oJudgement": null,
            "oCompatibilities": null,
            "oRatingState": {
                "tag": "FinalRating",
                "contents": {
                    "tag": "RNoGo"
                }
            }
        },
        "Google OSS Policy": {
            "rating": "CANNOT_BE_USED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "CC-BY-NC-4.0",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-NC-4.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is CANNOT_BE_USED \"Everything that Google undertakes, including research, is considered a commercial endeavor, so no code released under a license that restricts it to non-commercial uses may be used at Google. For example, works under any Creative Commons licenses containing NC (CC BY-NC, CC BY-NC-SA, CC BY-NC-ND) may not be used at Google.\""
                        }
                    ]
                ]
            },
            "description": "Everything that Google undertakes, including research, is considered a commercial endeavor, so no code released under a license that restricts it to non-commercial uses may be used at Google. For example, works under any Creative Commons licenses containing NC (CC BY-NC, CC BY-NC-SA, CC BY-NC-ND) may not be used at Google."
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is CANNOT_BE_USED \"Everything that Google undertakes, including research, is considered a commercial endeavor, so no code released under a license that restricts it to non-commercial uses may be used at Google. For example, works under any Creative Commons licenses containing NC (CC BY-NC, CC BY-NC-SA, CC BY-NC-ND) may not be used at Google.\""
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://creativecommons.org/licenses/by-nc/4.0/"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/CC-BY-NC-4.0.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/by-nc/4.0/legalcode"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-BY-NC-4.0.svg
