== Creative Commons Attribution 1.0 Generic (CC-BY-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Attribution 1.0 Generic
|Shortname |CC-BY-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↓**``It is believed that 2.0 still has problems
(http://evan.prodromou.name/ccsummary/ccsummary.html), but it is under
discussion between debian-legal and cc-licenses.'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/CC-BY-1.0.json
* https://creativecommons.org/licenses/by/1.0/legalcode

'''''

=== Raw Data

==== Facts

* LicenseName
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/CC-BY-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-BY-1.0",
        "Creative Commons Attribution 1.0 Generic"
    ],
    "__impliedId": "CC-BY-1.0",
    "__impliedAmbiguousNames": [
        "Creative Commons Attribution License (CC-by), v1.0"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-BY-1.0"
                ],
                "__impliedId": "CC-BY-1.0"
            },
            "shortname": "CC-BY-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Attribution 1.0 Generic",
            "spdxDetailsURL": "http://spdx.org/licenses/CC-BY-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/CC-BY-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/by/1.0/legalcode"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-BY-1.0",
                    "Creative Commons Attribution 1.0 Generic"
                ],
                "__impliedId": "CC-BY-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CC-BY-1.0.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/by/1.0/legalcode"
                    ]
                ]
            },
            "spdxLicenseId": "CC-BY-1.0"
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Creative Commons Attribution License (CC-by), v1.0",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Creative Commons Attribution License (CC-by), v1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "It is believed that 2.0 still has problems (http://evan.prodromou.name/ccsummary/ccsummary.html), but it is under discussion between debian-legal and cc-licenses."
                        }
                    ]
                ]
            },
            "Comment": "It is believed that 2.0 still has problems (http://evan.prodromou.name/ccsummary/ccsummary.html), but it is under discussion between debian-legal and cc-licenses.",
            "LicenseId": "CC-BY-1.0"
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "CC-BY-1.0",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "It is believed that 2.0 still has problems (http://evan.prodromou.name/ccsummary/ccsummary.html), but it is under discussion between debian-legal and cc-licenses."
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Google OSS Policy",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/CC-BY-1.0.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/by/1.0/legalcode"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-BY-1.0.svg
