== Creative Commons Attribution 3.0 Austria (CC-BY-3.0-AT)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Attribution 3.0 Austria
|Shortname |CC-BY-3.0-AT
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Creative Commons BY 3.0 (Austria)`
* `scancode:cc-by-3.0-at`

=== Comments on (easy) usability

=== General Comments

* ``category: CC-BY'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-3.0-(Austria).yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/CC-BY-3.0-AT.json
* https://creativecommons.org/licenses/by/3.0/at/legalcode

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-3.0-(Austria).yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/CC-BY-3.0-AT.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-BY-3.0-AT",
        "Creative Commons BY 3.0 (Austria)",
        "scancode:cc-by-3.0-at",
        "Creative Commons Attribution 3.0 Austria"
    ],
    "__impliedId": "CC-BY-3.0-AT",
    "__impliedAmbiguousNames": [
        "Creative Commons BY 3.0 (Austria)"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: CC-BY"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-BY-3.0-AT"
                ],
                "__impliedId": "CC-BY-3.0-AT"
            },
            "shortname": "CC-BY-3.0-AT",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Attribution 3.0 Austria",
            "spdxDetailsURL": "https://spdx.org/licenses/CC-BY-3.0-AT.json",
            "_sourceURL": "https://spdx.org/licenses/CC-BY-3.0-AT.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/by/3.0/at/legalcode"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-BY-3.0-AT",
                    "Creative Commons Attribution 3.0 Austria"
                ],
                "__impliedId": "CC-BY-3.0-AT",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/CC-BY-3.0-AT.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/by/3.0/at/legalcode"
                    ]
                ]
            },
            "spdxLicenseId": "CC-BY-3.0-AT"
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "CC-BY-3.0-AT",
            "shortName": null,
            "category": "CC-BY",
            "alternativeNames": [
                "Creative Commons BY 3.0 (Austria)"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-3.0-(Austria).yaml",
            "otherIds": [
                "scancode:cc-by-3.0-at"
            ],
            "canonicalName": "Creative Commons BY 3.0 (Austria)",
            "_implications": {
                "__impliedNames": [
                    "Creative Commons BY 3.0 (Austria)",
                    "CC-BY-3.0-AT",
                    "scancode:cc-by-3.0-at"
                ],
                "__impliedId": "CC-BY-3.0-AT",
                "__impliedAmbiguousNames": [
                    "Creative Commons BY 3.0 (Austria)"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: CC-BY"
                        ]
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/CC-BY-3.0-AT.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/by/3.0/at/legalcode"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-BY-3.0-AT.svg
