== Creative Commons Attribution No Derivatives 4.0 International (CC-BY-ND-4.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Attribution No Derivatives 4.0 International
|Shortname |CC-BY-ND-4.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↓**``Google Classification is RESTRICTED'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/CC-BY-ND-4.0.json
* https://creativecommons.org/licenses/by-nd/4.0/legalcode

'''''

=== Raw Data

==== Facts

* LicenseName
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/CC-BY-ND-4.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-BY-ND-4.0",
        "Creative Commons Attribution No Derivatives 4.0 International"
    ],
    "__impliedId": "CC-BY-ND-4.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-BY-ND-4.0"
                ],
                "__impliedId": "CC-BY-ND-4.0"
            },
            "shortname": "CC-BY-ND-4.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Attribution No Derivatives 4.0 International",
            "spdxDetailsURL": "http://spdx.org/licenses/CC-BY-ND-4.0.json",
            "_sourceURL": "https://spdx.org/licenses/CC-BY-ND-4.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/by-nd/4.0/legalcode"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-BY-ND-4.0",
                    "Creative Commons Attribution No Derivatives 4.0 International"
                ],
                "__impliedId": "CC-BY-ND-4.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CC-BY-ND-4.0.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/by-nd/4.0/legalcode"
                    ]
                ]
            },
            "spdxLicenseId": "CC-BY-ND-4.0"
        },
        "Google OSS Policy": {
            "rating": "RESTRICTED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "CC-BY-ND-4.0",
            "_implications": {
                "__impliedNames": [
                    "CC-BY-ND-4.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is RESTRICTED"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is RESTRICTED"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/CC-BY-ND-4.0.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/by-nd/4.0/legalcode"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-BY-ND-4.0.svg
