== Creative Commons Attribution Share Alike 2.1 Japan (CC-BY-SA-2.1-JP)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Attribution Share Alike 2.1 Japan
|Shortname |CC-BY-SA-2.1-JP
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Creative Commons BY-SA 2.1 (JP)`

=== Comments on (easy) usability

=== General Comments

* ``category: CC-BY-SA'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-SA-2.1-(JP).yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/CC-BY-SA-2.1-JP.json
* https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-SA-2.1-(JP).yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/CC-BY-SA-2.1-JP.html[SPDX] (all data [in
this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-BY-SA-2.1-JP",
        "Creative Commons BY-SA 2.1 (JP)",
        "Creative Commons Attribution Share Alike 2.1 Japan"
    ],
    "__impliedId": "CC-BY-SA-2.1-JP",
    "__impliedAmbiguousNames": [
        "CC-BY-SA-2.1-JP"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: CC-BY-SA"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-BY-SA-2.1-JP"
                ],
                "__impliedId": "CC-BY-SA-2.1-JP"
            },
            "shortname": "CC-BY-SA-2.1-JP",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Attribution Share Alike 2.1 Japan",
            "spdxDetailsURL": "https://spdx.org/licenses/CC-BY-SA-2.1-JP.json",
            "_sourceURL": "https://spdx.org/licenses/CC-BY-SA-2.1-JP.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-BY-SA-2.1-JP",
                    "Creative Commons Attribution Share Alike 2.1 Japan"
                ],
                "__impliedId": "CC-BY-SA-2.1-JP",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/CC-BY-SA-2.1-JP.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode"
                    ]
                ]
            },
            "spdxLicenseId": "CC-BY-SA-2.1-JP"
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "CC-BY-SA-2.1-JP",
            "shortName": null,
            "category": "CC-BY-SA",
            "alternativeNames": [
                "CC-BY-SA-2.1-JP"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/[cr]/Creative-Commons-BY-SA-2.1-(JP).yaml",
            "otherIds": [],
            "canonicalName": "Creative Commons BY-SA 2.1 (JP)",
            "_implications": {
                "__impliedNames": [
                    "Creative Commons BY-SA 2.1 (JP)",
                    "CC-BY-SA-2.1-JP"
                ],
                "__impliedId": "CC-BY-SA-2.1-JP",
                "__impliedAmbiguousNames": [
                    "CC-BY-SA-2.1-JP"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: CC-BY-SA"
                        ]
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/CC-BY-SA-2.1-JP.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-BY-SA-2.1-JP.svg
