== Creative Commons Public Domain Dedication and Certification (CC-PDDC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Creative Commons Public Domain Dedication and Certification
|Shortname |CC-PDDC
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://cc-pd+`
* `+CC-PD+`
* `+Creative Commons Copyright-Only Dedication (based on United States law) or Public Domain Certification+`

=== Comments on (easy) usability

=== General Comments

* ``http://creativecommons.org/licenses/publicdomain/'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:* https://creativecommons.org/licenses/publicdomain/
* *SPDX:* http://spdx.org/licenses/CC-PDDC.json
* *open-license:* http://open-license.hitachi.com/licenses/276

=== Description from open-license

* {blank}
+
....
Description: The work shall be in the public domain.
Actions:
- Transmit the work.
- Use of copyrighted material
- Modify the work.
- Distribute the work
- Making use of copyrighted material

Conditions: None
....

(source: Hitachi open-license)

=== Text

....
The person or persons who have associated work with this document (the "Dedicator" or "Certifier") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the "Work") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a "dedicator" below.

A certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.

Dedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.

Dedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/CC-PDDC.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pd.yml[Scancode]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "CC-PDDC",
        "Creative Commons Public Domain Dedication and Certification",
        "scancode://cc-pd",
        "CC-PD",
        "Creative Commons Copyright-Only Dedication (based on United States law) or Public Domain Certification"
    ],
    "__impliedId": "CC-PDDC",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "http://creativecommons.org/licenses/publicdomain/"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CC-PDDC"
                ],
                "__impliedId": "CC-PDDC"
            },
            "shortname": "CC-PDDC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Creative Commons Public Domain Dedication and Certification",
            "spdxDetailsURL": "http://spdx.org/licenses/CC-PDDC.json",
            "_sourceURL": "https://spdx.org/licenses/CC-PDDC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://creativecommons.org/licenses/publicdomain/"
            ],
            "_implications": {
                "__impliedNames": [
                    "CC-PDDC",
                    "Creative Commons Public Domain Dedication and Certification"
                ],
                "__impliedId": "CC-PDDC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CC-PDDC.json"
                    ],
                    [
                        null,
                        "https://creativecommons.org/licenses/publicdomain/"
                    ]
                ]
            },
            "spdxLicenseId": "CC-PDDC"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://creativecommons.org/licenses/publicdomain/",
            "shortName": "CC-PD",
            "textUrls": null,
            "text": "The person or persons who have associated work with this document (the \"Dedicator\" or \"Certifier\") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the \"Work\") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a \"dedicator\" below.\n\nA certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.\n\nDedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.\n\nDedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.",
            "category": "Public Domain",
            "osiUrl": null,
            "owner": "Creative Commons",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pd.yml",
            "key": "cc-pd",
            "name": "Creative Commons Public Domain Certification",
            "spdxId": "CC-PDDC",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://cc-pd",
                    "CC-PD",
                    "CC-PDDC"
                ],
                "__impliedId": "CC-PDDC",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The person or persons who have associated work with this document (the \"Dedicator\" or \"Certifier\") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the \"Work\") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a \"dedicator\" below.\n\nA certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.\n\nDedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.\n\nDedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://creativecommons.org/licenses/publicdomain/"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "http://creativecommons.org/licenses/publicdomain/",
            "notices": [
                {
                    "content": "When certifying a work as belonging to the public domain, take reasonable steps to verify the copyright status of the work to see if it can be treated as belonging to the public domain.",
                    "description": "Check the copyright status when handling copyrighted material."
                },
                {
                    "content": "If you own your work as belonging to the public domain, you permanently relinquish all present and future rights under copyright law to that work."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/276",
            "content": "The person or persons who have associated work with this document (the \"Dedicator\" or \"Certifier\") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the \"Work\") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a \"dedicator\" below.\n\nA certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.\n\nDedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.\n\nDedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.",
            "name": "Creative Commons Copyright-Only Dedication (based on United States law) or Public Domain Certification",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Transmit the work."
                        },
                        {
                            "name": "Use of copyrighted material"
                        },
                        {
                            "name": "Modify the work."
                        },
                        {
                            "name": "Distribute the work"
                        },
                        {
                            "name": "Making use of copyrighted material"
                        }
                    ],
                    "_str": "Description: The work shall be in the public domain.\nActions:\n- Transmit the work.\n- Use of copyrighted material\n- Modify the work.\n- Distribute the work\n- Making use of copyrighted material\n\nConditions: None\n",
                    "conditions": null,
                    "description": "The work shall be in the public domain."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Creative Commons Copyright-Only Dedication (based on United States law) or Public Domain Certification",
                    "CC-PDDC"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "http://creativecommons.org/licenses/publicdomain/"
                        ]
                    ]
                ],
                "__impliedText": "The person or persons who have associated work with this document (the \"Dedicator\" or \"Certifier\") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the \"Work\") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a \"dedicator\" below.\n\nA certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.\n\nDedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.\n\nDedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/276"
                    ]
                ]
            }
        }
    },
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "The person or persons who have associated work with this document (the \"Dedicator\" or \"Certifier\") hereby either (a) certifies that, to the best of his knowledge, the work of authorship identified is in the public domain of the country from which the work is published, or (b) hereby dedicates whatever copyright the dedicators holds in the work of authorship identified below (the \"Work\") to the public domain. A certifier, moreover, dedicates any copyright interest he may have in the associated work, and for these purposes, is described as a \"dedicator\" below.\n\nA certifier has taken reasonable steps to verify the copyright status of this work. Certifier recognizes that his good faith efforts may not shield him from liability if in fact the work certified is not in the public domain.\n\nDedicator makes this dedication for the benefit of the public at large and to the detriment of the Dedicator's heirs and successors. Dedicator intends this dedication to be an overt act of relinquishment in perpetuity of all present and future rights under copyright law, whether vested or contingent, in the Work. Dedicator understands that such relinquishment of all rights includes the relinquishment of all rights to enforce (by lawsuit or otherwise) those copyrights in the Work.\n\nDedicator recognizes that, once placed in the public domain, the Work may be freely reproduced, distributed, transmitted, used, modified, built upon, or otherwise exploited by anyone for any purpose, commercial or non-commercial, and in any way, including by methods that have not yet been invented or conceived.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/CC-PDDC.json"
        ],
        [
            null,
            "https://creativecommons.org/licenses/publicdomain/"
        ],
        [
            "Homepage",
            "https://creativecommons.org/licenses/publicdomain/"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/276"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CC-PDDC.svg