== CeCILL Free Software License Agreement v1.1 (CECILL-1.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |CeCILL Free Software License Agreement v1.1
|Shortname |CECILL-1.1
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/CECILL-1.1.json
* http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/CECILL-1.1.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CECILL-1.1",
        "CeCILL Free Software License Agreement v1.1"
    ],
    "__impliedId": "CECILL-1.1",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CECILL-1.1"
                ],
                "__impliedId": "CECILL-1.1"
            },
            "shortname": "CECILL-1.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "CeCILL Free Software License Agreement v1.1",
            "spdxDetailsURL": "http://spdx.org/licenses/CECILL-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/CECILL-1.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "CECILL-1.1",
                    "CeCILL Free Software License Agreement v1.1"
                ],
                "__impliedId": "CECILL-1.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CECILL-1.1.json"
                    ],
                    [
                        null,
                        "http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html"
                    ]
                ]
            },
            "spdxLicenseId": "CECILL-1.1"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "CECILL-1.1"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "CECILL-1.1",
            "copyleftkind": "NoCopyleft"
        }
    },
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/CECILL-1.1.json"
        ],
        [
            null,
            "http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CECILL-1.1.svg
