== CNRI Python Open Source GPL Compatible License Agreement (CNRI-Python-GPL-Compatible)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |CNRI Python Open Source GPL Compatible License Agreement
|Shortname |CNRI-Python-GPL-Compatible
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html
* *SPDX:* http://spdx.org/licenses/CNRI-Python-GPL-Compatible.json
* http://www.python.org/download/releases/1.6.1/download_win/

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html[SPDX] (all
data [in this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "CNRI-Python-GPL-Compatible",
        "CNRI Python Open Source GPL Compatible License Agreement"
    ],
    "__impliedId": "CNRI-Python-GPL-Compatible",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "CNRI-Python-GPL-Compatible"
                ],
                "__impliedId": "CNRI-Python-GPL-Compatible"
            },
            "shortname": "CNRI-Python-GPL-Compatible",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "CNRI Python Open Source GPL Compatible License Agreement",
            "spdxDetailsURL": "http://spdx.org/licenses/CNRI-Python-GPL-Compatible.json",
            "_sourceURL": "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.python.org/download/releases/1.6.1/download_win/"
            ],
            "_implications": {
                "__impliedNames": [
                    "CNRI-Python-GPL-Compatible",
                    "CNRI Python Open Source GPL Compatible License Agreement"
                ],
                "__impliedId": "CNRI-Python-GPL-Compatible",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/CNRI-Python-GPL-Compatible.json"
                    ],
                    [
                        null,
                        "http://www.python.org/download/releases/1.6.1/download_win/"
                    ]
                ]
            },
            "spdxLicenseId": "CNRI-Python-GPL-Compatible"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "CNRI-Python-GPL-Compatible"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "CNRI-Python-GPL-Compatible",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "CNRI Python Open Source GPL Compatible License Agreement",
            "id": "CNRI-Python-GPL-Compatible",
            "_implications": {
                "__impliedNames": [
                    "CNRI-Python-GPL-Compatible",
                    "CNRI Python Open Source GPL Compatible License Agreement"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/CNRI-Python-GPL-Compatible.json"
        ],
        [
            null,
            "http://www.python.org/download/releases/1.6.1/download_win/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/CNRI-Python-GPL-Compatible.svg
