== Copyfree Open Innovation License (COIL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Copyfree Open Innovation License
|Shortname |COIL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/COIL-1.0.json
* https://coil.apotheon.org/plaintext/01.0.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/COIL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "COIL-1.0",
        "Copyfree Open Innovation License"
    ],
    "__impliedId": "COIL-1.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "COIL-1.0"
                ],
                "__impliedId": "COIL-1.0"
            },
            "shortname": "COIL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Copyfree Open Innovation License",
            "spdxDetailsURL": "https://spdx.org/licenses/COIL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/COIL-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://coil.apotheon.org/plaintext/01.0.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "COIL-1.0",
                    "Copyfree Open Innovation License"
                ],
                "__impliedId": "COIL-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/COIL-1.0.json"
                    ],
                    [
                        null,
                        "https://coil.apotheon.org/plaintext/01.0.txt"
                    ]
                ]
            },
            "spdxLicenseId": "COIL-1.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/COIL-1.0.json"
        ],
        [
            null,
            "https://coil.apotheon.org/plaintext/01.0.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/COIL-1.0.svg
