== Condor Public License v1.1 (Condor-1.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Condor Public License v1.1
|Shortname |Condor-1.1
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/Condor-1.1.html
* *SPDX:* http://spdx.org/licenses/Condor-1.1.json
* http://research.cs.wisc.edu/condor/license.html#condor
* http://web.archive.org/web/20111123062036/http://research.cs.wisc.edu/condor/license.html#condor

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/Condor-1.1.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Condor-1.1",
        "Condor Public License v1.1"
    ],
    "__impliedId": "Condor-1.1",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Condor-1.1"
                ],
                "__impliedId": "Condor-1.1"
            },
            "shortname": "Condor-1.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Condor Public License v1.1",
            "spdxDetailsURL": "http://spdx.org/licenses/Condor-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/Condor-1.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://research.cs.wisc.edu/condor/license.html#condor",
                "http://web.archive.org/web/20111123062036/http://research.cs.wisc.edu/condor/license.html#condor"
            ],
            "_implications": {
                "__impliedNames": [
                    "Condor-1.1",
                    "Condor Public License v1.1"
                ],
                "__impliedId": "Condor-1.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Condor-1.1.json"
                    ],
                    [
                        null,
                        "http://research.cs.wisc.edu/condor/license.html#condor"
                    ],
                    [
                        null,
                        "http://web.archive.org/web/20111123062036/http://research.cs.wisc.edu/condor/license.html#condor"
                    ]
                ]
            },
            "spdxLicenseId": "Condor-1.1"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "Condor-1.1"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "Condor-1.1",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Condor-1.1.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Condor Public License v1.1",
            "id": "Condor-1.1",
            "_implications": {
                "__impliedNames": [
                    "Condor-1.1",
                    "Condor Public License v1.1"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Condor-1.1.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Condor-1.1.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Condor-1.1.json"
        ],
        [
            null,
            "http://research.cs.wisc.edu/condor/license.html#condor"
        ],
        [
            null,
            "http://web.archive.org/web/20111123062036/http://research.cs.wisc.edu/condor/license.html#condor"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Condor-1.1.svg
