== copyleft-next 0.3.0 (copyleft-next-0.3.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |copyleft-next 0.3.0
|Shortname |copyleft-next-0.3.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/copyleft-next-0.3.0.json
* https://github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.0

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/copyleft-next-0.3.0.html[SPDX] (all data [in
this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "copyleft-next-0.3.0",
        "copyleft-next 0.3.0"
    ],
    "__impliedId": "copyleft-next-0.3.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "copyleft-next-0.3.0"
                ],
                "__impliedId": "copyleft-next-0.3.0"
            },
            "shortname": "copyleft-next-0.3.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "copyleft-next 0.3.0",
            "spdxDetailsURL": "http://spdx.org/licenses/copyleft-next-0.3.0.json",
            "_sourceURL": "https://spdx.org/licenses/copyleft-next-0.3.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "copyleft-next-0.3.0",
                    "copyleft-next 0.3.0"
                ],
                "__impliedId": "copyleft-next-0.3.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/copyleft-next-0.3.0.json"
                    ],
                    [
                        null,
                        "https://github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.0"
                    ]
                ]
            },
            "spdxLicenseId": "copyleft-next-0.3.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/copyleft-next-0.3.0.json"
        ],
        [
            null,
            "https://github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.0"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/copyleft-next-0.3.0.svg
