== Crossword License (Crossword)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Crossword License
|Shortname |Crossword
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://crossword`

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Crossword
* *SPDX:* https://spdx.org/licenses/Crossword.html
* *SPDX:* http://spdx.org/licenses/Crossword.json

=== Text

....
Copyright (C) 1995-2009 Gerd Neugebauer
  
cwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY. No author or distributor  accepts responsibility to anyone for the
consequences of using it or for whether it serves any particular purpose  or
works at all, unless he says so in writing.

Everyone is granted permission to copy, modify and redistribute cwpuzzle.dtx,
provided this copyright notice is preserved and any modifications are indicated.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/Crossword.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/crossword.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Crossword",
        "Crossword License",
        "scancode://crossword"
    ],
    "__impliedId": "Crossword",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Crossword"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Crossword"
                ],
                "__impliedId": "Crossword"
            },
            "shortname": "Crossword",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Crossword License",
            "spdxDetailsURL": "http://spdx.org/licenses/Crossword.json",
            "_sourceURL": "https://spdx.org/licenses/Crossword.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Crossword"
            ],
            "_implications": {
                "__impliedNames": [
                    "Crossword",
                    "Crossword License"
                ],
                "__impliedId": "Crossword",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Crossword.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Crossword"
                    ]
                ]
            },
            "spdxLicenseId": "Crossword"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Crossword",
            "GPLv3 Compat?": "Yes",
            "Short Name": "Crossword",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Crossword License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Crossword License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Crossword"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Crossword",
            "shortName": "Crossword License",
            "textUrls": null,
            "text": "Copyright (C) 1995-2009 Gerd Neugebauer\n Â \ncwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY\nWARRANTY. No author or distributor  accepts responsibility to anyone for the\nconsequences of using it or for whether it serves any particular purpose  or\nworks at all, unless he says so in writing.\n\nEveryone is granted permission to copy, modify and redistribute cwpuzzle.dtx,\nprovided this copyright notice is preserved and any modifications are indicated.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Gerd Neugebauer",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/crossword.yml",
            "key": "crossword",
            "name": "Crossword License",
            "spdxId": "Crossword",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://crossword",
                    "Crossword License",
                    "Crossword"
                ],
                "__impliedId": "Crossword",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Copyright (C) 1995-2009 Gerd Neugebauer\n  \ncwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY\nWARRANTY. No author or distributor  accepts responsibility to anyone for the\nconsequences of using it or for whether it serves any particular purpose  or\nworks at all, unless he says so in writing.\n\nEveryone is granted permission to copy, modify and redistribute cwpuzzle.dtx,\nprovided this copyright notice is preserved and any modifications are indicated.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Crossword"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Crossword.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Crossword License",
            "id": "Crossword",
            "_implications": {
                "__impliedNames": [
                    "Crossword",
                    "Crossword License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Crossword.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Copyright (C) 1995-2009 Gerd Neugebauer\n  \ncwpuzzle.dtx is distributed in the hope that it will be useful, but WITHOUT ANY\nWARRANTY. No author or distributor  accepts responsibility to anyone for the\nconsequences of using it or for whether it serves any particular purpose  or\nworks at all, unless he says so in writing.\n\nEveryone is granted permission to copy, modify and redistribute cwpuzzle.dtx,\nprovided this copyright notice is preserved and any modifications are indicated.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Crossword.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Crossword.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Crossword"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Crossword"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Crossword.svg
