== DOC License (DOC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |DOC License
|Shortname |DOC
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/DOC.html
* *SPDX:* http://spdx.org/licenses/DOC.json
* http://www.cs.wustl.edu/~schmidt/ACE-copying.html
* https://www.dre.vanderbilt.edu/~schmidt/ACE-copying.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/DOC.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "DOC",
        "DOC License"
    ],
    "__impliedId": "DOC",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "DOC"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "DOC"
                ],
                "__impliedId": "DOC"
            },
            "shortname": "DOC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "DOC License",
            "spdxDetailsURL": "http://spdx.org/licenses/DOC.json",
            "_sourceURL": "https://spdx.org/licenses/DOC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.cs.wustl.edu/~schmidt/ACE-copying.html",
                "https://www.dre.vanderbilt.edu/~schmidt/ACE-copying.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "DOC",
                    "DOC License"
                ],
                "__impliedId": "DOC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/DOC.json"
                    ],
                    [
                        null,
                        "http://www.cs.wustl.edu/~schmidt/ACE-copying.html"
                    ],
                    [
                        null,
                        "https://www.dre.vanderbilt.edu/~schmidt/ACE-copying.html"
                    ]
                ]
            },
            "spdxLicenseId": "DOC"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://www.cs.wustl.edu/~schmidt/ACE-copying.html",
            "GPLv3 Compat?": "Yes",
            "Short Name": "DOC",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "DOC License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "DOC License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "DOC"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/DOC.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "DOC License",
            "id": "DOC",
            "_implications": {
                "__impliedNames": [
                    "DOC",
                    "DOC License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/DOC.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/DOC.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/DOC.json"
        ],
        [
            null,
            "http://www.cs.wustl.edu/~schmidt/ACE-copying.html"
        ],
        [
            null,
            "https://www.dre.vanderbilt.edu/~schmidt/ACE-copying.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/DOC.svg
