== dvipdfm License (dvipdfm)

[cols=",",options="header",]
|==========================
|Key |Value
|Fullname |dvipdfm License
|Shortname |dvipdfm
|Rating |Unknown
|Classification |NoCopyleft
|==========================

=== Comments on (easy) usability

* *↑* This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/dvipdfm
* *SPDX:* http://spdx.org/licenses/dvipdfm.json

=== Text

....
A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "dvipdfm",
        "dvipdfm License"
    ],
    "__impliedId": "dvipdfm",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "dvipdfm",
                    "dvipdfm",
                    "dvipdfm License"
                ],
                "__impliedId": "dvipdfm"
            },
            "shortname": "dvipdfm",
            "otherNames": [
                "dvipdfm",
                "dvipdfm License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "dvipdfm License",
            "spdxDetailsURL": "http://spdx.org/licenses/dvipdfm.json",
            "_sourceURL": "https://spdx.org/licenses/dvipdfm.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/dvipdfm"
            ],
            "_implications": {
                "__impliedNames": [
                    "dvipdfm",
                    "dvipdfm License"
                ],
                "__impliedId": "dvipdfm",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/dvipdfm.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/dvipdfm"
                    ]
                ]
            },
            "spdxLicenseId": "dvipdfm"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/dvipdfm",
            "GPLv3 Compat?": "NO",
            "Short Name": "dvipdfm",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "dvipdfm License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "dvipdfm License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/dvipdfm",
            "shortName": "dvipdfm License",
            "textUrls": null,
            "text": "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Unspecified",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/dvipdfm.yml",
            "key": "dvipdfm",
            "name": "dvipdfm License",
            "spdxId": "dvipdfm",
            "_implications": {
                "__impliedNames": [
                    "dvipdfm",
                    "dvipdfm License",
                    "dvipdfm"
                ],
                "__impliedId": "dvipdfm",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/dvipdfm"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "A modified version of this file may be distributed, but it should be distributed with a *different* name. Changed files must be distributed *together with a complete and unchanged* distribution of these files.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/dvipdfm.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/dvipdfm"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/dvipdfm"
        ]
    ]
}
....