== Educational Community License v1.0 (ECL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Educational Community License v1.0
|Shortname |ECL-1.0
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |False
|===

*Other Names:*

* `+ECL 1.0+`
* `+Educational Community License, Version 1.0+`
* `+Educational Community License 1.0+`

=== Comments on (easy) usability

* **↑**Is OSI Approved (source:
https://spdx.org/licenses/ECL-1.0.html[SPDX])
* **↑**Rating is: Silver (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* http://www.opensource.org/licenses/ecl1.php
* *OSI Page:* http://opensource.org/licenses/ecl1.php
* *OSI Page:* https://opensource.org/licenses/ECL-1.0
* *SPDX:* http://spdx.org/licenses/ECL-1.0.json
* *SPDX:* https://spdx.org/licenses/ECL-1.0.html

=== Text

....
The Educational Community License 1.0

This Educational Community License (the "License") applies
to any original work of authorship (the "Original Work") whose owner
(the "Licensor") has placed the following notice immediately following
the copyright notice for the Original Work:

Copyright (c) <year> <copyright holders>

Licensed under the Educational Community License version 1.0

This Original Work, including software, source code, documents,
or other related items, is being provided by the copyright holder(s)
subject to the terms of the Educational Community License. By
obtaining, using and/or copying this Original Work, you agree that you
have read, understand, and will comply with the following terms and
conditions of the Educational Community License:

Permission to use, copy, modify, merge, publish, distribute, and
sublicense this Original Work and its documentation, with or without
modification, for any purpose, and without fee or royalty to the
copyright holder(s) is hereby granted, provided that you include the
following on ALL copies of the Original Work or portions thereof,
including modifications or derivatives, that you make:


The full text of the Educational Community License in a location viewable to
users of the redistributed or derivative work.


Any pre-existing intellectual property disclaimers, notices, or terms and
conditions.


Notice of any changes or modifications to the Original Work, including the
date the changes were made.


Any modifications of the Original Work must be distributed in such a manner as
to avoid any confusion with the Original Work of the copyright holders.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

The name and trademarks of copyright holder(s) may NOT be used
in advertising or publicity pertaining to the Original or Derivative
Works without specific, written prior permission. Title to copyright in
the Original Work and any associated documentation will at all times
remain with the copyright holders.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "ECL-1.0",
        "Educational Community License v1.0",
        "ecl-1.0",
        "ECL 1.0",
        "Educational Community License, Version 1.0",
        "Educational Community License 1.0"
    ],
    "__impliedId": "ECL-1.0",
    "__isFsfFree": true,
    "__hasPatentHint": false,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ECL-1.0",
                    "ECL-1.0",
                    "Educational Community License v1.0",
                    "ecl-1.0",
                    "ECL 1.0",
                    "Educational Community License, Version 1.0",
                    "Educational Community License 1.0"
                ],
                "__impliedId": "ECL-1.0"
            },
            "shortname": "ECL-1.0",
            "otherNames": [
                "ECL-1.0",
                "Educational Community License v1.0",
                "ecl-1.0",
                "ECL 1.0",
                "Educational Community License, Version 1.0",
                "Educational Community License 1.0"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Educational Community License v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/ECL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/ECL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/ECL-1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "ECL-1.0",
                    "Educational Community License v1.0"
                ],
                "__impliedId": "ECL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ECL-1.0.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ECL-1.0"
                    ]
                ]
            },
            "spdxLicenseId": "ECL-1.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://opensource.org/licenses/ecl1.php",
            "GPLv3 Compat?": "Yes",
            "Short Name": "ECL 1.0",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Educational Community License 1.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Educational Community License 1.0"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://opensource.org/licenses/ECL-1.0",
                "https://opensource.org/licenses/ECL-1.0"
            ],
            "homepageUrl": "http://www.opensource.org/licenses/ecl1.php",
            "shortName": "ECL 1.0",
            "textUrls": null,
            "text": "The Educational Community License 1.0\n\nThis Educational Community License (the \"License\") applies\nto any original work of authorship (the \"Original Work\") whose owner\n(the \"Licensor\") has placed the following notice immediately following\nthe copyright notice for the Original Work:\n\nCopyright (c) <year> <copyright holders>\n\nLicensed under the Educational Community License version 1.0\n\nThis Original Work, including software, source code, documents,\nor other related items, is being provided by the copyright holder(s)\nsubject to the terms of the Educational Community License. By\nobtaining, using and/or copying this Original Work, you agree that you\nhave read, understand, and will comply with the following terms and\nconditions of the Educational Community License:\n\nPermission to use, copy, modify, merge, publish, distribute, and\nsublicense this Original Work and its documentation, with or without\nmodification, for any purpose, and without fee or royalty to the\ncopyright holder(s) is hereby granted, provided that you include the\nfollowing on ALL copies of the Original Work or portions thereof,\nincluding modifications or derivatives, that you make:\n\n\nThe full text of the Educational Community License in a location viewable to\nusers of the redistributed or derivative work.\n\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions.\n\n\nNotice of any changes or modifications to the Original Work, including the\ndate the changes were made.\n\n\nAny modifications of the Original Work must be distributed in such a manner as\nto avoid any confusion with the Original Work of the copyright holders.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\nIN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\nCLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\nTORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nThe name and trademarks of copyright holder(s) may NOT be used\nin advertising or publicity pertaining to the Original or Derivative\nWorks without specific, written prior permission. Title to copyright in\nthe Original Work and any associated documentation will at all times\nremain with the copyright holders.",
            "category": "Permissive",
            "osiUrl": "http://opensource.org/licenses/ecl1.php",
            "owner": "OSI - Open Source Initiative",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ecl-1.0.yml",
            "key": "ecl-1.0",
            "name": "Educational Community License 1.0",
            "spdxId": "ECL-1.0",
            "_implications": {
                "__impliedNames": [
                    "ecl-1.0",
                    "ECL 1.0",
                    "ECL-1.0"
                ],
                "__impliedId": "ECL-1.0",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The Educational Community License 1.0\n\nThis Educational Community License (the \"License\") applies\nto any original work of authorship (the \"Original Work\") whose owner\n(the \"Licensor\") has placed the following notice immediately following\nthe copyright notice for the Original Work:\n\nCopyright (c) <year> <copyright holders>\n\nLicensed under the Educational Community License version 1.0\n\nThis Original Work, including software, source code, documents,\nor other related items, is being provided by the copyright holder(s)\nsubject to the terms of the Educational Community License. By\nobtaining, using and/or copying this Original Work, you agree that you\nhave read, understand, and will comply with the following terms and\nconditions of the Educational Community License:\n\nPermission to use, copy, modify, merge, publish, distribute, and\nsublicense this Original Work and its documentation, with or without\nmodification, for any purpose, and without fee or royalty to the\ncopyright holder(s) is hereby granted, provided that you include the\nfollowing on ALL copies of the Original Work or portions thereof,\nincluding modifications or derivatives, that you make:\n\n\nThe full text of the Educational Community License in a location viewable to\nusers of the redistributed or derivative work.\n\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions.\n\n\nNotice of any changes or modifications to the Original Work, including the\ndate the changes were made.\n\n\nAny modifications of the Original Work must be distributed in such a manner as\nto avoid any confusion with the Original Work of the copyright holders.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\nIN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\nCLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\nTORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nThe name and trademarks of copyright holder(s) may NOT be used\nin advertising or publicity pertaining to the Original or Derivative\nWorks without specific, written prior permission. Title to copyright in\nthe Original Work and any associated documentation will at all times\nremain with the copyright holders.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.opensource.org/licenses/ecl1.php"
                    ],
                    [
                        "OSI Page",
                        "http://opensource.org/licenses/ecl1.php"
                    ],
                    [
                        null,
                        "http://opensource.org/licenses/ECL-1.0"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ECL-1.0"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/ECL-1.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Educational Community License v1.0",
            "id": "ECL-1.0",
            "_implications": {
                "__impliedNames": [
                    "ECL-1.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ECL-1.0.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/ECL-1.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "ECL-1.0",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": "ECL-2.0",
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "Educational Community License, Version 1.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "obsolete",
                "osi-approved"
            ],
            "id": "ECL-1.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/ECL-1.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "ECL-1.0",
                    "Educational Community License, Version 1.0",
                    "ECL-1.0"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/ECL-1.0"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Permissive",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": "2007",
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "Koordinaten": {
                "name": "Educational Community License",
                "version": "1.0",
                "spdxId": "ECL-1.0"
            },
            "_implications": {
                "__impliedNames": [
                    "ECL-1.0",
                    "Educational Community License 1.0"
                ],
                "__hasPatentHint": false
            },
            "Modification": {
                "value": "Permissive",
                "description": "modification of the code by a licensee"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "The Educational Community License 1.0\n\nThis Educational Community License (the \"License\") applies\nto any original work of authorship (the \"Original Work\") whose owner\n(the \"Licensor\") has placed the following notice immediately following\nthe copyright notice for the Original Work:\n\nCopyright (c) <year> <copyright holders>\n\nLicensed under the Educational Community License version 1.0\n\nThis Original Work, including software, source code, documents,\nor other related items, is being provided by the copyright holder(s)\nsubject to the terms of the Educational Community License. By\nobtaining, using and/or copying this Original Work, you agree that you\nhave read, understand, and will comply with the following terms and\nconditions of the Educational Community License:\n\nPermission to use, copy, modify, merge, publish, distribute, and\nsublicense this Original Work and its documentation, with or without\nmodification, for any purpose, and without fee or royalty to the\ncopyright holder(s) is hereby granted, provided that you include the\nfollowing on ALL copies of the Original Work or portions thereof,\nincluding modifications or derivatives, that you make:\n\n\nThe full text of the Educational Community License in a location viewable to\nusers of the redistributed or derivative work.\n\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions.\n\n\nNotice of any changes or modifications to the Original Work, including the\ndate the changes were made.\n\n\nAny modifications of the Original Work must be distributed in such a manner as\nto avoid any confusion with the Original Work of the copyright holders.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\nIN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\nCLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\nTORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nThe name and trademarks of copyright holder(s) may NOT be used\nin advertising or publicity pertaining to the Original or Derivative\nWorks without specific, written prior permission. Title to copyright in\nthe Original Work and any associated documentation will at all times\nremain with the copyright holders.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ECL-1.0.json"
        ],
        [
            null,
            "https://opensource.org/licenses/ECL-1.0"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ECL-1.0.html"
        ],
        [
            "Homepage",
            "http://www.opensource.org/licenses/ecl1.php"
        ],
        [
            "OSI Page",
            "http://opensource.org/licenses/ecl1.php"
        ],
        [
            null,
            "http://opensource.org/licenses/ECL-1.0"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/ECL-1.0"
        ]
    ]
}
....