== eGenix.com Public License 1.1.0 (eGenix)

[cols=",",options="header",]
|=========================================
|Key |Value
|Fullname |eGenix.com Public License 1.1.0
|Shortname |eGenix
|Rating |Go
|Classification |NoCopyleft
|=========================================

*Other Names:*

* `egenix-1.1.0`
* `eGenix Public License 1.1.0`

=== Comments on (easy) usability

* *↑* Rating is: Bronze (source: https://blueoakcouncil.org/list[BlueOak
License List])
* *↑* This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:*
http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf
* *SPDX:* http://spdx.org/licenses/eGenix.json
* *SPDX:* https://spdx.org/licenses/eGenix.html
* https://fedoraproject.org/wiki/Licensing/eGenix.com_Public_License_1.1.0

=== Text

....
EGENIX.COM PUBLIC LICENSE AGREEMENT 
Version 1.1.0 

This license agreement is based on the Python CNRI License Agreement, a widely accepted open- source license. 

1. Introduction 
This "License Agreement" is between eGenix.com Software, Skills and Services GmbH ("eGenix.com"), having an office at Pastor-Loeh-Str. 48, D-40764 Langenfeld, Germany, and the Individual or Organization ("Licensee") accessing and otherwise using this software in source or binary form and its associated documentation ("the Software"). 

2. License 
Subject to the terms and conditions of this eGenix.com Public License Agreement, eGenix.com hereby grants Licensee a non-exclusive, royalty-free, world-wide license to reproduce, analyze, test, perform and/or display publicly, prepare derivative works, distribute, and otherwise use the Software alone or in any derivative version, provided, however, that the eGenix.com Public License Agreement is retained in the Software, or in any derivative version of the Software prepared by Licensee. 

3. NO WARRANTY 
eGenix.com is making the Software available to Licensee on an "AS IS" basis. SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, EGENIX.COM MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. BY WAY OF EXAMPLE, BUT NOT LIMITATION, EGENIX.COM MAKES NO AND DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE WILL NOT INFRINGE ANY THIRD PARTY RIGHTS. 

4. LIMITATION OF LIABILITY 
EGENIX.COM SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF THE SOFTWARE FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THE SOFTWARE, OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF THE POSSIBILITY THEREOF. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO LICENSEE. 

5. Termination 
This License Agreement will automatically terminate upon a material breach of its terms and conditions. 

6. Third Party Rights 
Any software or documentation in source or binary form provided along with the Software that is associated with a separate license agreement is licensed to Licensee under the terms of that license agreement. This License Agreement does not apply to those portions of the Software. Copies of the third party licenses are included in the Software Distribution. 

7. General 
Nothing in this License Agreement affects any statutory rights of consumers that cannot be waived or limited by contract. 

Nothing in this License Agreement shall be deemed to create any relationship of agency, partnership, or joint venture between eGenix.com and Licensee. 

If any provision of this License Agreement shall be unlawful, void, or for any reason unenforceable, such provision shall be modified to the extent necessary to render it enforceable without losing its intent, or, if no such modification is possible, be severed from this License Agreement and shall not affect the validity and enforceability of the remaining provisions of this License Agreement. 

This License Agreement shall be governed by and interpreted in all respects by the law of Germany, excluding conflict of law provisions. It shall not be governed by the United Nations Convention on Contracts for International Sale of Goods. This License Agreement does not grant permission to use eGenix.com trademarks or trade names in a trademark sense to endorse or promote products or services of Licensee, or any third party. 

The controlling language of this License Agreement is English. If Licensee has received a translation into another language, it has been provided for Licensee's convenience only. 

8. Agreement 
By downloading, copying, installing or otherwise using the Software, Licensee agrees to be bound by the terms and conditions of this License Agreement. For question regarding this License Agreement, please write to: 
     eGenix.com Software, Skills and Services GmbH 
     Pastor-Loeh-Str. 48 
     D-40764 Langenfeld 
     Germany
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "eGenix",
        "eGenix.com Public License 1.1.0",
        "egenix-1.1.0",
        "eGenix Public License 1.1.0"
    ],
    "__impliedId": "eGenix",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "eGenix",
                    "eGenix",
                    "eGenix.com Public License 1.1.0",
                    "egenix-1.1.0",
                    "eGenix Public License 1.1.0"
                ],
                "__impliedId": "eGenix"
            },
            "shortname": "eGenix",
            "otherNames": [
                "eGenix",
                "eGenix.com Public License 1.1.0",
                "egenix-1.1.0",
                "eGenix Public License 1.1.0"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "eGenix.com Public License 1.1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/eGenix.json",
            "_sourceURL": "https://spdx.org/licenses/eGenix.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf",
                "https://fedoraproject.org/wiki/Licensing/eGenix.com_Public_License_1.1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "eGenix",
                    "eGenix.com Public License 1.1.0"
                ],
                "__impliedId": "eGenix",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/eGenix.json"
                    ],
                    [
                        null,
                        "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/eGenix.com_Public_License_1.1.0"
                    ]
                ]
            },
            "spdxLicenseId": "eGenix"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/eGenix.com_Public_License_1.1.0",
            "GPLv3 Compat?": "Yes",
            "Short Name": "eGenix",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "eGenix.com Public License 1.1.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "eGenix.com Public License 1.1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf",
            "shortName": "eGenix Public License 1.1.0",
            "textUrls": null,
            "text": "EGENIX.COM PUBLIC LICENSE AGREEMENT \nVersion 1.1.0 \n\nThis license agreement is based on the Python CNRI License Agreement, a widely accepted open- source license. \n\n1. Introduction \nThis \"License Agreement\" is between eGenix.com Software, Skills and Services GmbH (\"eGenix.com\"), having an office at Pastor-Loeh-Str. 48, D-40764 Langenfeld, Germany, and the Individual or Organization (\"Licensee\") accessing and otherwise using this software in source or binary form and its associated documentation (\"the Software\"). \n\n2. License \nSubject to the terms and conditions of this eGenix.com Public License Agreement, eGenix.com hereby grants Licensee a non-exclusive, royalty-free, world-wide license to reproduce, analyze, test, perform and/or display publicly, prepare derivative works, distribute, and otherwise use the Software alone or in any derivative version, provided, however, that the eGenix.com Public License Agreement is retained in the Software, or in any derivative version of the Software prepared by Licensee. \n\n3. NO WARRANTY \neGenix.com is making the Software available to Licensee on an \"AS IS\" basis. SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, EGENIX.COM MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. BY WAY OF EXAMPLE, BUT NOT LIMITATION, EGENIX.COM MAKES NO AND DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE WILL NOT INFRINGE ANY THIRD PARTY RIGHTS. \n\n4. LIMITATION OF LIABILITY \nEGENIX.COM SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF THE SOFTWARE FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THE SOFTWARE, OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF THE POSSIBILITY THEREOF. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO LICENSEE. \n\n5. Termination \nThis License Agreement will automatically terminate upon a material breach of its terms and conditions. \n\n6. Third Party Rights \nAny software or documentation in source or binary form provided along with the Software that is associated with a separate license agreement is licensed to Licensee under the terms of that license agreement. This License Agreement does not apply to those portions of the Software. Copies of the third party licenses are included in the Software Distribution. \n\n7. General \nNothing in this License Agreement affects any statutory rights of consumers that cannot be waived or limited by contract. \n\nNothing in this License Agreement shall be deemed to create any relationship of agency, partnership, or joint venture between eGenix.com and Licensee. \n\nIf any provision of this License Agreement shall be unlawful, void, or for any reason unenforceable, such provision shall be modified to the extent necessary to render it enforceable without losing its intent, or, if no such modification is possible, be severed from this License Agreement and shall not affect the validity and enforceability of the remaining provisions of this License Agreement. \n\nThis License Agreement shall be governed by and interpreted in all respects by the law of Germany, excluding conflict of law provisions. It shall not be governed by the United Nations Convention on Contracts for International Sale of Goods. This License Agreement does not grant permission to use eGenix.com trademarks or trade names in a trademark sense to endorse or promote products or services of Licensee, or any third party. \n\nThe controlling language of this License Agreement is English. If Licensee has received a translation into another language, it has been provided for Licensee's convenience only. \n\n8. Agreement \nBy downloading, copying, installing or otherwise using the Software, Licensee agrees to be bound by the terms and conditions of this License Agreement. For question regarding this License Agreement, please write to: \n     eGenix.com Software, Skills and Services GmbH \n     Pastor-Loeh-Str. 48 \n     D-40764 Langenfeld \n     Germany",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "eGenix",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/egenix-1.1.0.yml",
            "key": "egenix-1.1.0",
            "name": "eGenix Public License 1.1.0",
            "spdxId": "eGenix",
            "_implications": {
                "__impliedNames": [
                    "egenix-1.1.0",
                    "eGenix Public License 1.1.0",
                    "eGenix"
                ],
                "__impliedId": "eGenix",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "EGENIX.COM PUBLIC LICENSE AGREEMENT \nVersion 1.1.0 \n\nThis license agreement is based on the Python CNRI License Agreement, a widely accepted open- source license. \n\n1. Introduction \nThis \"License Agreement\" is between eGenix.com Software, Skills and Services GmbH (\"eGenix.com\"), having an office at Pastor-Loeh-Str. 48, D-40764 Langenfeld, Germany, and the Individual or Organization (\"Licensee\") accessing and otherwise using this software in source or binary form and its associated documentation (\"the Software\"). \n\n2. License \nSubject to the terms and conditions of this eGenix.com Public License Agreement, eGenix.com hereby grants Licensee a non-exclusive, royalty-free, world-wide license to reproduce, analyze, test, perform and/or display publicly, prepare derivative works, distribute, and otherwise use the Software alone or in any derivative version, provided, however, that the eGenix.com Public License Agreement is retained in the Software, or in any derivative version of the Software prepared by Licensee. \n\n3. NO WARRANTY \neGenix.com is making the Software available to Licensee on an \"AS IS\" basis. SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, EGENIX.COM MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. BY WAY OF EXAMPLE, BUT NOT LIMITATION, EGENIX.COM MAKES NO AND DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE WILL NOT INFRINGE ANY THIRD PARTY RIGHTS. \n\n4. LIMITATION OF LIABILITY \nEGENIX.COM SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF THE SOFTWARE FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THE SOFTWARE, OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF THE POSSIBILITY THEREOF. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO LICENSEE. \n\n5. Termination \nThis License Agreement will automatically terminate upon a material breach of its terms and conditions. \n\n6. Third Party Rights \nAny software or documentation in source or binary form provided along with the Software that is associated with a separate license agreement is licensed to Licensee under the terms of that license agreement. This License Agreement does not apply to those portions of the Software. Copies of the third party licenses are included in the Software Distribution. \n\n7. General \nNothing in this License Agreement affects any statutory rights of consumers that cannot be waived or limited by contract. \n\nNothing in this License Agreement shall be deemed to create any relationship of agency, partnership, or joint venture between eGenix.com and Licensee. \n\nIf any provision of this License Agreement shall be unlawful, void, or for any reason unenforceable, such provision shall be modified to the extent necessary to render it enforceable without losing its intent, or, if no such modification is possible, be severed from this License Agreement and shall not affect the validity and enforceability of the remaining provisions of this License Agreement. \n\nThis License Agreement shall be governed by and interpreted in all respects by the law of Germany, excluding conflict of law provisions. It shall not be governed by the United Nations Convention on Contracts for International Sale of Goods. This License Agreement does not grant permission to use eGenix.com trademarks or trade names in a trademark sense to endorse or promote products or services of Licensee, or any third party. \n\nThe controlling language of this License Agreement is English. If Licensee has received a translation into another language, it has been provided for Licensee's convenience only. \n\n8. Agreement \nBy downloading, copying, installing or otherwise using the Software, Licensee agrees to be bound by the terms and conditions of this License Agreement. For question regarding this License Agreement, please write to: \n     eGenix.com Software, Skills and Services GmbH \n     Pastor-Loeh-Str. 48 \n     D-40764 Langenfeld \n     Germany",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/eGenix.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "eGenix.com Public License 1.1.0",
            "id": "eGenix",
            "_implications": {
                "__impliedNames": [
                    "eGenix"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/eGenix.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "EGENIX.COM PUBLIC LICENSE AGREEMENT \nVersion 1.1.0 \n\nThis license agreement is based on the Python CNRI License Agreement, a widely accepted open- source license. \n\n1. Introduction \nThis \"License Agreement\" is between eGenix.com Software, Skills and Services GmbH (\"eGenix.com\"), having an office at Pastor-Loeh-Str. 48, D-40764 Langenfeld, Germany, and the Individual or Organization (\"Licensee\") accessing and otherwise using this software in source or binary form and its associated documentation (\"the Software\"). \n\n2. License \nSubject to the terms and conditions of this eGenix.com Public License Agreement, eGenix.com hereby grants Licensee a non-exclusive, royalty-free, world-wide license to reproduce, analyze, test, perform and/or display publicly, prepare derivative works, distribute, and otherwise use the Software alone or in any derivative version, provided, however, that the eGenix.com Public License Agreement is retained in the Software, or in any derivative version of the Software prepared by Licensee. \n\n3. NO WARRANTY \neGenix.com is making the Software available to Licensee on an \"AS IS\" basis. SUBJECT TO ANY STATUTORY WARRANTIES WHICH CAN NOT BE EXCLUDED, EGENIX.COM MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED. BY WAY OF EXAMPLE, BUT NOT LIMITATION, EGENIX.COM MAKES NO AND DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE WILL NOT INFRINGE ANY THIRD PARTY RIGHTS. \n\n4. LIMITATION OF LIABILITY \nEGENIX.COM SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF THE SOFTWARE FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THE SOFTWARE, OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF THE POSSIBILITY THEREOF. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO LICENSEE. \n\n5. Termination \nThis License Agreement will automatically terminate upon a material breach of its terms and conditions. \n\n6. Third Party Rights \nAny software or documentation in source or binary form provided along with the Software that is associated with a separate license agreement is licensed to Licensee under the terms of that license agreement. This License Agreement does not apply to those portions of the Software. Copies of the third party licenses are included in the Software Distribution. \n\n7. General \nNothing in this License Agreement affects any statutory rights of consumers that cannot be waived or limited by contract. \n\nNothing in this License Agreement shall be deemed to create any relationship of agency, partnership, or joint venture between eGenix.com and Licensee. \n\nIf any provision of this License Agreement shall be unlawful, void, or for any reason unenforceable, such provision shall be modified to the extent necessary to render it enforceable without losing its intent, or, if no such modification is possible, be severed from this License Agreement and shall not affect the validity and enforceability of the remaining provisions of this License Agreement. \n\nThis License Agreement shall be governed by and interpreted in all respects by the law of Germany, excluding conflict of law provisions. It shall not be governed by the United Nations Convention on Contracts for International Sale of Goods. This License Agreement does not grant permission to use eGenix.com trademarks or trade names in a trademark sense to endorse or promote products or services of Licensee, or any third party. \n\nThe controlling language of this License Agreement is English. If Licensee has received a translation into another language, it has been provided for Licensee's convenience only. \n\n8. Agreement \nBy downloading, copying, installing or otherwise using the Software, Licensee agrees to be bound by the terms and conditions of this License Agreement. For question regarding this License Agreement, please write to: \n     eGenix.com Software, Skills and Services GmbH \n     Pastor-Loeh-Str. 48 \n     D-40764 Langenfeld \n     Germany",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/eGenix.json"
        ],
        [
            null,
            "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/eGenix.com_Public_License_1.1.0"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/eGenix.html"
        ],
        [
            "Homepage",
            "http://www.egenix.com/products/eGenix.com-Public-License-1.1.0.pdf"
        ]
    ]
}
....