== European Union Public License 1.0 (EUPL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |European Union Public License 1.0
|Shortname |EUPL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |SaaSCopyleft
|===

=== Comments on (easy) usability

* **↓**``Google Classification is CANNOT_BE_USED "The EUPL is very
similar to the AGPL. For the same reasons that the AGPL is banned, the
use of EUPL-licensed software is not allowed at Google."'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))

=== General Comments

* ``In addition to the requirements of strong copyleft licenses, network
copyleft licenses require you to share larger programs that you build
with the licensed software not just when you give copies to others, but
also when you run the software for others to use over the Internet or
another network.'' (source: https://blueoakcouncil.org/copyleft[BlueOak
License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* ``Strong copyleft licenses require you to share both the licensed
software (like the weak copyleft licenses, and larger programs that you
build with the licensed software, when you give copies to others.''
(source: https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *SPDX:* http://spdx.org/licenses/EUPL-1.0.json
* https://spdx.org/licenses/EUPL-1.0.html
* http://ec.europa.eu/idabc/en/document/7330.html
* http://ec.europa.eu/idabc/servlets/Doc027f.pdf?id=31096

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/EUPL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "EUPL-1.0",
        "European Union Public License 1.0"
    ],
    "__impliedId": "EUPL-1.0",
    "__impliedAmbiguousNames": [
        "European Union Public License"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "EUPL-1.0"
                ],
                "__impliedId": "EUPL-1.0"
            },
            "shortname": "EUPL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "European Union Public License 1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/EUPL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/EUPL-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://ec.europa.eu/idabc/en/document/7330.html",
                "http://ec.europa.eu/idabc/servlets/Doc027f.pdf?id=31096"
            ],
            "_implications": {
                "__impliedNames": [
                    "EUPL-1.0",
                    "European Union Public License 1.0"
                ],
                "__impliedId": "EUPL-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/EUPL-1.0.json"
                    ],
                    [
                        null,
                        "http://ec.europa.eu/idabc/en/document/7330.html"
                    ],
                    [
                        null,
                        "http://ec.europa.eu/idabc/servlets/Doc027f.pdf?id=31096"
                    ]
                ]
            },
            "spdxLicenseId": "EUPL-1.0"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "EUPL-1.0"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "StrongCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "StrongCopyleft"
            },
            "licensename": "EUPL-1.0",
            "copyleftkind": "StrongCopyleft"
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/EUPL-1.0.html",
            "familyName": "European Union Public License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "European Union Public License 1.0",
            "id": "EUPL-1.0",
            "_implications": {
                "__impliedNames": [
                    "EUPL-1.0",
                    "European Union Public License 1.0"
                ],
                "__impliedAmbiguousNames": [
                    "European Union Public License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                            "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "SaaSCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "SaaSCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/EUPL-1.0.html"
                    ]
                ]
            },
            "CopyleftKind": "SaaSCopyleft"
        },
        "Google OSS Policy": {
            "rating": "CANNOT_BE_USED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "EUPL-1.0",
            "_implications": {
                "__impliedNames": [
                    "EUPL-1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is CANNOT_BE_USED \"The EUPL is very similar to the AGPL. For the same reasons that the AGPL is banned, the use of EUPL-licensed software is not allowed at Google.\""
                        }
                    ]
                ]
            },
            "description": "The EUPL is very similar to the AGPL. For the same reasons that the AGPL is banned, the use of EUPL-licensed software is not allowed at Google."
        }
    },
    "__impliedJudgement": [
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is CANNOT_BE_USED \"The EUPL is very similar to the AGPL. For the same reasons that the AGPL is banned, the use of EUPL-licensed software is not allowed at Google.\""
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "SaaSCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "StrongCopyleft"
        ]
    ],
    "__calculatedCopyleft": "SaaSCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/EUPL-1.0.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/EUPL-1.0.json"
        ],
        [
            null,
            "http://ec.europa.eu/idabc/en/document/7330.html"
        ],
        [
            null,
            "http://ec.europa.eu/idabc/servlets/Doc027f.pdf?id=31096"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/EUPL-1.0.svg
