== Eurosym License (Eurosym)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Eurosym License
|Shortname |Eurosym
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/Eurosym.json
* https://fedoraproject.org/wiki/Licensing/Eurosym

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/Eurosym.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Eurosym",
        "Eurosym License"
    ],
    "__impliedId": "Eurosym",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Eurosym"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Eurosym"
                ],
                "__impliedId": "Eurosym"
            },
            "shortname": "Eurosym",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Eurosym License",
            "spdxDetailsURL": "http://spdx.org/licenses/Eurosym.json",
            "_sourceURL": "https://spdx.org/licenses/Eurosym.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Eurosym"
            ],
            "_implications": {
                "__impliedNames": [
                    "Eurosym",
                    "Eurosym License"
                ],
                "__impliedId": "Eurosym",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Eurosym.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Eurosym"
                    ]
                ]
            },
            "spdxLicenseId": "Eurosym"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Eurosym",
            "GPLv3 Compat?": "NO",
            "Short Name": "Eurosym",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Eurosym License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Eurosym License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Eurosym"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Eurosym.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Eurosym"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Eurosym.svg
