== Fair License (Fair)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Fair License
|Shortname |Fair
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `Fair License (Fair)`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/Fair.html[SPDX] (all data [in this repository]
is generated))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *OSI Page:* https://opensource.org/licenses/Fair
* *SPDX:* https://spdx.org/licenses/Fair.html
* *SPDX:* http://spdx.org/licenses/Fair.json
* http://fairlicense.org/

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/Fair.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Fair",
        "Fair License",
        "Fair License (Fair)"
    ],
    "__impliedId": "Fair",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Fair"
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/Fair",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "Fair",
            "title": "Fair License",
            "_implications": {
                "__impliedNames": [
                    "Fair",
                    "Fair License"
                ],
                "__impliedId": "Fair",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/Fair"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Fair"
                ],
                "__impliedId": "Fair"
            },
            "shortname": "Fair",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Fair License",
            "spdxDetailsURL": "http://spdx.org/licenses/Fair.json",
            "_sourceURL": "https://spdx.org/licenses/Fair.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://fairlicense.org/",
                "https://opensource.org/licenses/Fair"
            ],
            "_implications": {
                "__impliedNames": [
                    "Fair",
                    "Fair License"
                ],
                "__impliedId": "Fair",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Fair.json"
                    ],
                    [
                        null,
                        "http://fairlicense.org/"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/Fair"
                    ]
                ]
            },
            "spdxLicenseId": "Fair"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://opensource.org/licenses/fair.php",
            "GPLv3 Compat?": "Yes",
            "Short Name": "Fair",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Fair License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Fair License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Fair"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Fair License ",
            "commercialUse": true,
            "spdxId": "Fair",
            "_implications": {
                "__impliedNames": [
                    "Fair"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Fair.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Fair License",
            "id": "Fair",
            "_implications": {
                "__impliedNames": [
                    "Fair",
                    "Fair License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Fair.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/Fair",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "Fair",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "Fair License (Fair)",
            "other_names": [],
            "keywords": [
                "osi-approved",
                "discouraged",
                "redundant"
            ],
            "id": "Fair",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/Fair"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Fair",
                    "Fair License (Fair)",
                    "Fair"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/Fair"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Fair.html"
        ],
        [
            null,
            "https://opensource.org/licenses/Fair"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/Fair"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Fair.json"
        ],
        [
            null,
            "http://fairlicense.org/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Fair.svg
