== Fraunhofer FDK AAC Codec Library (FDK-AAC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Fraunhofer FDK AAC Codec Library
|Shortname |FDK-AAC
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Fraunhofer FDK AAC Codec Library (Android)`

=== Comments on (easy) usability

=== General Comments

* ``category: Fraunhofer FDK AAC Codec Library'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/Fraunhofer-FDK-AAC-Codec-Library-(Android).yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/FDK-AAC.json
* https://fedoraproject.org/wiki/Licensing/FDK-AAC
* https://directory.fsf.org/wiki/License:Fdk

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/Fraunhofer-FDK-AAC-Codec-Library-(Android).yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/FDK-AAC.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "FDK-AAC",
        "Fraunhofer FDK AAC Codec Library (Android)",
        "Fraunhofer FDK AAC Codec Library"
    ],
    "__impliedId": "FDK-AAC",
    "__impliedAmbiguousNames": [
        "http://opencore-amr.git.sourceforge.net/git/gitweb.cgi?p=opencore-amr/fdk-aac;a=blob;f=NOTICE",
        "Fraunhofer FDK AAC Codec Library for Android",
        "scancode:fraunhofer-fdk-aac-codec"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: Fraunhofer FDK AAC Codec Library"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FDK-AAC"
                ],
                "__impliedId": "FDK-AAC"
            },
            "shortname": "FDK-AAC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Fraunhofer FDK AAC Codec Library",
            "spdxDetailsURL": "https://spdx.org/licenses/FDK-AAC.json",
            "_sourceURL": "https://spdx.org/licenses/FDK-AAC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/FDK-AAC",
                "https://directory.fsf.org/wiki/License:Fdk"
            ],
            "_implications": {
                "__impliedNames": [
                    "FDK-AAC",
                    "Fraunhofer FDK AAC Codec Library"
                ],
                "__impliedId": "FDK-AAC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/FDK-AAC.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/FDK-AAC"
                    ],
                    [
                        null,
                        "https://directory.fsf.org/wiki/License:Fdk"
                    ]
                ]
            },
            "spdxLicenseId": "FDK-AAC"
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "FDK-AAC",
            "shortName": null,
            "category": "Fraunhofer FDK AAC Codec Library",
            "alternativeNames": [
                "http://opencore-amr.git.sourceforge.net/git/gitweb.cgi?p=opencore-amr/fdk-aac;a=blob;f=NOTICE",
                "Fraunhofer FDK AAC Codec Library for Android"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/Fraunhofer-FDK-AAC-Codec-Library-(Android).yaml",
            "otherIds": [
                "scancode:fraunhofer-fdk-aac-codec"
            ],
            "canonicalName": "Fraunhofer FDK AAC Codec Library (Android)",
            "_implications": {
                "__impliedNames": [
                    "Fraunhofer FDK AAC Codec Library (Android)",
                    "FDK-AAC"
                ],
                "__impliedId": "FDK-AAC",
                "__impliedAmbiguousNames": [
                    "http://opencore-amr.git.sourceforge.net/git/gitweb.cgi?p=opencore-amr/fdk-aac;a=blob;f=NOTICE",
                    "Fraunhofer FDK AAC Codec Library for Android",
                    "scancode:fraunhofer-fdk-aac-codec"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: Fraunhofer FDK AAC Codec Library"
                        ]
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/FDK-AAC.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/FDK-AAC"
        ],
        [
            null,
            "https://directory.fsf.org/wiki/License:Fdk"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/FDK-AAC.svg
