== Fraunhofer FDK AAC Codec Library (FDK-AAC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Fraunhofer FDK AAC Codec Library
|Shortname |FDK-AAC
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/FDK-AAC.json
* https://fedoraproject.org/wiki/Licensing/FDK-AAC
* https://directory.fsf.org/wiki/License:Fdk

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/FDK-AAC.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "FDK-AAC",
        "Fraunhofer FDK AAC Codec Library"
    ],
    "__impliedId": "FDK-AAC",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FDK-AAC"
                ],
                "__impliedId": "FDK-AAC"
            },
            "shortname": "FDK-AAC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Fraunhofer FDK AAC Codec Library",
            "spdxDetailsURL": "https://spdx.org/licenses/FDK-AAC.json",
            "_sourceURL": "https://spdx.org/licenses/FDK-AAC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/FDK-AAC",
                "https://directory.fsf.org/wiki/License:Fdk"
            ],
            "_implications": {
                "__impliedNames": [
                    "FDK-AAC",
                    "Fraunhofer FDK AAC Codec Library"
                ],
                "__impliedId": "FDK-AAC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/FDK-AAC.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/FDK-AAC"
                    ],
                    [
                        null,
                        "https://directory.fsf.org/wiki/License:Fdk"
                    ]
                ]
            },
            "spdxLicenseId": "FDK-AAC"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/FDK-AAC.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/FDK-AAC"
        ],
        [
            null,
            "https://directory.fsf.org/wiki/License:Fdk"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/FDK-AAC.svg
