== FreeBSD Documentation License (FreeBSD-DOC)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |FreeBSD Documentation License
|Shortname |FreeBSD-DOC
|Rating |Unknown
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://freebsd-doc`
* `FreeBSD Doc License`

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``category: FreeBSD Doc License'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/FreeBSD-Documentation-License.yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/FreeBSD-DOC.json
* https://www.freebsd.org/copyright/freebsd-doc-license/

=== Text

....
Redistribution and use in source and 'compiled' forms with or without
modification, are permitted provided that the following conditions are met:

    Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer as the first lines of this
    file unmodified.

    Redistributions in compiled form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

THIS DOCUMENTATION IS PROVIDED BY THE PROJECT "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/FreeBSD-Documentation-License.yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/FreeBSD-DOC.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/freebsd-doc.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "FreeBSD-DOC",
        "FreeBSD Documentation License",
        "scancode://freebsd-doc",
        "FreeBSD Doc License"
    ],
    "__impliedId": "FreeBSD-DOC",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "FBSDDL",
        "FreeBSD Documentation License"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: FreeBSD Doc License"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FreeBSD-DOC"
                ],
                "__impliedId": "FreeBSD-DOC"
            },
            "shortname": "FreeBSD-DOC",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "FreeBSD Documentation License",
            "spdxDetailsURL": "https://spdx.org/licenses/FreeBSD-DOC.json",
            "_sourceURL": "https://spdx.org/licenses/FreeBSD-DOC.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.freebsd.org/copyright/freebsd-doc-license/"
            ],
            "_implications": {
                "__impliedNames": [
                    "FreeBSD-DOC",
                    "FreeBSD Documentation License"
                ],
                "__impliedId": "FreeBSD-DOC",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/FreeBSD-DOC.json"
                    ],
                    [
                        null,
                        "https://www.freebsd.org/copyright/freebsd-doc-license/"
                    ]
                ]
            },
            "spdxLicenseId": "FreeBSD-DOC"
        },
        "Fedora Project Wiki": {
            "rating": "Good",
            "Upstream URL": "http://www.freebsd.org/copyright/freebsd-doc-license.html",
            "Short Name": "FBSDDL",
            "licenseType": "documentation license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "FreeBSD Documentation License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "FreeBSD Documentation License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "FBSDDL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "https://www.freebsd.org/copyright/freebsd-doc-license/"
            ],
            "homepageUrl": null,
            "shortName": "FreeBSD Doc License",
            "textUrls": null,
            "text": "Redistribution and use in source and 'compiled' forms with or without\nmodification, are permitted provided that the following conditions are met:\n\n    Redistributions of source code must retain the above copyright notice, this\n    list of conditions and the following disclaimer as the first lines of this\n    file unmodified.\n\n    Redistributions in compiled form must reproduce the above copyright notice,\n    this list of conditions and the following disclaimer in the documentation\n    and/or other materials provided with the distribution.\n\nTHIS DOCUMENTATION IS PROVIDED BY THE PROJECT \"AS IS\" AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\nEXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT\nOF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\nCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE\nPOSSIBILITY OF SUCH DAMAGE",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "FreeBSD",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/freebsd-doc.yml",
            "key": "freebsd-doc",
            "name": "FreeBSD Doc License",
            "spdxId": "FreeBSD-DOC",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://freebsd-doc",
                    "FreeBSD Doc License",
                    "FreeBSD-DOC"
                ],
                "__impliedId": "FreeBSD-DOC",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and 'compiled' forms with or without\nmodification, are permitted provided that the following conditions are met:\n\n    Redistributions of source code must retain the above copyright notice, this\n    list of conditions and the following disclaimer as the first lines of this\n    file unmodified.\n\n    Redistributions in compiled form must reproduce the above copyright notice,\n    this list of conditions and the following disclaimer in the documentation\n    and/or other materials provided with the distribution.\n\nTHIS DOCUMENTATION IS PROVIDED BY THE PROJECT \"AS IS\" AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\nEXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT\nOF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\nCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE\nPOSSIBILITY OF SUCH DAMAGE",
                "__impliedURLs": [
                    [
                        null,
                        "https://www.freebsd.org/copyright/freebsd-doc-license/"
                    ]
                ]
            }
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "FreeBSD-DOC",
            "shortName": null,
            "category": "FreeBSD Doc License",
            "alternativeNames": [
                "FreeBSD Documentation License"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[f]/[fr]/FreeBSD-Documentation-License.yaml",
            "otherIds": [],
            "canonicalName": "FreeBSD Documentation License",
            "_implications": {
                "__impliedNames": [
                    "FreeBSD Documentation License",
                    "FreeBSD-DOC"
                ],
                "__impliedId": "FreeBSD-DOC",
                "__impliedAmbiguousNames": [
                    "FreeBSD Documentation License"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: FreeBSD Doc License"
                        ]
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and 'compiled' forms with or without\nmodification, are permitted provided that the following conditions are met:\n\n    Redistributions of source code must retain the above copyright notice, this\n    list of conditions and the following disclaimer as the first lines of this\n    file unmodified.\n\n    Redistributions in compiled form must reproduce the above copyright notice,\n    this list of conditions and the following disclaimer in the documentation\n    and/or other materials provided with the distribution.\n\nTHIS DOCUMENTATION IS PROVIDED BY THE PROJECT \"AS IS\" AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\nEXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT\nOF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\nINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\nCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS DOCUMENTATION, EVEN IF ADVISED OF THE\nPOSSIBILITY OF SUCH DAMAGE",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/FreeBSD-DOC.json"
        ],
        [
            null,
            "https://www.freebsd.org/copyright/freebsd-doc-license/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/FreeBSD-DOC.svg
