== FSF Unlimited License (FSFUL)

[cols=",",options="header",]
|===============================
|Key |Value
|Fullname |FSF Unlimited License
|Shortname |FSFUL
|Rating |Unknown
|Classification |NoCopyleft
|===============================

*Other Names:*

* `fsf-free`
* `FSF Free Software License`

=== Comments on (easy) usability

* *↑* This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* http://www.fsf.org/licensing/licenses/
* *SPDX:* http://spdx.org/licenses/FSFUL.json
* https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License

=== Text

....
This configure script is free software; the Free Software Foundation gives
unlimited permission to copy, distribute and modify it.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "FSFUL",
        "FSF Unlimited License",
        "fsf-free",
        "FSF Free Software License"
    ],
    "__impliedId": "FSFUL",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FSFUL",
                    "FSFUL",
                    "FSF Unlimited License",
                    "fsf-free",
                    "FSF Free Software License"
                ],
                "__impliedId": "FSFUL"
            },
            "shortname": "FSFUL",
            "otherNames": [
                "FSFUL",
                "FSF Unlimited License",
                "fsf-free",
                "FSF Free Software License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "FSF Unlimited License",
            "spdxDetailsURL": "http://spdx.org/licenses/FSFUL.json",
            "_sourceURL": "https://spdx.org/licenses/FSFUL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "FSFUL",
                    "FSF Unlimited License"
                ],
                "__impliedId": "FSFUL",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/FSFUL.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License"
                    ]
                ]
            },
            "spdxLicenseId": "FSFUL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License",
            "GPLv3 Compat?": "Yes",
            "Short Name": "FSFUL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "FSF Unlimited License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "FSF Unlimited License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.fsf.org/licensing/licenses/",
            "shortName": "FSF Free Software License",
            "textUrls": null,
            "text": "This configure script is free software; the Free Software Foundation gives\nunlimited permission to copy, distribute and modify it.",
            "category": "Public Domain",
            "osiUrl": null,
            "owner": "Free Software Foundation (FSF)",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/fsf-free.yml",
            "key": "fsf-free",
            "name": "Free Software Foundation - Free Software License",
            "spdxId": "FSFUL",
            "_implications": {
                "__impliedNames": [
                    "fsf-free",
                    "FSF Free Software License",
                    "FSFUL"
                ],
                "__impliedId": "FSFUL",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This configure script is free software; the Free Software Foundation gives\nunlimited permission to copy, distribute and modify it.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.fsf.org/licensing/licenses/"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "This configure script is free software; the Free Software Foundation gives\nunlimited permission to copy, distribute and modify it.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/FSFUL.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License"
        ],
        [
            "Homepage",
            "http://www.fsf.org/licensing/licenses/"
        ]
    ]
}
....