== FSF Unlimited License (with License Retention) (FSFULLR)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |FSF Unlimited License (with License Retention)
|Shortname |FSFULLR
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/FSFULLR.json
* https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/FSFULLR.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "FSFULLR",
        "FSF Unlimited License (with License Retention)"
    ],
    "__impliedId": "FSFULLR",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "FSFULLR"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FSFULLR"
                ],
                "__impliedId": "FSFULLR"
            },
            "shortname": "FSFULLR",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "FSF Unlimited License (with License Retention)",
            "spdxDetailsURL": "http://spdx.org/licenses/FSFULLR.json",
            "_sourceURL": "https://spdx.org/licenses/FSFULLR.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
            ],
            "_implications": {
                "__impliedNames": [
                    "FSFULLR",
                    "FSF Unlimited License (with License Retention)"
                ],
                "__impliedId": "FSFULLR",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/FSFULLR.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
                    ]
                ]
            },
            "spdxLicenseId": "FSFULLR"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant",
            "GPLv3 Compat?": "Yes",
            "Short Name": "FSFULLR",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "FSF Unlimited License (with License Retention)",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "FSF Unlimited License (with License Retention)"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "FSFULLR"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/FSFULLR.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/FSFULLR.svg
