== FSF Unlimited License (with License Retention) (FSFULLR)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |FSF Unlimited License (with License Retention)
|Shortname |FSFULLR
|Rating |Unknown
|Classification |NoCopyleft
|===

*Other Names:*

* `+fsf-unlimited+`
* `+FSF-Unlimited+`

=== Comments on (easy) usability

* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:*
https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant
* *SPDX:* http://spdx.org/licenses/FSFULLR.json

=== Text

....
This file is free software; the Free Software Foundation gives
unlimited permission to copy and/or distribute it, with or without
modifications, as long as this notice is preserved.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "FSFULLR",
        "FSF Unlimited License (with License Retention)",
        "fsf-unlimited",
        "FSF-Unlimited"
    ],
    "__impliedId": "FSFULLR",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "FSFULLR",
                    "FSFULLR",
                    "FSF Unlimited License (with License Retention)",
                    "fsf-unlimited",
                    "FSF-Unlimited"
                ],
                "__impliedId": "FSFULLR"
            },
            "shortname": "FSFULLR",
            "otherNames": [
                "FSFULLR",
                "FSF Unlimited License (with License Retention)",
                "fsf-unlimited",
                "FSF-Unlimited"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "FSF Unlimited License (with License Retention)",
            "spdxDetailsURL": "http://spdx.org/licenses/FSFULLR.json",
            "_sourceURL": "https://spdx.org/licenses/FSFULLR.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
            ],
            "_implications": {
                "__impliedNames": [
                    "FSFULLR",
                    "FSF Unlimited License (with License Retention)"
                ],
                "__impliedId": "FSFULLR",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/FSFULLR.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
                    ]
                ]
            },
            "spdxLicenseId": "FSFULLR"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant",
            "GPLv3 Compat?": "Yes",
            "Short Name": "FSFULLR",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "FSF Unlimited License (with License Retention)",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "FSF Unlimited License (with License Retention)"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant",
            "shortName": "FSF-Unlimited",
            "textUrls": null,
            "text": "This file is free software; the Free Software Foundation gives\nunlimited permission to copy and/or distribute it, with or without\nmodifications, as long as this notice is preserved.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Free Software Foundation (FSF)",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/fsf-unlimited.yml",
            "key": "fsf-unlimited",
            "name": "Free Software Foundation - Unlimited License",
            "spdxId": "FSFULLR",
            "_implications": {
                "__impliedNames": [
                    "fsf-unlimited",
                    "FSF-Unlimited",
                    "FSFULLR"
                ],
                "__impliedId": "FSFULLR",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This file is free software; the Free Software Foundation gives\nunlimited permission to copy and/or distribute it, with or without\nmodifications, as long as this notice is preserved.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This file is free software; the Free Software Foundation gives\nunlimited permission to copy and/or distribute it, with or without\nmodifications, as long as this notice is preserved.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/FSFULLR.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention_Variant"
        ]
    ]
}
....