== GNU Free Documentation License v1.3 only (GFDL-1.3-only)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |GNU Free Documentation License v1.3 only
|Shortname |GFDL-1.3-only
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↓**``Exception: Data licensed under the FDL with no invariant
sections are considered DFSG-free as of GR 2006-001:
http://www.debian.org/vote/2006/vote_001#outcome'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/GFDL-1.3-only.json
* https://www.gnu.org/licenses/fdl-1.3.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://spdx.org/licenses/GFDL-1.3-only.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "GFDL-1.3-only",
        "GNU Free Documentation License v1.3 only"
    ],
    "__impliedId": "GFDL-1.3-only",
    "__impliedAmbiguousNames": [
        "GNU Free Documentation License (GFDL)"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "GFDL-1.3-only"
                ],
                "__impliedId": "GFDL-1.3-only"
            },
            "shortname": "GFDL-1.3-only",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "GNU Free Documentation License v1.3 only",
            "spdxDetailsURL": "http://spdx.org/licenses/GFDL-1.3-only.json",
            "_sourceURL": "https://spdx.org/licenses/GFDL-1.3-only.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.gnu.org/licenses/fdl-1.3.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "GFDL-1.3-only",
                    "GNU Free Documentation License v1.3 only"
                ],
                "__impliedId": "GFDL-1.3-only",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/GFDL-1.3-only.json"
                    ],
                    [
                        null,
                        "https://www.gnu.org/licenses/fdl-1.3.txt"
                    ]
                ]
            },
            "spdxLicenseId": "GFDL-1.3-only"
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "GNU Free Documentation License (GFDL)",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "GFDL-1.3-only"
                ],
                "__impliedAmbiguousNames": [
                    "GNU Free Documentation License (GFDL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Exception: Data licensed under the FDL with no invariant sections are considered DFSG-free as of GR 2006-001: http://www.debian.org/vote/2006/vote_001#outcome"
                        }
                    ]
                ]
            },
            "Comment": "Exception: Data licensed under the FDL with no invariant sections are considered DFSG-free as of GR 2006-001: http://www.debian.org/vote/2006/vote_001#outcome",
            "LicenseId": "GFDL-1.3-only"
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "Exception: Data licensed under the FDL with no invariant sections are considered DFSG-free as of GR 2006-001: http://www.debian.org/vote/2006/vote_001#outcome"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/GFDL-1.3-only.json"
        ],
        [
            null,
            "https://www.gnu.org/licenses/fdl-1.3.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/GFDL-1.3-only.svg
