== GNU Free Documentation License v1.1 or later - invariants (GFDL-1.1-invariants-or-later)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |GNU Free Documentation License v1.1 or later - invariants
|Shortname |GFDL-1.1-invariants-or-later
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/GFDL-1.1-invariants-or-later.json
* https://www.gnu.org/licenses/old-licenses/fdl-1.1.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/GFDL-1.1-invariants-or-later.html[SPDX] (all
data [in this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "GFDL-1.1-invariants-or-later",
        "GNU Free Documentation License v1.1 or later - invariants"
    ],
    "__impliedId": "GFDL-1.1-invariants-or-later",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "GFDL-1.1-invariants-or-later"
                ],
                "__impliedId": "GFDL-1.1-invariants-or-later"
            },
            "shortname": "GFDL-1.1-invariants-or-later",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "GNU Free Documentation License v1.1 or later - invariants",
            "spdxDetailsURL": "http://spdx.org/licenses/GFDL-1.1-invariants-or-later.json",
            "_sourceURL": "https://spdx.org/licenses/GFDL-1.1-invariants-or-later.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.gnu.org/licenses/old-licenses/fdl-1.1.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "GFDL-1.1-invariants-or-later",
                    "GNU Free Documentation License v1.1 or later - invariants"
                ],
                "__impliedId": "GFDL-1.1-invariants-or-later",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/GFDL-1.1-invariants-or-later.json"
                    ],
                    [
                        null,
                        "https://www.gnu.org/licenses/old-licenses/fdl-1.1.txt"
                    ]
                ]
            },
            "spdxLicenseId": "GFDL-1.1-invariants-or-later"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/GFDL-1.1-invariants-or-later.json"
        ],
        [
            null,
            "https://www.gnu.org/licenses/old-licenses/fdl-1.1.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/GFDL-1.1-invariants-or-later.svg
