== Glulxe License (Glulxe)

[cols=",",options="header",]
|==========================
|Key |Value
|Fullname |Glulxe License
|Shortname |Glulxe
|Rating |Unknown
|Classification |NoCopyleft
|==========================

=== Comments on (easy) usability

* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Glulxe
* *SPDX:* http://spdx.org/licenses/Glulxe.json

=== Text

....
You may copy and distribute it freely, by any means and under any conditions,
as long as the code and documentation is not changed. You may also incorporate
this code into your own program and distribute that, or modify this code and
use and distribute the modified version, as long as you retain a notice in your
program or documentation which mentions my name and the URL shown above.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Glulxe",
        "Glulxe License",
        "glulxe"
    ],
    "__impliedId": "Glulxe",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Glulxe",
                    "Glulxe",
                    "Glulxe License",
                    "glulxe"
                ],
                "__impliedId": "Glulxe"
            },
            "shortname": "Glulxe",
            "otherNames": [
                "Glulxe",
                "Glulxe License",
                "glulxe"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Glulxe License",
            "spdxDetailsURL": "http://spdx.org/licenses/Glulxe.json",
            "_sourceURL": "https://spdx.org/licenses/Glulxe.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Glulxe"
            ],
            "_implications": {
                "__impliedNames": [
                    "Glulxe",
                    "Glulxe License"
                ],
                "__impliedId": "Glulxe",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Glulxe.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Glulxe"
                    ]
                ]
            },
            "spdxLicenseId": "Glulxe"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Glulxe",
            "GPLv3 Compat?": "Yes",
            "Short Name": "Glulxe",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Glulxe License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Glulxe License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Glulxe",
            "shortName": "Glulxe License",
            "textUrls": null,
            "text": "You may copy and distribute it freely, by any means and under any conditions,\nas long as the code and documentation is not changed. You may also incorporate\nthis code into your own program and distribute that, or modify this code and\nuse and distribute the modified version, as long as you retain a notice in your\nprogram or documentation which mentions my name and the URL shown above.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Andrew Plotkin",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/glulxe.yml",
            "key": "glulxe",
            "name": "Glulxe License",
            "spdxId": "Glulxe",
            "_implications": {
                "__impliedNames": [
                    "glulxe",
                    "Glulxe License",
                    "Glulxe"
                ],
                "__impliedId": "Glulxe",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "You may copy and distribute it freely, by any means and under any conditions,\nas long as the code and documentation is not changed. You may also incorporate\nthis code into your own program and distribute that, or modify this code and\nuse and distribute the modified version, as long as you retain a notice in your\nprogram or documentation which mentions my name and the URL shown above.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Glulxe"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "You may copy and distribute it freely, by any means and under any conditions,\nas long as the code and documentation is not changed. You may also incorporate\nthis code into your own program and distribute that, or modify this code and\nuse and distribute the modified version, as long as you retain a notice in your\nprogram or documentation which mentions my name and the URL shown above.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Glulxe.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Glulxe"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Glulxe"
        ]
    ]
}
....