== Good Luck With That Public License (GLWTPL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Good Luck With That Public License
|Shortname |GLWTPL
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/GLWTPL.json
* https://github.com/me-shaon/GLWTPL/commit/da5f6bc734095efbacb442c0b31e33a65b9d6e85

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/GLWTPL.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "GLWTPL",
        "Good Luck With That Public License"
    ],
    "__impliedId": "GLWTPL",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "GLWTPL"
                ],
                "__impliedId": "GLWTPL"
            },
            "shortname": "GLWTPL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Good Luck With That Public License",
            "spdxDetailsURL": "http://spdx.org/licenses/GLWTPL.json",
            "_sourceURL": "https://spdx.org/licenses/GLWTPL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/me-shaon/GLWTPL/commit/da5f6bc734095efbacb442c0b31e33a65b9d6e85"
            ],
            "_implications": {
                "__impliedNames": [
                    "GLWTPL",
                    "Good Luck With That Public License"
                ],
                "__impliedId": "GLWTPL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/GLWTPL.json"
                    ],
                    [
                        null,
                        "https://github.com/me-shaon/GLWTPL/commit/da5f6bc734095efbacb442c0b31e33a65b9d6e85"
                    ]
                ]
            },
            "spdxLicenseId": "GLWTPL"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/GLWTPL.json"
        ],
        [
            null,
            "https://github.com/me-shaon/GLWTPL/commit/da5f6bc734095efbacb442c0b31e33a65b9d6e85"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/GLWTPL.svg
