== Haskell Language Report License (HaskellReport)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Haskell Language Report License
|Shortname |HaskellReport
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/HaskellReport.json
* https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://spdx.org/licenses/HaskellReport.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "HaskellReport",
        "Haskell Language Report License"
    ],
    "__impliedId": "HaskellReport",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "HaskellReport"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "HaskellReport"
                ],
                "__impliedId": "HaskellReport"
            },
            "shortname": "HaskellReport",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Haskell Language Report License",
            "spdxDetailsURL": "http://spdx.org/licenses/HaskellReport.json",
            "_sourceURL": "https://spdx.org/licenses/HaskellReport.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "HaskellReport",
                    "Haskell Language Report License"
                ],
                "__impliedId": "HaskellReport",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/HaskellReport.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License"
                    ]
                ]
            },
            "spdxLicenseId": "HaskellReport"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License",
            "GPLv3 Compat?": "Yes",
            "Short Name": "HaskellReport",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Haskell Language Report License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Haskell Language Report License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "HaskellReport"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/HaskellReport.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/HaskellReport.svg
