== IBM PowerPC Initialization and Boot Software (IBM-pibs)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |IBM PowerPC Initialization and Boot Software
|Shortname |IBM-pibs
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |True
|===

*Other Names:*

* `+scancode://ibm-pibs+`
* `+IBM PowerPC Software+`

=== Comments on (easy) usability

* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== URLs

* *Homepage:*
http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d
* *SPDX:* http://spdx.org/licenses/IBM-pibs.json
* *SPDX:* https://spdx.org/licenses/IBM-pibs.html

=== OSADL Rule

....
USE CASE Source code delivery OR Binary delivery
	YOU MUST Provide Copyright notice (Copyright notice)
	YOU MUST Provide License text
PATENT HINTS Yes
....

(source: OSADL License Checklist)

=== Text

....
This source code has been made available to you by IBM on an AS-IS
basis.  Anyone receiving this source is licensed under IBM copyrights to
use it in any way he or she deems fit, including copying it, modifying
it, compiling it, and redistributing it either with or without
modifications.  No license under IBM patents or patent applications is
to be implied by the copyright license.

Any user of this software should understand that IBM cannot provide
technical support for this software and will not be responsible for any
consequences resulting from the use of this software.

Any person who transfers this source code or any derivative work must
include the IBM copyright notice, this paragraph, and the preceding two
paragraphs in the transferred software.

COPYRIGHT   I B M   CORPORATION 
LICENSED MATERIAL  -  PROGRAM PROPERTY OF I B M
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "IBM-pibs",
        "IBM PowerPC Initialization and Boot Software",
        "scancode://ibm-pibs",
        "IBM PowerPC Software"
    ],
    "__impliedId": "IBM-pibs",
    "__hasPatentHint": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "IBM-pibs",
                    "IBM-pibs",
                    "IBM PowerPC Initialization and Boot Software",
                    "scancode://ibm-pibs",
                    "IBM PowerPC Software"
                ],
                "__impliedId": "IBM-pibs"
            },
            "shortname": "IBM-pibs",
            "otherNames": [
                "IBM-pibs",
                "IBM PowerPC Initialization and Boot Software",
                "scancode://ibm-pibs",
                "IBM PowerPC Software"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "IBM PowerPC Initialization and Boot Software",
            "spdxDetailsURL": "http://spdx.org/licenses/IBM-pibs.json",
            "_sourceURL": "https://spdx.org/licenses/IBM-pibs.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"
            ],
            "_implications": {
                "__impliedNames": [
                    "IBM-pibs",
                    "IBM PowerPC Initialization and Boot Software"
                ],
                "__impliedId": "IBM-pibs",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/IBM-pibs.json"
                    ],
                    [
                        null,
                        "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"
                    ]
                ]
            },
            "spdxLicenseId": "IBM-pibs"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/IBM-pibs.txt",
            "spdxId": "IBM-pibs",
            "osadlRule": "USE CASE Source code delivery OR Binary delivery\n\tYOU MUST Provide Copyright notice (Copyright notice)\n\tYOU MUST Provide License text\nPATENT HINTS Yes\n",
            "_implications": {
                "__impliedNames": [
                    "IBM-pibs"
                ],
                "__hasPatentHint": true
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d",
            "shortName": "IBM PowerPC Software",
            "textUrls": null,
            "text": "This source code has been made available to you by IBM on an AS-IS\nbasis.  Anyone receiving this source is licensed under IBM copyrights to\nuse it in any way he or she deems fit, including copying it, modifying\nit, compiling it, and redistributing it either with or without\nmodifications.  No license under IBM patents or patent applications is\nto be implied by the copyright license.\n\nAny user of this software should understand that IBM cannot provide\ntechnical support for this software and will not be responsible for any\nconsequences resulting from the use of this software.\n\nAny person who transfers this source code or any derivative work must\ninclude the IBM copyright notice, this paragraph, and the preceding two\nparagraphs in the transferred software.\n\nCOPYRIGHT   I B M   CORPORATION \nLICENSED MATERIAL  -  PROGRAM PROPERTY OF I B M\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "IBM",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ibm-pibs.yml",
            "key": "ibm-pibs",
            "name": "IBM PowerPC Initialization and Boot Software",
            "spdxId": "IBM-pibs",
            "_implications": {
                "__impliedNames": [
                    "scancode://ibm-pibs",
                    "IBM PowerPC Software",
                    "IBM-pibs"
                ],
                "__impliedId": "IBM-pibs",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This source code has been made available to you by IBM on an AS-IS\nbasis.  Anyone receiving this source is licensed under IBM copyrights to\nuse it in any way he or she deems fit, including copying it, modifying\nit, compiling it, and redistributing it either with or without\nmodifications.  No license under IBM patents or patent applications is\nto be implied by the copyright license.\n\nAny user of this software should understand that IBM cannot provide\ntechnical support for this software and will not be responsible for any\nconsequences resulting from the use of this software.\n\nAny person who transfers this source code or any derivative work must\ninclude the IBM copyright notice, this paragraph, and the preceding two\nparagraphs in the transferred software.\n\nCOPYRIGHT   I B M   CORPORATION \nLICENSED MATERIAL  -  PROGRAM PROPERTY OF I B M\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/IBM-pibs.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "IBM PowerPC Initialization and Boot Software",
            "id": "IBM-pibs",
            "_implications": {
                "__impliedNames": [
                    "IBM-pibs"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/IBM-pibs.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This source code has been made available to you by IBM on an AS-IS\nbasis.  Anyone receiving this source is licensed under IBM copyrights to\nuse it in any way he or she deems fit, including copying it, modifying\nit, compiling it, and redistributing it either with or without\nmodifications.  No license under IBM patents or patent applications is\nto be implied by the copyright license.\n\nAny user of this software should understand that IBM cannot provide\ntechnical support for this software and will not be responsible for any\nconsequences resulting from the use of this software.\n\nAny person who transfers this source code or any derivative work must\ninclude the IBM copyright notice, this paragraph, and the preceding two\nparagraphs in the transferred software.\n\nCOPYRIGHT   I B M   CORPORATION \nLICENSED MATERIAL  -  PROGRAM PROPERTY OF I B M\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/IBM-pibs.json"
        ],
        [
            null,
            "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/IBM-pibs.html"
        ],
        [
            "Homepage",
            "http://git.denx.de/?p=u-boot.git;a=blob;f=arch/powerpc/cpu/ppc4xx/miiphy.c;h=297155fdafa064b955e53e9832de93bfb0cfb85b;hb=9fab4bf4cc077c21e43941866f3f2c196f28670d"
        ]
    ]
}
....