== ICU License (ICU)

[cols=",",options="header",]
|==========================
|Key |Value
|Fullname |ICU License
|Shortname |ICU
|Rating |Go
|Classification |NoCopyleft
|==========================

*Other Names:*

* `x11`
* `X11 License`
* `X11`
* `x11-xconsortium`
* `X11-Style (X Consortium)`

=== Comments on (easy) usability

* *↑* Rating is: Bronze (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== URLs

* *Homepage:* http://www.xfree86.org/3.3.6/COPYRIGHT2.html
* *Homepage:* http://www.xfree86.org/current/LICENSE5.html
* *SPDX:* http://spdx.org/licenses/ICU.json
* *SPDX:* http://spdx.org/licenses/X11.json
* *SPDX:* https://spdx.org/licenses/ICU.html
* *SPDX:* https://spdx.org/licenses/X11.html
* http://source.icu-project.org/repos/icu/icu/trunk/license.html
* http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3

=== OSADL Rule

....
USE CASE Source code delivery OR Binary delivery
	YOU MUST Forward Copyright notices
	YOU MUST Forward License text
	YOU MUST Provide Copyright notices In Documentation
	YOU MUST Provide License text In Documentation
	YOU MUST NOT Promote
....

=== Text

....
Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, provided that the above copyright
notice(s) and this permission notice appear in all copies of the Software and that
both the above copyright notice(s) and this permission notice appear in supporting
documentation.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE
COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY
SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall not be used
in advertising or otherwise to promote the sale, use or other dealings in this
Software without prior written authorization of the copyright holder.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "ICU",
        "ICU License",
        "x11",
        "X11 License",
        "X11",
        "x11-xconsortium",
        "X11-Style (X Consortium)"
    ],
    "__impliedId": "ICU",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ICU",
                    "ICU",
                    "ICU License",
                    "x11",
                    "X11 License"
                ],
                "__impliedId": "ICU"
            },
            "shortname": "ICU",
            "otherNames": [
                "ICU",
                "ICU License",
                "x11",
                "X11 License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "ICU License",
            "spdxDetailsURL": "http://spdx.org/licenses/ICU.json",
            "_sourceURL": "https://spdx.org/licenses/ICU.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "ICU",
                    "ICU License"
                ],
                "__impliedId": "ICU",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ICU.json"
                    ],
                    [
                        null,
                        "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "ICU"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/ICU.txt",
            "spdxId": "ICU",
            "osadlRule": "USE CASE Source code delivery OR Binary delivery\r\n\tYOU MUST Forward Copyright notices\n\tYOU MUST Forward License text\n\tYOU MUST Provide Copyright notices In Documentation\n\tYOU MUST Provide License text In Documentation\n\tYOU MUST NOT Promote\n",
            "_implications": {
                "__impliedNames": [
                    "ICU"
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://source.icu-project.org/repos/icu/icu/trunk/license.html",
                "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3",
                "http://www.xfree86.org/current/LICENSE5.html"
            ],
            "homepageUrl": "http://www.xfree86.org/3.3.6/COPYRIGHT2.html",
            "shortName": "X11 License",
            "textUrls": null,
            "text": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, and/or sell copies of the Software, and to permit persons\nto whom the Software is furnished to do so, provided that the above copyright\nnotice(s) and this permission notice appear in all copies of the Software and that\nboth the above copyright notice(s) and this permission notice appear in supporting\ndocumentation.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE\nCOPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY\nSPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM\nLOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER\nTORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS\nSOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall not be used\nin advertising or otherwise to promote the sale, use or other dealings in this\nSoftware without prior written authorization of the copyright holder.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "XFree86 Project, Inc",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11.yml",
            "key": "x11",
            "name": "X11 License",
            "spdxId": "ICU",
            "_implications": {
                "__impliedNames": [
                    "x11",
                    "X11 License",
                    "ICU"
                ],
                "__impliedId": "ICU",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, and/or sell copies of the Software, and to permit persons\nto whom the Software is furnished to do so, provided that the above copyright\nnotice(s) and this permission notice appear in all copies of the Software and that\nboth the above copyright notice(s) and this permission notice appear in supporting\ndocumentation.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE\nCOPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY\nSPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM\nLOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER\nTORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS\nSOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall not be used\nin advertising or otherwise to promote the sale, use or other dealings in this\nSoftware without prior written authorization of the copyright holder.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.xfree86.org/3.3.6/COPYRIGHT2.html"
                    ],
                    [
                        null,
                        "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
                    ],
                    [
                        null,
                        "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"
                    ],
                    [
                        null,
                        "http://www.xfree86.org/current/LICENSE5.html"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/ICU.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "ICU License",
            "id": "ICU",
            "_implications": {
                "__impliedNames": [
                    "ICU"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ICU.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, and/or sell copies of the Software, and to permit persons\nto whom the Software is furnished to do so, provided that the above copyright\nnotice(s) and this permission notice appear in all copies of the Software and that\nboth the above copyright notice(s) and this permission notice appear in supporting\ndocumentation.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE\nCOPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY\nSPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM\nLOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER\nTORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS\nSOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall not be used\nin advertising or otherwise to promote the sale, use or other dealings in this\nSoftware without prior written authorization of the copyright holder.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ICU.json"
        ],
        [
            null,
            "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/X11.json"
        ],
        [
            null,
            "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ICU.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/X11.html"
        ],
        [
            "Homepage",
            "http://www.xfree86.org/3.3.6/COPYRIGHT2.html"
        ],
        [
            null,
            "http://www.xfree86.org/current/LICENSE5.html"
        ],
        [
            "Homepage",
            "http://www.xfree86.org/current/LICENSE5.html"
        ]
    ]
}
....