== ICU License (ICU)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |ICU License
|Shortname |ICU
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+X11+`
* `+X11 License+`
* `+scancode://x11-xconsortium+`
* `+X11-Style (X Consortium)+`
* `+scancode://x11+`
* `+ICU License (ICU 1.8.1 and later)+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *Homepage:* http://www.xfree86.org/current/LICENSE5.html
* *Homepage:* http://www.xfree86.org/3.3.6/COPYRIGHT2.html
* *SPDX:* http://spdx.org/licenses/ICU.json
* *SPDX:* http://spdx.org/licenses/X11.json
* *SPDX:* https://spdx.org/licenses/ICU.html
* *SPDX:* https://spdx.org/licenses/X11.html
* *open-license:* http://open-license.hitachi.com/licenses/297
* http://source.icu-project.org/repos/icu/icu/trunk/license.html
* http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3

=== Description from open-license

....
Description: Relevant documentation for the software should be treated in the same way as for the software.
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved object code (Use the fetched code as it is.)
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use the object code generated from the modified source code
- Use binaries generated from modified source code
- Use the retrieved executable (Use the obtained executable as is.)
- Use the executable generated from the modified source code

Conditions: None
....

....
Description: Relevant documentation and accompanying documents for the software will be treated in the same way as the software. The same rights will be granted to those to whom the software is provided.
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribute the obtained object code (Redistribute the code as it was obtained)
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribution of Modified Source Code
- Distribute the object code generated from the modified source code
- Distribute the generated binaries from modified source code
- Selling Software
- Distribute the obtained executable (Redistribute the obtained executable as-is)
- Distribute the executable generated from the modified source code
- Publish the modified source code.
- Present the object code generated from the modified source code.
- Present the executable generated from the modified source code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license
....

....
Description: With permission of the copyright owner.
Actions:
- Use the copyright holder's name in software promotions and advertisements

Conditions:
REQUISITE: Get special permission in writing.
....

(source: Hitachi open-license)

=== Text

....
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE X CONSORTIUM
BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of the X Consortium shall not be
used in advertising or otherwise to promote the sale, use or other dealings in
this Software without prior written authorization from the X Consortium.

X Window System is a trademark of X Consortium, Inc.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/ICU.html[SPDX] (all data [in this
repository] is generated)
* https://spdx.org/licenses/X11.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-xconsortium.yml[Scancode]
(CC0-1.0)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11.yml[Scancode]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "X11",
        "ICU",
        "ICU License",
        "X11 License",
        "scancode://x11-xconsortium",
        "X11-Style (X Consortium)",
        "scancode://x11",
        "ICU License (ICU 1.8.1 and later)"
    ],
    "__impliedId": "ICU",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "X11"
                ],
                "__impliedId": "X11"
            },
            "shortname": "X11",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "ICU License",
            "spdxDetailsURL": "http://spdx.org/licenses/ICU.json",
            "_sourceURL": "https://spdx.org/licenses/ICU.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "ICU",
                    "ICU License"
                ],
                "__impliedId": "ICU",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ICU.json"
                    ],
                    [
                        null,
                        "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "ICU"
        },
        "Scancode": {
            "otherUrls": [
                "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"
            ],
            "homepageUrl": "http://www.xfree86.org/current/LICENSE5.html",
            "shortName": "X11-Style (X Consortium)",
            "textUrls": null,
            "text": "Permission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \"Software\"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE X CONSORTIUM\nBE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF\nCONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nExcept as contained in this notice, the name of the X Consortium shall not be\nused in advertising or otherwise to promote the sale, use or other dealings in\nthis Software without prior written authorization from the X Consortium.\n\nX Window System is a trademark of X Consortium, Inc.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "X Consortium",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-xconsortium.yml",
            "key": "x11-xconsortium",
            "name": "X11-Style (X Consortium)",
            "spdxId": "X11",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://x11-xconsortium",
                    "X11-Style (X Consortium)",
                    "X11"
                ],
                "__impliedId": "X11",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \"Software\"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE X CONSORTIUM\nBE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF\nCONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nExcept as contained in this notice, the name of the X Consortium shall not be\nused in advertising or otherwise to promote the sale, use or other dealings in\nthis Software without prior written authorization from the X Consortium.\n\nX Window System is a trademark of X Consortium, Inc.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.xfree86.org/current/LICENSE5.html"
                    ],
                    [
                        null,
                        "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "notices": [
                {
                    "content": "the software is provided \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, and non-infringement. the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the warranties of commercial applicability, fitness for a particular purpose, and non-infringement.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "In no event shall the copyright holder be liable for any claim, special, indirect or consequential damages, whether in contract, negligence or other tort action, arising out of the use or performance of such software, or for any damages resulting from loss of use, loss of data or loss of profits."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/297",
            "content": "COPYRIGHT AND PERMISSION NOTICE\n\nCopyright (c) <years> International Business Machines Corporation and others \n\nAll rights reserved. \n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation. \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. \n\nExcept as contained in this notice, the name of a copyright holder shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization of the copyright holder.",
            "name": "ICU License (ICU 1.8.1 and later)",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved object code",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use the object code generated from the modified source code"
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        },
                        {
                            "name": "Use the retrieved executable",
                            "description": "Use the obtained executable as is."
                        },
                        {
                            "name": "Use the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: Relevant documentation for the software should be treated in the same way as for the software.\nActions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved object code (Use the fetched code as it is.)\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use the object code generated from the modified source code\n- Use binaries generated from modified source code\n- Use the retrieved executable (Use the obtained executable as is.)\n- Use the executable generated from the modified source code\n\nConditions: None\n",
                    "conditions": null,
                    "description": "Relevant documentation for the software should be treated in the same way as for the software."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the obtained object code",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        },
                        {
                            "name": "Distribute the object code generated from the modified source code"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        },
                        {
                            "name": "Selling Software"
                        },
                        {
                            "name": "Distribute the obtained executable",
                            "description": "Redistribute the obtained executable as-is"
                        },
                        {
                            "name": "Distribute the executable generated from the modified source code"
                        },
                        {
                            "name": "Publish the modified source code."
                        },
                        {
                            "name": "Present the object code generated from the modified source code."
                        },
                        {
                            "name": "Present the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: Relevant documentation and accompanying documents for the software will be treated in the same way as the software. The same rights will be granted to those to whom the software is provided.\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribute the obtained object code (Redistribute the code as it was obtained)\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribution of Modified Source Code\n- Distribute the object code generated from the modified source code\n- Distribute the generated binaries from modified source code\n- Selling Software\n- Distribute the obtained executable (Redistribute the obtained executable as-is)\n- Distribute the executable generated from the modified source code\n- Publish the modified source code.\n- Present the object code generated from the modified source code.\n- Present the executable generated from the modified source code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                        "type": "OBLIGATION"
                    },
                    "description": "Relevant documentation and accompanying documents for the software will be treated in the same way as the software. The same rights will be granted to those to whom the software is provided."
                },
                {
                    "actions": [
                        {
                            "name": "Use the copyright holder's name in software promotions and advertisements"
                        }
                    ],
                    "_str": "Description: With permission of the copyright owner.\nActions:\n- Use the copyright holder's name in software promotions and advertisements\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "With permission of the copyright owner."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "ICU License (ICU 1.8.1 and later)",
                    "ICU"
                ],
                "__impliedText": "COPYRIGHT AND PERMISSION NOTICE\n\nCopyright (c) <years> International Business Machines Corporation and others \n\nAll rights reserved. \n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, provided that the above copyright notice(s) and this permission notice appear in all copies of the Software and that both the above copyright notice(s) and this permission notice appear in supporting documentation. \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. \n\nExcept as contained in this notice, the name of a copyright holder shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization of the copyright holder.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/297"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/ICU.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "ICU License",
            "id": "ICU",
            "_implications": {
                "__impliedNames": [
                    "ICU",
                    "ICU License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ICU.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \"Software\"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE X CONSORTIUM\nBE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF\nCONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nExcept as contained in this notice, the name of the X Consortium shall not be\nused in advertising or otherwise to promote the sale, use or other dealings in\nthis Software without prior written authorization from the X Consortium.\n\nX Window System is a trademark of X Consortium, Inc.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ICU.json"
        ],
        [
            null,
            "http://source.icu-project.org/repos/icu/icu/trunk/license.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/X11.json"
        ],
        [
            null,
            "http://www.xfree86.org/3.3.6/COPYRIGHT2.html#3"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ICU.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/X11.html"
        ],
        [
            "Homepage",
            "http://www.xfree86.org/current/LICENSE5.html"
        ],
        [
            "Homepage",
            "http://www.xfree86.org/3.3.6/COPYRIGHT2.html"
        ],
        [
            null,
            "http://www.xfree86.org/current/LICENSE5.html"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/297"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/ICU.svg