== Imlib2 License (Imlib2)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Imlib2 License
|Shortname |Imlib2
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

*Other Names:*

* `+scancode://imlib2+`

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *Homepage:*
http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING
* *SPDX:* http://spdx.org/licenses/Imlib2.json
* *open-license:* http://open-license.hitachi.com/licenses/1561
* https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING

=== Text

....
Imlib2 License 

Permission is hereby granted, free of charge, to any person obtaining a copy 
of this software and associated documentation files (the "Software"), to 
deal in the Software without restriction, including without limitation the 
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or 
sell copies of the Software, and to permit persons to whom the Software is 
furnished to do so, subject to the following conditions: 

The above copyright notice and this permission notice shall be included in 
all copies of the Software and its Copyright notices. In addition publicly 
documented acknowledgment must be given that this software has been used if no 
source code of this software is made available publicly. Making the source 
available publicly means including the source for this software with the 
distribution, or a method to get this software via some reasonable mechanism 
(electronic transfer via a network or media) as well as making an offer to 
supply the source on request. This Copyright notice serves as an offer to 
supply the source on on request as well. Instead of this, supplying 
acknowledgments of use of this software in either Copyright notices, Manuals, 
Publicity and Marketing documents or any documentation provided with any 
product containing this software. This License does not apply to any software 
that links to the libraries provided by this software (statically or 
dynamically), but only to the software provided. 

Please see the COPYING-PLAIN for a plain-english explanation of this notice 
and its intent. 

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/Imlib2.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/imlib2.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Imlib2",
        "Imlib2 License",
        "scancode://imlib2"
    ],
    "__impliedId": "Imlib2",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Imlib2"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Imlib2"
                ],
                "__impliedId": "Imlib2"
            },
            "shortname": "Imlib2",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Imlib2 License",
            "spdxDetailsURL": "http://spdx.org/licenses/Imlib2.json",
            "_sourceURL": "https://spdx.org/licenses/Imlib2.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING",
                "https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING"
            ],
            "_implications": {
                "__impliedNames": [
                    "Imlib2",
                    "Imlib2 License"
                ],
                "__impliedId": "Imlib2",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Imlib2.json"
                    ],
                    [
                        null,
                        "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING"
                    ],
                    [
                        null,
                        "https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING"
                    ]
                ]
            },
            "spdxLicenseId": "Imlib2"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Imlib2",
            "GPLv3 Compat?": "Yes",
            "Short Name": "Imlib2",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Imlib2 License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Imlib2 License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Imlib2"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING"
            ],
            "homepageUrl": "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING",
            "shortName": "Imlib2 License",
            "textUrls": null,
            "text": "Imlib2 License \n\nPermission is hereby granted, free of charge, to any person obtaining a copy \nof this software and associated documentation files (the \"Software\"), to \ndeal in the Software without restriction, including without limitation the \nrights to use, copy, modify, merge, publish, distribute, sublicense, and/or \nsell copies of the Software, and to permit persons to whom the Software is \nfurnished to do so, subject to the following conditions: \n\nThe above copyright notice and this permission notice shall be included in \nall copies of the Software and its Copyright notices. In addition publicly \ndocumented acknowledgment must be given that this software has been used if no \nsource code of this software is made available publicly. Making the source \navailable publicly means including the source for this software with the \ndistribution, or a method to get this software via some reasonable mechanism \n(electronic transfer via a network or media) as well as making an offer to \nsupply the source on request. This Copyright notice serves as an offer to \nsupply the source on on request as well. Instead of this, supplying \nacknowledgments of use of this software in either Copyright notices, Manuals, \nPublicity and Marketing documents or any documentation provided with any \nproduct containing this software. This License does not apply to any software \nthat links to the libraries provided by this software (statically or \ndynamically), but only to the software provided. \n\nPlease see the COPYING-PLAIN for a plain-english explanation of this notice \nand its intent. \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL \nTHE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER \nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN \nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
            "category": "Copyleft Limited",
            "osiUrl": null,
            "owner": "Enlightenment",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/imlib2.yml",
            "key": "imlib2",
            "name": "Imlib2 License",
            "spdxId": "Imlib2",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://imlib2",
                    "Imlib2 License",
                    "Imlib2"
                ],
                "__impliedId": "Imlib2",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft",
                "__impliedText": "Imlib2 License \n\nPermission is hereby granted, free of charge, to any person obtaining a copy \nof this software and associated documentation files (the \"Software\"), to \ndeal in the Software without restriction, including without limitation the \nrights to use, copy, modify, merge, publish, distribute, sublicense, and/or \nsell copies of the Software, and to permit persons to whom the Software is \nfurnished to do so, subject to the following conditions: \n\nThe above copyright notice and this permission notice shall be included in \nall copies of the Software and its Copyright notices. In addition publicly \ndocumented acknowledgment must be given that this software has been used if no \nsource code of this software is made available publicly. Making the source \navailable publicly means including the source for this software with the \ndistribution, or a method to get this software via some reasonable mechanism \n(electronic transfer via a network or media) as well as making an offer to \nsupply the source on request. This Copyright notice serves as an offer to \nsupply the source on on request as well. Instead of this, supplying \nacknowledgments of use of this software in either Copyright notices, Manuals, \nPublicity and Marketing documents or any documentation provided with any \nproduct containing this software. This License does not apply to any software \nthat links to the libraries provided by this software (statically or \ndynamically), but only to the software provided. \n\nPlease see the COPYING-PLAIN for a plain-english explanation of this notice \nand its intent. \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL \nTHE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER \nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN \nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING"
                    ],
                    [
                        null,
                        "https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "_license_uri": "http://open-license.hitachi.com/licenses/1561",
            "_license_permissions": [
                {
                    "_permission_summary": "",
                    "_permission_description": "Relevant documentation for the software should be treated in the same way as for the software.",
                    "_permission_conditionHead": null,
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Use the fetched code as it is.",
                            "_action_uri": "http://open-license.hitachi.com/actions/1",
                            "_action_id": "actions/1",
                            "_action_name": "Use the obtained source code without modification"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/3",
                            "_action_id": "actions/3",
                            "_action_name": "Modify the obtained source code."
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/4",
                            "_action_id": "actions/4",
                            "_action_name": "Using Modified Source Code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Use the fetched code as it is.",
                            "_action_uri": "http://open-license.hitachi.com/actions/5",
                            "_action_id": "actions/5",
                            "_action_name": "Use the retrieved object code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/7",
                            "_action_id": "actions/7",
                            "_action_name": "Use the object code generated from the modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Use the obtained executable as is.",
                            "_action_uri": "http://open-license.hitachi.com/actions/84",
                            "_action_id": "actions/84",
                            "_action_name": "Use the retrieved executable"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/87",
                            "_action_id": "actions/87",
                            "_action_name": "Use the executable generated from the modified source code"
                        }
                    ]
                },
                {
                    "_permission_summary": "",
                    "_permission_description": "The relevant documentation for the software will be treated in the same way as the software. The same rights will be granted to those to whom the software is provided.",
                    "_permission_conditionHead": {
                        "AND": [
                            {
                                "_condition_uri": "http://open-license.hitachi.com/conditions/191",
                                "_condition_id": "conditions/191",
                                "_condition_name": "Include copyright notice, trademark notice, list of terms and conditions, and disclaimer included in the license",
                                "_condition_description": "",
                                "_condition_schemaVersion": "0.1",
                                "_condition_baseUri": "http://open-license.hitachi.com/",
                                "_condition_conditionType": "OBLIGATION"
                            }
                        ]
                    },
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Redistribute the code as it was obtained",
                            "_action_uri": "http://open-license.hitachi.com/actions/9",
                            "_action_id": "actions/9",
                            "_action_name": "Distribute the obtained source code without modification"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/12",
                            "_action_id": "actions/12",
                            "_action_name": "Distribution of Modified Source Code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/19",
                            "_action_id": "actions/19",
                            "_action_name": "Sublicense the acquired source code."
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/25",
                            "_action_id": "actions/25",
                            "_action_name": "Sublicensing Modified Source Code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/90",
                            "_action_id": "actions/90",
                            "_action_name": "Publish the modified source code."
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Publish the source code as it was obtained.",
                            "_action_uri": "http://open-license.hitachi.com/actions/403",
                            "_action_id": "actions/403",
                            "_action_name": "Publish the acquired source code."
                        }
                    ]
                },
                {
                    "_permission_summary": "",
                    "_permission_description": "The relevant documentation for the software will be treated in the same way as the software. The same rights will be granted to those to whom the software is provided. Acknowledgements should be included in any copyright notices, manuals, advertising or promotional documents, or accompanying documentation for products containing the software. The acknowledgment should state that the software is being used.",
                    "_permission_conditionHead": {
                        "AND": [
                            {
                                "_condition_uri": "http://open-license.hitachi.com/conditions/191",
                                "_condition_id": "conditions/191",
                                "_condition_name": "Include copyright notice, trademark notice, list of terms and conditions, and disclaimer included in the license",
                                "_condition_description": "",
                                "_condition_schemaVersion": "0.1",
                                "_condition_baseUri": "http://open-license.hitachi.com/",
                                "_condition_conditionType": "OBLIGATION"
                            },
                            {
                                "OR": [
                                    {
                                        "_condition_uri": "http://open-license.hitachi.com/conditions/13",
                                        "_condition_id": "conditions/13",
                                        "_condition_name": "Acknowledgements",
                                        "_condition_description": "",
                                        "_condition_schemaVersion": "0.1",
                                        "_condition_baseUri": "http://open-license.hitachi.com/",
                                        "_condition_conditionType": "OBLIGATION"
                                    },
                                    {
                                        "OR": [
                                            {
                                                "_condition_uri": "http://open-license.hitachi.com/conditions/21",
                                                "_condition_id": "conditions/21",
                                                "_condition_name": "Attach the source code corresponding to the software in question.",
                                                "_condition_description": "",
                                                "_condition_schemaVersion": "0.1",
                                                "_condition_baseUri": "http://open-license.hitachi.com/",
                                                "_condition_conditionType": "OBLIGATION"
                                            },
                                            {
                                                "_condition_uri": "http://open-license.hitachi.com/conditions/87",
                                                "_condition_id": "conditions/87",
                                                "_condition_name": "Communicate that the corresponding source code for the software is available on media commonly used for software interchange and in a reasonable manner.",
                                                "_condition_description": "",
                                                "_condition_schemaVersion": "0.1",
                                                "_condition_baseUri": "http://open-license.hitachi.com/",
                                                "_condition_conditionType": "OBLIGATION"
                                            },
                                            {
                                                "_condition_uri": "http://open-license.hitachi.com/conditions/624",
                                                "_condition_id": "conditions/624",
                                                "_condition_name": "Provide source code for the software upon request",
                                                "_condition_description": "",
                                                "_condition_schemaVersion": "0.1",
                                                "_condition_baseUri": "http://open-license.hitachi.com/",
                                                "_condition_conditionType": "OBLIGATION"
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Redistribute the code as it was obtained",
                            "_action_uri": "http://open-license.hitachi.com/actions/10",
                            "_action_id": "actions/10",
                            "_action_name": "Distribute the obtained object code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/13",
                            "_action_id": "actions/13",
                            "_action_name": "Distribute the object code generated from the modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/22",
                            "_action_id": "actions/22",
                            "_action_name": "Sublicense the acquired object code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/28",
                            "_action_id": "actions/28",
                            "_action_name": "Sublicense the object code generated from the modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/35",
                            "_action_id": "actions/35",
                            "_action_name": "Selling Software"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Redistribute the obtained executable as-is",
                            "_action_uri": "http://open-license.hitachi.com/actions/86",
                            "_action_id": "actions/86",
                            "_action_name": "Distribute the obtained executable"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/89",
                            "_action_id": "actions/89",
                            "_action_name": "Distribute the executable generated from the modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/91",
                            "_action_id": "actions/91",
                            "_action_name": "Present the object code generated from the modified source code."
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/92",
                            "_action_id": "actions/92",
                            "_action_name": "Present the executable generated from the modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/106",
                            "_action_id": "actions/106",
                            "_action_name": "Sublicense the acquired executable"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.",
                            "_action_uri": "http://open-license.hitachi.com/actions/109",
                            "_action_id": "actions/109",
                            "_action_name": "Sublicense the generated executable from modified source code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Publish the fetched object code as it is.",
                            "_action_uri": "http://open-license.hitachi.com/actions/404",
                            "_action_id": "actions/404",
                            "_action_name": "Publish the retrieved object code"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_action_description": "Publish the obtained executable as is.",
                            "_action_uri": "http://open-license.hitachi.com/actions/406",
                            "_action_id": "actions/406",
                            "_action_name": "Present the obtained executables."
                        }
                    ]
                }
            ],
            "_license_id": "licenses/1561",
            "_sourceURL": "http://open-license.hitachi.com/licenses/1561",
            "_license_name": "Imlib2 License",
            "_license_summary": "https://git.enlightenment.org/legacy/imlib2.git/tree/ and https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING",
            "_license_content": "Permission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to\r\ndeal in the Software without restriction, including without limitation the\r\nrights to use, copy, modify, merge, publish, distribute, sublicense, and/or\r\nsell copies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in\r\nall copies of the Software and its Copyright notices. In addition publicly\r\ndocumented acknowledgment must be given that this software has been used if no\r\nsource code of this software is made available publicly. Making the source\r\navailable publicly means including the source for this software with the\r\ndistribution, or a method to get this software via some reasonable mechanism\r\n(electronic transfer via a network or media) as well as making an offer to\r\nsupply the source on request. This Copyright notice serves as an offer to\r\nsupply the source on on request as well. Instead of this, supplying\r\nacknowledgments of use of this software in either Copyright notices, Manuals,\r\nPublicity and Marketing documents or any documentation provided with any\r\nproduct containing this software. This License does not apply to any software\r\nthat links to the libraries provided by this software (statically or\r\ndynamically), but only to the software provided.\r\n\r\nPlease see the COPYING-PLAIN for a plain-english explanation of this notice\r\nand its intent.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\r\nTHE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER \r\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\r\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
            "_license_notices": [
                {
                    "_notice_description": "",
                    "_notice_content": "This license applies only to such software and does not apply to any software that links (whether static or dynamic) to the libraries provided by such software.",
                    "_notice_baseUri": "http://open-license.hitachi.com/",
                    "_notice_schemaVersion": "0.1",
                    "_notice_uri": "http://open-license.hitachi.com/notices/850",
                    "_notice_id": "notices/850"
                },
                {
                    "_notice_description": "There is no guarantee.",
                    "_notice_content": "the software is provided \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, and non-infringement. the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the warranties of commercial applicability, fitness for a particular purpose, and non-infringement.",
                    "_notice_baseUri": "http://open-license.hitachi.com/",
                    "_notice_schemaVersion": "0.1",
                    "_notice_uri": "http://open-license.hitachi.com/notices/3",
                    "_notice_id": "notices/3"
                },
                {
                    "_notice_description": "",
                    "_notice_content": "The author shall not be liable for any claims, damages or otherwise arising out of the use or other treatment of such software, whether in contract, negligence or other tort action.",
                    "_notice_baseUri": "http://open-license.hitachi.com/",
                    "_notice_schemaVersion": "0.1",
                    "_notice_uri": "http://open-license.hitachi.com/notices/725",
                    "_notice_id": "notices/725"
                }
            ],
            "_license_description": "",
            "_license_baseUri": "http://open-license.hitachi.com/",
            "_license_schemaVersion": "0.1",
            "_implications": {
                "__impliedNames": [
                    "Imlib2 License"
                ],
                "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy\r\nof this software and associated documentation files (the \"Software\"), to\r\ndeal in the Software without restriction, including without limitation the\r\nrights to use, copy, modify, merge, publish, distribute, sublicense, and/or\r\nsell copies of the Software, and to permit persons to whom the Software is\r\nfurnished to do so, subject to the following conditions:\r\n\r\nThe above copyright notice and this permission notice shall be included in\r\nall copies of the Software and its Copyright notices. In addition publicly\r\ndocumented acknowledgment must be given that this software has been used if no\r\nsource code of this software is made available publicly. Making the source\r\navailable publicly means including the source for this software with the\r\ndistribution, or a method to get this software via some reasonable mechanism\r\n(electronic transfer via a network or media) as well as making an offer to\r\nsupply the source on request. This Copyright notice serves as an offer to\r\nsupply the source on on request as well. Instead of this, supplying\r\nacknowledgments of use of this software in either Copyright notices, Manuals,\r\nPublicity and Marketing documents or any documentation provided with any\r\nproduct containing this software. This License does not apply to any software\r\nthat links to the libraries provided by this software (statically or\r\ndynamically), but only to the software provided.\r\n\r\nPlease see the COPYING-PLAIN for a plain-english explanation of this notice\r\nand its intent.\r\n\r\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\r\nTHE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER \r\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\r\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/1561"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Imlib2 License \n\nPermission is hereby granted, free of charge, to any person obtaining a copy \nof this software and associated documentation files (the \"Software\"), to \ndeal in the Software without restriction, including without limitation the \nrights to use, copy, modify, merge, publish, distribute, sublicense, and/or \nsell copies of the Software, and to permit persons to whom the Software is \nfurnished to do so, subject to the following conditions: \n\nThe above copyright notice and this permission notice shall be included in \nall copies of the Software and its Copyright notices. In addition publicly \ndocumented acknowledgment must be given that this software has been used if no \nsource code of this software is made available publicly. Making the source \navailable publicly means including the source for this software with the \ndistribution, or a method to get this software via some reasonable mechanism \n(electronic transfer via a network or media) as well as making an offer to \nsupply the source on request. This Copyright notice serves as an offer to \nsupply the source on on request as well. Instead of this, supplying \nacknowledgments of use of this software in either Copyright notices, Manuals, \nPublicity and Marketing documents or any documentation provided with any \nproduct containing this software. This License does not apply to any software \nthat links to the libraries provided by this software (statically or \ndynamically), but only to the software provided. \n\nPlease see the COPYING-PLAIN for a plain-english explanation of this notice \nand its intent. \n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL \nTHE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER \nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN \nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Imlib2.json"
        ],
        [
            null,
            "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING"
        ],
        [
            null,
            "https://git.enlightenment.org/legacy/imlib2.git/tree/COPYING"
        ],
        [
            "Homepage",
            "http://trac.enlightenment.org/e/browser/trunk/imlib2/COPYING"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/1561"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Imlib2.svg