== Info-ZIP License (Info-ZIP)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Info-ZIP License
|Shortname |Info-ZIP
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `Info-ZIP license (version 2009-Jan-02)`
* `Info-ZIP copyright and license (version 2005-Feb-10)`
* `Info-ZIP license (Version 2007-Mar-04)`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``This applies to all source code from
http://www.info-zip.org/pub/infozip/license.html明示されているものを除き,
Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05
or later.'' (source: https://github.com/Hitachi/open-license[Hitachi
open-license] (CDLA-Permissive-1.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/Info-ZIP.html
* *SPDX:* http://spdx.org/licenses/Info-ZIP.json
* *open-license:* http://open-license.hitachi.com/licenses/365
* *open-license:* http://open-license.hitachi.com/licenses/830
* *open-license:* http://open-license.hitachi.com/licenses/1694
* http://www.info-zip.org/license.html

=== Description from open-license

(source: Hitachi open-license)

=== Text

....
This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.

Copyright (c) 1990-2009 Info-ZIP. All rights reserved. 

For the purposes of this copyright and license, "Info-ZIP" is defined as the following set of individuals: 


Mark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. 
This software is provided "as is," without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. 

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: 


    •Redistributions of source code (in whole or in part) must retain the above copyright notice, 
    definition, disclaimer, and this list of conditions. 

    •Redistributions in binary form (compiled executables and libraries) must reproduce 
    the above copyright notice, definition, disclaimer, and this list of conditions in documentation 
    and/or other materials provided with the distribution. Additional documentation is not needed 
    for executables where a command line license option provides these and a note regarding 
    this option is in the executable's startup banner. The sole exception to this condition 
    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a 
    self-extracting archive; that is permitted without inclusion of this license, as long as 
    the normal SFX banner has not been removed from the binary or disabled. 

    •Altered versions--including, but not limited to, ports to new operating systems, 
    existing ports with new graphical interfaces, versions with modified or added 
    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must 
    be plainly marked as such and must not be misrepresented as being the original source or, 
    if binaries, compiled from the original source. Such altered versions also must not 
    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of 
    the altered versions with the names "Info-ZIP" (or any variation thereof, including, but 
    not limited to, different capitalizations), "Pocket UnZip," "WiZ" or "MacZip" without the 
    explicit permission of Info-ZIP. Such altered versions are further prohibited from 
    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP 
    URL(s), such as to imply Info-ZIP will provide support for the altered versions. 

    •Info-ZIP retains the right to use the names "Info-ZIP," "Zip," "UnZip," 
    "UnZipSFX," "WiZ," "Pocket UnZip," "Pocket Zip," and "MacZip" for its own source and binary releases.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/Info-ZIP.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Info-ZIP",
        "Info-ZIP License",
        "Info-ZIP license (version 2009-Jan-02)",
        "Info-ZIP copyright and license (version 2005-Feb-10)",
        "Info-ZIP license (Version 2007-Mar-04)"
    ],
    "__impliedId": "Info-ZIP",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "This applies to all source code from http://www.info-zip.org/pub/infozip/license.html明示されているものを除き, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Info-ZIP"
                ],
                "__impliedId": "Info-ZIP"
            },
            "shortname": "Info-ZIP",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Info-ZIP License",
            "spdxDetailsURL": "http://spdx.org/licenses/Info-ZIP.json",
            "_sourceURL": "https://spdx.org/licenses/Info-ZIP.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.info-zip.org/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP",
                    "Info-ZIP License"
                ],
                "__impliedId": "Info-ZIP",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Info-ZIP.json"
                    ],
                    [
                        null,
                        "http://www.info-zip.org/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "Info-ZIP"
        },
        "Hitachi open-license": {
            "summary": "This applies to all source code from http://www.info-zip.org/pub/infozip/license.html明示されているものを除き, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later.",
            "notices": [],
            "_sourceURL": "http://open-license.hitachi.com/licenses/365",
            "content": "This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.\n\nCopyright (c) 1990-2009 Info-ZIP. All rights reserved. \n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals: \n\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. \nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. \n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: \n\n\n    •Redistributions of source code (in whole or in part) must retain the above copyright notice, \n    definition, disclaimer, and this list of conditions. \n\n    •Redistributions in binary form (compiled executables and libraries) must reproduce \n    the above copyright notice, definition, disclaimer, and this list of conditions in documentation \n    and/or other materials provided with the distribution. Additional documentation is not needed \n    for executables where a command line license option provides these and a note regarding \n    this option is in the executable's startup banner. The sole exception to this condition \n    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a \n    self-extracting archive; that is permitted without inclusion of this license, as long as \n    the normal SFX banner has not been removed from the binary or disabled. \n\n    •Altered versions--including, but not limited to, ports to new operating systems, \n    existing ports with new graphical interfaces, versions with modified or added \n    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must \n    be plainly marked as such and must not be misrepresented as being the original source or, \n    if binaries, compiled from the original source. Such altered versions also must not \n    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of \n    the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but \n    not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the \n    explicit permission of Info-ZIP. Such altered versions are further prohibited from \n    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP \n    URL(s), such as to imply Info-ZIP will provide support for the altered versions. \n\n    •Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \n    \"UnZipSFX,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
            "name": "Info-ZIP license (version 2009-Jan-02)",
            "permissions": [],
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP license (version 2009-Jan-02)",
                    "Info-ZIP"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "This applies to all source code from http://www.info-zip.org/pub/infozip/license.html明示されているものを除き, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later."
                        ]
                    ]
                ],
                "__impliedText": "This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.\n\nCopyright (c) 1990-2009 Info-ZIP. All rights reserved. \n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals: \n\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. \nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. \n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: \n\n\n    •Redistributions of source code (in whole or in part) must retain the above copyright notice, \n    definition, disclaimer, and this list of conditions. \n\n    •Redistributions in binary form (compiled executables and libraries) must reproduce \n    the above copyright notice, definition, disclaimer, and this list of conditions in documentation \n    and/or other materials provided with the distribution. Additional documentation is not needed \n    for executables where a command line license option provides these and a note regarding \n    this option is in the executable's startup banner. The sole exception to this condition \n    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a \n    self-extracting archive; that is permitted without inclusion of this license, as long as \n    the normal SFX banner has not been removed from the binary or disabled. \n\n    •Altered versions--including, but not limited to, ports to new operating systems, \n    existing ports with new graphical interfaces, versions with modified or added \n    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must \n    be plainly marked as such and must not be misrepresented as being the original source or, \n    if binaries, compiled from the original source. Such altered versions also must not \n    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of \n    the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but \n    not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the \n    explicit permission of Info-ZIP. Such altered versions are further prohibited from \n    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP \n    URL(s), such as to imply Info-ZIP will provide support for the altered versions. \n\n    •Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \n    \"UnZipSFX,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/365"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Info-ZIP.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Info-ZIP License",
            "id": "Info-ZIP",
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP",
                    "Info-ZIP License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Info-ZIP.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.\n\nCopyright (c) 1990-2009 Info-ZIP. All rights reserved. \n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals: \n\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. \nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. \n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: \n\n\n    •Redistributions of source code (in whole or in part) must retain the above copyright notice, \n    definition, disclaimer, and this list of conditions. \n\n    •Redistributions in binary form (compiled executables and libraries) must reproduce \n    the above copyright notice, definition, disclaimer, and this list of conditions in documentation \n    and/or other materials provided with the distribution. Additional documentation is not needed \n    for executables where a command line license option provides these and a note regarding \n    this option is in the executable's startup banner. The sole exception to this condition \n    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a \n    self-extracting archive; that is permitted without inclusion of this license, as long as \n    the normal SFX banner has not been removed from the binary or disabled. \n\n    •Altered versions--including, but not limited to, ports to new operating systems, \n    existing ports with new graphical interfaces, versions with modified or added \n    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must \n    be plainly marked as such and must not be misrepresented as being the original source or, \n    if binaries, compiled from the original source. Such altered versions also must not \n    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of \n    the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but \n    not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the \n    explicit permission of Info-ZIP. Such altered versions are further prohibited from \n    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP \n    URL(s), such as to imply Info-ZIP will provide support for the altered versions. \n\n    •Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \n    \"UnZipSFX,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Info-ZIP.html"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/365"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/830"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/1694"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Info-ZIP.json"
        ],
        [
            null,
            "http://www.info-zip.org/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Info-ZIP.svg
