== Info-ZIP License (Info-ZIP)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Info-ZIP License
|Shortname |Info-ZIP
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://info-zip+`
* `+Info-ZIP license (version 2009-Jan-02)+`
* `+Info-ZIP copyright and license (version 2005-Feb-10)+`
* `+Info-ZIP license (Version 2007-Mar-04)+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``This applies to all source code from
http://www.info-zip.org/pub/infozip/license.html明示されているものを除き,
Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05
or later.'' (source: https://github.com/Hitachi/open-license[Hitachi
open-license] (CDLA-Permissive-1.0))

=== URLs

* *Homepage:* http://www.info-zip.org/doc/
* *SPDX:* http://spdx.org/licenses/Info-ZIP.json
* *SPDX:* https://spdx.org/licenses/Info-ZIP.html
* *open-license:* http://open-license.hitachi.com/licenses/365
* *open-license:* http://open-license.hitachi.com/licenses/830
* *open-license:* http://open-license.hitachi.com/licenses/1694
* http://www.info-zip.org/license.html

=== openLicenseDesc

....
[]
....

(source: Hitachi open-license)

=== Text

....
Info-Zip License

This is version 1999-Oct-05 of the Info-ZIP copyright and license. The definitive version of this document should be available at ftp://ftp.cdrom.com/pub/infozip/license.html indefinitely.

Copyright (c) 1990-1999 Info-ZIP. All rights reserved.

For the purposes of this copyright and license, "Info-ZIP" is defined as the following set of individuals:

Mark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Christian Spieler, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White

This software is provided "as is," without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

1. Redistributions of source code must retain the above copyright notice, definition, disclaimer, and this list of conditions.

2. Redistributions in binary form must reproduce the above copyright notice, definition, disclaimer, and this list of conditions in documentation and/or other materials provided with the distribution.

3. Altered versions--including, but not limited to, ports to new operating systems, existing ports with new graphical interfaces, and dynamic, shared, or static library versions--must be plainly marked as such and must not be misrepresented as being the original source. Such altered versions also must not be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of the altered versions with the names "Info-ZIP" (or any variation thereof, including, but not limited to, different capitalizations), "Pocket UnZip," "WiZ" or "MacZip" without the explicit permission of Info-ZIP. Such altered versions are further prohibited from misrepresentative use of theZip-Bugs or Info-ZIP e-mail addresses or of the Info-ZIP URL(s).

4. Info-ZIP retains the right to use the names "Info-ZIP," "Zip," "UnZip," "WiZ," "Pocket UnZip," "Pocket Zip," and "MacZip" for its own source and binary releases.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/Info-ZIP.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/info-zip.yml[Scancode]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Info-ZIP",
        "Info-ZIP License",
        "scancode://info-zip",
        "Info-Zip License",
        "Info-ZIP license (version 2009-Jan-02)",
        "Info-ZIP copyright and license (version 2005-Feb-10)",
        "Info-ZIP license (Version 2007-Mar-04)"
    ],
    "__impliedId": "Info-ZIP",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "This applies to all source code from http://www.info-zip.org/pub/infozip/license.htmlæç¤ºããã¦ãããã®ãé¤ã, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Info-ZIP"
                ],
                "__impliedId": "Info-ZIP"
            },
            "shortname": "Info-ZIP",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Info-ZIP License",
            "spdxDetailsURL": "http://spdx.org/licenses/Info-ZIP.json",
            "_sourceURL": "https://spdx.org/licenses/Info-ZIP.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.info-zip.org/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP",
                    "Info-ZIP License"
                ],
                "__impliedId": "Info-ZIP",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Info-ZIP.json"
                    ],
                    [
                        null,
                        "http://www.info-zip.org/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "Info-ZIP"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.info-zip.org/doc/",
            "shortName": "Info-Zip License",
            "textUrls": null,
            "text": "Info-Zip License\n\nThis is version 1999-Oct-05 of the Info-ZIP copyright and license. The definitive version of this document should be available at ftp://ftp.cdrom.com/pub/infozip/license.html indefinitely.\n\nCopyright (c) 1990-1999 Info-ZIP. All rights reserved.\n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals:\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Christian Spieler, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White\n\nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n1. Redistributions of source code must retain the above copyright notice, definition, disclaimer, and this list of conditions.\n\n2. Redistributions in binary form must reproduce the above copyright notice, definition, disclaimer, and this list of conditions in documentation and/or other materials provided with the distribution.\n\n3. Altered versions--including, but not limited to, ports to new operating systems, existing ports with new graphical interfaces, and dynamic, shared, or static library versions--must be plainly marked as such and must not be misrepresented as being the original source. Such altered versions also must not be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the explicit permission of Info-ZIP. Such altered versions are further prohibited from misrepresentative use of theZip-Bugs or Info-ZIP e-mail addresses or of the Info-ZIP URL(s).\n\n4. Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "info-zip",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/info-zip.yml",
            "key": "info-zip",
            "name": "Info-Zip License",
            "spdxId": "Info-ZIP",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://info-zip",
                    "Info-Zip License",
                    "Info-ZIP"
                ],
                "__impliedId": "Info-ZIP",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Info-Zip License\n\nThis is version 1999-Oct-05 of the Info-ZIP copyright and license. The definitive version of this document should be available at ftp://ftp.cdrom.com/pub/infozip/license.html indefinitely.\n\nCopyright (c) 1990-1999 Info-ZIP. All rights reserved.\n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals:\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Christian Spieler, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White\n\nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n1. Redistributions of source code must retain the above copyright notice, definition, disclaimer, and this list of conditions.\n\n2. Redistributions in binary form must reproduce the above copyright notice, definition, disclaimer, and this list of conditions in documentation and/or other materials provided with the distribution.\n\n3. Altered versions--including, but not limited to, ports to new operating systems, existing ports with new graphical interfaces, and dynamic, shared, or static library versions--must be plainly marked as such and must not be misrepresented as being the original source. Such altered versions also must not be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the explicit permission of Info-ZIP. Such altered versions are further prohibited from misrepresentative use of theZip-Bugs or Info-ZIP e-mail addresses or of the Info-ZIP URL(s).\n\n4. Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.info-zip.org/doc/"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "This applies to all source code from http://www.info-zip.org/pub/infozip/license.htmlæç¤ºããã¦ãããã®ãé¤ã, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later.",
            "permissionsStr": "[]",
            "notices": [],
            "_sourceURL": "http://open-license.hitachi.com/licenses/365",
            "content": "This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.\r\n\r\nCopyright (c) 1990-2009 Info-ZIP. All rights reserved. \r\n\r\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals: \r\n\r\n\r\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. \r\nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. \r\n\r\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: \r\n\r\n\r\n    â¢Redistributions of source code (in whole or in part) must retain the above copyright notice, \r\n    definition, disclaimer, and this list of conditions. \r\n\r\n    â¢Redistributions in binary form (compiled executables and libraries) must reproduce \r\n    the above copyright notice, definition, disclaimer, and this list of conditions in documentation \r\n    and/or other materials provided with the distribution. Additional documentation is not needed \r\n    for executables where a command line license option provides these and a note regarding \r\n    this option is in the executable's startup banner. The sole exception to this condition \r\n    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a \r\n    self-extracting archive; that is permitted without inclusion of this license, as long as \r\n    the normal SFX banner has not been removed from the binary or disabled. \r\n\r\n    â¢Altered versions--including, but not limited to, ports to new operating systems, \r\n    existing ports with new graphical interfaces, versions with modified or added \r\n    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must \r\n    be plainly marked as such and must not be misrepresented as being the original source or, \r\n    if binaries, compiled from the original source. Such altered versions also must not \r\n    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of \r\n    the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but \r\n    not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the \r\n    explicit permission of Info-ZIP. Such altered versions are further prohibited from \r\n    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP \r\n    URL(s), such as to imply Info-ZIP will provide support for the altered versions. \r\n\r\n    â¢Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \r\n    \"UnZipSFX,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
            "name": "Info-ZIP license (version 2009-Jan-02)",
            "permissions": [],
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP license (version 2009-Jan-02)",
                    "Info-ZIP"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "This applies to all source code from http://www.info-zip.org/pub/infozip/license.htmlæç¤ºããã¦ãããã®ãé¤ã, Zip 2.3 or later, UnZip 5.41 or later, WiZ 5.0 or later, and MacZip 1.05 or later."
                        ]
                    ]
                ],
                "__impliedText": "This is version 2009-Jan-02 of the Info-ZIP license. The definitive version of this document should be available at ftp://ftp.info-zip.org/pub/infozip/license.html indefinitely and a copy at http://www.info-zip.org/pub/infozip/license.html.\r\n\r\nCopyright (c) 1990-2009 Info-ZIP. All rights reserved. \r\n\r\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals: \r\n\r\n\r\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ed Gordon, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Steven M. Schweda, Christian Spieler, Cosmin Truta, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White. \r\nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software. \r\n\r\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the above disclaimer and the following restrictions: \r\n\r\n\r\n    â¢Redistributions of source code (in whole or in part) must retain the above copyright notice, \r\n    definition, disclaimer, and this list of conditions. \r\n\r\n    â¢Redistributions in binary form (compiled executables and libraries) must reproduce \r\n    the above copyright notice, definition, disclaimer, and this list of conditions in documentation \r\n    and/or other materials provided with the distribution. Additional documentation is not needed \r\n    for executables where a command line license option provides these and a note regarding \r\n    this option is in the executable's startup banner. The sole exception to this condition \r\n    is redistribution of a standard UnZipSFX binary (including SFXWiz) as part of a \r\n    self-extracting archive; that is permitted without inclusion of this license, as long as \r\n    the normal SFX banner has not been removed from the binary or disabled. \r\n\r\n    â¢Altered versions--including, but not limited to, ports to new operating systems, \r\n    existing ports with new graphical interfaces, versions with modified or added \r\n    functionality, and dynamic, shared, or static library versions not from Info-ZIP--must \r\n    be plainly marked as such and must not be misrepresented as being the original source or, \r\n    if binaries, compiled from the original source. Such altered versions also must not \r\n    be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of \r\n    the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but \r\n    not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the \r\n    explicit permission of Info-ZIP. Such altered versions are further prohibited from \r\n    misrepresentative use of the Zip-Bugs or Info-ZIP e-mail addresses or the Info-ZIP \r\n    URL(s), such as to imply Info-ZIP will provide support for the altered versions. \r\n\r\n    â¢Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \r\n    \"UnZipSFX,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/365"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Info-ZIP.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Info-ZIP License",
            "id": "Info-ZIP",
            "_implications": {
                "__impliedNames": [
                    "Info-ZIP",
                    "Info-ZIP License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Info-ZIP.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Info-Zip License\n\nThis is version 1999-Oct-05 of the Info-ZIP copyright and license. The definitive version of this document should be available at ftp://ftp.cdrom.com/pub/infozip/license.html indefinitely.\n\nCopyright (c) 1990-1999 Info-ZIP. All rights reserved.\n\nFor the purposes of this copyright and license, \"Info-ZIP\" is defined as the following set of individuals:\n\nMark Adler, John Bush, Karl Davis, Harald Denker, Jean-Michel Dubois, Jean-loup Gailly, Hunter Goatley, Ian Gorman, Chris Herborth, Dirk Haase, Greg Hartwig, Robert Heath, Jonathan Hudson, Paul Kienitz, David Kirschbaum, Johnny Lee, Onno van der Linden, Igor Mandrichenko, Steve P. Miller, Sergio Monesi, Keith Owens, George Petrov, Greg Roelofs, Kai Uwe Rommel, Steve Salisbury, Dave Smith, Christian Spieler, Antoine Verheijen, Paul von Behren, Rich Wales, Mike White\n\nThis software is provided \"as is,\" without warranty of any kind, express or implied. In no event shall Info-ZIP or its contributors be held liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use this software.\n\nPermission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:\n\n1. Redistributions of source code must retain the above copyright notice, definition, disclaimer, and this list of conditions.\n\n2. Redistributions in binary form must reproduce the above copyright notice, definition, disclaimer, and this list of conditions in documentation and/or other materials provided with the distribution.\n\n3. Altered versions--including, but not limited to, ports to new operating systems, existing ports with new graphical interfaces, and dynamic, shared, or static library versions--must be plainly marked as such and must not be misrepresented as being the original source. Such altered versions also must not be misrepresented as being Info-ZIP releases--including, but not limited to, labeling of the altered versions with the names \"Info-ZIP\" (or any variation thereof, including, but not limited to, different capitalizations), \"Pocket UnZip,\" \"WiZ\" or \"MacZip\" without the explicit permission of Info-ZIP. Such altered versions are further prohibited from misrepresentative use of theZip-Bugs or Info-ZIP e-mail addresses or of the Info-ZIP URL(s).\n\n4. Info-ZIP retains the right to use the names \"Info-ZIP,\" \"Zip,\" \"UnZip,\" \"WiZ,\" \"Pocket UnZip,\" \"Pocket Zip,\" and \"MacZip\" for its own source and binary releases.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Info-ZIP.json"
        ],
        [
            null,
            "http://www.info-zip.org/license.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Info-ZIP.html"
        ],
        [
            "Homepage",
            "http://www.info-zip.org/doc/"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/365"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/830"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/1694"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Info-ZIP.svg