== JSON License (JSON)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |JSON License
|Shortname |JSON
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↓**``Infamous for the clause The Software shall be used for Good,
not Evil.'' (source: https://wiki.debian.org/DFSGLicenses[Debian Free
Software Guidelines] (NOASSERTION))
* **↓**``This software licenses which is NOT OKAY for Fedora. Nothing in
Fedora is permitted to use this license. It is either non-free or
deprecated.'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/JSON.json
* http://www.json.org/license.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/JSON.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "JSON",
        "JSON License"
    ],
    "__impliedId": "JSON",
    "__impliedAmbiguousNames": [
        "JSON evil license"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "JSON"
                ],
                "__impliedId": "JSON"
            },
            "shortname": "JSON",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "JSON License",
            "spdxDetailsURL": "http://spdx.org/licenses/JSON.json",
            "_sourceURL": "https://spdx.org/licenses/JSON.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.json.org/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "JSON",
                    "JSON License"
                ],
                "__impliedId": "JSON",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/JSON.json"
                    ],
                    [
                        null,
                        "http://www.json.org/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "JSON"
        },
        "Fedora Project Wiki": {
            "rating": "Bad",
            "Upstream URL": "http://www.json.org/license.html",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "JSON License",
            "FSF Free?": "No",
            "_implications": {
                "__impliedNames": [
                    "JSON License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
                        }
                    ]
                ]
            },
            "Notes": "The clause \"The Software shall be used for Good, not Evil.\" is impossible to parse or comply with."
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "JSON evil license",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "JSON"
                ],
                "__impliedAmbiguousNames": [
                    "JSON evil license"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Infamous for the clause The Software shall be used for Good, not Evil."
                        }
                    ]
                ]
            },
            "Comment": "Infamous for the clause The Software shall be used for Good, not Evil.",
            "LicenseId": "JSON"
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "JSON",
            "_implications": {
                "__impliedNames": [
                    "JSON"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "Infamous for the clause The Software shall be used for Good, not Evil."
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "NegativeJudgement",
                "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Google OSS Policy",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/JSON.json"
        ],
        [
            null,
            "http://www.json.org/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/JSON.svg
