== Licence Art Libre 1.3 (LAL-1.3)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Licence Art Libre 1.3
|Shortname |LAL-1.3
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `LAL 1.3`

=== Comments on (easy) usability

* ``It is currently unstettled whether this license is DFSG-free''
(source: https://wiki.debian.org/DFSGLicenses[Debian Free Software
Guidelines] (NOASSERTION))

=== General Comments

* ``category: LAL'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/[la]/LAL-1.3.yaml[Metaeffekt
Universe] (CC-BY-4.0))

=== URLs

* *SPDX:* https://spdx.org/licenses/LAL-1.3.json
* https://artlibre.org/

'''''

=== Raw Data

==== Facts

* LicenseName
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/[la]/LAL-1.3.yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/LAL-1.3.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "LAL-1.3",
        "LAL 1.3",
        "Licence Art Libre 1.3"
    ],
    "__impliedId": "LAL-1.3",
    "__impliedAmbiguousNames": [
        "Licence Art Libre (Free Art License)",
        "LAL, Version 1.3",
        "LAL, 1.3",
        "Licence Art Libre 1.3"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: LAL"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "LAL-1.3"
                ],
                "__impliedId": "LAL-1.3"
            },
            "shortname": "LAL-1.3",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Licence Art Libre 1.3",
            "spdxDetailsURL": "https://spdx.org/licenses/LAL-1.3.json",
            "_sourceURL": "https://spdx.org/licenses/LAL-1.3.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://artlibre.org/"
            ],
            "_implications": {
                "__impliedNames": [
                    "LAL-1.3",
                    "Licence Art Libre 1.3"
                ],
                "__impliedId": "LAL-1.3",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/LAL-1.3.json"
                    ],
                    [
                        null,
                        "https://artlibre.org/"
                    ]
                ]
            },
            "spdxLicenseId": "LAL-1.3"
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Licence Art Libre (Free Art License)",
            "State": "DFSGStateUnsettled",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "LAL-1.3"
                ],
                "__impliedAmbiguousNames": [
                    "Licence Art Libre (Free Art License)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "It is currently unstettled whether this license is DFSG-free"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "LAL-1.3"
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "LAL-1.3",
            "shortName": null,
            "category": "LAL",
            "alternativeNames": [
                "LAL, Version 1.3",
                "LAL, 1.3",
                "Licence Art Libre 1.3"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/[la]/LAL-1.3.yaml",
            "otherIds": [],
            "canonicalName": "LAL 1.3",
            "_implications": {
                "__impliedNames": [
                    "LAL 1.3",
                    "LAL-1.3"
                ],
                "__impliedId": "LAL-1.3",
                "__impliedAmbiguousNames": [
                    "LAL, Version 1.3",
                    "LAL, 1.3",
                    "Licence Art Libre 1.3"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: LAL"
                        ]
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NeutralJudgement",
                "contents": "It is currently unstettled whether this license is DFSG-free"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/LAL-1.3.json"
        ],
        [
            null,
            "https://artlibre.org/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/LAL-1.3.svg
