== PNG Reference Library version 2 (libpng-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |PNG Reference Library version 2
|Shortname |libpng-2.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/libpng-2.0.json
* http://www.libpng.org/pub/png/src/libpng-LICENSE.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/libpng-2.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "libpng-2.0",
        "PNG Reference Library version 2"
    ],
    "__impliedId": "libpng-2.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "libpng-2.0"
                ],
                "__impliedId": "libpng-2.0"
            },
            "shortname": "libpng-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "PNG Reference Library version 2",
            "spdxDetailsURL": "http://spdx.org/licenses/libpng-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/libpng-2.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.libpng.org/pub/png/src/libpng-LICENSE.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "libpng-2.0",
                    "PNG Reference Library version 2"
                ],
                "__impliedId": "libpng-2.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/libpng-2.0.json"
                    ],
                    [
                        null,
                        "http://www.libpng.org/pub/png/src/libpng-LICENSE.txt"
                    ]
                ]
            },
            "spdxLicenseId": "libpng-2.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/libpng-2.0.json"
        ],
        [
            null,
            "http://www.libpng.org/pub/png/src/libpng-LICENSE.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/libpng-2.0.svg
