== libselinux public domain notice (libselinux-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |libselinux public domain notice
|Shortname |libselinux-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/libselinux-1.0.json
* https://github.com/SELinuxProject/selinux/blob/master/libselinux/LICENSE

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "libselinux-1.0",
        "libselinux public domain notice"
    ],
    "__impliedId": "libselinux-1.0",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "libselinux public domain notice",
            "spdxDetailsURL": "http://spdx.org/licenses/libselinux-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/libselinux-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/SELinuxProject/selinux/blob/master/libselinux/LICENSE"
            ],
            "_implications": {
                "__impliedNames": [
                    "libselinux-1.0",
                    "libselinux public domain notice"
                ],
                "__impliedId": "libselinux-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/libselinux-1.0.json"
                    ],
                    [
                        null,
                        "https://github.com/SELinuxProject/selinux/blob/master/libselinux/LICENSE"
                    ]
                ]
            },
            "spdxLicenseId": "libselinux-1.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/libselinux-1.0.json"
        ],
        [
            null,
            "https://github.com/SELinuxProject/selinux/blob/master/libselinux/LICENSE"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/libselinux-1.0.svg[image,title="dot"]