== Linux Kernel Variant of OpenIB.org license (Linux-OpenIB)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Linux Kernel Variant of OpenIB.org license
|Shortname |Linux-OpenIB
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://linux-openib+`

=== Comments on (easy) usability

* **↑**``Rating is: Silver'' (source:
https://blueoakcouncil.org/list[BlueOak License List])
* ``This license is a hybrid of two common licenses the BSD-2-Clause
(bsd- simplified) and the MIT License (mit). '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/linux-openib.yml[Scancode])

=== URLs

* *Homepage:*
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h
* *SPDX:* http://spdx.org/licenses/Linux-OpenIB.json
* *SPDX:* https://spdx.org/licenses/Linux-OpenIB.html
* https://github.com/spdx/license-list-XML/issues/620
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h?id=3215b9d57a2c75c4305a3956ca303d7004485200

=== Text

....
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

- Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

- Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Linux-OpenIB",
        "Linux Kernel Variant of OpenIB.org license",
        "scancode://linux-openib"
    ],
    "__impliedId": "Linux-OpenIB",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Linux Kernel Variant of OpenIB.org license",
            "spdxDetailsURL": "http://spdx.org/licenses/Linux-OpenIB.json",
            "_sourceURL": "https://spdx.org/licenses/Linux-OpenIB.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
            ],
            "_implications": {
                "__impliedNames": [
                    "Linux-OpenIB",
                    "Linux Kernel Variant of OpenIB.org license"
                ],
                "__impliedId": "Linux-OpenIB",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Linux-OpenIB.json"
                    ],
                    [
                        null,
                        "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
                    ]
                ]
            },
            "spdxLicenseId": "Linux-OpenIB"
        },
        "Scancode": {
            "otherUrls": [
                "https://github.com/spdx/license-list-XML/issues/620",
                "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h?id=3215b9d57a2c75c4305a3956ca303d7004485200"
            ],
            "homepageUrl": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h",
            "shortName": "Linux-OpenIB",
            "textUrls": null,
            "text": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n- Redistributions of source code must retain the above copyright notice, this\n  list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright notice,\n  this list of conditions and the following disclaimer in the documentation\n  and/or other materials provided with the distribution.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Linux Foundation",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/linux-openib.yml",
            "key": "linux-openib",
            "name": "Linux-OpenIB",
            "spdxId": "Linux-OpenIB",
            "notes": "This license is a hybrid of two common licenses the BSD-2-Clause (bsd-\nsimplified) and the MIT License (mit).\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://linux-openib",
                    "Linux-OpenIB",
                    "Linux-OpenIB"
                ],
                "__impliedId": "Linux-OpenIB",
                "__impliedJudgement": [
                    [
                        "Scancode",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "This license is a hybrid of two common licenses the BSD-2-Clause (bsd-\nsimplified) and the MIT License (mit).\n"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n- Redistributions of source code must retain the above copyright notice, this\n  list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright notice,\n  this list of conditions and the following disclaimer in the documentation\n  and/or other materials provided with the distribution.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
                    ],
                    [
                        null,
                        "https://github.com/spdx/license-list-XML/issues/620"
                    ],
                    [
                        null,
                        "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h?id=3215b9d57a2c75c4305a3956ca303d7004485200"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/Linux-OpenIB.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Linux Kernel Variant of OpenIB.org license",
            "id": "Linux-OpenIB",
            "_implications": {
                "__impliedNames": [
                    "Linux-OpenIB"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Linux-OpenIB.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ],
        [
            "Scancode",
            {
                "tag": "NeutralJudgement",
                "contents": "This license is a hybrid of two common licenses the BSD-2-Clause (bsd-\nsimplified) and the MIT License (mit).\n"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n- Redistributions of source code must retain the above copyright notice, this\n  list of conditions and the following disclaimer.\n\n- Redistributions in binary form must reproduce the above copyright notice,\n  this list of conditions and the following disclaimer in the documentation\n  and/or other materials provided with the distribution.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Linux-OpenIB.json"
        ],
        [
            null,
            "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Linux-OpenIB.html"
        ],
        [
            "Homepage",
            "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
        ],
        [
            null,
            "https://github.com/spdx/license-list-XML/issues/620"
        ],
        [
            null,
            "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h?id=3215b9d57a2c75c4305a3956ca303d7004485200"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/Linux-OpenIB.svg[image,title="dot"]