== Linux Kernel Variant of OpenIB.org license (Linux-OpenIB)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Linux Kernel Variant of OpenIB.org license
|Shortname |Linux-OpenIB
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Silver'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/Linux-OpenIB.html
* *SPDX:* http://spdx.org/licenses/Linux-OpenIB.json
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/Linux-OpenIB.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Linux-OpenIB",
        "Linux Kernel Variant of OpenIB.org license"
    ],
    "__impliedId": "Linux-OpenIB",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Linux-OpenIB"
                ],
                "__impliedId": "Linux-OpenIB"
            },
            "shortname": "Linux-OpenIB",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Linux Kernel Variant of OpenIB.org license",
            "spdxDetailsURL": "http://spdx.org/licenses/Linux-OpenIB.json",
            "_sourceURL": "https://spdx.org/licenses/Linux-OpenIB.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
            ],
            "_implications": {
                "__impliedNames": [
                    "Linux-OpenIB",
                    "Linux Kernel Variant of OpenIB.org license"
                ],
                "__impliedId": "Linux-OpenIB",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Linux-OpenIB.json"
                    ],
                    [
                        null,
                        "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
                    ]
                ]
            },
            "spdxLicenseId": "Linux-OpenIB"
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/Linux-OpenIB.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Linux Kernel Variant of OpenIB.org license",
            "id": "Linux-OpenIB",
            "_implications": {
                "__impliedNames": [
                    "Linux-OpenIB",
                    "Linux Kernel Variant of OpenIB.org license"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Linux-OpenIB.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Linux-OpenIB.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Linux-OpenIB.json"
        ],
        [
            null,
            "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Linux-OpenIB.svg
