== The MirOS Licence (MirOS)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |The MirOS Licence
|Shortname |MirOS
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `MirOS License`
* `MirOS Licence`
* `The MirOS Licence (MirOS)`
* `scancode://mir-os`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/MirOS.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Permissive licence, Ⓕ Copyfree, very similar to MIT and ISC but
applicable to more than just software'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``https://opensource.org/licenses/miros.html'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``Per SPDX.org, this license is OSI certified.'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mir-os.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* https://www.mirbsd.org/MirOS-Licence
* *OSI Page:* https://opensource.org/licenses/MirOS
* *OSI Page:* http://opensource.org/licenses/miros.html
* *SPDX:* https://spdx.org/licenses/MirOS.html
* *SPDX:* http://spdx.org/licenses/MirOS.json
* *open-license:* http://open-license.hitachi.com/licenses/1554
* http://www.opensource.org/licenses/MirOS

=== Description from open-license

* {blank}
+
....
Description: Relevant documentation for the software should be treated in the same way as for the software.
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved object code (Use the fetched code as it is.)
- Use the object code generated from the modified source code
- Use the retrieved executable (Use the obtained executable as is.)
- Use the executable generated from the modified source code

Conditions: None
....
* {blank}
+
....
Description: Related documentation and accompanying documents for the software are treated in the same way as the software.
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribute the obtained object code (Redistribute the code as it was obtained)
- Distribution of Modified Source Code
- Distribute the object code generated from the modified source code
- Executing the fetched source code publicly
- Sublicense the acquired source code. (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)
- Publicly execute the fetched object code
- Sublicense the acquired object code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)
- Publicly execute the modified source code
- Sublicensing Modified Source Code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)
- Publicly execute the object code generated from the modified source code
- Sublicense the object code generated from the modified source code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)
- Selling Software
- Distribute the obtained executable (Redistribute the obtained executable as-is)
- Distribute the executable generated from the modified source code
- Publicly execute the retrieved executable
- Sublicense the acquired executable (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)
- Publicly execute executables generated from modified source code
- Sublicense the generated executable from modified source code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)

Conditions:
AND
  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license

....

(source: Hitachi open-license)

=== Text

....
Provided that these terms and disclaimer and all copyright notices
are retained or reproduced in an accompanying document, permission
is granted to deal in this work without restriction, including un‐
limited rights to use, publicly perform, distribute, sell, modify,
merge, give away, or sublicence.

This work is provided "AS IS" and WITHOUT WARRANTY of any kind, to
the utmost extent permitted by applicable law, neither express nor
implied; without malicious intent or gross negligence. In no event
may a licensor, author or contributor be held liable for indirect,
direct, other damage, loss, or other issues arising in any way out
of dealing in the work, even if advised of the possibility of such
damage or existence of a defect, except proven that it results out
of said person's immediate fault when using the work as intended.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/MirOS.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mir-os.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "MirOS",
        "MirOS License",
        "MirOS Licence",
        "The MirOS Licence (MirOS)",
        "The MirOS Licence",
        "scancode://mir-os"
    ],
    "__impliedId": "MirOS",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "The MirOS Licence",
        "MirOS"
    ],
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "https://opensource.org/licenses/miros.html"
            ]
        ],
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified."
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/MirOS",
            "maintainer": "",
            "od_conformance": "approved",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "MirOS",
            "title": "MirOS Licence",
            "_implications": {
                "__impliedNames": [
                    "MirOS",
                    "MirOS Licence"
                ],
                "__impliedId": "MirOS",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/MirOS"
                    ]
                ]
            },
            "domain_content": true
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MirOS"
                ],
                "__impliedId": "MirOS"
            },
            "shortname": "MirOS",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "The MirOS Licence",
            "spdxDetailsURL": "http://spdx.org/licenses/MirOS.json",
            "_sourceURL": "https://spdx.org/licenses/MirOS.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/MirOS"
            ],
            "_implications": {
                "__impliedNames": [
                    "MirOS",
                    "The MirOS Licence"
                ],
                "__impliedId": "MirOS",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MirOS.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/MirOS"
                    ]
                ]
            },
            "spdxLicenseId": "MirOS"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://mirbsd.de/MirOS-Licence",
            "GPLv3 Compat?": "Yes",
            "Short Name": "MirOS",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "MirOS License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "MirOS License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "MirOS"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://www.opensource.org/licenses/MirOS",
                "https://opensource.org/licenses/MirOS"
            ],
            "homepageUrl": "https://www.mirbsd.org/MirOS-Licence",
            "shortName": "MirOS License",
            "textUrls": null,
            "text": "Provided that these terms and disclaimer and all copyright notices\nare retained or reproduced in an accompanying document, permission\nis granted to deal in this work without restriction, including unâ\nlimited rights to use, publicly perform, distribute, sell, modify,\nmerge, give away, or sublicence.\n\nThis work is provided \"AS IS\" and WITHOUT WARRANTY of any kind, to\nthe utmost extent permitted by applicable law, neither express nor\nimplied; without malicious intent or gross negligence. In no event\nmay a licensor, author or contributor be held liable for indirect,\ndirect, other damage, loss, or other issues arising in any way out\nof dealing in the work, even if advised of the possibility of such\ndamage or existence of a defect, except proven that it results out\nof said person's immediate fault when using the work as intended.\n",
            "category": "Permissive",
            "osiUrl": "http://opensource.org/licenses/miros.html",
            "owner": "MirOS Project",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mir-os.yml",
            "key": "mir-os",
            "name": "MirOS License",
            "spdxId": "MirOS",
            "notes": "Per SPDX.org, this license is OSI certified.",
            "_implications": {
                "__impliedNames": [
                    "scancode://mir-os",
                    "MirOS License",
                    "MirOS"
                ],
                "__impliedId": "MirOS",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Provided that these terms and disclaimer and all copyright notices\nare retained or reproduced in an accompanying document, permission\nis granted to deal in this work without restriction, including un‐\nlimited rights to use, publicly perform, distribute, sell, modify,\nmerge, give away, or sublicence.\n\nThis work is provided \"AS IS\" and WITHOUT WARRANTY of any kind, to\nthe utmost extent permitted by applicable law, neither express nor\nimplied; without malicious intent or gross negligence. In no event\nmay a licensor, author or contributor be held liable for indirect,\ndirect, other damage, loss, or other issues arising in any way out\nof dealing in the work, even if advised of the possibility of such\ndamage or existence of a defect, except proven that it results out\nof said person's immediate fault when using the work as intended.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://www.mirbsd.org/MirOS-Licence"
                    ],
                    [
                        "OSI Page",
                        "http://opensource.org/licenses/miros.html"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/MirOS"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/MirOS"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "MirOS Licence",
            "commercialUse": true,
            "spdxId": "MirOS",
            "_implications": {
                "__impliedNames": [
                    "MirOS"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "The MirOS Licence",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "MirOS"
                ],
                "__impliedAmbiguousNames": [
                    "The MirOS Licence"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Permissive licence, Ⓕ Copyfree, very similar to MIT and ISC but applicable to more than just software"
                        }
                    ]
                ]
            },
            "Comment": "Permissive licence, Ⓕ Copyfree, very similar to MIT and ISC but applicable to more than just software",
            "LicenseId": "MirOS"
        },
        "Hitachi open-license": {
            "summary": "https://opensource.org/licenses/miros.html",
            "notices": [
                {
                    "content": "such software is provided \"as-is\" and, except in the case of bad faith or gross negligence, without warranty of any kind, either express or implied, to the extent permitted by applicable law.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "neither the licensor, the author, nor the contributor shall be liable for any damages, losses, or other problems, including indirect or direct damages, arising out of the use of such software, even if they have been advised of the possibility of such damages or of the existence of a defect. You may not use the Software for any purpose other than that for which it was intended. You may not use the Software for any purpose other than the intended use of the Software, unless such use is caused by direct negligence of the Licensor, the Author, or the Contributor."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/1554",
            "content": "/*-\n* Copyright © year, year, year, …\n* First M. Last <user@host.domain>\n*\n* Provided that these terms and disclaimer and all copyright notices\n* are retained or reproduced in an accompanying document, permission\n* is granted to deal in this work without restriction, including un‐\n* limited rights to use, publicly perform, distribute, sell, modify,\n* merge, give away, or sublicence.\n*\n* This work is provided \"AS IS\" and WITHOUT WARRANTY of any kind, to\n* the utmost extent permitted by applicable law, neither express nor\n* implied; without malicious intent or gross negligence. In no event\n* may a licensor, author or contributor be held liable for indirect,\n* direct, other damage, loss, or other issues arising in any way out\n* of dealing in the work, even if advised of the possibility of such\n* damage or existence of a defect, except proven that it results out\n* of said person's immediate fault when using the work as intended.\n*/\n\nI_N_S_T_R_U_C_T_I_O_N_S_:_\nTo apply the template(¹) specify the years of copyright (separated by\ncomma, not as a range), the legal names of the copyright holders, and\nthe real names of the authors if different. Avoid adding text.\n\nR_A_T_I_O_N_A_L_E_:_\nThis licence is apt for any kind of work (such as source code, fonts,\ndocumentation, graphics, sound etc.) and the preferred terms for work\nadded to MirBSD. It has been drafted as universally usable equivalent\nof the \"historic permission notice\"⁽²⁾ adapted to Europen law because\nin some (droit d'auteur) countries authors cannot disclaim all liabi‐\nlities. Compliance to DFSG⁽³⁾ 1.1 is ensured, and GPLv2 compatibility\nis asserted unless advertising clauses are used. The MirOS Licence is\ncertified to conform to OKD⁽⁴⁾ 1.0 and OSD⁽⁵⁾ 1.9, and qualifies as a\nFree Software⁽⁶⁾ and also Free Documentation⁽⁷⁾ licence and is inclu‐\nded in some relevant lists⁽⁸⁾⁽⁹⁾⁽¹⁰⁾.\n\nWe believe you are not liable for work inserted which is intellectual\nproperty of third parties, if you were not aware of the fact, act ap‐\npropriately as soon as you become aware of that problem, seek an ami‐\ncable solution for all parties, and never knowingly distribute a work\nwithout being authorised to do so by its licensors.\n\nR_E_F_E_R_E_N_C_E_S_:_\n① also at http://mirbsd.de/MirOS-Licence\n② http://www.opensource.org/licenses/historical.php\n③ http://www.debian.org/social_contract#guidelines\n④ http://www.opendefinition.org/1.0\n⑤ http://www.opensource.org/docs/osd\n⑥ http://www.gnu.org/philosophy/free-sw.html\n⑦ http://www.gnu.org/philosophy/free-doc.html\n⑧ http://www.ifross.de/ifross_html/lizenzcenter.html\n⑨ http://www.opendefinition.org/licenses\n⑩ http://opensource.org/licenses/miros.html",
            "name": "MirOS License",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved object code",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Use the object code generated from the modified source code"
                        },
                        {
                            "name": "Use the retrieved executable",
                            "description": "Use the obtained executable as is."
                        },
                        {
                            "name": "Use the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: Relevant documentation for the software should be treated in the same way as for the software.\nActions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved object code (Use the fetched code as it is.)\n- Use the object code generated from the modified source code\n- Use the retrieved executable (Use the obtained executable as is.)\n- Use the executable generated from the modified source code\n\nConditions: None\n",
                    "conditions": null,
                    "description": "Relevant documentation for the software should be treated in the same way as for the software."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the obtained object code",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        },
                        {
                            "name": "Distribute the object code generated from the modified source code"
                        },
                        {
                            "name": "Executing the fetched source code publicly"
                        },
                        {
                            "name": "Sublicense the acquired source code.",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        },
                        {
                            "name": "Publicly execute the fetched object code"
                        },
                        {
                            "name": "Sublicense the acquired object code",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        },
                        {
                            "name": "Publicly execute the modified source code"
                        },
                        {
                            "name": "Sublicensing Modified Source Code",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        },
                        {
                            "name": "Publicly execute the object code generated from the modified source code"
                        },
                        {
                            "name": "Sublicense the object code generated from the modified source code",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        },
                        {
                            "name": "Selling Software"
                        },
                        {
                            "name": "Distribute the obtained executable",
                            "description": "Redistribute the obtained executable as-is"
                        },
                        {
                            "name": "Distribute the executable generated from the modified source code"
                        },
                        {
                            "name": "Publicly execute the retrieved executable"
                        },
                        {
                            "name": "Sublicense the acquired executable",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        },
                        {
                            "name": "Publicly execute executables generated from modified source code"
                        },
                        {
                            "name": "Sublicense the generated executable from modified source code",
                            "description": "Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party."
                        }
                    ],
                    "_str": "Description: Related documentation and accompanying documents for the software are treated in the same way as the software.\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribute the obtained object code (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n- Distribute the object code generated from the modified source code\n- Executing the fetched source code publicly\n- Sublicense the acquired source code. (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n- Publicly execute the fetched object code\n- Sublicense the acquired object code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n- Publicly execute the modified source code\n- Sublicensing Modified Source Code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n- Publicly execute the object code generated from the modified source code\n- Sublicense the object code generated from the modified source code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n- Selling Software\n- Distribute the obtained executable (Redistribute the obtained executable as-is)\n- Distribute the executable generated from the modified source code\n- Publicly execute the retrieved executable\n- Sublicense the acquired executable (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n- Publicly execute executables generated from modified source code\n- Sublicense the generated executable from modified source code (Sublicensing means that the person to whom the license was granted re-grants the license granted to a third party.)\n\nConditions:\nAND\n  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Related documentation and accompanying documents for the software are treated in the same way as the software."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "MirOS License"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "https://opensource.org/licenses/miros.html"
                        ]
                    ]
                ],
                "__impliedText": "/*-\n* Copyright © year, year, year, …\n* First M. Last <user@host.domain>\n*\n* Provided that these terms and disclaimer and all copyright notices\n* are retained or reproduced in an accompanying document, permission\n* is granted to deal in this work without restriction, including un‐\n* limited rights to use, publicly perform, distribute, sell, modify,\n* merge, give away, or sublicence.\n*\n* This work is provided \"AS IS\" and WITHOUT WARRANTY of any kind, to\n* the utmost extent permitted by applicable law, neither express nor\n* implied; without malicious intent or gross negligence. In no event\n* may a licensor, author or contributor be held liable for indirect,\n* direct, other damage, loss, or other issues arising in any way out\n* of dealing in the work, even if advised of the possibility of such\n* damage or existence of a defect, except proven that it results out\n* of said person's immediate fault when using the work as intended.\n*/\n\nI_N_S_T_R_U_C_T_I_O_N_S_:_\nTo apply the template(¹) specify the years of copyright (separated by\ncomma, not as a range), the legal names of the copyright holders, and\nthe real names of the authors if different. Avoid adding text.\n\nR_A_T_I_O_N_A_L_E_:_\nThis licence is apt for any kind of work (such as source code, fonts,\ndocumentation, graphics, sound etc.) and the preferred terms for work\nadded to MirBSD. It has been drafted as universally usable equivalent\nof the \"historic permission notice\"⁽²⁾ adapted to Europen law because\nin some (droit d'auteur) countries authors cannot disclaim all liabi‐\nlities. Compliance to DFSG⁽³⁾ 1.1 is ensured, and GPLv2 compatibility\nis asserted unless advertising clauses are used. The MirOS Licence is\ncertified to conform to OKD⁽⁴⁾ 1.0 and OSD⁽⁵⁾ 1.9, and qualifies as a\nFree Software⁽⁶⁾ and also Free Documentation⁽⁷⁾ licence and is inclu‐\nded in some relevant lists⁽⁸⁾⁽⁹⁾⁽¹⁰⁾.\n\nWe believe you are not liable for work inserted which is intellectual\nproperty of third parties, if you were not aware of the fact, act ap‐\npropriately as soon as you become aware of that problem, seek an ami‐\ncable solution for all parties, and never knowingly distribute a work\nwithout being authorised to do so by its licensors.\n\nR_E_F_E_R_E_N_C_E_S_:_\n① also at http://mirbsd.de/MirOS-Licence\n② http://www.opensource.org/licenses/historical.php\n③ http://www.debian.org/social_contract#guidelines\n④ http://www.opendefinition.org/1.0\n⑤ http://www.opensource.org/docs/osd\n⑥ http://www.gnu.org/philosophy/free-sw.html\n⑦ http://www.gnu.org/philosophy/free-doc.html\n⑧ http://www.ifross.de/ifross_html/lizenzcenter.html\n⑨ http://www.opendefinition.org/licenses\n⑩ http://opensource.org/licenses/miros.html",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/1554"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/MirOS.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "MirOS License",
            "id": "MirOS",
            "_implications": {
                "__impliedNames": [
                    "MirOS",
                    "MirOS License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MirOS.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/MirOS",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "MirOS",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The MirOS Licence (MirOS)",
            "other_names": [],
            "keywords": [
                "osi-approved"
            ],
            "id": "MirOS",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/MirOS"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "MirOS",
                    "The MirOS Licence (MirOS)",
                    "MirOS"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/MirOS"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "Permissive licence, Ⓕ Copyfree, very similar to MIT and ISC but applicable to more than just software"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "Provided that these terms and disclaimer and all copyright notices\nare retained or reproduced in an accompanying document, permission\nis granted to deal in this work without restriction, including un‐\nlimited rights to use, publicly perform, distribute, sell, modify,\nmerge, give away, or sublicence.\n\nThis work is provided \"AS IS\" and WITHOUT WARRANTY of any kind, to\nthe utmost extent permitted by applicable law, neither express nor\nimplied; without malicious intent or gross negligence. In no event\nmay a licensor, author or contributor be held liable for indirect,\ndirect, other damage, loss, or other issues arising in any way out\nof dealing in the work, even if advised of the possibility of such\ndamage or existence of a defect, except proven that it results out\nof said person's immediate fault when using the work as intended.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/MirOS.html"
        ],
        [
            null,
            "https://opensource.org/licenses/MirOS"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/MirOS"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/1554"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/MirOS.json"
        ],
        [
            "Homepage",
            "https://www.mirbsd.org/MirOS-Licence"
        ],
        [
            "OSI Page",
            "http://opensource.org/licenses/miros.html"
        ],
        [
            null,
            "http://www.opensource.org/licenses/MirOS"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MirOS.svg
