== Enlightenment License (e16) (MIT-advertising)

[cols=",",options="header",]
|=====================================
|Key |Value
|Fullname |Enlightenment License (e16)
|Shortname |MIT-advertising
|Rating |Go
|Classification |NoCopyleft
|=====================================

*Other Names:*

* `enlightenment`
* `EFL MIT-Style License`

=== Comments on (easy) usability

* *↑* Rating is: Bronze (source: https://blueoakcouncil.org/list[BlueOak
License List])
* *↑* This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* http://www.enlightenment.org/
* *SPDX:* http://spdx.org/licenses/MIT-advertising.json
* *SPDX:* https://spdx.org/licenses/MIT-advertising.html
* https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising

=== Text

....
Copyright (C) 2000 Carsten Haitzler and various contributors (see AUTHORS)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies of the Software, its documentation and marketing & publicity materials, and acknowledgment shall be given in the documentation, materials and software packages that this Software was used.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AUTHORS: 
The Rasterman <raster@rasterman.com> 
Tom Gilbert <tom@linuxbrit.co.uk> 
Burra <burra@colorado.edu> 
Chris Ross <chris@darkrock.co.uk> 
Term <term@twistedpath.org> 
Tilman Sauerbeck <tilman@code-monkey.de> 
Ibukun Olumuyiwa <ibukun@computer.org> 
Yuri <da2001@hotmail.ru> 
Nicholas Curran <quasar@bigblue.net.au> 
Howell Tam <pigeon@pigeond.net> 
Nathan Ingersoll <rbdpngn@users.sourceforge.net> 
Andrew Elcock <andy@elcock.org> 
Kim Woelders <kim@woelders.dk> 
Sebastian Dransfeld <sebastid@tango.flipp.net> 
Simon Poole <simon.armlinux@themalago.net> 
Jorge Luis Zapata Muga <jorgeluis.zapata@gmail.com> 
dan sinclair <zero@everburning.com> 
Michael 'Mickey' Lauer <mickey@tm.informatik.uni-frankfurt.de> 
David 'onefang' Seikel <onefang@gmail.com> 
Hisham 'CodeWarrior' Mardam Bey <hisham@hisham.cc> 
Brian 'rephorm' Mattern <rephorm@rephorm.com> 
Tim Horton <hortont424@gmail.com> 
Arnaud de Turckheim 'quarium' <quarium@gmail.com> 
Matt Barclay <mbarclay@gmail.com> 
Peter Wehrfritz <peter.wehrfritz@web.de>
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "MIT-advertising",
        "Enlightenment License (e16)",
        "enlightenment",
        "EFL MIT-Style License"
    ],
    "__impliedId": "MIT-advertising",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MIT-advertising",
                    "MIT-advertising",
                    "Enlightenment License (e16)",
                    "enlightenment",
                    "EFL MIT-Style License"
                ],
                "__impliedId": "MIT-advertising"
            },
            "shortname": "MIT-advertising",
            "otherNames": [
                "MIT-advertising",
                "Enlightenment License (e16)",
                "enlightenment",
                "EFL MIT-Style License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Enlightenment License (e16)",
            "spdxDetailsURL": "http://spdx.org/licenses/MIT-advertising.json",
            "_sourceURL": "https://spdx.org/licenses/MIT-advertising.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising"
            ],
            "_implications": {
                "__impliedNames": [
                    "MIT-advertising",
                    "Enlightenment License (e16)"
                ],
                "__impliedId": "MIT-advertising",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MIT-advertising.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising"
                    ]
                ]
            },
            "spdxLicenseId": "MIT-advertising"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising",
            "GPLv3 Compat?": "NO",
            "Short Name": "MIT with advertising",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Enlightenment License (e16)",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Enlightenment License (e16)"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.enlightenment.org/",
            "shortName": "EFL MIT-Style License",
            "textUrls": null,
            "text": "Copyright (C) 2000 Carsten Haitzler and various contributors (see AUTHORS)\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies of the Software, its documentation and marketing & publicity materials, and acknowledgment shall be given in the documentation, materials and software packages that this Software was used.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nAUTHORS: \nThe Rasterman <raster@rasterman.com> \nTom Gilbert <tom@linuxbrit.co.uk> \nBurra <burra@colorado.edu> \nChris Ross <chris@darkrock.co.uk> \nTerm <term@twistedpath.org> \nTilman Sauerbeck <tilman@code-monkey.de> \nIbukun Olumuyiwa <ibukun@computer.org> \nYuri <da2001@hotmail.ru> \nNicholas Curran <quasar@bigblue.net.au> \nHowell Tam <pigeon@pigeond.net> \nNathan Ingersoll <rbdpngn@users.sourceforge.net> \nAndrew Elcock <andy@elcock.org> \nKim Woelders <kim@woelders.dk> \nSebastian Dransfeld <sebastid@tango.flipp.net> \nSimon Poole <simon.armlinux@themalago.net> \nJorge Luis Zapata Muga <jorgeluis.zapata@gmail.com> \ndan sinclair <zero@everburning.com> \nMichael 'Mickey' Lauer <mickey@tm.informatik.uni-frankfurt.de> \nDavid 'onefang' Seikel <onefang@gmail.com> \nHisham 'CodeWarrior' Mardam Bey <hisham@hisham.cc> \nBrian 'rephorm' Mattern <rephorm@rephorm.com> \nTim Horton <hortont424@gmail.com> \nArnaud de Turckheim 'quarium' <quarium@gmail.com> \nMatt Barclay <mbarclay@gmail.com> \nPeter Wehrfritz <peter.wehrfritz@web.de>",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Enlightenment",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/enlightenment.yml",
            "key": "enlightenment",
            "name": "Enlightenment (EFL) MIT-Style License",
            "spdxId": "MIT-advertising",
            "_implications": {
                "__impliedNames": [
                    "enlightenment",
                    "EFL MIT-Style License",
                    "MIT-advertising"
                ],
                "__impliedId": "MIT-advertising",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Copyright (C) 2000 Carsten Haitzler and various contributors (see AUTHORS)\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies of the Software, its documentation and marketing & publicity materials, and acknowledgment shall be given in the documentation, materials and software packages that this Software was used.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nAUTHORS: \nThe Rasterman <raster@rasterman.com> \nTom Gilbert <tom@linuxbrit.co.uk> \nBurra <burra@colorado.edu> \nChris Ross <chris@darkrock.co.uk> \nTerm <term@twistedpath.org> \nTilman Sauerbeck <tilman@code-monkey.de> \nIbukun Olumuyiwa <ibukun@computer.org> \nYuri <da2001@hotmail.ru> \nNicholas Curran <quasar@bigblue.net.au> \nHowell Tam <pigeon@pigeond.net> \nNathan Ingersoll <rbdpngn@users.sourceforge.net> \nAndrew Elcock <andy@elcock.org> \nKim Woelders <kim@woelders.dk> \nSebastian Dransfeld <sebastid@tango.flipp.net> \nSimon Poole <simon.armlinux@themalago.net> \nJorge Luis Zapata Muga <jorgeluis.zapata@gmail.com> \ndan sinclair <zero@everburning.com> \nMichael 'Mickey' Lauer <mickey@tm.informatik.uni-frankfurt.de> \nDavid 'onefang' Seikel <onefang@gmail.com> \nHisham 'CodeWarrior' Mardam Bey <hisham@hisham.cc> \nBrian 'rephorm' Mattern <rephorm@rephorm.com> \nTim Horton <hortont424@gmail.com> \nArnaud de Turckheim 'quarium' <quarium@gmail.com> \nMatt Barclay <mbarclay@gmail.com> \nPeter Wehrfritz <peter.wehrfritz@web.de>",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.enlightenment.org/"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/MIT-advertising.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Enlightenment License (e16)",
            "id": "MIT-advertising",
            "_implications": {
                "__impliedNames": [
                    "MIT-advertising"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MIT-advertising.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "Copyright (C) 2000 Carsten Haitzler and various contributors (see AUTHORS)\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies of the Software, its documentation and marketing & publicity materials, and acknowledgment shall be given in the documentation, materials and software packages that this Software was used.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n\nAUTHORS: \nThe Rasterman <raster@rasterman.com> \nTom Gilbert <tom@linuxbrit.co.uk> \nBurra <burra@colorado.edu> \nChris Ross <chris@darkrock.co.uk> \nTerm <term@twistedpath.org> \nTilman Sauerbeck <tilman@code-monkey.de> \nIbukun Olumuyiwa <ibukun@computer.org> \nYuri <da2001@hotmail.ru> \nNicholas Curran <quasar@bigblue.net.au> \nHowell Tam <pigeon@pigeond.net> \nNathan Ingersoll <rbdpngn@users.sourceforge.net> \nAndrew Elcock <andy@elcock.org> \nKim Woelders <kim@woelders.dk> \nSebastian Dransfeld <sebastid@tango.flipp.net> \nSimon Poole <simon.armlinux@themalago.net> \nJorge Luis Zapata Muga <jorgeluis.zapata@gmail.com> \ndan sinclair <zero@everburning.com> \nMichael 'Mickey' Lauer <mickey@tm.informatik.uni-frankfurt.de> \nDavid 'onefang' Seikel <onefang@gmail.com> \nHisham 'CodeWarrior' Mardam Bey <hisham@hisham.cc> \nBrian 'rephorm' Mattern <rephorm@rephorm.com> \nTim Horton <hortont424@gmail.com> \nArnaud de Turckheim 'quarium' <quarium@gmail.com> \nMatt Barclay <mbarclay@gmail.com> \nPeter Wehrfritz <peter.wehrfritz@web.de>",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/MIT-advertising.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/MIT-advertising.html"
        ],
        [
            "Homepage",
            "http://www.enlightenment.org/"
        ]
    ]
}
....