== MIT No Attribution (MIT-0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |MIT No Attribution
|Shortname |MIT-0
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `MIT License (no attribution)`
* `scancode://mit-0`
* `MIT-0-Clause`

=== Description

____
A short and simple permissive license with no conditions, not even
requiring preservation of copyright and license notices. Licensed works,
modifications, and larger works may be distributed under different terms
and without source code.
____

(source: choosealicense.com
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/MIT-0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``category: MIT'' (source:
https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[m]/[mi]/MIT-License-(no-attribution).yaml[Metaeffekt
Universe] (CC-BY-4.0))
* ``The former ekioh license has been deprecated in favor of this
license. Except for the dangling ", subject to the following
conditions:" text, the ekioh license is essentially identical to the
mit-0. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-0.yml[Scancode]
(CC0-1.0))

=== Obligations

[cols=",,",options="header",]
|===
|Rights: |Conditions: |Limitations:
a|
* commercial-use
* modifications
* distribution
* private-use

a|

a|
* liability
* warranty

|===

(source:
https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/mit-0.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== URLs

* *Homepage:*
https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE
* *SPDX:* https://spdx.org/licenses/MIT-0.html
* *SPDX:* https://spdx.org/licenses/MIT-0.json
* https://github.com/aws/mit-0
* https://romanrm.net/mit-zero
* https://kryogenix.org/code/browser/licence.html

=== Text

....
Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/mit-0.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT])
* https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[m]/[mi]/MIT-License-(no-attribution).yaml[Metaeffekt
Universe] (CC-BY-4.0)
* https://spdx.org/licenses/MIT-0.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-0.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "MIT-0",
        "MIT No Attribution",
        "mit-0",
        "MIT License (no attribution)",
        "scancode://mit-0",
        "MIT-0-Clause"
    ],
    "__impliedId": "MIT-0",
    "__impliedAmbiguousNames": [
        "MIT, Version 0",
        "MIT, 0",
        "MIT License, Version 0",
        "MIT License 0",
        "MIT No Attribution",
        "scancode:ekioh",
        "scancode:pd-mit",
        "scancode:tigra-calendar-4.0"
    ],
    "__impliedComments": [
        [
            "Metaeffekt Universe",
            [
                "category: MIT"
            ]
        ],
        [
            "Scancode",
            [
                "The former ekioh license has been deprecated in favor of this license. Except\nfor the dangling \", subject to the following conditions:\" text, the ekioh\nlicense is essentially identical to the mit-0.\n"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MIT-0"
                ],
                "__impliedId": "MIT-0"
            },
            "shortname": "MIT-0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "MIT No Attribution",
            "spdxDetailsURL": "https://spdx.org/licenses/MIT-0.json",
            "_sourceURL": "https://spdx.org/licenses/MIT-0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://github.com/aws/mit-0",
                "https://romanrm.net/mit-zero",
                "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE"
            ],
            "_implications": {
                "__impliedNames": [
                    "MIT-0",
                    "MIT No Attribution"
                ],
                "__impliedId": "MIT-0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MIT-0.json"
                    ],
                    [
                        null,
                        "https://github.com/aws/mit-0"
                    ],
                    [
                        null,
                        "https://romanrm.net/mit-zero"
                    ],
                    [
                        null,
                        "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE"
                    ]
                ]
            },
            "spdxLicenseId": "MIT-0"
        },
        "Scancode": {
            "otherUrls": [
                "https://github.com/aws/mit-0",
                "https://romanrm.net/mit-zero",
                "https://kryogenix.org/code/browser/licence.html"
            ],
            "homepageUrl": "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE",
            "shortName": "MIT-0-Clause",
            "textUrls": null,
            "text": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Amazon Web Services",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-0.yml",
            "key": "mit-0",
            "name": "MIT No Attribution",
            "spdxId": "MIT-0",
            "notes": "The former ekioh license has been deprecated in favor of this license. Except\nfor the dangling \", subject to the following conditions:\" text, the ekioh\nlicense is essentially identical to the mit-0.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://mit-0",
                    "MIT-0-Clause",
                    "MIT-0"
                ],
                "__impliedId": "MIT-0",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "The former ekioh license has been deprecated in favor of this license. Except\nfor the dangling \", subject to the following conditions:\" text, the ekioh\nlicense is essentially identical to the mit-0.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE"
                    ],
                    [
                        null,
                        "https://github.com/aws/mit-0"
                    ],
                    [
                        null,
                        "https://romanrm.net/mit-zero"
                    ],
                    [
                        null,
                        "https://kryogenix.org/code/browser/licence.html"
                    ]
                ]
            }
        },
        "Metaeffekt Universe": {
            "spdxIdentifier": "MIT-0",
            "shortName": null,
            "category": "MIT",
            "alternativeNames": [
                "MIT, Version 0",
                "MIT, 0",
                "MIT License, Version 0",
                "MIT License 0",
                "MIT No Attribution"
            ],
            "_sourceURL": "https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[m]/[mi]/MIT-License-(no-attribution).yaml",
            "otherIds": [
                "scancode:ekioh",
                "scancode:pd-mit",
                "scancode:tigra-calendar-4.0"
            ],
            "canonicalName": "MIT License (no attribution)",
            "_implications": {
                "__impliedNames": [
                    "MIT License (no attribution)",
                    "MIT-0"
                ],
                "__impliedId": "MIT-0",
                "__impliedAmbiguousNames": [
                    "MIT, Version 0",
                    "MIT, 0",
                    "MIT License, Version 0",
                    "MIT License 0",
                    "MIT No Attribution",
                    "scancode:ekioh",
                    "scancode:pd-mit",
                    "scancode:tigra-calendar-4.0"
                ],
                "__impliedComments": [
                    [
                        "Metaeffekt Universe",
                        [
                            "category: MIT"
                        ]
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/MIT-0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "MIT No Attribution",
            "id": "MIT-0",
            "_implications": {
                "__impliedNames": [
                    "MIT-0",
                    "MIT No Attribution"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MIT-0.html"
                    ]
                ]
            }
        },
        "choosealicense.com": {
            "limitations": [
                "liability",
                "warranty"
            ],
            "_sourceURL": "https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/mit-0.txt",
            "content": "---\ntitle: MIT No Attribution\nspdx-id: MIT-0\n\ndescription: A short and simple permissive license with no conditions, not even requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.\n\nhow: Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.\n\nusing:\n  rssfs: https://github.com/dertuxmalwieder/rssfs/blob/master/LICENSE\n  SOIL2: https://github.com/SpartanJ/SOIL2/blob/master/LICENSE\n  Units.NET: https://github.com/angularsen/UnitsNet/blob/master/LICENSE\n\npermissions:\n  - commercial-use\n  - modifications\n  - distribution\n  - private-use\n\nconditions: []\n\nlimitations:\n  - liability\n  - warranty\n\n---\n\nMIT No Attribution\n\nCopyright [year] [fullname]\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n",
            "name": "mit-0",
            "hidden": null,
            "spdxId": "MIT-0",
            "conditions": [],
            "permissions": [
                "commercial-use",
                "modifications",
                "distribution",
                "private-use"
            ],
            "featured": null,
            "nickname": null,
            "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.",
            "title": "MIT No Attribution",
            "_implications": {
                "__impliedNames": [
                    "mit-0",
                    "MIT-0"
                ],
                "__obligations": {
                    "limitations": [
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "liability"
                        },
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "warranty"
                        }
                    ],
                    "rights": [
                        {
                            "tag": "ImpliedRight",
                            "contents": "commercial-use"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "modifications"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "distribution"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "private-use"
                        }
                    ],
                    "conditions": []
                }
            },
            "description": "A short and simple permissive license with no conditions, not even requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code."
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__obligations": {
        "limitations": [
            {
                "tag": "ImpliedLimitation",
                "contents": "liability"
            },
            {
                "tag": "ImpliedLimitation",
                "contents": "warranty"
            }
        ],
        "rights": [
            {
                "tag": "ImpliedRight",
                "contents": "commercial-use"
            },
            {
                "tag": "ImpliedRight",
                "contents": "modifications"
            },
            {
                "tag": "ImpliedRight",
                "contents": "distribution"
            },
            {
                "tag": "ImpliedRight",
                "contents": "private-use"
            }
        ],
        "conditions": []
    },
    "__isOsiApproved": true,
    "__impliedText": "Permission is hereby granted, free of charge, to any person obtaining a copy of this\nsoftware and associated documentation files (the \"Software\"), to deal in the Software\nwithout restriction, including without limitation the rights to use, copy, modify,\nmerge, publish, distribute, sublicense, and/or sell copies of the Software, and to\npermit persons to whom the Software is furnished to do so.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\nINCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A\nPARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\nOF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\nSOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/MIT-0.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/MIT-0.json"
        ],
        [
            null,
            "https://github.com/aws/mit-0"
        ],
        [
            null,
            "https://romanrm.net/mit-zero"
        ],
        [
            null,
            "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE"
        ],
        [
            "Homepage",
            "https://github.com/awsdocs/aws-cloud9-user-guide/blob/master/LICENSE-SAMPLECODE"
        ],
        [
            null,
            "https://kryogenix.org/code/browser/licence.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MIT-0.svg
