== feh License (MIT-feh)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |feh License
|Shortname |MIT-feh
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/MIT-feh.html
* *SPDX:* http://spdx.org/licenses/MIT-feh.json
* https://fedoraproject.org/wiki/Licensing/MIT#feh

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/MIT-feh.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "MIT-feh",
        "feh License"
    ],
    "__impliedId": "MIT-feh",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "MIT"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MIT-feh"
                ],
                "__impliedId": "MIT-feh"
            },
            "shortname": "MIT-feh",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "feh License",
            "spdxDetailsURL": "http://spdx.org/licenses/MIT-feh.json",
            "_sourceURL": "https://spdx.org/licenses/MIT-feh.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/MIT#feh"
            ],
            "_implications": {
                "__impliedNames": [
                    "MIT-feh",
                    "feh License"
                ],
                "__impliedId": "MIT-feh",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MIT-feh.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/MIT#feh"
                    ]
                ]
            },
            "spdxLicenseId": "MIT-feh"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/MIT#feh",
            "GPLv3 Compat?": "Yes",
            "Short Name": "MIT",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "feh License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "feh License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "MIT"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "MIT-feh"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "MIT-feh",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/MIT-feh.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "feh License",
            "id": "MIT-feh",
            "_implications": {
                "__impliedNames": [
                    "MIT-feh",
                    "feh License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MIT-feh.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/MIT-feh.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/MIT-feh.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/MIT#feh"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MIT-feh.svg
