== MIT +no-false-attribs license (MITNFA)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |MIT +no-false-attribs license
|Shortname |MITNFA
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://mit-no-false-attribs+`
* `+MIT no false attribution License+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``Per Fedora, this license is based on the MIT license, but contains
an additional section covering the removal of attributions in certain
modification scenarios. It is Free and GPL-compatible. Use License
MITNFA '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-no-false-attribs.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/MITNFA
* *SPDX:* http://spdx.org/licenses/MITNFA.json
* *SPDX:* https://spdx.org/licenses/MITNFA.html
* *open-license:* http://open-license.hitachi.com/licenses/698

=== Text

....
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

Distributions of all or part of the Software intended to be used
by the recipients as they would use the unmodified Software,
containing modifications that substantially alter, remove, or
disable functionality of the Software, outside of the documented
configuration mechanisms provided by the Software, shall be
modified such that the Original Author's bug reporting email
addresses and urls are either replaced with the contact information
of the parties responsible for the changes, or removed entirely.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/MITNFA.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-no-false-attribs.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "MITNFA",
        "MIT +no-false-attribs license",
        "scancode://mit-no-false-attribs",
        "MIT no false attribution License",
        "MIT +no-false-attribs License"
    ],
    "__impliedId": "MITNFA",
    "__isFsfFree": true,
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per Fedora, this license is based on the MIT license, but contains an\nadditional section covering the removal of attributions in certain\nmodification scenarios. It is Free and GPL-compatible. Use License MITNFA\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "MIT +no-false-attribs license",
            "spdxDetailsURL": "http://spdx.org/licenses/MITNFA.json",
            "_sourceURL": "https://spdx.org/licenses/MITNFA.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/MITNFA"
            ],
            "_implications": {
                "__impliedNames": [
                    "MITNFA",
                    "MIT +no-false-attribs license"
                ],
                "__impliedId": "MITNFA",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MITNFA.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/MITNFA"
                    ]
                ]
            },
            "spdxLicenseId": "MITNFA"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/MITNFA",
            "GPLv3 Compat?": "Yes",
            "Short Name": "MITNFA",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "MIT +no-false-attribs license",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "MIT +no-false-attribs license"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/MITNFA",
            "shortName": "MIT no false attribution License",
            "textUrls": null,
            "text": "Permission is hereby granted, free of charge, to any person\nobtaining a copy of this software and associated documentation\nfiles (the \"Software\"), to deal in the Software without\nrestriction, including without limitation the rights to use,\ncopy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the\nSoftware is furnished to do so, subject to the following\nconditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nDistributions of all or part of the Software intended to be used\nby the recipients as they would use the unmodified Software,\ncontaining modifications that substantially alter, remove, or\ndisable functionality of the Software, outside of the documented\nconfiguration mechanisms provided by the Software, shall be\nmodified such that the Original Author's bug reporting email\naddresses and urls are either replaced with the contact information\nof the parties responsible for the changes, or removed entirely.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\nOF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\nWHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\nFROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\nOTHER DEALINGS IN THE SOFTWARE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "npm Registry",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-no-false-attribs.yml",
            "key": "mit-no-false-attribs",
            "name": "MIT with no false attribution License",
            "spdxId": "MITNFA",
            "notes": "Per Fedora, this license is based on the MIT license, but contains an\nadditional section covering the removal of attributions in certain\nmodification scenarios. It is Free and GPL-compatible. Use License MITNFA\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://mit-no-false-attribs",
                    "MIT no false attribution License",
                    "MITNFA"
                ],
                "__impliedId": "MITNFA",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per Fedora, this license is based on the MIT license, but contains an\nadditional section covering the removal of attributions in certain\nmodification scenarios. It is Free and GPL-compatible. Use License MITNFA\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission is hereby granted, free of charge, to any person\nobtaining a copy of this software and associated documentation\nfiles (the \"Software\"), to deal in the Software without\nrestriction, including without limitation the rights to use,\ncopy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the\nSoftware is furnished to do so, subject to the following\nconditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nDistributions of all or part of the Software intended to be used\nby the recipients as they would use the unmodified Software,\ncontaining modifications that substantially alter, remove, or\ndisable functionality of the Software, outside of the documented\nconfiguration mechanisms provided by the Software, shall be\nmodified such that the Original Author's bug reporting email\naddresses and urls are either replaced with the contact information\nof the parties responsible for the changes, or removed entirely.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\nOF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\nWHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\nFROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\nOTHER DEALINGS IN THE SOFTWARE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/MITNFA"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "_license_uri": "http://open-license.hitachi.com/licenses/698",
            "_license_permissions": [
                {
                    "_permission_summary": "",
                    "_permission_description": "ã½ããã¦ã§ã¢ã®é¢é£ææ¸ãã½ããã¦ã§ã¢ã¨åæ§ã«æ±ãã",
                    "_permission_conditionHead": {
                        "tag": "OlConditionTreeAnd",
                        "contents": []
                    },
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããã³ã¼ãããã®ã¾ã¾ä½¿ã",
                            "_action_uri": "http://open-license.hitachi.com/actions/1",
                            "_action_id": "actions/1",
                            "_action_name": "åå¾ããã½ã¼ã¹ã³ã¼ããæ¹å¤ããã«ä½¿ç¨ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/3",
                            "_action_id": "actions/3",
                            "_action_name": "åå¾ããã½ã¼ã¹ã³ã¼ããæ¹å¤ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/4",
                            "_action_id": "actions/4",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ããä½¿ç¨ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããã³ã¼ãããã®ã¾ã¾ä½¿ã",
                            "_action_uri": "http://open-license.hitachi.com/actions/5",
                            "_action_id": "actions/5",
                            "_action_name": "åå¾ãããªãã¸ã§ã¯ãã³ã¼ããä½¿ç¨ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/7",
                            "_action_id": "actions/7",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæãããªãã¸ã§ã¯ãã³ã¼ããä½¿ç¨ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããå®è¡å½¢å¼ããã®ã¾ã¾ä½¿ã",
                            "_action_uri": "http://open-license.hitachi.com/actions/84",
                            "_action_id": "actions/84",
                            "_action_name": "åå¾ããå®è¡å½¢å¼ãä½¿ç¨ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/87",
                            "_action_id": "actions/87",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæããå®è¡å½¢å¼ãä½¿ç¨ãã"
                        }
                    ]
                },
                {
                    "_permission_summary": "",
                    "_permission_description": "ã½ããã¦ã§ã¢ã®é¢é£ææ¸ãã½ããã¦ã§ã¢ã¨åæ§ã«æ±ãã\r\nã½ããã¦ã§ã¢ãæä¾ããç¸æã«ãåãæ¨©å©ãè¨±å¯ãããã¨ã«ãªãã",
                    "_permission_conditionHead": {
                        "tag": "OlConditionTreeAnd",
                        "contents": []
                    },
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããã³ã¼ãããã®ã¾ã¾åé å¸ãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/9",
                            "_action_id": "actions/9",
                            "_action_name": "åå¾ããã½ã¼ã¹ã³ã¼ããæ¹å¤ããã«é å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããã³ã¼ãããã®ã¾ã¾åé å¸ãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/10",
                            "_action_id": "actions/10",
                            "_action_name": "åå¾ãããªãã¸ã§ã¯ãã³ã¼ããé å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/19",
                            "_action_id": "actions/19",
                            "_action_name": "åå¾ããã½ã¼ã¹ã³ã¼ãããµãã©ã¤ã»ã³ã¹ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/22",
                            "_action_id": "actions/22",
                            "_action_name": "åå¾ãããªãã¸ã§ã¯ãã³ã¼ãããµãã©ã¤ã»ã³ã¹ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/35",
                            "_action_id": "actions/35",
                            "_action_name": "ã½ããã¦ã§ã¢ãè²©å£²ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "åå¾ããå®è¡å½¢å¼ããã®ã¾ã¾åé å¸ãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/86",
                            "_action_id": "actions/86",
                            "_action_name": "åå¾ããå®è¡å½¢å¼ãé å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/106",
                            "_action_id": "actions/106",
                            "_action_name": "åå¾ããå®è¡å½¢å¼ããµãã©ã¤ã»ã³ã¹ãã"
                        }
                    ]
                },
                {
                    "_permission_summary": "",
                    "_permission_description": "ã½ããã¦ã§ã¢ã®é¢é£ææ¸ãã½ããã¦ã§ã¢ã¨åæ§ã«æ±ãã\r\nã½ããã¦ã§ã¢ãæä¾ããç¸æã«ãåãæ¨©å©ãè¨±å¯ãããã¨ã«ãªãã",
                    "_permission_conditionHead": {
                        "tag": "OlConditionTreeAnd",
                        "contents": []
                    },
                    "_permission_actions": [
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/12",
                            "_action_id": "actions/12",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ããé å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/13",
                            "_action_id": "actions/13",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæãããªãã¸ã§ã¯ãã³ã¼ããé å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/25",
                            "_action_id": "actions/25",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããµãã©ã¤ã»ã³ã¹ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/28",
                            "_action_id": "actions/28",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæãããªãã¸ã§ã¯ãã³ã¼ãããµãã©ã¤ã»ã³ã¹ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "",
                            "_action_uri": "http://open-license.hitachi.com/actions/89",
                            "_action_id": "actions/89",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæããå®è¡å½¢å¼ãé å¸ãã"
                        },
                        {
                            "_action_baseUri": "http://open-license.hitachi.com/",
                            "_action_schemaVersion": "0.1",
                            "_description": "ãµãã©ã¤ã»ã³ã¹ã¯ãå½è©²ã©ã¤ã»ã³ã¹ãä»ä¸ãããèããååº¦ãç¬¬ä¸èã«ãã®ä»ä¸ãããã©ã¤ã»ã³ã¹ãä¾ä¸ãããã¨ãæãã",
                            "_action_uri": "http://open-license.hitachi.com/actions/109",
                            "_action_id": "actions/109",
                            "_action_name": "æ¹å¤ããã½ã¼ã¹ã³ã¼ãããçæããå®è¡å½¢å¼ããµãã©ã¤ã»ã³ã¹ãã"
                        }
                    ]
                }
            ],
            "_license_id": "licenses/698",
            "_sourceURL": "http://open-license.hitachi.com/licenses/698",
            "_license_name": "MIT +no-false-attribs License",
            "_license_summary": "",
            "_license_description": "",
            "_license_baseUri": "http://open-license.hitachi.com/",
            "_license_schemaVersion": "0.1",
            "_implications": {
                "__impliedNames": [
                    "MIT +no-false-attribs License"
                ],
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/698"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/MITNFA.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "MIT +no-false-attribs license",
            "id": "MITNFA",
            "_implications": {
                "__impliedNames": [
                    "MITNFA",
                    "MIT +no-false-attribs license"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MITNFA.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Permission is hereby granted, free of charge, to any person\nobtaining a copy of this software and associated documentation\nfiles (the \"Software\"), to deal in the Software without\nrestriction, including without limitation the rights to use,\ncopy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the\nSoftware is furnished to do so, subject to the following\nconditions:\n\nThe above copyright notice and this permission notice shall be\nincluded in all copies or substantial portions of the Software.\n\nDistributions of all or part of the Software intended to be used\nby the recipients as they would use the unmodified Software,\ncontaining modifications that substantially alter, remove, or\ndisable functionality of the Software, outside of the documented\nconfiguration mechanisms provided by the Software, shall be\nmodified such that the Original Author's bug reporting email\naddresses and urls are either replaced with the contact information\nof the parties responsible for the changes, or removed entirely.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\nOF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT\nHOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\nWHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\nFROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\nOTHER DEALINGS IN THE SOFTWARE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/MITNFA.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/MITNFA"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/MITNFA.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/MITNFA"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/698"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MITNFA.svg