== mpich2 License (mpich2)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |mpich2 License
|Shortname |mpich2
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://mpich+`
* `+MPICH License+`

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``Per Fedora, this is missing the anti-publicity-use clause, and
doesn't mention sublicensing, but otherwise, it is functionally
identical to MIT. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mpich.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* https://svn.mcs.anl.gov/repos/mpi/mpich2/trunk/COPYRIGHT
* *SPDX:* http://spdx.org/licenses/mpich2.json
* *SPDX:* https://spdx.org/licenses/mpich2.html
* https://fedoraproject.org/wiki/Licensing/MIT

=== Text

....
COPYRIGHT

    The following is a notice of limited availability of the code, and disclaimer
    which must be included in the prologue of the code and in all source listings
    of the code.

    Copyright Notice
     + 2002 University of Chicago

    Permission is hereby granted to use, reproduce, prepare derivative works, and
    to redistribute to others.  This software was authored by:

    Mathematics and Computer Science Division
    Argonne National Laboratory, Argonne IL 60439

    (and)

    Department of Computer Science
    University of Illinois at Urbana-Champaign


GOVERNMENT LICENSE

    Portions of this material resulted from work developed under a U.S.
    Government Contract and are subject to the following license: the Government
    is granted for itself and others acting on its behalf a paid-up, nonexclusive,
    irrevocable worldwide license in this computer software to reproduce, prepare
    derivative works, and perform publicly and display publicly.

    				  DISCLAIMER

    This computer code material was prepared, in part, as an account of work
    sponsored by an agency of the United States Government.  Neither the United
    States, nor the University of Chicago, nor any of their employees, makes any
    warranty express or implied, or assumes any legal liability or responsibility
    for the accuracy, completeness, or usefulness of any information, apparatus,
    product, or process disclosed, or represents that its use would not infringe
    privately owned rights.
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/mpich2.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mpich.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])

==== Raw JSON

....
{
    "__impliedNames": [
        "mpich2",
        "mpich2 License",
        "scancode://mpich",
        "MPICH License"
    ],
    "__impliedId": "mpich2",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "MIT"
    ],
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per Fedora, this is missing the anti-publicity-use clause, and doesn't\nmention sublicensing, but otherwise, it is functionally identical to MIT.\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "mpich2 License",
            "spdxDetailsURL": "http://spdx.org/licenses/mpich2.json",
            "_sourceURL": "https://spdx.org/licenses/mpich2.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/MIT"
            ],
            "_implications": {
                "__impliedNames": [
                    "mpich2",
                    "mpich2 License"
                ],
                "__impliedId": "mpich2",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/mpich2.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/MIT"
                    ]
                ]
            },
            "spdxLicenseId": "mpich2"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/MIT",
            "GPLv3 Compat?": "Yes",
            "Short Name": "MIT",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "mpich2 License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "mpich2 License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "MIT"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "https://fedoraproject.org/wiki/Licensing/MIT"
            ],
            "homepageUrl": "https://svn.mcs.anl.gov/repos/mpi/mpich2/trunk/COPYRIGHT",
            "shortName": "MPICH License",
            "textUrls": null,
            "text": "COPYRIGHT\n\n    The following is a notice of limited availability of the code, and disclaimer\n    which must be included in the prologue of the code and in all source listings\n    of the code.\n\n    Copyright Notice\n     + 2002 University of Chicago\n\n    Permission is hereby granted to use, reproduce, prepare derivative works, and\n    to redistribute to others.  This software was authored by:\n\n    Mathematics and Computer Science Division\n    Argonne National Laboratory, Argonne IL 60439\n\n    (and)\n\n    Department of Computer Science\n    University of Illinois at Urbana-Champaign\n\n\nGOVERNMENT LICENSE\n\n    Portions of this material resulted from work developed under a U.S.\n    Government Contract and are subject to the following license: the Government\n    is granted for itself and others acting on its behalf a paid-up, nonexclusive,\n    irrevocable worldwide license in this computer software to reproduce, prepare\n    derivative works, and perform publicly and display publicly.\n\n    \t\t\t\t  DISCLAIMER\n\n    This computer code material was prepared, in part, as an account of work\n    sponsored by an agency of the United States Government.  Neither the United\n    States, nor the University of Chicago, nor any of their employees, makes any\n    warranty express or implied, or assumes any legal liability or responsibility\n    for the accuracy, completeness, or usefulness of any information, apparatus,\n    product, or process disclosed, or represents that its use would not infringe\n    privately owned rights.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "University of Chicago",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mpich.yml",
            "key": "mpich",
            "name": "MPICH License",
            "spdxId": "mpich2",
            "notes": "Per Fedora, this is missing the anti-publicity-use clause, and doesn't\nmention sublicensing, but otherwise, it is functionally identical to MIT.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://mpich",
                    "MPICH License",
                    "mpich2"
                ],
                "__impliedId": "mpich2",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per Fedora, this is missing the anti-publicity-use clause, and doesn't\nmention sublicensing, but otherwise, it is functionally identical to MIT.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "COPYRIGHT\n\n    The following is a notice of limited availability of the code, and disclaimer\n    which must be included in the prologue of the code and in all source listings\n    of the code.\n\n    Copyright Notice\n     + 2002 University of Chicago\n\n    Permission is hereby granted to use, reproduce, prepare derivative works, and\n    to redistribute to others.  This software was authored by:\n\n    Mathematics and Computer Science Division\n    Argonne National Laboratory, Argonne IL 60439\n\n    (and)\n\n    Department of Computer Science\n    University of Illinois at Urbana-Champaign\n\n\nGOVERNMENT LICENSE\n\n    Portions of this material resulted from work developed under a U.S.\n    Government Contract and are subject to the following license: the Government\n    is granted for itself and others acting on its behalf a paid-up, nonexclusive,\n    irrevocable worldwide license in this computer software to reproduce, prepare\n    derivative works, and perform publicly and display publicly.\n\n    \t\t\t\t  DISCLAIMER\n\n    This computer code material was prepared, in part, as an account of work\n    sponsored by an agency of the United States Government.  Neither the United\n    States, nor the University of Chicago, nor any of their employees, makes any\n    warranty express or implied, or assumes any legal liability or responsibility\n    for the accuracy, completeness, or usefulness of any information, apparatus,\n    product, or process disclosed, or represents that its use would not infringe\n    privately owned rights.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://svn.mcs.anl.gov/repos/mpi/mpich2/trunk/COPYRIGHT"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/MIT"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/mpich2.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "mpich2 License",
            "id": "mpich2",
            "_implications": {
                "__impliedNames": [
                    "mpich2",
                    "mpich2 License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/mpich2.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "COPYRIGHT\n\n    The following is a notice of limited availability of the code, and disclaimer\n    which must be included in the prologue of the code and in all source listings\n    of the code.\n\n    Copyright Notice\n     + 2002 University of Chicago\n\n    Permission is hereby granted to use, reproduce, prepare derivative works, and\n    to redistribute to others.  This software was authored by:\n\n    Mathematics and Computer Science Division\n    Argonne National Laboratory, Argonne IL 60439\n\n    (and)\n\n    Department of Computer Science\n    University of Illinois at Urbana-Champaign\n\n\nGOVERNMENT LICENSE\n\n    Portions of this material resulted from work developed under a U.S.\n    Government Contract and are subject to the following license: the Government\n    is granted for itself and others acting on its behalf a paid-up, nonexclusive,\n    irrevocable worldwide license in this computer software to reproduce, prepare\n    derivative works, and perform publicly and display publicly.\n\n    \t\t\t\t  DISCLAIMER\n\n    This computer code material was prepared, in part, as an account of work\n    sponsored by an agency of the United States Government.  Neither the United\n    States, nor the University of Chicago, nor any of their employees, makes any\n    warranty express or implied, or assumes any legal liability or responsibility\n    for the accuracy, completeness, or usefulness of any information, apparatus,\n    product, or process disclosed, or represents that its use would not infringe\n    privately owned rights.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/mpich2.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/MIT"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/mpich2.html"
        ],
        [
            "Homepage",
            "https://svn.mcs.anl.gov/repos/mpi/mpich2/trunk/COPYRIGHT"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/mpich2.svg