== Mozilla Public License 2.0 (no copyleft exception) (MPL-2.0-no-copyleft-exception)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Mozilla Public License 2.0 (no copyleft exception)
|Shortname |MPL-2.0-no-copyleft-exception
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html[SPDX] (all
data [in this repository] is generated))
* **↑**``This license is compatible with the
DebianFreeSoftwareGuidelines (DFSG-free)'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

* ``Weak copyleft licenses require sharing changes and additions to the
licensed software when you give copies to others.'' (source:
https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *SPDX:* http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json
* https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html
* http://www.mozilla.org/MPL/2.0/
* https://opensource.org/licenses/MPL-2.0

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html[SPDX]
(all data [in this repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "MPL-2.0-no-copyleft-exception",
        "Mozilla Public License 2.0 (no copyleft exception)"
    ],
    "__impliedId": "MPL-2.0-no-copyleft-exception",
    "__impliedAmbiguousNames": [
        "Mozilla Public License",
        "Mozilla Public License (MPL)"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "Weak copyleft licenses require sharing changes and additions to the licensed software when you give copies to others."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedId": "MPL-2.0-no-copyleft-exception"
            },
            "shortname": "MPL-2.0-no-copyleft-exception",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Mozilla Public License 2.0 (no copyleft exception)",
            "spdxDetailsURL": "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json",
            "_sourceURL": "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.mozilla.org/MPL/2.0/",
                "https://opensource.org/licenses/MPL-2.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception",
                    "Mozilla Public License 2.0 (no copyleft exception)"
                ],
                "__impliedId": "MPL-2.0-no-copyleft-exception",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json"
                    ],
                    [
                        null,
                        "http://www.mozilla.org/MPL/2.0/"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/MPL-2.0"
                    ]
                ]
            },
            "spdxLicenseId": "MPL-2.0-no-copyleft-exception"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "MPL-2.0-no-copyleft-exception",
            "copyleftkind": "WeakCopyleft"
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Mozilla Public License (MPL)",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedAmbiguousNames": [
                    "Mozilla Public License (MPL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "MPL-2.0-no-copyleft-exception"
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html",
            "familyName": "Mozilla Public License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "Mozilla Public License 2.0 (no copyleft exception)",
            "id": "MPL-2.0-no-copyleft-exception",
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception",
                    "Mozilla Public License 2.0 (no copyleft exception)"
                ],
                "__impliedAmbiguousNames": [
                    "Mozilla Public License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "Weak copyleft licenses require sharing changes and additions to the licensed software when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html"
                    ]
                ]
            },
            "CopyleftKind": "WeakCopyleft"
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "WeakCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json"
        ],
        [
            null,
            "http://www.mozilla.org/MPL/2.0/"
        ],
        [
            null,
            "https://opensource.org/licenses/MPL-2.0"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MPL-2.0-no-copyleft-exception.svg
