== Mozilla Public License 2.0 (no copyleft exception) (MPL-2.0-no-copyleft-exception)

[cols=",",options="header",]
|============================================================
|Key |Value
|Fullname |Mozilla Public License 2.0 (no copyleft exception)
|Shortname |MPL-2.0-no-copyleft-exception
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|============================================================

*Other Names:*

* `MPL 2.0 with no copyleft exception`

=== Comments on (easy) usability

* **↑**Is OSI Approved (source:
https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html[SPDX])
* **↑**This license is compatible with the DebianFreeSoftwareGuidelines
(DFSG-free) (source: https://wiki.debian.org/DFSGLicenses[Debian Free
Software Guidelines])

=== URLs

* *Homepage:* http://www.mozilla.org/MPL/2.0/
* *OSI Page:* http://opensource.org/licenses/MPL-2.0
* *SPDX:* http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json

=== OSADL Rule

....
USE CASE Source code delivery
	YOU MUST Provide License notice
	YOU MUST Reference License text
	YOU MUST NOT Modify Legal notices
	IF Service offerings
		ATTRIBUTE NOT Transferable
		YOU MUST Indemnify Other contributors
	IF Software modification
		YOU MUST Grant License
			ATTRIBUTE Original license
	YOU MUST NOT Restrict Granted rights
USE CASE Binary delivery
	YOU MUST Provide Source code
		YOU MUST Reference Source code
		ATTRIBUTE Reasonable
		ATTRIBUTE Timely
		ATTRIBUTE No profit
	USE CASE License change
		YOU MUST NOT Restrict Granted rights
	IF Service offerings
		ATTRIBUTE NOT Transferable
		YOU MUST Indemnify Other contributors
COMPATIBILITY BSD-2-Clause
COMPATIBILITY BSD-2-Clause-Patent
COMPATIBILITY BSD-3-Clause
COMPATIBILITY bzip2-1.0.5
COMPATIBILITY bzip2-1.0.6
COMPATIBILITY CC0-1.0
COMPATIBILITY curl
COMPATIBILITY IBM-pibs
COMPATIBILITY ICU
COMPATIBILITY ISC
COMPATIBILITY Libpng
COMPATIBILITY MIT
COMPATIBILITY MPL-2.0
COMPATIBILITY NTP
COMPATIBILITY UPL-1.0
COMPATIBILITY WTFPL
COMPATIBILITY X11
COMPATIBILITY Zlib
COPYLEFT CLAUSE Yes
PATENT HINTS
....

(source: OSADL License Checklist)

=== Text

....
This Source Code Form is "Incompatible With Secondary Licenses", as
defined by the Mozilla Public License, v. 2.0.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "MPL-2.0-no-copyleft-exception",
        "Mozilla Public License 2.0 (no copyleft exception)",
        "mpl-2.0-no-copyleft-exception",
        "MPL 2.0 with no copyleft exception"
    ],
    "__impliedId": "MPL-2.0-no-copyleft-exception",
    "__impliedAmbiguousNames": [
        "Mozilla Public License (MPL)"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception",
                    "MPL-2.0-no-copyleft-exception",
                    "Mozilla Public License 2.0 (no copyleft exception)",
                    "mpl-2.0-no-copyleft-exception",
                    "MPL 2.0 with no copyleft exception"
                ],
                "__impliedId": "MPL-2.0-no-copyleft-exception"
            },
            "shortname": "MPL-2.0-no-copyleft-exception",
            "otherNames": [
                "MPL-2.0-no-copyleft-exception",
                "Mozilla Public License 2.0 (no copyleft exception)",
                "mpl-2.0-no-copyleft-exception",
                "MPL 2.0 with no copyleft exception"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Mozilla Public License 2.0 (no copyleft exception)",
            "spdxDetailsURL": "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json",
            "_sourceURL": "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.mozilla.org/MPL/2.0/",
                "https://opensource.org/licenses/MPL-2.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception",
                    "Mozilla Public License 2.0 (no copyleft exception)"
                ],
                "__impliedId": "MPL-2.0-no-copyleft-exception",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json"
                    ],
                    [
                        null,
                        "http://www.mozilla.org/MPL/2.0/"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/MPL-2.0"
                    ]
                ]
            },
            "spdxLicenseId": "MPL-2.0-no-copyleft-exception"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/MPL-2.0-no-copyleft-exception.txt",
            "spdxId": "MPL-2.0-no-copyleft-exception",
            "osadlRule": "USE CASE Source code delivery\n\tYOU MUST Provide License notice\n\tYOU MUST Reference License text\n\tYOU MUST NOT Modify Legal notices\n\tIF Service offerings\n\t\tATTRIBUTE NOT Transferable\n\t\tYOU MUST Indemnify Other contributors\n\tIF Software modification\n\t\tYOU MUST Grant License\n\t\t\tATTRIBUTE Original license\n\tYOU MUST NOT Restrict Granted rights\nUSE CASE Binary delivery\n\tYOU MUST Provide Source code\n\t\tYOU MUST Reference Source code\n\t\tATTRIBUTE Reasonable\n\t\tATTRIBUTE Timely\n\t\tATTRIBUTE No profit\n\tUSE CASE License change\n\t\tYOU MUST NOT Restrict Granted rights\n\tIF Service offerings\n\t\tATTRIBUTE NOT Transferable\n\t\tYOU MUST Indemnify Other contributors\nCOMPATIBILITY BSD-2-Clause\r\nCOMPATIBILITY BSD-2-Clause-Patent\r\nCOMPATIBILITY BSD-3-Clause\r\nCOMPATIBILITY bzip2-1.0.5\r\nCOMPATIBILITY bzip2-1.0.6\r\nCOMPATIBILITY CC0-1.0\r\nCOMPATIBILITY curl\r\nCOMPATIBILITY IBM-pibs\r\nCOMPATIBILITY ICU\r\nCOMPATIBILITY ISC\r\nCOMPATIBILITY Libpng\r\nCOMPATIBILITY MIT\r\nCOMPATIBILITY MPL-2.0\r\nCOMPATIBILITY NTP\r\nCOMPATIBILITY UPL-1.0\r\nCOMPATIBILITY WTFPL\r\nCOMPATIBILITY X11\r\nCOMPATIBILITY Zlib\r\nCOPYLEFT CLAUSE Yes\nPATENT HINTS\n",
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedCopyleft": [
                    [
                        "OSADL License Checklist",
                        "Copyleft"
                    ]
                ],
                "__calculatedCopyleft": "Copyleft"
            }
        },
        "Scancode": {
            "otherUrls": [
                "https://opensource.org/licenses/MPL-2.0"
            ],
            "homepageUrl": "http://www.mozilla.org/MPL/2.0/",
            "shortName": "MPL 2.0 with no copyleft exception",
            "textUrls": null,
            "text": "This Source Code Form is \"Incompatible With Secondary Licenses\", as\ndefined by the Mozilla Public License, v. 2.0.\n",
            "category": "Copyleft Limited",
            "osiUrl": "http://opensource.org/licenses/MPL-2.0",
            "owner": "Mozilla",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mpl-2.0-no-copyleft-exception.yml",
            "key": "mpl-2.0-no-copyleft-exception",
            "name": "Mozilla Public License 2.0 (no copyleft exception)",
            "spdxId": "MPL-2.0-no-copyleft-exception",
            "_implications": {
                "__impliedNames": [
                    "mpl-2.0-no-copyleft-exception",
                    "MPL 2.0 with no copyleft exception",
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedId": "MPL-2.0-no-copyleft-exception",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft",
                "__impliedText": "This Source Code Form is \"Incompatible With Secondary Licenses\", as\ndefined by the Mozilla Public License, v. 2.0.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.mozilla.org/MPL/2.0/"
                    ],
                    [
                        "OSI Page",
                        "http://opensource.org/licenses/MPL-2.0"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/MPL-2.0"
                    ]
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Mozilla Public License (MPL)",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "MPL-2.0-no-copyleft-exception"
                ],
                "__impliedAmbiguousNames": [
                    "Mozilla Public License (MPL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "MPL-2.0-no-copyleft-exception"
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "OSADL License Checklist",
            "Copyleft"
        ],
        [
            "Scancode",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "This Source Code Form is \"Incompatible With Secondary Licenses\", as\ndefined by the Mozilla Public License, v. 2.0.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/MPL-2.0-no-copyleft-exception.json"
        ],
        [
            null,
            "http://www.mozilla.org/MPL/2.0/"
        ],
        [
            null,
            "https://opensource.org/licenses/MPL-2.0"
        ],
        [
            "Homepage",
            "http://www.mozilla.org/MPL/2.0/"
        ],
        [
            "OSI Page",
            "http://opensource.org/licenses/MPL-2.0"
        ]
    ]
}
....