== Matrix Template Library License (MTLL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Matrix Template Library License
|Shortname |MTLL
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://mtll+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``Per Fedora, this license was found in the Matrix Template Library.
It is derived from the Apache Software License v1.1, but it is modified
in several ways. It is Free, but GPL-incompatible. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mtll.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:*
https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License
* *SPDX:* http://spdx.org/licenses/MTLL.json
* *SPDX:* https://spdx.org/licenses/MTLL.html

=== Text

....
Software License for MTL


This file is part of the Matrix Template Library

Dresden University of Technology -- short TUD -- and Indiana University 
-- short IU -- have the exclusive rights to license this product under the
following license.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
1. All redistributions of source code must retain the above copyright notice, the list of authors in the original source code, this list of conditions and the disclaimer listed in this license; 
2. All redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer listed in this license in the documentation and/or other materials provided with the distribution; 
3. Any documentation included with all redistributions must include the following acknowledgement: 
"This product includes software developed at the University of Notre Dame, the Pervasive Technology Labs at Indiana University, and Dresden University of Technology. For technical information contact Andrew Lumsdaine at the Pervasive Technology Labs at Indiana University. For administrative and license questions contact the Advanced Research and Technology Institute at 1100 Waterway Blvd. Indianapolis, Indiana 46202, phone 317-274-5905, fax 317-274-5902." 
Alternatively, this acknowledgement may appear in the software itself, and wherever such third-party acknowledgments normally appear. 
4. The name "MTL" shall not be used to endorse or promote products derived from this software without prior written permission from IU or TUD. For written permission, please contact Indiana University Advanced Research & Technology Institute. 
5. Products derived from this software may not be called "MTL", nor may "MTL" appear in their name, without prior written permission of Indiana University Advanced Research & Technology Institute.

TUD and IU provide no reassurances that the source code provided does not infringe the patent or any other intellectual property rights of any other entity. TUD and IU disclaim any liability to any recipient for claims brought by any other entity based on infringement of intellectual property rights or otherwise.

LICENSEE UNDERSTANDS THAT SOFTWARE IS PROVIDED "AS IS" FOR WHICH NO WARRANTIES AS TO CAPABILITIES OR ACCURACY ARE MADE. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY GIVE NO WARRANTIES AND MAKE NO REPRESENTATION THAT SOFTWARE IS FREE OF INFRINGEMENT OF THIRD PARTY PATENT, COPYRIGHT, OR OTHER PROPRIETARY RIGHTS. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY MAKE NO WARRANTIES THAT SOFTWARE IS FREE FROM "BUGS", "VIRUSES", "TROJAN HORSES", "TRAP DOORS", "WORMS", OR OTHER HARMFUL CODE. LICENSEE ASSUMES THE ENTIRE RISK AS TO THE PERFORMANCE OF SOFTWARE AND/OR ASSOCIATED MATERIALS, AND TO THE PERFORMANCE AND VALIDITY OF INFORMATION GENERATED USING SOFTWARE.
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/MTLL.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mtll.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "MTLL",
        "Matrix Template Library License",
        "scancode://mtll"
    ],
    "__impliedId": "MTLL",
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per Fedora, this license was found in the Matrix Template Library. It is\nderived from the Apache Software License v1.1, but it is modified in\nseveral ways. It is Free, but GPL-incompatible.\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Matrix Template Library License",
            "spdxDetailsURL": "http://spdx.org/licenses/MTLL.json",
            "_sourceURL": "https://spdx.org/licenses/MTLL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "MTLL",
                    "Matrix Template Library License"
                ],
                "__impliedId": "MTLL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MTLL.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"
                    ]
                ]
            },
            "spdxLicenseId": "MTLL"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License",
            "shortName": "Matrix Template Library License",
            "textUrls": null,
            "text": "Software License for MTL\n\n\nThis file is part of the Matrix Template Library\n\nDresden University of Technology -- short TUD -- and Indiana University \n-- short IU -- have the exclusive rights to license this product under the\nfollowing license.\n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: \n1. All redistributions of source code must retain the above copyright notice, the list of authors in the original source code, this list of conditions and the disclaimer listed in this license; \n2. All redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer listed in this license in the documentation and/or other materials provided with the distribution; \n3. Any documentation included with all redistributions must include the following acknowledgement: \n\"This product includes software developed at the University of Notre Dame, the Pervasive Technology Labs at Indiana University, and Dresden University of Technology. For technical information contact Andrew Lumsdaine at the Pervasive Technology Labs at Indiana University. For administrative and license questions contact the Advanced Research and Technology Institute at 1100 Waterway Blvd. Indianapolis, Indiana 46202, phone 317-274-5905, fax 317-274-5902.\" \nAlternatively, this acknowledgement may appear in the software itself, and wherever such third-party acknowledgments normally appear. \n4. The name \"MTL\" shall not be used to endorse or promote products derived from this software without prior written permission from IU or TUD. For written permission, please contact Indiana University Advanced Research & Technology Institute. \n5. Products derived from this software may not be called \"MTL\", nor may \"MTL\" appear in their name, without prior written permission of Indiana University Advanced Research & Technology Institute.\n\nTUD and IU provide no reassurances that the source code provided does not infringe the patent or any other intellectual property rights of any other entity. TUD and IU disclaim any liability to any recipient for claims brought by any other entity based on infringement of intellectual property rights or otherwise.\n\nLICENSEE UNDERSTANDS THAT SOFTWARE IS PROVIDED \"AS IS\" FOR WHICH NO WARRANTIES AS TO CAPABILITIES OR ACCURACY ARE MADE. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY GIVE NO WARRANTIES AND MAKE NO REPRESENTATION THAT SOFTWARE IS FREE OF INFRINGEMENT OF THIRD PARTY PATENT, COPYRIGHT, OR OTHER PROPRIETARY RIGHTS. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY MAKE NO WARRANTIES THAT SOFTWARE IS FREE FROM \"BUGS\", \"VIRUSES\", \"TROJAN HORSES\", \"TRAP DOORS\", \"WORMS\", OR OTHER HARMFUL CODE. LICENSEE ASSUMES THE ENTIRE RISK AS TO THE PERFORMANCE OF SOFTWARE AND/OR ASSOCIATED MATERIALS, AND TO THE PERFORMANCE AND VALIDITY OF INFORMATION GENERATED USING SOFTWARE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Indiana University",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mtll.yml",
            "key": "mtll",
            "name": "Matrix Template Library License",
            "spdxId": "MTLL",
            "notes": "Per Fedora, this license was found in the Matrix Template Library. It is\nderived from the Apache Software License v1.1, but it is modified in\nseveral ways. It is Free, but GPL-incompatible.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://mtll",
                    "Matrix Template Library License",
                    "MTLL"
                ],
                "__impliedId": "MTLL",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per Fedora, this license was found in the Matrix Template Library. It is\nderived from the Apache Software License v1.1, but it is modified in\nseveral ways. It is Free, but GPL-incompatible.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Software License for MTL\n\n\nThis file is part of the Matrix Template Library\n\nDresden University of Technology -- short TUD -- and Indiana University \n-- short IU -- have the exclusive rights to license this product under the\nfollowing license.\n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: \n1. All redistributions of source code must retain the above copyright notice, the list of authors in the original source code, this list of conditions and the disclaimer listed in this license; \n2. All redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer listed in this license in the documentation and/or other materials provided with the distribution; \n3. Any documentation included with all redistributions must include the following acknowledgement: \n\"This product includes software developed at the University of Notre Dame, the Pervasive Technology Labs at Indiana University, and Dresden University of Technology. For technical information contact Andrew Lumsdaine at the Pervasive Technology Labs at Indiana University. For administrative and license questions contact the Advanced Research and Technology Institute at 1100 Waterway Blvd. Indianapolis, Indiana 46202, phone 317-274-5905, fax 317-274-5902.\" \nAlternatively, this acknowledgement may appear in the software itself, and wherever such third-party acknowledgments normally appear. \n4. The name \"MTL\" shall not be used to endorse or promote products derived from this software without prior written permission from IU or TUD. For written permission, please contact Indiana University Advanced Research & Technology Institute. \n5. Products derived from this software may not be called \"MTL\", nor may \"MTL\" appear in their name, without prior written permission of Indiana University Advanced Research & Technology Institute.\n\nTUD and IU provide no reassurances that the source code provided does not infringe the patent or any other intellectual property rights of any other entity. TUD and IU disclaim any liability to any recipient for claims brought by any other entity based on infringement of intellectual property rights or otherwise.\n\nLICENSEE UNDERSTANDS THAT SOFTWARE IS PROVIDED \"AS IS\" FOR WHICH NO WARRANTIES AS TO CAPABILITIES OR ACCURACY ARE MADE. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY GIVE NO WARRANTIES AND MAKE NO REPRESENTATION THAT SOFTWARE IS FREE OF INFRINGEMENT OF THIRD PARTY PATENT, COPYRIGHT, OR OTHER PROPRIETARY RIGHTS. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY MAKE NO WARRANTIES THAT SOFTWARE IS FREE FROM \"BUGS\", \"VIRUSES\", \"TROJAN HORSES\", \"TRAP DOORS\", \"WORMS\", OR OTHER HARMFUL CODE. LICENSEE ASSUMES THE ENTIRE RISK AS TO THE PERFORMANCE OF SOFTWARE AND/OR ASSOCIATED MATERIALS, AND TO THE PERFORMANCE AND VALIDITY OF INFORMATION GENERATED USING SOFTWARE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/MTLL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Matrix Template Library License",
            "id": "MTLL",
            "_implications": {
                "__impliedNames": [
                    "MTLL",
                    "Matrix Template Library License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/MTLL.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Software License for MTL\n\n\nThis file is part of the Matrix Template Library\n\nDresden University of Technology -- short TUD -- and Indiana University \n-- short IU -- have the exclusive rights to license this product under the\nfollowing license.\n\nRedistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: \n1. All redistributions of source code must retain the above copyright notice, the list of authors in the original source code, this list of conditions and the disclaimer listed in this license; \n2. All redistributions in binary form must reproduce the above copyright notice, this list of conditions and the disclaimer listed in this license in the documentation and/or other materials provided with the distribution; \n3. Any documentation included with all redistributions must include the following acknowledgement: \n\"This product includes software developed at the University of Notre Dame, the Pervasive Technology Labs at Indiana University, and Dresden University of Technology. For technical information contact Andrew Lumsdaine at the Pervasive Technology Labs at Indiana University. For administrative and license questions contact the Advanced Research and Technology Institute at 1100 Waterway Blvd. Indianapolis, Indiana 46202, phone 317-274-5905, fax 317-274-5902.\" \nAlternatively, this acknowledgement may appear in the software itself, and wherever such third-party acknowledgments normally appear. \n4. The name \"MTL\" shall not be used to endorse or promote products derived from this software without prior written permission from IU or TUD. For written permission, please contact Indiana University Advanced Research & Technology Institute. \n5. Products derived from this software may not be called \"MTL\", nor may \"MTL\" appear in their name, without prior written permission of Indiana University Advanced Research & Technology Institute.\n\nTUD and IU provide no reassurances that the source code provided does not infringe the patent or any other intellectual property rights of any other entity. TUD and IU disclaim any liability to any recipient for claims brought by any other entity based on infringement of intellectual property rights or otherwise.\n\nLICENSEE UNDERSTANDS THAT SOFTWARE IS PROVIDED \"AS IS\" FOR WHICH NO WARRANTIES AS TO CAPABILITIES OR ACCURACY ARE MADE. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY GIVE NO WARRANTIES AND MAKE NO REPRESENTATION THAT SOFTWARE IS FREE OF INFRINGEMENT OF THIRD PARTY PATENT, COPYRIGHT, OR OTHER PROPRIETARY RIGHTS. DRESDEN UNIVERSITY OF TECHNOLOGY AND INDIANA UNIVERSITY MAKE NO WARRANTIES THAT SOFTWARE IS FREE FROM \"BUGS\", \"VIRUSES\", \"TROJAN HORSES\", \"TRAP DOORS\", \"WORMS\", OR OTHER HARMFUL CODE. LICENSEE ASSUMES THE ENTIRE RISK AS TO THE PERFORMANCE OF SOFTWARE AND/OR ASSOCIATED MATERIALS, AND TO THE PERFORMANCE AND VALIDITY OF INFORMATION GENERATED USING SOFTWARE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/MTLL.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/MTLL.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MTLL.svg