== Mulan Permissive Software License, Version 1 (MulanPSL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Mulan Permissive Software License, Version 1
|Shortname |MulanPSL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/MulanPSL-1.0.json
* https://license.coscl.org.cn/MulanPSL/
* https://github.com/yuwenlong/longphp/blob/25dfb70cc2a466dc4bb55ba30901cbce08d164b5/LICENSE

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/MulanPSL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "MulanPSL-1.0",
        "Mulan Permissive Software License, Version 1"
    ],
    "__impliedId": "MulanPSL-1.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "MulanPSL-1.0"
                ],
                "__impliedId": "MulanPSL-1.0"
            },
            "shortname": "MulanPSL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Mulan Permissive Software License, Version 1",
            "spdxDetailsURL": "http://spdx.org/licenses/MulanPSL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/MulanPSL-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://license.coscl.org.cn/MulanPSL/",
                "https://github.com/yuwenlong/longphp/blob/25dfb70cc2a466dc4bb55ba30901cbce08d164b5/LICENSE"
            ],
            "_implications": {
                "__impliedNames": [
                    "MulanPSL-1.0",
                    "Mulan Permissive Software License, Version 1"
                ],
                "__impliedId": "MulanPSL-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/MulanPSL-1.0.json"
                    ],
                    [
                        null,
                        "https://license.coscl.org.cn/MulanPSL/"
                    ],
                    [
                        null,
                        "https://github.com/yuwenlong/longphp/blob/25dfb70cc2a466dc4bb55ba30901cbce08d164b5/LICENSE"
                    ]
                ]
            },
            "spdxLicenseId": "MulanPSL-1.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/MulanPSL-1.0.json"
        ],
        [
            null,
            "https://license.coscl.org.cn/MulanPSL/"
        ],
        [
            null,
            "https://github.com/yuwenlong/longphp/blob/25dfb70cc2a466dc4bb55ba30901cbce08d164b5/LICENSE"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/MulanPSL-1.0.svg
