== Net-SNMP License (Net-SNMP)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Net-SNMP License
|Shortname |Net-SNMP
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/Net-SNMP.html
* *SPDX:* http://spdx.org/licenses/Net-SNMP.json
* http://net-snmp.sourceforge.net/about/license.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/Net-SNMP.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Net-SNMP",
        "Net-SNMP License"
    ],
    "__impliedId": "Net-SNMP",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Net-SNMP"
                ],
                "__impliedId": "Net-SNMP"
            },
            "shortname": "Net-SNMP",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Net-SNMP License",
            "spdxDetailsURL": "http://spdx.org/licenses/Net-SNMP.json",
            "_sourceURL": "https://spdx.org/licenses/Net-SNMP.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://net-snmp.sourceforge.net/about/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Net-SNMP",
                    "Net-SNMP License"
                ],
                "__impliedId": "Net-SNMP",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Net-SNMP.json"
                    ],
                    [
                        null,
                        "http://net-snmp.sourceforge.net/about/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "Net-SNMP"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Net-SNMP.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Net-SNMP License",
            "id": "Net-SNMP",
            "_implications": {
                "__impliedNames": [
                    "Net-SNMP",
                    "Net-SNMP License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Net-SNMP.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Net-SNMP.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Net-SNMP.json"
        ],
        [
            null,
            "http://net-snmp.sourceforge.net/about/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Net-SNMP.svg
