== NIST Public Domain Notice (NIST-PD)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |NIST Public Domain Notice
|Shortname |NIST-PD
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://nist-pd`

=== Comments on (easy) usability

=== General Comments

=== URLs

* *Homepage:* https://github.com/usnistgov/jsip/blob/master/README#L122
* *SPDX:* http://spdx.org/licenses/NIST-PD.json
* https://github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt
* https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md
* https://github.com/usnistgov/jsip

=== Text

....
Conditions Of Use

This software was developed by employees of the National Institute of
Standards and Technology (NIST), an agency of the Federal Government.
Pursuant to title 15 Untied States Code Section 105, works of NIST
employees are not subject to copyright protection in the United States
and are considered to be in the public domain.  As a result, a formal
license is not needed to use the software.

This software is provided by NIST as a service and is expressly
provided "AS IS."  NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED
OR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT
AND DATA ACCURACY.  NIST does not warrant or make any representations
regarding the use of the software or the results thereof, including but
not limited to the correctness, accuracy, reliability or usefulness of
the software.

Permission to use this software is contingent upon your acceptance
of the terms of this agreement
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/NIST-PD.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/nist-pd.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "NIST-PD",
        "NIST Public Domain Notice",
        "scancode://nist-pd"
    ],
    "__impliedId": "NIST-PD",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "NIST-PD"
                ],
                "__impliedId": "NIST-PD"
            },
            "shortname": "NIST-PD",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "NIST Public Domain Notice",
            "spdxDetailsURL": "http://spdx.org/licenses/NIST-PD.json",
            "_sourceURL": "https://spdx.org/licenses/NIST-PD.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt",
                "https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md"
            ],
            "_implications": {
                "__impliedNames": [
                    "NIST-PD",
                    "NIST Public Domain Notice"
                ],
                "__impliedId": "NIST-PD",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/NIST-PD.json"
                    ],
                    [
                        null,
                        "https://github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt"
                    ],
                    [
                        null,
                        "https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md"
                    ]
                ]
            },
            "spdxLicenseId": "NIST-PD"
        },
        "Scancode": {
            "otherUrls": [
                "https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md",
                "https://github.com/usnistgov/jsip"
            ],
            "homepageUrl": "https://github.com/usnistgov/jsip/blob/master/README#L122",
            "shortName": "NIST Public Domain Notice",
            "textUrls": null,
            "text": "Conditions Of Use\n\nThis software was developed by employees of the National Institute of\nStandards and Technology (NIST), an agency of the Federal Government.\nPursuant to title 15 Untied States Code Section 105, works of NIST\nemployees are not subject to copyright protection in the United States\nand are considered to be in the public domain.  As a result, a formal\nlicense is not needed to use the software.\n\nThis software is provided by NIST as a service and is expressly\nprovided \"AS IS.\"  NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED\nOR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT\nAND DATA ACCURACY.  NIST does not warrant or make any representations\nregarding the use of the software or the results thereof, including but\nnot limited to the correctness, accuracy, reliability or usefulness of\nthe software.\n\nPermission to use this software is contingent upon your acceptance\nof the terms of this agreement",
            "category": "Public Domain",
            "osiUrl": null,
            "owner": "NIST",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/nist-pd.yml",
            "key": "nist-pd",
            "name": "NIST Public Domain Notice",
            "spdxId": "NIST-PD",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://nist-pd",
                    "NIST Public Domain Notice",
                    "NIST-PD"
                ],
                "__impliedId": "NIST-PD",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Conditions Of Use\n\nThis software was developed by employees of the National Institute of\nStandards and Technology (NIST), an agency of the Federal Government.\nPursuant to title 15 Untied States Code Section 105, works of NIST\nemployees are not subject to copyright protection in the United States\nand are considered to be in the public domain.  As a result, a formal\nlicense is not needed to use the software.\n\nThis software is provided by NIST as a service and is expressly\nprovided \"AS IS.\"  NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED\nOR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT\nAND DATA ACCURACY.  NIST does not warrant or make any representations\nregarding the use of the software or the results thereof, including but\nnot limited to the correctness, accuracy, reliability or usefulness of\nthe software.\n\nPermission to use this software is contingent upon your acceptance\nof the terms of this agreement",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://github.com/usnistgov/jsip/blob/master/README#L122"
                    ],
                    [
                        null,
                        "https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md"
                    ],
                    [
                        null,
                        "https://github.com/usnistgov/jsip"
                    ]
                ]
            }
        }
    },
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Conditions Of Use\n\nThis software was developed by employees of the National Institute of\nStandards and Technology (NIST), an agency of the Federal Government.\nPursuant to title 15 Untied States Code Section 105, works of NIST\nemployees are not subject to copyright protection in the United States\nand are considered to be in the public domain.  As a result, a formal\nlicense is not needed to use the software.\n\nThis software is provided by NIST as a service and is expressly\nprovided \"AS IS.\"  NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED\nOR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT\nAND DATA ACCURACY.  NIST does not warrant or make any representations\nregarding the use of the software or the results thereof, including but\nnot limited to the correctness, accuracy, reliability or usefulness of\nthe software.\n\nPermission to use this software is contingent upon your acceptance\nof the terms of this agreement",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/NIST-PD.json"
        ],
        [
            null,
            "https://github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt"
        ],
        [
            null,
            "https://github.com/tcheneau/Routing/blob/f09f46fcfe636107f22f2c98348188a65a135d98/README.md"
        ],
        [
            "Homepage",
            "https://github.com/usnistgov/jsip/blob/master/README#L122"
        ],
        [
            null,
            "https://github.com/usnistgov/jsip"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/NIST-PD.svg
