== Norwegian Licence for Open Government Data (NLOD-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Norwegian Licence for Open Government Data
|Shortname |NLOD-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/NLOD-1.0.json
* http://data.norge.no/nlod/en/1.0

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/NLOD-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "NLOD-1.0",
        "Norwegian Licence for Open Government Data"
    ],
    "__impliedId": "NLOD-1.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "NLOD-1.0"
                ],
                "__impliedId": "NLOD-1.0"
            },
            "shortname": "NLOD-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Norwegian Licence for Open Government Data",
            "spdxDetailsURL": "http://spdx.org/licenses/NLOD-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/NLOD-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://data.norge.no/nlod/en/1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "NLOD-1.0",
                    "Norwegian Licence for Open Government Data"
                ],
                "__impliedId": "NLOD-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/NLOD-1.0.json"
                    ],
                    [
                        null,
                        "http://data.norge.no/nlod/en/1.0"
                    ]
                ]
            },
            "spdxLicenseId": "NLOD-1.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/NLOD-1.0.json"
        ],
        [
            null,
            "http://data.norge.no/nlod/en/1.0"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/NLOD-1.0.svg
