== Netizen Open Source License (NOSL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Netizen Open Source License
|Shortname |NOSL
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/NOSL.json
* http://bits.netizen.com.au/licenses/NOSL/nosl.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/NOSL.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "NOSL",
        "Netizen Open Source License"
    ],
    "__impliedId": "NOSL",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "NOSL"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "NOSL"
                ],
                "__impliedId": "NOSL"
            },
            "shortname": "NOSL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Netizen Open Source License",
            "spdxDetailsURL": "http://spdx.org/licenses/NOSL.json",
            "_sourceURL": "https://spdx.org/licenses/NOSL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://bits.netizen.com.au/licenses/NOSL/nosl.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "NOSL",
                    "Netizen Open Source License"
                ],
                "__impliedId": "NOSL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/NOSL.json"
                    ],
                    [
                        null,
                        "http://bits.netizen.com.au/licenses/NOSL/nosl.txt"
                    ]
                ]
            },
            "spdxLicenseId": "NOSL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://bits.netizen.com.au/licenses/NOSL/nosl.txt",
            "GPLv3 Compat?": null,
            "Short Name": "NOSL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Netizen Open Source License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Netizen Open Source License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "NOSL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "NOSL"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "NOSL",
            "copyleftkind": "WeakCopyleft"
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/NOSL.json"
        ],
        [
            null,
            "http://bits.netizen.com.au/licenses/NOSL/nosl.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/NOSL.svg
