== SIL Open Font License 1.0 with no Reserved Font Name (OFL-1.0-no-RFN)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |SIL Open Font License 1.0 with no Reserved Font Name
|Shortname |OFL-1.0-no-RFN
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/OFL-1.0-no-RFN.json
* http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/OFL-1.0-no-RFN.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OFL-1.0-no-RFN",
        "SIL Open Font License 1.0 with no Reserved Font Name"
    ],
    "__impliedId": "OFL-1.0-no-RFN",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "SIL Open Font License 1.0 with no Reserved Font Name",
            "spdxDetailsURL": "http://spdx.org/licenses/OFL-1.0-no-RFN.json",
            "_sourceURL": "https://spdx.org/licenses/OFL-1.0-no-RFN.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web"
            ],
            "_implications": {
                "__impliedNames": [
                    "OFL-1.0-no-RFN",
                    "SIL Open Font License 1.0 with no Reserved Font Name"
                ],
                "__impliedId": "OFL-1.0-no-RFN",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OFL-1.0-no-RFN.json"
                    ],
                    [
                        null,
                        "http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web"
                    ]
                ]
            },
            "spdxLicenseId": "OFL-1.0-no-RFN"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/OFL-1.0-no-RFN.json"
        ],
        [
            null,
            "http://scripts.sil.org/cms/scripts/page.php?item_id=OFL10_web"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OFL-1.0-no-RFN.svg