== Open Government Licence v1.0 (OGL-UK-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open Government Licence v1.0
|Shortname |OGL-UK-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `Open Government Licence 1.0 (United Kingdom)`

=== Comments on (easy) usability

* **↓**``The license issuperseded'' (source:
https://github.com/okfn/licenses/blob/master/licenses.csv[Open Knowledge
International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0]))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/OGL-UK-1.0.json
* https://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://spdx.org/licenses/OGL-UK-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OGL-UK-1.0",
        "Open Government Licence 1.0 (United Kingdom)",
        "Open Government Licence v1.0"
    ],
    "__impliedId": "OGL-UK-1.0",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "superseded",
            "domain_software": true,
            "url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": true,
            "osd_conformance": "not reviewed",
            "id": "OGL-UK-1.0",
            "title": "Open Government Licence 1.0 (United Kingdom)",
            "_implications": {
                "__impliedNames": [
                    "OGL-UK-1.0",
                    "Open Government Licence 1.0 (United Kingdom)"
                ],
                "__impliedId": "OGL-UK-1.0",
                "__impliedJudgement": [
                    [
                        "Open Knowledge International",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "The license issuperseded"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        null,
                        "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
                    ]
                ]
            },
            "domain_content": true
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OGL-UK-1.0"
                ],
                "__impliedId": "OGL-UK-1.0"
            },
            "shortname": "OGL-UK-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open Government Licence v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/OGL-UK-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/OGL-UK-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
            ],
            "_implications": {
                "__impliedNames": [
                    "OGL-UK-1.0",
                    "Open Government Licence v1.0"
                ],
                "__impliedId": "OGL-UK-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OGL-UK-1.0.json"
                    ],
                    [
                        null,
                        "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
                    ]
                ]
            },
            "spdxLicenseId": "OGL-UK-1.0"
        }
    },
    "__impliedJudgement": [
        [
            "Open Knowledge International",
            {
                "tag": "NegativeJudgement",
                "contents": "The license issuperseded"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OGL-UK-1.0.json"
        ],
        [
            null,
            "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OGL-UK-1.0.svg
