== Open Group Test Suite License (OGTSL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open Group Test Suite License
|Shortname |OGTSL
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `The Open Group Test Suite License (OGTSL)`
* `License :: OSI Approved :: Open Group Test Suite License`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/OGTSL.html[SPDX] (all data [in this
repository] is generated))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↓**``This software licenses which is NOT OKAY for Fedora. Nothing in
Fedora is permitted to use this license. It is either non-free or
deprecated.'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *OSI Page:* https://opensource.org/licenses/OGTSL
* *SPDX:* https://spdx.org/licenses/OGTSL.html
* *SPDX:* http://spdx.org/licenses/OGTSL.json
* http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/OGTSL.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OGTSL",
        "Open Group Test Suite License",
        "The Open Group Test Suite License (OGTSL)",
        "License :: OSI Approved :: Open Group Test Suite License"
    ],
    "__impliedId": "OGTSL",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/OGTSL",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "OGTSL",
            "title": "Open Group Test Suite License",
            "_implications": {
                "__impliedNames": [
                    "OGTSL",
                    "Open Group Test Suite License"
                ],
                "__impliedId": "OGTSL",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/OGTSL"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OGTSL"
                ],
                "__impliedId": "OGTSL"
            },
            "shortname": "OGTSL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open Group Test Suite License",
            "spdxDetailsURL": "http://spdx.org/licenses/OGTSL.json",
            "_sourceURL": "https://spdx.org/licenses/OGTSL.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt",
                "https://opensource.org/licenses/OGTSL"
            ],
            "_implications": {
                "__impliedNames": [
                    "OGTSL",
                    "Open Group Test Suite License"
                ],
                "__impliedId": "OGTSL",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OGTSL.json"
                    ],
                    [
                        null,
                        "http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/OGTSL"
                    ]
                ]
            },
            "spdxLicenseId": "OGTSL"
        },
        "Fedora Project Wiki": {
            "rating": "Bad",
            "Upstream URL": "http://opensource.org/licenses/opengroup.php",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Open Group Test Suite License",
            "FSF Free?": "No",
            "_implications": {
                "__impliedNames": [
                    "Open Group Test Suite License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
                        }
                    ]
                ]
            },
            "Notes": "Same flaws as Artistic 1.0"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Open Group Test Suite License",
            "commercialUse": true,
            "spdxId": "OGTSL",
            "_implications": {
                "__impliedNames": [
                    "OGTSL"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/OGTSL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Open Group Test Suite License",
            "id": "OGTSL",
            "_implications": {
                "__impliedNames": [
                    "OGTSL",
                    "Open Group Test Suite License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/OGTSL.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/OGTSL",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "OGTSL",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Open Group Test Suite License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The Open Group Test Suite License (OGTSL)",
            "other_names": [],
            "keywords": [
                "osi-approved"
            ],
            "id": "OGTSL",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/OGTSL"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "OGTSL",
                    "The Open Group Test Suite License (OGTSL)",
                    "OGTSL",
                    "License :: OSI Approved :: Open Group Test Suite License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/OGTSL"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "NegativeJudgement",
                "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/OGTSL.html"
        ],
        [
            null,
            "https://opensource.org/licenses/OGTSL"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/OGTSL"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OGTSL.json"
        ],
        [
            null,
            "http://www.opengroup.org/testing/downloads/The_Open_Group_TSL.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OGTSL.svg
