== Open LDAP Public License v2.3 (OLDAP-2.3)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open LDAP Public License v2.3
|Shortname |OLDAP-2.3
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/OLDAP-2.3.html
* *SPDX:* http://spdx.org/licenses/OLDAP-2.3.json
* http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/OLDAP-2.3.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OLDAP-2.3",
        "Open LDAP Public License v2.3"
    ],
    "__impliedId": "OLDAP-2.3",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OLDAP-2.3"
                ],
                "__impliedId": "OLDAP-2.3"
            },
            "shortname": "OLDAP-2.3",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open LDAP Public License v2.3",
            "spdxDetailsURL": "http://spdx.org/licenses/OLDAP-2.3.json",
            "_sourceURL": "https://spdx.org/licenses/OLDAP-2.3.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3"
            ],
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.3",
                    "Open LDAP Public License v2.3"
                ],
                "__impliedId": "OLDAP-2.3",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OLDAP-2.3.json"
                    ],
                    [
                        null,
                        "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3"
                    ]
                ]
            },
            "spdxLicenseId": "OLDAP-2.3"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "OLDAP-2.3"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "OLDAP-2.3",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/OLDAP-2.3.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Open LDAP Public License v2.3",
            "id": "OLDAP-2.3",
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.3",
                    "Open LDAP Public License v2.3"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/OLDAP-2.3.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/OLDAP-2.3.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OLDAP-2.3.json"
        ],
        [
            null,
            "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=d32cf54a32d581ab475d23c810b0a7fbaf8d63c3"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OLDAP-2.3.svg
