== Open LDAP Public License v2.0.1 (OLDAP-2.0.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open LDAP Public License v2.0.1
|Shortname |OLDAP-2.0.1
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `scancode://openldap-2.0.1`
* `OpenLDAP Public License 2.0.1`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``Per SPDX.org, this license was released 21 December 1999. This
license is the same as 2.0 with the word "registered" removed from in
front of "trademark." '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openldap-2.0.1.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:*
http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e
* *SPDX:* https://spdx.org/licenses/OLDAP-2.0.1.html
* *SPDX:* http://spdx.org/licenses/OLDAP-2.0.1.json

=== Text

....
The OpenLDAP Public License 

Version 2.0.1, 21 December 1999 
Copyright 1999, The OpenLDAP Foundation, Redwood City, California, USA. 
All Rights Reserved. 

Redistribution and use of this software and associated documentation 
("Software"), with or without modification, are permitted provided 
that the following conditions are met: 

1. Redistributions of source code must retain copyright 
statements and notices. Redistributions must also contain a 
copy of this document. 

2. Redistributions in binary form must reproduce the 
above copyright notice, this list of conditions and the 
following disclaimer in the documentation and/or other 
materials provided with the distribution. 

3. The name "OpenLDAP" must not be used to endorse or promote 
products derived from this Software without prior written 
permission of the OpenLDAP Foundation. For written permission, 
please contact foundation@openldap.org. 

4. Products derived from this Software may not be called "OpenLDAP" 
nor may "OpenLDAP" appear in their names without prior written 
permission of the OpenLDAP Foundation. OpenLDAP is a trademark 
of the OpenLDAP Foundation. 

5. Due credit should be given to the OpenLDAP Project 
(http://www.openldap.org/). 

THIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS 
``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT 
NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
THE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/OLDAP-2.0.1.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openldap-2.0.1.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "OLDAP-2.0.1",
        "Open LDAP Public License v2.0.1",
        "scancode://openldap-2.0.1",
        "OpenLDAP Public License 2.0.1"
    ],
    "__impliedId": "OLDAP-2.0.1",
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per SPDX.org, this license was released 21 December 1999. This license is\nthe same as 2.0 with the word \"registered\" removed from in front of\n\"trademark.\"\n"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OLDAP-2.0.1"
                ],
                "__impliedId": "OLDAP-2.0.1"
            },
            "shortname": "OLDAP-2.0.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open LDAP Public License v2.0.1",
            "spdxDetailsURL": "http://spdx.org/licenses/OLDAP-2.0.1.json",
            "_sourceURL": "https://spdx.org/licenses/OLDAP-2.0.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"
            ],
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.0.1",
                    "Open LDAP Public License v2.0.1"
                ],
                "__impliedId": "OLDAP-2.0.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OLDAP-2.0.1.json"
                    ],
                    [
                        null,
                        "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"
                    ]
                ]
            },
            "spdxLicenseId": "OLDAP-2.0.1"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e",
            "shortName": "OpenLDAP Public License 2.0.1",
            "textUrls": null,
            "text": "The OpenLDAP Public License \n\nVersion 2.0.1, 21 December 1999 \nCopyright 1999, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "OpenLDAP Foundation",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openldap-2.0.1.yml",
            "key": "openldap-2.0.1",
            "name": "OpenLDAP Public License 2.0.1",
            "spdxId": "OLDAP-2.0.1",
            "notes": "Per SPDX.org, this license was released 21 December 1999. This license is\nthe same as 2.0 with the word \"registered\" removed from in front of\n\"trademark.\"\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://openldap-2.0.1",
                    "OpenLDAP Public License 2.0.1",
                    "OLDAP-2.0.1"
                ],
                "__impliedId": "OLDAP-2.0.1",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license was released 21 December 1999. This license is\nthe same as 2.0 with the word \"registered\" removed from in front of\n\"trademark.\"\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The OpenLDAP Public License \n\nVersion 2.0.1, 21 December 1999 \nCopyright 1999, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "OLDAP-2.0.1"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "OLDAP-2.0.1",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/OLDAP-2.0.1.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Open LDAP Public License v2.0.1",
            "id": "OLDAP-2.0.1",
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.0.1",
                    "Open LDAP Public License v2.0.1"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/OLDAP-2.0.1.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "The OpenLDAP Public License \n\nVersion 2.0.1, 21 December 1999 \nCopyright 1999, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/OLDAP-2.0.1.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OLDAP-2.0.1.json"
        ],
        [
            null,
            "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"
        ],
        [
            "Homepage",
            "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b6d68acd14e51ca3aab4428bf26522aa74873f0e"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OLDAP-2.0.1.svg
