== Open LDAP Public License v2.1 (OLDAP-2.1)

[cols=",",options="header",]
|=======================================
|Key |Value
|Fullname |Open LDAP Public License v2.1
|Shortname |OLDAP-2.1
|Rating |Go
|Classification |NoCopyleft
|=======================================

*Other Names:*

* `openldap-2.1`
* `OpenLDAP Public License 2.1`

=== Comments on (easy) usability

* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== URLs

* *Homepage:*
http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715
* *SPDX:* http://spdx.org/licenses/OLDAP-2.1.json
* *SPDX:* https://spdx.org/licenses/OLDAP-2.1.html

=== Text

....
The OpenLDAP Public License 

Version 2.1, 29 February 2000 
Copyright 1999-2000, The OpenLDAP Foundation, Redwood City, California, USA. 
All Rights Reserved. 

Redistribution and use of this software and associated documentation 
("Software"), with or without modification, are permitted provided 
that the following conditions are met: 

1. Redistributions of source code must retain copyright 
statements and notices. Redistributions must also contain a 
copy of this document. 

2. Redistributions in binary form must reproduce the 
above copyright notice, this list of conditions and the 
following disclaimer in the documentation and/or other 
materials provided with the distribution. 

3. The name "OpenLDAP" must not be used to endorse or promote 
products derived from this Software without prior written 
permission of the OpenLDAP Foundation. For written permission, 
please contact foundation@openldap.org. 

4. Products derived from this Software may not be called "OpenLDAP" 
nor may "OpenLDAP" appear in their names without prior written 
permission of the OpenLDAP Foundation. OpenLDAP is a trademark 
of the OpenLDAP Foundation. 

5. Due credit should be given to the OpenLDAP Project 
(http://www.openldap.org/). 

6. The OpenLDAP Foundation may revise this license from time to 
time. Each revision is distinguished by a version number. You 
may use the Software under terms of this license revision or under 
the terms of any subsequent license revision. 

THIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS 
``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT 
NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
THE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "OLDAP-2.1",
        "Open LDAP Public License v2.1",
        "openldap-2.1",
        "OpenLDAP Public License 2.1"
    ],
    "__impliedId": "OLDAP-2.1",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OLDAP-2.1",
                    "OLDAP-2.1",
                    "Open LDAP Public License v2.1",
                    "openldap-2.1",
                    "OpenLDAP Public License 2.1"
                ],
                "__impliedId": "OLDAP-2.1"
            },
            "shortname": "OLDAP-2.1",
            "otherNames": [
                "OLDAP-2.1",
                "Open LDAP Public License v2.1",
                "openldap-2.1",
                "OpenLDAP Public License 2.1"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open LDAP Public License v2.1",
            "spdxDetailsURL": "http://spdx.org/licenses/OLDAP-2.1.json",
            "_sourceURL": "https://spdx.org/licenses/OLDAP-2.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"
            ],
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.1",
                    "Open LDAP Public License v2.1"
                ],
                "__impliedId": "OLDAP-2.1",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OLDAP-2.1.json"
                    ],
                    [
                        null,
                        "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"
                    ]
                ]
            },
            "spdxLicenseId": "OLDAP-2.1"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715",
            "shortName": "OpenLDAP Public License 2.1",
            "textUrls": null,
            "text": "The OpenLDAP Public License \n\nVersion 2.1, 29 February 2000 \nCopyright 1999-2000, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\n6. The OpenLDAP Foundation may revise this license from time to \ntime. Each revision is distinguished by a version number. You \nmay use the Software under terms of this license revision or under \nthe terms of any subsequent license revision. \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "OpenLDAP Foundation",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openldap-2.1.yml",
            "key": "openldap-2.1",
            "name": "OpenLDAP Public License 2.1",
            "spdxId": "OLDAP-2.1",
            "_implications": {
                "__impliedNames": [
                    "openldap-2.1",
                    "OpenLDAP Public License 2.1",
                    "OLDAP-2.1"
                ],
                "__impliedId": "OLDAP-2.1",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "The OpenLDAP Public License \n\nVersion 2.1, 29 February 2000 \nCopyright 1999-2000, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\n6. The OpenLDAP Foundation may revise this license from time to \ntime. Each revision is distinguished by a version number. You \nmay use the Software under terms of this license revision or under \nthe terms of any subsequent license revision. \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/OLDAP-2.1.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Open LDAP Public License v2.1",
            "id": "OLDAP-2.1",
            "_implications": {
                "__impliedNames": [
                    "OLDAP-2.1"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/OLDAP-2.1.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "The OpenLDAP Public License \n\nVersion 2.1, 29 February 2000 \nCopyright 1999-2000, The OpenLDAP Foundation, Redwood City, California, USA. \nAll Rights Reserved. \n\nRedistribution and use of this software and associated documentation \n(\"Software\"), with or without modification, are permitted provided \nthat the following conditions are met: \n\n1. Redistributions of source code must retain copyright \nstatements and notices. Redistributions must also contain a \ncopy of this document. \n\n2. Redistributions in binary form must reproduce the \nabove copyright notice, this list of conditions and the \nfollowing disclaimer in the documentation and/or other \nmaterials provided with the distribution. \n\n3. The name \"OpenLDAP\" must not be used to endorse or promote \nproducts derived from this Software without prior written \npermission of the OpenLDAP Foundation. For written permission, \nplease contact foundation@openldap.org. \n\n4. Products derived from this Software may not be called \"OpenLDAP\" \nnor may \"OpenLDAP\" appear in their names without prior written \npermission of the OpenLDAP Foundation. OpenLDAP is a trademark \nof the OpenLDAP Foundation. \n\n5. Due credit should be given to the OpenLDAP Project \n(http://www.openldap.org/). \n\n6. The OpenLDAP Foundation may revise this license from time to \ntime. Each revision is distinguished by a version number. You \nmay use the Software under terms of this license revision or under \nthe terms of any subsequent license revision. \n\nTHIS SOFTWARE IS PROVIDED BY THE OPENLDAP FOUNDATION AND CONTRIBUTORS \n``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT \nNOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND \nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL \nTHE OPENLDAP FOUNDATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) \nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, \nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED \nOF THE POSSIBILITY OF SUCH DAMAGE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/OLDAP-2.1.json"
        ],
        [
            null,
            "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/OLDAP-2.1.html"
        ],
        [
            "Homepage",
            "http://www.openldap.org/devel/gitweb.cgi?p=openldap.git;a=blob;f=LICENSE;hb=b0d176738e96a0d3b9f85cb51e140a86f21be715"
        ]
    ]
}
....