== OpenSSL License (OpenSSL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |OpenSSL License
|Shortname |OpenSSL
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |False
|===

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/OpenSSL.html
* *SPDX:* http://spdx.org/licenses/OpenSSL.json
* *open-license:* http://open-license.hitachi.com/licenses/279
* http://www.openssl.org/source/license.html

=== Description from open-license

* {blank}
+
....
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use binaries generated from modified source code

Conditions: None
....
* {blank}
+
....
Description: Acknowledgements include "This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/)."
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribution of Modified Source Code

Conditions:
AND
  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license
  OBLIGATION: Acknowledgements

....
* {blank}
+
....
Description: Acknowledgements include "This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/)."
Actions:
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribute the generated binaries from modified source code

Conditions:
AND
  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license
  OBLIGATION: Acknowledgements

....
* {blank}
+
....
Description: Acknowledgements include "This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/)."
Actions:
- Create an advertising medium that describes the features and use of the software

Conditions:
OBLIGATION: Acknowledgements
....
* {blank}
+
....
Description: "OpenSSL Toolkit" and "OpenSSL Project". openssl-core@openssl.orgに連絡する.
Actions:
- Use the name to endorse and promote derived products

Conditions:
REQUISITE: Get special permission in writing.
....
* {blank}
+
....
Description: To use the name "OpenSSL". Get written permission from the OpenSSL Project.
Actions:
- Use the name of the product or part of the name of the product from which it was derived

Conditions:
REQUISITE: Get special permission in writing.
....

(source: Hitachi open-license)

=== Text

....
 OpenSSL License
  ---------------

/* ====================================================================
 * Copyright (c) <year> The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/finos/OSLC-handbook/blob/master/src/OpenSSL.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/OpenSSL.html[SPDX] (all data [in this
repository] is generated)
* https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses[Wikipedia]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])

==== Raw JSON

....
{
    "__impliedNames": [
        "OpenSSL",
        "OpenSSL License",
        "OpenSSL license"
    ],
    "__impliedId": "OpenSSL",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "OpenSSL"
    ],
    "__hasPatentHint": false,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OpenSSL"
                ],
                "__impliedId": "OpenSSL"
            },
            "shortname": "OpenSSL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "OpenSSL License",
            "spdxDetailsURL": "http://spdx.org/licenses/OpenSSL.json",
            "_sourceURL": "https://spdx.org/licenses/OpenSSL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.openssl.org/source/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "OpenSSL",
                    "OpenSSL License"
                ],
                "__impliedId": "OpenSSL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OpenSSL.json"
                    ],
                    [
                        null,
                        "http://www.openssl.org/source/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "OpenSSL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.sdisw.com/openssl.htm",
            "GPLv3 Compat?": "NO",
            "Short Name": "OpenSSL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "OpenSSL License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "OpenSSL License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "OpenSSL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "OpenSSL"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "OpenSSL",
            "copyleftkind": "NoCopyleft"
        },
        "Hitachi open-license": {
            "notices": [
                {
                    "content": "the software is provided by the openssl project \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "Neither the OpenSSL Project nor any contributor, for any cause whatsoever, shall be liable for any damages, regardless of how caused, and regardless of whether the basis of liability is contract, strict liability, or tort (including negligence), even if they have been advised of the possibility of such damages, for the software For any direct, indirect, special, incidental, punitive or consequential damages (including, but not limited to, compensation for procurement of replacement or substitute services, loss of use, loss of data, loss of profits, or business interruption) arising out of the use of ) shall not be liable in any way (including"
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/279",
            "content": " OpenSSL License\n  ---------------\n\n/* ====================================================================\n * Copyright (c) <year> The OpenSSL Project.  All rights reserved.\n *\n * Redistribution and use in source and binary forms, with or without\n * modification, are permitted provided that the following conditions\n * are met:\n *\n * 1. Redistributions of source code must retain the above copyright\n *    notice, this list of conditions and the following disclaimer.\n *\n * 2. Redistributions in binary form must reproduce the above copyright\n *    notice, this list of conditions and the following disclaimer in\n *    the documentation and/or other materials provided with the\n *    distribution.\n *\n * 3. All advertising materials mentioning features or use of this\n *    software must display the following acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n *\n * 4. The names \"OpenSSL Toolkit\" and \"OpenSSL Project\" must not be used to\n *    endorse or promote products derived from this software without\n *    prior written permission. For written permission, please contact\n *    openssl-core@openssl.org.\n *\n * 5. Products derived from this software may not be called \"OpenSSL\"\n *    nor may \"OpenSSL\" appear in their names without prior written\n *    permission of the OpenSSL Project.\n *\n * 6. Redistributions of any form whatsoever must retain the following\n *    acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n *\n * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n * OF THE POSSIBILITY OF SUCH DAMAGE.\n * ====================================================================\n *\n * This product includes cryptographic software written by Eric Young\n * (eay@cryptsoft.com).  This product includes software written by Tim\n * Hudson (tjh@cryptsoft.com).\n *\n */",
            "name": "OpenSSL License",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use binaries generated from modified source code\n\nConditions: None\n",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "Description: Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\"\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n\nConditions:\nAND\n  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer included in the license\n  OBLIGATION: Acknowledgements\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\""
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "Description: Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\"\nActions:\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribute the generated binaries from modified source code\n\nConditions:\nAND\n  OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license\n  OBLIGATION: Acknowledgements\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\""
                },
                {
                    "actions": [
                        {
                            "name": "Create an advertising medium that describes the features and use of the software"
                        }
                    ],
                    "_str": "Description: Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\"\nActions:\n- Create an advertising medium that describes the features and use of the software\n\nConditions:\nOBLIGATION: Acknowledgements\n",
                    "conditions": {
                        "name": "Acknowledgements",
                        "type": "OBLIGATION"
                    },
                    "description": "Acknowledgements include \"This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).\""
                },
                {
                    "actions": [
                        {
                            "name": "Use the name to endorse and promote derived products"
                        }
                    ],
                    "_str": "Description: \"OpenSSL Toolkit\" and \"OpenSSL Project\". openssl-core@openssl.orgに連絡する.\nActions:\n- Use the name to endorse and promote derived products\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "\"OpenSSL Toolkit\" and \"OpenSSL Project\". openssl-core@openssl.orgに連絡する."
                },
                {
                    "actions": [
                        {
                            "name": "Use the name of the product or part of the name of the product from which it was derived"
                        }
                    ],
                    "_str": "Description: To use the name \"OpenSSL\". Get written permission from the OpenSSL Project.\nActions:\n- Use the name of the product or part of the name of the product from which it was derived\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "To use the name \"OpenSSL\". Get written permission from the OpenSSL Project."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "OpenSSL License"
                ],
                "__impliedText": " OpenSSL License\n  ---------------\n\n/* ====================================================================\n * Copyright (c) <year> The OpenSSL Project.  All rights reserved.\n *\n * Redistribution and use in source and binary forms, with or without\n * modification, are permitted provided that the following conditions\n * are met:\n *\n * 1. Redistributions of source code must retain the above copyright\n *    notice, this list of conditions and the following disclaimer.\n *\n * 2. Redistributions in binary form must reproduce the above copyright\n *    notice, this list of conditions and the following disclaimer in\n *    the documentation and/or other materials provided with the\n *    distribution.\n *\n * 3. All advertising materials mentioning features or use of this\n *    software must display the following acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n *\n * 4. The names \"OpenSSL Toolkit\" and \"OpenSSL Project\" must not be used to\n *    endorse or promote products derived from this software without\n *    prior written permission. For written permission, please contact\n *    openssl-core@openssl.org.\n *\n * 5. Products derived from this software may not be called \"OpenSSL\"\n *    nor may \"OpenSSL\" appear in their names without prior written\n *    permission of the OpenSSL Project.\n *\n * 6. Redistributions of any form whatsoever must retain the following\n *    acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n *\n * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n * OF THE POSSIBILITY OF SUCH DAMAGE.\n * ====================================================================\n *\n * This product includes cryptographic software written by Eric Young\n * (eay@cryptsoft.com).  This product includes software written by Tim\n * Hudson (tjh@cryptsoft.com).\n *\n */",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/279"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/OpenSSL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "OpenSSL License",
            "id": "OpenSSL",
            "_implications": {
                "__impliedNames": [
                    "OpenSSL",
                    "OpenSSL License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/OpenSSL.html"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Permissive",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": null,
            "Coordinates": {
                "name": "OpenSSL license",
                "version": null,
                "spdxId": "OpenSSL"
            },
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "_implications": {
                "__impliedNames": [
                    "OpenSSL",
                    "OpenSSL license"
                ],
                "__hasPatentHint": false
            },
            "Modification": {
                "value": "Permissive",
                "description": "modification of the code by a licensee"
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copyright notice",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Acknowledgement must be included for any redistribution",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "Include acknowledgement in advertising mentioning features or use",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "Include acknowledgement in advertising mentioning features or use. \"The word 'cryptographic' can be left out if the rouines from the library being used are not cryptographic related\".",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "Include acknowledgement If you include any Windows specific code (or a derivative thereof) from the apps directory (application code)",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Name of project cannot be used for derived products without permission",
                    "termComplianceNotes": null,
                    "termType": "condition"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/OpenSSL.yaml",
            "name": "OpenSSL License",
            "nameFromFilename": "OpenSSL",
            "notes": "This license is actually a set of two licenses, which have similar text and requirements but different copyright holders and therefore different acknowledgment text. Some requirements to include acknowledgements may only apply if you are using that part of the project written by a specific copyright holder.",
            "_implications": {
                "__impliedNames": [
                    "OpenSSL",
                    "OpenSSL License"
                ]
            },
            "licenseId": [
                "OpenSSL",
                "OpenSSL License"
            ]
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "OpenSSL",
            "_implications": {
                "__impliedNames": [
                    "OpenSSL"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": " OpenSSL License\n  ---------------\n\n/* ====================================================================\n * Copyright (c) <year> The OpenSSL Project.  All rights reserved.\n *\n * Redistribution and use in source and binary forms, with or without\n * modification, are permitted provided that the following conditions\n * are met:\n *\n * 1. Redistributions of source code must retain the above copyright\n *    notice, this list of conditions and the following disclaimer.\n *\n * 2. Redistributions in binary form must reproduce the above copyright\n *    notice, this list of conditions and the following disclaimer in\n *    the documentation and/or other materials provided with the\n *    distribution.\n *\n * 3. All advertising materials mentioning features or use of this\n *    software must display the following acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)\"\n *\n * 4. The names \"OpenSSL Toolkit\" and \"OpenSSL Project\" must not be used to\n *    endorse or promote products derived from this software without\n *    prior written permission. For written permission, please contact\n *    openssl-core@openssl.org.\n *\n * 5. Products derived from this software may not be called \"OpenSSL\"\n *    nor may \"OpenSSL\" appear in their names without prior written\n *    permission of the OpenSSL Project.\n *\n * 6. Redistributions of any form whatsoever must retain the following\n *    acknowledgment:\n *    \"This product includes software developed by the OpenSSL Project\n *    for use in the OpenSSL Toolkit (http://www.openssl.org/)\"\n *\n * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY\n * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR\n * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n * OF THE POSSIBILITY OF SUCH DAMAGE.\n * ====================================================================\n *\n * This product includes cryptographic software written by Eric Young\n * (eay@cryptsoft.com).  This product includes software written by Tim\n * Hudson (tjh@cryptsoft.com).\n *\n */",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/OpenSSL.html"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/279"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OpenSSL.json"
        ],
        [
            null,
            "http://www.openssl.org/source/license.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OpenSSL.svg
