== Open Public License v1.0 (OPL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open Public License v1.0
|Shortname |OPL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↓**``This license is not compatible with the
DebianFreeSoftwareGuidelines (DFSG-unfree)'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/OPL-1.0.json
* http://old.koalateam.com/jackaroo/OPL_1_0.TXT
* https://fedoraproject.org/wiki/Licensing/Open_Public_License

'''''

=== Raw Data

==== Facts

* LicenseName
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://spdx.org/licenses/OPL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OPL-1.0",
        "Open Public License v1.0"
    ],
    "__impliedId": "OPL-1.0",
    "__impliedAmbiguousNames": [
        "Open Publication License (OPL) v1.0"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OPL-1.0"
                ],
                "__impliedId": "OPL-1.0"
            },
            "shortname": "OPL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open Public License v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/OPL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/OPL-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://old.koalateam.com/jackaroo/OPL_1_0.TXT",
                "https://fedoraproject.org/wiki/Licensing/Open_Public_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "OPL-1.0",
                    "Open Public License v1.0"
                ],
                "__impliedId": "OPL-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OPL-1.0.json"
                    ],
                    [
                        null,
                        "http://old.koalateam.com/jackaroo/OPL_1_0.TXT"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Open_Public_License"
                    ]
                ]
            },
            "spdxLicenseId": "OPL-1.0"
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Open Publication License (OPL) v1.0",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "OPL-1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Open Publication License (OPL) v1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "OPL-1.0"
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
            }
        ]
    ],
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/OPL-1.0.json"
        ],
        [
            null,
            "http://old.koalateam.com/jackaroo/OPL_1_0.TXT"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Open_Public_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OPL-1.0.svg
