== OSET Public License version 2.1 (OSET-PL-2.1)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |OSET Public License version 2.1
|Shortname |OSET-PL-2.1
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/OSET-PL-2.1.html[SPDX] (all data [in this
repository] is generated))

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/OSET-PL-2.1.json
* http://www.osetfoundation.org/public-license
* https://opensource.org/licenses/OPL-2.1

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/OSET-PL-2.1.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OSET-PL-2.1",
        "OSET Public License version 2.1"
    ],
    "__impliedId": "OSET-PL-2.1",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OSET-PL-2.1"
                ],
                "__impliedId": "OSET-PL-2.1"
            },
            "shortname": "OSET-PL-2.1",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "OSET Public License version 2.1",
            "spdxDetailsURL": "http://spdx.org/licenses/OSET-PL-2.1.json",
            "_sourceURL": "https://spdx.org/licenses/OSET-PL-2.1.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.osetfoundation.org/public-license",
                "https://opensource.org/licenses/OPL-2.1"
            ],
            "_implications": {
                "__impliedNames": [
                    "OSET-PL-2.1",
                    "OSET Public License version 2.1"
                ],
                "__impliedId": "OSET-PL-2.1",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OSET-PL-2.1.json"
                    ],
                    [
                        null,
                        "http://www.osetfoundation.org/public-license"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/OPL-2.1"
                    ]
                ]
            },
            "spdxLicenseId": "OSET-PL-2.1"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "OSET Public License version 2.1",
            "commercialUse": true,
            "spdxId": "OSET-PL-2.1",
            "_implications": {
                "__impliedNames": [
                    "OSET-PL-2.1"
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/OSET-PL-2.1.json"
        ],
        [
            null,
            "http://www.osetfoundation.org/public-license"
        ],
        [
            null,
            "https://opensource.org/licenses/OPL-2.1"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OSET-PL-2.1.svg
