== Open Software License 1.0 (OSL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Open Software License 1.0
|Shortname |OSL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |SaaSCopyleft
|===

*Other Names:*

* `Open Software License, Version 1.0`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/OSL-1.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Google Classification is RESTRICTED'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))

=== General Comments

* ``In addition to the requirements of strong copyleft licenses, network
copyleft licenses require you to share larger programs that you build
with the licensed software not just when you give copies to others, but
also when you run the software for others to use over the Internet or
another network.'' (source: https://blueoakcouncil.org/copyleft[BlueOak
License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* ``Strong copyleft licenses require you to share both the licensed
software (like the weak copyleft licenses, and larger programs that you
build with the licensed software, when you give copies to others.''
(source: https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *OSI Page:* https://opensource.org/licenses/OSL-1.0
* *SPDX:* http://spdx.org/licenses/OSL-1.0.json
* https://spdx.org/licenses/OSL-1.0.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/librariesio/license-compatibility/blob/master/lib/license/licenses.json[librariesio
license-compatibility]
(https://github.com/librariesio/license-compatibility/blob/master/LICENSE.txt[MIT])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/OSL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "OSL-1.0",
        "Open Software License 1.0",
        "Open Software License, Version 1.0"
    ],
    "__impliedId": "OSL-1.0",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Open Software License",
        "OSL 1.0"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "OSL-1.0"
                ],
                "__impliedId": "OSL-1.0"
            },
            "shortname": "OSL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Open Software License 1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/OSL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/OSL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/OSL-1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "OSL-1.0",
                    "Open Software License 1.0"
                ],
                "__impliedId": "OSL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/OSL-1.0.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/OSL-1.0"
                    ]
                ]
            },
            "spdxLicenseId": "OSL-1.0"
        },
        "librariesio license-compatibility": {
            "implications": {
                "__impliedNames": [
                    "OSL-1.0"
                ],
                "__impliedCopyleft": [
                    [
                        "librariesio license-compatibility",
                        "SaaSCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "SaaSCopyleft"
            },
            "licensename": "OSL-1.0",
            "copyleftkind": "SaaSCopyleft"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.opensource.org/licenses/osl-1.0.txt",
            "GPLv3 Compat?": "NO",
            "Short Name": "OSL 1.0",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Open Software License 1.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Open Software License 1.0"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "OSL 1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "OSL-1.0"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "StrongCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "StrongCopyleft"
            },
            "licensename": "OSL-1.0",
            "copyleftkind": "StrongCopyleft"
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/OSL-1.0.html",
            "familyName": "Open Software License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "Open Software License 1.0",
            "id": "OSL-1.0",
            "_implications": {
                "__impliedNames": [
                    "OSL-1.0",
                    "Open Software License 1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Open Software License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                            "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "SaaSCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "SaaSCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/OSL-1.0.html"
                    ]
                ]
            },
            "CopyleftKind": "SaaSCopyleft"
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/OSL-1.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "OSL-1.0",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": "OLS-3.0",
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "Open Software License, Version 1.0",
            "other_names": [],
            "keywords": [
                "osi-approved",
                "discouraged",
                "redundant"
            ],
            "id": "OSL-1.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/OSL-1.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "OSL-1.0",
                    "Open Software License, Version 1.0",
                    "OSL-1.0"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/OSL-1.0"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "RESTRICTED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "OSL-1.0",
            "_implications": {
                "__impliedNames": [
                    "OSL-1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is RESTRICTED"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is RESTRICTED"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "SaaSCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "StrongCopyleft"
        ],
        [
            "librariesio license-compatibility",
            "SaaSCopyleft"
        ]
    ],
    "__calculatedCopyleft": "SaaSCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/OSL-1.0.html"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/OSL-1.0"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/OSL-1.0.json"
        ],
        [
            null,
            "https://opensource.org/licenses/OSL-1.0"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/OSL-1.0.svg
