== The Parity Public License 7.0.0 (Parity-7.0.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |The Parity Public License 7.0.0
|Shortname |Parity-7.0.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |MaximalCopyleft
|===

=== Comments on (easy) usability

=== General Comments

* ``Maximal copyleft licenses answer the question “When does the license
require you to share?” differently than other families. Maximal copyleft
licenses require you to share software you make with others, and to
license that software alike when you do.'' (source:
https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *SPDX:* http://spdx.org/licenses/Parity-7.0.0.json
* https://spdx.org/licenses/Parity-7.0.0.html
* https://paritylicense.com/versions/7.0.0.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/Parity-7.0.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Parity-7.0.0",
        "The Parity Public License 7.0.0"
    ],
    "__impliedId": "Parity-7.0.0",
    "__impliedAmbiguousNames": [
        "The Parity Public License"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "Maximal copyleft licenses answer the question “When does the license require you to share?” differently than other families. Maximal copyleft licenses require you to share software you make with others, and to license that software alike when you do."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Parity-7.0.0"
                ],
                "__impliedId": "Parity-7.0.0"
            },
            "shortname": "Parity-7.0.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "The Parity Public License 7.0.0",
            "spdxDetailsURL": "http://spdx.org/licenses/Parity-7.0.0.json",
            "_sourceURL": "https://spdx.org/licenses/Parity-7.0.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://paritylicense.com/versions/7.0.0.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Parity-7.0.0",
                    "The Parity Public License 7.0.0"
                ],
                "__impliedId": "Parity-7.0.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Parity-7.0.0.json"
                    ],
                    [
                        null,
                        "https://paritylicense.com/versions/7.0.0.html"
                    ]
                ]
            },
            "spdxLicenseId": "Parity-7.0.0"
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/Parity-7.0.0.html",
            "familyName": "The Parity Public License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "The Parity Public License 7.0.0",
            "id": "Parity-7.0.0",
            "_implications": {
                "__impliedNames": [
                    "Parity-7.0.0",
                    "The Parity Public License 7.0.0"
                ],
                "__impliedAmbiguousNames": [
                    "The Parity Public License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "Maximal copyleft licenses answer the question “When does the license require you to share?” differently than other families. Maximal copyleft licenses require you to share software you make with others, and to license that software alike when you do."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "MaximalCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "MaximalCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/Parity-7.0.0.html"
                    ]
                ]
            },
            "CopyleftKind": "MaximalCopyleft"
        }
    },
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "MaximalCopyleft"
        ]
    ],
    "__calculatedCopyleft": "MaximalCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/Parity-7.0.0.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Parity-7.0.0.json"
        ],
        [
            null,
            "https://paritylicense.com/versions/7.0.0.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Parity-7.0.0.svg
