== PHP License v3.0 (PHP-3.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |PHP License v3.0
|Shortname |PHP-3.0
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://php-3.0+`
* `+PHP License 3.0+`
* `+The PHP License, Version 3.0+`
* `+PHP License, version 3.0+`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/PHP-3.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``Per SPDX.org, this license is OSI certified.'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/php-3.0.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* http://www.php.net/license/
* *OSI Page:* http://www.opensource.org/licenses/php.html
* *OSI Page:* https://opensource.org/licenses/PHP-3.0
* *SPDX:* http://spdx.org/licenses/PHP-3.0.json
* *SPDX:* https://spdx.org/licenses/PHP-3.0.html
* *open-license:* http://open-license.hitachi.com/licenses/811
* http://www.php.net/license/3_0.txt
* http://www.opensource.org/licenses/PHP-3.0

=== Description from open-license

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/1", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/1", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/3", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/3", _action_name = Modify the obtained source code., _action_description = },OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/4", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/4", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/6", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/6", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/8", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/8", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing}
....

....
OlPermission {_permission_summary = , _permission_description = Acknowledgements include "This product includes PHP, freely available from <http://www.php.net/>", _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/9", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/9", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/12", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/12", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/1", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/1", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/13", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/13", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])}
....

....
OlPermission {_permission_summary = , _permission_description = Acknowledgements include "This product includes PHP, freely available from <http://www.php.net/>", _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/11", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/11", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/14", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/14", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/2", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/2", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/13", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/13", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])}
....

....
OlPermission {_permission_summary = , _permission_description = "PHP" as the name is used. group@php.netに連絡する., _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/29", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/29", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/3", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/3", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}
....

....
OlPermission {_permission_summary = , _permission_description = To use the name "PHP", please refer to group@php.netの許可を取る. ● Instead of "PHP Foo" or "phpfoo", you can use "Foo for PHP" to indicate that your software works with PHP. Instead of using "PHP Foo" or "phpfoo", you can use "Foo for PHP" to indicate that the software runs with PHP., _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/30", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/30", _action_name = Use the name of the product or part of the name of the product from which it was derived, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/3", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/3", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}
....

(source: Hitachi open-license)

=== Text

....
-------------------------------------------------------------------- 
                  The PHP License, version 3.0
Copyright (c) 1999 - 2006 The PHP Group. All rights reserved.
-------------------------------------------------------------------- 

Redistribution and use in source and binary forms, with or without
modification, is permitted provided that the following conditions
are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
 
  2. Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in
     the documentation and/or other materials provided with the
     distribution.
 
  3. The name "PHP" must not be used to endorse or promote products
     derived from this software without prior written permission. For
     written permission, please contact group@php.net.
  
  4. Products derived from this software may not be called "PHP", nor
     may "PHP" appear in their name, without prior written permission
     from group@php.net.  You may indicate that your software works in
     conjunction with PHP by saying "Foo for PHP" instead of calling
     it "PHP Foo" or "phpfoo"
 
  5. The PHP Group may publish revised and/or new versions of the
     license from time to time. Each version will be given a
     distinguishing version number.
     Once covered code has been published under a particular version
     of the license, you may always continue to use it under the terms
     of that version. You may also choose to use such covered code
     under the terms of any subsequent version of the license
     published by the PHP Group. No one other than the PHP Group has
     the right to modify the terms applicable to covered code created
     under this License.

  6. Redistributions of any form whatsoever must retain the following
     acknowledgment:
     "This product includes PHP, freely available from
     <http://www.php.net/>".

THIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND 
ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP
DEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

-------------------------------------------------------------------- 

This software consists of voluntary contributions made by many
individuals on behalf of the PHP Group.

The PHP Group can be contacted via Email at group@php.net.

For more information on the PHP Group and the PHP project, 
please see <http://www.php.net>.

This product includes the Zend Engine, freely available at
<http://www.zend.com>.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/PHP-3.0.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/php-3.0.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/finos/OSLC-handbook/blob/master/src/PHP-3.0.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "PHP-3.0",
        "PHP License v3.0",
        "scancode://php-3.0",
        "PHP License 3.0",
        "The PHP License, Version 3.0",
        "PHP License, version 3.0"
    ],
    "__impliedId": "PHP-3.0",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "PHP"
    ],
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified."
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/PHP-3.0",
            "maintainer": "PHP Group",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "PHP-3.0",
            "title": "PHP License 3.0",
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0",
                    "PHP License 3.0"
                ],
                "__impliedId": "PHP-3.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/PHP-3.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "PHP-3.0"
                ],
                "__impliedId": "PHP-3.0"
            },
            "shortname": "PHP-3.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "PHP License v3.0",
            "spdxDetailsURL": "http://spdx.org/licenses/PHP-3.0.json",
            "_sourceURL": "https://spdx.org/licenses/PHP-3.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.php.net/license/3_0.txt",
                "https://opensource.org/licenses/PHP-3.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0",
                    "PHP License v3.0"
                ],
                "__impliedId": "PHP-3.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/PHP-3.0.json"
                    ],
                    [
                        null,
                        "http://www.php.net/license/3_0.txt"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/PHP-3.0"
                    ]
                ]
            },
            "spdxLicenseId": "PHP-3.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.php.net/license/3_01.txt",
            "GPLv3 Compat?": "NO",
            "Short Name": "PHP",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "PHP License v3.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "PHP License v3.0"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "PHP"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://www.opensource.org/licenses/PHP-3.0",
                "http://www.php.net/license/3_0.txt",
                "https://opensource.org/licenses/PHP-3.0"
            ],
            "homepageUrl": "http://www.php.net/license/",
            "shortName": "PHP License 3.0",
            "textUrls": null,
            "text": "-------------------------------------------------------------------- \n                  The PHP License, version 3.0\nCopyright (c) 1999 - 2006 The PHP Group. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer.\n \n  2. Redistributions in binary form must reproduce the above copyright\n     notice, this list of conditions and the following disclaimer in\n     the documentation and/or other materials provided with the\n     distribution.\n \n  3. The name \"PHP\" must not be used to endorse or promote products\n     derived from this software without prior written permission. For\n     written permission, please contact group@php.net.\n  \n  4. Products derived from this software may not be called \"PHP\", nor\n     may \"PHP\" appear in their name, without prior written permission\n     from group@php.net.  You may indicate that your software works in\n     conjunction with PHP by saying \"Foo for PHP\" instead of calling\n     it \"PHP Foo\" or \"phpfoo\"\n \n  5. The PHP Group may publish revised and/or new versions of the\n     license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the terms\n     of that version. You may also choose to use such covered code\n     under the terms of any subsequent version of the license\n     published by the PHP Group. No one other than the PHP Group has\n     the right to modify the terms applicable to covered code created\n     under this License.\n\n  6. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes PHP, freely available from\n     <http://www.php.net/>\".\n\nTHIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP\nDEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\nOF THE POSSIBILITY OF SUCH DAMAGE.\n\n-------------------------------------------------------------------- \n\nThis software consists of voluntary contributions made by many\nindividuals on behalf of the PHP Group.\n\nThe PHP Group can be contacted via Email at group@php.net.\n\nFor more information on the PHP Group and the PHP project, \nplease see <http://www.php.net>.\n\nThis product includes the Zend Engine, freely available at\n<http://www.zend.com>.",
            "category": "Permissive",
            "osiUrl": "http://www.opensource.org/licenses/php.html",
            "owner": "PHP Project",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/php-3.0.yml",
            "key": "php-3.0",
            "name": "PHP License 3.0",
            "spdxId": "PHP-3.0",
            "notes": "Per SPDX.org, this license is OSI certified.",
            "_implications": {
                "__impliedNames": [
                    "scancode://php-3.0",
                    "PHP License 3.0",
                    "PHP-3.0"
                ],
                "__impliedId": "PHP-3.0",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "-------------------------------------------------------------------- \n                  The PHP License, version 3.0\nCopyright (c) 1999 - 2006 The PHP Group. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer.\n \n  2. Redistributions in binary form must reproduce the above copyright\n     notice, this list of conditions and the following disclaimer in\n     the documentation and/or other materials provided with the\n     distribution.\n \n  3. The name \"PHP\" must not be used to endorse or promote products\n     derived from this software without prior written permission. For\n     written permission, please contact group@php.net.\n  \n  4. Products derived from this software may not be called \"PHP\", nor\n     may \"PHP\" appear in their name, without prior written permission\n     from group@php.net.  You may indicate that your software works in\n     conjunction with PHP by saying \"Foo for PHP\" instead of calling\n     it \"PHP Foo\" or \"phpfoo\"\n \n  5. The PHP Group may publish revised and/or new versions of the\n     license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the terms\n     of that version. You may also choose to use such covered code\n     under the terms of any subsequent version of the license\n     published by the PHP Group. No one other than the PHP Group has\n     the right to modify the terms applicable to covered code created\n     under this License.\n\n  6. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes PHP, freely available from\n     <http://www.php.net/>\".\n\nTHIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP\nDEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\nOF THE POSSIBILITY OF SUCH DAMAGE.\n\n-------------------------------------------------------------------- \n\nThis software consists of voluntary contributions made by many\nindividuals on behalf of the PHP Group.\n\nThe PHP Group can be contacted via Email at group@php.net.\n\nFor more information on the PHP Group and the PHP project, \nplease see <http://www.php.net>.\n\nThis product includes the Zend Engine, freely available at\n<http://www.zend.com>.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.php.net/license/"
                    ],
                    [
                        "OSI Page",
                        "http://www.opensource.org/licenses/php.html"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/PHP-3.0"
                    ],
                    [
                        null,
                        "http://www.php.net/license/3_0.txt"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/PHP-3.0"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "PHP License 3.0",
            "commercialUse": true,
            "spdxId": "PHP-3.0",
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0"
                ]
            }
        },
        "Hitachi open-license": {
            "permissionsStr": "[OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/1\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/1\", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/3\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/3\", _action_name = Modify the obtained source code., _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/4\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/4\", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/6\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/6\", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/8\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/8\", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing},OlPermission {_permission_summary = , _permission_description = Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\", _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/9\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/9\", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/12\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/12\", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])},OlPermission {_permission_summary = , _permission_description = Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\", _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/11\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/11\", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/14\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/14\", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])},OlPermission {_permission_summary = , _permission_description = \"PHP\" as the name is used. group@php.netã«é£çµ¡ãã., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/29\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/29\", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))},OlPermission {_permission_summary = , _permission_description = To use the name \"PHP\", please refer to group@php.netã®è¨±å¯ãåã. â Instead of \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that your software works with PHP. Instead of using \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that the software runs with PHP., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/30\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/30\", _action_name = Use the name of the product or part of the name of the product from which it was derived, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}]",
            "notices": [
                {
                    "content": "the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of commercial usability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "Neither the copyright owner nor any contributor, for any cause whatsoever, shall be liable for damages, regardless of how caused, and regardless of whether the liability is based on contract, strict liability, or tort (including negligence), even if they have been advised of the possibility of such damages arising from the use of the software, and even if they have been advised of the possibility of such damages. for any direct, indirect, incidental, special, punitive, or consequential damages (including, but not limited to, compensation for procurement of substitute goods or services, loss of use, loss of data, loss of profits, or business interruption). It shall not be defeated."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/811",
            "content": "-------------------------------------------------------------------- \r\n                  The PHP License, version 3.0\r\nCopyright (c) 1999 - 2002 The PHP Group. All rights reserved.\r\n-------------------------------------------------------------------- \r\n\r\nRedistribution and use in source and binary forms, with or without\r\nmodification, is permitted provided that the following conditions\r\nare met:\r\n\r\n  1. Redistributions of source code must retain the above copyright\r\n     notice, this list of conditions and the following disclaimer.\r\n \r\n  2. Redistributions in binary form must reproduce the above copyright\r\n     notice, this list of conditions and the following disclaimer in\r\n     the documentation and/or other materials provided with the\r\n     distribution.\r\n \r\n  3. The name \"PHP\" must not be used to endorse or promote products\r\n     derived from this software without prior written permission. For\r\n     written permission, please contact group@php.net.\r\n  \r\n  4. Products derived from this software may not be called \"PHP\", nor\r\n     may \"PHP\" appear in their name, without prior written permission\r\n     from group@php.net.  You may indicate that your software works in\r\n     conjunction with PHP by saying \"Foo for PHP\" instead of calling\r\n     it \"PHP Foo\" or \"phpfoo\"\r\n \r\n  5. The PHP Group may publish revised and/or new versions of the\r\n     license from time to time. Each version will be given a\r\n     distinguishing version number.\r\n     Once covered code has been published under a particular version\r\n     of the license, you may always continue to use it under the terms\r\n     of that version. You may also choose to use such covered code\r\n     under the terms of any subsequent version of the license\r\n     published by the PHP Group. No one other than the PHP Group has\r\n     the right to modify the terms applicable to covered code created\r\n     under this License.\r\n\r\n  6. Redistributions of any form whatsoever must retain the following\r\n     acknowledgment:\r\n     \"This product includes PHP, freely available from\r\n     <http://www.php.net/>\".\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND \r\nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\r\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \r\nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP\r\nDEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \r\nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \r\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \r\nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\r\nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\r\nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\r\nOF THE POSSIBILITY OF SUCH DAMAGE.\r\n\r\n-------------------------------------------------------------------- \r\n\r\nThis software consists of voluntary contributions made by many\r\nindividuals on behalf of the PHP Group.\r\n\r\nThe PHP Group can be contacted via Email at group@php.net.\r\n\r\nFor more information on the PHP Group and the PHP project, \r\nplease see <http://www.php.net>.\r\n\r\nThis product includes the Zend Engine, freely available at\r\n<http://www.zend.com>.\r\n\r\n----------\r\n",
            "name": "PHP License, version 3.0",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/1\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/1\", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/3\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/3\", _action_name = Modify the obtained source code., _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/4\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/4\", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/6\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/6\", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/8\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/8\", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing}",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\", _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/9\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/9\", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/12\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/12\", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])}",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\""
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\", _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/11\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/11\", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/14\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/14\", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = })])}",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes PHP, freely available from <http://www.php.net/>\""
                },
                {
                    "actions": [
                        {
                            "name": "Use the name to endorse and promote derived products"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = \"PHP\" as the name is used. group@php.netã«é£çµ¡ãã., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/29\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/29\", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "\"PHP\" as the name is used. group@php.netã«é£çµ¡ãã."
                },
                {
                    "actions": [
                        {
                            "name": "Use the name of the product or part of the name of the product from which it was derived"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = To use the name \"PHP\", please refer to group@php.netã®è¨±å¯ãåã. â Instead of \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that your software works with PHP. Instead of using \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that the software runs with PHP., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/30\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/30\", _action_name = Use the name of the product or part of the name of the product from which it was derived, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "To use the name \"PHP\", please refer to group@php.netã®è¨±å¯ãåã. â Instead of \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that your software works with PHP. Instead of using \"PHP Foo\" or \"phpfoo\", you can use \"Foo for PHP\" to indicate that the software runs with PHP."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "PHP License, version 3.0",
                    "PHP-3.0"
                ],
                "__impliedText": "-------------------------------------------------------------------- \r\n                  The PHP License, version 3.0\r\nCopyright (c) 1999 - 2002 The PHP Group. All rights reserved.\r\n-------------------------------------------------------------------- \r\n\r\nRedistribution and use in source and binary forms, with or without\r\nmodification, is permitted provided that the following conditions\r\nare met:\r\n\r\n  1. Redistributions of source code must retain the above copyright\r\n     notice, this list of conditions and the following disclaimer.\r\n \r\n  2. Redistributions in binary form must reproduce the above copyright\r\n     notice, this list of conditions and the following disclaimer in\r\n     the documentation and/or other materials provided with the\r\n     distribution.\r\n \r\n  3. The name \"PHP\" must not be used to endorse or promote products\r\n     derived from this software without prior written permission. For\r\n     written permission, please contact group@php.net.\r\n  \r\n  4. Products derived from this software may not be called \"PHP\", nor\r\n     may \"PHP\" appear in their name, without prior written permission\r\n     from group@php.net.  You may indicate that your software works in\r\n     conjunction with PHP by saying \"Foo for PHP\" instead of calling\r\n     it \"PHP Foo\" or \"phpfoo\"\r\n \r\n  5. The PHP Group may publish revised and/or new versions of the\r\n     license from time to time. Each version will be given a\r\n     distinguishing version number.\r\n     Once covered code has been published under a particular version\r\n     of the license, you may always continue to use it under the terms\r\n     of that version. You may also choose to use such covered code\r\n     under the terms of any subsequent version of the license\r\n     published by the PHP Group. No one other than the PHP Group has\r\n     the right to modify the terms applicable to covered code created\r\n     under this License.\r\n\r\n  6. Redistributions of any form whatsoever must retain the following\r\n     acknowledgment:\r\n     \"This product includes PHP, freely available from\r\n     <http://www.php.net/>\".\r\n\r\nTHIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND \r\nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\r\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \r\nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP\r\nDEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \r\nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \r\n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \r\nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\r\nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\r\nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\r\nOF THE POSSIBILITY OF SUCH DAMAGE.\r\n\r\n-------------------------------------------------------------------- \r\n\r\nThis software consists of voluntary contributions made by many\r\nindividuals on behalf of the PHP Group.\r\n\r\nThe PHP Group can be contacted via Email at group@php.net.\r\n\r\nFor more information on the PHP Group and the PHP project, \r\nplease see <http://www.php.net>.\r\n\r\nThis product includes the Zend Engine, freely available at\r\n<http://www.zend.com>.\r\n\r\n----------\r\n",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/811"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/PHP-3.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "PHP License v3.0",
            "id": "PHP-3.0",
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0",
                    "PHP License v3.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/PHP-3.0.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/PHP-3.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "PHP-3.0",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The PHP License, Version 3.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "PHP-3.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/PHP-3.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0",
                    "The PHP License, Version 3.0",
                    "PHP-3.0"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/PHP-3.0"
                    ]
                ]
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": "For binary distributions, this information must be provided in âthe documentation and/or other materials provided with the distributionâ",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copyright notice",
                    "termComplianceNotes": "For binary distributions, this information must be provided in âthe documentation and/or other materials provided with the distributionâ",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Name of project cannot be used for derived products without permission",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Acknowlegment must be retained in all redistributions",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": null,
                    "termSeeAlso": null,
                    "termDescription": "Allows use of covered code under the terms of same version or any later version of the license.",
                    "termComplianceNotes": null,
                    "termType": "license_versions"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/PHP-3.0.yaml",
            "name": "PHP License v3.0",
            "nameFromFilename": "PHP-3.0",
            "notes": "PHP-3.0 and PHP-3.01 are the same license, but for a slight variation in the acknowledment text.",
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0",
                    "PHP License v3.0"
                ]
            },
            "licenseId": [
                "PHP-3.0",
                "PHP License v3.0"
            ]
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "PHP-3.0",
            "_implications": {
                "__impliedNames": [
                    "PHP-3.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "-------------------------------------------------------------------- \n                  The PHP License, version 3.0\nCopyright (c) 1999 - 2006 The PHP Group. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer.\n \n  2. Redistributions in binary form must reproduce the above copyright\n     notice, this list of conditions and the following disclaimer in\n     the documentation and/or other materials provided with the\n     distribution.\n \n  3. The name \"PHP\" must not be used to endorse or promote products\n     derived from this software without prior written permission. For\n     written permission, please contact group@php.net.\n  \n  4. Products derived from this software may not be called \"PHP\", nor\n     may \"PHP\" appear in their name, without prior written permission\n     from group@php.net.  You may indicate that your software works in\n     conjunction with PHP by saying \"Foo for PHP\" instead of calling\n     it \"PHP Foo\" or \"phpfoo\"\n \n  5. The PHP Group may publish revised and/or new versions of the\n     license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the terms\n     of that version. You may also choose to use such covered code\n     under the terms of any subsequent version of the license\n     published by the PHP Group. No one other than the PHP Group has\n     the right to modify the terms applicable to covered code created\n     under this License.\n\n  6. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes PHP, freely available from\n     <http://www.php.net/>\".\n\nTHIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE PHP\nDEVELOPMENT TEAM OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \nINDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES \n(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR \nSERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\nHOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\nSTRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\nARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\nOF THE POSSIBILITY OF SUCH DAMAGE.\n\n-------------------------------------------------------------------- \n\nThis software consists of voluntary contributions made by many\nindividuals on behalf of the PHP Group.\n\nThe PHP Group can be contacted via Email at group@php.net.\n\nFor more information on the PHP Group and the PHP project, \nplease see <http://www.php.net>.\n\nThis product includes the Zend Engine, freely available at\n<http://www.zend.com>.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/PHP-3.0.json"
        ],
        [
            null,
            "http://www.php.net/license/3_0.txt"
        ],
        [
            null,
            "https://opensource.org/licenses/PHP-3.0"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/PHP-3.0.html"
        ],
        [
            "Homepage",
            "http://www.php.net/license/"
        ],
        [
            "OSI Page",
            "http://www.opensource.org/licenses/php.html"
        ],
        [
            null,
            "http://www.opensource.org/licenses/PHP-3.0"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/PHP-3.0"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/811"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/PHP-3.0.svg