== Plexus Classworlds License (Plexus)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Plexus Classworlds License
|Shortname |Plexus
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/Plexus.html
* *SPDX:* http://spdx.org/licenses/Plexus.json
* https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/finos/OSLC-handbook/blob/master/src/Plexus.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/Plexus.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Plexus",
        "Plexus Classworlds License"
    ],
    "__impliedId": "Plexus",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Plexus"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Plexus"
                ],
                "__impliedId": "Plexus"
            },
            "shortname": "Plexus",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Plexus Classworlds License",
            "spdxDetailsURL": "http://spdx.org/licenses/Plexus.json",
            "_sourceURL": "https://spdx.org/licenses/Plexus.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "Plexus",
                    "Plexus Classworlds License"
                ],
                "__impliedId": "Plexus",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Plexus.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License"
                    ]
                ]
            },
            "spdxLicenseId": "Plexus"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License",
            "GPLv3 Compat?": "NO",
            "Short Name": "Plexus",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Plexus Classworlds License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Plexus Classworlds License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Plexus"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Plexus.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Plexus Classworlds License",
            "id": "Plexus",
            "_implications": {
                "__impliedNames": [
                    "Plexus",
                    "Plexus Classworlds License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Plexus.html"
                    ]
                ]
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copyright notice",
                    "termComplianceNotes": "For binary distributions, this information must be provided in “the documentation and/or other materials provided with the distribution”",
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Name of project cannot be used for derived products without permission",
                    "termComplianceNotes": null,
                    "termType": "condition"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/Plexus.yaml",
            "name": "Plexus Classworlds License",
            "nameFromFilename": "Plexus",
            "notes": "This license also includes a clause that states, \"due credit should be given\" to the copyright holder, but given the non-obligatory nature of \"should\", this is not considered a requirement.",
            "_implications": {
                "__impliedNames": [
                    "Plexus",
                    "Plexus Classworlds License"
                ]
            },
            "licenseId": [
                "Plexus",
                "Plexus Classworlds License"
            ]
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Plexus.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Plexus.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Plexus.svg
