== PostgreSQL License (PostgreSQL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |PostgreSQL License
|Shortname |PostgreSQL
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://postgresql+`
* `+The PostgreSQL Licence+`

=== Description

____
A very short, BSD-style license, used specifically for PostgreSQL.
____

(source: choosealicense.com
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/PostgreSQL.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Rating is: Silver'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``Per SPDX.org, this license is OSI certified.'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/postgresql.yml[Scancode]
(CC0-1.0))

=== Obligations

[cols=",,",options="header",]
|===
|Rights: |Conditions: |Limitations:
a|
* commercial-use
* modifications
* distribution
* private-use

a|
* include-copyright

a|
* liability
* warranty

|===

(source:
https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/postgresql.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT]))

=== URLs

* *Homepage:* http://www.postgresql.org/about/licence
* *OSI Page:* http://www.opensource.org/licenses/postgresql
* *OSI Page:* https://opensource.org/licenses/PostgreSQL
* *SPDX:* http://spdx.org/licenses/PostgreSQL.json
* *SPDX:* https://spdx.org/licenses/PostgreSQL.html

=== Text

....
PostgreSQL is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.

PostgreSQL Database Management System
(formerly known as Postgres, then as Postgres95)

Portions Copyright (c) The PostgreSQL Global Development Group

Portions Copyright (c) 1994, The Regents of the University of California

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose, without fee, and without a written agreement is
hereby granted, provided that the above copyright notice and this paragraph and
the following two paragraphs appear in all copies.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND
THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/PostgreSQL.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/postgresql.yml[Scancode]
(CC0-1.0)
* https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/postgresql.txt[choosealicense.com]
(https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md[MIT])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])

==== Raw JSON

....
{
    "__impliedNames": [
        "PostgreSQL",
        "PostgreSQL License",
        "scancode://postgresql",
        "postgresql",
        "The PostgreSQL Licence"
    ],
    "__impliedId": "PostgreSQL",
    "__isFsfFree": true,
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified."
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/PostgreSQL",
            "maintainer": "PostgreSQL Global Development Group",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "PostgreSQL",
            "title": "PostgreSQL License",
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL",
                    "PostgreSQL License"
                ],
                "__impliedId": "PostgreSQL",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/PostgreSQL"
                    ]
                ]
            },
            "domain_content": false
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "PostgreSQL License",
            "spdxDetailsURL": "http://spdx.org/licenses/PostgreSQL.json",
            "_sourceURL": "https://spdx.org/licenses/PostgreSQL.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.postgresql.org/about/licence",
                "https://opensource.org/licenses/PostgreSQL"
            ],
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL",
                    "PostgreSQL License"
                ],
                "__impliedId": "PostgreSQL",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/PostgreSQL.json"
                    ],
                    [
                        null,
                        "http://www.postgresql.org/about/licence"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/PostgreSQL"
                    ]
                ]
            },
            "spdxLicenseId": "PostgreSQL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/PostgreSQL_License",
            "GPLv3 Compat?": "Yes",
            "Short Name": "PostgreSQL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "PostgreSQL License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL License",
                    "PostgreSQL"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://www.opensource.org/licenses/PostgreSQL",
                "https://opensource.org/licenses/PostgreSQL"
            ],
            "homepageUrl": "http://www.postgresql.org/about/licence",
            "shortName": "PostgreSQL License",
            "textUrls": null,
            "text": "PostgreSQL is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.\n\nPostgreSQL Database Management System\n(formerly known as Postgres, then as Postgres95)\n\nPortions Copyright (c) The PostgreSQL Global Development Group\n\nPortions Copyright (c) 1994, The Regents of the University of California\n\nPermission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose, without fee, and without a written agreement is\nhereby granted, provided that the above copyright notice and this paragraph and\nthe following two paragraphs appear in all copies.\n\nIN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR\nDIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST\nPROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF\nTHE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nTHE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\nBUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\nPARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS, AND\nTHE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,\nUPDATES, ENHANCEMENTS, OR MODIFICATIONS.",
            "category": "Permissive",
            "osiUrl": "http://www.opensource.org/licenses/postgresql",
            "owner": "PostgreSQL",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/postgresql.yml",
            "key": "postgresql",
            "name": "PostgreSQL License",
            "spdxId": "PostgreSQL",
            "notes": "Per SPDX.org, this license is OSI certified.",
            "_implications": {
                "__impliedNames": [
                    "scancode://postgresql",
                    "PostgreSQL License",
                    "PostgreSQL"
                ],
                "__impliedId": "PostgreSQL",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "PostgreSQL is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.\n\nPostgreSQL Database Management System\n(formerly known as Postgres, then as Postgres95)\n\nPortions Copyright (c) The PostgreSQL Global Development Group\n\nPortions Copyright (c) 1994, The Regents of the University of California\n\nPermission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose, without fee, and without a written agreement is\nhereby granted, provided that the above copyright notice and this paragraph and\nthe following two paragraphs appear in all copies.\n\nIN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR\nDIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST\nPROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF\nTHE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nTHE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\nBUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\nPARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS, AND\nTHE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,\nUPDATES, ENHANCEMENTS, OR MODIFICATIONS.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.postgresql.org/about/licence"
                    ],
                    [
                        "OSI Page",
                        "http://www.opensource.org/licenses/postgresql"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/PostgreSQL"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/PostgreSQL"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "The PostgreSQL License ",
            "commercialUse": true,
            "spdxId": "PostgreSQL",
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Silver",
            "url": "https://spdx.org/licenses/PostgreSQL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "PostgreSQL License",
            "id": "PostgreSQL",
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL",
                    "PostgreSQL License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Silver"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/PostgreSQL.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/PostgreSQL",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "PostgreSQL",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The PostgreSQL Licence",
            "other_names": [],
            "keywords": [
                "osi-approved",
                "discouraged",
                "redundant"
            ],
            "id": "PostgreSQL",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/PostgreSQL"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL",
                    "The PostgreSQL Licence",
                    "PostgreSQL"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/PostgreSQL"
                    ]
                ]
            }
        },
        "choosealicense.com": {
            "limitations": [
                "liability",
                "warranty"
            ],
            "_sourceURL": "https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/postgresql.txt",
            "content": "---\ntitle: PostgreSQL License\nspdx-id: PostgreSQL\n\ndescription: A very short, BSD-style license, used specifically for PostgreSQL.\n\nhow: Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.\n\nusing:\n  pgBadger: https://github.com/darold/pgbadger/blob/master/LICENSE\n  pgAdmin: https://github.com/postgres/pgadmin4/blob/master/LICENSE\n  .NET Access to PostgreSQL: https://github.com/npgsql/npgsql/blob/main/LICENSE\n\npermissions:\n  - commercial-use\n  - modifications\n  - distribution\n  - private-use\n\nconditions:\n  - include-copyright\n\nlimitations:\n  - liability\n  - warranty\n\n---\n\nPostgreSQL License\n\nCopyright (c) [year], [fullname]\n\nPermission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose, without fee, and without a written agreement is\nhereby granted, provided that the above copyright notice and this paragraph\nand the following two paragraphs appear in all copies.\n\nIN NO EVENT SHALL [fullname] BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,\nSPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING\nOUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF [fullname]\nHAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\n[fullname] SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\nPARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS,\nAND [fullname] HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,\nENHANCEMENTS, OR MODIFICATIONS.\n",
            "name": "postgresql",
            "hidden": null,
            "spdxId": "PostgreSQL",
            "conditions": [
                "include-copyright"
            ],
            "permissions": [
                "commercial-use",
                "modifications",
                "distribution",
                "private-use"
            ],
            "featured": null,
            "nickname": null,
            "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.",
            "title": "PostgreSQL License",
            "_implications": {
                "__impliedNames": [
                    "postgresql",
                    "PostgreSQL"
                ],
                "__obligations": {
                    "limitations": [
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "liability"
                        },
                        {
                            "tag": "ImpliedLimitation",
                            "contents": "warranty"
                        }
                    ],
                    "rights": [
                        {
                            "tag": "ImpliedRight",
                            "contents": "commercial-use"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "modifications"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "distribution"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "private-use"
                        }
                    ],
                    "conditions": [
                        {
                            "tag": "ImpliedCondition",
                            "contents": "include-copyright"
                        }
                    ]
                }
            },
            "description": "A very short, BSD-style license, used specifically for PostgreSQL."
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "PostgreSQL",
            "_implications": {
                "__impliedNames": [
                    "PostgreSQL"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Silver"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__obligations": {
        "limitations": [
            {
                "tag": "ImpliedLimitation",
                "contents": "liability"
            },
            {
                "tag": "ImpliedLimitation",
                "contents": "warranty"
            }
        ],
        "rights": [
            {
                "tag": "ImpliedRight",
                "contents": "commercial-use"
            },
            {
                "tag": "ImpliedRight",
                "contents": "modifications"
            },
            {
                "tag": "ImpliedRight",
                "contents": "distribution"
            },
            {
                "tag": "ImpliedRight",
                "contents": "private-use"
            }
        ],
        "conditions": [
            {
                "tag": "ImpliedCondition",
                "contents": "include-copyright"
            }
        ]
    },
    "__isOsiApproved": true,
    "__impliedText": "PostgreSQL is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.\n\nPostgreSQL Database Management System\n(formerly known as Postgres, then as Postgres95)\n\nPortions Copyright (c) The PostgreSQL Global Development Group\n\nPortions Copyright (c) 1994, The Regents of the University of California\n\nPermission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose, without fee, and without a written agreement is\nhereby granted, provided that the above copyright notice and this paragraph and\nthe following two paragraphs appear in all copies.\n\nIN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR\nDIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST\nPROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF\nTHE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nTHE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,\nBUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\nPARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN \"AS IS\" BASIS, AND\nTHE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,\nUPDATES, ENHANCEMENTS, OR MODIFICATIONS.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/PostgreSQL.json"
        ],
        [
            null,
            "http://www.postgresql.org/about/licence"
        ],
        [
            null,
            "https://opensource.org/licenses/PostgreSQL"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/PostgreSQL.html"
        ],
        [
            "Homepage",
            "http://www.postgresql.org/about/licence"
        ],
        [
            "OSI Page",
            "http://www.opensource.org/licenses/postgresql"
        ],
        [
            null,
            "http://www.opensource.org/licenses/PostgreSQL"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/PostgreSQL"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/PostgreSQL.svg