== Python Software Foundation License 2.0 (PSF-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Python Software Foundation License 2.0
|Shortname |PSF-2.0
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/PSF-2.0.json
* https://opensource.org/licenses/Python-2.0

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/PSF-2.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "PSF-2.0",
        "Python Software Foundation License 2.0"
    ],
    "__impliedId": "PSF-2.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "PSF-2.0"
                ],
                "__impliedId": "PSF-2.0"
            },
            "shortname": "PSF-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Python Software Foundation License 2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/PSF-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/PSF-2.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/Python-2.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "PSF-2.0",
                    "Python Software Foundation License 2.0"
                ],
                "__impliedId": "PSF-2.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/PSF-2.0.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/Python-2.0"
                    ]
                ]
            },
            "spdxLicenseId": "PSF-2.0"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/PSF-2.0.json"
        ],
        [
            null,
            "https://opensource.org/licenses/Python-2.0"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/PSF-2.0.svg
