== Q Public License 1.0 (QPL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Q Public License 1.0
|Shortname |QPL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |StrongCopyleft
|Has Patent Hint |False
|===

*Other Names:*

* `+scancode://qpl-1.0+`
* `+QPL 1.0+`
* `+Q Public License+`
* `+The Q Public License Version (QPL-1.0)+`
* `+License :: OSI Approved :: Qt Public License (QPL)+`
* `+Q PUBLIC LICENSE version 1.0+`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/QPL-1.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* ``The QPL is not GPL-compatible, which, regardless of one's opinion
about the license's DFSG-freeness, poses a major practical problem for
any code licensed under the QPL that is reused elsewhere in conjunction
with code under the GNU GPL. This makes the QPL alone a particularly
poor choice of license for a library. Furthermore, it is not clear that
the Trolltech corporation (the author of the Qt library and the QPL
itself) believes the QPL to be a free software license. Trolltech's
website describes how their dual-license approach is intended to be
"open source-friendly" (see
http://www.trolltech.com/company/model.html). If Trolltech felt that the
QPL alone were friendly enough to open-source, why do they have a
dual-licensing policy?'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))
* **↓**``Google Classification is RESTRICTED'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))

=== General Comments

* ``Strong copyleft licenses require you to share both the licensed
software (like the weak copyleft licenses, and larger programs that you
build with the licensed software, when you give copies to others.''
(source: https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* ``https://opensource.org/licenses/QPL-1.0'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``Per SPDX.org, this license is OSI certified.'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/qpl-1.0.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* http://doc.trolltech.com/4.0/qpl.html
* *OSI Page:* https://opensource.org/licenses/QPL-1.0
* *SPDX:* http://spdx.org/licenses/QPL-1.0.json
* *open-license:* http://open-license.hitachi.com/licenses/788
* http://doc.qt.nokia.com/3.3/license.html
* https://spdx.org/licenses/QPL-1.0.html
* http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses
* http://www.opensource.org/licenses/QPL-1.0

=== Description from open-license

....
Description: The software may be used to compile, link, and execute legitimately developed application programs.
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved executable (Use the obtained executable as is.)
- Use the executable generated from the modified source code

....

....
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)

Conditions:
OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/532", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/532", _condition_conditionType = OBLIGATION, _condition_name = Include copyright and trademark notices and disclaimers contained in the software, _condition_description = }

....

....
Description: If this license applies to a Modification of the Software, the initial developer is granted a non-exclusive, royalty-free right to distribute his or her Modification as part of future versions of the Software, provided that such future versions are also available under the terms of this license in addition to the initial developer's license. However, such future versions shall be made available under the terms of this license in addition to the initial developer's license.
Actions:
- Create and distribute your modifications in a form separate from the original software (Create a patch file or other format)

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/68", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/68", _condition_conditionType = OBLIGATION, _condition_name = Include the copyright notice contained in the software, _condition_description = }


....

....
Actions:
- Distribute the obtained executable (Redistribute the obtained executable as-is)

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/8", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/8", _condition_conditionType = OBLIGATION, _condition_name = Give you a copy of the relevant license., _condition_description = }
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/534", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/534", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive the source code corresponding to the software., _condition_description = No fee shall be charged in excess of the cost of transferring the data. ● Conspicuous inclusion of a notice regarding these terms and conditions.}


....

....
Actions:
- Distribute the executable generated from the modified source code

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/8", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/8", _condition_conditionType = OBLIGATION, _condition_name = Give you a copy of the relevant license., _condition_description = }
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/534", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/534", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive the source code corresponding to the software., _condition_description = No fee shall be charged in excess of the cost of transferring the data. ● Conspicuous inclusion of a notice regarding these terms and conditions.}
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/535", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/535", _condition_conditionType = OBLIGATION, _condition_name = Apply this license to the entire modification, _condition_description = }


....

....
Actions:
- Develop and distribute application programs, reusable components and other software items linked to the software (including modifications)

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/537", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/537", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive and use the source code corresponding to the item in question., _condition_description = No fee shall be charged in excess of the cost of transferring the data.}
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/538", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/538", _condition_conditionType = OBLIGATION, _condition_name = expressly grant the recipient of the item a license to use and distribute the item, and any modifications thereof, in both executable and source code form., _condition_description = }
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/539", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/539", _condition_conditionType = OBLIGATION, _condition_name = Supply copies of items not available to the general public to early developers of the software upon request from them., _condition_description = }


....

(source: Hitachi open-license)

=== Text

....
The Q Public License Version 1.0

Copyright (C) 1999 Trolltech AS, Norway.
Everyone is permitted to copy and distribute this license document.

The intent of this license is to establish freedom to share and change the software regulated by this license under the open source model.

This license applies to any software containing a notice placed by the copyright holder saying that it may be distributed under the terms of the Q Public License version 1.0. Such software is herein referred to as the Software. This license covers modification and distribution of the Software, use of third-party application programs based on the Software, and development of free software which uses the Software.

Granted Rights

1. You are granted the non-exclusive rights set forth in this license provided you agree to and comply with any and all conditions in this license. Whole or partial distribution of the Software, or software items that link with the Software, in any form signifies acceptance of this license.

2. You may copy and distribute the Software in unmodified form provided that the entire package, including - but not restricted to - copyright, trademark notices and disclaimers, as released by the initial developer of the Software, is distributed.

3. You may make modifications to the Software and distribute your modifications, in a form that is separate from the Software, such as patches. The following restrictions apply to modifications:

    a. Modifications must not alter or remove any copyright notices in the Software.

    b. When modifications to the Software are released under this license, a non-exclusive royalty-free right is granted to the initial developer of the Software to distribute your modification in future versions of the Software provided such versions remain available under these terms in addition to any other license(s) of the initial developer.

4. You may distribute machine-executable forms of the Software or machine-executable forms of modified versions of the Software, provided that you meet these restrictions:

    a. You must include this license document in the distribution.

    b. You must ensure that all recipients of the machine-executable forms are also able to receive the complete machine-readable source code to the distributed Software, including all modifications, without any charge beyond the costs of data transfer, and place prominent notices in the distribution explaining this.

    c. You must ensure that all modifications included in the machine-executable forms are available under the terms of this license.

5. You may use the original or modified versions of the Software to compile, link and run application programs legally developed by you or by others.

6. You may develop application programs, reusable components and other software items that link with the original or modified versions of the Software. These items, when distributed, are subject to the following requirements:

    a. You must ensure that all recipients of machine-executable forms of these items are also able to receive and use the complete machine-readable source code to the items without any charge beyond the costs of data transfer.

    b. You must explicitly license all recipients of your items to use and re-distribute original and modified versions of the items in both machine-executable and source code forms. The recipients must be able to do so without any charges whatsoever, and they must be able to re-distribute to anyone they choose.

    c. If the items are not available to the general public, and the initial developer of the Software requests a copy of the items, then you must supply one.

Limitations of Liability
In no event shall the initial developers or copyright holders be liable for any damages whatsoever, including - but not restricted to - lost revenue or profits or other direct, indirect, special, incidental or consequential damages, even if they have been advised of the possibility of such damages, except to the extent invariable law, if any, provides otherwise.

No Warranty
The Software and this license document are provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

Choice of Law
This license is governed by the Laws of Norway. Disputes shall be settled by Oslo City Court.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/QPL-1.0.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/qpl-1.0.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses[Wikipedia]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "QPL-1.0",
        "Q Public License 1.0",
        "scancode://qpl-1.0",
        "QPL 1.0",
        "Q Public License",
        "The Q Public License Version (QPL-1.0)",
        "License :: OSI Approved :: Qt Public License (QPL)",
        "Q PUBLIC LICENSE version 1.0"
    ],
    "__impliedId": "QPL-1.0",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Q Public License",
        "QPL",
        "Q Public License (QPL), Version 1.0"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
            ]
        ],
        [
            "Hitachi open-license",
            [
                "https://opensource.org/licenses/QPL-1.0"
            ]
        ],
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified."
            ]
        ]
    ],
    "__hasPatentHint": false,
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/QPL-1.0",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "QPL-1.0",
            "title": "Q Public License 1.0",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0",
                    "Q Public License 1.0"
                ],
                "__impliedId": "QPL-1.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/QPL-1.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "QPL-1.0"
                ],
                "__impliedId": "QPL-1.0"
            },
            "shortname": "QPL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Q Public License 1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/QPL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/QPL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://doc.qt.nokia.com/3.3/license.html",
                "https://opensource.org/licenses/QPL-1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0",
                    "Q Public License 1.0"
                ],
                "__impliedId": "QPL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/QPL-1.0.json"
                    ],
                    [
                        null,
                        "http://doc.qt.nokia.com/3.3/license.html"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/QPL-1.0"
                    ]
                ]
            },
            "spdxLicenseId": "QPL-1.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://doc.qt.digia.com/3.0/license.html",
            "GPLv3 Compat?": "NO",
            "Short Name": "QPL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Q Public License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Q Public License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "QPL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://doc.qt.nokia.com/3.3/license.html",
                "http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses",
                "http://www.opensource.org/licenses/QPL-1.0",
                "https://opensource.org/licenses/QPL-1.0"
            ],
            "homepageUrl": "http://doc.trolltech.com/4.0/qpl.html",
            "shortName": "QPL 1.0",
            "textUrls": null,
            "text": "The Q Public License Version 1.0\n\nCopyright (C) 1999 Trolltech AS, Norway.\nEveryone is permitted to copy and distribute this license document.\n\nThe intent of this license is to establish freedom to share and change the software regulated by this license under the open source model.\n\nThis license applies to any software containing a notice placed by the copyright holder saying that it may be distributed under the terms of the Q Public License version 1.0. Such software is herein referred to as the Software. This license covers modification and distribution of the Software, use of third-party application programs based on the Software, and development of free software which uses the Software.\n\nGranted Rights\n\n1. You are granted the non-exclusive rights set forth in this license provided you agree to and comply with any and all conditions in this license. Whole or partial distribution of the Software, or software items that link with the Software, in any form signifies acceptance of this license.\n\n2. You may copy and distribute the Software in unmodified form provided that the entire package, including - but not restricted to - copyright, trademark notices and disclaimers, as released by the initial developer of the Software, is distributed.\n\n3. You may make modifications to the Software and distribute your modifications, in a form that is separate from the Software, such as patches. The following restrictions apply to modifications:\n\n    a. Modifications must not alter or remove any copyright notices in the Software.\n\n    b. When modifications to the Software are released under this license, a non-exclusive royalty-free right is granted to the initial developer of the Software to distribute your modification in future versions of the Software provided such versions remain available under these terms in addition to any other license(s) of the initial developer.\n\n4. You may distribute machine-executable forms of the Software or machine-executable forms of modified versions of the Software, provided that you meet these restrictions:\n\n    a. You must include this license document in the distribution.\n\n    b. You must ensure that all recipients of the machine-executable forms are also able to receive the complete machine-readable source code to the distributed Software, including all modifications, without any charge beyond the costs of data transfer, and place prominent notices in the distribution explaining this.\n\n    c. You must ensure that all modifications included in the machine-executable forms are available under the terms of this license.\n\n5. You may use the original or modified versions of the Software to compile, link and run application programs legally developed by you or by others.\n\n6. You may develop application programs, reusable components and other software items that link with the original or modified versions of the Software. These items, when distributed, are subject to the following requirements:\n\n    a. You must ensure that all recipients of machine-executable forms of these items are also able to receive and use the complete machine-readable source code to the items without any charge beyond the costs of data transfer.\n\n    b. You must explicitly license all recipients of your items to use and re-distribute original and modified versions of the items in both machine-executable and source code forms. The recipients must be able to do so without any charges whatsoever, and they must be able to re-distribute to anyone they choose.\n\n    c. If the items are not available to the general public, and the initial developer of the Software requests a copy of the items, then you must supply one.\n\nLimitations of Liability\nIn no event shall the initial developers or copyright holders be liable for any damages whatsoever, including - but not restricted to - lost revenue or profits or other direct, indirect, special, incidental or consequential damages, even if they have been advised of the possibility of such damages, except to the extent invariable law, if any, provides otherwise.\n\nNo Warranty\nThe Software and this license document are provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.\n\nChoice of Law\nThis license is governed by the Laws of Norway. Disputes shall be settled by Oslo City Court.",
            "category": "Copyleft Limited",
            "osiUrl": null,
            "owner": "Trolltech",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/qpl-1.0.yml",
            "key": "qpl-1.0",
            "name": "Q Public License Version 1.0",
            "spdxId": "QPL-1.0",
            "notes": "Per SPDX.org, this license is OSI certified.",
            "_implications": {
                "__impliedNames": [
                    "scancode://qpl-1.0",
                    "QPL 1.0",
                    "QPL-1.0"
                ],
                "__impliedId": "QPL-1.0",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft",
                "__impliedText": "The Q Public License Version 1.0\n\nCopyright (C) 1999 Trolltech AS, Norway.\nEveryone is permitted to copy and distribute this license document.\n\nThe intent of this license is to establish freedom to share and change the software regulated by this license under the open source model.\n\nThis license applies to any software containing a notice placed by the copyright holder saying that it may be distributed under the terms of the Q Public License version 1.0. Such software is herein referred to as the Software. This license covers modification and distribution of the Software, use of third-party application programs based on the Software, and development of free software which uses the Software.\n\nGranted Rights\n\n1. You are granted the non-exclusive rights set forth in this license provided you agree to and comply with any and all conditions in this license. Whole or partial distribution of the Software, or software items that link with the Software, in any form signifies acceptance of this license.\n\n2. You may copy and distribute the Software in unmodified form provided that the entire package, including - but not restricted to - copyright, trademark notices and disclaimers, as released by the initial developer of the Software, is distributed.\n\n3. You may make modifications to the Software and distribute your modifications, in a form that is separate from the Software, such as patches. The following restrictions apply to modifications:\n\n    a. Modifications must not alter or remove any copyright notices in the Software.\n\n    b. When modifications to the Software are released under this license, a non-exclusive royalty-free right is granted to the initial developer of the Software to distribute your modification in future versions of the Software provided such versions remain available under these terms in addition to any other license(s) of the initial developer.\n\n4. You may distribute machine-executable forms of the Software or machine-executable forms of modified versions of the Software, provided that you meet these restrictions:\n\n    a. You must include this license document in the distribution.\n\n    b. You must ensure that all recipients of the machine-executable forms are also able to receive the complete machine-readable source code to the distributed Software, including all modifications, without any charge beyond the costs of data transfer, and place prominent notices in the distribution explaining this.\n\n    c. You must ensure that all modifications included in the machine-executable forms are available under the terms of this license.\n\n5. You may use the original or modified versions of the Software to compile, link and run application programs legally developed by you or by others.\n\n6. You may develop application programs, reusable components and other software items that link with the original or modified versions of the Software. These items, when distributed, are subject to the following requirements:\n\n    a. You must ensure that all recipients of machine-executable forms of these items are also able to receive and use the complete machine-readable source code to the items without any charge beyond the costs of data transfer.\n\n    b. You must explicitly license all recipients of your items to use and re-distribute original and modified versions of the items in both machine-executable and source code forms. The recipients must be able to do so without any charges whatsoever, and they must be able to re-distribute to anyone they choose.\n\n    c. If the items are not available to the general public, and the initial developer of the Software requests a copy of the items, then you must supply one.\n\nLimitations of Liability\nIn no event shall the initial developers or copyright holders be liable for any damages whatsoever, including - but not restricted to - lost revenue or profits or other direct, indirect, special, incidental or consequential damages, even if they have been advised of the possibility of such damages, except to the extent invariable law, if any, provides otherwise.\n\nNo Warranty\nThe Software and this license document are provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.\n\nChoice of Law\nThis license is governed by the Laws of Norway. Disputes shall be settled by Oslo City Court.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://doc.trolltech.com/4.0/qpl.html"
                    ],
                    [
                        null,
                        "http://doc.qt.nokia.com/3.3/license.html"
                    ],
                    [
                        null,
                        "http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/QPL-1.0"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/QPL-1.0"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Q Public License ",
            "commercialUse": true,
            "spdxId": "QPL-1.0",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "Q Public License (QPL), Version 1.0",
            "State": "DFSGStateUnsettled",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Q Public License (QPL), Version 1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "The QPL is not GPL-compatible, which, regardless of one's opinion about the license's DFSG-freeness, poses a major practical problem for any code licensed under the QPL that is reused elsewhere in conjunction with code under the GNU GPL. This makes the QPL alone a particularly poor choice of license for a library. Furthermore, it is not clear that the Trolltech corporation (the author of the Qt library and the QPL itself) believes the QPL to be a free software license. Trolltech's website describes how their dual-license approach is intended to be \"open source-friendly\" (see http://www.trolltech.com/company/model.html). If Trolltech felt that the QPL alone were friendly enough to open-source, why do they have a dual-licensing policy?"
                        }
                    ]
                ]
            },
            "Comment": "The QPL is not GPL-compatible, which, regardless of one's opinion about the license's DFSG-freeness, poses a major practical problem for any code licensed under the QPL that is reused elsewhere in conjunction with code under the GNU GPL. This makes the QPL alone a particularly poor choice of license for a library. Furthermore, it is not clear that the Trolltech corporation (the author of the Qt library and the QPL itself) believes the QPL to be a free software license. Trolltech's website describes how their dual-license approach is intended to be \"open source-friendly\" (see http://www.trolltech.com/company/model.html). If Trolltech felt that the QPL alone were friendly enough to open-source, why do they have a dual-licensing policy?",
            "LicenseId": "QPL-1.0"
        },
        "Hitachi open-license": {
            "summary": "https://opensource.org/licenses/QPL-1.0",
            "notices": [
                {
                    "content": "Neither the initial developer nor the copyright holder, even if advised of the possibility of such damages, shall be liable for any damages, including, but not limited to, loss of income, loss of profits, or any other direct, indirect, special, incidental, or consequential damages, except to the extent it would otherwise be provided in the event of an unchanging law The Company shall not be liable for any of the following"
                },
                {
                    "content": "such software and this license are provided \"as-is\" and without any warranties of any kind, including warranties of design, commercial applicability or fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "This license is subject to the provisions of Norwegian law. The dispute shall be resolved by the Oslo City Court."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/788",
            "content": "\t\t\t     THE Q PUBLIC LICENSE\r\n\t\t\t\t  version 1.0\r\n\r\n\t\t   Copyright (C) 1999-2000 Trolltech AS, Norway.\r\n\t\t       Everyone is permitted to copy and\r\n\t\t       distribute this license document.\r\n\r\nThe intent of this license is to establish freedom to share and change the\r\nsoftware regulated by this license under the open source model.\r\n\r\nThis license applies to any software containing a notice placed by the\r\ncopyright holder saying that it may be distributed under the terms of\r\nthe Q Public License version 1.0.  Such software is herein referred to as\r\nthe Software.  This license covers modification and distribution of the\r\nSoftware, use of third-party application programs based on the Software,\r\nand development of free software which uses the Software.\r\n\r\n\t\t\t\t Granted Rights\r\n\r\n1. You are granted the non-exclusive rights set forth in this license\r\n   provided you agree to and comply with any and all conditions in this\r\n   license.  Whole or partial distribution of the Software, or software\r\n   items that link with the Software, in any form signifies acceptance of\r\n   this license.\r\n\r\n2. You may copy and distribute the Software in unmodified form provided\r\n   that the entire package, including - but not restricted to - copyright,\r\n   trademark notices and disclaimers, as released by the initial developer\r\n   of the Software, is distributed.\r\n\r\n3. You may make modifications to the Software and distribute your\r\n   modifications, in a form that is separate from the Software, such as\r\n   patches. The following restrictions apply to modifications:\r\n\r\n     a. Modifications must not alter or remove any copyright notices in\r\n        the Software.\r\n\r\n     b. When modifications to the Software are released under this\r\n        license, a non-exclusive royalty-free right is granted to the\r\n        initial developer of the Software to distribute your modification\r\n        in future versions of the Software provided such versions remain\r\n        available under these terms in addition to any other license(s) of\r\n        the initial developer.\r\n\r\n4. You may distribute machine-executable forms of the Software or\r\n   machine-executable forms of modified versions of the Software, provided\r\n   that you meet these restrictions:\r\n\r\n     a. You must include this license document in the distribution.\r\n\r\n     b. You must ensure that all recipients of the machine-executable forms\r\n        are also able to receive the complete machine-readable source code\r\n        to the distributed Software, including all modifications, without\r\n        any charge beyond the costs of data transfer, and place prominent\r\n        notices in the distribution explaining this.\r\n\r\n     c. You must ensure that all modifications included in the\r\n        machine-executable forms are available under the terms of this\r\n        license.\r\n\r\n5. You may use the original or modified versions of the Software to\r\n   compile, link and run application programs legally developed by you\r\n   or by others.\r\n\r\n6. You may develop application programs, reusable components and other\r\n   software items that link with the original or modified versions of the\r\n   Software.  These items, when distributed, are subject to the following\r\n   requirements:\r\n\r\n     a. You must ensure that all recipients of machine-executable forms of\r\n        these items are also able to receive and use the complete\r\n        machine-readable source code to the items without any charge\r\n        beyond the costs of data transfer.\r\n\r\n     b. You must explicitly license all recipients of your items to use\r\n        and re-distribute original and modified versions of the items in\r\n        both machine-executable and source code forms. The recipients must\r\n        be able to do so without any charges whatsoever, and they must be\r\n        able to re-distribute to anyone they choose.\r\n\r\n\r\n     c. If the items are not available to the general public, and the\r\n        initial developer of the Software requests a copy of the items,\r\n        then you must supply one.\r\n\r\n\t\t\t    Limitations of Liability\r\n\r\nIn no event shall the initial developers or copyright holders be liable\r\nfor any damages whatsoever, including - but not restricted to - lost\r\nrevenue or profits or other direct, indirect, special, incidental or\r\nconsequential damages, even if they have been advised of the possibility\r\nof such damages, except to the extent invariable law, if any, provides\r\notherwise.\r\n\r\n\t\t\t          No Warranty\r\n\r\nThe Software and this license document are provided AS IS with NO WARRANTY\r\nOF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS\r\nFOR A PARTICULAR PURPOSE.\r\n                                 Choice of Law\r\n\r\nThis license is governed by the Laws of Norway. Disputes shall be settled\r\nby Oslo City Court.",
            "name": "Q PUBLIC LICENSE version 1.0",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved executable",
                            "description": "Use the obtained executable as is."
                        },
                        {
                            "name": "Use the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: The software may be used to compile, link, and execute legitimately developed application programs.\nActions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved executable (Use the obtained executable as is.)\n- Use the executable generated from the modified source code\n\n",
                    "conditions": null,
                    "description": "The software may be used to compile, link, and execute legitimately developed application programs."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n\nConditions:\nOlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/532\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/532\", _condition_conditionType = OBLIGATION, _condition_name = Include copyright and trademark notices and disclaimers contained in the software, _condition_description = }\n\n",
                    "conditions": {
                        "name": "Include copyright and trademark notices and disclaimers contained in the software",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Create and distribute your modifications in a form separate from the original software",
                            "description": "Create a patch file or other format"
                        }
                    ],
                    "_str": "Description: If this license applies to a Modification of the Software, the initial developer is granted a non-exclusive, royalty-free right to distribute his or her Modification as part of future versions of the Software, provided that such future versions are also available under the terms of this license in addition to the initial developer's license. However, such future versions shall be made available under the terms of this license in addition to the initial developer's license.\nActions:\n- Create and distribute your modifications in a form separate from the original software (Create a patch file or other format)\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/68\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/68\", _condition_conditionType = OBLIGATION, _condition_name = Include the copyright notice contained in the software, _condition_description = }\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include the copyright notice contained in the software",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "If this license applies to a Modification of the Software, the initial developer is granted a non-exclusive, royalty-free right to distribute his or her Modification as part of future versions of the Software, provided that such future versions are also available under the terms of this license in addition to the initial developer's license. However, such future versions shall be made available under the terms of this license in addition to the initial developer's license."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained executable",
                            "description": "Redistribute the obtained executable as-is"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the obtained executable (Redistribute the obtained executable as-is)\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/8\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/8\", _condition_conditionType = OBLIGATION, _condition_name = Give you a copy of the relevant license., _condition_description = }\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/534\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/534\", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive the source code corresponding to the software., _condition_description = No fee shall be charged in excess of the cost of transferring the data. â Conspicuous inclusion of a notice regarding these terms and conditions.}\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Give you a copy of the relevant license.",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Enables the recipient to receive the source code corresponding to the software.",
                                "type": "OBLIGATION",
                                "description": "No fee shall be charged in excess of the cost of transferring the data. â Conspicuous inclusion of a notice regarding these terms and conditions."
                            }
                        ]
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Distribute the executable generated from the modified source code\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/8\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/8\", _condition_conditionType = OBLIGATION, _condition_name = Give you a copy of the relevant license., _condition_description = }\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/534\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/534\", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive the source code corresponding to the software., _condition_description = No fee shall be charged in excess of the cost of transferring the data. â Conspicuous inclusion of a notice regarding these terms and conditions.}\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/535\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/535\", _condition_conditionType = OBLIGATION, _condition_name = Apply this license to the entire modification, _condition_description = }\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Give you a copy of the relevant license.",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Enables the recipient to receive the source code corresponding to the software.",
                                "type": "OBLIGATION",
                                "description": "No fee shall be charged in excess of the cost of transferring the data. â Conspicuous inclusion of a notice regarding these terms and conditions."
                            },
                            {
                                "name": "Apply this license to the entire modification",
                                "type": "OBLIGATION"
                            }
                        ]
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Develop and distribute application programs, reusable components and other software items linked to the software (including modifications)"
                        }
                    ],
                    "_str": "Actions:\n- Develop and distribute application programs, reusable components and other software items linked to the software (including modifications)\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/537\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/537\", _condition_conditionType = OBLIGATION, _condition_name = Enables the recipient to receive and use the source code corresponding to the item in question., _condition_description = No fee shall be charged in excess of the cost of transferring the data.}\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/538\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/538\", _condition_conditionType = OBLIGATION, _condition_name = expressly grant the recipient of the item a license to use and distribute the item, and any modifications thereof, in both executable and source code form., _condition_description = }\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/539\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/539\", _condition_conditionType = OBLIGATION, _condition_name = Supply copies of items not available to the general public to early developers of the software upon request from them., _condition_description = }\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Enables the recipient to receive and use the source code corresponding to the item in question.",
                                "type": "OBLIGATION",
                                "description": "No fee shall be charged in excess of the cost of transferring the data."
                            },
                            {
                                "name": "expressly grant the recipient of the item a license to use and distribute the item, and any modifications thereof, in both executable and source code form.",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Supply copies of items not available to the general public to early developers of the software upon request from them.",
                                "type": "OBLIGATION"
                            }
                        ]
                    }
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Q PUBLIC LICENSE version 1.0",
                    "QPL-1.0"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "https://opensource.org/licenses/QPL-1.0"
                        ]
                    ]
                ],
                "__impliedText": "\t\t\t     THE Q PUBLIC LICENSE\r\n\t\t\t\t  version 1.0\r\n\r\n\t\t   Copyright (C) 1999-2000 Trolltech AS, Norway.\r\n\t\t       Everyone is permitted to copy and\r\n\t\t       distribute this license document.\r\n\r\nThe intent of this license is to establish freedom to share and change the\r\nsoftware regulated by this license under the open source model.\r\n\r\nThis license applies to any software containing a notice placed by the\r\ncopyright holder saying that it may be distributed under the terms of\r\nthe Q Public License version 1.0.  Such software is herein referred to as\r\nthe Software.  This license covers modification and distribution of the\r\nSoftware, use of third-party application programs based on the Software,\r\nand development of free software which uses the Software.\r\n\r\n\t\t\t\t Granted Rights\r\n\r\n1. You are granted the non-exclusive rights set forth in this license\r\n   provided you agree to and comply with any and all conditions in this\r\n   license.  Whole or partial distribution of the Software, or software\r\n   items that link with the Software, in any form signifies acceptance of\r\n   this license.\r\n\r\n2. You may copy and distribute the Software in unmodified form provided\r\n   that the entire package, including - but not restricted to - copyright,\r\n   trademark notices and disclaimers, as released by the initial developer\r\n   of the Software, is distributed.\r\n\r\n3. You may make modifications to the Software and distribute your\r\n   modifications, in a form that is separate from the Software, such as\r\n   patches. The following restrictions apply to modifications:\r\n\r\n     a. Modifications must not alter or remove any copyright notices in\r\n        the Software.\r\n\r\n     b. When modifications to the Software are released under this\r\n        license, a non-exclusive royalty-free right is granted to the\r\n        initial developer of the Software to distribute your modification\r\n        in future versions of the Software provided such versions remain\r\n        available under these terms in addition to any other license(s) of\r\n        the initial developer.\r\n\r\n4. You may distribute machine-executable forms of the Software or\r\n   machine-executable forms of modified versions of the Software, provided\r\n   that you meet these restrictions:\r\n\r\n     a. You must include this license document in the distribution.\r\n\r\n     b. You must ensure that all recipients of the machine-executable forms\r\n        are also able to receive the complete machine-readable source code\r\n        to the distributed Software, including all modifications, without\r\n        any charge beyond the costs of data transfer, and place prominent\r\n        notices in the distribution explaining this.\r\n\r\n     c. You must ensure that all modifications included in the\r\n        machine-executable forms are available under the terms of this\r\n        license.\r\n\r\n5. You may use the original or modified versions of the Software to\r\n   compile, link and run application programs legally developed by you\r\n   or by others.\r\n\r\n6. You may develop application programs, reusable components and other\r\n   software items that link with the original or modified versions of the\r\n   Software.  These items, when distributed, are subject to the following\r\n   requirements:\r\n\r\n     a. You must ensure that all recipients of machine-executable forms of\r\n        these items are also able to receive and use the complete\r\n        machine-readable source code to the items without any charge\r\n        beyond the costs of data transfer.\r\n\r\n     b. You must explicitly license all recipients of your items to use\r\n        and re-distribute original and modified versions of the items in\r\n        both machine-executable and source code forms. The recipients must\r\n        be able to do so without any charges whatsoever, and they must be\r\n        able to re-distribute to anyone they choose.\r\n\r\n\r\n     c. If the items are not available to the general public, and the\r\n        initial developer of the Software requests a copy of the items,\r\n        then you must supply one.\r\n\r\n\t\t\t    Limitations of Liability\r\n\r\nIn no event shall the initial developers or copyright holders be liable\r\nfor any damages whatsoever, including - but not restricted to - lost\r\nrevenue or profits or other direct, indirect, special, incidental or\r\nconsequential damages, even if they have been advised of the possibility\r\nof such damages, except to the extent invariable law, if any, provides\r\notherwise.\r\n\r\n\t\t\t          No Warranty\r\n\r\nThe Software and this license document are provided AS IS with NO WARRANTY\r\nOF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS\r\nFOR A PARTICULAR PURPOSE.\r\n                                 Choice of Law\r\n\r\nThis license is governed by the Laws of Norway. Disputes shall be settled\r\nby Oslo City Court.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/788"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/QPL-1.0.html",
            "familyName": "Q Public License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "Q Public License 1.0",
            "id": "QPL-1.0",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0",
                    "Q Public License 1.0"
                ],
                "__impliedAmbiguousNames": [
                    "Q Public License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "StrongCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "StrongCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/QPL-1.0.html"
                    ]
                ]
            },
            "CopyleftKind": "StrongCopyleft"
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/QPL-1.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "QPL-1.0",
                    "scheme": "DEP5"
                },
                {
                    "identifier": "QPL-1.0",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Qt Public License (QPL)",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The Q Public License Version (QPL-1.0)",
            "other_names": [],
            "keywords": [
                "osi-approved"
            ],
            "id": "QPL-1.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/QPL-1.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0",
                    "The Q Public License Version (QPL-1.0)",
                    "QPL-1.0",
                    "QPL-1.0",
                    "License :: OSI Approved :: Qt Public License (QPL)"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/QPL-1.0"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Limited",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": null,
            "Coordinates": {
                "name": "Q Public License",
                "version": null,
                "spdxId": "QPL-1.0"
            },
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0",
                    "Q Public License"
                ],
                "__hasPatentHint": false
            },
            "Modification": {
                "value": "Limited",
                "description": "modification of the code by a licensee"
            }
        },
        "Google OSS Policy": {
            "rating": "RESTRICTED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "QPL-1.0",
            "_implications": {
                "__impliedNames": [
                    "QPL-1.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is RESTRICTED"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NeutralJudgement",
                "contents": "The QPL is not GPL-compatible, which, regardless of one's opinion about the license's DFSG-freeness, poses a major practical problem for any code licensed under the QPL that is reused elsewhere in conjunction with code under the GNU GPL. This makes the QPL alone a particularly poor choice of license for a library. Furthermore, it is not clear that the Trolltech corporation (the author of the Qt library and the QPL itself) believes the QPL to be a free software license. Trolltech's website describes how their dual-license approach is intended to be \"open source-friendly\" (see http://www.trolltech.com/company/model.html). If Trolltech felt that the QPL alone were friendly enough to open-source, why do they have a dual-licensing policy?"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is RESTRICTED"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "StrongCopyleft"
        ],
        [
            "Scancode",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "StrongCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "The Q Public License Version 1.0\n\nCopyright (C) 1999 Trolltech AS, Norway.\nEveryone is permitted to copy and distribute this license document.\n\nThe intent of this license is to establish freedom to share and change the software regulated by this license under the open source model.\n\nThis license applies to any software containing a notice placed by the copyright holder saying that it may be distributed under the terms of the Q Public License version 1.0. Such software is herein referred to as the Software. This license covers modification and distribution of the Software, use of third-party application programs based on the Software, and development of free software which uses the Software.\n\nGranted Rights\n\n1. You are granted the non-exclusive rights set forth in this license provided you agree to and comply with any and all conditions in this license. Whole or partial distribution of the Software, or software items that link with the Software, in any form signifies acceptance of this license.\n\n2. You may copy and distribute the Software in unmodified form provided that the entire package, including - but not restricted to - copyright, trademark notices and disclaimers, as released by the initial developer of the Software, is distributed.\n\n3. You may make modifications to the Software and distribute your modifications, in a form that is separate from the Software, such as patches. The following restrictions apply to modifications:\n\n    a. Modifications must not alter or remove any copyright notices in the Software.\n\n    b. When modifications to the Software are released under this license, a non-exclusive royalty-free right is granted to the initial developer of the Software to distribute your modification in future versions of the Software provided such versions remain available under these terms in addition to any other license(s) of the initial developer.\n\n4. You may distribute machine-executable forms of the Software or machine-executable forms of modified versions of the Software, provided that you meet these restrictions:\n\n    a. You must include this license document in the distribution.\n\n    b. You must ensure that all recipients of the machine-executable forms are also able to receive the complete machine-readable source code to the distributed Software, including all modifications, without any charge beyond the costs of data transfer, and place prominent notices in the distribution explaining this.\n\n    c. You must ensure that all modifications included in the machine-executable forms are available under the terms of this license.\n\n5. You may use the original or modified versions of the Software to compile, link and run application programs legally developed by you or by others.\n\n6. You may develop application programs, reusable components and other software items that link with the original or modified versions of the Software. These items, when distributed, are subject to the following requirements:\n\n    a. You must ensure that all recipients of machine-executable forms of these items are also able to receive and use the complete machine-readable source code to the items without any charge beyond the costs of data transfer.\n\n    b. You must explicitly license all recipients of your items to use and re-distribute original and modified versions of the items in both machine-executable and source code forms. The recipients must be able to do so without any charges whatsoever, and they must be able to re-distribute to anyone they choose.\n\n    c. If the items are not available to the general public, and the initial developer of the Software requests a copy of the items, then you must supply one.\n\nLimitations of Liability\nIn no event shall the initial developers or copyright holders be liable for any damages whatsoever, including - but not restricted to - lost revenue or profits or other direct, indirect, special, incidental or consequential damages, even if they have been advised of the possibility of such damages, except to the extent invariable law, if any, provides otherwise.\n\nNo Warranty\nThe Software and this license document are provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.\n\nChoice of Law\nThis license is governed by the Laws of Norway. Disputes shall be settled by Oslo City Court.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/QPL-1.0.json"
        ],
        [
            null,
            "http://doc.qt.nokia.com/3.3/license.html"
        ],
        [
            null,
            "https://opensource.org/licenses/QPL-1.0"
        ],
        [
            null,
            "https://spdx.org/licenses/QPL-1.0.html"
        ],
        [
            "Homepage",
            "http://doc.trolltech.com/4.0/qpl.html"
        ],
        [
            null,
            "http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses"
        ],
        [
            null,
            "http://www.opensource.org/licenses/QPL-1.0"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/QPL-1.0"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/788"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/QPL-1.0.svg