== RealNetworks Public Source License v1.0 (RPSL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |RealNetworks Public Source License v1.0
|Shortname |RPSL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |SaaSCopyleft
|===

*Other Names:*

* `RealNetworks Public Source License 1.0`
* `RealNetworks Public Source License, Version 1.0`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/RPSL-1.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``This license is not compatible with the
DebianFreeSoftwareGuidelines (DFSG-unfree)'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION))

=== General Comments

* ``In addition to the requirements of strong copyleft licenses, network
copyleft licenses require you to share larger programs that you build
with the licensed software not just when you give copies to others, but
also when you run the software for others to use over the Internet or
another network.'' (source: https://blueoakcouncil.org/copyleft[BlueOak
License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* ``Strong copyleft licenses require you to share both the licensed
software (like the weak copyleft licenses, and larger programs that you
build with the licensed software, when you give copies to others.''
(source: https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== URLs

* *OSI Page:* https://opensource.org/licenses/RPSL-1.0
* *SPDX:* http://spdx.org/licenses/RPSL-1.0.json
* https://spdx.org/licenses/RPSL-1.0.html
* https://helixcommunity.org/content/rpsl

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/copyleft[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines]
(NOASSERTION)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/RPSL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "RPSL-1.0",
        "RealNetworks Public Source License v1.0",
        "RealNetworks Public Source License V1.0",
        "RealNetworks Public Source License 1.0",
        "RealNetworks Public Source License, Version 1.0"
    ],
    "__impliedId": "RPSL-1.0",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "RealNetworks Public Source License",
        "RealNetworks Public Source License (RPSL)",
        "RPSL"
    ],
    "__impliedComments": [
        [
            "BlueOak License List",
            [
                "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/RPSL-1.0",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "RPSL-1.0",
            "title": "RealNetworks Public Source License 1.0",
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0",
                    "RealNetworks Public Source License 1.0"
                ],
                "__impliedId": "RPSL-1.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/RPSL-1.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "RPSL-1.0"
                ],
                "__impliedId": "RPSL-1.0"
            },
            "shortname": "RPSL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "RealNetworks Public Source License v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/RPSL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/RPSL-1.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://helixcommunity.org/content/rpsl",
                "https://opensource.org/licenses/RPSL-1.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0",
                    "RealNetworks Public Source License v1.0"
                ],
                "__impliedId": "RPSL-1.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/RPSL-1.0.json"
                    ],
                    [
                        null,
                        "https://helixcommunity.org/content/rpsl"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/RPSL-1.0"
                    ]
                ]
            },
            "spdxLicenseId": "RPSL-1.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.opensource.org/licenses/real.php",
            "GPLv3 Compat?": null,
            "Short Name": "RPSL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "RealNetworks Public Source License V1.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "RealNetworks Public Source License V1.0"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "RPSL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "RealNetworks Public Source License V1.0",
            "commercialUse": true,
            "spdxId": "RPSL-1.0",
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "RealNetworks Public Source License (RPSL)",
            "State": "DFSGInCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0"
                ],
                "__impliedAmbiguousNames": [
                    "RealNetworks Public Source License (RPSL)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "RPSL-1.0"
        },
        "BlueOak License List": {
            "url": "https://spdx.org/licenses/RPSL-1.0.html",
            "familyName": "RealNetworks Public Source License",
            "_sourceURL": "https://blueoakcouncil.org/copyleft",
            "name": "RealNetworks Public Source License v1.0",
            "id": "RPSL-1.0",
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0",
                    "RealNetworks Public Source License v1.0"
                ],
                "__impliedAmbiguousNames": [
                    "RealNetworks Public Source License"
                ],
                "__impliedComments": [
                    [
                        "BlueOak License List",
                        [
                            "In addition to the requirements of strong copyleft licenses, network copyleft licenses require you to share larger programs that you build with the licensed software not just when you give copies to others, but also when you run the software for others to use over the Internet or another network.",
                            "Strong copyleft licenses require you to share both the licensed software (like the weak copyleft licenses, and larger programs that you build with the licensed software, when you give copies to others."
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "SaaSCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "SaaSCopyleft",
                "__impliedURLs": [
                    [
                        null,
                        "https://spdx.org/licenses/RPSL-1.0.html"
                    ]
                ]
            },
            "CopyleftKind": "SaaSCopyleft"
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/RPSL-1.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "RPSL-1.0",
                    "scheme": "SPDX"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "RealNetworks Public Source License, Version 1.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "RPSL-1.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/RPSL-1.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "RPSL-1.0",
                    "RealNetworks Public Source License, Version 1.0",
                    "RPSL-1.0"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/RPSL-1.0"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Debian Free Software Guidelines",
            {
                "tag": "NegativeJudgement",
                "contents": "This license is not compatible with the DebianFreeSoftwareGuidelines (DFSG-unfree)"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "SaaSCopyleft"
        ]
    ],
    "__calculatedCopyleft": "SaaSCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            null,
            "https://spdx.org/licenses/RPSL-1.0.html"
        ],
        [
            null,
            "https://opensource.org/licenses/RPSL-1.0"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/RPSL-1.0"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/RPSL-1.0.json"
        ],
        [
            null,
            "https://helixcommunity.org/content/rpsl"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/RPSL-1.0.svg
