== RSA Message-Digest License (RSA-MD)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |RSA Message-Digest License
|Shortname |RSA-MD
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `RSA Message-Digest License `

=== Comments on (easy) usability

* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/RSA-MD.html
* *SPDX:* http://spdx.org/licenses/RSA-MD.json
* http://www.faqs.org/rfcs/rfc1321.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/RSA-MD.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "RSA-MD",
        "RSA Message-Digest License ",
        "RSA Message-Digest License"
    ],
    "__impliedId": "RSA-MD",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "RSA-MD"
                ],
                "__impliedId": "RSA-MD"
            },
            "shortname": "RSA-MD",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "RSA Message-Digest License",
            "spdxDetailsURL": "http://spdx.org/licenses/RSA-MD.json",
            "_sourceURL": "https://spdx.org/licenses/RSA-MD.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.faqs.org/rfcs/rfc1321.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "RSA-MD",
                    "RSA Message-Digest License"
                ],
                "__impliedId": "RSA-MD",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/RSA-MD.json"
                    ],
                    [
                        null,
                        "http://www.faqs.org/rfcs/rfc1321.html"
                    ]
                ]
            },
            "spdxLicenseId": "RSA-MD"
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/RSA-MD.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "RSA Message-Digest License ",
            "id": "RSA-MD",
            "_implications": {
                "__impliedNames": [
                    "RSA-MD",
                    "RSA Message-Digest License "
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/RSA-MD.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/RSA-MD.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/RSA-MD.json"
        ],
        [
            null,
            "http://www.faqs.org/rfcs/rfc1321.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/RSA-MD.svg
