== Ricoh Source Code Public License (RSCPL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Ricoh Source Code Public License
|Shortname |RSCPL
|Rating |Unknown, probably Stop or No-Go
|Classification |WeakCopyleft
|===

*Other Names:*

* `The Ricoh Source Code Public License`
* `License :: OSI Approved :: Ricoh Source Code Public License`

=== Comments on (easy) usability

* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/RSCPL.html[SPDX] (all data [in this
repository] is generated))
* **↓**``This software licenses which is NOT OKAY for Fedora. Nothing in
Fedora is permitted to use this license. It is either non-free or
deprecated.'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *OSI Page:* https://opensource.org/licenses/RSCPL
* *SPDX:* http://spdx.org/licenses/RSCPL.json
* http://wayback.archive.org/web/20060715140826/http://www.risource.org/RPL/RPL-1.0A.shtml

'''''

=== Raw Data

==== Facts

* LicenseName
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/RSCPL.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "RSCPL",
        "Ricoh Source Code Public License",
        "The Ricoh Source Code Public License",
        "License :: OSI Approved :: Ricoh Source Code Public License"
    ],
    "__impliedId": "RSCPL",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/RSCPL",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "RSCPL",
            "title": "Ricoh Source Code Public License",
            "_implications": {
                "__impliedNames": [
                    "RSCPL",
                    "Ricoh Source Code Public License"
                ],
                "__impliedId": "RSCPL",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/RSCPL"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "RSCPL"
                ],
                "__impliedId": "RSCPL"
            },
            "shortname": "RSCPL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Ricoh Source Code Public License",
            "spdxDetailsURL": "http://spdx.org/licenses/RSCPL.json",
            "_sourceURL": "https://spdx.org/licenses/RSCPL.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://wayback.archive.org/web/20060715140826/http://www.risource.org/RPL/RPL-1.0A.shtml",
                "https://opensource.org/licenses/RSCPL"
            ],
            "_implications": {
                "__impliedNames": [
                    "RSCPL",
                    "Ricoh Source Code Public License"
                ],
                "__impliedId": "RSCPL",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/RSCPL.json"
                    ],
                    [
                        null,
                        "http://wayback.archive.org/web/20060715140826/http://www.risource.org/RPL/RPL-1.0A.shtml"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/RSCPL"
                    ]
                ]
            },
            "spdxLicenseId": "RSCPL"
        },
        "Fedora Project Wiki": {
            "rating": "Bad",
            "Upstream URL": "http://opensource.org/licenses/ricohpl.php",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Ricoh Source Code Public License",
            "FSF Free?": "No",
            "_implications": {
                "__impliedNames": [
                    "Ricoh Source Code Public License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
                        }
                    ]
                ]
            },
            "Notes": null
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "RSCPL"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "RSCPL",
            "copyleftkind": "WeakCopyleft"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "copyleft",
            "freedomOrDeath": "no",
            "typeCopyleft": "weak",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Ricoh Source Code Public License ",
            "commercialUse": true,
            "spdxId": "RSCPL",
            "_implications": {
                "__impliedNames": [
                    "RSCPL"
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/RSCPL",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "RSCPL",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Ricoh Source Code Public License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The Ricoh Source Code Public License",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "RSCPL",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/RSCPL"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "RSCPL",
                    "The Ricoh Source Code Public License",
                    "RSCPL",
                    "License :: OSI Approved :: Ricoh Source Code Public License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/RSCPL"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "NegativeJudgement",
                "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            null,
            "https://opensource.org/licenses/RSCPL"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/RSCPL"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/RSCPL.json"
        ],
        [
            null,
            "http://wayback.archive.org/web/20060715140826/http://www.risource.org/RPL/RPL-1.0A.shtml"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/RSCPL.svg
