== Ruby License (Ruby)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Ruby License
|Shortname |Ruby
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

*Other Names:*

* `+scancode://ruby+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List])
* ``Google Classification is RECIPROCAL'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])

=== General Comments

* ``This version of the Ruby license is the latest found in the dual
license COPYING dated from 2010-09-15 Per SPDX.org, Ruby is
disjunctively licensed project that allows the choice of this license
and another. The other license choice has changed over time (from GPL
originally, to BSD-2-Clause currently), so one needs to be aware of that
change. The Ruby License itself is un-versioned, but has varied a bit
over the years, the last substantive variation being in 2002. ''
(source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ruby.yml[Scancode])

=== URLs

* *Homepage:* http://www.ruby-lang.org/en/LICENSE.txt
* *SPDX:* http://spdx.org/licenses/Ruby.json
* *SPDX:* https://spdx.org/licenses/Ruby.html
* https://raw.githubusercontent.com/ruby/ruby/2cd6800fd8437b1f862f3f5c44db877159271d17/COPYING

=== Text

....

  1. You may make and give away verbatim copies of the source form of the
     software without restriction, provided that you duplicate all of the
     original copyright notices and associated disclaimers.

  2. You may modify your copy of the software in any way, provided that
     you do at least ONE of the following:

       a) place your modifications in the Public Domain or otherwise
          make them Freely Available, such as by posting said
          modifications to Usenet or an equivalent medium, or by allowing
          the author to include your modifications in the software.

       b) use the modified software only within your corporation or
          organization.

       c) give non-standard binaries non-standard names, with
          instructions on where to get the original software distribution.

       d) make other distribution arrangements with the author.

  3. You may distribute the software in object code or binary form,
     provided that you do at least ONE of the following:

       a) distribute the binaries and library files of the software,
          together with instructions (in the manual page or equivalent)
          on where to get the original distribution.

       b) accompany the distribution with the machine-readable source of
          the software.

       c) give non-standard binaries non-standard names, with
          instructions on where to get the original software distribution.

       d) make other distribution arrangements with the author.

  4. You may modify and include the part of the software into any other
     software (possibly commercial).  But some files in the distribution
     are not written by the author, so that they are not under these terms.

     For the list of those files and their copying conditions, see the
     file LEGAL.

  5. The scripts and library files supplied as input to or produced as
     output from the software do not automatically fall under the
     copyright of the software, but belong to whomever generated them,
     and may be sold commercially, and may be aggregated with this
     software.

  6. THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
     IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
     PURPOSE.
....

'''''

=== Raw Data

* SPDX
* BlueOak License List
* Scancode
* Google OSS Policy

....
{
    "__impliedNames": [
        "Ruby",
        "Ruby License",
        "scancode://ruby"
    ],
    "__impliedId": "Ruby",
    "__impliedComments": [
        [
            "Scancode",
            [
                "This version of the Ruby license is the latest found in the dual license\nCOPYING dated from 2010-09-15 Per SPDX.org, Ruby is disjunctively licensed\nproject that allows the choice of this license and another. The other\nlicense choice has changed over time (from GPL originally, to BSD-2-Clause\ncurrently), so one needs to be aware of that change. The Ruby License\nitself is un-versioned, but has varied a bit over the years, the last\nsubstantive variation being in 2002.\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Ruby License",
            "spdxDetailsURL": "http://spdx.org/licenses/Ruby.json",
            "_sourceURL": "https://spdx.org/licenses/Ruby.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.ruby-lang.org/en/LICENSE.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "Ruby",
                    "Ruby License"
                ],
                "__impliedId": "Ruby",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Ruby.json"
                    ],
                    [
                        null,
                        "http://www.ruby-lang.org/en/LICENSE.txt"
                    ]
                ]
            },
            "spdxLicenseId": "Ruby"
        },
        "Scancode": {
            "otherUrls": [
                "https://raw.githubusercontent.com/ruby/ruby/2cd6800fd8437b1f862f3f5c44db877159271d17/COPYING"
            ],
            "homepageUrl": "http://www.ruby-lang.org/en/LICENSE.txt",
            "shortName": "Ruby License",
            "textUrls": null,
            "text": "\n  1. You may make and give away verbatim copies of the source form of the\n     software without restriction, provided that you duplicate all of the\n     original copyright notices and associated disclaimers.\n\n  2. You may modify your copy of the software in any way, provided that\n     you do at least ONE of the following:\n\n       a) place your modifications in the Public Domain or otherwise\n          make them Freely Available, such as by posting said\n          modifications to Usenet or an equivalent medium, or by allowing\n          the author to include your modifications in the software.\n\n       b) use the modified software only within your corporation or\n          organization.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  3. You may distribute the software in object code or binary form,\n     provided that you do at least ONE of the following:\n\n       a) distribute the binaries and library files of the software,\n          together with instructions (in the manual page or equivalent)\n          on where to get the original distribution.\n\n       b) accompany the distribution with the machine-readable source of\n          the software.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  4. You may modify and include the part of the software into any other\n     software (possibly commercial).  But some files in the distribution\n     are not written by the author, so that they are not under these terms.\n\n     For the list of those files and their copying conditions, see the\n     file LEGAL.\n\n  5. The scripts and library files supplied as input to or produced as\n     output from the software do not automatically fall under the\n     copyright of the software, but belong to whomever generated them,\n     and may be sold commercially, and may be aggregated with this\n     software.\n\n  6. THIS SOFTWARE IS PROVIDED \"AS IS\" AND WITHOUT ANY EXPRESS OR\n     IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED\n     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n     PURPOSE.",
            "category": "Copyleft Limited",
            "osiUrl": null,
            "owner": "Ruby",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ruby.yml",
            "key": "ruby",
            "name": "Ruby License",
            "spdxId": "Ruby",
            "notes": "This version of the Ruby license is the latest found in the dual license\nCOPYING dated from 2010-09-15 Per SPDX.org, Ruby is disjunctively licensed\nproject that allows the choice of this license and another. The other\nlicense choice has changed over time (from GPL originally, to BSD-2-Clause\ncurrently), so one needs to be aware of that change. The Ruby License\nitself is un-versioned, but has varied a bit over the years, the last\nsubstantive variation being in 2002.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://ruby",
                    "Ruby License",
                    "Ruby"
                ],
                "__impliedId": "Ruby",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "This version of the Ruby license is the latest found in the dual license\nCOPYING dated from 2010-09-15 Per SPDX.org, Ruby is disjunctively licensed\nproject that allows the choice of this license and another. The other\nlicense choice has changed over time (from GPL originally, to BSD-2-Clause\ncurrently), so one needs to be aware of that change. The Ruby License\nitself is un-versioned, but has varied a bit over the years, the last\nsubstantive variation being in 2002.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft",
                "__impliedText": "\n  1. You may make and give away verbatim copies of the source form of the\n     software without restriction, provided that you duplicate all of the\n     original copyright notices and associated disclaimers.\n\n  2. You may modify your copy of the software in any way, provided that\n     you do at least ONE of the following:\n\n       a) place your modifications in the Public Domain or otherwise\n          make them Freely Available, such as by posting said\n          modifications to Usenet or an equivalent medium, or by allowing\n          the author to include your modifications in the software.\n\n       b) use the modified software only within your corporation or\n          organization.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  3. You may distribute the software in object code or binary form,\n     provided that you do at least ONE of the following:\n\n       a) distribute the binaries and library files of the software,\n          together with instructions (in the manual page or equivalent)\n          on where to get the original distribution.\n\n       b) accompany the distribution with the machine-readable source of\n          the software.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  4. You may modify and include the part of the software into any other\n     software (possibly commercial).  But some files in the distribution\n     are not written by the author, so that they are not under these terms.\n\n     For the list of those files and their copying conditions, see the\n     file LEGAL.\n\n  5. The scripts and library files supplied as input to or produced as\n     output from the software do not automatically fall under the\n     copyright of the software, but belong to whomever generated them,\n     and may be sold commercially, and may be aggregated with this\n     software.\n\n  6. THIS SOFTWARE IS PROVIDED \"AS IS\" AND WITHOUT ANY EXPRESS OR\n     IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED\n     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n     PURPOSE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.ruby-lang.org/en/LICENSE.txt"
                    ],
                    [
                        null,
                        "https://raw.githubusercontent.com/ruby/ruby/2cd6800fd8437b1f862f3f5c44db877159271d17/COPYING"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Ruby.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Ruby License",
            "id": "Ruby",
            "_implications": {
                "__impliedNames": [
                    "Ruby",
                    "Ruby License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Ruby.html"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "RECIPROCAL",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "Ruby",
            "_implications": {
                "__impliedNames": [
                    "Ruby"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "Google Classification is RECIPROCAL"
                        }
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NeutralJudgement",
                "contents": "Google Classification is RECIPROCAL"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "\n  1. You may make and give away verbatim copies of the source form of the\n     software without restriction, provided that you duplicate all of the\n     original copyright notices and associated disclaimers.\n\n  2. You may modify your copy of the software in any way, provided that\n     you do at least ONE of the following:\n\n       a) place your modifications in the Public Domain or otherwise\n          make them Freely Available, such as by posting said\n          modifications to Usenet or an equivalent medium, or by allowing\n          the author to include your modifications in the software.\n\n       b) use the modified software only within your corporation or\n          organization.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  3. You may distribute the software in object code or binary form,\n     provided that you do at least ONE of the following:\n\n       a) distribute the binaries and library files of the software,\n          together with instructions (in the manual page or equivalent)\n          on where to get the original distribution.\n\n       b) accompany the distribution with the machine-readable source of\n          the software.\n\n       c) give non-standard binaries non-standard names, with\n          instructions on where to get the original software distribution.\n\n       d) make other distribution arrangements with the author.\n\n  4. You may modify and include the part of the software into any other\n     software (possibly commercial).  But some files in the distribution\n     are not written by the author, so that they are not under these terms.\n\n     For the list of those files and their copying conditions, see the\n     file LEGAL.\n\n  5. The scripts and library files supplied as input to or produced as\n     output from the software do not automatically fall under the\n     copyright of the software, but belong to whomever generated them,\n     and may be sold commercially, and may be aggregated with this\n     software.\n\n  6. THIS SOFTWARE IS PROVIDED \"AS IS\" AND WITHOUT ANY EXPRESS OR\n     IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED\n     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\n     PURPOSE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Ruby.json"
        ],
        [
            null,
            "http://www.ruby-lang.org/en/LICENSE.txt"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Ruby.html"
        ],
        [
            "Homepage",
            "http://www.ruby-lang.org/en/LICENSE.txt"
        ],
        [
            null,
            "https://raw.githubusercontent.com/ruby/ruby/2cd6800fd8437b1f862f3f5c44db877159271d17/COPYING"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/Ruby.svg[image,title="dot"]