== Saxpath License (Saxpath)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Saxpath License
|Shortname |Saxpath
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Saxpath_License
* *SPDX:* http://spdx.org/licenses/Saxpath.json
* *SPDX:* https://spdx.org/licenses/Saxpath.html

=== Text

....
Redistribution and use in source and binary forms, with or without modification,
re permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions, and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions, and the disclaimer that follows these conditions in
the documentation and/or other materials provided with the distribution.

3. The name "SAXPath" must not be used to endorse or promote products derived
from this software without prior written permission. For written permission,
please contact license@saxpath.org.

4. Products derived from this software may not be called "SAXPath", nor may
"SAXPath" appear in their name, without prior written permission from the
SAXPath Project Management (pm@saxpath.org).

In addition, we request (but do not require) that you include in the end-user
documentation provided with the redistribution and/or in the software itself
an acknowledgement equivalent to the following:
"This product includes software developed by the SAXPath Project
(http://www.saxpath.org/)."

Alternatively, the acknowledgment may be graphical using the logos available
at http://www.saxpath.org/

THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE SAXPath
AUTHORS OR THE PROJECT CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Saxpath",
        "Saxpath License",
        "saxpath"
    ],
    "__impliedId": "Saxpath",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Saxpath",
                    "Saxpath",
                    "Saxpath License",
                    "saxpath"
                ],
                "__impliedId": "Saxpath"
            },
            "shortname": "Saxpath",
            "otherNames": [
                "Saxpath",
                "Saxpath License",
                "saxpath"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Saxpath License",
            "spdxDetailsURL": "http://spdx.org/licenses/Saxpath.json",
            "_sourceURL": "https://spdx.org/licenses/Saxpath.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Saxpath_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "Saxpath",
                    "Saxpath License"
                ],
                "__impliedId": "Saxpath",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Saxpath.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Saxpath_License"
                    ]
                ]
            },
            "spdxLicenseId": "Saxpath"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/Saxpath_License",
            "GPLv3 Compat?": "NO",
            "Short Name": "Saxpath",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Saxpath License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Saxpath License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Saxpath_License",
            "shortName": "Saxpath License",
            "textUrls": null,
            "text": "Redistribution and use in source and binary forms, with or without modification,\nre permitted provided that the following conditions are met:\n\n1. Redistributions of source code must retain the above copyright notice, this\nlist of conditions, and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright notice,\nthis list of conditions, and the disclaimer that follows these conditions in\nthe documentation and/or other materials provided with the distribution.\n\n3. The name \"SAXPath\" must not be used to endorse or promote products derived\nfrom this software without prior written permission. For written permission,\nplease contact license@saxpath.org.\n\n4. Products derived from this software may not be called \"SAXPath\", nor may\n\"SAXPath\" appear in their name, without prior written permission from the\nSAXPath Project Management (pm@saxpath.org).\n\nIn addition, we request (but do not require) that you include in the end-user\ndocumentation provided with the redistribution and/or in the software itself\nan acknowledgement equivalent to the following:\n\"This product includes software developed by the SAXPath Project\n(http://www.saxpath.org/).\"\n\nAlternatively, the acknowledgment may be graphical using the logos available\nat http://www.saxpath.org/\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,\nINCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE SAXPath\nAUTHORS OR THE PROJECT CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Codehaus",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/saxpath.yml",
            "key": "saxpath",
            "name": "Saxpath License",
            "spdxId": "Saxpath",
            "_implications": {
                "__impliedNames": [
                    "saxpath",
                    "Saxpath License",
                    "Saxpath"
                ],
                "__impliedId": "Saxpath",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nre permitted provided that the following conditions are met:\n\n1. Redistributions of source code must retain the above copyright notice, this\nlist of conditions, and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright notice,\nthis list of conditions, and the disclaimer that follows these conditions in\nthe documentation and/or other materials provided with the distribution.\n\n3. The name \"SAXPath\" must not be used to endorse or promote products derived\nfrom this software without prior written permission. For written permission,\nplease contact license@saxpath.org.\n\n4. Products derived from this software may not be called \"SAXPath\", nor may\n\"SAXPath\" appear in their name, without prior written permission from the\nSAXPath Project Management (pm@saxpath.org).\n\nIn addition, we request (but do not require) that you include in the end-user\ndocumentation provided with the redistribution and/or in the software itself\nan acknowledgement equivalent to the following:\n\"This product includes software developed by the SAXPath Project\n(http://www.saxpath.org/).\"\n\nAlternatively, the acknowledgment may be graphical using the logos available\nat http://www.saxpath.org/\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,\nINCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE SAXPath\nAUTHORS OR THE PROJECT CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Saxpath_License"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Saxpath.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Saxpath License",
            "id": "Saxpath",
            "_implications": {
                "__impliedNames": [
                    "Saxpath"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Saxpath.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Redistribution and use in source and binary forms, with or without modification,\nre permitted provided that the following conditions are met:\n\n1. Redistributions of source code must retain the above copyright notice, this\nlist of conditions, and the following disclaimer.\n\n2. Redistributions in binary form must reproduce the above copyright notice,\nthis list of conditions, and the disclaimer that follows these conditions in\nthe documentation and/or other materials provided with the distribution.\n\n3. The name \"SAXPath\" must not be used to endorse or promote products derived\nfrom this software without prior written permission. For written permission,\nplease contact license@saxpath.org.\n\n4. Products derived from this software may not be called \"SAXPath\", nor may\n\"SAXPath\" appear in their name, without prior written permission from the\nSAXPath Project Management (pm@saxpath.org).\n\nIn addition, we request (but do not require) that you include in the end-user\ndocumentation provided with the redistribution and/or in the software itself\nan acknowledgement equivalent to the following:\n\"This product includes software developed by the SAXPath Project\n(http://www.saxpath.org/).\"\n\nAlternatively, the acknowledgment may be graphical using the logos available\nat http://www.saxpath.org/\n\nTHIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,\nINCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\nFITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE SAXPath\nAUTHORS OR THE PROJECT CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Saxpath.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Saxpath_License"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Saxpath.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Saxpath_License"
        ]
    ]
}
....