== Sendmail License 8.23 (Sendmail-8.23)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Sendmail License 8.23
|Shortname |Sendmail-8.23
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/Sendmail-8.23.json
* https://www.proofpoint.com/sites/default/files/sendmail-license.pdf
* https://web.archive.org/web/20181003101040/https://www.proofpoint.com/sites/default/files/sendmail-license.pdf

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/Sendmail-8.23.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Sendmail-8.23",
        "Sendmail License 8.23"
    ],
    "__impliedId": "Sendmail-8.23",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Sendmail-8.23"
                ],
                "__impliedId": "Sendmail-8.23"
            },
            "shortname": "Sendmail-8.23",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Sendmail License 8.23",
            "spdxDetailsURL": "http://spdx.org/licenses/Sendmail-8.23.json",
            "_sourceURL": "https://spdx.org/licenses/Sendmail-8.23.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.proofpoint.com/sites/default/files/sendmail-license.pdf",
                "https://web.archive.org/web/20181003101040/https://www.proofpoint.com/sites/default/files/sendmail-license.pdf"
            ],
            "_implications": {
                "__impliedNames": [
                    "Sendmail-8.23",
                    "Sendmail License 8.23"
                ],
                "__impliedId": "Sendmail-8.23",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Sendmail-8.23.json"
                    ],
                    [
                        null,
                        "https://www.proofpoint.com/sites/default/files/sendmail-license.pdf"
                    ],
                    [
                        null,
                        "https://web.archive.org/web/20181003101040/https://www.proofpoint.com/sites/default/files/sendmail-license.pdf"
                    ]
                ]
            },
            "spdxLicenseId": "Sendmail-8.23"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Sendmail-8.23.json"
        ],
        [
            null,
            "https://www.proofpoint.com/sites/default/files/sendmail-license.pdf"
        ],
        [
            null,
            "https://web.archive.org/web/20181003101040/https://www.proofpoint.com/sites/default/files/sendmail-license.pdf"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Sendmail-8.23.svg
