== Solderpad Hardware License v0.5 (SHL-0.5)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Solderpad Hardware License v0.5
|Shortname |SHL-0.5
|Rating |Unknown, probably Attention or Stop or No-Go
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/SHL-0.5.json
* https://solderpad.org/licenses/SHL-0.5/

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/SHL-0.5.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "SHL-0.5",
        "Solderpad Hardware License v0.5"
    ],
    "__impliedId": "SHL-0.5",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "SHL-0.5"
                ],
                "__impliedId": "SHL-0.5"
            },
            "shortname": "SHL-0.5",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Solderpad Hardware License v0.5",
            "spdxDetailsURL": "http://spdx.org/licenses/SHL-0.5.json",
            "_sourceURL": "https://spdx.org/licenses/SHL-0.5.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://solderpad.org/licenses/SHL-0.5/"
            ],
            "_implications": {
                "__impliedNames": [
                    "SHL-0.5",
                    "Solderpad Hardware License v0.5"
                ],
                "__impliedId": "SHL-0.5",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/SHL-0.5.json"
                    ],
                    [
                        null,
                        "https://solderpad.org/licenses/SHL-0.5/"
                    ]
                ]
            },
            "spdxLicenseId": "SHL-0.5"
        }
    },
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/SHL-0.5.json"
        ],
        [
            null,
            "https://solderpad.org/licenses/SHL-0.5/"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/SHL-0.5.svg
