== Standard ML of New Jersey License (SMLNJ)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Standard ML of New Jersey License
|Shortname |SMLNJ
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://standard-ml-nj+`
* `+Standard ML of New Jersey+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== General Comments

* ``per SPDX.org, SPDX ended up with this license on the license list
twice once as of v1.17 with the short identifier SMLNJ and then added
(again) as of v1.20 with the short identifier StandardML-NJ. The former
list entry has been deprecated. Here, this license is not verbatim the
SPDX SMLMJ, but instead the more generic variant as used in the Java CUP
parser generator that has no specific references to Lucent and Bell Labs
and is therefore a better choice for reuse. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.yml[Scancode])

=== URLs

* *Homepage:* http://www.smlnj.org//license.html
* *SPDX:* http://spdx.org/licenses/SMLNJ.json
* *SPDX:* https://spdx.org/licenses/SMLNJ.html
* https://www.smlnj.org/license.html
* http://www.gnu.org/licenses/license-list.html#StandardMLofNJ
* http://www2.cs.tum.edu/projects/cup/

=== Text

....
Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both the copyright notice and this permission notice and warranty
disclaimer appear in supporting documentation, and that the names of the
authors or their employers not be used in advertising or publicity
pertaining to distribution of the software without specific, written
prior permission.

The authors and their employers disclaim all warranties with regard to
this software, including all implied warranties of merchantability and
fitness. In no event shall the authors or their employers be liable for
any special, indirect or consequential damages or any damages whatsoever
resulting from loss of use, data or profits, whether in an action of
contract, negligence or other tortious action, arising out of or in
connection with the use or performance of this software.
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/SMLNJ.html[SPDX]
* https://blueoakcouncil.org/list[BlueOak License List]
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.yml[Scancode]

==== Dot Cluster Graph

../dot/SMLNJ.svg

==== Raw JSON

....
{
    "__impliedNames": [
        "SMLNJ",
        "Standard ML of New Jersey License",
        "scancode://standard-ml-nj",
        "Standard ML of New Jersey"
    ],
    "__impliedId": "SMLNJ",
    "__impliedComments": [
        [
            "Scancode",
            [
                "per SPDX.org, SPDX ended up with this license on the license list twice\nonce as of v1.17 with the short identifier SMLNJ and then added (again) as\nof v1.20 with the short identifier StandardML-NJ. The former list entry has\nbeen deprecated. Here, this license is not verbatim the SPDX SMLMJ, but\ninstead the more generic variant as used in the Java CUP parser generator\nthat has no specific references to Lucent and Bell Labs and is therefore a\nbetter choice for reuse.\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Standard ML of New Jersey License",
            "spdxDetailsURL": "http://spdx.org/licenses/SMLNJ.json",
            "_sourceURL": "https://spdx.org/licenses/SMLNJ.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://www.smlnj.org/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "SMLNJ",
                    "Standard ML of New Jersey License"
                ],
                "__impliedId": "SMLNJ",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/SMLNJ.json"
                    ],
                    [
                        null,
                        "https://www.smlnj.org/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "SMLNJ"
        },
        "Scancode": {
            "otherUrls": [
                "http://www.gnu.org/licenses/license-list.html#StandardMLofNJ",
                "http://www2.cs.tum.edu/projects/cup/",
                "https://www.smlnj.org/license.html"
            ],
            "homepageUrl": "http://www.smlnj.org//license.html",
            "shortName": "Standard ML of New Jersey",
            "textUrls": null,
            "text": "Permission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose and without fee is hereby granted,\nprovided that the above copyright notice appear in all copies and that\nboth the copyright notice and this permission notice and warranty\ndisclaimer appear in supporting documentation, and that the names of the\nauthors or their employers not be used in advertising or publicity\npertaining to distribution of the software without specific, written\nprior permission.\n\nThe authors and their employers disclaim all warranties with regard to\nthis software, including all implied warranties of merchantability and\nfitness. In no event shall the authors or their employers be liable for\nany special, indirect or consequential damages or any damages whatsoever\nresulting from loss of use, data or profits, whether in an action of\ncontract, negligence or other tortious action, arising out of or in\nconnection with the use or performance of this software.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Alcatel-Lucent",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.yml",
            "key": "standard-ml-nj",
            "name": "Standard ML of New Jersey",
            "spdxId": "SMLNJ",
            "notes": "per SPDX.org, SPDX ended up with this license on the license list twice\nonce as of v1.17 with the short identifier SMLNJ and then added (again) as\nof v1.20 with the short identifier StandardML-NJ. The former list entry has\nbeen deprecated. Here, this license is not verbatim the SPDX SMLMJ, but\ninstead the more generic variant as used in the Java CUP parser generator\nthat has no specific references to Lucent and Bell Labs and is therefore a\nbetter choice for reuse.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://standard-ml-nj",
                    "Standard ML of New Jersey",
                    "SMLNJ"
                ],
                "__impliedId": "SMLNJ",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "per SPDX.org, SPDX ended up with this license on the license list twice\nonce as of v1.17 with the short identifier SMLNJ and then added (again) as\nof v1.20 with the short identifier StandardML-NJ. The former list entry has\nbeen deprecated. Here, this license is not verbatim the SPDX SMLMJ, but\ninstead the more generic variant as used in the Java CUP parser generator\nthat has no specific references to Lucent and Bell Labs and is therefore a\nbetter choice for reuse.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Permission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose and without fee is hereby granted,\nprovided that the above copyright notice appear in all copies and that\nboth the copyright notice and this permission notice and warranty\ndisclaimer appear in supporting documentation, and that the names of the\nauthors or their employers not be used in advertising or publicity\npertaining to distribution of the software without specific, written\nprior permission.\n\nThe authors and their employers disclaim all warranties with regard to\nthis software, including all implied warranties of merchantability and\nfitness. In no event shall the authors or their employers be liable for\nany special, indirect or consequential damages or any damages whatsoever\nresulting from loss of use, data or profits, whether in an action of\ncontract, negligence or other tortious action, arising out of or in\nconnection with the use or performance of this software.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.smlnj.org//license.html"
                    ],
                    [
                        null,
                        "http://www.gnu.org/licenses/license-list.html#StandardMLofNJ"
                    ],
                    [
                        null,
                        "http://www2.cs.tum.edu/projects/cup/"
                    ],
                    [
                        null,
                        "https://www.smlnj.org/license.html"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/SMLNJ.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Standard ML of New Jersey License",
            "id": "SMLNJ",
            "_implications": {
                "__impliedNames": [
                    "SMLNJ",
                    "Standard ML of New Jersey License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/SMLNJ.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "Permission to use, copy, modify, and distribute this software and its\ndocumentation for any purpose and without fee is hereby granted,\nprovided that the above copyright notice appear in all copies and that\nboth the copyright notice and this permission notice and warranty\ndisclaimer appear in supporting documentation, and that the names of the\nauthors or their employers not be used in advertising or publicity\npertaining to distribution of the software without specific, written\nprior permission.\n\nThe authors and their employers disclaim all warranties with regard to\nthis software, including all implied warranties of merchantability and\nfitness. In no event shall the authors or their employers be liable for\nany special, indirect or consequential damages or any damages whatsoever\nresulting from loss of use, data or profits, whether in an action of\ncontract, negligence or other tortious action, arising out of or in\nconnection with the use or performance of this software.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/SMLNJ.json"
        ],
        [
            null,
            "https://www.smlnj.org/license.html"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/SMLNJ.html"
        ],
        [
            "Homepage",
            "http://www.smlnj.org//license.html"
        ],
        [
            null,
            "http://www.gnu.org/licenses/license-list.html#StandardMLofNJ"
        ],
        [
            null,
            "http://www2.cs.tum.edu/projects/cup/"
        ]
    ]
}
....