== Spencer License 94 (Spencer-94)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Spencer License 94
|Shortname |Spencer-94
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://hs-regexp+`
* `+Henry Spencer Regexp License+`

=== Comments on (easy) usability

* **↓**Rating is: Lead (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== URLs

* *Homepage:* https://github.com/garyhouston/regex/blob/master/COPYRIGHT
* *SPDX:* http://spdx.org/licenses/Spencer-94.json
* *SPDX:* https://spdx.org/licenses/Spencer-94.html
* https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License

=== Text

....
This software is not subject to any license of the American Telephone and
Telegraph Company or of the Regents of the University of California.

Permission is granted to anyone to use this software for any purpose on any
computer system, and to alter it and redistribute it, subject to the following
restrictions:

1. The author is not responsible for the consequences of use of this software,
no matter how awful, even if they arise from flaws in it.

2. The origin of this software must not be misrepresented, either by explicit
claim or by omission. Since few users ever read sources, credits must appear in
the documentation.

3. Altered versions must be plainly marked as such, and must not be
misrepresented as being the original software. Since few users ever read
sources, credits must appear in the documentation.

4. This notice may not be removed or altered.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Spencer-94",
        "Spencer License 94",
        "scancode://hs-regexp",
        "Henry Spencer Regexp License"
    ],
    "__impliedId": "Spencer-94",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Spencer-94",
                    "Spencer-94",
                    "Spencer License 94",
                    "scancode://hs-regexp",
                    "Henry Spencer Regexp License"
                ],
                "__impliedId": "Spencer-94"
            },
            "shortname": "Spencer-94",
            "otherNames": [
                "Spencer-94",
                "Spencer License 94",
                "scancode://hs-regexp",
                "Henry Spencer Regexp License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Spencer License 94",
            "spdxDetailsURL": "http://spdx.org/licenses/Spencer-94.json",
            "_sourceURL": "https://spdx.org/licenses/Spencer-94.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "Spencer-94",
                    "Spencer License 94"
                ],
                "__impliedId": "Spencer-94",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Spencer-94.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"
                    ]
                ]
            },
            "spdxLicenseId": "Spencer-94"
        },
        "Scancode": {
            "otherUrls": [
                "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"
            ],
            "homepageUrl": "https://github.com/garyhouston/regex/blob/master/COPYRIGHT",
            "shortName": "Henry Spencer Regexp License",
            "textUrls": null,
            "text": "This software is not subject to any license of the American Telephone and\nTelegraph Company or of the Regents of the University of California.\n\nPermission is granted to anyone to use this software for any purpose on any\ncomputer system, and to alter it and redistribute it, subject to the following\nrestrictions:\n\n1. The author is not responsible for the consequences of use of this software,\nno matter how awful, even if they arise from flaws in it.\n\n2. The origin of this software must not be misrepresented, either by explicit\nclaim or by omission. Since few users ever read sources, credits must appear in\nthe documentation.\n\n3. Altered versions must be plainly marked as such, and must not be\nmisrepresented as being the original software. Since few users ever read\nsources, credits must appear in the documentation.\n\n4. This notice may not be removed or altered.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Henry Spencer",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/hs-regexp.yml",
            "key": "hs-regexp",
            "name": "Henry Spencer Regexp License",
            "spdxId": "Spencer-94",
            "_implications": {
                "__impliedNames": [
                    "scancode://hs-regexp",
                    "Henry Spencer Regexp License",
                    "Spencer-94"
                ],
                "__impliedId": "Spencer-94",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This software is not subject to any license of the American Telephone and\nTelegraph Company or of the Regents of the University of California.\n\nPermission is granted to anyone to use this software for any purpose on any\ncomputer system, and to alter it and redistribute it, subject to the following\nrestrictions:\n\n1. The author is not responsible for the consequences of use of this software,\nno matter how awful, even if they arise from flaws in it.\n\n2. The origin of this software must not be misrepresented, either by explicit\nclaim or by omission. Since few users ever read sources, credits must appear in\nthe documentation.\n\n3. Altered versions must be plainly marked as such, and must not be\nmisrepresented as being the original software. Since few users ever read\nsources, credits must appear in the documentation.\n\n4. This notice may not be removed or altered.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://github.com/garyhouston/regex/blob/master/COPYRIGHT"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Spencer-94.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Spencer License 94",
            "id": "Spencer-94",
            "_implications": {
                "__impliedNames": [
                    "Spencer-94"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Spencer-94.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This software is not subject to any license of the American Telephone and\nTelegraph Company or of the Regents of the University of California.\n\nPermission is granted to anyone to use this software for any purpose on any\ncomputer system, and to alter it and redistribute it, subject to the following\nrestrictions:\n\n1. The author is not responsible for the consequences of use of this software,\nno matter how awful, even if they arise from flaws in it.\n\n2. The origin of this software must not be misrepresented, either by explicit\nclaim or by omission. Since few users ever read sources, credits must appear in\nthe documentation.\n\n3. Altered versions must be plainly marked as such, and must not be\nmisrepresented as being the original software. Since few users ever read\nsources, credits must appear in the documentation.\n\n4. This notice may not be removed or altered.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Spencer-94.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Henry_Spencer_Reg-Ex_Library_License"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Spencer-94.html"
        ],
        [
            "Homepage",
            "https://github.com/garyhouston/regex/blob/master/COPYRIGHT"
        ]
    ]
}
....