== SSH short notice (SSH-short)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |SSH short notice
|Shortname |SSH-short
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://tatu-ylonen+`
* `+Tatu Ylonen License+`

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/SSH-short.json
* https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h
* http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1
* https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp

=== Text

....
As far as I am concerned, the code I have written for this software
can be used freely for any purpose.  Any derived versions of this
software must be clearly marked as such, and if the derived work is
incompatible with the protocol description in the RFC file, it must be
called by a name other than "ssh" or "Secure Shell".
....

'''''

=== Raw Data

==== Facts

* https://spdx.org/licenses/SSH-short.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tatu-ylonen.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "SSH-short",
        "SSH short notice",
        "scancode://tatu-ylonen",
        "Tatu Ylonen License"
    ],
    "__impliedId": "SSH-short",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "SSH short notice",
            "spdxDetailsURL": "http://spdx.org/licenses/SSH-short.json",
            "_sourceURL": "https://spdx.org/licenses/SSH-short.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h",
                "http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1",
                "https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp"
            ],
            "_implications": {
                "__impliedNames": [
                    "SSH-short",
                    "SSH short notice"
                ],
                "__impliedId": "SSH-short",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/SSH-short.json"
                    ],
                    [
                        null,
                        "https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h"
                    ],
                    [
                        null,
                        "http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1"
                    ],
                    [
                        null,
                        "https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp"
                    ]
                ]
            },
            "spdxLicenseId": "SSH-short"
        },
        "Scancode": {
            "otherUrls": [
                "https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h",
                "http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1",
                "https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp"
            ],
            "homepageUrl": null,
            "shortName": "Tatu Ylonen License",
            "textUrls": null,
            "text": "As far as I am concerned, the code I have written for this software\ncan be used freely for any purpose.  Any derived versions of this\nsoftware must be clearly marked as such, and if the derived work is\nincompatible with the protocol description in the RFC file, it must be\ncalled by a name other than \"ssh\" or \"Secure Shell\".\n",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Secure Shell",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tatu-ylonen.yml",
            "key": "tatu-ylonen",
            "name": "Tatu Ylonen License",
            "spdxId": "SSH-short",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://tatu-ylonen",
                    "Tatu Ylonen License",
                    "SSH-short"
                ],
                "__impliedId": "SSH-short",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "As far as I am concerned, the code I have written for this software\ncan be used freely for any purpose.  Any derived versions of this\nsoftware must be clearly marked as such, and if the derived work is\nincompatible with the protocol description in the RFC file, it must be\ncalled by a name other than \"ssh\" or \"Secure Shell\".\n",
                "__impliedURLs": [
                    [
                        null,
                        "https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h"
                    ],
                    [
                        null,
                        "http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1"
                    ],
                    [
                        null,
                        "https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp"
                    ]
                ]
            }
        }
    },
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "As far as I am concerned, the code I have written for this software\ncan be used freely for any purpose.  Any derived versions of this\nsoftware must be clearly marked as such, and if the derived work is\nincompatible with the protocol description in the RFC file, it must be\ncalled by a name other than \"ssh\" or \"Secure Shell\".\n",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/SSH-short.json"
        ],
        [
            null,
            "https://github.com/openssh/openssh-portable/blob/1b11ea7c58cd5c59838b5fa574cd456d6047b2d4/pathnames.h"
        ],
        [
            null,
            "http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1"
        ],
        [
            null,
            "https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/SSH-short.svg