== TCL/TK License (TCL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |TCL/TK License
|Shortname |TCL
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/TCL.html
* *SPDX:* http://spdx.org/licenses/TCL.json
* http://www.tcl.tk/software/tcltk/license.html
* https://fedoraproject.org/wiki/Licensing/TCL

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/finos/OSLC-handbook/blob/master/src/TCL.yaml[finos/OSLC-handbook]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/TCL.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "TCL",
        "TCL/TK License"
    ],
    "__impliedId": "TCL",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "TCL"
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "TCL"
                ],
                "__impliedId": "TCL"
            },
            "shortname": "TCL",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "TCL/TK License",
            "spdxDetailsURL": "http://spdx.org/licenses/TCL.json",
            "_sourceURL": "https://spdx.org/licenses/TCL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.tcl.tk/software/tcltk/license.html",
                "https://fedoraproject.org/wiki/Licensing/TCL"
            ],
            "_implications": {
                "__impliedNames": [
                    "TCL",
                    "TCL/TK License"
                ],
                "__impliedId": "TCL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/TCL.json"
                    ],
                    [
                        null,
                        "http://www.tcl.tk/software/tcltk/license.html"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/TCL"
                    ]
                ]
            },
            "spdxLicenseId": "TCL"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/TCL",
            "GPLv3 Compat?": "Yes",
            "Short Name": "TCL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "TCL/TK License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "TCL/TK License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "TCL"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "TCL"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "TCL",
            "copyleftkind": "NoCopyleft"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/TCL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "TCL/TK License",
            "id": "TCL",
            "_implications": {
                "__impliedNames": [
                    "TCL",
                    "TCL/TK License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/TCL.html"
                    ]
                ]
            }
        },
        "finos/OSLC-handbook": {
            "terms": [
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Provide copy of license",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "UB",
                        "MB",
                        "US",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Retain copyright notices",
                    "termComplianceNotes": null,
                    "termType": "condition"
                },
                {
                    "termUseCases": [
                        "MB",
                        "MS"
                    ],
                    "termSeeAlso": null,
                    "termDescription": "Modified versions need not follow this license, provided that new license terms appear on first page of each applicable file",
                    "termComplianceNotes": null,
                    "termType": "other"
                }
            ],
            "_sourceURL": "https://github.com/finos/OSLC-handbook/blob/master/src/TCL.yaml",
            "name": "TCL/TK License",
            "nameFromFilename": "TCL",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "TCL",
                    "TCL/TK License"
                ]
            },
            "licenseId": [
                "TCL",
                "TCL/TK License"
            ]
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/TCL.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/TCL.json"
        ],
        [
            null,
            "http://www.tcl.tk/software/tcltk/license.html"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/TCL"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/TCL.svg
