== TCP Wrappers License (TCP-wrappers)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |TCP Wrappers License
|Shortname |TCP-wrappers
|Rating |Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/TCP-wrappers.html
* *SPDX:* http://spdx.org/licenses/TCP-wrappers.json
* http://rc.quest.com/topics/openssh/license.php#tcpwrappers

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://spdx.org/licenses/TCP-wrappers.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "TCP-wrappers",
        "TCP Wrappers License"
    ],
    "__impliedId": "TCP-wrappers",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "TCP-wrappers"
                ],
                "__impliedId": "TCP-wrappers"
            },
            "shortname": "TCP-wrappers",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "TCP Wrappers License",
            "spdxDetailsURL": "http://spdx.org/licenses/TCP-wrappers.json",
            "_sourceURL": "https://spdx.org/licenses/TCP-wrappers.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://rc.quest.com/topics/openssh/license.php#tcpwrappers"
            ],
            "_implications": {
                "__impliedNames": [
                    "TCP-wrappers",
                    "TCP Wrappers License"
                ],
                "__impliedId": "TCP-wrappers",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/TCP-wrappers.json"
                    ],
                    [
                        null,
                        "http://rc.quest.com/topics/openssh/license.php#tcpwrappers"
                    ]
                ]
            },
            "spdxLicenseId": "TCP-wrappers"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/TCP-wrappers.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "TCP Wrappers License",
            "id": "TCP-wrappers",
            "_implications": {
                "__impliedNames": [
                    "TCP-wrappers",
                    "TCP Wrappers License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/TCP-wrappers.html"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "TCP-wrappers",
            "_implications": {
                "__impliedNames": [
                    "TCP-wrappers"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/TCP-wrappers.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/TCP-wrappers.json"
        ],
        [
            null,
            "http://rc.quest.com/topics/openssh/license.php#tcpwrappers"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/TCP-wrappers.svg
