== TMate Open Source License (TMate)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |TMate Open Source License
|Shortname |TMate
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |Copyleft
|===

*Other Names:*

* `+scancode://tmate+`
* `+TMate Open Source License for "TMate JavaSVN library"+`

=== Description

____
https://svnkit.com/license.html
____

(source: https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== Comments on (easy) usability

* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``https://svnkit.com/license.html'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:* http://svnkit.com/licensing.html
* *SPDX:* http://spdx.org/licenses/TMate.json
* *open-license:* http://open-license.hitachi.com/licenses/972
* *open-license:* http://open-license.hitachi.com/licenses/1391
* http://svnkit.com/license.html

=== Text

....
This license applies to all portions of TMate SVNKit library, which 
are not externally-maintained libraries (e.g. Ganymed SSH library).

All the source code and compiled classes in package org.tigris.subversion.javahl
except SvnClient class are covered by the license in JAVAHL-LICENSE file

Copyright (c) 2004-2009 TMate Software. All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
      this list of conditions and the following disclaimer.
      
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.
      
    * Redistributions in any form must be accompanied by information on how to 
      obtain complete source code for the software that uses SVNKit and any 
      accompanying software that uses the software that uses SVNKit. The source 
      code must either be included in the distribution or be available for no 
      more than the cost of distribution plus a nominal fee, and must be freely 
      redistributable under reasonable conditions. For an executable file, complete 
      source code means the source code for all modules it contains. It does not 
      include source code for modules or files that typically accompany the major 
      components of the operating system on which the executable file runs.
      
    * Redistribution in any form without redistributing source code for software 
      that uses SVNKit is possible only when such redistribution is explictly permitted 
      by TMate Software. Please, contact TMate Software at support@svnkit.com to 
      get such permission.

THIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE 
DISCLAIMED. 

IN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/TMate.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tmate.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "TMate",
        "TMate Open Source License",
        "scancode://tmate",
        "TMate Open Source License for \"TMate JavaSVN library\""
    ],
    "__impliedId": "TMate",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "TMate"
    ],
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "https://svnkit.com/license.html"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "TMate"
                ],
                "__impliedId": "TMate"
            },
            "shortname": "TMate",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "TMate Open Source License",
            "spdxDetailsURL": "http://spdx.org/licenses/TMate.json",
            "_sourceURL": "https://spdx.org/licenses/TMate.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://svnkit.com/license.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "TMate",
                    "TMate Open Source License"
                ],
                "__impliedId": "TMate",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/TMate.json"
                    ],
                    [
                        null,
                        "http://svnkit.com/license.html"
                    ]
                ]
            },
            "spdxLicenseId": "TMate"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://svnkit.com/license.html",
            "GPLv3 Compat?": "NO",
            "Short Name": "TMate",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "TMate Open Source License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "TMate Open Source License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "TMate"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://svnkit.com/licensing.html",
            "shortName": "TMate Open Source License",
            "textUrls": null,
            "text": "This license applies to all portions of TMate SVNKit library, which \nare not externally-maintained libraries (e.g. Ganymed SSH library).\n\nAll the source code and compiled classes in package org.tigris.subversion.javahl\nexcept SvnClient class are covered by the license in JAVAHL-LICENSE file\n\nCopyright (c) 2004-2009 TMate Software. All rights reserved.\n\nRedistribution and use in source and binary forms, with or without modification, \nare permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright notice, \n      this list of conditions and the following disclaimer.\n      \n    * Redistributions in binary form must reproduce the above copyright notice, \n      this list of conditions and the following disclaimer in the documentation \n      and/or other materials provided with the distribution.\n      \n    * Redistributions in any form must be accompanied by information on how to \n      obtain complete source code for the software that uses SVNKit and any \n      accompanying software that uses the software that uses SVNKit. The source \n      code must either be included in the distribution or be available for no \n      more than the cost of distribution plus a nominal fee, and must be freely \n      redistributable under reasonable conditions. For an executable file, complete \n      source code means the source code for all modules it contains. It does not \n      include source code for modules or files that typically accompany the major \n      components of the operating system on which the executable file runs.\n      \n    * Redistribution in any form without redistributing source code for software \n      that uses SVNKit is possible only when such redistribution is explictly permitted \n      by TMate Software. Please, contact TMate Software at support@svnkit.com to \n      get such permission.\n\nTHIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF \nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE \nDISCLAIMED. \n\nIN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, \nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT \nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF \nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF \nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
            "category": "Copyleft",
            "osiUrl": null,
            "owner": "SVNKit (TMate)",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tmate.yml",
            "key": "tmate",
            "name": "TMate Open Source License",
            "spdxId": "TMate",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://tmate",
                    "TMate Open Source License",
                    "TMate"
                ],
                "__impliedId": "TMate",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "Copyleft"
                    ]
                ],
                "__calculatedCopyleft": "Copyleft",
                "__impliedText": "This license applies to all portions of TMate SVNKit library, which \nare not externally-maintained libraries (e.g. Ganymed SSH library).\n\nAll the source code and compiled classes in package org.tigris.subversion.javahl\nexcept SvnClient class are covered by the license in JAVAHL-LICENSE file\n\nCopyright (c) 2004-2009 TMate Software. All rights reserved.\n\nRedistribution and use in source and binary forms, with or without modification, \nare permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright notice, \n      this list of conditions and the following disclaimer.\n      \n    * Redistributions in binary form must reproduce the above copyright notice, \n      this list of conditions and the following disclaimer in the documentation \n      and/or other materials provided with the distribution.\n      \n    * Redistributions in any form must be accompanied by information on how to \n      obtain complete source code for the software that uses SVNKit and any \n      accompanying software that uses the software that uses SVNKit. The source \n      code must either be included in the distribution or be available for no \n      more than the cost of distribution plus a nominal fee, and must be freely \n      redistributable under reasonable conditions. For an executable file, complete \n      source code means the source code for all modules it contains. It does not \n      include source code for modules or files that typically accompany the major \n      components of the operating system on which the executable file runs.\n      \n    * Redistribution in any form without redistributing source code for software \n      that uses SVNKit is possible only when such redistribution is explictly permitted \n      by TMate Software. Please, contact TMate Software at support@svnkit.com to \n      get such permission.\n\nTHIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF \nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE \nDISCLAIMED. \n\nIN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, \nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT \nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF \nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF \nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://svnkit.com/licensing.html"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "https://svnkit.com/license.html",
            "notices": [
                {
                    "content": "the software is provided by the copyright holder \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, and non-infringement. The warranties include, but are not limited to, the implied warranties of commercial applicability, fitness for a particular purpose, and non-infringement.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "The copyright holder may be liable for direct, indirect, and incidental damages arising from the use of the software, regardless of the cause of the damage, and regardless of whether the liability is based on contract, strict liability, or tort (including negligence), even if he or she has been advised of the possibility of such damages. in no event shall you be liable for any damages, incidental, special, exemplary, or consequential damages (including, but not limited to, compensation for procurement of substitute or substitute services, loss of use, loss of data, loss of profits, or business interruption) "
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/972",
            "content": "The TMate Open Source License.\r\n\r\nThis license applies to all portions of TMate SVNKit library, which \r\nare not externally-maintained libraries (e.g. Ganymed SSH library).\r\n\r\nAll the source code and compiled classes in package org.tigris.subversion.javahl\r\nexcept SvnClient class are covered by the license in JAVAHL-LICENSE file\r\n\r\nCopyright (c) 2004-2012 TMate Software. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification, \r\nare permitted provided that the following conditions are met:\r\n\r\n    * Redistributions of source code must retain the above copyright notice, \r\n      this list of conditions and the following disclaimer.\r\n      \r\n    * Redistributions in binary form must reproduce the above copyright notice, \r\n      this list of conditions and the following disclaimer in the documentation \r\n      and/or other materials provided with the distribution.\r\n      \r\n    * Redistributions in any form must be accompanied by information on how to \r\n      obtain complete source code for the software that uses SVNKit and any \r\n      accompanying software that uses the software that uses SVNKit. The source \r\n      code must either be included in the distribution or be available for no \r\n      more than the cost of distribution plus a nominal fee, and must be freely \r\n      redistributable under reasonable conditions. For an executable file, complete \r\n      source code means the source code for all modules it contains. It does not \r\n      include source code for modules or files that typically accompany the major \r\n      components of the operating system on which the executable file runs.\r\n      \r\n    * Redistribution in any form without redistributing source code for software \r\n      that uses SVNKit is possible only when such redistribution is explictly permitted \r\n      by TMate Software. Please, contact TMate Software at support@svnkit.com to \r\n      get such permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED\r\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF \r\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE \r\nDISCLAIMED. \r\n\r\nIN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, \r\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT \r\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \r\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF \r\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \r\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF \r\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
            "name": "TMate Open Source License",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "OR": [
                                    {
                                        "name": "Attach the source code of the software that uses the software in question.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Tell them that the source code for the software that uses the software is available in exchange for a fee of about the cost of distribution.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Obtain express permission from the copyright holder not to redistribute the source code of software that uses the software.",
                                        "type": "OBLIGATION"
                                    }
                                ]
                            },
                            {
                                "OR": [
                                    {
                                        "name": "Attach the source code of the software that accompanies the software, which is the software that uses the software that uses the software.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Communicate that the source code for the software that accompanies the software, which is the software that uses the software, is available",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Obtain the express permission of the copyright holder that he may not redistribute the source code of any software that accompanies the software that uses the software, which is the software that uses the software.",
                                        "type": "OBLIGATION"
                                    }
                                ]
                            }
                        ]
                    },
                    "description": "The source code is redistributed under reasonable conditions. â Permission may be obtained from the copyright holder at support@svnkit.comã«é£çµ¡ãã."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "OR": [
                                    {
                                        "name": "Attach the source code corresponding to the software in question.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Tell them that the corresponding source code for the software is available in exchange for a fee for the cost of distribution.",
                                        "type": "OBLIGATION"
                                    }
                                ]
                            },
                            {
                                "OR": [
                                    {
                                        "name": "Attach the source code of the software that uses the software in question.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Tell them that the source code for the software that uses the software is available in exchange for a fee of about the cost of distribution.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Obtain express permission from the copyright holder not to redistribute the source code of software that uses the software.",
                                        "type": "OBLIGATION"
                                    }
                                ]
                            },
                            {
                                "OR": [
                                    {
                                        "name": "Attach the source code of the software that accompanies the software, which is the software that uses the software that uses the software.",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Communicate that the source code for the software that accompanies the software, which is the software that uses the software, is available",
                                        "type": "OBLIGATION"
                                    },
                                    {
                                        "name": "Obtain the express permission of the copyright holder that he may not redistribute the source code of any software that accompanies the software that uses the software, which is the software that uses the software.",
                                        "type": "OBLIGATION"
                                    }
                                ]
                            }
                        ]
                    },
                    "description": "The source code is redistributed under reasonable conditions. â Permission may be obtained from the copyright holder at support@svnkit.comã«é£çµ¡ãã."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "TMate Open Source License"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "https://svnkit.com/license.html"
                        ]
                    ]
                ],
                "__impliedText": "The TMate Open Source License.\r\n\r\nThis license applies to all portions of TMate SVNKit library, which \r\nare not externally-maintained libraries (e.g. Ganymed SSH library).\r\n\r\nAll the source code and compiled classes in package org.tigris.subversion.javahl\r\nexcept SvnClient class are covered by the license in JAVAHL-LICENSE file\r\n\r\nCopyright (c) 2004-2012 TMate Software. All rights reserved.\r\n\r\nRedistribution and use in source and binary forms, with or without modification, \r\nare permitted provided that the following conditions are met:\r\n\r\n    * Redistributions of source code must retain the above copyright notice, \r\n      this list of conditions and the following disclaimer.\r\n      \r\n    * Redistributions in binary form must reproduce the above copyright notice, \r\n      this list of conditions and the following disclaimer in the documentation \r\n      and/or other materials provided with the distribution.\r\n      \r\n    * Redistributions in any form must be accompanied by information on how to \r\n      obtain complete source code for the software that uses SVNKit and any \r\n      accompanying software that uses the software that uses SVNKit. The source \r\n      code must either be included in the distribution or be available for no \r\n      more than the cost of distribution plus a nominal fee, and must be freely \r\n      redistributable under reasonable conditions. For an executable file, complete \r\n      source code means the source code for all modules it contains. It does not \r\n      include source code for modules or files that typically accompany the major \r\n      components of the operating system on which the executable file runs.\r\n      \r\n    * Redistribution in any form without redistributing source code for software \r\n      that uses SVNKit is possible only when such redistribution is explictly permitted \r\n      by TMate Software. Please, contact TMate Software at support@svnkit.com to \r\n      get such permission.\r\n\r\nTHIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED\r\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF \r\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE \r\nDISCLAIMED. \r\n\r\nIN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, \r\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT \r\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \r\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF \r\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \r\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF \r\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/972"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "Copyleft"
        ]
    ],
    "__calculatedCopyleft": "Copyleft",
    "__isOsiApproved": false,
    "__impliedText": "This license applies to all portions of TMate SVNKit library, which \nare not externally-maintained libraries (e.g. Ganymed SSH library).\n\nAll the source code and compiled classes in package org.tigris.subversion.javahl\nexcept SvnClient class are covered by the license in JAVAHL-LICENSE file\n\nCopyright (c) 2004-2009 TMate Software. All rights reserved.\n\nRedistribution and use in source and binary forms, with or without modification, \nare permitted provided that the following conditions are met:\n\n    * Redistributions of source code must retain the above copyright notice, \n      this list of conditions and the following disclaimer.\n      \n    * Redistributions in binary form must reproduce the above copyright notice, \n      this list of conditions and the following disclaimer in the documentation \n      and/or other materials provided with the distribution.\n      \n    * Redistributions in any form must be accompanied by information on how to \n      obtain complete source code for the software that uses SVNKit and any \n      accompanying software that uses the software that uses SVNKit. The source \n      code must either be included in the distribution or be available for no \n      more than the cost of distribution plus a nominal fee, and must be freely \n      redistributable under reasonable conditions. For an executable file, complete \n      source code means the source code for all modules it contains. It does not \n      include source code for modules or files that typically accompany the major \n      components of the operating system on which the executable file runs.\n      \n    * Redistribution in any form without redistributing source code for software \n      that uses SVNKit is possible only when such redistribution is explictly permitted \n      by TMate Software. Please, contact TMate Software at support@svnkit.com to \n      get such permission.\n\nTHIS SOFTWARE IS PROVIDED BY TMATE SOFTWARE ``AS IS'' AND ANY EXPRESS OR IMPLIED\nWARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF \nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT, ARE \nDISCLAIMED. \n\nIN NO EVENT SHALL TMATE SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT, \nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT \nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF \nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE \nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF \nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/TMate.json"
        ],
        [
            null,
            "http://svnkit.com/license.html"
        ],
        [
            "Homepage",
            "http://svnkit.com/licensing.html"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/972"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/1391"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/TMate.svg