== Technische Universitaet Berlin License 2.0 (TU-Berlin-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Technische Universitaet Berlin License 2.0
|Shortname |TU-Berlin-2.0
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

=== Comments on (easy) usability

* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

=== URLs

* *SPDX:* https://spdx.org/licenses/TU-Berlin-2.0.html
* *SPDX:* http://spdx.org/licenses/TU-Berlin-2.0.json
* https://github.com/CorsixTH/deps/blob/fd339a9f526d1d9c9f01ccf39e438a015da50035/licences/libgsm.txt

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://spdx.org/licenses/TU-Berlin-2.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "TU-Berlin-2.0",
        "Technische Universitaet Berlin License 2.0"
    ],
    "__impliedId": "TU-Berlin-2.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "TU-Berlin-2.0"
                ],
                "__impliedId": "TU-Berlin-2.0"
            },
            "shortname": "TU-Berlin-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Technische Universitaet Berlin License 2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/TU-Berlin-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/TU-Berlin-2.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://github.com/CorsixTH/deps/blob/fd339a9f526d1d9c9f01ccf39e438a015da50035/licences/libgsm.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "TU-Berlin-2.0",
                    "Technische Universitaet Berlin License 2.0"
                ],
                "__impliedId": "TU-Berlin-2.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/TU-Berlin-2.0.json"
                    ],
                    [
                        null,
                        "https://github.com/CorsixTH/deps/blob/fd339a9f526d1d9c9f01ccf39e438a015da50035/licences/libgsm.txt"
                    ]
                ]
            },
            "spdxLicenseId": "TU-Berlin-2.0"
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/TU-Berlin-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Technische Universitaet Berlin License 2.0",
            "id": "TU-Berlin-2.0",
            "_implications": {
                "__impliedNames": [
                    "TU-Berlin-2.0",
                    "Technische Universitaet Berlin License 2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/TU-Berlin-2.0.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/TU-Berlin-2.0.html"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/TU-Berlin-2.0.json"
        ],
        [
            null,
            "https://github.com/CorsixTH/deps/blob/fd339a9f526d1d9c9f01ccf39e438a015da50035/licences/libgsm.txt"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/TU-Berlin-2.0.svg
