== Unicode Terms of Use (Unicode-TOU)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Unicode Terms of Use
|Shortname |Unicode-TOU
|Rating |Unknown, probably Attention or Stop or No-Go
|===

*Other Names:*

* `scancode://unicode-tou`

=== Comments on (easy) usability

=== General Comments

* ``EXHIBIT 1 of UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND
SOFTWARE is registered separately.
https://factbook.soft.hitachi.co.jp/production/db/legl_licenses/ 314''
(source: https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:* http://www.unicode.org/copyright.html
* *SPDX:* http://spdx.org/licenses/Unicode-TOU.json
* *open-license:* http://open-license.hitachi.com/licenses/313

=== Description from open-license

(source: Hitachi open-license)

=== Text

....
Unicode Terms of Use

For the general privacy policy governing access to this site, see the
Unicode Privacy Policy. For trademark usage, see the Unicode® Consortium
Name and Trademark Usage Policy.

A. Unicode Copyright.

1. Copyright ©  Unicode, Inc. All rights reserved.

2. Certain documents and files on this website contain a legend
indicating that "Modification is permitted." Any person is hereby
authorized, without fee, to modify such documents and files to create
derivative works conforming to the Unicode® Standard, subject to Terms
and Conditions herein.

3. Any person is hereby authorized, without fee, to view, use,
reproduce, and distribute all documents and files solely for
informational purposes in the creation of products supporting the
Unicode Standard, subject to the Terms and Conditions herein.

4. Further specifications of rights and restrictions pertaining to the
use of the particular set of data files known as the "Unicode Character
Database" can be found in Exhibit 1.

5. Each version of the Unicode Standard has further specifications of
rights and restrictions of use. For the book editions (Unicode 5.0 and
earlier), these are found on the back of the title page. The online code
charts carry specific restrictions. All other files, including online
documentation of the core specification for Unicode 6.0 and later, are
covered under these general Terms of Use.

6. No license is granted to "mirror" the Unicode website where a fee is
charged for access to the "mirror" site.

7. Modification is not permitted with respect to this document. All
copies of this document must be verbatim.

B. Restricted Rights Legend. Any technical data or software which is
licensed to the United States of America, its agencies and/or
instrumentalities under this Agreement is commercial technical data or
commercial computer software developed exclusively at private expense as
defined in FAR 2.101, or DFARS 252.227-7014 (June 1995), as applicable.
For technical data, use, duplication, or disclosure by the Government is
subject to restrictions as set forth in DFARS 202.227-7015 Technical
Data, Commercial and Items (Nov 1995) and this Agreement. For Software,
in accordance with FAR 12-212 or DFARS 227-7202, as applicable, use,
duplication or disclosure by the Government is subject to the
restrictions set forth in this Agreement.

C. Warranties and Disclaimers.

1. This publication and/or website may include technical or
typographical errors or other inaccuracies . Changes are periodically
added to the information herein; these changes will be incorporated in
new editions of the publication and/or website. Unicode may make
improvements and/or changes in the product(s) and/or program(s)
described in this publication and/or website at any time.

2. If this file has been purchased on magnetic or optical media from
Unicode, Inc. the sole and exclusive remedy for any claim will be
exchange of the defective media within ninety (90) days of original
purchase.

3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE
IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS,
IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
UNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR
OMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH
ARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.

D. Waiver of Damages. In no event shall Unicode or its licensors be
liable for any special, incidental, indirect or consequential damages of
any kind, or any damages whatsoever, whether or not Unicode was advised
of the possibility of the damage, including, without limitation, those
resulting from the following: loss of use, data or profits, in
connection with the use, modification or distribution of this
information or its derivatives.

E. Trademarks & Logos.

1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,
Inc. "The Unicode Consortium" and "Unicode, Inc." are trade names of
Unicode, Inc. Use of the information and materials found on this website
indicates your acknowledgement of Unicode, Inc.’s exclusive worldwide
rights in the Unicode Word Mark, the Unicode Logo, and the Unicode trade
names.

2. The Unicode Consortium Name and Trademark Usage Policy ("Trademark
Policy") are incorporated herein by reference and you agree to abide by
the provisions of the Trademark Policy, which may be changed from time
to time in the sole discretion of Unicode, Inc.

3. All third party trademarks referenced herein are the property of
their respective owners.

F. Miscellaneous.

1. Jurisdiction and Venue. This server is operated from a location in
the State of California, United States of America. Unicode makes no
representation that the materials are appropriate for use in other
locations. If you access this server from other locations, you are
responsible for compliance with local laws. This Agreement, all use of
this site and any claims and damages resulting from use of this site are
governed solely by the laws of the State of California without regard to
any principles which would apply the laws of a different jurisdiction.
The user agrees that any disputes regarding this site shall be resolved
solely in the courts located in Santa Clara County, California. The user
agrees said courts have personal jurisdiction and agree to waive any
right to transfer the dispute to any other forum.

2. Modification by Unicode Unicode shall have the right to modify this
Agreement at any time by posting it to this site. The user may not
assign any part of this Agreement without Unicode’s prior written
consent.

3. Taxes. The user agrees to pay any taxes arising from access to this
website or use of the information herein, except for those based on
Unicode’s net income.

4. Severability. If any provision of this Agreement is declared invalid
or unenforceable, the remaining provisions of this Agreement shall
remain in effect.

5. Entire Agreement. This Agreement constitutes the entire agreement
between the parties.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/Unicode-TOU.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-tou.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Unicode-TOU",
        "Unicode Terms of Use",
        "scancode://unicode-tou"
    ],
    "__impliedId": "Unicode-TOU",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "EXHIBIT 1 of UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE is registered separately. https://factbook.soft.hitachi.co.jp/production/db/legl_licenses/ 314"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Unicode-TOU"
                ],
                "__impliedId": "Unicode-TOU"
            },
            "shortname": "Unicode-TOU",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Unicode Terms of Use",
            "spdxDetailsURL": "http://spdx.org/licenses/Unicode-TOU.json",
            "_sourceURL": "https://spdx.org/licenses/Unicode-TOU.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.unicode.org/copyright.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Unicode-TOU",
                    "Unicode Terms of Use"
                ],
                "__impliedId": "Unicode-TOU",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Unicode-TOU.json"
                    ],
                    [
                        null,
                        "http://www.unicode.org/copyright.html"
                    ]
                ]
            },
            "spdxLicenseId": "Unicode-TOU"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "http://www.unicode.org/copyright.html",
            "shortName": "Unicode Terms of Use",
            "textUrls": null,
            "text": "Unicode Terms of Use\n\nFor the general privacy policy governing access to this site, see the\nUnicode Privacy Policy. For trademark usage, see the UnicodeÂ® Consortium\nName and Trademark Usage Policy.\n\nA. Unicode Copyright.\n\n1. Copyright Â©  Unicode, Inc. All rights reserved.\n\n2. Certain documents and files on this website contain a legend\nindicating that \"Modification is permitted.\" Any person is hereby\nauthorized, without fee, to modify such documents and files to create\nderivative works conforming to the UnicodeÂ® Standard, subject to Terms\nand Conditions herein.\n\n3. Any person is hereby authorized, without fee, to view, use,\nreproduce, and distribute all documents and files solely for\ninformational purposes in the creation of products supporting the\nUnicode Standard, subject to the Terms and Conditions herein.\n\n4. Further specifications of rights and restrictions pertaining to the\nuse of the particular set of data files known as the \"Unicode Character\nDatabase\" can be found in Exhibit 1.\n\n5. Each version of the Unicode Standard has further specifications of\nrights and restrictions of use. For the book editions (Unicode 5.0 and\nearlier), these are found on the back of the title page. The online code\ncharts carry specific restrictions. All other files, including online\ndocumentation of the core specification for Unicode 6.0 and later, are\ncovered under these general Terms of Use.\n\n6. No license is granted to \"mirror\" the Unicode website where a fee is\ncharged for access to the \"mirror\" site.\n\n7. Modification is not permitted with respect to this document. All\ncopies of this document must be verbatim.\n\nB. Restricted Rights Legend. Any technical data or software which is\nlicensed to the United States of America, its agencies and/or\ninstrumentalities under this Agreement is commercial technical data or\ncommercial computer software developed exclusively at private expense as\ndefined in FAR 2.101, or DFARS 252.227-7014 (June 1995), as applicable.\nFor technical data, use, duplication, or disclosure by the Government is\nsubject to restrictions as set forth in DFARS 202.227-7015 Technical\nData, Commercial and Items (Nov 1995) and this Agreement. For Software,\nin accordance with FAR 12-212 or DFARS 227-7202, as applicable, use,\nduplication or disclosure by the Government is subject to the\nrestrictions set forth in this Agreement.\n\nC. Warranties and Disclaimers.\n\n1. This publication and/or website may include technical or\ntypographical errors or other inaccuracies . Changes are periodically\nadded to the information herein; these changes will be incorporated in\nnew editions of the publication and/or website. Unicode may make\nimprovements and/or changes in the product(s) and/or program(s)\ndescribed in this publication and/or website at any time.\n\n2. If this file has been purchased on magnetic or optical media from\nUnicode, Inc. the sole and exclusive remedy for any claim will be\nexchange of the defective media within ninety (90) days of original\npurchase.\n\n3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE\nIS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS,\nIMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.\nUNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR\nOMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH\nARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.\n\nD. Waiver of Damages. In no event shall Unicode or its licensors be\nliable for any special, incidental, indirect or consequential damages of\nany kind, or any damages whatsoever, whether or not Unicode was advised\nof the possibility of the damage, including, without limitation, those\nresulting from the following: loss of use, data or profits, in\nconnection with the use, modification or distribution of this\ninformation or its derivatives.\n\nE. Trademarks & Logos.\n\n1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,\nInc. \"The Unicode Consortium\" and \"Unicode, Inc.\" are trade names of\nUnicode, Inc. Use of the information and materials found on this website\nindicates your acknowledgement of Unicode, Inc.âs exclusive worldwide\nrights in the Unicode Word Mark, the Unicode Logo, and the Unicode trade\nnames.\n\n2. The Unicode Consortium Name and Trademark Usage Policy (\"Trademark\nPolicy\") are incorporated herein by reference and you agree to abide by\nthe provisions of the Trademark Policy, which may be changed from time\nto time in the sole discretion of Unicode, Inc.\n\n3. All third party trademarks referenced herein are the property of\ntheir respective owners.\n\nF. Miscellaneous.\n\n1. Jurisdiction and Venue. This server is operated from a location in\nthe State of California, United States of America. Unicode makes no\nrepresentation that the materials are appropriate for use in other\nlocations. If you access this server from other locations, you are\nresponsible for compliance with local laws. This Agreement, all use of\nthis site and any claims and damages resulting from use of this site are\ngoverned solely by the laws of the State of California without regard to\nany principles which would apply the laws of a different jurisdiction.\nThe user agrees that any disputes regarding this site shall be resolved\nsolely in the courts located in Santa Clara County, California. The user\nagrees said courts have personal jurisdiction and agree to waive any\nright to transfer the dispute to any other forum.\n\n2. Modification by Unicode Unicode shall have the right to modify this\nAgreement at any time by posting it to this site. The user may not\nassign any part of this Agreement without Unicodeâs prior written\nconsent.\n\n3. Taxes. The user agrees to pay any taxes arising from access to this\nwebsite or use of the information herein, except for those based on\nUnicodeâs net income.\n\n4. Severability. If any provision of this Agreement is declared invalid\nor unenforceable, the remaining provisions of this Agreement shall\nremain in effect.\n\n5. Entire Agreement. This Agreement constitutes the entire agreement\nbetween the parties.",
            "category": "Proprietary Free",
            "osiUrl": null,
            "owner": "Unicode Consortium",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-tou.yml",
            "key": "unicode-tou",
            "name": "Unicode Terms of Use",
            "spdxId": "Unicode-TOU",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://unicode-tou",
                    "Unicode Terms of Use",
                    "Unicode-TOU"
                ],
                "__impliedId": "Unicode-TOU",
                "__impliedText": "Unicode Terms of Use\n\nFor the general privacy policy governing access to this site, see the\nUnicode Privacy Policy. For trademark usage, see the Unicode® Consortium\nName and Trademark Usage Policy.\n\nA. Unicode Copyright.\n\n1. Copyright ©  Unicode, Inc. All rights reserved.\n\n2. Certain documents and files on this website contain a legend\nindicating that \"Modification is permitted.\" Any person is hereby\nauthorized, without fee, to modify such documents and files to create\nderivative works conforming to the Unicode® Standard, subject to Terms\nand Conditions herein.\n\n3. Any person is hereby authorized, without fee, to view, use,\nreproduce, and distribute all documents and files solely for\ninformational purposes in the creation of products supporting the\nUnicode Standard, subject to the Terms and Conditions herein.\n\n4. Further specifications of rights and restrictions pertaining to the\nuse of the particular set of data files known as the \"Unicode Character\nDatabase\" can be found in Exhibit 1.\n\n5. Each version of the Unicode Standard has further specifications of\nrights and restrictions of use. For the book editions (Unicode 5.0 and\nearlier), these are found on the back of the title page. The online code\ncharts carry specific restrictions. All other files, including online\ndocumentation of the core specification for Unicode 6.0 and later, are\ncovered under these general Terms of Use.\n\n6. No license is granted to \"mirror\" the Unicode website where a fee is\ncharged for access to the \"mirror\" site.\n\n7. Modification is not permitted with respect to this document. All\ncopies of this document must be verbatim.\n\nB. Restricted Rights Legend. Any technical data or software which is\nlicensed to the United States of America, its agencies and/or\ninstrumentalities under this Agreement is commercial technical data or\ncommercial computer software developed exclusively at private expense as\ndefined in FAR 2.101, or DFARS 252.227-7014 (June 1995), as applicable.\nFor technical data, use, duplication, or disclosure by the Government is\nsubject to restrictions as set forth in DFARS 202.227-7015 Technical\nData, Commercial and Items (Nov 1995) and this Agreement. For Software,\nin accordance with FAR 12-212 or DFARS 227-7202, as applicable, use,\nduplication or disclosure by the Government is subject to the\nrestrictions set forth in this Agreement.\n\nC. Warranties and Disclaimers.\n\n1. This publication and/or website may include technical or\ntypographical errors or other inaccuracies . Changes are periodically\nadded to the information herein; these changes will be incorporated in\nnew editions of the publication and/or website. Unicode may make\nimprovements and/or changes in the product(s) and/or program(s)\ndescribed in this publication and/or website at any time.\n\n2. If this file has been purchased on magnetic or optical media from\nUnicode, Inc. the sole and exclusive remedy for any claim will be\nexchange of the defective media within ninety (90) days of original\npurchase.\n\n3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE\nIS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS,\nIMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.\nUNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR\nOMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH\nARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.\n\nD. Waiver of Damages. In no event shall Unicode or its licensors be\nliable for any special, incidental, indirect or consequential damages of\nany kind, or any damages whatsoever, whether or not Unicode was advised\nof the possibility of the damage, including, without limitation, those\nresulting from the following: loss of use, data or profits, in\nconnection with the use, modification or distribution of this\ninformation or its derivatives.\n\nE. Trademarks & Logos.\n\n1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,\nInc. \"The Unicode Consortium\" and \"Unicode, Inc.\" are trade names of\nUnicode, Inc. Use of the information and materials found on this website\nindicates your acknowledgement of Unicode, Inc.’s exclusive worldwide\nrights in the Unicode Word Mark, the Unicode Logo, and the Unicode trade\nnames.\n\n2. The Unicode Consortium Name and Trademark Usage Policy (\"Trademark\nPolicy\") are incorporated herein by reference and you agree to abide by\nthe provisions of the Trademark Policy, which may be changed from time\nto time in the sole discretion of Unicode, Inc.\n\n3. All third party trademarks referenced herein are the property of\ntheir respective owners.\n\nF. Miscellaneous.\n\n1. Jurisdiction and Venue. This server is operated from a location in\nthe State of California, United States of America. Unicode makes no\nrepresentation that the materials are appropriate for use in other\nlocations. If you access this server from other locations, you are\nresponsible for compliance with local laws. This Agreement, all use of\nthis site and any claims and damages resulting from use of this site are\ngoverned solely by the laws of the State of California without regard to\nany principles which would apply the laws of a different jurisdiction.\nThe user agrees that any disputes regarding this site shall be resolved\nsolely in the courts located in Santa Clara County, California. The user\nagrees said courts have personal jurisdiction and agree to waive any\nright to transfer the dispute to any other forum.\n\n2. Modification by Unicode Unicode shall have the right to modify this\nAgreement at any time by posting it to this site. The user may not\nassign any part of this Agreement without Unicode’s prior written\nconsent.\n\n3. Taxes. The user agrees to pay any taxes arising from access to this\nwebsite or use of the information herein, except for those based on\nUnicode’s net income.\n\n4. Severability. If any provision of this Agreement is declared invalid\nor unenforceable, the remaining provisions of this Agreement shall\nremain in effect.\n\n5. Entire Agreement. This Agreement constitutes the entire agreement\nbetween the parties.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.unicode.org/copyright.html"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "EXHIBIT 1 of UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE is registered separately. https://factbook.soft.hitachi.co.jp/production/db/legl_licenses/ 314",
            "notices": [],
            "_sourceURL": "http://open-license.hitachi.com/licenses/313",
            "content": "Unicode Terms of Use\n\nFor the general privacy policy governing access to this site, see the Unicode\nPrivacy Policy. For trademark usage, see the Unicode® Consortium Name and\nTrademark Usage Policy.\n\nA. Unicode Copyright.\n   1. Copyright © 1991-<year> Unicode, Inc. All rights reserved.\n\n   2. Certain documents and files on this website contain a legend indicating\n      that \"Modification is permitted.\" Any person is hereby authorized,\n      without fee, to modify such documents and files to create derivative\n      works conforming to the Unicode® Standard, subject to Terms and\n      Conditions herein.\n\n    3. Any person is hereby authorized, without fee, to view, use, reproduce,\n       and distribute all documents and files solely for informational\n       purposes in the creation of products supporting the Unicode Standard,\n       subject to the Terms and Conditions herein.\n\n    4. Further specifications of rights and restrictions pertaining to the use\n       of the particular set of data files known as the \"Unicode Character\n       Database\" can be found in Exhibit 1.\n\n    5. Each version of the Unicode Standard has further specifications of\n       rights and restrictions of use. For the book editions (Unicode 5.0 and\n       earlier), these are found on the back of the title page. The online\n       code charts carry specific restrictions. All other files, including\n       online documentation of the core specification for Unicode 6.0 and\n       later, are covered under these general Terms of Use.\n\n    6. No license is granted to \"mirror\" the Unicode website where a fee is\n       charged for access to the \"mirror\" site.\n\n    7. Modification is not permitted with respect to this document. All copies\n       of this document must be verbatim.\n\nB. Restricted Rights Legend. Any technical data or software which is licensed\n   to the United States of America, its agencies and/or instrumentalities\n   under this Agreement is commercial technical data or commercial computer\n   software developed exclusively at private expense as defined in FAR 2.101,\n   or DFARS 252.227-7014 (June 1995), as applicable. For technical data, use,\n   duplication, or disclosure by the Government is subject to restrictions as\n   set forth in DFARS 202.227-7015 Technical Data, Commercial and Items (Nov\n   1995) and this Agreement. For Software, in accordance with FAR 12-212 or\n   DFARS 227-7202, as applicable, use, duplication or disclosure by the\n   Government is subject to the restrictions set forth in this Agreement.\n\nC. Warranties and Disclaimers.\n   1. This publication and/or website may include technical or typographical\n      errors or other inaccuracies . Changes are periodically added to the\n      information herein; these changes will be incorporated in new editions\n      of the publication and/or website. Unicode may make improvements and/or\n      changes in the product(s) and/or program(s) described in this\n      publication and/or website at any time.\n\n    2. If this file has been purchased on magnetic or optical media from\n       Unicode, Inc. the sole and exclusive remedy for any claim will be\n       exchange of the defective media within ninety (90) days of original\n       purchase.\n\n    3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE IS\n       PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS, IMPLIED,\n       OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF\n       MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.\n       UNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR\n       OMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH\n       ARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.\n\nD. Waiver of Damages. In no event shall Unicode or its licensors be liable for\n   any special, incidental, indirect or consequential damages of any kind, or\n   any damages whatsoever, whether or not Unicode was advised of the\n   possibility of the damage, including, without limitation, those resulting\n   from the following: loss of use, data or profits, in connection with the\n   use, modification or distribution of this information or its derivatives.\n\nE.Trademarks & Logos.\n   1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,\n      Inc.  “The Unicode Consortium” and “Unicode, Inc.” are trade names of\n      Unicode, Inc.  Use of the information and materials found on this\n      website indicates your acknowledgement of Unicode, Inc.’s exclusive\n      worldwide rights in the Unicode Word Mark, the Unicode Logo, and the\n      Unicode trade names.\n\n   2. The Unicode Consortium Name and Trademark Usage Policy (“Trademark\n      Policy”) are incorporated herein by reference and you agree to abide by\n      the provisions of the Trademark Policy, which may be changed from time\n      to time in the sole discretion of Unicode, Inc.\n\n   3. All third party trademarks referenced herein are the property of their\n      respective owners.\n\nMiscellaneous.\n   1. Jurisdiction and Venue. This server is operated from a location in the\n      State of California, United States of America. Unicode makes no\n      representation that the materials are appropriate for use in other\n      locations. If you access this server from other locations, you are\n      responsible for compliance with local laws. This Agreement, all use of\n      this site and any claims and damages resulting from use of this site are\n      governed solely by the laws of the State of California without regard to\n      any principles which would apply the laws of a different jurisdiction.\n      The user agrees that any disputes regarding this site shall be resolved\n      solely in the courts located in Santa Clara County, California. The user\n      agrees said courts have personal jurisdiction and agree to waive any\n      right to transfer the dispute to any other forum.\n\n   2. Modification by Unicode.  Unicode shall have the right to modify this\n      Agreement at any time by posting it to this site. The user may not\n      assign any part of this Agreement without Unicode’s prior written\n      consent.\n\n   3. Taxes. The user agrees to pay any taxes arising from access to this\n      website or use of the information herein, except for those based on\n      Unicode’s net income.\n\n   4. Severability.  If any provision of this Agreement is declared invalid or\n      unenforceable, the remaining provisions of this Agreement shall remain\n      in effect.\n\n   5. Entire Agreement. This Agreement constitutes the entire agreement\n      between the parties.\n\nEXHIBIT 1\nUNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/, and\nhttp://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF\nonline code charts under the directory http://www.unicode.org/Public/.\nSoftware includes any source code published in the Unicode Standard or under\nthe directories http://www.unicode.org/Public/,\nhttp://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.\n\nNOTICE TO USER: Carefully read the following legal agreement. BY DOWNLOADING,\nINSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA FILES (\"DATA\nFILES\"), AND/OR SOFTWARE (\"SOFTWARE\"), YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO\nBE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT\nAGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR\nSOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-<year> Unicode, Inc. All rights reserved. Distributed under the\nTerms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof the Unicode data files and any associated documentation (the \"Data Files\")\nor Unicode software and any associated documentation (the \"Software\") to deal\nin the Data Files or Software without restriction, including without\nlimitation the rights to use, copy, modify, merge, publish, distribute, and/or\nsell copies of the Data Files or Software, and to permit persons to whom the\nData Files or Software are furnished to do so, provided that (a) the above\ncopyright notice(s) and this permission notice appear with all copies of the\nData Files or Software, (b) both the above copyright notice(s) and this\npermission notice appear in associated documentation, and (c) there is clear\nnotice in each modified Data File or in the Software as well as in the\ndocumentation associated with the Data File(s) or Software that the data or\nsoftware has been modified.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY\nKIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD\nPARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN\nTHIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL\nDAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR\nPROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS\nACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE\nDATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall not\nbe used in advertising or otherwise to promote the sale, use or other dealings\nin these Data Files or Software without prior written authorization of the\ncopyright holder.\n\nUnicode and the Unicode logo are trademarks of Unicode, Inc. in the United\nStates and other countries. All third party trademarks referenced herein are\nthe property of their respective owners.",
            "name": "Unicode Terms of Use",
            "permissions": [],
            "_implications": {
                "__impliedNames": [
                    "Unicode Terms of Use"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "EXHIBIT 1 of UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE is registered separately. https://factbook.soft.hitachi.co.jp/production/db/legl_licenses/ 314"
                        ]
                    ]
                ],
                "__impliedText": "Unicode Terms of Use\n\nFor the general privacy policy governing access to this site, see the Unicode\nPrivacy Policy. For trademark usage, see the Unicode® Consortium Name and\nTrademark Usage Policy.\n\nA. Unicode Copyright.\n   1. Copyright © 1991-<year> Unicode, Inc. All rights reserved.\n\n   2. Certain documents and files on this website contain a legend indicating\n      that \"Modification is permitted.\" Any person is hereby authorized,\n      without fee, to modify such documents and files to create derivative\n      works conforming to the Unicode® Standard, subject to Terms and\n      Conditions herein.\n\n    3. Any person is hereby authorized, without fee, to view, use, reproduce,\n       and distribute all documents and files solely for informational\n       purposes in the creation of products supporting the Unicode Standard,\n       subject to the Terms and Conditions herein.\n\n    4. Further specifications of rights and restrictions pertaining to the use\n       of the particular set of data files known as the \"Unicode Character\n       Database\" can be found in Exhibit 1.\n\n    5. Each version of the Unicode Standard has further specifications of\n       rights and restrictions of use. For the book editions (Unicode 5.0 and\n       earlier), these are found on the back of the title page. The online\n       code charts carry specific restrictions. All other files, including\n       online documentation of the core specification for Unicode 6.0 and\n       later, are covered under these general Terms of Use.\n\n    6. No license is granted to \"mirror\" the Unicode website where a fee is\n       charged for access to the \"mirror\" site.\n\n    7. Modification is not permitted with respect to this document. All copies\n       of this document must be verbatim.\n\nB. Restricted Rights Legend. Any technical data or software which is licensed\n   to the United States of America, its agencies and/or instrumentalities\n   under this Agreement is commercial technical data or commercial computer\n   software developed exclusively at private expense as defined in FAR 2.101,\n   or DFARS 252.227-7014 (June 1995), as applicable. For technical data, use,\n   duplication, or disclosure by the Government is subject to restrictions as\n   set forth in DFARS 202.227-7015 Technical Data, Commercial and Items (Nov\n   1995) and this Agreement. For Software, in accordance with FAR 12-212 or\n   DFARS 227-7202, as applicable, use, duplication or disclosure by the\n   Government is subject to the restrictions set forth in this Agreement.\n\nC. Warranties and Disclaimers.\n   1. This publication and/or website may include technical or typographical\n      errors or other inaccuracies . Changes are periodically added to the\n      information herein; these changes will be incorporated in new editions\n      of the publication and/or website. Unicode may make improvements and/or\n      changes in the product(s) and/or program(s) described in this\n      publication and/or website at any time.\n\n    2. If this file has been purchased on magnetic or optical media from\n       Unicode, Inc. the sole and exclusive remedy for any claim will be\n       exchange of the defective media within ninety (90) days of original\n       purchase.\n\n    3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE IS\n       PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS, IMPLIED,\n       OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF\n       MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.\n       UNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR\n       OMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH\n       ARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.\n\nD. Waiver of Damages. In no event shall Unicode or its licensors be liable for\n   any special, incidental, indirect or consequential damages of any kind, or\n   any damages whatsoever, whether or not Unicode was advised of the\n   possibility of the damage, including, without limitation, those resulting\n   from the following: loss of use, data or profits, in connection with the\n   use, modification or distribution of this information or its derivatives.\n\nE.Trademarks & Logos.\n   1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,\n      Inc.  “The Unicode Consortium” and “Unicode, Inc.” are trade names of\n      Unicode, Inc.  Use of the information and materials found on this\n      website indicates your acknowledgement of Unicode, Inc.’s exclusive\n      worldwide rights in the Unicode Word Mark, the Unicode Logo, and the\n      Unicode trade names.\n\n   2. The Unicode Consortium Name and Trademark Usage Policy (“Trademark\n      Policy”) are incorporated herein by reference and you agree to abide by\n      the provisions of the Trademark Policy, which may be changed from time\n      to time in the sole discretion of Unicode, Inc.\n\n   3. All third party trademarks referenced herein are the property of their\n      respective owners.\n\nMiscellaneous.\n   1. Jurisdiction and Venue. This server is operated from a location in the\n      State of California, United States of America. Unicode makes no\n      representation that the materials are appropriate for use in other\n      locations. If you access this server from other locations, you are\n      responsible for compliance with local laws. This Agreement, all use of\n      this site and any claims and damages resulting from use of this site are\n      governed solely by the laws of the State of California without regard to\n      any principles which would apply the laws of a different jurisdiction.\n      The user agrees that any disputes regarding this site shall be resolved\n      solely in the courts located in Santa Clara County, California. The user\n      agrees said courts have personal jurisdiction and agree to waive any\n      right to transfer the dispute to any other forum.\n\n   2. Modification by Unicode.  Unicode shall have the right to modify this\n      Agreement at any time by posting it to this site. The user may not\n      assign any part of this Agreement without Unicode’s prior written\n      consent.\n\n   3. Taxes. The user agrees to pay any taxes arising from access to this\n      website or use of the information herein, except for those based on\n      Unicode’s net income.\n\n   4. Severability.  If any provision of this Agreement is declared invalid or\n      unenforceable, the remaining provisions of this Agreement shall remain\n      in effect.\n\n   5. Entire Agreement. This Agreement constitutes the entire agreement\n      between the parties.\n\nEXHIBIT 1\nUNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/, and\nhttp://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF\nonline code charts under the directory http://www.unicode.org/Public/.\nSoftware includes any source code published in the Unicode Standard or under\nthe directories http://www.unicode.org/Public/,\nhttp://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.\n\nNOTICE TO USER: Carefully read the following legal agreement. BY DOWNLOADING,\nINSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA FILES (\"DATA\nFILES\"), AND/OR SOFTWARE (\"SOFTWARE\"), YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO\nBE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT\nAGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR\nSOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-<year> Unicode, Inc. All rights reserved. Distributed under the\nTerms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof the Unicode data files and any associated documentation (the \"Data Files\")\nor Unicode software and any associated documentation (the \"Software\") to deal\nin the Data Files or Software without restriction, including without\nlimitation the rights to use, copy, modify, merge, publish, distribute, and/or\nsell copies of the Data Files or Software, and to permit persons to whom the\nData Files or Software are furnished to do so, provided that (a) the above\ncopyright notice(s) and this permission notice appear with all copies of the\nData Files or Software, (b) both the above copyright notice(s) and this\npermission notice appear in associated documentation, and (c) there is clear\nnotice in each modified Data File or in the Software as well as in the\ndocumentation associated with the Data File(s) or Software that the data or\nsoftware has been modified.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY\nKIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF THIRD\nPARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN\nTHIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL\nDAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR\nPROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS\nACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE\nDATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall not\nbe used in advertising or otherwise to promote the sale, use or other dealings\nin these Data Files or Software without prior written authorization of the\ncopyright holder.\n\nUnicode and the Unicode logo are trademarks of Unicode, Inc. in the United\nStates and other countries. All third party trademarks referenced herein are\nthe property of their respective owners.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/313"
                    ]
                ]
            }
        }
    },
    "__isOsiApproved": false,
    "__impliedText": "Unicode Terms of Use\n\nFor the general privacy policy governing access to this site, see the\nUnicode Privacy Policy. For trademark usage, see the Unicode® Consortium\nName and Trademark Usage Policy.\n\nA. Unicode Copyright.\n\n1. Copyright ©  Unicode, Inc. All rights reserved.\n\n2. Certain documents and files on this website contain a legend\nindicating that \"Modification is permitted.\" Any person is hereby\nauthorized, without fee, to modify such documents and files to create\nderivative works conforming to the Unicode® Standard, subject to Terms\nand Conditions herein.\n\n3. Any person is hereby authorized, without fee, to view, use,\nreproduce, and distribute all documents and files solely for\ninformational purposes in the creation of products supporting the\nUnicode Standard, subject to the Terms and Conditions herein.\n\n4. Further specifications of rights and restrictions pertaining to the\nuse of the particular set of data files known as the \"Unicode Character\nDatabase\" can be found in Exhibit 1.\n\n5. Each version of the Unicode Standard has further specifications of\nrights and restrictions of use. For the book editions (Unicode 5.0 and\nearlier), these are found on the back of the title page. The online code\ncharts carry specific restrictions. All other files, including online\ndocumentation of the core specification for Unicode 6.0 and later, are\ncovered under these general Terms of Use.\n\n6. No license is granted to \"mirror\" the Unicode website where a fee is\ncharged for access to the \"mirror\" site.\n\n7. Modification is not permitted with respect to this document. All\ncopies of this document must be verbatim.\n\nB. Restricted Rights Legend. Any technical data or software which is\nlicensed to the United States of America, its agencies and/or\ninstrumentalities under this Agreement is commercial technical data or\ncommercial computer software developed exclusively at private expense as\ndefined in FAR 2.101, or DFARS 252.227-7014 (June 1995), as applicable.\nFor technical data, use, duplication, or disclosure by the Government is\nsubject to restrictions as set forth in DFARS 202.227-7015 Technical\nData, Commercial and Items (Nov 1995) and this Agreement. For Software,\nin accordance with FAR 12-212 or DFARS 227-7202, as applicable, use,\nduplication or disclosure by the Government is subject to the\nrestrictions set forth in this Agreement.\n\nC. Warranties and Disclaimers.\n\n1. This publication and/or website may include technical or\ntypographical errors or other inaccuracies . Changes are periodically\nadded to the information herein; these changes will be incorporated in\nnew editions of the publication and/or website. Unicode may make\nimprovements and/or changes in the product(s) and/or program(s)\ndescribed in this publication and/or website at any time.\n\n2. If this file has been purchased on magnetic or optical media from\nUnicode, Inc. the sole and exclusive remedy for any claim will be\nexchange of the defective media within ninety (90) days of original\npurchase.\n\n3. EXCEPT AS PROVIDED IN SECTION C.2, THIS PUBLICATION AND/OR SOFTWARE\nIS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS,\nIMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.\nUNICODE AND ITS LICENSORS ASSUME NO RESPONSIBILITY FOR ERRORS OR\nOMISSIONS IN THIS PUBLICATION AND/OR SOFTWARE OR OTHER DOCUMENTS WHICH\nARE REFERENCED BY OR LINKED TO THIS PUBLICATION OR THE UNICODE WEBSITE.\n\nD. Waiver of Damages. In no event shall Unicode or its licensors be\nliable for any special, incidental, indirect or consequential damages of\nany kind, or any damages whatsoever, whether or not Unicode was advised\nof the possibility of the damage, including, without limitation, those\nresulting from the following: loss of use, data or profits, in\nconnection with the use, modification or distribution of this\ninformation or its derivatives.\n\nE. Trademarks & Logos.\n\n1. The Unicode Word Mark and the Unicode Logo are trademarks of Unicode,\nInc. \"The Unicode Consortium\" and \"Unicode, Inc.\" are trade names of\nUnicode, Inc. Use of the information and materials found on this website\nindicates your acknowledgement of Unicode, Inc.’s exclusive worldwide\nrights in the Unicode Word Mark, the Unicode Logo, and the Unicode trade\nnames.\n\n2. The Unicode Consortium Name and Trademark Usage Policy (\"Trademark\nPolicy\") are incorporated herein by reference and you agree to abide by\nthe provisions of the Trademark Policy, which may be changed from time\nto time in the sole discretion of Unicode, Inc.\n\n3. All third party trademarks referenced herein are the property of\ntheir respective owners.\n\nF. Miscellaneous.\n\n1. Jurisdiction and Venue. This server is operated from a location in\nthe State of California, United States of America. Unicode makes no\nrepresentation that the materials are appropriate for use in other\nlocations. If you access this server from other locations, you are\nresponsible for compliance with local laws. This Agreement, all use of\nthis site and any claims and damages resulting from use of this site are\ngoverned solely by the laws of the State of California without regard to\nany principles which would apply the laws of a different jurisdiction.\nThe user agrees that any disputes regarding this site shall be resolved\nsolely in the courts located in Santa Clara County, California. The user\nagrees said courts have personal jurisdiction and agree to waive any\nright to transfer the dispute to any other forum.\n\n2. Modification by Unicode Unicode shall have the right to modify this\nAgreement at any time by posting it to this site. The user may not\nassign any part of this Agreement without Unicode’s prior written\nconsent.\n\n3. Taxes. The user agrees to pay any taxes arising from access to this\nwebsite or use of the information herein, except for those based on\nUnicode’s net income.\n\n4. Severability. If any provision of this Agreement is declared invalid\nor unenforceable, the remaining provisions of this Agreement shall\nremain in effect.\n\n5. Entire Agreement. This Agreement constitutes the entire agreement\nbetween the parties.",
    "__impliedURLs": [
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/313"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Unicode-TOU.json"
        ],
        [
            null,
            "http://www.unicode.org/copyright.html"
        ],
        [
            "Homepage",
            "http://www.unicode.org/copyright.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Unicode-TOU.svg
