== Unicode License Agreement - Data Files and Software (2015) (Unicode-DFS-2015)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Unicode License Agreement - Data Files and Software (2015)
|Shortname |Unicode-DFS-2015
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE (since 2016)`
* `scancode://unicode-dfs-2015`
* `Unicode DFS 2015`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``http://www.unicode.org/copyright.html#License'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``The Unicode Data Files are located in the following directories
[http://www.unicode.org/Public/, http://www.unicode.org/reports/,
http://www.unicode.org/cldr/data/, http All data files in
://source.icu-project.org/repos/icu/, and
http://www.unicode.org/utility/trac/browser/]. However, it excludes PDFs
of online code tables in the following directories:
[http://www.unicode.org/Public/]. The software is either the source code
published by the Unicode Standard, or it is available in the following
directories [http://www.unicode.org/Public/,
http://www.unicode.org/reports/,http://www.unicode It refers to the
source code in [.org/cldr/data/,
http://source.icu-project.org/repos/icu/, and
http://www.unicode.org/utility/trac/browser/].'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:*
https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html
* *SPDX:* https://spdx.org/licenses/Unicode-DFS-2015.html
* *SPDX:* http://spdx.org/licenses/Unicode-DFS-2015.json
* *open-license:* http://open-license.hitachi.com/licenses/976

=== Description from open-license

* {blank}
+
....
Description: Treat related documents in the same way as data files and software.
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved object code (Use the fetched code as it is.)
- Use the object code generated from the modified source code
- Use the retrieved executable (Use the obtained executable as is.)
- Use the executable generated from the modified source code
- To use the acquired data file without modification (Use the fetched data files as they are.)
- Modify the acquired data file.
- Using Modified Data Files

Conditions: None
....
* {blank}
+
....
Description: Related documents are treated in the same way as data files.
Actions:
- Distribute the acquired data files without modification (Distribute the acquired data files as they are)
- Distribution of modified data files
- Selling data files
- I'm going to present the modified data file.
- Sell altered data files.

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer contained in such data files.
....
* {blank}
+
....
Description: Related documentation should be treated in the same way as software.
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribute the obtained object code (Redistribute the code as it was obtained)
- Distribution of Modified Source Code
- Distribute the object code generated from the modified source code
- Selling Software
- Distribute the obtained executable (Redistribute the obtained executable as-is)
- Distribute the executable generated from the modified source code
- Publish the modified source code.
- Present the object code generated from the modified source code.
- Present the executable generated from the modified source code

Conditions:
OBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer contained in such software
....
* {blank}
+
....
Actions:
- Use the copyright holder's name in software promotions and advertisements
- Use the copyright holder's name in data file promotions and advertisements.

Conditions:
REQUISITE: Get special permission in writing.
....

(source: Hitachi open-license)

=== Text

....
UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE

Unicode Data Files include all data files under the directories
http://www.unicode.org/Public/, http://www.unicode.org/reports/, and
http://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF
online code charts under the directory http://www.unicode.org/Public/.
Software includes any source code published in the Unicode Standard or
under the directories http://www.unicode.org/Public/,
http://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA
FILES ("DATA FILES"), AND/OR SOFTWARE ("SOFTWARE"), YOU UNEQUIVOCALLY
ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF
THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY,
DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

COPYRIGHT AND PERMISSION NOTICE

Copyright © 1991-2015 Unicode, Inc. All rights reserved. Distributed
under the Terms of Use in http://www.unicode.org/copyright.html.

Permission is hereby granted, free of charge, to any person obtaining a
copy of the Unicode data files and any associated documentation (the
"Data Files") or Unicode software and any associated documentation (the
"Software") to deal in the Data Files or Software without restriction,
including without limitation the rights to use, copy, modify, merge,
publish, distribute, and/or sell copies of the Data Files or Software,
and to permit persons to whom the Data Files or Software are furnished
to do so, provided that

(a) this copyright and permission notice appear with all copies of
the Data Files or Software,

(b) this copyright and permission notice appear in associated
documentation, and

(c) there is clear notice in each modified Data File or in the
Software as well as in the documentation associated with the Data
File(s) or Software that the data or software has been modified.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF
ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR
ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER
RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or
other dealings in these Data Files or Software without prior written
authorization of the copyright holder.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/Unicode-DFS-2015.html[SPDX] (all data [in
this repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2015.yml[Scancode]
(CC0-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Unicode-DFS-2015",
        "Unicode License Agreement - Data Files and Software (2015)",
        "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE (since 2016)",
        "scancode://unicode-dfs-2015",
        "Unicode DFS 2015"
    ],
    "__impliedId": "Unicode-DFS-2015",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "http://www.unicode.org/copyright.html#License",
                "The Unicode Data Files are located in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/, http://www.unicode.org/cldr/data/, http All data files in ://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]. However, it excludes PDFs of online code tables in the following directories: [http://www.unicode.org/Public/]. The software is either the source code published by the Unicode Standard, or it is available in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/,http://www.unicode It refers to the source code in [.org/cldr/data/, http://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]."
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Unicode-DFS-2015"
                ],
                "__impliedId": "Unicode-DFS-2015"
            },
            "shortname": "Unicode-DFS-2015",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Unicode License Agreement - Data Files and Software (2015)",
            "spdxDetailsURL": "http://spdx.org/licenses/Unicode-DFS-2015.json",
            "_sourceURL": "https://spdx.org/licenses/Unicode-DFS-2015.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Unicode-DFS-2015",
                    "Unicode License Agreement - Data Files and Software (2015)"
                ],
                "__impliedId": "Unicode-DFS-2015",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Unicode-DFS-2015.json"
                    ],
                    [
                        null,
                        "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
                    ]
                ]
            },
            "spdxLicenseId": "Unicode-DFS-2015"
        },
        "Scancode": {
            "otherUrls": [
                "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
            ],
            "homepageUrl": "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html",
            "shortName": "Unicode DFS 2015",
            "textUrls": null,
            "text": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/, and\nhttp://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF\nonline code charts under the directory http://www.unicode.org/Public/.\nSoftware includes any source code published in the Unicode Standard or\nunder the directories http://www.unicode.org/Public/,\nhttp://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.\n\nNOTICE TO USER: Carefully read the following legal agreement. BY\nDOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA\nFILES (\"DATA FILES\"), AND/OR SOFTWARE (\"SOFTWARE\"), YOU UNEQUIVOCALLY\nACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF\nTHIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY,\nDISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright Â© 1991-2015 Unicode, Inc. All rights reserved. Distributed\nunder the Terms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining a\ncopy of the Unicode data files and any associated documentation (the\n\"Data Files\") or Unicode software and any associated documentation (the\n\"Software\") to deal in the Data Files or Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge,\npublish, distribute, and/or sell copies of the Data Files or Software,\nand to permit persons to whom the Data Files or Software are furnished\nto do so, provided that\n\n(a) this copyright and permission notice appear with all copies of\nthe Data Files or Software,\n\n(b) this copyright and permission notice appear in associated\ndocumentation, and\n\n(c) there is clear notice in each modified Data File or in the\nSoftware as well as in the documentation associated with the Data\nFile(s) or Software that the data or software has been modified.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT\nHOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR\nANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER\nRESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF\nCONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN\nCONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall\nnot be used in advertising or otherwise to promote the sale, use or\nother dealings in these Data Files or Software without prior written\nauthorization of the copyright holder.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Unicode Consortium",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/unicode-dfs-2015.yml",
            "key": "unicode-dfs-2015",
            "name": "Unicode License Agreement - Data Files and Software (2015)",
            "spdxId": "Unicode-DFS-2015",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://unicode-dfs-2015",
                    "Unicode DFS 2015",
                    "Unicode-DFS-2015"
                ],
                "__impliedId": "Unicode-DFS-2015",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/, and\nhttp://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF\nonline code charts under the directory http://www.unicode.org/Public/.\nSoftware includes any source code published in the Unicode Standard or\nunder the directories http://www.unicode.org/Public/,\nhttp://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.\n\nNOTICE TO USER: Carefully read the following legal agreement. BY\nDOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA\nFILES (\"DATA FILES\"), AND/OR SOFTWARE (\"SOFTWARE\"), YOU UNEQUIVOCALLY\nACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF\nTHIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY,\nDISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-2015 Unicode, Inc. All rights reserved. Distributed\nunder the Terms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining a\ncopy of the Unicode data files and any associated documentation (the\n\"Data Files\") or Unicode software and any associated documentation (the\n\"Software\") to deal in the Data Files or Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge,\npublish, distribute, and/or sell copies of the Data Files or Software,\nand to permit persons to whom the Data Files or Software are furnished\nto do so, provided that\n\n(a) this copyright and permission notice appear with all copies of\nthe Data Files or Software,\n\n(b) this copyright and permission notice appear in associated\ndocumentation, and\n\n(c) there is clear notice in each modified Data File or in the\nSoftware as well as in the documentation associated with the Data\nFile(s) or Software that the data or software has been modified.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT\nHOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR\nANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER\nRESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF\nCONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN\nCONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall\nnot be used in advertising or otherwise to promote the sale, use or\nother dealings in these Data Files or Software without prior written\nauthorization of the copyright holder.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
                    ],
                    [
                        null,
                        "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "http://www.unicode.org/copyright.html#License",
            "notices": [
                {
                    "content": "the data files and software and related documentation are provided \"as-is\" and without any warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose and non-infringement. The warranties include, but are not limited to, the warranties of commercial applicability, fitness for a particular purpose, and non-infringement.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "In no event shall the copyright holder be liable for any claim, special, indirect or consequential damages, and any damages resulting from loss of use, loss of data or loss of profits, whether in contract, negligence or other tort action, arising out of the use or performance of such data files, software and related documentation. No liability shall be assumed."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/976",
            "content": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/,\nhttp://www.unicode.org/cldr/data/, http://source.icu-project.org/repos/icu/, and\nhttp://www.unicode.org/utility/trac/browser/.\n\nUnicode Data Files do not include PDF online code charts under the\ndirectory http://www.unicode.org/Public/.\n\nSoftware includes any source code published in the Unicode Standard\nor under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/,\nhttp://www.unicode.org/cldr/data/, http://source.icu-project.org/repos/icu/, and\nhttp://www.unicode.org/utility/trac/browser/.\n\nNOTICE TO USER: Carefully read the following legal agreement.\nBY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S\nDATA FILES (\"DATA FILES\"), AND/OR SOFTWARE (\"SOFTWARE\"),\nYOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE\nTERMS AND CONDITIONS OF THIS AGREEMENT.\nIF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE\nTHE DATA FILES OR SOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-<year> Unicode, Inc. All rights reserved.\nDistributed under the Terms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of the Unicode data files and any associated documentation\n(the \"Data Files\") or Unicode software and any associated documentation\n(the \"Software\") to deal in the Data Files or Software\nwithout restriction, including without limitation the rights to use,\ncopy, modify, merge, publish, distribute, and/or sell copies of\nthe Data Files or Software, and to permit persons to whom the Data Files\nor Software are furnished to do so, provided that either\n(a) this copyright and permission notice appear with all copies\nof the Data Files or Software, or\n(b) this copyright and permission notice appear in associated\nDocumentation.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT OF THIRD PARTY RIGHTS.\nIN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS\nNOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL\nDAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,\nDATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER\nTORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR\nPERFORMANCE OF THE DATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder\nshall not be used in advertising or otherwise to promote the sale,\nuse or other dealings in these Data Files or Software without prior\nwritten authorization of the copyright holder.",
            "name": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE (since 2016)",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved object code",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Use the object code generated from the modified source code"
                        },
                        {
                            "name": "Use the retrieved executable",
                            "description": "Use the obtained executable as is."
                        },
                        {
                            "name": "Use the executable generated from the modified source code"
                        },
                        {
                            "name": "To use the acquired data file without modification",
                            "description": "Use the fetched data files as they are."
                        },
                        {
                            "name": "Modify the acquired data file."
                        },
                        {
                            "name": "Using Modified Data Files"
                        }
                    ],
                    "_str": "Description: Treat related documents in the same way as data files and software.\nActions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved object code (Use the fetched code as it is.)\n- Use the object code generated from the modified source code\n- Use the retrieved executable (Use the obtained executable as is.)\n- Use the executable generated from the modified source code\n- To use the acquired data file without modification (Use the fetched data files as they are.)\n- Modify the acquired data file.\n- Using Modified Data Files\n\nConditions: None\n",
                    "conditions": null,
                    "description": "Treat related documents in the same way as data files and software."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the acquired data files without modification",
                            "description": "Distribute the acquired data files as they are"
                        },
                        {
                            "name": "Distribution of modified data files"
                        },
                        {
                            "name": "Selling data files"
                        },
                        {
                            "name": "I'm going to present the modified data file."
                        },
                        {
                            "name": "Sell altered data files."
                        }
                    ],
                    "_str": "Description: Related documents are treated in the same way as data files.\nActions:\n- Distribute the acquired data files without modification (Distribute the acquired data files as they are)\n- Distribution of modified data files\n- Selling data files\n- I'm going to present the modified data file.\n- Sell altered data files.\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer contained in such data files.\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer contained in such data files.",
                        "type": "OBLIGATION"
                    },
                    "description": "Related documents are treated in the same way as data files."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the obtained object code",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        },
                        {
                            "name": "Distribute the object code generated from the modified source code"
                        },
                        {
                            "name": "Selling Software"
                        },
                        {
                            "name": "Distribute the obtained executable",
                            "description": "Redistribute the obtained executable as-is"
                        },
                        {
                            "name": "Distribute the executable generated from the modified source code"
                        },
                        {
                            "name": "Publish the modified source code."
                        },
                        {
                            "name": "Present the object code generated from the modified source code."
                        },
                        {
                            "name": "Present the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: Related documentation should be treated in the same way as software.\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribute the obtained object code (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n- Distribute the object code generated from the modified source code\n- Selling Software\n- Distribute the obtained executable (Redistribute the obtained executable as-is)\n- Distribute the executable generated from the modified source code\n- Publish the modified source code.\n- Present the object code generated from the modified source code.\n- Present the executable generated from the modified source code\n\nConditions:\nOBLIGATION: Include a copyright notice, list of terms and conditions, and disclaimer contained in such software\n",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer contained in such software",
                        "type": "OBLIGATION"
                    },
                    "description": "Related documentation should be treated in the same way as software."
                },
                {
                    "actions": [
                        {
                            "name": "Use the copyright holder's name in software promotions and advertisements"
                        },
                        {
                            "name": "Use the copyright holder's name in data file promotions and advertisements."
                        }
                    ],
                    "_str": "Actions:\n- Use the copyright holder's name in software promotions and advertisements\n- Use the copyright holder's name in data file promotions and advertisements.\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    }
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE (since 2016)",
                    "Unicode-DFS-2015"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "http://www.unicode.org/copyright.html#License",
                            "The Unicode Data Files are located in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/, http://www.unicode.org/cldr/data/, http All data files in ://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]. However, it excludes PDFs of online code tables in the following directories: [http://www.unicode.org/Public/]. The software is either the source code published by the Unicode Standard, or it is available in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/,http://www.unicode It refers to the source code in [.org/cldr/data/, http://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]."
                        ]
                    ]
                ],
                "__impliedText": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/,\nhttp://www.unicode.org/cldr/data/, http://source.icu-project.org/repos/icu/, and\nhttp://www.unicode.org/utility/trac/browser/.\n\nUnicode Data Files do not include PDF online code charts under the\ndirectory http://www.unicode.org/Public/.\n\nSoftware includes any source code published in the Unicode Standard\nor under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/,\nhttp://www.unicode.org/cldr/data/, http://source.icu-project.org/repos/icu/, and\nhttp://www.unicode.org/utility/trac/browser/.\n\nNOTICE TO USER: Carefully read the following legal agreement.\nBY DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S\nDATA FILES (\"DATA FILES\"), AND/OR SOFTWARE (\"SOFTWARE\"),\nYOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE\nTERMS AND CONDITIONS OF THIS AGREEMENT.\nIF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE\nTHE DATA FILES OR SOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-<year> Unicode, Inc. All rights reserved.\nDistributed under the Terms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of the Unicode data files and any associated documentation\n(the \"Data Files\") or Unicode software and any associated documentation\n(the \"Software\") to deal in the Data Files or Software\nwithout restriction, including without limitation the rights to use,\ncopy, modify, merge, publish, distribute, and/or sell copies of\nthe Data Files or Software, and to permit persons to whom the Data Files\nor Software are furnished to do so, provided that either\n(a) this copyright and permission notice appear with all copies\nof the Data Files or Software, or\n(b) this copyright and permission notice appear in associated\nDocumentation.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT OF THIRD PARTY RIGHTS.\nIN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS\nNOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL\nDAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,\nDATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER\nTORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR\nPERFORMANCE OF THE DATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder\nshall not be used in advertising or otherwise to promote the sale,\nuse or other dealings in these Data Files or Software without prior\nwritten authorization of the copyright holder.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/976"
                    ]
                ]
            },
            "description": "The Unicode Data Files are located in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/, http://www.unicode.org/cldr/data/, http All data files in ://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]. However, it excludes PDFs of online code tables in the following directories: [http://www.unicode.org/Public/]. The software is either the source code published by the Unicode Standard, or it is available in the following directories [http://www.unicode.org/Public/, http://www.unicode.org/reports/,http://www.unicode It refers to the source code in [.org/cldr/data/, http://source.icu-project.org/repos/icu/, and http://www.unicode.org/utility/trac/browser/]."
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Unicode-DFS-2015.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Unicode License Agreement - Data Files and Software (2015)",
            "id": "Unicode-DFS-2015",
            "_implications": {
                "__impliedNames": [
                    "Unicode-DFS-2015",
                    "Unicode License Agreement - Data Files and Software (2015)"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Unicode-DFS-2015.html"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "Unicode-DFS-2015",
            "_implications": {
                "__impliedNames": [
                    "Unicode-DFS-2015"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE\n\nUnicode Data Files include all data files under the directories\nhttp://www.unicode.org/Public/, http://www.unicode.org/reports/, and\nhttp://www.unicode.org/cldr/data/. Unicode Data Files do not include PDF\nonline code charts under the directory http://www.unicode.org/Public/.\nSoftware includes any source code published in the Unicode Standard or\nunder the directories http://www.unicode.org/Public/,\nhttp://www.unicode.org/reports/, and http://www.unicode.org/cldr/data/.\n\nNOTICE TO USER: Carefully read the following legal agreement. BY\nDOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING UNICODE INC.'S DATA\nFILES (\"DATA FILES\"), AND/OR SOFTWARE (\"SOFTWARE\"), YOU UNEQUIVOCALLY\nACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE TERMS AND CONDITIONS OF\nTHIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT DOWNLOAD, INSTALL, COPY,\nDISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.\n\nCOPYRIGHT AND PERMISSION NOTICE\n\nCopyright © 1991-2015 Unicode, Inc. All rights reserved. Distributed\nunder the Terms of Use in http://www.unicode.org/copyright.html.\n\nPermission is hereby granted, free of charge, to any person obtaining a\ncopy of the Unicode data files and any associated documentation (the\n\"Data Files\") or Unicode software and any associated documentation (the\n\"Software\") to deal in the Data Files or Software without restriction,\nincluding without limitation the rights to use, copy, modify, merge,\npublish, distribute, and/or sell copies of the Data Files or Software,\nand to permit persons to whom the Data Files or Software are furnished\nto do so, provided that\n\n(a) this copyright and permission notice appear with all copies of\nthe Data Files or Software,\n\n(b) this copyright and permission notice appear in associated\ndocumentation, and\n\n(c) there is clear notice in each modified Data File or in the\nSoftware as well as in the documentation associated with the Data\nFile(s) or Software that the data or software has been modified.\n\nTHE DATA FILES AND SOFTWARE ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF\nANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE\nWARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\nNONINFRINGEMENT OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT\nHOLDER OR HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR\nANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER\nRESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF\nCONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN\nCONNECTION WITH THE USE OR PERFORMANCE OF THE DATA FILES OR SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder shall\nnot be used in advertising or otherwise to promote the sale, use or\nother dealings in these Data Files or Software without prior written\nauthorization of the copyright holder.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Unicode-DFS-2015.html"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/976"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Unicode-DFS-2015.json"
        ],
        [
            null,
            "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
        ],
        [
            "Homepage",
            "https://web.archive.org/web/20151224134844/http://unicode.org/copyright.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Unicode-DFS-2015.svg
