== W3C Software Notice and License (2002-12-31) (W3C)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |W3C Software Notice and License (2002-12-31)
|Shortname |W3C
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |False
|===

*Other Names:*

* `+W3C Software Notice and License+`
* `+W3C License+`
* `+The W3C Software Notice and License+`
* `+License :: OSI Approved :: W3C License+`
* `+W3C Software Notice and License (became active on December 31 2002)+`
* `+scancode://w3c+`
* `+W3C Software Notice and License 20021231+`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/W3C.html[SPDX] (all data [in this repository]
is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

* ``http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231''
(source: https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``"W3C Software Short Notice" can be found at
http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html
"previous version" can be found at http The link for "Free Software
Foundation's assessment of GPL compatibility" can be found at
http://www. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses
"OSI's certification" can be found at
www.w3.org/Consortium/Legal/copyright-software-19980720.
gnu.org/philosophy/license-list.html#GPLCompatibleLicenses "OSI's
certification" can be found at
http://www.opensource.org/licenses/W3C.php." The link for "Open Source
Definition" is http://www.opensource.org/docs/definition.php'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``Per SPDX.org, this license was released 13 December 2002. This
license is OSI certified. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3c.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:*
http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
* *OSI Page:* https://opensource.org/licenses/W3C
* *SPDX:* https://spdx.org/licenses/W3C.html
* *SPDX:* http://spdx.org/licenses/W3C.json
* *open-license:* http://open-license.hitachi.com/licenses/269
* http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html
* http://www.opensource.org/licenses/W3C
* http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html
http://www.opensource.org/licenses/W3C.php

=== Description from open-license

* {blank}
+
....
Description: Relevant documentation for the software should be treated in the same way as for the software.
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Using Modified Source Code
- Use the retrieved object code (Use the fetched code as it is.)
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use the object code generated from the modified source code
- Use binaries generated from modified source code
- Use the retrieved executable (Use the obtained executable as is.)
- Use the executable generated from the modified source code

Conditions: None
....
* {blank}
+
....
Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is here: http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.html■W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.]$name_of_software: $distribution_URICopyright © [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3C® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<- here ■"1998 Version" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.html ■"Copyright" link to http Link to "World Wide Web Consortium" can be found at http://www.w3.org/ ■"Massachusetts Institute of Technology" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/■"European Research Consortium for Informatics and Mathematics" can be found at http://www.ercim.org/■"Keio University" The link to http://www.keio.ac.jp/■"Beihang" can be found at http://ev.buaa.edu.cn/
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribute the obtained object code (Redistribute the code as it was obtained)
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribute the obtained executable (Redistribute the obtained executable as-is)

Conditions:
AND
  OBLIGATION: Give you a copy of the relevant license.
  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property

....
* {blank}
+
....
Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.html■W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright © [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3C® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this far■"1998 Version" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.html■"Copyright" link to http Link to "World Wide Web Consortium" can be found at http://www.w3.org/ ■"Massachusetts Institute of Technology" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/■"European Research Consortium for Informatics and Mathematics" can be found at http://www.ercim.org/■"Keio University" The link to http://www.keio.ac.jp/■The link to "Beihang" is http://ev.buaa.edu.cn/● When you inform people of changes you have made, it is recommended to inform them of the URI to get the code.
Actions:
- Modify the obtained source code.

Conditions:
AND
  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property
  OBLIGATION: Include a file to report the changes you make and the date of all changes

....
* {blank}
+
....
Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.html■W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright © [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3C® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this far■"1998 Version" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.html■"Copyright" link to http Link to "World Wide Web Consortium" can be found at http://www.w3.org/ ■"Massachusetts Institute of Technology" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/■"European Research Consortium for Informatics and Mathematics" can be found at http://www.ercim.org/■"Keio University" The link to http://www.keio.ac.jp/■The link to "Beihang" is http://ev.buaa.edu.cn/● When you inform people of changes you have made, it is recommended to inform them of the URI to get the code.
Actions:
- Distribution of Modified Source Code
- Distribute the object code generated from the modified source code
- Distribute the generated binaries from modified source code
- Distribute the executable generated from the modified source code

Conditions:
AND
  OBLIGATION: Give you a copy of the relevant license.
  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property
  OBLIGATION: Include a file to report the changes you make and the date of all changes

....
* {blank}
+
....
Description: The copyright to the software and related documentation is retained by the copyright holder at all times.
Actions:
- Using the copyright holder's name or trademark in software promotion and advertising

Conditions:
REQUISITE: Get special permission in writing.
....

(source: Hitachi open-license)

=== Text

....
By obtaining, using and/or copying this work, you (the licensee) agree that you
have read, understood, and will comply with the following terms and conditions.

Permission to copy, modify, and distribute this software and its documentation,
with or without modification, for any purpose and without fee or royalty is
hereby granted, provided that you include the following on ALL copies of the
software and documentation or portions thereof, including modifications:

The full text of this NOTICE in a location viewable to users of the
redistributed or derivative work.

Any pre-existing intellectual property disclaimers, notices, or terms and
conditions. If none exist, the W3C Software Short Notice should be included
(hypertext is preferred, text is permitted) within the body of any redistributed
or derivative code.

Notice of any changes or modifications to the files, including the date changes
were made. (We recommend you provide URIs to the location from which the code is
derived.)

Disclaimers
THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT HOLDERS MAKE
NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT
THE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY
PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.

COPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.

The name and trademarks of copyright holders may NOT be used in advertising or
publicity pertaining to the software without specific, written prior permission.
Title to copyright in this software and any associated documentation will at all
times remain with copyright holders.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)
* https://spdx.org/licenses/W3C.html[SPDX] (all data [in this
repository] is generated)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3c.yml[Scancode]
(CC0-1.0)
* https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses[Wikipedia]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])

==== Raw JSON

....
{
    "__impliedNames": [
        "W3C",
        "W3C Software Notice and License (2002-12-31)",
        "W3C Software Notice and License",
        "W3C License",
        "The W3C Software Notice and License",
        "License :: OSI Approved :: W3C License",
        "W3C Software Notice and License (became active on December 31 2002)",
        "scancode://w3c",
        "W3C Software Notice and License 20021231"
    ],
    "__impliedId": "W3C",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "W3C"
    ],
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
                "\"W3C Software Short Notice\" can be found at http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html \"previous version\" can be found at http The link for \"Free Software Foundation's assessment of GPL compatibility\" can be found at http://www. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at www.w3.org/Consortium/Legal/copyright-software-19980720. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at http://www.opensource.org/licenses/W3C.php.\" The link for \"Open Source Definition\" is http://www.opensource.org/docs/definition.php"
            ]
        ],
        [
            "Scancode",
            [
                "Per SPDX.org, this license was released 13 December 2002. This license is\nOSI certified.\n"
            ]
        ]
    ],
    "__hasPatentHint": false,
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/W3C",
            "maintainer": "World Wide Web Consortium",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "W3C",
            "title": "W3C License",
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C License"
                ],
                "__impliedId": "W3C",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "W3C"
                ],
                "__impliedId": "W3C"
            },
            "shortname": "W3C",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "W3C Software Notice and License (2002-12-31)",
            "spdxDetailsURL": "http://spdx.org/licenses/W3C.json",
            "_sourceURL": "https://spdx.org/licenses/W3C.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html",
                "https://opensource.org/licenses/W3C"
            ],
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C Software Notice and License (2002-12-31)"
                ],
                "__impliedId": "W3C",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/W3C.json"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            },
            "spdxLicenseId": "W3C"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
            "GPLv3 Compat?": "Yes",
            "Short Name": "W3C",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "W3C Software Notice and License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "W3C Software Notice and License"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "W3C"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://www.opensource.org/licenses/W3C",
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html",
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php",
                "https://opensource.org/licenses/W3C"
            ],
            "homepageUrl": "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
            "shortName": "W3C Software Notice and License",
            "textUrls": null,
            "text": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "W3C - World Wide Web Consortium",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3c.yml",
            "key": "w3c",
            "name": "W3C Software Notice and License",
            "spdxId": "W3C",
            "notes": "Per SPDX.org, this license was released 13 December 2002. This license is\nOSI certified.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://w3c",
                    "W3C Software Notice and License",
                    "W3C"
                ],
                "__impliedId": "W3C",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license was released 13 December 2002. This license is\nOSI certified.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/W3C"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            }
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "W3C"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            },
            "licensename": "W3C",
            "copyleftkind": "NoCopyleft"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "W3C License",
            "commercialUse": true,
            "spdxId": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C"
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
            "notices": [
                {
                    "content": "the software and related documentation are provided \"as-is\" and the copyright holder makes no warranties of any kind, either express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement of third party patents, copyrights, trademarks and other rights by use of the software and related documentation. The warranties include, but are not limited to, the warranties of commercial applicability, fitness for a particular purpose, and non-infringement of patents, copyrights, trademarks or other rights of third parties by use of the software or related documentation.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "In no event shall the copyright holder be liable for any direct, indirect, special or consequential damages resulting from the use of such software or related documentation."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/269",
            "content": "W3C Software Notice and License\n\nThis work (and included software, documentation such as READMEs, or other related items) is being provided by the copyright holders under the following license.\n\n\nLicense\n\nBy obtaining, using and/or copying this work, you (the licensee) agree that you have read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation, with or without modification, for any purpose and without fee or royalty is hereby granted, provided that you include the following on ALL copies of the software and documentation or portions thereof, including modifications:\n\n    â¢The full text of this NOTICE in a location viewable to users of the redistributed or \n    derivative work.\n\n    â¢Any pre-existing intellectual property disclaimers, notices, or terms and conditions. \n    If none exist, the W3C Software Short Notice should be included (hypertext is \n    preferred, text is permitted) within the body of any redistributed or \n    derivative code.\n\n    â¢Notice of any changes or modifications to the files, including the date changes \n    were made. (We recommend you provide URIs to the location from which the code \n    is derived.)\n\n\nDisclaimers\n\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or publicity pertaining to the software without specific, written prior permission. Title to copyright in this software and any associated documentation will at all times remain with copyright holders.\n\n\nNotes\n\nThis version: http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231\n\nThis formulation of W3C's notice and license became active on December 31 2002. This version removes the copyright ownership notice such that this license can be used with materials other than those owned by the W3C, reflects that ERCIM is now a host of the W3C, includes references to this specific dated version of the license, and removes the ambiguous grant of \"use\". Otherwise, this version is the same as the previous version and is written so as to preserve the Free Software Foundation's assessment of GPL compatibility and OSI's certification under the Open Source Definition.",
            "name": "W3C Software Notice and License (became active on December 31 2002)",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved object code",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use the object code generated from the modified source code"
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        },
                        {
                            "name": "Use the retrieved executable",
                            "description": "Use the obtained executable as is."
                        },
                        {
                            "name": "Use the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: Relevant documentation for the software should be treated in the same way as for the software.\nActions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Using Modified Source Code\n- Use the retrieved object code (Use the fetched code as it is.)\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use the object code generated from the modified source code\n- Use binaries generated from modified source code\n- Use the retrieved executable (Use the obtained executable as is.)\n- Use the executable generated from the modified source code\n\nConditions: None\n",
                    "conditions": null,
                    "description": "Relevant documentation for the software should be treated in the same way as for the software."
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the obtained object code",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the obtained executable",
                            "description": "Redistribute the obtained executable as-is"
                        }
                    ],
                    "_str": "Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is here: http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.]$name_of_software: $distribution_URICopyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<- here â \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.html â \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â \"Beihang\" can be found at http://ev.buaa.edu.cn/\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribute the obtained object code (Redistribute the code as it was obtained)\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribute the obtained executable (Redistribute the obtained executable as-is)\n\nConditions:\nAND\n  OBLIGATION: Give you a copy of the relevant license.\n  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Give you a copy of the relevant license.",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Include disclaimers, notices and clauses regarding existing intellectual property",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is here: http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.]$name_of_software: $distribution_URICopyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<- here â \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.html â \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â \"Beihang\" can be found at http://ev.buaa.edu.cn/"
                },
                {
                    "actions": [
                        {
                            "name": "Modify the obtained source code."
                        }
                    ],
                    "_str": "Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this farâ \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.htmlâ \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â The link to \"Beihang\" is http://ev.buaa.edu.cn/â When you inform people of changes you have made, it is recommended to inform them of the URI to get the code.\nActions:\n- Modify the obtained source code.\n\nConditions:\nAND\n  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property\n  OBLIGATION: Include a file to report the changes you make and the date of all changes\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include disclaimers, notices and clauses regarding existing intellectual property",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Include a file to report the changes you make and the date of all changes",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this farâ \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.htmlâ \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â The link to \"Beihang\" is http://ev.buaa.edu.cn/â When you inform people of changes you have made, it is recommended to inform them of the URI to get the code."
                },
                {
                    "actions": [
                        {
                            "name": "Distribution of Modified Source Code"
                        },
                        {
                            "name": "Distribute the object code generated from the modified source code"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        },
                        {
                            "name": "Distribute the executable generated from the modified source code"
                        }
                    ],
                    "_str": "Description: The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this farâ \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.htmlâ \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â The link to \"Beihang\" is http://ev.buaa.edu.cn/â When you inform people of changes you have made, it is recommended to inform them of the URI to get the code.\nActions:\n- Distribution of Modified Source Code\n- Distribute the object code generated from the modified source code\n- Distribute the generated binaries from modified source code\n- Distribute the executable generated from the modified source code\n\nConditions:\nAND\n  OBLIGATION: Give you a copy of the relevant license.\n  OBLIGATION: Include disclaimers, notices and clauses regarding existing intellectual property\n  OBLIGATION: Include a file to report the changes you make and the date of all changes\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Give you a copy of the relevant license.",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Include disclaimers, notices and clauses regarding existing intellectual property",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Include a file to report the changes you make and the date of all changes",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "The software's associated documentation should be treated in the same manner as the software. Include the W3C Software Short Notice (hypertext recommended, or text) in the body of the software's code, unless there is a disclaimer, notice, or clause at all. The link to the W3C Software Short Notice is http://www.w3.org/Consortium/Legal/2002/copyright-software-short-notice-20021231.htmlâ W3C Software A Short Notice can be found here: here ->[This notice should be placed within redistributed or derivative software code when appropriate. formulation became active on December 31 2002, superseding the 1998 version.] $name_of_software: $distribution_URI Copyright Â© [$date-of-software ] World Wide Web Consortium, (Massachusetts Institute of Technology, European Research Consortium for Informatics and Mathematics, Keio University, Beihang). This work is distributed under the W3CÂ® Software License [1] in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.[1] http://www.w3.org/Consortium/Legal/2002/copyright-software- 20021231<-this farâ \"1998 Version\" link to http://www.w3.org/Consortium/Legal/generic-copyright-notice-19980720.htmlâ \"Copyright\" link to http Link to \"World Wide Web Consortium\" can be found at http://www.w3.org/ â \"Massachusetts Institute of Technology\" link to www.w3.org/Consortium/Legal/ipr-notice The link to http://www.lcs.mit.edu/â \"European Research Consortium for Informatics and Mathematics\" can be found at http://www.ercim.org/â \"Keio University\" The link to http://www.keio.ac.jp/â The link to \"Beihang\" is http://ev.buaa.edu.cn/â When you inform people of changes you have made, it is recommended to inform them of the URI to get the code."
                },
                {
                    "actions": [
                        {
                            "name": "Using the copyright holder's name or trademark in software promotion and advertising"
                        }
                    ],
                    "_str": "Description: The copyright to the software and related documentation is retained by the copyright holder at all times.\nActions:\n- Using the copyright holder's name or trademark in software promotion and advertising\n\nConditions:\nREQUISITE: Get special permission in writing.\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "The copyright to the software and related documentation is retained by the copyright holder at all times."
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "W3C Software Notice and License (became active on December 31 2002)",
                    "W3C"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
                            "\"W3C Software Short Notice\" can be found at http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html \"previous version\" can be found at http The link for \"Free Software Foundation's assessment of GPL compatibility\" can be found at http://www. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at www.w3.org/Consortium/Legal/copyright-software-19980720. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at http://www.opensource.org/licenses/W3C.php.\" The link for \"Open Source Definition\" is http://www.opensource.org/docs/definition.php"
                        ]
                    ]
                ],
                "__impliedText": "W3C Software Notice and License\n\nThis work (and included software, documentation such as READMEs, or other related items) is being provided by the copyright holders under the following license.\n\n\nLicense\n\nBy obtaining, using and/or copying this work, you (the licensee) agree that you have read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation, with or without modification, for any purpose and without fee or royalty is hereby granted, provided that you include the following on ALL copies of the software and documentation or portions thereof, including modifications:\n\n    â¢The full text of this NOTICE in a location viewable to users of the redistributed or \n    derivative work.\n\n    â¢Any pre-existing intellectual property disclaimers, notices, or terms and conditions. \n    If none exist, the W3C Software Short Notice should be included (hypertext is \n    preferred, text is permitted) within the body of any redistributed or \n    derivative code.\n\n    â¢Notice of any changes or modifications to the files, including the date changes \n    were made. (We recommend you provide URIs to the location from which the code \n    is derived.)\n\n\nDisclaimers\n\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or publicity pertaining to the software without specific, written prior permission. Title to copyright in this software and any associated documentation will at all times remain with copyright holders.\n\n\nNotes\n\nThis version: http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231\n\nThis formulation of W3C's notice and license became active on December 31 2002. This version removes the copyright ownership notice such that this license can be used with materials other than those owned by the W3C, reflects that ERCIM is now a host of the W3C, includes references to this specific dated version of the license, and removes the ambiguous grant of \"use\". Otherwise, this version is the same as the previous version and is written so as to preserve the Free Software Foundation's assessment of GPL compatibility and OSI's certification under the Open Source Definition.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/269"
                    ]
                ]
            },
            "description": "\"W3C Software Short Notice\" can be found at http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html \"previous version\" can be found at http The link for \"Free Software Foundation's assessment of GPL compatibility\" can be found at http://www. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at www.w3.org/Consortium/Legal/copyright-software-19980720. gnu.org/philosophy/license-list.html#GPLCompatibleLicenses \"OSI's certification\" can be found at http://www.opensource.org/licenses/W3C.php.\" The link for \"Open Source Definition\" is http://www.opensource.org/docs/definition.php"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/W3C.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "W3C Software Notice and License (2002-12-31)",
            "id": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C Software Notice and License (2002-12-31)"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/W3C.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/W3C",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "W3C",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: W3C License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The W3C Software Notice and License",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "W3C",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/W3C"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "The W3C Software Notice and License",
                    "W3C",
                    "License :: OSI Approved :: W3C License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Permissive",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": "December 31, 2002",
            "Coordinates": {
                "name": "W3C Software Notice and License",
                "version": "20021231",
                "spdxId": "W3C"
            },
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C Software Notice and License 20021231"
                ],
                "__hasPatentHint": false
            },
            "Modification": {
                "value": "Permissive",
                "description": "modification of the code by a licensee"
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "HansHammel license-compatibility-checker",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/W3C.html"
        ],
        [
            null,
            "https://opensource.org/licenses/W3C"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/W3C"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/269"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/W3C.json"
        ],
        [
            null,
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
        ],
        [
            "Homepage",
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231"
        ],
        [
            null,
            "http://www.opensource.org/licenses/W3C"
        ],
        [
            null,
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/W3C.svg