== W3C Software Notice and License (2002-12-31) (W3C)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |W3C Software Notice and License (2002-12-31)
|Shortname |W3C
|Rating |Go
|Classification |NoCopyleft
|Has Patent Hint |False
|===

*Other Names:*

* `+scancode:w3c+`
* `+W3C Software Notice and License+`
* `+The W3C Software Notice and License+`
* `+License :: OSI Approved :: W3C License+`
* `+W3C Software Notice and License 20021231+`
* `+W3C License+`

=== Comments on (easy) usability

* **↑**Google Classification is NOTICE (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])
* **↑**Is OSI Approved (source:
https://spdx.org/licenses/W3C.html[SPDX])
* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:*
http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
* *OSI Page:* https://opensource.org/licenses/W3C
* *SPDX:* http://spdx.org/licenses/W3C.json
* *SPDX:* https://spdx.org/licenses/W3C.html
* http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html
* http://www.opensource.org/licenses/W3C
* http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html
http://www.opensource.org/licenses/W3C.php

=== Text

....
By obtaining, using and/or copying this work, you (the licensee) agree that you
have read, understood, and will comply with the following terms and conditions.

Permission to copy, modify, and distribute this software and its documentation,
with or without modification, for any purpose and without fee or royalty is
hereby granted, provided that you include the following on ALL copies of the
software and documentation or portions thereof, including modifications:

The full text of this NOTICE in a location viewable to users of the
redistributed or derivative work.

Any pre-existing intellectual property disclaimers, notices, or terms and
conditions. If none exist, the W3C Software Short Notice should be included
(hypertext is preferred, text is permitted) within the body of any redistributed
or derivative code.

Notice of any changes or modifications to the files, including the date changes
were made. (We recommend you provide URIs to the location from which the code is
derived.)

Disclaimers
THIS SOFTWARE AND DOCUMENTATION IS PROVIDED "AS IS," AND COPYRIGHT HOLDERS MAKE
NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT
THE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY
PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.

COPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.

The name and trademarks of copyright holders may NOT be used in advertising or
publicity pertaining to the software without specific, written prior permission.
Title to copyright in this software and any associated documentation will at all
times remain with copyright holders.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "W3C",
        "W3C Software Notice and License (2002-12-31)",
        "scancode:w3c",
        "W3C Software Notice and License",
        "The W3C Software Notice and License",
        "License :: OSI Approved :: W3C License",
        "W3C Software Notice and License 20021231",
        "W3C License"
    ],
    "__impliedId": "W3C",
    "__isFsfFree": true,
    "__hasPatentHint": false,
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/W3C",
            "maintainer": "World Wide Web Consortium",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "W3C",
            "title": "W3C License",
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C License"
                ],
                "__impliedId": "W3C",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C",
                    "W3C Software Notice and License (2002-12-31)",
                    "scancode:w3c",
                    "W3C Software Notice and License",
                    "The W3C Software Notice and License",
                    "License :: OSI Approved :: W3C License",
                    "W3C Software Notice and License 20021231",
                    "W3C License"
                ],
                "__impliedId": "W3C"
            },
            "shortname": "W3C",
            "otherNames": [
                "W3C",
                "W3C Software Notice and License (2002-12-31)",
                "scancode:w3c",
                "W3C Software Notice and License",
                "The W3C Software Notice and License",
                "License :: OSI Approved :: W3C License",
                "W3C Software Notice and License 20021231",
                "W3C License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "W3C Software Notice and License (2002-12-31)",
            "spdxDetailsURL": "http://spdx.org/licenses/W3C.json",
            "_sourceURL": "https://spdx.org/licenses/W3C.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html",
                "https://opensource.org/licenses/W3C"
            ],
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C Software Notice and License (2002-12-31)"
                ],
                "__impliedId": "W3C",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/W3C.json"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            },
            "spdxLicenseId": "W3C"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
            "GPLv3 Compat?": "Yes",
            "Short Name": "W3C",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "W3C Software Notice and License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "W3C Software Notice and License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://www.opensource.org/licenses/W3C",
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html",
                "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php",
                "https://opensource.org/licenses/W3C"
            ],
            "homepageUrl": "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231",
            "shortName": "W3C Software Notice and License",
            "textUrls": null,
            "text": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "W3C - World Wide Web Consortium",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3c.yml",
            "key": "w3c",
            "name": "W3C Software Notice and License",
            "spdxId": "W3C",
            "_implications": {
                "__impliedNames": [
                    "scancode:w3c",
                    "W3C Software Notice and License",
                    "W3C"
                ],
                "__impliedId": "W3C",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231"
                    ],
                    [
                        null,
                        "http://www.opensource.org/licenses/W3C"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
                    ],
                    [
                        null,
                        "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "W3C License",
            "commercialUse": true,
            "spdxId": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/W3C.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "W3C Software Notice and License (2002-12-31)",
            "id": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/W3C.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/W3C",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "W3C",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: W3C License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The W3C Software Notice and License",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "W3C",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/W3C"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "The W3C Software Notice and License",
                    "W3C",
                    "License :: OSI Approved :: W3C License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/W3C"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Linking": {
                "value": "Permissive",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": "December 31, 2002",
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "Koordinaten": {
                "name": "W3C Software Notice and License",
                "version": "20021231",
                "spdxId": "W3C"
            },
            "_implications": {
                "__impliedNames": [
                    "W3C",
                    "W3C Software Notice and License 20021231"
                ],
                "__hasPatentHint": false
            },
            "Modification": {
                "value": "Permissive",
                "description": "modification of the code by a licensee"
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "W3C",
            "_implications": {
                "__impliedNames": [
                    "W3C"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "By obtaining, using and/or copying this work, you (the licensee) agree that you\nhave read, understood, and will comply with the following terms and conditions.\n\nPermission to copy, modify, and distribute this software and its documentation,\nwith or without modification, for any purpose and without fee or royalty is\nhereby granted, provided that you include the following on ALL copies of the\nsoftware and documentation or portions thereof, including modifications:\n\nThe full text of this NOTICE in a location viewable to users of the\nredistributed or derivative work.\n\nAny pre-existing intellectual property disclaimers, notices, or terms and\nconditions. If none exist, the W3C Software Short Notice should be included\n(hypertext is preferred, text is permitted) within the body of any redistributed\nor derivative code.\n\nNotice of any changes or modifications to the files, including the date changes\nwere made. (We recommend you provide URIs to the location from which the code is\nderived.)\n\nDisclaimers\nTHIS SOFTWARE AND DOCUMENTATION IS PROVIDED \"AS IS,\" AND COPYRIGHT HOLDERS MAKE\nNO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED\nTO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT\nTHE USE OF THE SOFTWARE OR DOCUMENTATION WILL NOT INFRINGE ANY THIRD PARTY\nPATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.\n\nCOPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR\nCONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENTATION.\n\nThe name and trademarks of copyright holders may NOT be used in advertising or\npublicity pertaining to the software without specific, written prior permission.\nTitle to copyright in this software and any associated documentation will at all\ntimes remain with copyright holders.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/W3C.json"
        ],
        [
            null,
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html"
        ],
        [
            null,
            "https://opensource.org/licenses/W3C"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/W3C.html"
        ],
        [
            "Homepage",
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231"
        ],
        [
            null,
            "http://www.opensource.org/licenses/W3C"
        ],
        [
            null,
            "http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231.html http://www.opensource.org/licenses/W3C.php"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/W3C"
        ]
    ]
}
....