== Wsuipa License (Wsuipa)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Wsuipa License
|Shortname |Wsuipa
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://wsuipa+`

=== Comments on (easy) usability

* Per Fedora, this license was found on the "wsuipa" component of
texlive 2010. It is Free, but GPL-incompatible. (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/wsuipa.yml[Scancode])
* **↓**Rating is: Lead (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/Wsuipa
* *SPDX:* http://spdx.org/licenses/Wsuipa.json
* *SPDX:* https://spdx.org/licenses/Wsuipa.html

=== Text

....
This file was added by Clea F. Rees on 2008/11/30 with the permission of Dean
Guenther and pointers to this file were added to all source files.

Unlimited copying and redistribution of each of the files is permitted as long
as the file is not modified. Modifications, and redistribution of modified
versions, are also permitted, but only if the resulting file is renamed.

The copyright holder is Washington State University. The original author of the
fonts is Janene Winter. The primary contact (as of 2008) is Dean Guenther.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "Wsuipa",
        "Wsuipa License",
        "scancode://wsuipa"
    ],
    "__impliedId": "Wsuipa",
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Wsuipa License",
            "spdxDetailsURL": "http://spdx.org/licenses/Wsuipa.json",
            "_sourceURL": "https://spdx.org/licenses/Wsuipa.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/Wsuipa"
            ],
            "_implications": {
                "__impliedNames": [
                    "Wsuipa",
                    "Wsuipa License"
                ],
                "__impliedId": "Wsuipa",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Wsuipa.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/Wsuipa"
                    ]
                ]
            },
            "spdxLicenseId": "Wsuipa"
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/Wsuipa",
            "shortName": "Wsuipa License",
            "textUrls": null,
            "text": "This file was added by Clea F. Rees on 2008/11/30 with the permission of Dean\nGuenther and pointers to this file were added to all source files.\n\nUnlimited copying and redistribution of each of the files is permitted as long\nas the file is not modified. Modifications, and redistribution of modified\nversions, are also permitted, but only if the resulting file is renamed.\n\nThe copyright holder is Washington State University. The original author of the\nfonts is Janene Winter. The primary contact (as of 2008) is Dean Guenther.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Washington State University",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/wsuipa.yml",
            "key": "wsuipa",
            "name": "Wsuipa License",
            "spdxId": "Wsuipa",
            "notes": "Per Fedora, this license was found on the \"wsuipa\" component of texlive\n2010. It is Free, but GPL-incompatible.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://wsuipa",
                    "Wsuipa License",
                    "Wsuipa"
                ],
                "__impliedId": "Wsuipa",
                "__impliedJudgement": [
                    [
                        "Scancode",
                        {
                            "tag": "NeutralJudgement",
                            "contents": "Per Fedora, this license was found on the \"wsuipa\" component of texlive\n2010. It is Free, but GPL-incompatible.\n"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This file was added by Clea F. Rees on 2008/11/30 with the permission of Dean\nGuenther and pointers to this file were added to all source files.\n\nUnlimited copying and redistribution of each of the files is permitted as long\nas the file is not modified. Modifications, and redistribution of modified\nversions, are also permitted, but only if the resulting file is renamed.\n\nThe copyright holder is Washington State University. The original author of the\nfonts is Janene Winter. The primary contact (as of 2008) is Dean Guenther.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/Wsuipa"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Wsuipa.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Wsuipa License",
            "id": "Wsuipa",
            "_implications": {
                "__impliedNames": [
                    "Wsuipa"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Wsuipa.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Scancode",
            {
                "tag": "NeutralJudgement",
                "contents": "Per Fedora, this license was found on the \"wsuipa\" component of texlive\n2010. It is Free, but GPL-incompatible.\n"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This file was added by Clea F. Rees on 2008/11/30 with the permission of Dean\nGuenther and pointers to this file were added to all source files.\n\nUnlimited copying and redistribution of each of the files is permitted as long\nas the file is not modified. Modifications, and redistribution of modified\nversions, are also permitted, but only if the resulting file is renamed.\n\nThe copyright holder is Washington State University. The original author of the\nfonts is Janene Winter. The primary contact (as of 2008) is Dean Guenther.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Wsuipa.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/Wsuipa"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Wsuipa.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/Wsuipa"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/Wsuipa.svg[image,title="dot"]