== Do What The F*ck You Want To Public License (WTFPL)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Do What The F*ck You Want To Public License
|Shortname |WTFPL
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|Has Patent Hint |False
|===

*Other Names:*

* `+scancode://wtfpl-2.0+`
* `+WTFPL 2.0+`
* `+Do What The Fuck You Want To Public License (WTFPL) 2+`

=== Description

____
The easiest license out there. It gives the user permissions to do
whatever they want with your code.
____

(source: choosealicense.com)

=== Comments on (easy) usability

* **↑**This license is compatible with the DebianFreeSoftwareGuidelines
(DFSG-free) (source: https://wiki.debian.org/DFSGLicenses[Debian Free
Software Guidelines])
* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])
* **↓**Google Classification is CANNOT_BE_USED "Code released under the
WTFPL cannot be used at Google. This license has a large number of
issues (lack of warranty disclaimer, very vague rights grant), and was
also rejected as an open source license by OSI. We also do not allow
contribution to projects under the WTFPL." (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])
* **↓**Rating is: Lead (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== Obligations

[cols=",,",options="header",]
|===
|Rights: |Conditions: |Limitations:
a|
* commercial-use
* modifications
* distribution
* private-use

a|

a|

|===

(source:
https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/wtfpl.txt[choosealicense.com])

=== URLs

* *Homepage:* http://sam.zoy.org/wtfpl/
* *SPDX:* http://spdx.org/licenses/WTFPL.json
* *SPDX:* https://spdx.org/licenses/WTFPL.html
* http://sam.zoy.org/wtfpl/COPYING
* http://fedoraproject.org/wiki/Licensing/WTFPL

=== OSADL Rule

....
USE CASE Source code delivery OR Binary delivery
....

(source: OSADL License Checklist)

=== Text

....
DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

 Copyright (C) 2004 Sam Hocevar
  14 rue de Plaisance, 75014 Paris, France
 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "WTFPL",
        "Do What The F*ck You Want To Public License",
        "scancode://wtfpl-2.0",
        "WTFPL 2.0",
        "wtfpl",
        "Do What The Fuck You Want To Public License (WTFPL) 2"
    ],
    "__impliedId": "WTFPL",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE"
    ],
    "__hasPatentHint": false,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "WTFPL",
                    "WTFPL",
                    "Do What The F*ck You Want To Public License",
                    "scancode://wtfpl-2.0",
                    "WTFPL 2.0",
                    "wtfpl",
                    "Do What The Fuck You Want To Public License (WTFPL) 2"
                ],
                "__impliedId": "WTFPL"
            },
            "shortname": "WTFPL",
            "otherNames": [
                "WTFPL",
                "Do What The F*ck You Want To Public License",
                "scancode://wtfpl-2.0",
                "WTFPL 2.0",
                "wtfpl",
                "Do What The Fuck You Want To Public License (WTFPL) 2"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Do What The F*ck You Want To Public License",
            "spdxDetailsURL": "http://spdx.org/licenses/WTFPL.json",
            "_sourceURL": "https://spdx.org/licenses/WTFPL.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://sam.zoy.org/wtfpl/COPYING"
            ],
            "_implications": {
                "__impliedNames": [
                    "WTFPL",
                    "Do What The F*ck You Want To Public License"
                ],
                "__impliedId": "WTFPL",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/WTFPL.json"
                    ],
                    [
                        null,
                        "http://sam.zoy.org/wtfpl/COPYING"
                    ]
                ]
            },
            "spdxLicenseId": "WTFPL"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/WTFPL.txt",
            "spdxId": "WTFPL",
            "osadlRule": "USE CASE Source code delivery OR Binary delivery\n",
            "_implications": {
                "__impliedNames": [
                    "WTFPL"
                ]
            }
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "Yes",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/WTFPL",
            "GPLv3 Compat?": "Yes",
            "Short Name": "WTFPL",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Do What The F*ck You Want To Public License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Do What The F*ck You Want To Public License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "http://fedoraproject.org/wiki/Licensing/WTFPL"
            ],
            "homepageUrl": "http://sam.zoy.org/wtfpl/",
            "shortName": "WTFPL 2.0",
            "textUrls": null,
            "text": "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n                    Version 2, December 2004\n\n Copyright (C) 2004 Sam Hocevar\n  14 rue de Plaisance, 75014 Paris, France\n Everyone is permitted to copy and distribute verbatim or modified\n copies of this license document, and changing it is allowed as long\n as the name is changed.\n\n            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n  0. You just DO WHAT THE FUCK YOU WANT TO.",
            "category": "Public Domain",
            "osiUrl": null,
            "owner": "Sam Hocevar",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/wtfpl-2.0.yml",
            "key": "wtfpl-2.0",
            "name": "WTFPL 2.0",
            "spdxId": "WTFPL",
            "_implications": {
                "__impliedNames": [
                    "scancode://wtfpl-2.0",
                    "WTFPL 2.0",
                    "WTFPL"
                ],
                "__impliedId": "WTFPL",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n                    Version 2, December 2004\n\n Copyright (C) 2004 Sam Hocevar\n  14 rue de Plaisance, 75014 Paris, France\n Everyone is permitted to copy and distribute verbatim or modified\n copies of this license document, and changing it is allowed as long\n as the name is changed.\n\n            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n  0. You just DO WHAT THE FUCK YOU WANT TO.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://sam.zoy.org/wtfpl/"
                    ],
                    [
                        null,
                        "http://fedoraproject.org/wiki/Licensing/WTFPL"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Do what the F*ck You want to Public License",
            "commercialUse": true,
            "spdxId": "WTFPL",
            "_implications": {
                "__impliedNames": [
                    "WTFPL"
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "WTFPL"
                ],
                "__impliedAmbiguousNames": [
                    "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "WTFPL"
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/WTFPL.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Do What The F*ck You Want To Public License",
            "id": "WTFPL",
            "_implications": {
                "__impliedNames": [
                    "WTFPL"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/WTFPL.html"
                    ]
                ]
            }
        },
        "Wikipedia": {
            "Distribution": {
                "value": "Permissive/Public domain",
                "description": "distribution of the code to third parties"
            },
            "Sublicensing": {
                "value": "Yes",
                "description": "whether modified code may be licensed under a different license (for example a copyright) or must retain the same license under which it was provided"
            },
            "Linking": {
                "value": "Permissive/Public domain",
                "description": "linking of the licensed code with code licensed under a different license (e.g. when the code is provided as a library)"
            },
            "Publication date": "December 2004",
            "_sourceURL": "https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses",
            "Koordinaten": {
                "name": "Do What The Fuck You Want To Public License (WTFPL)",
                "version": "2",
                "spdxId": "WTFPL"
            },
            "Patent grant": {
                "value": "No",
                "description": "protection of licensees from patent claims made by code contributors regarding their contribution, and protection of contributors from patent claims made by licensees"
            },
            "Trademark grant": {
                "value": "No",
                "description": "use of trademarks associated with the licensed code or its contributors by a licensee"
            },
            "_implications": {
                "__impliedNames": [
                    "WTFPL",
                    "Do What The Fuck You Want To Public License (WTFPL) 2"
                ],
                "__hasPatentHint": false
            },
            "Private use": {
                "value": "Yes",
                "description": "whether modification to the code must be shared with the community or may be used privately (e.g. internal use by a corporation)"
            },
            "Modification": {
                "value": "Permissive/Public domain",
                "description": "modification of the code by a licensee"
            }
        },
        "choosealicense.com": {
            "limitations": [],
            "_sourceURL": "https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/wtfpl.txt",
            "content": "---\ntitle: \"Do What The F*ck You Want To Public License\"\nspdx-id: WTFPL\n\ndescription: The easiest license out there. It gives the user permissions to do whatever they want with your code.\n\nhow: Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.\n\nusing:\n\npermissions:\n  - commercial-use\n  - modifications\n  - distribution\n  - private-use\n\nconditions: []\n\nlimitations: []\n\n---\n\n            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n                    Version 2, December 2004\n\n Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>\n\n Everyone is permitted to copy and distribute verbatim or modified\n copies of this license document, and changing it is allowed as long\n as the name is changed.\n\n            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n  0. You just DO WHAT THE FUCK YOU WANT TO.\n",
            "name": "wtfpl",
            "hidden": null,
            "spdxId": "WTFPL",
            "conditions": [],
            "permissions": [
                "commercial-use",
                "modifications",
                "distribution",
                "private-use"
            ],
            "featured": null,
            "nickname": null,
            "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
            "title": "\"Do What The F*ck You Want To Public License\"",
            "_implications": {
                "__impliedNames": [
                    "wtfpl",
                    "WTFPL"
                ],
                "__obligations": {
                    "limitations": [],
                    "rights": [
                        {
                            "tag": "ImpliedRight",
                            "contents": "commercial-use"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "modifications"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "distribution"
                        },
                        {
                            "tag": "ImpliedRight",
                            "contents": "private-use"
                        }
                    ],
                    "conditions": []
                }
            },
            "description": "The easiest license out there. It gives the user permissions to do whatever they want with your code."
        },
        "Google OSS Policy": {
            "rating": "CANNOT_BE_USED",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "WTFPL",
            "_implications": {
                "__impliedNames": [
                    "WTFPL"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Google Classification is CANNOT_BE_USED \"Code released under the WTFPL cannot be used at Google. This license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI. We also do not allow contribution to projects under the WTFPL.\""
                        }
                    ]
                ]
            },
            "description": "Code released under the WTFPL cannot be used at Google. This license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI. We also do not allow contribution to projects under the WTFPL."
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "NegativeJudgement",
                "contents": "Google Classification is CANNOT_BE_USED \"Code released under the WTFPL cannot be used at Google. This license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI. We also do not allow contribution to projects under the WTFPL.\""
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__obligations": {
        "limitations": [],
        "rights": [
            {
                "tag": "ImpliedRight",
                "contents": "commercial-use"
            },
            {
                "tag": "ImpliedRight",
                "contents": "modifications"
            },
            {
                "tag": "ImpliedRight",
                "contents": "distribution"
            },
            {
                "tag": "ImpliedRight",
                "contents": "private-use"
            }
        ],
        "conditions": []
    },
    "__isOsiApproved": false,
    "__impliedText": "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n                    Version 2, December 2004\n\n Copyright (C) 2004 Sam Hocevar\n  14 rue de Plaisance, 75014 Paris, France\n Everyone is permitted to copy and distribute verbatim or modified\n copies of this license document, and changing it is allowed as long\n as the name is changed.\n\n            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n\n  0. You just DO WHAT THE FUCK YOU WANT TO.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/WTFPL.json"
        ],
        [
            null,
            "http://sam.zoy.org/wtfpl/COPYING"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/WTFPL.html"
        ],
        [
            "Homepage",
            "http://sam.zoy.org/wtfpl/"
        ],
        [
            null,
            "http://fedoraproject.org/wiki/Licensing/WTFPL"
        ]
    ]
}
....