== X.Net License (Xnet)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |X.Net License
|Shortname |Xnet
|Rating |Unknown, no option left
|Classification |NoCopyleft
|===

*Other Names:*

* `The X.Net, Inc. License`
* `License :: OSI Approved :: X.Net License`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/Xnet.html[SPDX] (all data [in this repository]
is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))
* **↓**``This software licenses which is NOT OKAY for Fedora. Nothing in
Fedora is permitted to use this license. It is either non-free or
deprecated.'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))

=== General Comments

=== URLs

* *OSI Page:* https://opensource.org/licenses/Xnet
* *SPDX:* https://spdx.org/licenses/Xnet.html
* *SPDX:* http://spdx.org/licenses/Xnet.json

'''''

=== Raw Data

==== Facts

* LicenseName
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://spdx.org/licenses/Xnet.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Xnet",
        "X.Net License",
        "The X.Net, Inc. License",
        "License :: OSI Approved :: X.Net License"
    ],
    "__impliedId": "Xnet",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/Xnet",
            "maintainer": "",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "Xnet",
            "title": "X.Net License",
            "_implications": {
                "__impliedNames": [
                    "Xnet",
                    "X.Net License"
                ],
                "__impliedId": "Xnet",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/Xnet"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Xnet"
                ],
                "__impliedId": "Xnet"
            },
            "shortname": "Xnet",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "X.Net License",
            "spdxDetailsURL": "http://spdx.org/licenses/Xnet.json",
            "_sourceURL": "https://spdx.org/licenses/Xnet.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "https://opensource.org/licenses/Xnet"
            ],
            "_implications": {
                "__impliedNames": [
                    "Xnet",
                    "X.Net License"
                ],
                "__impliedId": "Xnet",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Xnet.json"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/Xnet"
                    ]
                ]
            },
            "spdxLicenseId": "Xnet"
        },
        "Fedora Project Wiki": {
            "rating": "Bad",
            "Upstream URL": "http://opensource.org/licenses/xnet.php",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "X.Net License",
            "FSF Free?": "N/A",
            "_implications": {
                "__impliedNames": [
                    "X.Net License"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
                        }
                    ]
                ]
            },
            "Notes": "Deprecated license"
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "X.Net License ",
            "commercialUse": true,
            "spdxId": "Xnet",
            "_implications": {
                "__impliedNames": [
                    "Xnet"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/Xnet.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "X.Net License",
            "id": "Xnet",
            "_implications": {
                "__impliedNames": [
                    "Xnet",
                    "X.Net License"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Xnet.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/Xnet",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "Xnet",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: X.Net License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The X.Net, Inc. License",
            "other_names": [],
            "keywords": [
                "osi-approved",
                "discouraged",
                "redundant"
            ],
            "id": "Xnet",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/Xnet"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Xnet",
                    "The X.Net, Inc. License",
                    "Xnet",
                    "License :: OSI Approved :: X.Net License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/Xnet"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "Xnet",
            "_implications": {
                "__impliedNames": [
                    "Xnet"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "NegativeJudgement",
                "contents": "This software licenses which is NOT OKAY for Fedora. Nothing in Fedora is permitted to use this license. It is either non-free or deprecated."
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedURLs": [
        [
            "SPDX",
            "https://spdx.org/licenses/Xnet.html"
        ],
        [
            null,
            "https://opensource.org/licenses/Xnet"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/Xnet"
        ],
        [
            "SPDX",
            "http://spdx.org/licenses/Xnet.json"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Xnet.svg
