== XSkat License (XSkat)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |XSkat License
|Shortname |XSkat
|Rating |Unknown
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode:xskat+`

=== Comments on (easy) usability

* **↑**This software Licenses is OK for Fedora (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki])

=== URLs

* *Homepage:* https://fedoraproject.org/wiki/Licensing/XSkat_License
* *SPDX:* http://spdx.org/licenses/XSkat.json

=== Text

....
This program is free software; you can redistribute it freely.
Use it at your own risk; there is NO WARRANTY.

Redistribution of modified versions is permitted provided that the following
conditions are met:

1. All copyright & permission notices are preserved.

2.a) Only changes required for packaging or porting are made. 
or
2.b) It is clearly stated who last changed the program. The program is renamed
or the version number is of the form x.y.z, where x.y is the version of the
original program and z is an arbitrary suffix.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "XSkat",
        "XSkat License",
        "scancode:xskat"
    ],
    "__impliedId": "XSkat",
    "__isFsfFree": true,
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "XSkat",
                    "XSkat",
                    "XSkat License",
                    "scancode:xskat"
                ],
                "__impliedId": "XSkat"
            },
            "shortname": "XSkat",
            "otherNames": [
                "XSkat",
                "XSkat License",
                "scancode:xskat"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "XSkat License",
            "spdxDetailsURL": "http://spdx.org/licenses/XSkat.json",
            "_sourceURL": "https://spdx.org/licenses/XSkat.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/XSkat_License"
            ],
            "_implications": {
                "__impliedNames": [
                    "XSkat",
                    "XSkat License"
                ],
                "__impliedId": "XSkat",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/XSkat.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/XSkat_License"
                    ]
                ]
            },
            "spdxLicenseId": "XSkat"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "https://fedoraproject.org/wiki/Licensing/XSkat_License",
            "GPLv3 Compat?": "NO",
            "Short Name": "XSkat",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "XSkat License",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "XSkat License"
                ],
                "__isFsfFree": true,
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing/XSkat_License",
            "shortName": "XSkat License",
            "textUrls": null,
            "text": "This program is free software; you can redistribute it freely.\nUse it at your own risk; there is NO WARRANTY.\n\nRedistribution of modified versions is permitted provided that the following\nconditions are met:\n\n1. All copyright & permission notices are preserved.\n\n2.a) Only changes required for packaging or porting are made. \nor\n2.b) It is clearly stated who last changed the program. The program is renamed\nor the version number is of the form x.y.z, where x.y is the version of the\noriginal program and z is an arbitrary suffix.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "XSkat",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/xskat.yml",
            "key": "xskat",
            "name": "XSkat License",
            "spdxId": "XSkat",
            "_implications": {
                "__impliedNames": [
                    "scancode:xskat",
                    "XSkat License",
                    "XSkat"
                ],
                "__impliedId": "XSkat",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This program is free software; you can redistribute it freely.\nUse it at your own risk; there is NO WARRANTY.\n\nRedistribution of modified versions is permitted provided that the following\nconditions are met:\n\n1. All copyright & permission notices are preserved.\n\n2.a) Only changes required for packaging or porting are made. \nor\n2.b) It is clearly stated who last changed the program. The program is renamed\nor the version number is of the form x.y.z, where x.y is the version of the\noriginal program and z is an arbitrary suffix.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing/XSkat_License"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This program is free software; you can redistribute it freely.\nUse it at your own risk; there is NO WARRANTY.\n\nRedistribution of modified versions is permitted provided that the following\nconditions are met:\n\n1. All copyright & permission notices are preserved.\n\n2.a) Only changes required for packaging or porting are made. \nor\n2.b) It is clearly stated who last changed the program. The program is renamed\nor the version number is of the form x.y.z, where x.y is the version of the\noriginal program and z is an arbitrary suffix.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/XSkat.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/XSkat_License"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing/XSkat_License"
        ]
    ]
}
....