== Yahoo! Public License v1.0 (YPL-1.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Yahoo! Public License v1.0
|Shortname |YPL-1.0
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/YPL-1.0.json
* http://www.zimbra.com/license/yahoo_public_license_1.0.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/YPL-1.0.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "YPL-1.0",
        "Yahoo! Public License v1.0"
    ],
    "__impliedId": "YPL-1.0",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "YPL-1.0"
                ],
                "__impliedId": "YPL-1.0"
            },
            "shortname": "YPL-1.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Yahoo! Public License v1.0",
            "spdxDetailsURL": "http://spdx.org/licenses/YPL-1.0.json",
            "_sourceURL": "https://spdx.org/licenses/YPL-1.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://www.zimbra.com/license/yahoo_public_license_1.0.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "YPL-1.0",
                    "Yahoo! Public License v1.0"
                ],
                "__impliedId": "YPL-1.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/YPL-1.0.json"
                    ],
                    [
                        null,
                        "http://www.zimbra.com/license/yahoo_public_license_1.0.html"
                    ]
                ]
            },
            "spdxLicenseId": "YPL-1.0"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "YPL-1.0"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "YPL-1.0",
            "copyleftkind": "WeakCopyleft"
        }
    },
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/YPL-1.0.json"
        ],
        [
            null,
            "http://www.zimbra.com/license/yahoo_public_license_1.0.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/YPL-1.0.svg
