== Zend License v2.0 (Zend-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Zend License v2.0
|Shortname |Zend-2.0
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://zend-2.0+`
* `+Zend Engine License 2.0+`
* `+Zend Engine License, Version 2.00+`
* `+ Zend-2.0+`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``This software Licenses is OK for Fedora'' (source:
https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0]))
* **↓**``Rating is: Lead'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``http://www.zend.com/license/2_00.txt'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))

=== URLs

* *Homepage:*
https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt
* *SPDX:* http://spdx.org/licenses/Zend-2.0.json
* *SPDX:* https://spdx.org/licenses/Zend-2.0.html
* *open-license:* http://open-license.hitachi.com/licenses/837

=== Description from open-license

....
Actions:
- Use the obtained source code without modification (Use the fetched code as it is.)
- Modify the obtained source code.
- Using Modified Source Code
- Use the retrieved binaries (Use the fetched binary as it is.)
- Use binaries generated from modified source code

....

....
Description: Acknowledgements include "This product includes the Zend Engine, freely available at http://www.zend.com"
Actions:
- Distribute the obtained source code without modification (Redistribute the code as it was obtained)
- Distribution of Modified Source Code

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/1", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/1", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/13", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/13", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }


....

....
Description: Acknowledgements include "This product includes the Zend Engine, freely available at http://www.zend.com"
Actions:
- Distribute the fetched binaries (Redistribute the fetched binaries as they are)
- Distribute the generated binaries from modified source code

Conditions:
AND
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/2", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/2", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }
  OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/13", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/13", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }


....

....
Description: "Zend", when using the name "Zend Engine". license@zend.comに連絡する.
Actions:
- Use the name to endorse and promote derived products

Conditions:
OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/3", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/3", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }

....

....
Description: Acknowledgement is here: "The Zend Engine is freely available at http://www.zend.com"
Actions:
- Create an advertising medium that describes the features and use of the software

Conditions:
OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/13", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/13", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }

....

(source: Hitachi open-license)

=== Text

....
-------------------------------------------------------------------- 
                The Zend Engine License, version 2.00
Copyright (c) 1999-2002 Zend Technologies Ltd. All rights reserved.
-------------------------------------------------------------------- 

Redistribution and use in source and binary forms, with or without
modification, is permitted provided that the following conditions
are met:

  1. Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer. 
 
  2. Redistributions in binary form must reproduce the above 
     copyright notice, this list of conditions and the following 
     disclaimer in the documentation and/or other materials provided
     with the distribution.
 
  3. The names "Zend" and "Zend Engine" must not be used to endorse
     or promote products derived from this software without prior
     permission from Zend Technologies Ltd. For written permission,
     please contact license@zend.com. 
 
  4. Zend Technologies Ltd. may publish revised and/or new versions
     of the license from time to time. Each version will be given a
     distinguishing version number.
     Once covered code has been published under a particular version
     of the license, you may always continue to use it under the
     terms of that version. You may also choose to use such covered
     code under the terms of any subsequent version of the license
     published by Zend Technologies Ltd. No one other than Zend
     Technologies Ltd. has the right to modify the terms applicable
     to covered code created under this License.

  5. Redistributions of any form whatsoever must retain the following
     acknowledgment:
     "This product includes the Zend Engine, freely available at
     http://www.zend.com"

  6. All advertising materials mentioning features or use of this
     software must display the following acknowledgment:
     "The Zend Engine is freely available at http://www.zend.com"

THIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND 
ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND
TECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
--------------------------------------------------------------------
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/Zend-2.0.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zend-2.0.yml[Scancode]
(CC0-1.0)
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing[Fedora
Project Wiki]
(https://creativecommons.org/licenses/by-sa/3.0/legalcode[CC-BY-SA-3.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "Zend-2.0",
        "Zend License v2.0",
        "scancode://zend-2.0",
        "Zend Engine License 2.0",
        "Zend Engine License, Version 2.00",
        " Zend-2.0"
    ],
    "__impliedId": "Zend-2.0",
    "__isFsfFree": true,
    "__impliedAmbiguousNames": [
        "Zend"
    ],
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "http://www.zend.com/license/2_00.txt"
            ]
        ]
    ],
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Zend-2.0"
                ],
                "__impliedId": "Zend-2.0"
            },
            "shortname": "Zend-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Zend License v2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/Zend-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/Zend-2.0.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"
            ],
            "_implications": {
                "__impliedNames": [
                    "Zend-2.0",
                    "Zend License v2.0"
                ],
                "__impliedId": "Zend-2.0",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Zend-2.0.json"
                    ],
                    [
                        null,
                        "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"
                    ]
                ]
            },
            "spdxLicenseId": "Zend-2.0"
        },
        "Fedora Project Wiki": {
            "GPLv2 Compat?": "NO",
            "rating": "Good",
            "Upstream URL": "http://www.zend.com/license/2_00.txt",
            "GPLv3 Compat?": null,
            "Short Name": "Zend",
            "licenseType": "license",
            "_sourceURL": "https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing",
            "Full Name": "Zend License v2.0",
            "FSF Free?": "Yes",
            "_implications": {
                "__impliedNames": [
                    "Zend License v2.0"
                ],
                "__isFsfFree": true,
                "__impliedAmbiguousNames": [
                    "Zend"
                ],
                "__impliedJudgement": [
                    [
                        "Fedora Project Wiki",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This software Licenses is OK for Fedora"
                        }
                    ]
                ]
            }
        },
        "Scancode": {
            "otherUrls": null,
            "homepageUrl": "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt",
            "shortName": "Zend Engine License 2.0",
            "textUrls": null,
            "text": "-------------------------------------------------------------------- \n                The Zend Engine License, version 2.00\nCopyright (c) 1999-2002 Zend Technologies Ltd. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer. \n \n  2. Redistributions in binary form must reproduce the above \n     copyright notice, this list of conditions and the following \n     disclaimer in the documentation and/or other materials provided\n     with the distribution.\n \n  3. The names \"Zend\" and \"Zend Engine\" must not be used to endorse\n     or promote products derived from this software without prior\n     permission from Zend Technologies Ltd. For written permission,\n     please contact license@zend.com. \n \n  4. Zend Technologies Ltd. may publish revised and/or new versions\n     of the license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the\n     terms of that version. You may also choose to use such covered\n     code under the terms of any subsequent version of the license\n     published by Zend Technologies Ltd. No one other than Zend\n     Technologies Ltd. has the right to modify the terms applicable\n     to covered code created under this License.\n\n  5. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes the Zend Engine, freely available at\n     http://www.zend.com\"\n\n  6. All advertising materials mentioning features or use of this\n     software must display the following acknowledgment:\n     \"The Zend Engine is freely available at http://www.zend.com\"\n\nTHIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND\nTECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n--------------------------------------------------------------------",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Zend Technologies Ltd.",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zend-2.0.yml",
            "key": "zend-2.0",
            "name": "Zend Engine License 2.0",
            "spdxId": "Zend-2.0",
            "notes": null,
            "_implications": {
                "__impliedNames": [
                    "scancode://zend-2.0",
                    "Zend Engine License 2.0",
                    "Zend-2.0"
                ],
                "__impliedId": "Zend-2.0",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "-------------------------------------------------------------------- \n                The Zend Engine License, version 2.00\nCopyright (c) 1999-2002 Zend Technologies Ltd. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer. \n \n  2. Redistributions in binary form must reproduce the above \n     copyright notice, this list of conditions and the following \n     disclaimer in the documentation and/or other materials provided\n     with the distribution.\n \n  3. The names \"Zend\" and \"Zend Engine\" must not be used to endorse\n     or promote products derived from this software without prior\n     permission from Zend Technologies Ltd. For written permission,\n     please contact license@zend.com. \n \n  4. Zend Technologies Ltd. may publish revised and/or new versions\n     of the license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the\n     terms of that version. You may also choose to use such covered\n     code under the terms of any subsequent version of the license\n     published by Zend Technologies Ltd. No one other than Zend\n     Technologies Ltd. has the right to modify the terms applicable\n     to covered code created under this License.\n\n  5. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes the Zend Engine, freely available at\n     http://www.zend.com\"\n\n  6. All advertising materials mentioning features or use of this\n     software must display the following acknowledgment:\n     \"The Zend Engine is freely available at http://www.zend.com\"\n\nTHIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND\nTECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n--------------------------------------------------------------------",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"
                    ]
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "http://www.zend.com/license/2_00.txt",
            "notices": [
                {
                    "content": "the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of commercial usability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "Neither the copyright owner nor any contributor, for any cause whatsoever, shall be liable for damages, regardless of how caused, and regardless of whether the liability is based on contract, strict liability, or tort (including negligence), even if they have been advised of the possibility of such damages arising from the use of the software, and even if they have been advised of the possibility of such damages. for any direct, indirect, incidental, special, punitive, or consequential damages (including, but not limited to, compensation for procurement of substitute goods or services, loss of use, loss of data, loss of profits, or business interruption). It shall not be defeated."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/837",
            "content": "-------------------------------------------------------------------- \r\n                The Zend Engine License, Version 2.00\r\nCopyright (c) 1999-2006 Zend Technologies Ltd. All rights reserved.\r\n-------------------------------------------------------------------- \r\n\r\nRedistribution and use in source and binary forms, with or without\r\nmodification, is permitted provided that the following conditions\r\nare met:\r\n\r\n  1. Redistributions of source code must retain the above copyright\r\n     notice, this list of conditions and the following disclaimer. \r\n \r\n  2. Redistributions in binary form must reproduce the above \r\n     copyright notice, this list of conditions and the following \r\n     disclaimer in the documentation and/or other materials provided\r\n     with the distribution.\r\n \r\n  3. The names \"Zend\" and \"Zend Engine\" must not be used to endorse\r\n     or promote products derived from this software without prior\r\n     permission from Zend Technologies Ltd. For written permission,\r\n     please contact license@zend.com. \r\n \r\n  4. Zend Technologies Ltd. may publish revised and/or new versions\r\n     of the license from time to time. Each version will be given a\r\n     distinguishing version number.\r\n     Once covered code has been published under a particular version\r\n     of the license, you may always continue to use it under the\r\n     terms of that version. You may also choose to use such covered\r\n     code under the terms of any subsequent version of the license\r\n     published by Zend Technologies Ltd. No one other than Zend\r\n     Technologies Ltd. has the right to modify the terms applicable\r\n     to covered code created under this License.\r\n\r\n  5. Redistributions of any form whatsoever must retain the following\r\n     acknowledgment:\r\n     \"This product includes the Zend Engine, freely available at\r\n     http://www.zend.com\"\r\n\r\n  6. All advertising materials mentioning features or use of this\r\n     software must display the following acknowledgment:\r\n     \"The Zend Engine is freely available at http://www.zend.com\"\r\n\r\nTHIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND \r\nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\r\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \r\nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND\r\nTECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\r\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\r\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\r\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\r\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\r\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\r\nSUCH DAMAGE.\r\n\r\n-------------------------------------------------------------------- ",
            "name": "Zend Engine License, Version 2.00",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Modify the obtained source code."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "Actions:\n- Use the obtained source code without modification (Use the fetched code as it is.)\n- Modify the obtained source code.\n- Using Modified Source Code\n- Use the retrieved binaries (Use the fetched binary as it is.)\n- Use binaries generated from modified source code\n\n",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        },
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "Description: Acknowledgements include \"This product includes the Zend Engine, freely available at http://www.zend.com\"\nActions:\n- Distribute the obtained source code without modification (Redistribute the code as it was obtained)\n- Distribution of Modified Source Code\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes the Zend Engine, freely available at http://www.zend.com\""
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        },
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "Description: Acknowledgements include \"This product includes the Zend Engine, freely available at http://www.zend.com\"\nActions:\n- Distribute the fetched binaries (Redistribute the fetched binaries as they are)\n- Distribute the generated binaries from modified source code\n\nConditions:\nAND\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }\n  OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }\n\n\n",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Acknowledgements",
                                "type": "OBLIGATION"
                            }
                        ]
                    },
                    "description": "Acknowledgements include \"This product includes the Zend Engine, freely available at http://www.zend.com\""
                },
                {
                    "actions": [
                        {
                            "name": "Use the name to endorse and promote derived products"
                        }
                    ],
                    "_str": "Description: \"Zend\", when using the name \"Zend Engine\". license@zend.comã«é£çµ¡ãã.\nActions:\n- Use the name to endorse and promote derived products\n\nConditions:\nOlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }\n\n",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "\"Zend\", when using the name \"Zend Engine\". license@zend.comã«é£çµ¡ãã."
                },
                {
                    "actions": [
                        {
                            "name": "Create an advertising medium that describes the features and use of the software"
                        }
                    ],
                    "_str": "Description: Acknowledgement is here: \"The Zend Engine is freely available at http://www.zend.com\"\nActions:\n- Create an advertising medium that describes the features and use of the software\n\nConditions:\nOlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/13\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/13\", _condition_conditionType = OBLIGATION, _condition_name = Acknowledgements, _condition_description = }\n\n",
                    "conditions": {
                        "name": "Acknowledgements",
                        "type": "OBLIGATION"
                    },
                    "description": "Acknowledgement is here: \"The Zend Engine is freely available at http://www.zend.com\""
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Zend Engine License, Version 2.00",
                    " Zend-2.0"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "http://www.zend.com/license/2_00.txt"
                        ]
                    ]
                ],
                "__impliedText": "-------------------------------------------------------------------- \r\n                The Zend Engine License, Version 2.00\r\nCopyright (c) 1999-2006 Zend Technologies Ltd. All rights reserved.\r\n-------------------------------------------------------------------- \r\n\r\nRedistribution and use in source and binary forms, with or without\r\nmodification, is permitted provided that the following conditions\r\nare met:\r\n\r\n  1. Redistributions of source code must retain the above copyright\r\n     notice, this list of conditions and the following disclaimer. \r\n \r\n  2. Redistributions in binary form must reproduce the above \r\n     copyright notice, this list of conditions and the following \r\n     disclaimer in the documentation and/or other materials provided\r\n     with the distribution.\r\n \r\n  3. The names \"Zend\" and \"Zend Engine\" must not be used to endorse\r\n     or promote products derived from this software without prior\r\n     permission from Zend Technologies Ltd. For written permission,\r\n     please contact license@zend.com. \r\n \r\n  4. Zend Technologies Ltd. may publish revised and/or new versions\r\n     of the license from time to time. Each version will be given a\r\n     distinguishing version number.\r\n     Once covered code has been published under a particular version\r\n     of the license, you may always continue to use it under the\r\n     terms of that version. You may also choose to use such covered\r\n     code under the terms of any subsequent version of the license\r\n     published by Zend Technologies Ltd. No one other than Zend\r\n     Technologies Ltd. has the right to modify the terms applicable\r\n     to covered code created under this License.\r\n\r\n  5. Redistributions of any form whatsoever must retain the following\r\n     acknowledgment:\r\n     \"This product includes the Zend Engine, freely available at\r\n     http://www.zend.com\"\r\n\r\n  6. All advertising materials mentioning features or use of this\r\n     software must display the following acknowledgment:\r\n     \"The Zend Engine is freely available at http://www.zend.com\"\r\n\r\nTHIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND \r\nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\r\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \r\nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND\r\nTECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\r\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\r\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\r\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\r\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\r\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\r\nSUCH DAMAGE.\r\n\r\n-------------------------------------------------------------------- ",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/837"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/Zend-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Zend License v2.0",
            "id": "Zend-2.0",
            "_implications": {
                "__impliedNames": [
                    "Zend-2.0",
                    "Zend License v2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/Zend-2.0.html"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "Zend-2.0",
            "_implications": {
                "__impliedNames": [
                    "Zend-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Fedora Project Wiki",
            {
                "tag": "PositiveJudgement",
                "contents": "This software Licenses is OK for Fedora"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "-------------------------------------------------------------------- \n                The Zend Engine License, version 2.00\nCopyright (c) 1999-2002 Zend Technologies Ltd. All rights reserved.\n-------------------------------------------------------------------- \n\nRedistribution and use in source and binary forms, with or without\nmodification, is permitted provided that the following conditions\nare met:\n\n  1. Redistributions of source code must retain the above copyright\n     notice, this list of conditions and the following disclaimer. \n \n  2. Redistributions in binary form must reproduce the above \n     copyright notice, this list of conditions and the following \n     disclaimer in the documentation and/or other materials provided\n     with the distribution.\n \n  3. The names \"Zend\" and \"Zend Engine\" must not be used to endorse\n     or promote products derived from this software without prior\n     permission from Zend Technologies Ltd. For written permission,\n     please contact license@zend.com. \n \n  4. Zend Technologies Ltd. may publish revised and/or new versions\n     of the license from time to time. Each version will be given a\n     distinguishing version number.\n     Once covered code has been published under a particular version\n     of the license, you may always continue to use it under the\n     terms of that version. You may also choose to use such covered\n     code under the terms of any subsequent version of the license\n     published by Zend Technologies Ltd. No one other than Zend\n     Technologies Ltd. has the right to modify the terms applicable\n     to covered code created under this License.\n\n  5. Redistributions of any form whatsoever must retain the following\n     acknowledgment:\n     \"This product includes the Zend Engine, freely available at\n     http://www.zend.com\"\n\n  6. All advertising materials mentioning features or use of this\n     software must display the following acknowledgment:\n     \"The Zend Engine is freely available at http://www.zend.com\"\n\nTHIS SOFTWARE IS PROVIDED BY ZEND TECHNOLOGIES LTD. ``AS IS'' AND \nANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,\nTHE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A \nPARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ZEND\nTECHNOLOGIES LTD.  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF\nUSE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\nON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\nOR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT\nOF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\nSUCH DAMAGE.\n--------------------------------------------------------------------",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Zend-2.0.json"
        ],
        [
            null,
            "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/Zend-2.0.html"
        ],
        [
            "Homepage",
            "https://web.archive.org/web/20130517195954/http://www.zend.com/license/2_00.txt"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/837"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Zend-2.0.svg