== Zimbra Public License v1.3 (Zimbra-1.3)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Zimbra Public License v1.3
|Shortname |Zimbra-1.3
|Rating |Unknown, probably Attention or Stop or No-Go
|Classification |WeakCopyleft
|===

=== Comments on (easy) usability

=== General Comments

=== URLs

* *SPDX:* http://spdx.org/licenses/Zimbra-1.3.json
* http://web.archive.org/web/20100302225219/http://www.zimbra.com/license/zimbra-public-license-1-3.html

'''''

=== Raw Data

==== Facts

* LicenseName
* https://github.com/HansHammel/license-compatibility-checker/blob/master/lib/licenses.json[HansHammel
license-compatibility-checker]
(https://github.com/HansHammel/license-compatibility-checker/blob/master/LICENSE[MIT])
* https://spdx.org/licenses/Zimbra-1.3.html[SPDX] (all data [in this
repository] is generated)

==== Raw JSON

....
{
    "__impliedNames": [
        "Zimbra-1.3",
        "Zimbra Public License v1.3"
    ],
    "__impliedId": "Zimbra-1.3",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "Zimbra-1.3"
                ],
                "__impliedId": "Zimbra-1.3"
            },
            "shortname": "Zimbra-1.3",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Zimbra Public License v1.3",
            "spdxDetailsURL": "http://spdx.org/licenses/Zimbra-1.3.json",
            "_sourceURL": "https://spdx.org/licenses/Zimbra-1.3.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://web.archive.org/web/20100302225219/http://www.zimbra.com/license/zimbra-public-license-1-3.html"
            ],
            "_implications": {
                "__impliedNames": [
                    "Zimbra-1.3",
                    "Zimbra Public License v1.3"
                ],
                "__impliedId": "Zimbra-1.3",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/Zimbra-1.3.json"
                    ],
                    [
                        null,
                        "http://web.archive.org/web/20100302225219/http://www.zimbra.com/license/zimbra-public-license-1-3.html"
                    ]
                ]
            },
            "spdxLicenseId": "Zimbra-1.3"
        },
        "HansHammel license-compatibility-checker": {
            "implications": {
                "__impliedNames": [
                    "Zimbra-1.3"
                ],
                "__impliedCopyleft": [
                    [
                        "HansHammel license-compatibility-checker",
                        "WeakCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "WeakCopyleft"
            },
            "licensename": "Zimbra-1.3",
            "copyleftkind": "WeakCopyleft"
        }
    },
    "__impliedCopyleft": [
        [
            "HansHammel license-compatibility-checker",
            "WeakCopyleft"
        ]
    ],
    "__calculatedCopyleft": "WeakCopyleft",
    "__isOsiApproved": false,
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/Zimbra-1.3.json"
        ],
        [
            null,
            "http://web.archive.org/web/20100302225219/http://www.zimbra.com/license/zimbra-public-license-1-3.html"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/Zimbra-1.3.svg
