== zlib/libpng License with Acknowledgement (zlib-acknowledgement)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |zlib/libpng License with Acknowledgement
|Shortname |zlib-acknowledgement
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://zlib-acknowledgement+`
* `+ZLIB License with Acknowledgment+`

=== Comments on (easy) usability

* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List])
* **↑**``This license is compatible with the
DebianFreeSoftwareGuidelines (DFSG-free)'' (source:
https://wiki.debian.org/DFSGLicenses[Debian Free Software Guidelines])

=== General Comments

* ``Per Fedora, this license is the same as zlib, except that it
requires that an acknowledgement be made in the product documentation.
For Fedora, this is our Release notes, so if you have any packages which
use this license, you MUST be sure to have the appropriate
acknowledgement in the release notes. '' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zlib-acknowledgement.yml[Scancode])

=== URLs

* *Homepage:*
https://fedoraproject.org/wiki/Licensing:ZlibWithAcknowledgement?rd=Licensing/ZlibWithAcknowledgement
* *SPDX:* http://spdx.org/licenses/zlib-acknowledgement.json
* *SPDX:* https://spdx.org/licenses/zlib-acknowledgement.html
* https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement

=== OSADL Rule

....
USE CASE Source code delivery
	YOU MUST Forward Warranty disclaimer
	YOU MUST Forward License text
	YOU MUST NOT Appropriate
	IF Software modification
		YOU MUST Mark

USE CASE Binary delivery
	YOU MUST NOT Appropriate
	IF Software modification
		YOU MUST Mark

USE CASE Commercial distribution
	YOU MUST Credit Verbatim "Portions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002 Philip A. Craig"
....

(source: OSADL License Checklist)

=== Text

....
This software is provided 'as-is', without any express or implied warranty. In
no event will the authors be held liable for any damages arising from the use of
this software.

Permission is granted to anyone to use this software for any purpose, including
commercial applications, and to alter it and redistribute it freely, subject to
the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim
that you wrote the original software. If you use this software in a product, an
acknowledgment (see the following) in the product documentation is required.

Portions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James
W. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002
Philip A. Craig

2. Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
....

'''''

=== Raw Data

* SPDX
* BlueOak License List
* Scancode
* OSADL License Checklist
* Debian Free Software Guidelines

....
{
    "__impliedNames": [
        "zlib-acknowledgement",
        "zlib/libpng License with Acknowledgement",
        "scancode://zlib-acknowledgement",
        "ZLIB License with Acknowledgment"
    ],
    "__impliedId": "zlib-acknowledgement",
    "__impliedAmbiguousNames": [
        "The zlib/libpng License (Zlib)"
    ],
    "__impliedComments": [
        [
            "Scancode",
            [
                "Per Fedora, this license is the same as zlib, except that it requires that\nan acknowledgement be made in the product documentation. For Fedora, this\nis our Release notes, so if you have any packages which use this license,\nyou MUST be sure to have the appropriate acknowledgement in the release\nnotes.\n"
            ]
        ]
    ],
    "facts": {
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "zlib/libpng License with Acknowledgement",
            "spdxDetailsURL": "http://spdx.org/licenses/zlib-acknowledgement.json",
            "_sourceURL": "https://spdx.org/licenses/zlib-acknowledgement.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"
            ],
            "_implications": {
                "__impliedNames": [
                    "zlib-acknowledgement",
                    "zlib/libpng License with Acknowledgement"
                ],
                "__impliedId": "zlib-acknowledgement",
                "__isOsiApproved": false,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/zlib-acknowledgement.json"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"
                    ]
                ]
            },
            "spdxLicenseId": "zlib-acknowledgement"
        },
        "OSADL License Checklist": {
            "_sourceURL": "https://www.osadl.org/fileadmin/checklists/unreflicenses/zlib-acknowledgement.txt",
            "spdxId": "zlib-acknowledgement",
            "osadlRule": "USE CASE Source code delivery\n\tYOU MUST Forward Warranty disclaimer\n\tYOU MUST Forward License text\n\tYOU MUST NOT Appropriate\n\tIF Software modification\n\t\tYOU MUST Mark\n\r\nUSE CASE Binary delivery\n\tYOU MUST NOT Appropriate\n\tIF Software modification\n\t\tYOU MUST Mark\n\r\nUSE CASE Commercial distribution\n\tYOU MUST Credit Verbatim \"Portions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002 Philip A. Craig\"\n",
            "_implications": {
                "__impliedNames": [
                    "zlib-acknowledgement"
                ]
            }
        },
        "Scancode": {
            "otherUrls": [
                "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"
            ],
            "homepageUrl": "https://fedoraproject.org/wiki/Licensing:ZlibWithAcknowledgement?rd=Licensing/ZlibWithAcknowledgement",
            "shortName": "ZLIB License with Acknowledgment",
            "textUrls": null,
            "text": "This software is provided 'as-is', without any express or implied warranty. In\nno event will the authors be held liable for any damages arising from the use of\nthis software.\n\nPermission is granted to anyone to use this software for any purpose, including\ncommercial applications, and to alter it and redistribute it freely, subject to\nthe following restrictions:\n\n1. The origin of this software must not be misrepresented; you must not claim\nthat you wrote the original software. If you use this software in a product, an\nacknowledgment (see the following) in the product documentation is required.\n\nPortions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James\nW. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002\nPhilip A. Craig\n\n2. Altered source versions must be plainly marked as such, and must not be\nmisrepresented as being the original software.\n\n3. This notice may not be removed or altered from any source distribution.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Charlie Poole",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zlib-acknowledgement.yml",
            "key": "zlib-acknowledgement",
            "name": "ZLIB License with Acknowledgment",
            "spdxId": "zlib-acknowledgement",
            "notes": "Per Fedora, this license is the same as zlib, except that it requires that\nan acknowledgement be made in the product documentation. For Fedora, this\nis our Release notes, so if you have any packages which use this license,\nyou MUST be sure to have the appropriate acknowledgement in the release\nnotes.\n",
            "_implications": {
                "__impliedNames": [
                    "scancode://zlib-acknowledgement",
                    "ZLIB License with Acknowledgment",
                    "zlib-acknowledgement"
                ],
                "__impliedId": "zlib-acknowledgement",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per Fedora, this license is the same as zlib, except that it requires that\nan acknowledgement be made in the product documentation. For Fedora, this\nis our Release notes, so if you have any packages which use this license,\nyou MUST be sure to have the appropriate acknowledgement in the release\nnotes.\n"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This software is provided 'as-is', without any express or implied warranty. In\nno event will the authors be held liable for any damages arising from the use of\nthis software.\n\nPermission is granted to anyone to use this software for any purpose, including\ncommercial applications, and to alter it and redistribute it freely, subject to\nthe following restrictions:\n\n1. The origin of this software must not be misrepresented; you must not claim\nthat you wrote the original software. If you use this software in a product, an\nacknowledgment (see the following) in the product documentation is required.\n\nPortions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James\nW. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002\nPhilip A. Craig\n\n2. Altered source versions must be plainly marked as such, and must not be\nmisrepresented as being the original software.\n\n3. This notice may not be removed or altered from any source distribution.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "https://fedoraproject.org/wiki/Licensing:ZlibWithAcknowledgement?rd=Licensing/ZlibWithAcknowledgement"
                    ],
                    [
                        null,
                        "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"
                    ]
                ]
            }
        },
        "Debian Free Software Guidelines": {
            "LicenseName": "The zlib/libpng License (Zlib)",
            "State": "DFSGCompatible",
            "_sourceURL": "https://wiki.debian.org/DFSGLicenses",
            "_implications": {
                "__impliedNames": [
                    "zlib-acknowledgement"
                ],
                "__impliedAmbiguousNames": [
                    "The zlib/libpng License (Zlib)"
                ],
                "__impliedJudgement": [
                    [
                        "Debian Free Software Guidelines",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
                        }
                    ]
                ]
            },
            "Comment": null,
            "LicenseId": "zlib-acknowledgement"
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/zlib-acknowledgement.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "zlib/libpng License with Acknowledgement",
            "id": "zlib-acknowledgement",
            "_implications": {
                "__impliedNames": [
                    "zlib-acknowledgement",
                    "zlib/libpng License with Acknowledgement"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/zlib-acknowledgement.html"
                    ]
                ]
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Debian Free Software Guidelines",
            {
                "tag": "PositiveJudgement",
                "contents": "This license is compatible with the DebianFreeSoftwareGuidelines (DFSG-free)"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": false,
    "__impliedText": "This software is provided 'as-is', without any express or implied warranty. In\nno event will the authors be held liable for any damages arising from the use of\nthis software.\n\nPermission is granted to anyone to use this software for any purpose, including\ncommercial applications, and to alter it and redistribute it freely, subject to\nthe following restrictions:\n\n1. The origin of this software must not be misrepresented; you must not claim\nthat you wrote the original software. If you use this software in a product, an\nacknowledgment (see the following) in the product documentation is required.\n\nPortions Copyright (c) 2002-2007 Charlie Poole or Copyright (c) 2002-2004 James\nW. Newkirk, Michael C. Two, Alexei A. Vorontsov or Copyright (c) 2000-2002\nPhilip A. Craig\n\n2. Altered source versions must be plainly marked as such, and must not be\nmisrepresented as being the original software.\n\n3. This notice may not be removed or altered from any source distribution.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/zlib-acknowledgement.json"
        ],
        [
            null,
            "https://fedoraproject.org/wiki/Licensing/ZlibWithAcknowledgement"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/zlib-acknowledgement.html"
        ],
        [
            "Homepage",
            "https://fedoraproject.org/wiki/Licensing:ZlibWithAcknowledgement?rd=Licensing/ZlibWithAcknowledgement"
        ]
    ]
}
....

'''''

=== Dot Cluster Graph

image:../dot/zlib-acknowledgement.svg[image,title="dot"]