== Zope Public License 1.1 (ZPL-1.1)

[cols=",",options="header",]
|=======================================
|Key |Value
|Fullname |Zope Public License 1.1
|Shortname |ZPL-1.1
|Rating |Unknown, probably Stop or No-Go
|Classification |NoCopyleft
|=======================================

*Other Names:*

* `ZPL 1.1`

=== Comments on (easy) usability

* **↑**Google Classification is NOTICE (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])
* **↓**Rating is: Lead (source: https://blueoakcouncil.org/list[BlueOak
License List])

=== URLs

* *Homepage:* http://www.zope.org/Resources/License/
* *SPDX:* http://spdx.org/licenses/ZPL-1.1.json
* *SPDX:* https://spdx.org/licenses/ZPL-1.1.html
* http://old.zope.org/Resources/License/ZPL-1.1
* http://www.zope.com/

=== Text

....
Zope Public License (ZPL) Version 1.1

Copyright (c) Zope Corporation. All rights reserved.

This license has been certified as open source.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions in source code must retain the above copyright notice,
   this list of conditions, and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions, and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

   3. All advertising materials and documentation mentioning features derived
   from or use of this software must display the following acknowledgement:

      "This product includes software developed by Zope Corporation for use in
       the Z Object Publishing Environment (http://www.zope.com/)."

      In the event that the product being advertised includes an intact Zope
      distribution (with copyright and license included) then this clause is
      waived.

   4. Names associated with Zope or Zope Corporation must not be used to endorse
   or promote products derived from this software without prior written
   permission from Zope Corporation.

   5. Modified redistributions of any form whatsoever must retain the following
   acknowledgment:

      "This product includes software developed by Zope Corporation for use in
      the Z Object Publishing Environment (http://www.zope.com/)."

      Intact (re-)distributions of any official Zope release do not require an
      external acknowledgement.

   6. Modifications are encouraged but must be packaged separately as patches to
   official Zope releases. Distributions that do not clearly separate the
   patches from the original work must be clearly labeled as unofficial
   distributions. Modifications which do not carry the name Zope may be packaged
   in any form, as long as they conform to all of the clauses above.

Disclaimer

THIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This software consists of contributions made by Zope Corporation and many
individuals on behalf of Zope Corporation. Specific attributions are listed in
the accompanying credits file.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "ZPL-1.1",
        "Zope Public License 1.1",
        "zpl-1.1",
        "ZPL 1.1"
    ],
    "__impliedId": "ZPL-1.1",
    "facts": {
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ZPL-1.1",
                    "ZPL-1.1",
                    "Zope Public License 1.1",
                    "zpl-1.1",
                    "ZPL 1.1"
                ],
                "__impliedId": "ZPL-1.1"
            },
            "shortname": "ZPL-1.1",
            "otherNames": [
                "ZPL-1.1",
                "Zope Public License 1.1",
                "zpl-1.1",
                "ZPL 1.1"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Zope Public License 1.1",
            "spdxDetailsURL": "http://spdx.org/licenses/ZPL-1.1.json",
            "_sourceURL": "https://spdx.org/licenses/ZPL-1.1.html",
            "spdxLicIsOSIApproved": false,
            "spdxSeeAlso": [
                "http://old.zope.org/Resources/License/ZPL-1.1"
            ],
            "_implications": {
                "__impliedNames": [
                    "ZPL-1.1",
                    "Zope Public License 1.1"
                ],
                "__impliedId": "ZPL-1.1",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ZPL-1.1.json"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-1.1"
                    ]
                ]
            },
            "spdxLicenseId": "ZPL-1.1"
        },
        "Scancode": {
            "otherUrls": [
                "http://old.zope.org/Resources/License/ZPL-1.1",
                "http://www.zope.com/"
            ],
            "homepageUrl": "http://www.zope.org/Resources/License/",
            "shortName": "ZPL 1.1",
            "textUrls": null,
            "text": "Zope Public License (ZPL) Version 1.1\n\nCopyright (c) Zope Corporation. All rights reserved.\n\nThis license has been certified as open source.\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. All advertising materials and documentation mentioning features derived\n   from or use of this software must display the following acknowledgement:\n\n      \"This product includes software developed by Zope Corporation for use in\n       the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      In the event that the product being advertised includes an intact Zope\n      distribution (with copyright and license included) then this clause is\n      waived.\n\n   4. Names associated with Zope or Zope Corporation must not be used to endorse\n   or promote products derived from this software without prior written\n   permission from Zope Corporation.\n\n   5. Modified redistributions of any form whatsoever must retain the following\n   acknowledgment:\n\n      \"This product includes software developed by Zope Corporation for use in\n      the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      Intact (re-)distributions of any official Zope release do not require an\n      external acknowledgement.\n\n   6. Modifications are encouraged but must be packaged separately as patches to\n   official Zope releases. Distributions that do not clearly separate the\n   patches from the original work must be clearly labeled as unofficial\n   distributions. Modifications which do not carry the name Zope may be packaged\n   in any form, as long as they conform to all of the clauses above.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Zope Community",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zpl-1.1.yml",
            "key": "zpl-1.1",
            "name": "Zope Public License 1.1",
            "spdxId": "ZPL-1.1",
            "_implications": {
                "__impliedNames": [
                    "zpl-1.1",
                    "ZPL 1.1",
                    "ZPL-1.1"
                ],
                "__impliedId": "ZPL-1.1",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "Zope Public License (ZPL) Version 1.1\n\nCopyright (c) Zope Corporation. All rights reserved.\n\nThis license has been certified as open source.\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. All advertising materials and documentation mentioning features derived\n   from or use of this software must display the following acknowledgement:\n\n      \"This product includes software developed by Zope Corporation for use in\n       the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      In the event that the product being advertised includes an intact Zope\n      distribution (with copyright and license included) then this clause is\n      waived.\n\n   4. Names associated with Zope or Zope Corporation must not be used to endorse\n   or promote products derived from this software without prior written\n   permission from Zope Corporation.\n\n   5. Modified redistributions of any form whatsoever must retain the following\n   acknowledgment:\n\n      \"This product includes software developed by Zope Corporation for use in\n      the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      Intact (re-)distributions of any official Zope release do not require an\n      external acknowledgement.\n\n   6. Modifications are encouraged but must be packaged separately as patches to\n   official Zope releases. Distributions that do not clearly separate the\n   patches from the original work must be clearly labeled as unofficial\n   distributions. Modifications which do not carry the name Zope may be packaged\n   in any form, as long as they conform to all of the clauses above.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.zope.org/Resources/License/"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-1.1"
                    ],
                    [
                        null,
                        "http://www.zope.com/"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Lead",
            "url": "https://spdx.org/licenses/ZPL-1.1.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Zope Public License 1.1",
            "id": "ZPL-1.1",
            "_implications": {
                "__impliedNames": [
                    "ZPL-1.1"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "NegativeJudgement",
                            "contents": "Rating is: Lead"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ZPL-1.1.html"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "ZPL-1.1",
            "_implications": {
                "__impliedNames": [
                    "ZPL-1.1"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "NegativeJudgement",
                "contents": "Rating is: Lead"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "Zope Public License (ZPL) Version 1.1\n\nCopyright (c) Zope Corporation. All rights reserved.\n\nThis license has been certified as open source.\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. All advertising materials and documentation mentioning features derived\n   from or use of this software must display the following acknowledgement:\n\n      \"This product includes software developed by Zope Corporation for use in\n       the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      In the event that the product being advertised includes an intact Zope\n      distribution (with copyright and license included) then this clause is\n      waived.\n\n   4. Names associated with Zope or Zope Corporation must not be used to endorse\n   or promote products derived from this software without prior written\n   permission from Zope Corporation.\n\n   5. Modified redistributions of any form whatsoever must retain the following\n   acknowledgment:\n\n      \"This product includes software developed by Zope Corporation for use in\n      the Z Object Publishing Environment (http://www.zope.com/).\"\n\n      Intact (re-)distributions of any official Zope release do not require an\n      external acknowledgement.\n\n   6. Modifications are encouraged but must be packaged separately as patches to\n   official Zope releases. Distributions that do not clearly separate the\n   patches from the original work must be clearly labeled as unofficial\n   distributions. Modifications which do not carry the name Zope may be packaged\n   in any form, as long as they conform to all of the clauses above.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ZPL-1.1.json"
        ],
        [
            null,
            "http://old.zope.org/Resources/License/ZPL-1.1"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ZPL-1.1.html"
        ],
        [
            "Homepage",
            "http://www.zope.org/Resources/License/"
        ],
        [
            null,
            "http://www.zope.com/"
        ]
    ]
}
....