== Zope Public License 2.0 (ZPL-2.0)

[cols=",",options="header",]
|===
|Key |Value
|Fullname |Zope Public License 2.0
|Shortname |ZPL-2.0
|Rating |Go
|Classification |NoCopyleft
|===

*Other Names:*

* `+scancode://zpl-2.0+`
* `+ZPL 2.0+`
* `+The Zope Public License, Version 2.0+`
* `+Zope-2.0+`
* `+License :: OSI Approved :: Zope Public License+`
* `+Zope Public License (ZPL) Version 2.0+`

=== Comments on (easy) usability

* **↑**``Google Classification is NOTICE'' (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0]))
* **↑**``Is OSI Approved'' (source:
https://spdx.org/licenses/ZPL-2.0.html[SPDX] (all data [in this
repository] is generated))
* **↑**``Rating is: Bronze'' (source:
https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0]))

=== General Comments

* ``https://opensource.org/licenses/ZPL-2.0'' (source:
https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0))
* ``Per SPDX.org, this license is OSI certified'' (source:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zpl-2.0.yml[Scancode]
(CC0-1.0))

=== URLs

* *Homepage:* http://www.zope.org/Resources/License/
* *OSI Page:* https://opensource.org/licenses/ZPL-2.0
* *SPDX:* http://spdx.org/licenses/ZPL-2.0.json
* *SPDX:* https://spdx.org/licenses/ZPL-2.0.html
* *open-license:* http://open-license.hitachi.com/licenses/825
* http://old.zope.org/Resources/License/ZPL-2.0
* http://www.zope.com/Marks

=== Description from open-license

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/1", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/1", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/4", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/4", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/6", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/6", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/8", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/8", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing}
....

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/9", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/9", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/1", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/1", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }))}
....

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/11", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/11", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/2", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/2", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }))}
....

....
OlPermission {_permission_summary = , _permission_description = "If you use the name "Zope Corporation (tm)". get permission from Zope Corporation., _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/29", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/29", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/3", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/3", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}
....

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/3", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/3", _action_name = Modify the obtained source code., _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/40", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/40", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = }))}
....

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/12", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/12", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/1", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/1", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/40", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/40", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])}
....

....
OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = "0.1", _action_uri = "http://open-license.hitachi.com/actions/14", _action_baseUri = "http://open-license.hitachi.com/", _action_id = "actions/14", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/2", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/2", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = "0.1", _condition_uri = "http://open-license.hitachi.com/conditions/40", _condition_baseUri = "http://open-license.hitachi.com/", _condition_id = "conditions/40", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])}
....

(source: Hitachi open-license)

=== Text

....
This license has been certified as open source. It has also been designated as
GPL compatible by the Free Software Foundation (FSF).

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions in source code must retain the above copyright notice,
   this list of conditions, and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions, and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

   3. The name Zope Corporation (tm) must not be used to endorse or promote
   products derived from this software without prior written permission from
   Zope Corporation.

   4. The right to distribute this software or to use it for any purpose does
   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope
   Corporation. Use of them is covered in a separate agreement (see
   http://www.zope.com/Marks).

   5. If any files are modified, you must cause the modified files to carry
   prominent notices stating that you changed the files and the date of any
   change.

Disclaimer

THIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This software consists of contributions made by Zope Corporation and many
individuals on behalf of Zope Corporation. Specific attributions are listed in
the accompanying credits file.
....

'''''

=== Raw Data

==== Facts

* LicenseName
* https://spdx.org/licenses/ZPL-2.0.html[SPDX] (all data [in this
repository] is generated)
* https://blueoakcouncil.org/list[BlueOak License List]
(https://raw.githubusercontent.com/blueoakcouncil/blue-oak-list-npm-package/master/LICENSE[CC0-1.0])
* https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods[OpenChainPolicyTemplate]
(CC0-1.0)
* https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zpl-2.0.yml[Scancode]
(CC0-1.0)
* https://opensource.org/licenses/[OpenSourceInitiative]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy]
(https://creativecommons.org/licenses/by/4.0/legalcode[CC-BY-4.0])
* https://github.com/okfn/licenses/blob/master/licenses.csv[Open
Knowledge International]
(https://opendatacommons.org/licenses/pddl/1-0/[PDDL-1.0])
* https://github.com/Hitachi/open-license[Hitachi open-license]
(CDLA-Permissive-1.0)

==== Raw JSON

....
{
    "__impliedNames": [
        "ZPL-2.0",
        "Zope Public License 2.0",
        "scancode://zpl-2.0",
        "ZPL 2.0",
        "The Zope Public License, Version 2.0",
        "Zope-2.0",
        "License :: OSI Approved :: Zope Public License",
        "Zope Public License (ZPL) Version 2.0"
    ],
    "__impliedId": "ZPL-2.0",
    "__impliedComments": [
        [
            "Hitachi open-license",
            [
                "https://opensource.org/licenses/ZPL-2.0"
            ]
        ],
        [
            "Scancode",
            [
                "Per SPDX.org, this license is OSI certified"
            ]
        ]
    ],
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "legacy_ids": [],
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/ZPL-2.0",
            "maintainer": "Zope Foundation",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "ZPL-2.0",
            "title": "Zope Public License 2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "Zope Public License 2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ],
                "__impliedId": "ZPL-2.0"
            },
            "shortname": "ZPL-2.0",
            "otherNames": []
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Zope Public License 2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/ZPL-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/ZPL-2.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://old.zope.org/Resources/License/ZPL-2.0",
                "https://opensource.org/licenses/ZPL-2.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "Zope Public License 2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__isOsiApproved": true,
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ZPL-2.0.json"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-2.0"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            },
            "spdxLicenseId": "ZPL-2.0"
        },
        "Scancode": {
            "otherUrls": [
                "http://old.zope.org/Resources/License/ZPL-2.0",
                "http://opensource.org/licenses/ZPL-2.0",
                "http://www.zope.com/Marks",
                "https://opensource.org/licenses/ZPL-2.0"
            ],
            "homepageUrl": "http://www.zope.org/Resources/License/",
            "shortName": "ZPL 2.0",
            "textUrls": null,
            "text": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Zope Community",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zpl-2.0.yml",
            "key": "zpl-2.0",
            "name": "Zope Public License 2.0",
            "spdxId": "ZPL-2.0",
            "notes": "Per SPDX.org, this license is OSI certified",
            "_implications": {
                "__impliedNames": [
                    "scancode://zpl-2.0",
                    "ZPL 2.0",
                    "ZPL-2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedComments": [
                    [
                        "Scancode",
                        [
                            "Per SPDX.org, this license is OSI certified"
                        ]
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.zope.org/Resources/License/"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-2.0"
                    ],
                    [
                        null,
                        "http://opensource.org/licenses/ZPL-2.0"
                    ],
                    [
                        null,
                        "http://www.zope.com/Marks"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Zope Public License 2.0 ",
            "commercialUse": true,
            "spdxId": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ]
            }
        },
        "Hitachi open-license": {
            "summary": "https://opensource.org/licenses/ZPL-2.0",
            "permissionsStr": "[OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/1\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/1\", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/4\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/4\", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/6\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/6\", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/8\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/8\", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing},OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/9\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/9\", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }))},OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/11\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/11\", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }))},OlPermission {_permission_summary = , _permission_description = \"If you use the name \"Zope Corporation (tm)\". get permission from Zope Corporation., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/29\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/29\", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))},OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/3\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/3\", _action_name = Modify the obtained source code., _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = }))},OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/12\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/12\", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])},OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/14\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/14\", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])}]",
            "notices": [
                {
                    "content": "To use Zope Corporation's service marks and trademarks, please visit http://www.zope.com/Marksã«ããå¥ã®å¥ç´æ¸ãé©ç¨ããã."
                },
                {
                    "content": "the software is provided \"as-is\" and without warranty of any kind, either express or implied, including, but not limited to, the implied warranties of commercial usability and fitness for a particular purpose. The warranties include, but are not limited to, the implied warranties of commercial applicability and fitness for a particular purpose.",
                    "description": "There is no guarantee."
                },
                {
                    "content": "Neither the copyright owner nor any contributor, for any cause whatsoever, shall be liable for damages, regardless of how caused, and regardless of whether the liability is based on contract, strict liability, or tort (including negligence), even if they have been advised of the possibility of such damages arising from the use of the software, and even if they have been advised of the possibility of such damages. for any direct, indirect, incidental, special, punitive, or consequential damages (including, but not limited to, compensation for procurement of substitute goods or services, loss of use, loss of data, loss of profits, or business interruption). It shall not be defeated."
                }
            ],
            "_sourceURL": "http://open-license.hitachi.com/licenses/825",
            "content": "Zope Public License (ZPL) Version 2.0\r\n-----------------------------------------------\r\n\r\nThis software is Copyright (c) Zope Corporation (tm) and\r\nContributors. All rights reserved.\r\n\r\nThis license has been certified as open source. It has also\r\nbeen designated as GPL compatible by the Free Software\r\nFoundation (FSF).\r\n\r\nRedistribution and use in source and binary forms, with or\r\nwithout modification, are permitted provided that the\r\nfollowing conditions are met:\r\n\r\n1. Redistributions in source code must retain the above\r\n   copyright notice, this list of conditions, and the following\r\n   disclaimer.\r\n\r\n2. Redistributions in binary form must reproduce the above\r\n   copyright notice, this list of conditions, and the following\r\n   disclaimer in the documentation and/or other materials\r\n   provided with the distribution.\r\n\r\n3. The name Zope Corporation (tm) must not be used to\r\n   endorse or promote products derived from this software\r\n   without prior written permission from Zope Corporation.\r\n\r\n4. The right to distribute this software or to use it for\r\n   any purpose does not give you the right to use Servicemarks\r\n   (sm) or Trademarks (tm) of Zope Corporation. Use of them is\r\n   covered in a separate agreement (see\r\n   http://www.zope.com/Marks).\r\n\r\n5. If any files are modified, you must cause the modified\r\n   files to carry prominent notices stating that you changed\r\n   the files and the date of any change.\r\n\r\nDisclaimer\r\n\r\n  THIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS''\r\n  AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT\r\n  NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\r\n  AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN\r\n  NO EVENT SHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE\r\n  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\r\n  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\n  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\r\n  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\n  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\r\n  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\r\n  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\r\n  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH\r\n  DAMAGE.\r\n\r\n\r\nThis software consists of contributions made by Zope\r\nCorporation and many individuals on behalf of Zope\r\nCorporation.  Specific attributions are listed in the\r\naccompanying credits file.",
            "name": "Zope Public License (ZPL) Version 2.0",
            "permissions": [
                {
                    "actions": [
                        {
                            "name": "Use the obtained source code without modification",
                            "description": "Use the fetched code as it is."
                        },
                        {
                            "name": "Using Modified Source Code"
                        },
                        {
                            "name": "Use the retrieved binaries",
                            "description": "Use the fetched binary as it is."
                        },
                        {
                            "name": "Use binaries generated from modified source code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/1\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/1\", _action_name = Use the obtained source code without modification, _action_description = Use the fetched code as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/4\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/4\", _action_name = Using Modified Source Code, _action_description = },OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/6\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/6\", _action_name = Use the retrieved binaries, _action_description = Use the fetched binary as it is.},OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/8\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/8\", _action_name = Use binaries generated from modified source code, _action_description = }], _permission_conditionHead = Nothing}",
                    "conditions": null
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the obtained source code without modification",
                            "description": "Redistribute the code as it was obtained"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/9\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/9\", _action_name = Distribute the obtained source code without modification, _action_description = Redistribute the code as it was obtained}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }))}",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the fetched binaries",
                            "description": "Redistribute the fetched binaries as they are"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/11\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/11\", _action_name = Distribute the fetched binaries, _action_description = Redistribute the fetched binaries as they are}], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }))}",
                    "conditions": {
                        "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Use the name to endorse and promote derived products"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = \"If you use the name \"Zope Corporation (tm)\". get permission from Zope Corporation., _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/29\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/29\", _action_name = Use the name to endorse and promote derived products, _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/3\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/3\", _condition_conditionType = REQUISITE, _condition_name = Get special permission in writing., _condition_description = }))}",
                    "conditions": {
                        "name": "Get special permission in writing.",
                        "type": "REQUISITE"
                    },
                    "description": "\"If you use the name \"Zope Corporation (tm)\". get permission from Zope Corporation."
                },
                {
                    "actions": [
                        {
                            "name": "Modify the obtained source code."
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/3\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/3\", _action_name = Modify the obtained source code., _action_description = }], _permission_conditionHead = Just (OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = }))}",
                    "conditions": {
                        "name": "Indicate your changes and the date of your changes in the file where you made them.",
                        "type": "OBLIGATION"
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribution of Modified Source Code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/12\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/12\", _action_name = Distribution of Modified Source Code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/1\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/1\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])}",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Indicate your changes and the date of your changes in the file where you made them.",
                                "type": "OBLIGATION"
                            }
                        ]
                    }
                },
                {
                    "actions": [
                        {
                            "name": "Distribute the generated binaries from modified source code"
                        }
                    ],
                    "_str": "OlPermission {_permission_summary = , _permission_description = , _permission_actions = [OlAction {_action_schemaVersion = \"0.1\", _action_uri = \"http://open-license.hitachi.com/actions/14\", _action_baseUri = \"http://open-license.hitachi.com/\", _action_id = \"actions/14\", _action_name = Distribute the generated binaries from modified source code, _action_description = }], _permission_conditionHead = Just (OlConditionTreeAnd [OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/2\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/2\", _condition_conditionType = OBLIGATION, _condition_name = Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license, _condition_description = }),OlConditionTreeLeaf (OlCondition {_condition_schemaVersion = \"0.1\", _condition_uri = \"http://open-license.hitachi.com/conditions/40\", _condition_baseUri = \"http://open-license.hitachi.com/\", _condition_id = \"conditions/40\", _condition_conditionType = OBLIGATION, _condition_name = Indicate your changes and the date of your changes in the file where you made them., _condition_description = })])}",
                    "conditions": {
                        "AND": [
                            {
                                "name": "Include a copyright notice, list of terms and conditions, and disclaimer in the materials accompanying the distribution, which are included in the license",
                                "type": "OBLIGATION"
                            },
                            {
                                "name": "Indicate your changes and the date of your changes in the file where you made them.",
                                "type": "OBLIGATION"
                            }
                        ]
                    }
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "Zope Public License (ZPL) Version 2.0",
                    "ZPL-2.0"
                ],
                "__impliedComments": [
                    [
                        "Hitachi open-license",
                        [
                            "https://opensource.org/licenses/ZPL-2.0"
                        ]
                    ]
                ],
                "__impliedText": "Zope Public License (ZPL) Version 2.0\r\n-----------------------------------------------\r\n\r\nThis software is Copyright (c) Zope Corporation (tm) and\r\nContributors. All rights reserved.\r\n\r\nThis license has been certified as open source. It has also\r\nbeen designated as GPL compatible by the Free Software\r\nFoundation (FSF).\r\n\r\nRedistribution and use in source and binary forms, with or\r\nwithout modification, are permitted provided that the\r\nfollowing conditions are met:\r\n\r\n1. Redistributions in source code must retain the above\r\n   copyright notice, this list of conditions, and the following\r\n   disclaimer.\r\n\r\n2. Redistributions in binary form must reproduce the above\r\n   copyright notice, this list of conditions, and the following\r\n   disclaimer in the documentation and/or other materials\r\n   provided with the distribution.\r\n\r\n3. The name Zope Corporation (tm) must not be used to\r\n   endorse or promote products derived from this software\r\n   without prior written permission from Zope Corporation.\r\n\r\n4. The right to distribute this software or to use it for\r\n   any purpose does not give you the right to use Servicemarks\r\n   (sm) or Trademarks (tm) of Zope Corporation. Use of them is\r\n   covered in a separate agreement (see\r\n   http://www.zope.com/Marks).\r\n\r\n5. If any files are modified, you must cause the modified\r\n   files to carry prominent notices stating that you changed\r\n   the files and the date of any change.\r\n\r\nDisclaimer\r\n\r\n  THIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS''\r\n  AND ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT\r\n  NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY\r\n  AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN\r\n  NO EVENT SHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE\r\n  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\r\n  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\r\n  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\r\n  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\r\n  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\r\n  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\r\n  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\r\n  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH\r\n  DAMAGE.\r\n\r\n\r\nThis software consists of contributions made by Zope\r\nCorporation and many individuals on behalf of Zope\r\nCorporation.  Specific attributions are listed in the\r\naccompanying credits file.",
                "__impliedURLs": [
                    [
                        "open-license",
                        "http://open-license.hitachi.com/licenses/825"
                    ]
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/ZPL-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Zope Public License 2.0",
            "id": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "Zope Public License 2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ZPL-2.0.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/ZPL-2.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "Zope-2.0",
                    "scheme": "DEP5"
                },
                {
                    "identifier": "ZPL-2.0",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Zope Public License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The Zope Public License, Version 2.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "ZPL-2.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/ZPL-2.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "The Zope Public License, Version 2.0",
                    "Zope-2.0",
                    "ZPL-2.0",
                    "License :: OSI Approved :: Zope Public License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__isOsiApproved": true,
    "__impliedText": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ZPL-2.0.json"
        ],
        [
            null,
            "http://old.zope.org/Resources/License/ZPL-2.0"
        ],
        [
            null,
            "https://opensource.org/licenses/ZPL-2.0"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ZPL-2.0.html"
        ],
        [
            "Homepage",
            "http://www.zope.org/Resources/License/"
        ],
        [
            null,
            "http://opensource.org/licenses/ZPL-2.0"
        ],
        [
            null,
            "http://www.zope.com/Marks"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/ZPL-2.0"
        ],
        [
            "open-license",
            "http://open-license.hitachi.com/licenses/825"
        ]
    ]
}
....

==== Dot Cluster Graph

../dot/ZPL-2.0.svg