== Zope Public License 2.0 (ZPL-2.0)

[cols=",",options="header",]
|=================================
|Key |Value
|Fullname |Zope Public License 2.0
|Shortname |ZPL-2.0
|Rating |Go
|Classification |NoCopyleft
|=================================

*Other Names:*

* `ZPL 2.0`
* `The Zope Public License, Version 2.0`
* `Zope-2.0`
* `License :: OSI Approved :: Zope Public License`

=== Comments on (easy) usability

* **↑**Google Classification is NOTICE (source:
https://opensource.google.com/docs/thirdparty/licenses/[Google OSS
Policy])
* **↑**Is OSI Approved (source:
https://spdx.org/licenses/ZPL-2.0.html[SPDX])
* **↑**Rating is: Bronze (source:
https://blueoakcouncil.org/list[BlueOak License List])

=== URLs

* *Homepage:* http://www.zope.org/Resources/License/
* *OSI Page:* https://opensource.org/licenses/ZPL-2.0
* *SPDX:* http://spdx.org/licenses/ZPL-2.0.json
* *SPDX:* https://spdx.org/licenses/ZPL-2.0.html
* http://old.zope.org/Resources/License/ZPL-2.0
* http://www.zope.com/Marks

=== Text

....
This license has been certified as open source. It has also been designated as
GPL compatible by the Free Software Foundation (FSF).

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

   1. Redistributions in source code must retain the above copyright notice,
   this list of conditions, and the following disclaimer.

   2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions, and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

   3. The name Zope Corporation (tm) must not be used to endorse or promote
   products derived from this software without prior written permission from
   Zope Corporation.

   4. The right to distribute this software or to use it for any purpose does
   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope
   Corporation. Use of them is covered in a separate agreement (see
   http://www.zope.com/Marks).

   5. If any files are modified, you must cause the modified files to carry
   prominent notices stating that you changed the files and the date of any
   change.

Disclaimer

THIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This software consists of contributions made by Zope Corporation and many
individuals on behalf of Zope Corporation. Specific attributions are listed in
the accompanying credits file.
....

'''''

=== Raw Data

....
{
    "__impliedNames": [
        "ZPL-2.0",
        "Zope Public License 2.0",
        "zpl-2.0",
        "ZPL 2.0",
        "The Zope Public License, Version 2.0",
        "Zope-2.0",
        "License :: OSI Approved :: Zope Public License"
    ],
    "__impliedId": "ZPL-2.0",
    "facts": {
        "Open Knowledge International": {
            "is_generic": null,
            "status": "active",
            "domain_software": true,
            "url": "https://opensource.org/licenses/ZPL-2.0",
            "maintainer": "Zope Foundation",
            "od_conformance": "not reviewed",
            "_sourceURL": "https://github.com/okfn/licenses/blob/master/licenses.csv",
            "domain_data": false,
            "osd_conformance": "approved",
            "id": "ZPL-2.0",
            "title": "Zope Public License 2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "Zope Public License 2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedURLs": [
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            },
            "domain_content": false
        },
        "LicenseName": {
            "implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "ZPL-2.0",
                    "Zope Public License 2.0",
                    "zpl-2.0",
                    "ZPL 2.0",
                    "The Zope Public License, Version 2.0",
                    "Zope-2.0",
                    "License :: OSI Approved :: Zope Public License"
                ],
                "__impliedId": "ZPL-2.0"
            },
            "shortname": "ZPL-2.0",
            "otherNames": [
                "ZPL-2.0",
                "Zope Public License 2.0",
                "zpl-2.0",
                "ZPL 2.0",
                "The Zope Public License, Version 2.0",
                "Zope-2.0",
                "License :: OSI Approved :: Zope Public License"
            ]
        },
        "SPDX": {
            "isSPDXLicenseDeprecated": false,
            "spdxFullName": "Zope Public License 2.0",
            "spdxDetailsURL": "http://spdx.org/licenses/ZPL-2.0.json",
            "_sourceURL": "https://spdx.org/licenses/ZPL-2.0.html",
            "spdxLicIsOSIApproved": true,
            "spdxSeeAlso": [
                "http://old.zope.org/Resources/License/ZPL-2.0",
                "https://opensource.org/licenses/ZPL-2.0"
            ],
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "Zope Public License 2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedJudgement": [
                    [
                        "SPDX",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Is OSI Approved"
                        }
                    ]
                ],
                "__impliedURLs": [
                    [
                        "SPDX",
                        "http://spdx.org/licenses/ZPL-2.0.json"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-2.0"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            },
            "spdxLicenseId": "ZPL-2.0"
        },
        "Scancode": {
            "otherUrls": [
                "http://old.zope.org/Resources/License/ZPL-2.0",
                "http://opensource.org/licenses/ZPL-2.0",
                "http://www.zope.com/Marks",
                "https://opensource.org/licenses/ZPL-2.0"
            ],
            "homepageUrl": "http://www.zope.org/Resources/License/",
            "shortName": "ZPL 2.0",
            "textUrls": null,
            "text": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
            "category": "Permissive",
            "osiUrl": null,
            "owner": "Zope Community",
            "_sourceURL": "https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/zpl-2.0.yml",
            "key": "zpl-2.0",
            "name": "Zope Public License 2.0",
            "spdxId": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "zpl-2.0",
                    "ZPL 2.0",
                    "ZPL-2.0"
                ],
                "__impliedId": "ZPL-2.0",
                "__impliedCopyleft": [
                    [
                        "Scancode",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedText": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
                "__impliedURLs": [
                    [
                        "Homepage",
                        "http://www.zope.org/Resources/License/"
                    ],
                    [
                        null,
                        "http://old.zope.org/Resources/License/ZPL-2.0"
                    ],
                    [
                        null,
                        "http://opensource.org/licenses/ZPL-2.0"
                    ],
                    [
                        null,
                        "http://www.zope.com/Marks"
                    ],
                    [
                        null,
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            }
        },
        "OpenChainPolicyTemplate": {
            "isSaaSDeemed": "no",
            "licenseType": "permissive",
            "freedomOrDeath": "no",
            "typeCopyleft": "no",
            "_sourceURL": "https://github.com/OpenChain-Project/curriculum/raw/ddf1e879341adbd9b297cd67c5d5c16b2076540b/policy-template/Open%20Source%20Policy%20Template%20for%20OpenChain%20Specification%201.2.ods",
            "name": "Zope Public License 2.0 ",
            "commercialUse": true,
            "spdxId": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ]
            }
        },
        "BlueOak License List": {
            "BlueOakRating": "Bronze",
            "url": "https://spdx.org/licenses/ZPL-2.0.html",
            "isPermissive": true,
            "_sourceURL": "https://blueoakcouncil.org/list",
            "name": "Zope Public License 2.0",
            "id": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "BlueOak License List",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Rating is: Bronze"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "BlueOak License List",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft",
                "__impliedURLs": [
                    [
                        "SPDX",
                        "https://spdx.org/licenses/ZPL-2.0.html"
                    ]
                ]
            }
        },
        "OpenSourceInitiative": {
            "text": [
                {
                    "url": "https://opensource.org/licenses/ZPL-2.0",
                    "title": "HTML",
                    "media_type": "text/html"
                }
            ],
            "identifiers": [
                {
                    "identifier": "Zope-2.0",
                    "scheme": "DEP5"
                },
                {
                    "identifier": "ZPL-2.0",
                    "scheme": "SPDX"
                },
                {
                    "identifier": "License :: OSI Approved :: Zope Public License",
                    "scheme": "Trove"
                }
            ],
            "superseded_by": null,
            "_sourceURL": "https://opensource.org/licenses/",
            "name": "The Zope Public License, Version 2.0",
            "other_names": [],
            "keywords": [
                "discouraged",
                "non-reusable",
                "osi-approved"
            ],
            "id": "ZPL-2.0",
            "links": [
                {
                    "note": "OSI Page",
                    "url": "https://opensource.org/licenses/ZPL-2.0"
                }
            ],
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0",
                    "The Zope Public License, Version 2.0",
                    "Zope-2.0",
                    "ZPL-2.0",
                    "License :: OSI Approved :: Zope Public License"
                ],
                "__impliedURLs": [
                    [
                        "OSI Page",
                        "https://opensource.org/licenses/ZPL-2.0"
                    ]
                ]
            }
        },
        "Google OSS Policy": {
            "rating": "NOTICE",
            "_sourceURL": "https://opensource.google.com/docs/thirdparty/licenses/",
            "id": "ZPL-2.0",
            "_implications": {
                "__impliedNames": [
                    "ZPL-2.0"
                ],
                "__impliedJudgement": [
                    [
                        "Google OSS Policy",
                        {
                            "tag": "PositiveJudgement",
                            "contents": "Google Classification is NOTICE"
                        }
                    ]
                ],
                "__impliedCopyleft": [
                    [
                        "Google OSS Policy",
                        "NoCopyleft"
                    ]
                ],
                "__calculatedCopyleft": "NoCopyleft"
            }
        }
    },
    "__impliedJudgement": [
        [
            "BlueOak License List",
            {
                "tag": "PositiveJudgement",
                "contents": "Rating is: Bronze"
            }
        ],
        [
            "Google OSS Policy",
            {
                "tag": "PositiveJudgement",
                "contents": "Google Classification is NOTICE"
            }
        ],
        [
            "SPDX",
            {
                "tag": "PositiveJudgement",
                "contents": "Is OSI Approved"
            }
        ]
    ],
    "__impliedCopyleft": [
        [
            "BlueOak License List",
            "NoCopyleft"
        ],
        [
            "Google OSS Policy",
            "NoCopyleft"
        ],
        [
            "Scancode",
            "NoCopyleft"
        ]
    ],
    "__calculatedCopyleft": "NoCopyleft",
    "__impliedText": "This license has been certified as open source. It has also been designated as\nGPL compatible by the Free Software Foundation (FSF).\n\nRedistribution and use in source and binary forms, with or without modification,\nare permitted provided that the following conditions are met:\n\n   1. Redistributions in source code must retain the above copyright notice,\n   this list of conditions, and the following disclaimer.\n\n   2. Redistributions in binary form must reproduce the above copyright notice,\n   this list of conditions, and the following disclaimer in the documentation\n   and/or other materials provided with the distribution.\n\n   3. The name Zope Corporation (tm) must not be used to endorse or promote\n   products derived from this software without prior written permission from\n   Zope Corporation.\n\n   4. The right to distribute this software or to use it for any purpose does\n   not give you the right to use Servicemarks (sm) or Trademarks (tm) of Zope\n   Corporation. Use of them is covered in a separate agreement (see\n   http://www.zope.com/Marks).\n\n   5. If any files are modified, you must cause the modified files to carry\n   prominent notices stating that you changed the files and the date of any\n   change.\n\nDisclaimer\n\nTHIS SOFTWARE IS PROVIDED BY ZOPE CORPORATION ``AS IS'' AND ANY EXPRESSED OR\nIMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\nMERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT\nSHALL ZOPE CORPORATION OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\nINCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\nLIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\nPROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\nLIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\nADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n\nThis software consists of contributions made by Zope Corporation and many\nindividuals on behalf of Zope Corporation. Specific attributions are listed in\nthe accompanying credits file.",
    "__impliedURLs": [
        [
            "SPDX",
            "http://spdx.org/licenses/ZPL-2.0.json"
        ],
        [
            null,
            "http://old.zope.org/Resources/License/ZPL-2.0"
        ],
        [
            null,
            "https://opensource.org/licenses/ZPL-2.0"
        ],
        [
            "SPDX",
            "https://spdx.org/licenses/ZPL-2.0.html"
        ],
        [
            "Homepage",
            "http://www.zope.org/Resources/License/"
        ],
        [
            null,
            "http://opensource.org/licenses/ZPL-2.0"
        ],
        [
            null,
            "http://www.zope.com/Marks"
        ],
        [
            "OSI Page",
            "https://opensource.org/licenses/ZPL-2.0"
        ]
    ]
}
....