[license]

expression = "AAL"
status = "approved"

[fedora]

name = [
    "Attribution Assurance License"
]

abbreviation = [
    "AAL"
]

notes = '''
http://opensource.org/licenses/attribution.php
'''
