[license]

expression = "Abstyles"
status = "approved"

text = '''
Document License.  Meets Open Source definition.
'''

[fedora]

name = [
    "Abstyles License"
]

abbreviation = [
    "Abstyles"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Abstyles
'''
