[license]

expression = [ "ADSL" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense
'''

[fedora]

name = [
    "Amazon Digital Services License"
]

abbreviation = [
    "ADSL"
]

notes = '''
Permissive license
'''
