[license]

expression = "ADSL"
status = "approved"

text = '''
Permissive license
'''

[fedora]

name = [
    "Amazon Digital Services License"
]

abbreviation = [
    "ADSL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/AmazonDigitalServicesLicense
'''
