[license]

expression = "Afmparse"
status = "approved"

text = '''
Permissive license
'''

[fedora]

name = [
    "Afmparse License"
]

abbreviation = [
    "Afmparse"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Afmparse
'''
