[license]

expression = [ "AGPL-3.0-only" ]
status = "approved"

text = '''
http://www.fsf.org/licensing/licenses/agpl-3.0.html
'''

[fedora]

name = [
    "Affero General Public License 3.0"
]

abbreviation = [
    "AGPLv3"
]
