[license]

expression = "AGPL-3.0-only"
status = "approved"

[fedora]

name = [
    "Affero General Public License 3.0"
]

abbreviation = [
    "AGPLv3"
]

notes = '''
http://www.fsf.org/licensing/licenses/agpl-3.0.html
'''
