[license]

expression = "AGPL-1.0-only"
status = "approved"

[fedora]

name = [
    "Affero General Public License 1.0"
]

abbreviation = [
    "AGPLv1"
]

notes = '''
http://www.affero.org/oagpl.html
'''
