[license]

expression = "AML"
status = "approved"

text = '''
MIT-like license with a provision regarding no patent grant for derivative
works.
'''

[fedora]

name = [
    "Apple MIT License"
]

abbreviation = [
    "AML"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Apple_MIT_License
'''
