[license]

expression = "ANTLR-PD"
status = "approved"

[fedora]

name = [
    "ANTLR Software Rights Notice"
]

abbreviation = [
    "ANTLR-PD"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/ANTLR-PD
'''
