[license]

expression = "Apache-1.0"
status = "approved"

[fedora]

name = [
    "Apache Software License 1.0"
]

abbreviation = [
    "ASL 1.0"
]

notes = '''
http://www.apache.org/licenses/LICENSE-1.0
'''
