[license]

expression = [ "Apache-1.1" ]
status = "approved"

text = '''
http://4suite.org/COPYRIGHT  http://www.apache.org/licenses/LICENSE-1.1
https://fedoraproject.org/wiki/Licensing/MX4J
http://www.clearsilver.net/license.hdf
http://www.quickfixengine.org/quickfix/doc/html/license.html
http://phorum.org/license.txt
https://fedoraproject.org/wiki/Licensing/SequenceLibraryLicense
'''

[fedora]

name = [
    "4Suite Copyright License",
    "Apache Software License 1.1",
    "MX4J License",
    "Neotonic Clearsilver License",
    "QuickFix License",
    "Phorum License",
    "Sequence Library License"
]

abbreviation = [
    "ASL 1.1",
    "Phorum",
    "Sequence"
]

notes = '''
new URL http://www.worldlii.org/int/other/PubRL/2000/1.html  Bad URL; this is
the same license as Apache-1.1  Fedora uses identifier, "ASL 1.1" this is the
same as Apache 1.1 but for names   Fedora uses identifier, "ASL 1.1" link used
to go to a page that shows BSD-2-Clause and a notice regarding that change.
Found older(?) version with this license:
https://github.com/rphillips/clearsilver/blob/master/CS_LICENSE, which is same
as Apache 1.1 also see
https://github.com/blong42/clearsilver/blob/master/LICENSE
https://github.com/Phorum/Core/blob/master/docs/license.txt  PM: Reject (Apache
1.1 license-template should suffice)
'''
