[license]

expression = "Apache-2.0"
status = "approved"

[fedora]

name = [
    "Apache Software License 2.0"
]

abbreviation = [
    "ASL 2.0"
]

notes = '''
http://www.apache.org/licenses/LICENSE-2.0
'''
