[license]

expression = "APAFML"
status = "approved"

text = '''
Permissive license, specifically for Adobe AFM files  It shows up in the open
source package iText. See http://itextpdf.com/terms-of-use/adobe.html
'''

[fedora]

name = [
    "Adobe Postscript AFM License"
]

abbreviation = [
    "APAFML"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/AdobePostscriptAFM
'''
