[license]

expression = "App-s2p"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/App-s2p
'''

[fedora]

name = "App::s2p License"
abbreviation = "App-s2p"

notes = '''
used in https://metacpan.org/release/KNOK/File-MMagic-1.30/source/COPYING
https://github.com/spdx/license-list-XML/issues/1361
'''
