[license]

expression = "Artistic-2.0"
status = "approved"

[fedora]

name = [
    "Artistic 2.0"
]

abbreviation = [
    "Artistic 2.0"
]

notes = '''
http://www.perlfoundation.org/artistic_license_2_0
'''
