[license]

expression = "BitTorrent-1.1"
status = "approved"

text = '''
SPDX List also has BitTorrent-1.0
'''

[fedora]

name = [
    "BitTorrent License"
]

abbreviation = [
    "BitTorrent"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/BitTorrent_Open_Source_License
'''
