[license]

expression = "BitTorrent-1.1"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/BitTorrent_Open_Source_License
'''

[fedora]

name = "BitTorrent License"
abbreviation = "BitTorrent"

notes = '''
SPDX List also has BitTorrent-1.0
'''
