[license]

expression = "Borceux"
status = "approved"

text = '''
Permissive license. May be single package license.
'''

[fedora]

name = [
    "Borceux license"
]

abbreviation = [
    "Borceux"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Borceux
'''
