[license]

expression = "BSD-3-Clause-LBNL"
status = "approved"

text = '''
BSD like license with a provision at the end that makes any non licensed
additions subject to a FOSS license
'''

[fedora]

name = [
    "Lawrence Berkeley National Labs BSD variant license"
]

abbreviation = [
    "LBNL BSD"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/LBNLBSD
'''
