[license]

expression = "BSD-2-Clause-FreeBSD"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/BSD#2ClauseBSD
'''

[fedora]

name = [
    "BSD License (two clause)"
]

abbreviation = [
    "BSD"
]

notes = '''
Fedora uses identifier, "BSD"
'''
