[license]

expression = "BSD-2-Clause-Patent"
status = "approved"

[fedora]

name = [
    "BSD + Patent"
]

abbreviation = [
    "BSD-2-Clause-Patent"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/BSD-2-Clause-Patent
'''
