[license]

expression = "BSD-2-Clause"
status = "approved"

text = '''
http://www.cryptix.org/LICENSE.TXT
'''

[fedora]

name = "Cryptix General License"
abbreviation = "BSD"

notes = '''
Fedora uses identifier, "BSD"
'''
