[license]

expression = "BSD-4-Clause"
status = "approved"

text = '''
Fedora should link to: https://fedoraproject.org/wiki/Licensing:BSD?rd=Licensing
/BSD#Original_BSD_License_.28BSD_with_advertising.29  similar to BSD-4-Clause
'''

[fedora]

name = [
    "BSD License (Advertising Variant)"
]

abbreviation = [
    "BSD with advertising"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/BSD#BSDwithAdvertising
'''
