[license]

expression = "BSD-2-Clause"
status = "approved"

text = '''
short identifier issue - need to deal with for all BSD variants  Fedora uses
identifier, "BSD"
'''

[fedora]

name = [
    "Creative Commons BSD",
    "Cryptix General License"
]

abbreviation = [
    "BSD"
]

notes = '''
http://creativecommons.org/licenses/BSD/  http://www.cryptix.org/LICENSE.TXT
'''
