[license]

expression = "BSD 3-clause"
status = "approved"

text = '''
This is BSD 3-clause
'''

[fedora]

name = [
    "Eclipse Distribution License 1.0"
]

abbreviation = [
    "BSD"
]

notes = '''
http://www.eclipse.org/org/documents/edl-v10.php
'''
