[license]

expression = "BSD 3-clause"
status = "approved"

text = '''
http://www.eclipse.org/org/documents/edl-v10.php
'''

[fedora]

name = "Eclipse Distribution License 1.0"
abbreviation = "BSD"

notes = '''
This is BSD 3-clause
'''
