[license]

expression = "BSL-1.0"
status = "approved"

[fedora]

name = [
    "Boost Software License",
    "MIT:Thrift variant"
]

abbreviation = [
    "Boost",
    "MIT"
]

notes = '''
http://www.boost.org/LICENSE_1_0.txt
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Thrift_variant
'''
