[license]

expression = "CATOSL-1.1"
status = "approved"

text = '''
SPDX short identifier adds version #
'''

[fedora]

name = [
    "Computer Associates Trusted Open Source License 1.1"
]

abbreviation = [
    "CATOSL"
]

notes = '''
http://opensource.org/licenses/ca-tosl1.1.php
'''
