[license]

expression = [ "CC0-1.0" ]
status = "approved"

text = '''
http://creativecommons.org/publicdomain/zero/1.0/legalcode
'''

[fedora]

name = [
    "Creative Commons Zero 1.0 Universal"
]

abbreviation = [
    "CC0"
]
