[license]

expression = "CC0-1.0"
status = "approved"

[fedora]

name = [
    "Creative Commons Zero 1.0 Universal"
]

abbreviation = [
    "CC0"
]

notes = '''
http://creativecommons.org/publicdomain/zero/1.0/legalcode
'''
