[license]

expression = "CDDL-1.1"
status = "approved"

[fedora]

name = [
    "Common Development Distribution License 1.1"
]

abbreviation = [
    "CDDL-1.1"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/CDDL#CDDL_1.1
'''
