[license]

expression = [ "CDDL-1.0" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/CDDL#CDDL_1.0
'''

[fedora]

name = [
    "Common Development Distribution License 1.0"
]

abbreviation = [
    "CDDL-1.0"
]
