[license]

expression = "CECILL-1.1"
status = "approved"

text = '''
SPDX List also has CECILL-1.0
'''

[fedora]

name = [
    "CeCILL License v1.1"
]

abbreviation = [
    "CeCILL"
]

notes = '''
http://www.cecill.info/licences/Licence_CeCILL_V1.1-US.html
'''
