[license]

expression = "CECILL-B"
status = "approved"

text = '''
SPDX List also has CECILL-1.0
'''

[fedora]

name = [
    "CeCILL-B License"
]

abbreviation = [
    "CeCILL-B"
]

notes = '''
http://www.cecill.info/licences.en.html
'''
