[license]

expression = [ "CECILL-B" ]
status = "approved"

text = '''
http://www.cecill.info/licences.en.html
'''

[fedora]

name = [
    "CeCILL-B License"
]

abbreviation = [
    "CeCILL-B"
]

notes = '''
SPDX List also has CECILL-1.0
'''
