[license]

expression = "CECILL-2.0"
status = "approved"

text = '''
SPDX List also has CECILL-1.0
'''

[fedora]

name = [
    "CeCILL License v2"
]

abbreviation = [
    "CeCILL"
]

notes = '''
http://www.cecill.info/licences.en.html
'''
