[license]

expression = "CECILL-C"
status = "approved"

text = '''
SPDX List also has CECILL-1.0
'''

[fedora]

name = [
    "CeCILL-C License"
]

abbreviation = [
    "CeCILL-C"
]

notes = '''
http://www.cecill.info/licences.en.html
'''
