[license]

expression = "ClArtistic"
status = "approved"

[fedora]

name = [
    "Artistic (clarified)"
]

abbreviation = [
    "Artistic clarified"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/ArtisticClarified
'''
