[license]

expression = "CNRI-Python"
status = "approved"

[fedora]

name = [
    "CNRI License (Old Python)"
]

abbreviation = [
    "CNRI"
]

notes = '''
http://www.handle.net/python_licenses/python1.6_9-5-00.html
'''
