[license]

expression = "Condor-1.1"
status = "approved"

text = '''
The URL provided by Fedora does not point to any license.  SPDX short identifier
adds version #
'''

[fedora]

name = [
    "Condor Public License"
]

abbreviation = [
    "Condor"
]

notes = '''
http://www.cs.wisc.edu/condor/condor-public-license.html
'''
