[license]

expression = "CPAL-1.0"
status = "approved"

text = '''
SPDX short identifier adds version #
'''

[fedora]

name = [
    "CPAL License 1.0"
]

abbreviation = [
    "CPAL"
]

notes = '''
https://www.socialtext.net/open/index.cgi?cpal_license_in_wikitext
'''
