[license]

expression = "CPL-1.0"
status = "approved"

text = '''
http://www.eclipse.org/legal/cpl-v10.html
'''

[fedora]

name = [
    "Common Public License"
]

abbreviation = [
    "CPL"
]

notes = '''
SPDX short identifier adds version #
'''
