[license]

expression = "Crossword"
status = "approved"

text = '''
Permissive license. May be single package license.
'''

[fedora]

name = [
    "Crossword License"
]

abbreviation = [
    "Crossword"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Crossword
'''
