[license]

expression = "CrystalStacker"
status = "approved"

[fedora]

name = [
    "Crystal Stacker License"
]

abbreviation = [
    "Crystal Stacker"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/CrystalStacker
'''
