[license]

expression = "Cube"
status = "approved"

text = '''
Permissive license with requirement that you may not relicense the source code
under any other license. Official site http://src.gnu-
darwin.org/ports/games/assaultcube/work/AssaultCube/source/LICENSE
'''

[fedora]

name = [
    "Cube License"
]

abbreviation = [
    "Cube"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Cube
'''
