[license]

expression = "Dotseqn"
status = "approved"

text = '''
Permissive license. Appears to be single file/package
'''

[fedora]

name = [
    "Dotseqn License"
]

abbreviation = [
    "Dotseqn"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Dotseqn
'''
