[license]

expression = "DSDP"
status = "approved"

text = '''
MIT like license.
'''

[fedora]

name = [
    "DSDP License"
]

abbreviation = [
    "DSDP"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/DSDP
'''
