[license]

expression = "dvipdfm"
status = "approved"

text = '''
Permissive license. May be a one time license
'''

[fedora]

name = [
    "dvipdfm License"
]

abbreviation = [
    "dvipdfm"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/dvipdfm
'''
