[license]

expression = [ "dvipdfm" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/dvipdfm
'''

[fedora]

name = [
    "dvipdfm License"
]

abbreviation = [
    "dvipdfm"
]

notes = '''
Permissive license. May be a one time license
'''
