[license]

expression = "ECL-2.0"
status = "approved"

[fedora]

name = [
    "Educational Community License 2.0"
]

abbreviation = [
    "ECL 2.0"
]

notes = '''
http://www.osedu.org/licenses/ECL-2.0/
'''
