[license]

expression = "ECL-1.0"
status = "approved"

[fedora]

name = [
    "Educational Community License 1.0"
]

abbreviation = [
    "ECL 1.0"
]

notes = '''
http://opensource.org/licenses/ecl1.php
'''
