[license]

expression = "EFL-2.0"
status = "approved"

[fedora]

name = [
    "Eiffel Forum License 2.0"
]

abbreviation = [
    "EFL 2.0"
]

notes = '''
http://www.fsf.org/licensing/licenses/eiffel-forum-license-2.html
'''
