[license]

expression = "EPL-1.0"
status = "approved"

[fedora]

name = [
    "Eclipse Public License 1.0"
]

abbreviation = [
    "EPL-1.0"
]

notes = '''
http://www.eclipse.org/legal/epl-v10.html
'''
