[license]

expression = "EPL-2.0"
status = "approved"

[fedora]

name = [
    "Eclipse Public License 2.0"
]

abbreviation = [
    "EPL-2.0"
]

notes = '''
http://www.eclipse.org/legal/epl-v20.html
'''
