[license]

expression = "ErlPL-1.1"
status = "approved"

[fedora]

name = [
    "Erlang Public License 1.1"
]

abbreviation = [
    "ERPL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/ErlangPublicLicense
'''
