[license]

expression = "EUDatagrid"
status = "approved"

[fedora]

name = [
    "EU Datagrid Software License"
]

abbreviation = [
    "EU Datagrid"
]

notes = '''
http://www.opensource.org/licenses/eudatagrid.php
'''
