[license]

expression = "EUPL-1.1"
status = "approved"

[fedora]

name = [
    "European Union Public License 1.1"
]

abbreviation = [
    "EUPL 1.1"
]

notes = '''
http://ec.europa.eu/idabc/en/document/7774.html
'''
