[license]

expression = "EUPL-1.2"
status = "approved"

[fedora]

name = [
    "European Union Public License 1.2"
]

abbreviation = [
    "EUPL 1.2"
]

notes = '''
https://opensource.org/licenses/EUPL-1.2
'''
