[license]

expression = "Eurosym"
status = "approved"

text = '''
Copyleft license. German law applies
'''

[fedora]

name = [
    "Eurosym License"
]

abbreviation = [
    "Eurosym"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Eurosym
'''
