[license]

expression = "FDK-AAC"
status = "approved"

[fedora]

name = [
    "Fraunhofer FDK AAC License"
]

abbreviation = [
    "FDK-AAC"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/FDK-AAC
'''
