[license]

expression = "FSFAP"
status = "approved"

[fedora]

name = [
    "FSF All Permissive license"
]

abbreviation = [
    "FSFAP"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/FSFAP
'''
