[license]

expression = [ "FSFUL" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License
'''

[fedora]

name = [
    "FSF Unlimited License"
]

abbreviation = [
    "FSFUL"
]

notes = '''
Permissive license.
'''
