[license]

expression = "FSFUL"
status = "approved"

text = '''
Permissive license.
'''

[fedora]

name = [
    "FSF Unlimited License"
]

abbreviation = [
    "FSFUL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License
'''
