[license]

expression = "FSFULLR"
status = "approved"

text = '''
Permissive license.
'''

[fedora]

name = [
    "FSF Unlimited License (with License Retention)"
]

abbreviation = [
    "FSFULLR"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/FSF_Unlimited_License#License_Retention
_Variant
'''
