[license]

expression = "Giftware"
status = "approved"

text = '''
Permissive license.  done - added Allegro 4; Allegro 5 is same as zlib
'''

[fedora]

name = [
    "Giftware License"
]

abbreviation = [
    "Giftware"
]

notes = '''
http://www.talula.demon.co.uk/allegro/license.html
'''
