[license]

expression = "GL2PS"
status = "approved"

text = '''
Copyleft license.
'''

[fedora]

name = [
    "GL2PS License"
]

abbreviation = [
    "GL2PS"
]

notes = '''
http://www.geuz.org/gl2ps/COPYING.GL2PS
'''
