[license]

expression = "Gnuplot"
status = "approved"

text = '''
License requires changes to source to be packaged as patches and not appended to
the original source, etc.
'''

[fedora]

name = [
    "gnuplot License"
]

abbreviation = [
    "gnuplot"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Gnuplot
'''
