[license]

expression = "GPL-3.0-or-later"
status = "approved"

[fedora]

name = [
    "GNU General Public License v3.0 or later"
]

abbreviation = [
    "GPLv3+"
]

notes = '''
http://www.fsf.org/licensing/licenses/gpl.html
'''
