[license]

expression = "GPL-3.0-or-later WITH Font-exception-2.0"
status = "approved"

[fedora]

name = [
    "GNU General Public License v3.0 or later, with font embedding exception"
]

abbreviation = [
    "GPLv3+ with exceptions"
]

notes = '''
http://www.gnu.org/licenses/gpl-faq.html#FontException
'''
