[license]

expression = "GPL-2.0-or-later WITH Font-exception-2.0"
status = "approved"

text = '''
http://www.gnu.org/licenses/gpl-faq.html#FontException
'''

[fedora]

name = "GNU General Public License v2.0 or later, with font embedding exception"
abbreviation = "GPLv2+ with exceptions"
