[license]

expression = "GPL-3.0-or-later"
status = "approved"

text = '''
http://www.fsf.org/licensing/licenses/gpl.html
'''

[fedora]

name = "GNU General Public License v3.0 or later"
abbreviation = "GPLv3+"
