[license]

expression = "GPL-3.0-only"
status = "approved"

[fedora]

name = [
    "GNU General Public License v3.0 only"
]

abbreviation = [
    "GPLv3"
]

notes = '''
http://www.fsf.org/licensing/licenses/gpl.html
'''
