[license]

expression = "GPL-1.0-or-later WITH Classpath-exception-2.0"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/GPL_Classpath_Exception
'''

[fedora]

name = "GNU General Public License (no version), with Classpath exception"
abbreviation = "GPL+ with exceptions"
