[license]

expression = "GPL-2.0-or-later OR Artistic-1.0-Perl"
status = "approved"

text = '''
Some perl packages explicitly state GPLv2+, only use this license for those
cases
'''

[fedora]

name = "Perl License (variant)"
abbreviation = "GPLv2+ or Artistic"

notes = '''
this would be covered by using the short identifiers for each licnese choice
with the "OR" operator
'''
