[license]

expression = "GPL-2.0-or-later"
status = "approved"

text = '''
http://creativecommons.org/choose/cc-gpl  http://www.gnu.org/licenses/old-
licenses/gpl-2.0.html
'''

[fedora]

name = [
    "Creative Commons GNU GPL",
    "GNU General Public License v2.0 or later"
]

abbreviation = [
    "GPLv2+"
]

notes = '''
This is GPL-2.0+
'''
