[license]

expression = "GPL-2.0-or-later WITH eCos-2.0"
status = "approved"

[fedora]

name = [
    "eCos License v2.0"
]

abbreviation = [
    "eCos"
]

notes = '''
http://www.fsf.org/licensing/licenses/ecos-license.html
'''
