[license]

expression = "GPL-1.0-or-later OR Artistic-1.0-Perl"
status = "approved"

text = '''
this would be covered by using the short identifiers for each licnese choice
with the "OR" operator
'''

[fedora]

name = [
    "Perl License"
]

abbreviation = [
    "GPL+ or Artistic"
]

notes = '''
http://dev.perl.org/licenses/
'''
