[license]

expression = "GPL-3.0-only WITH Classpath-exception-2.0"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/GPL_Classpath_Exception
'''

[fedora]

name = "GNU General Public License v3.0 only, with Classpath exception"
abbreviation = "GPLv3 with exceptions"
