[license]

expression = "GPL-2.0-only WITH DigiRule-FOSS-exception GPL-2.0-only WITH Universal-FOSS-exception-1.0"
status = "approved"

text = '''
http://www.mysql.com/company/legal/licensing/foss-exception.html
'''

[fedora]

name = "MySQL License"
abbreviation = "GPLv2 with exceptions"

notes = '''
SPDX has the old one and the latest one (same as Fedora-provided link)  note for
SPDX: DigiRule needs markup in SPDX (current one) two versions of this, link
only goes to most current
'''
