[license]

expression = "HaskellReport"
status = "approved"

text = '''
there are 3 variations here, but the difference can be accomodated via a license
template as it's only a different in name; use same Fedora short identifier; add
as one license with template
'''

[fedora]

name = [
    "Haskell Language Report License"
]

abbreviation = [
    "HaskellReport"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Haskell_Language_Report_License
'''
