[license]

expression = "HPND"
status = "approved"

text = '''
no longer used in practice per OSI
'''

[fedora]

name = [
    "Historical Permission Notice and Disclaimer",
    "MIT:Old Style with legal disclaimer"
]

abbreviation = [
    "MIT"
]

notes = '''
http://opensource.org/licenses/historical.php  https://fedoraproject.org/wiki/Li
censing:MIT?rd=Licensing/MIT#Old_Style_with_legal_disclaimer
'''
