[license]

expression = "ICU"
status = "approved"

[fedora]

name = [
    "MIT:Modern style (ICU Variant)"
]

abbreviation = [
    "MIT"
]

notes = '''
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_style_.28IC
U_Variant.29
'''
