[license]

expression = [ "IJG" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/IJG
'''

[fedora]

name = [
    "Independent JPEG Group License"
]

abbreviation = [
    "IJG"
]
