[license]

expression = "IJG"
status = "approved"

[fedora]

name = [
    "Independent JPEG Group License"
]

abbreviation = [
    "IJG"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/IJG
'''
