[license]

expression = "Intel-ACPI"
status = "approved"

text = '''
Intel specific license.
'''

[fedora]

name = [
    "Intel ACPI Software License Agreement"
]

abbreviation = [
    "Intel ACPI"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Intel_ACPI_Software_License_Agreement
'''
