[license]

expression = "Interbase-1.0"
status = "approved"

text = '''
Fedora link does not provide license text:
http://www.borland.com/devsupport/interbase/opensource/IPL.html
'''

[fedora]

name = [
    "Interbase Public License"
]

abbreviation = [
    "Interbase"
]

notes = '''
http://www.firebirdsql.org/en/interbase-public-license/
'''
