[license]

expression = "JasPer-2.0"
status = "approved"

text = '''
MIT/BSD like
'''

[fedora]

name = [
    "JasPer License"
]

abbreviation = [
    "JasPer"
]

notes = '''
http://www.ece.uvic.ca/~mdadams/jasper/LICENSE
'''
