[license]

expression = "JasPer-2.0"
status = "approved"

text = '''
http://www.ece.uvic.ca/~mdadams/jasper/LICENSE
'''

[fedora]

name = "JasPer License"
abbreviation = "JasPer"

notes = '''
MIT/BSD like
'''
