[license]

expression = "Latex2e"
status = "approved"

text = '''
Copyleft license.
'''

[fedora]

name = [
    "Latex2e License"
]

abbreviation = [
    "Latex2e"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Latex2e
'''
