[license]

expression = "Latex2e"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Latex2e
'''

[fedora]

name = "Latex2e License"
abbreviation = "Latex2e"

notes = '''
Copyleft license.
'''
