[license]

expression = [ "Leptonica" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Leptonica
'''

[fedora]

name = [
    "Leptonica License"
]

abbreviation = [
    "Leptonica"
]

notes = '''
BSD like.  Official license site http://www.leptonica.com/about-the-license.html
'''
