[license]

expression = "LGPL-2.0-only "
status = "approved"

text = '''
Fedora treats 2.0 and 2.1 as same, SPDX does not
'''

[fedora]

name = [
    "GNU Lesser General Public License v2 (or 2.1) only"
]

abbreviation = [
    "LGPLv2"
]

notes = '''
=HYPERLINK("http://www.gnu.org/licenses/old-
licenses/lgpl-2.1.html","http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
Note that this license was originally referred to as the GNU Library General
Public License v2, but all current versions (v2.1 or newer) of the license are
correctly known as the GNU Lesser General Public License.")
'''
