[license]

expression = "LGPL-2.0-or-later WITH FLTK-exception"
status = "approved"

text = '''
http://www.fltk.org/COPYING.php
'''

[fedora]

name = "FLTK License"
abbreviation = "LGPLv2 with exceptions"

notes = '''
LGPLv2 with exception.
'''
