[license]

expression = "LGPL-2.0-or-later"
status = "approved"

text = '''
This is LGPL-2.0+
'''

[fedora]

name = [
    "Creative Commons GNU LGPL"
]

abbreviation = [
    "LGPLv2+"
]

notes = '''
http://creativecommons.org/choose/cc-lgpl
'''
