[license]

expression = [ "LGPL-3.0-or-later" ]
status = "approved"

text = '''
http://www.fsf.org/licensing/licenses/lgpl.html
'''

[fedora]

name = [
    "GNU Lesser General Public License v3.0 or later"
]

abbreviation = [
    "LGPLv3+"
]
