[license]

expression = "LGPL-2.0-or-later WITH WxWindows-exception-3.1"
status = "approved"

[fedora]

name = [
    "wxWindows Library License v 3.1"
]

abbreviation = [
    "wxWindows"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/wxWindows.html
'''
