[license]

expression = "LGPL-2.0-or-later WITH FLTK-exception"
status = "approved"

text = '''
LGPLv2 with exception.
'''

[fedora]

name = [
    "FLTK License"
]

abbreviation = [
    "LGPLv2 with exceptions"
]

notes = '''
http://www.fltk.org/COPYING.php
'''
