[license]

expression = "LGPL-3.0-only"
status = "approved"

[fedora]

name = [
    "GNU Lesser General Public License v3.0 only"
]

abbreviation = [
    "LGPLv3"
]

notes = '''
http://www.fsf.org/licensing/licenses/lgpl.html
'''
