[license]

expression = "LGPL-3.0-or-later"
status = "approved"

[fedora]

name = [
    "GNU Lesser General Public License v3.0 or later"
]

abbreviation = [
    "LGPLv3+"
]

notes = '''
http://www.fsf.org/licensing/licenses/lgpl.html
'''
