[license]

expression = "libtiff"
status = "approved"

text = '''
BSD/MIT like
'''

[fedora]

name = [
    "libtiff License",
    "MIT:Hylafax Variant"
]

abbreviation = [
    "libtiff",
    "MIT"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/libtiff
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Hylafax_Variant
'''
