[license]

expression = [ "LicenseRef-midnight" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/midnight
'''

[fedora]

name = [
    "midnight License"
]

abbreviation = [
    "midnight"
]

notes = '''
not found in Fedora currently, don't add to SPDX  FOSS license for single
package
'''
