[license]

expression = [ "LicenseRef-CRC32" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/CRC32
'''

[fedora]

name = [
    "CRC32 License"
]

abbreviation = [
    "CRC32"
]

notes = '''
not found in Fedora currently, don't add to SPDX
'''
