[license]

expression = "LicenseRef-Romio"
status = "approved"

text = '''
see current license here: https://www.open-mpi.org/community/license.php - it
appears that license was changed to BSD-3-Clause, so rejecting, can always add
later, if older versions are in wide-use Fedora link works now and has licene
text.
'''

[fedora]

name = [
    "Romio License"
]

abbreviation = [
    "Romio"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Romio_License
'''
