[license]

expression = [ "LicenseRef-Newmat" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Newmat_License
'''

[fedora]

name = [
    "Newmat License"
]

abbreviation = [
    "Newmat"
]

notes = '''
not found in Fedora currently, don't add to SPDX
'''
