[license]

expression = "LicenseRef-STMPL"
status = "approved"

text = '''
this is the same as MPL 1.0 except for the preamble and amendment at end, due to
this and that no one has seen it used currently, did not add
'''

[fedora]

name = [
    "SciTech MGL Public License"
]

abbreviation = [
    "STMPL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/STMPL
'''
