[license]

expression = "LicenseRef-SLIB"
status = "approved"

text = '''
The text at the given URL is not really the license it self, more an explanatory
text mentionning public domain dedication and the actual license. On a side
note, they seem to define a theshold for copyrightability at "a dozen of lines"
"PM: Reject (not a license, but rather an explanation of how SLIB is licensed on
file by file basis) DC: Reject (agree with PM) "
'''

[fedora]

name = [
    "SLIB License"
]

abbreviation = [
    "SLIB"
]

notes = '''
http://www-swiss.ai.mit.edu/~jaffer/SLIB_COPYING.txt
'''
