[license]

expression = "LicenseRef-mod_macro"
status = "approved"

text = '''
link broken - is this it?  https://people.apache.org/~fabien/mod_macro/LICENSE
also see https://fossies.org/linux/mod_macro/LICENSE
'''

[fedora]

name = [
    "mod_macro License"
]

abbreviation = [
    "mod_macro"
]

notes = '''
http://www.cri.ensmp.fr/~coelho/mod_macro/mod_macro/LICENSE
'''
