[license]

expression = "LicenseRef-VNLSL"
status = "approved"

text = '''
no current copy of license elsewhere and seems old and very specific so not
adding
'''

[fedora]

name = [
    "Vita Nuova Liberal Source License"
]

abbreviation = [
    "VNLSL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Vita_Nuova_Liberal_Source_License
'''
