[license]

expression = "LicenseRef-SCRIP"
status = "approved"

text = '''
Way too specific "JL: this seems old and can't find it elsewhere... reject? PM:
Add?-found wiki page and code available, although last contribution 3 yrs. ago
(see http://oceans11.lanl.gov/trac/SCRIP/wiki ) - too specific, decided not to
add"
'''

[fedora]

name = [
    "SCRIP License"
]

abbreviation = [
    "SCRIP"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/SCRIP
'''
