[license]

expression = "LPL-1.02"
status = "approved"

text = '''
SPDX List also has LPL-1.0
'''

[fedora]

name = [
    "Lucent Public License (Plan9)"
]

abbreviation = [
    "LPL"
]

notes = '''
http://plan9.bell-labs.com/plan9dist/license.html
'''
