[license]

expression = "LPPL-1.3a"
status = "approved"

text = '''
SPDX List also has LPPL-1.0, LPPL-1.1, LPPL-1.2, LPPL-1.3c
'''

[fedora]

name = [
    "LaTeX Project Public License"
]

abbreviation = [
    "LPPL"
]

notes = '''
http://www.latex-project.org/lppl/lppl-1-3a.txt
'''
