[license]

expression = "MakeIndex"
status = "approved"

text = '''
Strong Copyleft.
'''

[fedora]

name = [
    "MakeIndex License"
]

abbreviation = [
    "MakeIndex"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MakeIndex
'''
