[license]

expression = "MIT-feh"
status = "approved"

text = '''
Slight variant to MIT license. May be one package license
'''

[fedora]

name = [
    "feh License"
]

abbreviation = [
    "MIT"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MIT#feh
'''
