[license]

expression = "MIT-advertising"
status = "approved"

text = '''
This license is identical to MIT-FEH (except for templatized copyright
statement)
'''

[fedora]

name = [
    "Enlightenment License (e16)"
]

abbreviation = [
    "MIT with advertising"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MIT_With_Advertising
'''
