[license]

expression = "MIT-0"
status = "approved"

[fedora]

name = [
    "MIT No Attribution (MIT-0)"
]

abbreviation = [
    "MIT-0"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MIT-0
'''
