[license]

expression = "MIT"
status = "approved"

[fedora]

name = [
    "MIT:Modern Style with sublicense"
]

abbreviation = [
    "MIT"
]

notes = '''
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_
sublicense
'''
