[license]

expression = "MITNFA"
status = "approved"

[fedora]

name = [
    "MIT +no-false-attribs license"
]

abbreviation = [
    "MITNFA"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MITNFA
'''
