[license]

expression = "MPL-1.0"
status = "approved"

[fedora]

name = [
    "Mozilla Public License v1.0"
]

abbreviation = [
    "MPLv1.0"
]

notes = '''
http://opensource.org/licenses/mozilla1.0.php
'''
