[license]

expression = "MPL-1.1"
status = "approved"

[fedora]

name = [
    "Mozilla Public License v1.1"
]

abbreviation = [
    "MPLv1.1"
]

notes = '''
http://www.mozilla.org/MPL/MPL-1.1.html
'''
