[license]

expression = "MPL-2.0"
status = "approved"

[fedora]

name = [
    "Mozilla Public License v2.0"
]

abbreviation = [
    "MPLv2.0"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/MPLv2.0
'''
