[license]

expression = "MS-PL"
status = "approved"

[fedora]

name = [
    "Microsoft Public License"
]

abbreviation = [
    "MS-PL"
]

notes = '''
http://www.microsoft.com/opensource/licenses.mspx#Ms-PL
'''
