[license]

expression = "MS-RL"
status = "approved"

[fedora]

name = [
    "Microsoft Reciprocal License"
]

abbreviation = [
    "MS-RL"
]

notes = '''
http://www.microsoft.com/opensource/licenses.mspx#Ms-RL
'''
