[license]

expression = "MTLL"
status = "approved"

text = '''
Single package license. Apache-1.1-like
'''

[fedora]

name = [
    "Matrix Template Library License"
]

abbreviation = [
    "MTLL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Matrix_Template_Library_License
'''
