[license]

expression = "NCSA"
status = "approved"

[fedora]

name = [
    "NCSA/University of Illinois Open Source License"
]

abbreviation = [
    "NCSA"
]

notes = '''
http://otm.illinois.edu/uiuc_openSource
'''
