[license]

expression = "Newsletr"
status = "approved"

[fedora]

name = [
    "Newsletr License"
]

abbreviation = [
    "Newsletr"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Newsletr
'''
