[license]

expression = "NGPL"
status = "approved"

[fedora]

name = [
    "Nethack General Public License"
]

abbreviation = [
    "NGPL"
]

notes = '''
http://opensource.org/licenses/nethack.php
'''
