[license]

expression = "NIST-PD-fallback"
status = "approved"

[fedora]

name = [
    "NIST Software License"
]

abbreviation = [
    "NISTSL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/NISTSL
'''
