[license]

expression = "NOSL"
status = "approved"

[fedora]

name = [
    "Netizen Open Source License"
]

abbreviation = [
    "NOSL"
]

notes = '''
http://bits.netizen.com.au/licenses/NOSL/nosl.txt
'''
