[license]

expression = "NRL"
status = "approved"

text = '''
this license is just different enough from BSD-4-Clause, including adding a
clause stating that "All terms of the UC Berkeley copyright and license must be
followed.
'''

[fedora]

name = [
    "NRL License"
]

abbreviation = [
    "BSD with advertising"
]

notes = '''
http://web.mit.edu/network/isakmp/nrllicense.html
'''
