[license]

expression = "NRL"
status = "approved"

text = '''
http://web.mit.edu/network/isakmp/nrllicense.html
'''

[fedora]

name = "NRL License"
abbreviation = "BSD with advertising"

notes = '''
this license is just different enough from BSD-4-Clause, including adding a
clause stating that "All terms of the UC Berkeley copyright and license must be
followed.
'''
