[license]

expression = "Nunit zlib-acknowledgement"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Nunit
'''

[fedora]

name = "Nunit License"
abbreviation = "MIT with advertising"

notes = '''
added to SPDX as "Nunit" and later realized it was same as zlib-acknowledgement
with matching guidelines - use latter identifier
'''
