[license]

expression = "OGL-UK-3.0"
status = "approved"

[fedora]

name = [
    "Open Government License"
]

abbreviation = [
    "OGL"
]

notes = '''
http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
'''
