[license]

expression = "OLDAP-2.8"
status = "approved"

[fedora]

name = [
    "OpenLDAP License"
]

abbreviation = [
    "OpenLDAP"
]

notes = '''
http://www.openldap.org/software/release/license.html
'''
