[license]

expression = "OML"
status = "approved"

[fedora]

name = [
    "Open Market License"
]

abbreviation = [
    "OML"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Open_Market_License
'''
