[license]

expression = "OSL-3.0"
status = "approved"

[fedora]

name = [
    "Open Software License 3.0"
]

abbreviation = [
    "OSL 3.0"
]

notes = '''
http://opensource.org/licenses/osl-3.0.php
'''
