[license]

expression = "OSL-1.0"
status = "approved"

[fedora]

name = [
    "Open Software License 1.0"
]

abbreviation = [
    "OSL 1.0"
]

notes = '''
http://www.opensource.org/licenses/osl-1.0.txt
'''
