[license]

expression = "OSL-2.0"
status = "approved"

[fedora]

name = [
    "Open Software License 2.0"
]

abbreviation = [
    "OSL 2.0"
]

notes = '''
http://www.nexb.com/license/LICENSE-OSL-2.0.html
'''
