[license]

expression = "OSL-1-1"
status = "approved"

[fedora]

name = [
    "Open Software License 1.1"
]

abbreviation = [
    "OSL 1.0"
]

notes = '''
https://fedoraproject.org/wiki/Licensing:OSL1.1?rd=Licensing/OSL1.1
'''
