[license]

expression = "OSL-2.1"
status = "approved"

[fedora]

name = [
    "Open Software License 2.1"
]

abbreviation = [
    "OSL 2.1"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/OSL2.1
'''
