[license]

expression = "PHP-3.01"
status = "approved"

text = '''
SPDX List also has PHP-3.0
'''

[fedora]

name = [
    "PHP License v3.0"
]

abbreviation = [
    "PHP"
]

notes = '''
http://www.php.net/license/3_01.txt
'''
