[license]

expression = "Plexus"
status = "approved"

[fedora]

name = [
    "Plexus Classworlds License"
]

abbreviation = [
    "Plexus"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Plexus_Classworlds_License
'''
