[license]

expression = "PostgreSQL"
status = "approved"

[fedora]

name = [
    "PostgreSQL License"
]

abbreviation = [
    "PostgreSQL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/PostgreSQL_License
'''
