[license]

expression = [ "Rdisc" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Rdisc_License
'''

[fedora]

name = [
    "Rdisc License"
]

abbreviation = [
    "Rdisc"
]
