[license]

expression = "Saxpath"
status = "approved"

[fedora]

name = [
    "Saxpath License"
]

abbreviation = [
    "Saxpath"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Saxpath_License
'''
