[license]

expression = "SCEA"
status = "approved"

text = '''
note it is listed here too: http://en.opensuse.org/openSUSE:Accepted_licences
and elsewhere
'''

[fedora]

name = [
    "SCEA Shared Source License"
]

abbreviation = [
    "SCEA"
]

notes = '''
http://research.scea.com/scea_shared_source_license.html
'''
