[license]

expression = "SISSL"
status = "approved"

[fedora]

name = [
    "Sun Industry Standards Source License"
]

abbreviation = [
    "SISSL"
]

notes = '''
http://www.openoffice.org/licenses/sissl_license.html
'''
