[license]

expression = "Sleepycat"
status = "approved"

[fedora]

name = [
    "Sleepycat Software Product License"
]

abbreviation = [
    "Sleepycat"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Sleepycat
'''
