[license]

expression = "SPL-1.0"
status = "approved"

[fedora]

name = [
    "Sun Public License"
]

abbreviation = [
    "SPL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Sun_Public_License
'''
