[license]

expression = "StandardML-NJ"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/MIT
'''

[fedora]

name = "Standard ML of New Jersey License"
abbreviation = "MIT"

notes = '''
https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Standard_ML_of_New
_Jersey_Variant  There are other versions of this license that are more generic
(http://www2.cs.tum.edu/projects/cup/) , without ""Lucent""; this license needs
to be templated for the usual variables.
'''
