[license]

expression = "SWL"
status = "approved"

[fedora]

name = [
    "Scheme Widget Library (SWL) Software License Agreement"
]

abbreviation = [
    "SWL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/SWL
'''
