[license]

expression = [ "TOSL" ]
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/TOSL
'''

[fedora]

name = [
    "Trusster Open Source License"
]

abbreviation = [
    "TOSL"
]

notes = '''
per Fedora, sleepycat like but one substantial difference
'''
