[license]

expression = "TOSL"
status = "approved"

text = '''
per Fedora, sleepycat like but one substantial difference
'''

[fedora]

name = [
    "Trusster Open Source License"
]

abbreviation = [
    "TOSL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/TOSL
'''
