[license]

expression = "Unicode-DFS-2015"
status = "approved"

[fedora]

name = [
    "Unicode License"
]

abbreviation = [
    "Unicode"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Unicode
'''
