[license]

expression = "UPL-1.0"
status = "approved"

[fedora]

name = [
    "Universal Permissive License"
]

abbreviation = [
    "UPL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/UPL
'''
