[license]

expression = "VOSTROM"
status = "approved"

[fedora]

name = [
    "VOSTROM Public License for Open Source"
]

abbreviation = [
    "VOSTROM"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/VOSTROM
'''
