[license]

expression = "VSL-1.0"
status = "approved"

[fedora]

name = [
    "Vovida Software License v. 1.0"
]

abbreviation = [
    "VSL"
]

notes = '''
http://opensource.org/licenses/vovidapl.php
'''
