[license]

expression = "W3C"
status = "approved"

[fedora]

name = [
    "W3C Software Notice and License"
]

abbreviation = [
    "W3C"
]

notes = '''
http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
'''
