[license]

expression = [ "W3C" ]
status = "approved"

text = '''
http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231
'''

[fedora]

name = [
    "W3C Software Notice and License"
]

abbreviation = [
    "W3C"
]
