[license]

expression = "Wsuipa"
status = "approved"

text = '''
part of TEX
'''

[fedora]

name = [
    "Wsuipa License"
]

abbreviation = [
    "Wsuipa"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Wsuipa
'''
