[license]

expression = "WTFPL"
status = "approved"

[fedora]

name = [
    "Do What The F*ck You Want To Public License"
]

abbreviation = [
    "WTFPL"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/WTFPL
'''
