[license]

expression = "WTFPL"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/WTFPL
'''

[fedora]

name = "Do What The F*ck You Want To Public License"
abbreviation = "WTFPL"
