[license]

expression = "WXwindows"
status = "approved"

text = '''
http://www.wxwidgets.org/manuals/stable/wx_wxlicense.html
'''

[fedora]

name = "wxWidgets Library License"
abbreviation = "wxWidgets"

notes = '''
see https://www.wxwidgets.org/about/licence/ - not sure time frame of this, but
says it's same as wxWindows webarchive for wxwidgets URL that Fedora has shows
wxWindows license going back to 2008, https://web.archive.org/web/20080425022039
/http://docs.wxwidgets.org/stable/wx_wxlicense.html seems to appear in Fedora,
see: https://src.fedoraproject.org/rpms/python-wxpython4/blob/rawhide/f/python-
wxpython4.spec - check for actual text to see if it is different or not This is
actually the *wxWindows* (not wxWidget) Library Licence, Version 3.1. The SPDX
list didn't retain the version number.
'''
