[license]

expression = "Xerox"
status = "approved"

text = '''
Currently identified by fossology as "Xerox"
'''

[fedora]

name = [
    "Xerox License"
]

abbreviation = [
    "Xerox"
]

notes = '''
https://fedoraproject.org/wiki/Licensing/Xerox
'''
