[license]

expression = [ "YPL-1.1" ]
status = "approved"

text = '''
http://www.zimbra.com/license/yahoo_public_license_1.1.html
'''

[fedora]

name = [
    "Yahoo Public License v 1.1"
]

abbreviation = [
    "YPLv1.1"
]
