[license]

expression = "zlib"
status = "approved"

text = '''
https://fedoraproject.org/wiki/Licensing/Teeworlds
'''

[fedora]

name = "Teeworlds License"
abbreviation = "Teeworlds"

notes = '''
Fedora page mentions additional 4th clause as option - is this variant found? if
so, then might need new entry in SPDX In its Free version (cf. fedora Wiki for
details), it is identical to the Zlib license.
'''
