#!/bin/bash

# SPDX-FileCopyrightText: 2024 Henrik Sandklef
#
# SPDX-License-Identifier: GPL-3.0-or-later

SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})/../
PYTHONPATH=${SCRIPT_DIR}/python ${SCRIPT_DIR}/python/flame/__main__.py $*
