// Specification:
// https://spdx.github.io/spdx-spec/SPDX-license-expressions/
// We use only subset of the full specification for now

start: license

license: license_item | left_parenthesis license right_parenthesis | license operator license

left_parenthesis: "("
right_parenthesis: ")"
operator: "OR"|"AND"|"or"|"and"

%import common.WS
%ignore WS

// license_item is generated and appended to this grammar by create-grammar.py
