[license]

expression = [ "LicenseRef-OpenData" ]
status = "approved-content"

[fedora]

name = [
    "Open Data License (GeoLite Country and GeoLite City databases)"
]

abbreviation = [
    "BSD with advertising"
]

notes = '''
This is similar to BSD-4-Clause, but removes reference to source and binary
forms.
'''
