-- SPDX-FileCopyrightText: 2025 Siemens AG
-- SPDX-FileCopyrightText: 2025 Dearsh Oberoi <oberoidearsh@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only

CREATE TABLE IF NOT EXISTS oidc_clients (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    add_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uni_oidc_clients_client_id UNIQUE (client_id),
    CONSTRAINT fk_oidc_clients_users FOREIGN KEY (user_id) REFERENCES users(id)
);