-- SPDX-FileCopyrightText: 2025 Siemens AG
-- SPDX-FileCopyrightText: 2025 Dearsh Oberoi <oberoidearsh@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only

BEGIN;

-- Introduce integer id column to serve as a potential primary key in the tables

ALTER TABLE users ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM users
)
UPDATE users u
SET int_id = n.rn
FROM numbered n
WHERE u.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('users', 'int_id'), (SELECT MAX(int_id) FROM users));

ALTER TABLE license_dbs ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM license_dbs
)
UPDATE license_dbs l
SET int_id = n.rn
FROM numbered n
WHERE l.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('license_dbs', 'int_id'), (SELECT MAX(int_id) FROM license_dbs));

ALTER TABLE obligation_types ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM obligation_types
)
UPDATE obligation_types ot
SET int_id = n.rn
FROM numbered n
WHERE ot.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('obligation_types', 'int_id'), (SELECT MAX(int_id) FROM obligation_types));

ALTER TABLE obligation_classifications ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM obligation_classifications
)
UPDATE obligation_classifications oc
SET int_id = n.rn
FROM numbered n
WHERE oc.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('obligation_classifications', 'int_id'), (SELECT MAX(int_id) FROM obligation_classifications));

ALTER TABLE obligations ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM obligations
)
UPDATE obligations o
SET int_id = n.rn
FROM numbered n
WHERE o.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('obligations', 'int_id'), (SELECT MAX(int_id) FROM obligations));

ALTER TABLE audits ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM audits
)
UPDATE audits a
SET int_id = n.rn
FROM numbered n
WHERE a.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('audits', 'int_id'), (SELECT MAX(int_id) FROM audits));

ALTER TABLE change_logs ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM  change_logs
)
UPDATE  change_logs c
SET int_id = n.rn
FROM numbered n
WHERE c.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('change_logs', 'int_id'), (SELECT MAX(int_id) FROM change_logs));

ALTER TABLE oidc_clients ADD COLUMN IF NOT EXISTS int_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH numbered AS (
  SELECT ctid, row_number() OVER () AS rn
  FROM oidc_clients
)
UPDATE oidc_clients oc
SET int_id = n.rn
FROM numbered n
WHERE oc.ctid = n.ctid;
SELECT setval(pg_get_serial_sequence('oidc_clients', 'int_id'), (SELECT MAX(int_id) FROM oidc_clients));

-- Introduce UUID column to serve as a potential foreign key in the tables

ALTER TABLE license_dbs ADD COLUMN IF NOT EXISTS user_int_id BIGINT;
UPDATE license_dbs SET user_int_id = (SELECT int_id from users WHERE license_dbs.user_id = users.id);
ALTER TABLE license_dbs ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE obligations ADD COLUMN IF NOT EXISTS obligation_classification_int_id BIGINT;
UPDATE obligations SET obligation_classification_int_id = (SELECT int_id from obligation_classifications 
WHERE obligations.obligation_classification_id = obligation_classifications.id);
ALTER TABLE obligations ALTER COLUMN obligation_classification_int_id SET NOT NULL;

ALTER TABLE obligations ADD COLUMN IF NOT EXISTS obligation_type_int_id BIGINT;
UPDATE obligations SET obligation_type_int_id = (SELECT int_id from obligation_types 
WHERE obligations.obligation_type_id = obligation_types.id);
ALTER TABLE obligations ALTER COLUMN obligation_type_int_id SET NOT NULL;

ALTER TABLE audits ADD COLUMN IF NOT EXISTS user_int_id BIGINT;
UPDATE audits SET user_int_id = (SELECT int_id FROM users WHERE audits.user_id = users.id);
ALTER TABLE audits ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE audits ADD COLUMN IF NOT EXISTS type_int_id BIGINT;
UPDATE audits
SET type_int_id = CASE
  WHEN type = 'LICENSE' THEN (SELECT int_id FROM license_dbs WHERE license_dbs.rf_id = audits.type_id)
  WHEN type = 'OBLIGATION' THEN (SELECT int_id FROM obligations WHERE obligations.id = audits.type_id)
  WHEN type = 'USER' THEN (SELECT int_id FROM users WHERE users.id = audits.type_id)
  WHEN type = 'TYPE' THEN (SELECT int_id FROM obligation_types WHERE obligation_types.id = audits.type_id)
  WHEN type = 'CLASSIFICATION' THEN (SELECT int_id FROM obligation_classifications WHERE obligation_classifications.id = audits.type_id)
END;
ALTER TABLE audits ALTER COLUMN type_int_id SET NOT NULL;

ALTER TABLE change_logs ADD COLUMN IF NOT EXISTS audit_int_id BIGINT;
UPDATE change_logs SET audit_int_id = (SELECT int_id from audits WHERE change_logs.audit_id = audits.id);
ALTER TABLE change_logs ALTER COLUMN audit_int_id SET NOT NULL;

ALTER TABLE obligation_licenses ADD COLUMN IF NOT EXISTS license_int_id BIGINT;
UPDATE obligation_licenses SET license_int_id = (SELECT int_id from license_dbs WHERE license_dbs.rf_id = obligation_licenses.license_db_id);
ALTER TABLE obligation_licenses ALTER COLUMN license_int_id SET NOT NULL;

ALTER TABLE obligation_licenses ADD COLUMN IF NOT EXISTS obligation_int_id BIGINT;
UPDATE obligation_licenses SET obligation_int_id = (SELECT int_id from obligations WHERE obligations.id = obligation_licenses.obligation_id);
ALTER TABLE obligation_licenses ALTER COLUMN obligation_int_id SET NOT NULL;

ALTER TABLE oidc_clients ADD COLUMN IF NOT EXISTS user_int_id BIGINT;
UPDATE oidc_clients SET user_int_id = (SELECT int_id from users WHERE oidc_clients.user_id = users.id);
ALTER TABLE oidc_clients ALTER COLUMN user_int_id SET NOT NULL;

-- Drop old unwanted columns, rename new ones to appropriate names

ALTER TABLE oidc_clients DROP COLUMN IF EXISTS user_id;
ALTER TABLE oidc_clients DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='oidc_clients' AND column_name='user_int_id') THEN
    ALTER TABLE oidc_clients RENAME COLUMN user_int_id TO user_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='oidc_clients' AND column_name='int_id') THEN
    ALTER TABLE oidc_clients RENAME COLUMN int_id TO id;
  END IF;
END$$;

ALTER TABLE obligation_licenses DROP COLUMN IF EXISTS license_db_id;
ALTER TABLE obligation_licenses DROP COLUMN IF EXISTS obligation_id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligation_licenses' AND column_name='license_int_id') THEN
    ALTER TABLE obligation_licenses RENAME COLUMN license_int_id TO license_db_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligation_licenses' AND column_name='obligation_int_id') THEN
    ALTER TABLE obligation_licenses RENAME COLUMN obligation_int_id TO obligation_id;
  END IF;
END$$;

ALTER TABLE change_logs DROP COLUMN IF EXISTS audit_id;
ALTER TABLE change_logs DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='change_logs' AND column_name='audit_int_id') THEN
    ALTER TABLE change_logs RENAME COLUMN audit_int_id TO audit_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='change_logs' AND column_name='int_id') THEN
    ALTER TABLE change_logs RENAME COLUMN int_id TO id;
  END IF;
END$$;

ALTER TABLE audits DROP COLUMN IF EXISTS type_id;
ALTER TABLE audits DROP COLUMN IF EXISTS user_id;
ALTER TABLE audits DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='audits' AND column_name='type_int_id') THEN
    ALTER TABLE audits RENAME COLUMN type_int_id TO type_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='audits' AND column_name='user_int_id') THEN
    ALTER TABLE audits RENAME COLUMN user_int_id TO user_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='audits' AND column_name='int_id') THEN
    ALTER TABLE audits RENAME COLUMN int_id TO id;
  END IF;
END$$;


ALTER TABLE obligations DROP COLUMN IF EXISTS id;
ALTER TABLE obligations DROP COLUMN IF EXISTS obligation_type_id;
ALTER TABLE obligations DROP COLUMN IF EXISTS obligation_classification_id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligations' AND column_name='int_id') THEN
    ALTER TABLE obligations RENAME COLUMN int_id TO id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligations' AND column_name='obligation_type_int_id') THEN
    ALTER TABLE obligations RENAME COLUMN obligation_type_int_id TO obligation_type_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligations' AND column_name='obligation_classification_int_id') THEN
    ALTER TABLE obligations RENAME COLUMN obligation_classification_int_id TO obligation_classification_id;
  END IF;
END$$;

ALTER TABLE obligation_classifications DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligation_classifications' AND column_name='int_id') THEN
    ALTER TABLE obligation_classifications RENAME COLUMN int_id TO id;
  END IF;
END$$;

ALTER TABLE obligation_types DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='obligation_types' AND column_name='int_id') THEN
    ALTER TABLE obligation_types RENAME COLUMN int_id TO id;
  END IF;
END$$;

ALTER TABLE license_dbs DROP COLUMN IF EXISTS rf_id;
ALTER TABLE license_dbs DROP COLUMN IF EXISTS user_id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='license_dbs' AND column_name='int_id') THEN
    ALTER TABLE license_dbs RENAME COLUMN int_id TO rf_id;
  END IF;
END$$;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='license_dbs' AND column_name='user_int_id') THEN
    ALTER TABLE license_dbs RENAME COLUMN user_int_id TO user_id;
  END IF;
END$$;

ALTER TABLE users DROP COLUMN IF EXISTS id;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='int_id') THEN
    ALTER TABLE users RENAME COLUMN int_id to id;
  END IF;
END$$;

-- Add primary key and foreign key constraints

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'users_pkey'
  ) THEN
    ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'license_dbs_pkey'
  ) THEN
    ALTER TABLE license_dbs ADD CONSTRAINT license_dbs_pkey PRIMARY KEY (rf_id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_license_dbs_user'
  ) THEN
    ALTER TABLE license_dbs ADD CONSTRAINT fk_license_dbs_user FOREIGN KEY (user_id) REFERENCES users(id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'obligation_classifications_pkey'
  ) THEN
    ALTER TABLE obligation_classifications ADD CONSTRAINT obligation_classifications_pkey PRIMARY KEY (id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'obligation_types_pkey'
  ) THEN
    ALTER TABLE obligation_types ADD CONSTRAINT obligation_types_pkey PRIMARY KEY (id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'obligations_pkey'
  ) THEN
    ALTER TABLE obligations ADD CONSTRAINT obligations_pkey PRIMARY KEY (id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_obligations_classification'
  ) THEN
    ALTER TABLE obligations ADD CONSTRAINT fk_obligations_classification FOREIGN KEY (obligation_classification_id) REFERENCES obligation_classifications(id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_obligations_type'
  ) THEN
    ALTER TABLE obligations ADD CONSTRAINT fk_obligations_type FOREIGN KEY (obligation_type_id) REFERENCES obligation_types(id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'audits_pkey'
  ) THEN
    ALTER TABLE audits ADD CONSTRAINT audits_pkey PRIMARY KEY (id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_audits_user'
  ) THEN
    ALTER TABLE audits ADD CONSTRAINT fk_audits_user FOREIGN KEY (user_id) REFERENCES users(id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'change_logs_pkey'
  ) THEN
    ALTER TABLE change_logs ADD CONSTRAINT change_logs_pkey PRIMARY KEY (id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='fk_audits_change_logs'
  ) THEN
    ALTER TABLE change_logs ADD CONSTRAINT fk_audits_change_logs FOREIGN KEY (audit_id) REFERENCES audits(id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='fk_obligation_licenses_obligation'
  ) THEN
    ALTER TABLE obligation_licenses ADD CONSTRAINT fk_obligation_licenses_obligation FOREIGN KEY (obligation_id) REFERENCES obligations(id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='fk_obligation_licenses_license_db'
  ) THEN
    ALTER TABLE obligation_licenses ADD CONSTRAINT fk_obligation_licenses_license_db FOREIGN KEY (license_db_id) REFERENCES license_dbs(rf_id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'obligation_licenses_pkey'
  ) THEN
    ALTER TABLE obligation_licenses 
      ADD CONSTRAINT obligation_licenses_pkey
      PRIMARY KEY (obligation_id, license_db_id);
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='oidc_clients_pkey'
  ) THEN
    ALTER TABLE oidc_clients ADD CONSTRAINT oidc_clients_pkey PRIMARY KEY (id);
  END IF;
END$$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='fk_oidc_clients_users'
  ) THEN
    ALTER TABLE oidc_clients ADD CONSTRAINT fk_oidc_clients_users FOREIGN KEY (user_id) REFERENCES users(id);
  END IF;
END$$;

-- Remove unique constraints

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname ='uq_license_dbs_shortname'
  ) THEN
    ALTER TABLE license_dbs ADD CONSTRAINT uq_license_dbs_shortname UNIQUE (rf_shortname);
  END IF;
END$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uni_obligations_topic'
    ) THEN
      ALTER TABLE obligations ADD CONSTRAINT uni_obligations_topic UNIQUE (topic);
    END IF;
END$$;

DROP EXTENSION IF EXISTS "uuid-ossp";

COMMIT;