-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only


-- create_users_table.sql

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    user_email TEXT NOT NULL,
    user_level TEXT NOT NULL,
    user_password TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT uni_users_user_name UNIQUE (user_name),
    CONSTRAINT uni_users_user_email UNIQUE (user_email)
);

