-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only

CREATE TABLE IF NOT EXISTS audits (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    timestamp TIMESTAMPTZ,
    type TEXT,
    type_id BIGINT,
    CONSTRAINT fk_audits_user FOREIGN KEY (user_id) REFERENCES users(id)
);