-- SPDX-FileCopyrightText: 2025 Chayan Das <01chayandas@gmail.com>
-- SPDX-License-Identifier: GPL-2.0-only


CREATE TABLE IF NOT EXISTS obligation_classifications (
    id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    classification TEXT NOT NULL UNIQUE,
    color TEXT NOT NULL UNIQUE,
    active BOOLEAN  NOT NULL DEFAULT TRUE
);
