name: Publish Docker image

# on:
#   release:
#     types: [published]
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build and push Image'
        run: |
          docker-build-and-run.sh "--build-only"
          docker tag "maxhbr/ldbcollector" "ghcr.io/maxhbr/ldbcollector:latest"
          docker push "ghcr.io/maxhbr/ldbcollector:latest"
