name: Cabal build

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #   with:
    #     submodules: true
   
    - name: submodule checkout (partially complete)
      run: |
        sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
        sed -i 's/git@gitlab.com:/https:\/\/gitlab.com\//g' .gitmodules
        git submodule sync --recursive || true
        git submodule update --init --recursive || true
        # git submodule update --init

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7' # Exact version of ghc to use
        # cabal-version: 'latest'. Omitted, but defaults to 'latest'
        enable-stack: false

    - run: cabal update
    - run: cabal build
    - run: cabal test
    - run: time cabal run -- write BSD-3-Clause
    - uses: actions/upload-artifact@v2
      with:
        name: out
        path: _out

