name: Nix build

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: submodule checkout (partially complete)
      run: |
        sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
        sed -i 's/git@gitlab.com:/https:\/\/gitlab.com\//g' .gitmodules
        git submodule sync --recursive || true
        git submodule update --init --recursive || true
        # git submodule update --init

    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: nix build .#

    - run: nix flake check

