[license]

expression = [ "GFDL-1.3-no-invariants-or-later" ]
status = "approved-documentation"

[fedora]

name = [
    "GNU Free Documentation License v1.3 or later - no invariants"
]

abbreviation = [
    "GFDL"
]
